---
title: "Experimentation Lesson 5: Multi-Armed Bandits, Explore vs Exploit"
catalog_blurb: "Shift traffic toward the winning variant while the campaign is still running."
description: "The explore-exploit dilemma from scratch: regret as the cost of learning, an epsilon-greedy bandit in base R, and when a bandit beats a fixed A/B split."
keywords: "multi-armed bandit, explore exploit tradeoff, epsilon-greedy, cumulative regret, adaptive traffic allocation, bandit vs A/B test, regret minimization, bandit algorithm in R, online experiments"
post_type: "LESSON"
curriculum_id: "6.170.5"
webr: true
mathjax: true
lesson_access: "pro"
course_id: "ds-experimentation"
course_title: "Experimentation"
course_lesson: "5"
course_total: "7"
course_landing: "R-Experimentation-Course.html"
course_next: "Thompson-Sampling-and-Bayesian-Bandits.html"
course_prev: "Cluster-and-Switchback-Experiments.html"
---

=== step === cover
::eyebrow Lesson 5 of 7
## Multi-Armed Bandits, Explore vs Exploit

Every design in this course so far splits traffic once and holds the split until the planned verdict. Lesson 4 closed on the question that strains against that discipline: if one arm is clearly winning halfway through, why keep sending half your users to the loser?

Here is the version of that question Meera faces this month. The shoe store's Diwali sale runs for three weeks, and the announcement email goes to all 40,000 loyalty members. Her copywriter drafted three subject lines, and somewhere among them hides the best open rate. Every email sent with a worse line forfeits opens forever: when the sale ends there is no later in which to cash in what a test learned.

A **multi-armed bandit** is the tool built for exactly this shape of problem. Instead of splitting evenly and deciding at the end, it moves traffic toward whatever is winning while the campaign is still running. The catch is a genuine dilemma, explore or exploit, and this lesson prices it with the yardstick that makes every strategy comparable: regret.

By the end of this lesson you will be able to:

- Map a live campaign onto the bandit setting: arms, rounds, rewards, and the explore/exploit dilemma between them
- Define cumulative regret and price any allocation plan with it, before real traffic pays the bill
- Implement epsilon-greedy in a dozen lines of base R, read its per-arm tallies, and explain its never-flattening regret curve
- Decide when a bandit beats a fixed A/B split, and when the fixed split is still the right tool

**Prerequisites:** Lessons 1 and 3 of this course ([Designing Experiments for Power](Designing-Experiments-for-Power.html), [Experiment Pitfalls, Peeking and SRM](Experiment-Pitfalls-Peeking-and-SRM.html)) for power, the simulate-it-first habit, and why adaptive looks at data are dangerous; [A/B Testing and Experiment Design](AB-Testing-and-Experiment-Design.html) for the fixed split this lesson challenges; and comfort writing a short base R loop ([Control Flow in R](Control-Flow-in-R.html)).

::widget bandit-explore {}

=== step === concept
::eyebrow The setting
## Three subject lines, one list

The name comes from casinos. A slot machine is a one-armed bandit: one lever, and it takes your money. Picture a row of three machines whose payout rates are printed nowhere. You learn a machine's rate only by feeding it coins, and every coin fed to a worse machine is winnings forgone. Playing that row well is the **multi-armed bandit problem**, and Meera's email campaign is one:

- An **arm** is a subject line. There are \(K = 3\): line A, "The Diwali sale is on"; line B, "40 percent off ends Friday"; line C, "Your size is going fast". Their true open rates are \(p_A = 0.30\), \(p_B = 0.50\), \(p_C = 0.55\). Meera never sees these numbers; we grant ourselves omniscience so we can score strategies exactly, the same move as Lesson 1's power simulations.
- A **round** is one send: at round \(t\), a strategy picks a line, one member gets one email.
- The **reward** is what comes back: 1 if that member opens within a day, 0 if not.

::widget process-flow {"steps":[{"title":"Pick a line","sub":"the strategy chooses which subject line the next member gets"},{"title":"Send one email","sub":"one member, one send: round t of the campaign"},{"title":"Observe the reward","sub":"opened within a day scores 1, ignored scores 0"},{"title":"Update the tally","sub":"that line gains a send and maybe an open, then round t plus 1 begins"}]}

Because the tallies update after every send, the strategy can change its mind mid-campaign. That is called **adaptive allocation**, and it is the exact opposite of the fixed designs from Lessons 1 to 4, where every allocation was decided before the first visitor arrived. Adaptivity sounds like a free upgrade until you sit where the strategy sits. Suppose 60 emails have gone out:

| Line | Sends so far | Opens | Observed rate | Truth (hidden) |
|---|---|---|---|---|
| A: The Diwali sale is on | 15 | 4 | 0.27 | 0.30 |
| B: 40 percent off ends Friday | 20 | 11 | 0.55 | 0.50 |
| C: Your size is going fast | 25 | 12 | 0.48 | 0.55 |

Who gets email number 61? B has the best observed rate, so sending B **exploits** what the tallies say. But C's 0.48 rests on just 25 sends of evidence, easily an unlucky streak hiding the truly best line, so sending C **explores** to firm up the estimate. Both answers are defensible, and that is the point: exploit too early and you can lock onto a false leader like B forever; explore too long and you keep paying for opens you already knew how to get. This tension is the **explore/exploit dilemma**, and everything else in this lesson is about paying it as little as possible.

=== step === concept
::eyebrow The yardstick
## Regret: what not knowing costs

To compare strategies you need a score, and the natural one is envy. An oracle who knew the rates would send all 40,000 emails with line C and expect 40,000 x 0.55 = 22,000 opens. No real strategy can match that, because learning that C is best requires sending some emails with A and B. **Regret** is the gap: the opens a strategy forgoes, relative to the oracle, because of every send it gave to a worse line.

Formally, write \(p^{*}\) for the best true rate (here 0.55) and \(a_t\) for the arm a strategy picks at round \(t\). After \(T\) rounds the **cumulative regret** is

\[ R_T \;=\; \sum_{t=1}^{T} \bigl( p^{*} - p_{a_t} \bigr) \;=\; \sum_{k=1}^{K} N_k(T)\,\Delta_k \]

Every symbol in words: \(p_{a_t}\) is the true rate of the line chosen at round \(t\), so each round adds the shortfall of that round's choice. The second form is the same sum bookkept by arm: \(N_k(T)\) is how many sends line \(k\) received, and \(\Delta_k = p^{*} - p_k\) (Delta) is line \(k\)'s **gap**, the opens one send to it forgoes. Regret is sends-to-worse-lines, weighted by how much worse.

The per-arm form makes any fixed plan priceable in one line of R. Price two: the lazy plan (split all 40,000 evenly, a third each) and the Lesson 1 plan (a 2,000-per-line test, then blast the remaining 34,000 with the crowned winner, assuming it correctly crowns C, so C ends with 2,000 + 34,000 = 36,000 sends):

```r
rates <- c(A = 0.30, B = 0.50, C = 0.55)   # the truth: hidden from Meera, known to our simulator
gaps  <- max(rates) - rates                # each line's gap Delta: opens forgone per send
gaps
#>    A    B    C
#> 0.25 0.05 0.00

c(even_split      = sum(rep(40000/3, 3) * gaps),
  test_then_blast = sum(c(2000, 2000, 36000) * gaps))
#>      even_split test_then_blast
#>            4000             600
```

The even split forgoes 4,000 opens, nearly a fifth of everything the oracle would earn. The test-then-blast plan pays 600, all of it during the test phase: 2,000 sends x 0.25 for A plus 2,000 x 0.05 for B, and nothing after, because the blast rides the best line. Deciding is what stops the meter.

[KEY INSIGHT]
Regret charges every send to a worse arm as it happens; the final verdict refunds nothing. And because it only needs the true rates and the allocation counts, you can price a strategy in a simulated world before any real traffic pays for it, the same habit Lesson 1 built for power.

=== step === concept
::eyebrow The dial
## The test you cannot size

If 600 opens buys a safe crowning, an obvious thought follows: shrink the test. At 200 sends per line the test phase costs only 60 opens. Run the crowning 2,000 times in simulation and see what that discount buys, at 200 per line and at 2,000:

```r
set.seed(42)
crown <- function(n) which.max(rbinom(3, n, rates))   # test n per line, crown the tally leader
wrong <- sapply(c(200, 2000), function(n) mean(replicate(2000, crown(n)) != 3))

data.frame(per_line    = c(200, 2000),
           test_regret = c(200, 2000) * sum(gaps),
           wrong_crown = wrong)
#>   per_line test_regret wrong_crown
#> 1      200          60       0.158
#> 2     2000         600       0.002
```

The `rbinom(3, n, rates)` line runs one honest test batch: one binomial open-count per line, each at its true rate. At 200 per line, the cheap test crowns the wrong line in 15.8% of campaigns, roughly one in six, and a wrong crowning is expensive: blasting the remaining 39,400 emails with line B pays its 0.05 gap on every one, about 1,970 opens. At 2,000 per line the crowning is nearly certain, but the test phase itself costs 600. Explore a little and risk the blast; explore a lot and pay up front. The dilemma from the last step, now with prices attached.

So how big should the test be? Lesson 1 already answered, and the answer bites its own tail: a reliable separation of B from C needs a sample that grows like \(1/\Delta^2\), one over the gap squared. The gap is exactly what nobody knows before testing. If B's true rate were 0.54 instead of 0.50, even 2,000 per line would crown the wrong line routinely. A fixed design must buy all of its exploration blind, in one purchase, sized by a number it cannot see.

[KEY INSIGHT]
There is no correct test size, because the right amount of exploration depends on gaps that are unknown until after the exploring. The bandit's move is to stop deciding once: re-decide after every send, and let the arriving tallies set how much exploration is still worth buying.

=== step === quiz
::eyebrow Check yourself
## A right answer is not a free one

Meera sends a first wave of 12,000 emails, 4,000 with each line, and at the end the tallies correctly crown C. What is the regret of that wave?

::quiz {"correct":2,"gate":true,"difficulty":"intermediate"}
- Zero: the wave crowned the right winner, so nothing was lost ::no Regret charges every send as it happens, not the verdict at the end. The 8,000 emails that went out with A and B forwent opens that no crowning can refund.
- About 1,200 opens: 4,000 sends times the 0.25 gap for A, plus 4,000 times the 0.05 gap for B ::ok Right: 1,000 + 200 = 1,200 opens forgone against the all-C oracle. A test that ends on the correct answer still pays full price for the learning, and regret is the meter that shows it.
- It cannot be computed, because regret depends on true open rates that Meera never learns ::no True in the live campaign, and that is exactly how the yardstick is meant to be used: build a simulated world with rates you chose, price each strategy there before launch, the same habit as the Lesson 1 power simulations.

=== step === concept
::eyebrow The simplest bandit
## Epsilon-greedy: mostly exploit, always peek

The simplest strategy that re-decides every round has one parameter and one trick. The parameter is \(\varepsilon\) (epsilon), the **exploration rate**. Before each send, flip a biased coin: with probability \(\varepsilon\), **explore**, sending a line chosen uniformly at random, tallies be damned; otherwise **exploit**, sending the line with the best observed rate so far. With \(\varepsilon = 0.10\), nine sends in ten go to the current leader and one in ten goes anywhere, which is what keeps a line like C from being written off on 25 unlucky sends: random exploration keeps re-testing it, and if it truly is best, its tally eventually says so and the exploiting nine-in-ten switch over.

\[ a_t \;=\; \begin{cases} \text{a line chosen uniformly at random} & \text{with probability } \varepsilon \\[3pt] \arg\max_k \; \hat{p}_k & \text{with probability } 1 - \varepsilon \end{cases} \]

Here \(\hat{p}_k = \text{opens}_k / \text{sends}_k\) is line \(k\)'s observed open rate, and \(\arg\max_k\) just means "the line whose \(\hat{p}_k\) is currently highest". The whole algorithm is a dozen lines of base R. One implementation detail to notice: untried lines would divide zero by zero, so the `ifelse()` scores them as a perfect 1.0, which guarantees each line gets tried early, an **optimistic start**. Run the first 400 sends of Meera's campaign:

```r
set.seed(42)
eps      <- 0.10    # the exploration rate: 1 send in 10 goes to a random line
n_rounds <- 400     # the first 400 sends of the campaign

opens <- c(A = 0, B = 0, C = 0)
sends <- c(A = 0, B = 0, C = 0)

for (t in 1:n_rounds) {
  explore <- runif(1) < eps
  pick    <- if (explore) sample(3, 1)
             else which.max(ifelse(sends > 0, opens / sends, 1))
  opens[pick] <- opens[pick] + rbinom(1, 1, rates[pick])
  sends[pick] <- sends[pick] + 1
}
rbind(sends, est_rate = round(opens / sends, 2))
#>              A     B      C
#> sends    50.00 31.00 319.00
#> est_rate  0.34  0.39   0.61
```

No crowning ceremony, yet 319 of 400 sends went to C, the truly best line. The learning happened mid-flight, and the bill shows it:

```r
sum(sends * gaps)   # the realized regret of these 400 sends
#> [1] 14.05
```

An even split of the same 400 sends expects a regret of 400 x 0.10 = 40 (0.10 is the average gap). Epsilon-greedy paid about a third of that while finding the same winner. But file away one wart from the tallies above: its estimate for B is 0.39 against a true 0.50. The algorithm mostly stopped sending B after an unlucky start, so B's tally never got the evidence to recover. Epsilon-greedy earned well and learned badly, and that trade returns two steps from now.

=== step === concept
::eyebrow Feel it
## Watch the regret accumulate

Cumulative regret makes a strategy's whole life visible as one curve: each send to a worse line adds that line's gap, so the curve climbs steeply while the strategy is still confused and flattens as it stops wasting sends. The interactive below replays Meera's exact three-line campaign for 400 rounds. Toggle the two strategies and read the endings.

::widget bandit-explore {}

Look closely at epsilon-greedy's late rounds: the curve never goes flat. It cannot, because exploration never turns off. Long after C is obvious, one send in ten is still random, and two thirds of those random sends go to lines A and B. That steady drip has a price you can compute directly, using the average gap across the three lines:

```r
eps * 40000 * mean(gaps)   # the exploration tax alone, across the full 40,000-send list
#> [1] 400
```

A 400-open tax on the full list, paid mostly on a question that was settled in the first few hundred sends, and it scales with every extra send forever. Statisticians call this **linear regret**: the total grows in a straight line with \(T\), roughly \(\varepsilon \bar{\Delta} T\), where \(\bar{\Delta}\) (Delta-bar) is the average gap. It is the signature of a strategy that explores at a fixed rate. The benchmark it misses is startling: Lai and Robbins proved in 1985 that the best possible strategies have regret growing only like the **logarithm** of \(T\), meaning each doubling of the campaign adds roughly a constant, so the curve bends ever flatter.

Epsilon-greedy's second flaw is that its exploration is blind. A random exploring send is as likely to go to line A, hopeless at a 0.25 gap with 50 sends of evidence, as to line B, where the only live question, B versus C, actually resides. Shrinking \(\varepsilon\) over time patches the first flaw, but the deeper fix answers both at once: explore each line in proportion to how uncertain you still are about it. Toggle Thompson sampling in the widget and watch its curve bend toward flat: once a line is clearly worse it almost stops getting pulls. Building that strategy is the next lesson.

=== step === tryit
::eyebrow Your turn
## Price the plan you would have run

Before this course reached bandits, Meera's playbook was the Lesson 1 plan: a fixed test of 2,000 sends per line, then blast the remaining 34,000 emails with the crowned winner. Price that plan's regret, assuming the crowning correctly picks C. Fill in the two blanks.

```r
# 40,000 members; true gaps below. Test 2,000 per line, then blast the rest with C.
gaps  <- c(0.25, 0.05, 0)      # A, B, C: each line's gap from the best rate
test  <- rep(____, 3)          # the test phase: sends to each of the three lines
blast <- c(0, 0, ____)         # the blast phase: the rest of the list, all to line C
sum((test + blast) * gaps)     # the plan's regret, in forgone opens
```
::check {"regex":"rep\\(\\s*2000\\s*,\\s*3\\s*\\)[\\s\\S]*c\\(\\s*0\\s*,\\s*0\\s*,\\s*34000\\s*\\)","gate":true,"difficulty":"intermediate","ok":"600 forgone opens, every one paid during the test phase, and that is the BEST case: it assumes the crowning picked C. Had it crowned B instead, the blast alone would add 34,000 x 0.05 = 1,700 more. Epsilon-greedy paid 14 on its first 400 sends and about a 400-open lifetime tax on this list; Thompson sampling, next lesson, pays less still.","no":"Two blanks: the test phase sends 2,000 to each line, rep(2000, 3), and the blast sends the remaining 40,000 - 6,000 = 34,000 all to line C, c(0, 0, 34000). Then every send pays its line's true gap."}
::solution
```r
gaps  <- c(0.25, 0.05, 0)
test  <- rep(2000, 3)
blast <- c(0, 0, 34000)
sum((test + blast) * gaps)
#> [1] 600
```

=== step === concept
::eyebrow The right tool
## When a bandit beats a fixed split

If bandits pay less regret, why did this course spend four lessons on fixed splits? Because the two tools answer different questions. A fixed A/B test is built to **learn**: it buys an unbiased estimate with honest uncertainty, so a decision can be made once and exploited long after the test ends. A bandit is built to **earn**: it maximizes payoff during the allocation itself and treats knowledge as a means, not the deliverable. Four questions separate the jobs:

::widget process-flow {"steps":[{"title":"How long will the winner be used?","sub":"years of exploitation favor the fixed test; a 3-week sale favors the bandit"},{"title":"How fast is the reward?","sub":"opens land in hours; a 30-day repeat purchase starves the update loop"},{"title":"Is the estimate the deliverable?","sub":"adaptive tallies are biased; finance-grade lifts need a fixed split"},{"title":"Do the rates drift?","sub":"a bandit samples arms in different weeks, so time mixes into the comparison"}]}

| Reach for the bandit | Keep the fixed split |
|---|---|
| The decision dies with the campaign: subject lines, headlines, promo banners | The winner ships for years: checkout flows, pricing, ranking algorithms |
| The reward lands fast: opens, clicks, same-session buys | The reward straggles in: repeat purchase, churn, revenue per user |
| Total payoff during the campaign is the deliverable | The lift estimate and its interval are the deliverable |
| Many cheap arms, most of them expendable | Few expensive arms, each worth measuring properly |

The right column hides three honest caveats, and you have already met the evidence for each. First, the horizon: Meera's one-page checkout from Lesson 1 will run for years, so the 600-open cost of a properly powered test is nothing next to the value of deciding it correctly, with a confidence interval finance can book. Second, drift: Lesson 4 showed delivery times swinging with the clock, and open rates have clocks too, weekends, paydays, festival week. A fixed split balances time across arms by construction; a bandit concentrates each arm's sends in different stretches of the campaign, so line C can "win" partly because the bandit happened to favor it during payday week. Third, bias: remember B's tally, 0.39 against a truth of 0.50. Adaptive sampling starves the arms it abandons, freezing their unlucky averages, so a lift read straight off bandit tallies overstates the winner's edge. Corrections exist, but the fixed split gets honesty for free.

[WARNING]
The most common real-world bandit failure is feeding the loop a reward it cannot wait for. An open arrives in hours; a return, a renewal, a repeat purchase arrives in weeks. A bandit given a fast proxy will optimize the proxy: a pushy subject line can win opens while annoying the very customers the sale needs, and the loop will happily steer all 40,000 emails by the signal it can see.

[KEY INSIGHT]
Put the value on a timeline. If most of it arrives AFTER the decision, run the fixed test, estimate honestly, decide once. If most of it arrives DURING the allocation, let a bandit earn while it learns.

=== step === quiz
::eyebrow Check yourself
## Which test stays fixed?

After this lesson, Meera's team wants to run bandits on everything. Which job should STAY a fixed-split A/B test?

::quiz {"correct":2,"gate":true,"difficulty":"intermediate"}
- Choosing tomorrow's flash-sale push-notification headline from 8 drafts ::no Perishable decision, many arms, a reward that lands in minutes: bandit country. An 8-arm fixed split would still be exploring when the flash sale ends, paying full regret on a verdict there is no time left to use.
- The one-page checkout from Lesson 1, a permanent ship decision where finance wants the lift and an honest confidence interval ::ok Right, on both grounds. The winner will be exploited for years, so the regret of one properly powered test is trivial next to deciding correctly, and only the fixed split hands over unbiased estimates: bandit tallies, like line B frozen at 0.39, are bent by adaptive sampling.
- Rotating five hero banners on the homepage for the rest of the three-week sale ::no Short horizon, instant clicks, and nobody needs a publishable lift estimate: exactly the shape where a bandit earns during the campaign. A fixed split would deliver its knowledge just in time for the sale to be over.

=== step === concept
::eyebrow Go deeper
## References

A few authoritative places to take this further:

- [Sutton and Barto (2018), Reinforcement Learning: An Introduction](http://incompleteideas.net/book/the-book-2nd.html) - chapter 2 is the canonical bandit introduction: epsilon-greedy, optimistic starts and upper-confidence bounds, free online.
- [Lattimore and Szepesvari (2020), Bandit Algorithms](https://banditalgs.com/) - the rigorous book on regret: why logarithmic growth is the floor and which algorithms reach it, free online.
- [Lai and Robbins (1985), Asymptotically Efficient Adaptive Allocation Rules](https://doi.org/10.1016/0196-8858(85)90002-8) - the classic paper behind this lesson's benchmark: no strategy can beat logarithmic regret, and strategies matching it exist.
- [Scott (2015), Multi-armed bandit experiments in the online service economy](https://research.google/pubs/multi-armed-bandit-experiments-in-the-online-service-economy/) - how Google ran bandits in production, and the practitioner bridge to Thompson sampling, next lesson.
- [Stucchio (2015), Do not use bandit algorithms](https://www.chrisstucchio.com/blog/2015/dont_use_bandits.html) - the sharpest case for staying with fixed splits: delayed rewards and drift, this lesson's caveats argued at full strength.

=== step === complete
## Lesson 5 complete

The impatient question from Lesson 4 now has a full answer. You named the dilemma every allocation faces, explore or exploit, and priced it in regret: 4,000 forgone opens for the even split, 600 for test-then-blast, and a test size that cannot be chosen honestly because it depends on gaps nobody has measured yet. Then you built the smallest strategy that re-decides after every send: epsilon-greedy found line C mid-flight in a dozen lines of base R, paying 14 opens on its first 400 sends where an even split of those same sends pays 40. And you drew the boundary that keeps both tools employed: a bandit earns while it learns, a fixed test learns so you can decide once, honestly, and exploit for years.

Epsilon-greedy left two complaints on the table. Its exploration is blind, treating hopeless line A the same as the genuinely open B-versus-C question, and it never stops, paying a linear tax long after the answer is settled, while the Lai-Robbins benchmark says regret can grow as slowly as a logarithm. The widget already showed you the strategy that fixes both: its curve bends flat because it explores each arm in proportion to how uncertain it still is, by sampling from a Beta posterior per arm, the exact machinery the Bayesian course built. Next: Thompson Sampling and Bayesian Bandits.
