---
title: "Volatility Modeling with ARCH and GARCH Lesson 6: Multivariate volatility and DCC-GARCH"
slug: "Multivariate-Volatility-DCC-GARCH"
description: "Fit a DCC-GARCH to DAX and FTSE returns in R: a GARCH per series, then a correlation that updates each day, and see what it does to a 50/50 portfolio."
keywords: "DCC-GARCH, multivariate GARCH, dynamic conditional correlation, time-varying correlation, rolling correlation, portfolio risk, dccPre, rmgarch, DAX, FTSE"
mathjax: true
webr: true
date: "2026-09-26"
post_type: "LESSON"
course_id: "ts-volatility"
course_title: "Volatility Modeling with ARCH and GARCH"
course_lesson: "6"
course_total: "6"
course_landing: "Volatility-Modeling-ARCH-and-GARCH-Course.html"
course_prev: "Forecasting-Volatility-and-Value-at-Risk.html"
course_next: ""
curriculum_id: "5.100.6"
lesson_access: "pro"
catalog_blurb: "How correlations between assets change over time, and what that does to portfolio risk."
---

=== step === cover
## Multivariate volatility and DCC-GARCH

Today let's learn how to measure the risk of holding two stock indices together when the correlation between them does not stay fixed.

Say you hold half of your money in the DAX, the German stock index, and half in the FTSE 100, the UK index. You want to know how risky one day of holding this 50/50 position is.

The data is `EuStockMarkets`, which comes with R. It has the daily closing prices of four European indices over 1,860 business days from 1991 to 1998: the DAX and the FTSE, plus the Swiss SMI and the French CAC. We work with daily returns, the change in the log price times 100, so a return of 1 means the index moved about 1 percent. That leaves 1,859 days of returns.

The grid below shows the correlation between the returns of each pair of indices, computed over all 1,859 days.

::widget correlation-heatmap {"vars":["DAX","SMI","CAC","FTSE"],"matrix":[[1,0.7031,0.7344,0.6395],[0.7031,1,0.616,0.5848],[0.7344,0.616,1,0.6486],[0.6395,0.5848,0.6486,1]]}

Each cell is one number for the whole period, and the DAX and FTSE cell reads 0.64. Is one number like that enough to describe the risk of holding both?

=== step === concept
## Why portfolio risk depends on the correlation

Risk here means the standard deviation of the portfolio's daily return, and that depends on more than how risky each index is on its own.

A 50/50 portfolio earns 0.5 times the DAX return plus 0.5 times the FTSE return each day. The formula below gives the variance of that sum for weights \(w_1\) and \(w_2\), standard deviations \(\sigma_1\) and \(\sigma_2\), and correlation \(\rho\).

\[ \sigma_p^2 = w_1^2\sigma_1^2 + w_2^2\sigma_2^2 + 2\,w_1 w_2\,\rho\,\sigma_1\sigma_2 \]

The first two terms are each index's own variance, scaled by its weight squared. The third is the cross term, and it is the only one that contains \(\rho\). If the two indices move together, the cross term is large and the portfolio is riskier. If they move in opposite directions, it is negative and cancels part of the other two.

First we compute the returns, the standard deviation of each index and their correlation.

```r
# Load the daily returns of the four indices and measure the DAX and FTSE standard deviations and correlation
r <- diff(log(EuStockMarkets)) * 100
x <- r[, c("DAX", "FTSE")]
s1 <- sd(x[, "DAX"])
s2 <- sd(x[, "FTSE"])
rho_full <- cor(x[, "DAX"], x[, "FTSE"])
round(c(DAX = s1, FTSE = s2, correlation = rho_full), 4)
#>         DAX        FTSE correlation
#>      1.0301      0.7958      0.6395
```

`diff(log(EuStockMarkets))` takes the change in the log price from one day to the next, and `* 100` puts it in percent. The DAX has a daily standard deviation of 1.0301 percent and the FTSE 0.7958. Their correlation is 0.6395, the same 0.64 as on the grid, to four decimals.

The block below splits the 50/50 portfolio's variance into its three terms at that correlation.

```r
# Split the 50/50 portfolio variance into its three terms at the full-sample correlation
w <- c(0.5, 0.5)
term_dax <- w[1]^2 * s1^2
term_ftse <- w[2]^2 * s2^2
term_cross <- 2 * w[1] * w[2] * rho_full * s1 * s2
port_var <- term_dax + term_ftse + term_cross
terms <- c(term_dax = term_dax, term_ftse = term_ftse, term_cross = term_cross,
           variance = port_var, sd = sqrt(port_var))
round(terms, 4)
#>   term_dax  term_ftse term_cross   variance         sd
#>     0.2653     0.1583     0.2621     0.6857     0.8281
```

The DAX term is 0.2653, the FTSE term 0.1583 and the cross term 0.2621. They add up to a variance of 0.6857, so the portfolio's standard deviation is 0.8281 percent.

The block below repeats the calculation at four values of the correlation and keeps everything else fixed.

```r
# Compute the portfolio standard deviation at four values of the correlation
rho_grid <- c(-0.5, 0, rho_full, 1)
grid_var <- w[1]^2 * s1^2 + w[2]^2 * s2^2 + 2 * w[1] * w[2] * rho_grid * s1 * s2
data.frame(rho = round(rho_grid, 4), portfolio_sd = round(sqrt(grid_var), 4))
#>       rho portfolio_sd
#> 1 -0.5000       0.4676
#> 2  0.0000       0.6508
#> 3  0.6395       0.8281
#> 4  1.0000       0.9129
# The weighted sum of the two standard deviations, the portfolio sd when the correlation is 1
round(sum(w * c(s1, s2)), 4)
#> [1] 0.9129
```

At a correlation of 1 the portfolio's standard deviation is 0.9129, which equals the weighted sum of the two standard deviations. That is the risk with no diversification at all. At the actual correlation of 0.6395 it is 0.8281, so diversification takes 0.0848 off the risk.

[KEY INSIGHT]
The portfolio's risk moves with the correlation, from 0.4676 at -0.5 to 0.9129 at 1. So a wrong correlation gives a wrong risk number.

That makes the correlation an input worth checking. Does it really stay at 0.6395 from one day to the next?

=== step === concept
## Rolling windows: does the correlation stay at 0.6395?

A rolling correlation computes the correlation over the most recent k days, then moves the window forward one day and computes it again. Repeating that gives one correlation per day, which we call the correlation path.

The block below writes this as a function and applies it to the DAX and FTSE returns with windows of 20, 60 and 250 days.

```r
# Compute the DAX and FTSE rolling correlation over windows of 20, 60 and 250 days
roll_cor <- function(x, k) {
  n <- nrow(x)
  out <- rep(NA_real_, n)
  for (day in k:n) {
    window_rows <- x[(day - k + 1):day, ]
    out[day] <- cor(window_rows[, 1], window_rows[, 2])
  }
  out
}
rc20 <- roll_cor(x, 20)
rc60 <- roll_cor(x, 60)
rc250 <- roll_cor(x, 250)
path_summary <- function(p) {
  c(min = min(p, na.rm = TRUE), max = max(p, na.rm = TRUE), sd = sd(p, na.rm = TRUE))
}
rolling <- rbind(`20 days` = path_summary(rc20),
                 `60 days` = path_summary(rc60),
                 `250 days` = path_summary(rc250))
round(rolling, 3)
#>             min   max    sd
#> 20 days  -0.199 0.931 0.193
#> 60 days   0.138 0.848 0.132
#> 250 days  0.420 0.749 0.079
```

The first days of each path have no value because the window is not full yet. The 20-day correlation ran from -0.199 to 0.931, the 60-day from 0.138 to 0.848 and the 250-day from 0.420 to 0.749.

So the window length is a trade. A short window reacts fast but rests on few days, so it is noisy, with a standard deviation of 0.193 for 20 days. A long window is stable, at 0.079 for 250 days, but it is slow to move when the correlation changes.

The plot below draws the three paths with a dashed line at the full-sample correlation of 0.6395.

```r
# Plot the three rolling correlations against the full-sample correlation
tt <- as.numeric(time(EuStockMarkets))[-1]
plot(tt, rc20, type = "l", col = "grey65", ylim = c(-0.3, 1),
     xlab = "Year", ylab = "Correlation of DAX and FTSE returns")
lines(tt, rc60, col = "#1f7a55", lwd = 2)
lines(tt, rc250, col = "#b04a52", lwd = 2)
abline(h = rho_full, lty = 2)
legend("bottomleft", legend = c("20 days", "60 days", "250 days"),
       col = c("grey65", "#1f7a55", "#b04a52"), lwd = 2, bty = "n")
```

All three paths swing above and below the dashed line, and the shorter the window, the wider the swings.

But a wide path alone does not show that the correlation changed. Even if the true correlation never moved, a correlation computed from only 60 days would still vary from window to window. That variation is sampling error. The block below builds 1,859 pairs of random draws with a correlation fixed at 0.6395 and takes the same 60-day rolling correlation.

```r
# Simulate 1,859 pairs with a constant correlation and take the same 60-day rolling correlation
set.seed(2024)
n <- nrow(x)
e1 <- rnorm(n)
e2 <- rho_full * e1 + sqrt(1 - rho_full^2) * rnorm(n)
sim <- cbind(e1, e2)
rc60_sim <- roll_cor(sim, 60)
round(path_summary(rc60_sim), 3)
#>   min   max    sd
#> 0.308 0.831 0.099
```

The series `e2` mixes `e1` with fresh noise in the proportions that give the two series a true correlation of 0.6395. With that correlation fixed, the 60-day path still ranges from 0.308 to 0.831, with a standard deviation of 0.099.

The real 60-day path ranged from 0.138 to 0.848, with a standard deviation of 0.132. That is wider, which points to some real change. But a rolling window cannot say how much of its range is change and how much is sampling noise, so we need a model of the correlation itself. DCC-GARCH is one, and it works in two stages.

=== step === concept
## Stage 1: a GARCH(1,1) for each series and the standardised residuals

DCC-GARCH splits the problem into two jobs: how volatile each index is, and how the two move together. Stage 1 does the first job by fitting a GARCH(1,1) to each series.

A GARCH(1,1) says the variance of a day's return depends on yesterday's data. It equals a constant, plus a fraction of yesterday's squared residual, plus a fraction of yesterday's variance.

\[ \sigma_t^2 = \omega + \alpha\,\varepsilon_{t-1}^2 + \beta\,\sigma_{t-1}^2 \]

Here \(\varepsilon_{t-1}\) is yesterday's residual, the return minus the mean return, and \(\sigma_t^2\) is the conditional variance, the variance of today's return given the data up to yesterday. The constants \(\omega\), \(\alpha\) and \(\beta\) are estimated from the data.

Once a series has its conditional standard deviation \(\sigma_t\), we divide each day's return minus the mean by that day's \(\sigma_t\). The result is the standardised residual \(z_t\). Each day's move is now measured in units of how volatile that day was expected to be, so what is left is how the two series move together.

The function `dccPre()` from the MTS package fits both GARCH models. The block below keeps the standardised residuals in `z` and the conditional standard deviations in `s`.

```r
# Fit a GARCH(1,1) to each series with dccPre and keep the standardised residuals and conditional sds
library(MTS)
pre <- dccPre(x, include.mean = TRUE, p = 0, cond.dist = "norm")
#> Sample mean of the returns:  0.06520417 0.04319851
#> Component:  1
#> Estimates:  0.047541 0.068418 0.887613
#> se.coef  :  0.012638 0.014777 0.023557
#> t-value  :  3.761619 4.629948 37.67999
#> Component:  2
#> Estimates:  0.008486 0.045013 0.942508
#> se.coef  :  0.004435 0.011834 0.017022
#> t-value  :  1.913331 3.803615 55.36856
z <- pre$sresi
s <- pre$marVol
colnames(z) <- colnames(x)
colnames(s) <- colnames(x)
```

In the call, `include.mean = TRUE` gives each series its own mean, `p = 0` adds no lagged returns to the mean equation, and `cond.dist = "norm"` uses normal errors. The Estimates line gives omega, alpha and beta in that order. Component 1 is the DAX, with omega 0.0475, alpha 0.0684 and beta 0.8876. Component 2 is the FTSE, with 0.0085, 0.0450 and 0.9425. In both series beta is large and alpha is small, so a day's conditional variance comes mainly from yesterday's conditional variance and only a little from yesterday's squared residual.

The block below checks the range of each conditional standard deviation, and the standard deviation and correlation of the standardised residuals.

```r
# Check the conditional standard deviations and the standardised residuals
cond_sd_range <- rbind(min = apply(s, 2, min), max = apply(s, 2, max))
round(cond_sd_range, 3)
#>       DAX  FTSE
#> min 0.703 0.538
#> max 2.732 1.561
round(apply(z, 2, sd), 4)
#>    DAX   FTSE
#> 0.9999 1.0001
round(c(returns = cor(x)[1, 2], standardised = cor(z)[1, 2]), 4)
#>      returns standardised
#>       0.6395       0.6222
```

The DAX conditional standard deviation runs from 0.703 to 2.732 and the FTSE's from 0.538 to 1.561, so how volatile a day is changes a lot over the period. Both standardised residual series have a standard deviation of 1 to three decimals.

Their correlation is 0.6222, lower than 0.6395 for the raw returns. The reason is that each day is now divided by its own conditional standard deviation, which puts the volatile days on the same scale as the calm ones.

The plot below shows the two conditional standard deviations over time.

```r
# Plot the conditional standard deviation of each series over time
matplot(tt, s, type = "l", lty = 1, col = c("#1f7a55", "#b04a52"),
        xlab = "Year", ylab = "Conditional standard deviation (percent)")
legend("topleft", legend = colnames(s), col = c("#1f7a55", "#b04a52"), lty = 1, bty = "n")
```

Both lines change over the period, and the DAX line reaches higher than the FTSE line.

=== step === concept
## Stage 2: how DCC updates the correlation each day

Stage 2 models the correlation of the standardised residuals. To connect it to risk, write the covariance matrix of the two returns on day \(t\) as \(\mathbf{H}_t\).

\[ \mathbf{H}_t = \mathbf{D}_t\,\mathbf{R}_t\,\mathbf{D}_t \]

\(\mathbf{D}_t\) is a diagonal matrix holding the two conditional standard deviations, and \(\mathbf{R}_t\) is the 2 by 2 correlation matrix with \(\rho_t\) off the diagonal. Stage 1 gave us \(\mathbf{D}_t\), so stage 2 has to give \(\rho_t\).

DCC builds \(\rho_t\) from a matrix \(\mathbf{Q}_t\) that is updated every day.

\[ \mathbf{Q}_t = (1 - \alpha - \beta)\,\bar{\mathbf{Q}} + \alpha\,\mathbf{z}_{t-1}\mathbf{z}_{t-1}^{\top} + \beta\,\mathbf{Q}_{t-1} \]

Read it as three parts:

- \(\bar{\mathbf{Q}}\) is the correlation matrix of all the standardised residuals, the long-run level. Its off-diagonal entry is 0.6222, and it gets weight \(1 - \alpha - \beta\).
- \(\mathbf{z}_{t-1}\mathbf{z}_{t-1}^{\top}\) is yesterday's co-movement, the two standardised residuals multiplied together. The product is positive when the series moved the same way and negative when they moved in opposite ways. It gets weight \(\alpha\).
- \(\mathbf{Q}_{t-1}\) is yesterday's Q, carried over with weight \(\beta\).

That is the same shape as the GARCH(1,1) equation: a long-run level, yesterday's shock and yesterday's own value.

Q itself is not a correlation matrix, because its diagonal entries drift away from 1. So each day we rescale its entries \(q_{11,t}\), \(q_{22,t}\) and \(q_{12,t}\) into a correlation.

\[ \rho_t = \frac{q_{12,t}}{\sqrt{q_{11,t}\,q_{22,t}}} \]

The recursion starts at \(\mathbf{Q}_1 = \bar{\mathbf{Q}}\), so \(\rho_1 = 0.6222\).

Let's do one update by hand. We do not have \(\alpha\) and \(\beta\) yet, since maximum likelihood estimates both in the next section, so the block uses trial values of 0.02 and 0.97. It first takes day 1's standardised residuals and their matrix of products.

```r
# Set the starting matrix Qbar and the shock from day 1, with trial values of alpha and beta
alpha_try <- 0.02
beta_try <- 0.97
Qbar <- cor(z)
z1 <- z[1, ]
shock <- z1 %o% z1
round(z1, 4)
#>     DAX    FTSE
#> -0.9686  0.7963
round(shock, 4)
#>          DAX    FTSE
#> DAX   0.9381 -0.7713
#> FTSE -0.7713  0.6342
```

On day 1 the DAX return was 0.9686 conditional standard deviations below its mean and the FTSE return was 0.7963 above. They moved in opposite directions, so the product in the off-diagonal is -0.7713.

The block below applies the update to get day 2, and reads the correlation before and after.

```r
# Update Q from day 1 to day 2 and read the correlation before and after
Q1 <- Qbar
Q2 <- (1 - alpha_try - beta_try) * Qbar + alpha_try * shock + beta_try * Q1
round(Q2, 4)
#>         DAX   FTSE
#> DAX  0.9988 0.5943
#> FTSE 0.5943 0.9927
rho1 <- Q1[1, 2] / sqrt(Q1[1, 1] * Q1[2, 2])
rho2 <- Q2[1, 2] / sqrt(Q2[1, 1] * Q2[2, 2])
round(c(rho1 = rho1, rho2 = rho2), 4)
#>   rho1   rho2
#> 0.6222 0.5969
```

The off-diagonal of Q fell to 0.5943 while the diagonal stayed near 1, so the correlation fell from 0.6222 to 0.5969. The day with opposite moves pulled it down. A day when both indices move the same way by similar amounts pushes it up.

=== step === concept
## Estimating alpha and beta by maximum likelihood

We now need real values for \(\alpha\) and \(\beta\). Maximum likelihood picks the values that make the observed standardised residuals most likely. This is the second step of a two-step estimation: stage 1 is already fitted, so `z` stays fixed and only \(\alpha\) and \(\beta\) are estimated.

For a given correlation path, each day's pair of standardised residuals is treated as a draw from a bivariate normal distribution with variances of 1 and correlation \(\rho_t\). Dropping the terms that do not depend on \(\rho_t\), the negative log-likelihood is the sum below, where \(z_{1t}\) and \(z_{2t}\) are the DAX and FTSE standardised residuals.

\[ \sum_{t=1}^{1859} \frac{1}{2}\left[\log(1-\rho_t^2) + \frac{z_{1t}^2 - 2\rho_t z_{1t} z_{2t} + z_{2t}^2}{1-\rho_t^2}\right] \]

Smaller is better, and \(\rho_t\) depends on \(\alpha\) and \(\beta\) through the recursion. The first block writes the recursion as the function `dcc_rho()` and the negative log-likelihood as `negll()`. `negll()` returns a very large number when \(\alpha\) or \(\beta\) is negative or their sum reaches 1, which keeps the search inside the values that make the recursion stable.

```r
# Define the DCC recursion that turns alpha and beta into a correlation path
dcc_rho <- function(z, alpha, beta) {
  n <- nrow(z)
  Qbar <- cor(z)
  Q <- Qbar
  rho <- numeric(n)
  rho[1] <- Q[1, 2] / sqrt(Q[1, 1] * Q[2, 2])
  for (day in 2:n) {
    z_prev <- z[day - 1, ]
    Q <- (1 - alpha - beta) * Qbar + alpha * (z_prev %o% z_prev) + beta * Q
    rho[day] <- Q[1, 2] / sqrt(Q[1, 1] * Q[2, 2])
  }
  rho
}
# Define the negative log-likelihood of z given a correlation path, and the version for alpha and beta
gauss_nll <- function(rho) {
  sum(0.5 * (log(1 - rho^2) + (z[, 1]^2 - 2 * rho * z[, 1] * z[, 2] + z[, 2]^2) / (1 - rho^2)))
}
negll <- function(par) {
  alpha <- par[1]
  beta <- par[2]
  if (alpha < 0 || beta < 0 || alpha + beta >= 1) return(1e10)
  gauss_nll(dcc_rho(z, alpha, beta))
}
```

The function `optim()` searches for the \(\alpha\) and \(\beta\) that minimise `negll()`, starting from 0.03 and 0.9.

```r
# Find alpha and beta by minimising the negative log-likelihood
fit <- optim(c(0.03, 0.9), negll, method = "Nelder-Mead")
alpha_hat <- fit$par[1]
beta_hat <- fit$par[2]
round(c(alpha = alpha_hat, beta = beta_hat, alpha_plus_beta = alpha_hat + beta_hat), 4)
#>           alpha            beta alpha_plus_beta
#>          0.0181          0.9742          0.9923
# Approximate number of days for a deviation of Q from Qbar to halve
round(log(0.5) / log(alpha_hat + beta_hat))
#> [1] 90
# Compare the fit with a constant correlation
rho_const <- cor(z)[1, 2]
nll_const <- gauss_nll(rep(rho_const, nrow(z)))
round(c(dcc = fit$value, constant = nll_const, gain = nll_const - fit$value), 2)
#>      dcc constant     gain
#>  1386.76  1402.94    16.18
```

Alpha is 0.0181 and beta is 0.9742. So each day's co-movement enters Q with a weight of 0.0181, and 97.42 percent of yesterday's Q carries over.

Alpha plus beta is 0.9923, close to 1, which means a deviation of Q from its long-run level fades slowly. On average the deviation shrinks by the factor alpha plus beta each day, so it halves after log(0.5) / log(0.9923) days, about 90. That figure is an approximation. The negative log-likelihood is 1386.76 for DCC against 1402.94 for a constant correlation of 0.6222, so the DCC fit is lower by 16.18.

Now we compute the fitted correlation path and summarise it.

```r
# Compute the fitted correlation path and summarise it
rho <- dcc_rho(z, alpha_hat, beta_hat)
rho_summary <- c(min = min(rho), median = median(rho), mean = mean(rho), max = max(rho), sd = sd(rho))
round(rho_summary, 3)
#>    min median   mean    max     sd
#>  0.319  0.631  0.618  0.754  0.078
```

The fitted correlation runs from 0.319 to 0.754, with a median of 0.631. The plot below draws the path against the constant correlation of 0.6222.

```r
# Plot the fitted correlation path against the constant correlation
plot(tt, rho, type = "l", col = "#1f7a55", lwd = 1.5, ylim = c(0.2, 0.9),
     xlab = "Year", ylab = "DCC correlation of DAX and FTSE")
abline(h = rho_const, lty = 2)
```

=== step === concept
## The same model in rugarch and rmgarch

In practice you would use the rmgarch package, which fits both stages in one call. It builds on rugarch, which describes the GARCH model of each series.

Neither package runs in the browser, so the block below is code to run on your own machine, shown with the output it gave us. It uses `x` and the path `rho` from the earlier blocks.

```r-static
# Fit the same DCC(1,1) model with rugarch and rmgarch (run this locally)
library(rugarch)
library(rmgarch)

uni_spec <- ugarchspec(
  variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
  mean.model = list(armaOrder = c(0, 0), include.mean = TRUE),
  distribution.model = "norm"
)
multi_spec <- multispec(replicate(2, uni_spec))
dcc_spec <- dccspec(multi_spec, dccOrder = c(1, 1), distribution = "mvnorm")
dcc_fit <- dccfit(dcc_spec, data = x)

round(coef(dcc_fit), 4)
#>      [DAX].mu   [DAX].omega  [DAX].alpha1   [DAX].beta1     [FTSE].mu
#>        0.0654        0.0476        0.0685        0.8876        0.0490
#>  [FTSE].omega [FTSE].alpha1  [FTSE].beta1  [Joint]dcca1  [Joint]dccb1
#>        0.0085        0.0450        0.9426        0.0184        0.9737
rho_rmgarch <- rcor(dcc_fit)[1, 2, ]
round(cor(rho_rmgarch, rho), 4)
#> [1] 0.9999
```

`ugarchspec()` describes the GARCH(1,1) for one series, with a constant mean and normal errors. `multispec()` repeats that description for each series. `dccspec()` adds the DCC part: `dccOrder = c(1, 1)` means one lag of the co-movement term and one lag of Q, and `distribution = "mvnorm"` means multivariate normal errors. `dccfit()` estimates both stages, and `rcor()` returns the fitted correlation matrix for every day.

The omega, alpha1 and beta1 entries of each series are within 0.0001 of the `dccPre()` estimates. The mu entries differ a little from the sample means because rugarch estimates the mean together with the variance, while `dccPre()` subtracts the sample mean.

The last two entries are the DCC parameters: `dcca1` is alpha, 0.0184 against our 0.0181, and `dccb1` is beta, 0.9737 against our 0.9742. The correlation between its path and the path from our base R code is 0.9999, so the two fits agree closely.

With k series there are k(k-1)/2 correlations, which is 6 for the four indices on the grid. DCC still uses one alpha and one beta shared by every pair.

=== step === widget
## The DCC path against the 60-day rolling correlation

Both paths estimate the correlation of the DAX and the FTSE. The widget below plots the DCC path and the 60-day rolling correlation for the same days, as points and as box plots.

To keep the page light, the widget shows every 5th day from day 60, which is 360 days for each path. Use the buttons to switch between the two views.

::widget chart-plotter {"data":[{"x":1991.727,"y":0.659,"fill":"DCC"},{"x":1991.746,"y":0.635,"fill":"DCC"},{"x":1991.765,"y":0.605,"fill":"DCC"},{"x":1991.785,"y":0.609,"fill":"DCC"},{"x":1991.804,"y":0.585,"fill":"DCC"},{"x":1991.823,"y":0.563,"fill":"DCC"},{"x":1991.842,"y":0.542,"fill":"DCC"},{"x":1991.862,"y":0.563,"fill":"DCC"},{"x":1991.881,"y":0.578,"fill":"DCC"},{"x":1991.9,"y":0.599,"fill":"DCC"},{"x":1991.919,"y":0.603,"fill":"DCC"},{"x":1991.938,"y":0.59,"fill":"DCC"},{"x":1991.958,"y":0.586,"fill":"DCC"},{"x":1991.977,"y":0.586,"fill":"DCC"},{"x":1991.996,"y":0.589,"fill":"DCC"},{"x":1992.015,"y":0.52,"fill":"DCC"},{"x":1992.035,"y":0.52,"fill":"DCC"},{"x":1992.054,"y":0.531,"fill":"DCC"},{"x":1992.073,"y":0.535,"fill":"DCC"},{"x":1992.092,"y":0.544,"fill":"DCC"},{"x":1992.112,"y":0.532,"fill":"DCC"},{"x":1992.131,"y":0.516,"fill":"DCC"},{"x":1992.15,"y":0.536,"fill":"DCC"},{"x":1992.169,"y":0.569,"fill":"DCC"},{"x":1992.188,"y":0.565,"fill":"DCC"},{"x":1992.208,"y":0.56,"fill":"DCC"},{"x":1992.227,"y":0.558,"fill":"DCC"},{"x":1992.246,"y":0.583,"fill":"DCC"},{"x":1992.265,"y":0.577,"fill":"DCC"},{"x":1992.285,"y":0.492,"fill":"DCC"},{"x":1992.304,"y":0.497,"fill":"DCC"},{"x":1992.323,"y":0.487,"fill":"DCC"},{"x":1992.342,"y":0.486,"fill":"DCC"},{"x":1992.362,"y":0.489,"fill":"DCC"},{"x":1992.381,"y":0.507,"fill":"DCC"},{"x":1992.4,"y":0.501,"fill":"DCC"},{"x":1992.419,"y":0.514,"fill":"DCC"},{"x":1992.438,"y":0.534,"fill":"DCC"},{"x":1992.458,"y":0.534,"fill":"DCC"},{"x":1992.477,"y":0.533,"fill":"DCC"},{"x":1992.496,"y":0.555,"fill":"DCC"},{"x":1992.515,"y":0.54,"fill":"DCC"},{"x":1992.535,"y":0.551,"fill":"DCC"},{"x":1992.554,"y":0.615,"fill":"DCC"},{"x":1992.573,"y":0.619,"fill":"DCC"},{"x":1992.592,"y":0.615,"fill":"DCC"},{"x":1992.612,"y":0.588,"fill":"DCC"},{"x":1992.631,"y":0.605,"fill":"DCC"},{"x":1992.65,"y":0.592,"fill":"DCC"},{"x":1992.669,"y":0.66,"fill":"DCC"},{"x":1992.688,"y":0.671,"fill":"DCC"},{"x":1992.708,"y":0.659,"fill":"DCC"},{"x":1992.727,"y":0.583,"fill":"DCC"},{"x":1992.746,"y":0.563,"fill":"DCC"},{"x":1992.765,"y":0.579,"fill":"DCC"},{"x":1992.785,"y":0.648,"fill":"DCC"},{"x":1992.804,"y":0.647,"fill":"DCC"},{"x":1992.823,"y":0.641,"fill":"DCC"},{"x":1992.842,"y":0.636,"fill":"DCC"},{"x":1992.862,"y":0.625,"fill":"DCC"},{"x":1992.881,"y":0.616,"fill":"DCC"},{"x":1992.9,"y":0.603,"fill":"DCC"},{"x":1992.919,"y":0.609,"fill":"DCC"},{"x":1992.938,"y":0.627,"fill":"DCC"},{"x":1992.958,"y":0.62,"fill":"DCC"},{"x":1992.977,"y":0.637,"fill":"DCC"},{"x":1992.996,"y":0.624,"fill":"DCC"},{"x":1993.015,"y":0.602,"fill":"DCC"},{"x":1993.035,"y":0.556,"fill":"DCC"},{"x":1993.054,"y":0.54,"fill":"DCC"},{"x":1993.073,"y":0.531,"fill":"DCC"},{"x":1993.092,"y":0.482,"fill":"DCC"},{"x":1993.112,"y":0.499,"fill":"DCC"},{"x":1993.131,"y":0.501,"fill":"DCC"},{"x":1993.15,"y":0.523,"fill":"DCC"},{"x":1993.169,"y":0.556,"fill":"DCC"},{"x":1993.188,"y":0.519,"fill":"DCC"},{"x":1993.208,"y":0.556,"fill":"DCC"},{"x":1993.227,"y":0.544,"fill":"DCC"},{"x":1993.246,"y":0.574,"fill":"DCC"},{"x":1993.265,"y":0.557,"fill":"DCC"},{"x":1993.285,"y":0.54,"fill":"DCC"},{"x":1993.304,"y":0.543,"fill":"DCC"},{"x":1993.323,"y":0.535,"fill":"DCC"},{"x":1993.342,"y":0.547,"fill":"DCC"},{"x":1993.362,"y":0.522,"fill":"DCC"},{"x":1993.381,"y":0.539,"fill":"DCC"},{"x":1993.4,"y":0.553,"fill":"DCC"},{"x":1993.419,"y":0.546,"fill":"DCC"},{"x":1993.438,"y":0.51,"fill":"DCC"},{"x":1993.458,"y":0.539,"fill":"DCC"},{"x":1993.477,"y":0.537,"fill":"DCC"},{"x":1993.496,"y":0.541,"fill":"DCC"},{"x":1993.515,"y":0.531,"fill":"DCC"},{"x":1993.535,"y":0.409,"fill":"DCC"},{"x":1993.554,"y":0.396,"fill":"DCC"},{"x":1993.573,"y":0.417,"fill":"DCC"},{"x":1993.592,"y":0.336,"fill":"DCC"},{"x":1993.612,"y":0.33,"fill":"DCC"},{"x":1993.631,"y":0.374,"fill":"DCC"},{"x":1993.65,"y":0.395,"fill":"DCC"},{"x":1993.669,"y":0.421,"fill":"DCC"},{"x":1993.688,"y":0.429,"fill":"DCC"},{"x":1993.708,"y":0.455,"fill":"DCC"},{"x":1993.727,"y":0.47,"fill":"DCC"},{"x":1993.746,"y":0.43,"fill":"DCC"},{"x":1993.765,"y":0.455,"fill":"DCC"},{"x":1993.785,"y":0.506,"fill":"DCC"},{"x":1993.804,"y":0.541,"fill":"DCC"},{"x":1993.823,"y":0.528,"fill":"DCC"},{"x":1993.842,"y":0.552,"fill":"DCC"},{"x":1993.862,"y":0.617,"fill":"DCC"},{"x":1993.881,"y":0.617,"fill":"DCC"},{"x":1993.9,"y":0.59,"fill":"DCC"},{"x":1993.919,"y":0.616,"fill":"DCC"},{"x":1993.938,"y":0.624,"fill":"DCC"},{"x":1993.958,"y":0.639,"fill":"DCC"},{"x":1993.977,"y":0.625,"fill":"DCC"},{"x":1993.996,"y":0.636,"fill":"DCC"},{"x":1994.015,"y":0.532,"fill":"DCC"},{"x":1994.035,"y":0.516,"fill":"DCC"},{"x":1994.054,"y":0.54,"fill":"DCC"},{"x":1994.073,"y":0.501,"fill":"DCC"},{"x":1994.092,"y":0.49,"fill":"DCC"},{"x":1994.112,"y":0.518,"fill":"DCC"},{"x":1994.131,"y":0.546,"fill":"DCC"},{"x":1994.15,"y":0.572,"fill":"DCC"},{"x":1994.169,"y":0.624,"fill":"DCC"},{"x":1994.188,"y":0.656,"fill":"DCC"},{"x":1994.208,"y":0.656,"fill":"DCC"},{"x":1994.227,"y":0.666,"fill":"DCC"},{"x":1994.246,"y":0.631,"fill":"DCC"},{"x":1994.265,"y":0.629,"fill":"DCC"},{"x":1994.285,"y":0.633,"fill":"DCC"},{"x":1994.304,"y":0.633,"fill":"DCC"},{"x":1994.323,"y":0.62,"fill":"DCC"},{"x":1994.342,"y":0.631,"fill":"DCC"},{"x":1994.362,"y":0.628,"fill":"DCC"},{"x":1994.381,"y":0.623,"fill":"DCC"},{"x":1994.4,"y":0.606,"fill":"DCC"},{"x":1994.419,"y":0.667,"fill":"DCC"},{"x":1994.438,"y":0.658,"fill":"DCC"},{"x":1994.458,"y":0.653,"fill":"DCC"},{"x":1994.477,"y":0.664,"fill":"DCC"},{"x":1994.496,"y":0.675,"fill":"DCC"},{"x":1994.515,"y":0.677,"fill":"DCC"},{"x":1994.535,"y":0.677,"fill":"DCC"},{"x":1994.554,"y":0.68,"fill":"DCC"},{"x":1994.573,"y":0.682,"fill":"DCC"},{"x":1994.592,"y":0.674,"fill":"DCC"},{"x":1994.612,"y":0.693,"fill":"DCC"},{"x":1994.631,"y":0.67,"fill":"DCC"},{"x":1994.65,"y":0.66,"fill":"DCC"},{"x":1994.669,"y":0.684,"fill":"DCC"},{"x":1994.688,"y":0.684,"fill":"DCC"},{"x":1994.708,"y":0.649,"fill":"DCC"},{"x":1994.727,"y":0.69,"fill":"DCC"},{"x":1994.746,"y":0.69,"fill":"DCC"},{"x":1994.765,"y":0.695,"fill":"DCC"},{"x":1994.785,"y":0.689,"fill":"DCC"},{"x":1994.804,"y":0.675,"fill":"DCC"},{"x":1994.823,"y":0.678,"fill":"DCC"},{"x":1994.842,"y":0.697,"fill":"DCC"},{"x":1994.862,"y":0.694,"fill":"DCC"},{"x":1994.881,"y":0.713,"fill":"DCC"},{"x":1994.9,"y":0.718,"fill":"DCC"},{"x":1994.919,"y":0.735,"fill":"DCC"},{"x":1994.938,"y":0.713,"fill":"DCC"},{"x":1994.958,"y":0.721,"fill":"DCC"},{"x":1994.977,"y":0.724,"fill":"DCC"},{"x":1994.996,"y":0.716,"fill":"DCC"},{"x":1995.015,"y":0.693,"fill":"DCC"},{"x":1995.035,"y":0.677,"fill":"DCC"},{"x":1995.054,"y":0.672,"fill":"DCC"},{"x":1995.073,"y":0.7,"fill":"DCC"},{"x":1995.092,"y":0.71,"fill":"DCC"},{"x":1995.112,"y":0.701,"fill":"DCC"},{"x":1995.131,"y":0.708,"fill":"DCC"},{"x":1995.15,"y":0.701,"fill":"DCC"},{"x":1995.169,"y":0.72,"fill":"DCC"},{"x":1995.188,"y":0.735,"fill":"DCC"},{"x":1995.208,"y":0.717,"fill":"DCC"},{"x":1995.227,"y":0.712,"fill":"DCC"},{"x":1995.246,"y":0.677,"fill":"DCC"},{"x":1995.265,"y":0.707,"fill":"DCC"},{"x":1995.285,"y":0.711,"fill":"DCC"},{"x":1995.304,"y":0.706,"fill":"DCC"},{"x":1995.323,"y":0.715,"fill":"DCC"},{"x":1995.342,"y":0.698,"fill":"DCC"},{"x":1995.362,"y":0.701,"fill":"DCC"},{"x":1995.381,"y":0.692,"fill":"DCC"},{"x":1995.4,"y":0.676,"fill":"DCC"},{"x":1995.419,"y":0.688,"fill":"DCC"},{"x":1995.438,"y":0.687,"fill":"DCC"},{"x":1995.458,"y":0.682,"fill":"DCC"},{"x":1995.477,"y":0.669,"fill":"DCC"},{"x":1995.496,"y":0.646,"fill":"DCC"},{"x":1995.515,"y":0.607,"fill":"DCC"},{"x":1995.535,"y":0.661,"fill":"DCC"},{"x":1995.554,"y":0.646,"fill":"DCC"},{"x":1995.573,"y":0.642,"fill":"DCC"},{"x":1995.592,"y":0.621,"fill":"DCC"},{"x":1995.612,"y":0.656,"fill":"DCC"},{"x":1995.631,"y":0.653,"fill":"DCC"},{"x":1995.65,"y":0.652,"fill":"DCC"},{"x":1995.669,"y":0.638,"fill":"DCC"},{"x":1995.688,"y":0.635,"fill":"DCC"},{"x":1995.708,"y":0.627,"fill":"DCC"},{"x":1995.727,"y":0.648,"fill":"DCC"},{"x":1995.746,"y":0.668,"fill":"DCC"},{"x":1995.765,"y":0.686,"fill":"DCC"},{"x":1995.785,"y":0.681,"fill":"DCC"},{"x":1995.804,"y":0.689,"fill":"DCC"},{"x":1995.823,"y":0.697,"fill":"DCC"},{"x":1995.842,"y":0.692,"fill":"DCC"},{"x":1995.862,"y":0.679,"fill":"DCC"},{"x":1995.881,"y":0.675,"fill":"DCC"},{"x":1995.9,"y":0.646,"fill":"DCC"},{"x":1995.919,"y":0.61,"fill":"DCC"},{"x":1995.938,"y":0.616,"fill":"DCC"},{"x":1995.958,"y":0.599,"fill":"DCC"},{"x":1995.977,"y":0.585,"fill":"DCC"},{"x":1995.996,"y":0.645,"fill":"DCC"},{"x":1996.015,"y":0.623,"fill":"DCC"},{"x":1996.035,"y":0.583,"fill":"DCC"},{"x":1996.054,"y":0.576,"fill":"DCC"},{"x":1996.073,"y":0.585,"fill":"DCC"},{"x":1996.092,"y":0.577,"fill":"DCC"},{"x":1996.112,"y":0.538,"fill":"DCC"},{"x":1996.131,"y":0.566,"fill":"DCC"},{"x":1996.15,"y":0.548,"fill":"DCC"},{"x":1996.169,"y":0.571,"fill":"DCC"},{"x":1996.188,"y":0.579,"fill":"DCC"},{"x":1996.208,"y":0.594,"fill":"DCC"},{"x":1996.227,"y":0.557,"fill":"DCC"},{"x":1996.246,"y":0.547,"fill":"DCC"},{"x":1996.265,"y":0.478,"fill":"DCC"},{"x":1996.285,"y":0.489,"fill":"DCC"},{"x":1996.304,"y":0.516,"fill":"DCC"},{"x":1996.323,"y":0.536,"fill":"DCC"},{"x":1996.342,"y":0.535,"fill":"DCC"},{"x":1996.362,"y":0.55,"fill":"DCC"},{"x":1996.381,"y":0.558,"fill":"DCC"},{"x":1996.4,"y":0.573,"fill":"DCC"},{"x":1996.419,"y":0.587,"fill":"DCC"},{"x":1996.438,"y":0.58,"fill":"DCC"},{"x":1996.458,"y":0.591,"fill":"DCC"},{"x":1996.477,"y":0.603,"fill":"DCC"},{"x":1996.496,"y":0.601,"fill":"DCC"},{"x":1996.515,"y":0.554,"fill":"DCC"},{"x":1996.535,"y":0.559,"fill":"DCC"},{"x":1996.554,"y":0.577,"fill":"DCC"},{"x":1996.573,"y":0.656,"fill":"DCC"},{"x":1996.592,"y":0.679,"fill":"DCC"},{"x":1996.612,"y":0.692,"fill":"DCC"},{"x":1996.631,"y":0.687,"fill":"DCC"},{"x":1996.65,"y":0.697,"fill":"DCC"},{"x":1996.669,"y":0.692,"fill":"DCC"},{"x":1996.688,"y":0.679,"fill":"DCC"},{"x":1996.708,"y":0.672,"fill":"DCC"},{"x":1996.727,"y":0.687,"fill":"DCC"},{"x":1996.746,"y":0.667,"fill":"DCC"},{"x":1996.765,"y":0.656,"fill":"DCC"},{"x":1996.785,"y":0.64,"fill":"DCC"},{"x":1996.804,"y":0.645,"fill":"DCC"},{"x":1996.823,"y":0.657,"fill":"DCC"},{"x":1996.842,"y":0.658,"fill":"DCC"},{"x":1996.862,"y":0.664,"fill":"DCC"},{"x":1996.881,"y":0.618,"fill":"DCC"},{"x":1996.9,"y":0.621,"fill":"DCC"},{"x":1996.919,"y":0.568,"fill":"DCC"},{"x":1996.938,"y":0.574,"fill":"DCC"},{"x":1996.958,"y":0.648,"fill":"DCC"},{"x":1996.977,"y":0.682,"fill":"DCC"},{"x":1996.996,"y":0.677,"fill":"DCC"},{"x":1997.015,"y":0.671,"fill":"DCC"},{"x":1997.035,"y":0.715,"fill":"DCC"},{"x":1997.054,"y":0.707,"fill":"DCC"},{"x":1997.073,"y":0.715,"fill":"DCC"},{"x":1997.092,"y":0.682,"fill":"DCC"},{"x":1997.112,"y":0.691,"fill":"DCC"},{"x":1997.131,"y":0.674,"fill":"DCC"},{"x":1997.15,"y":0.663,"fill":"DCC"},{"x":1997.169,"y":0.624,"fill":"DCC"},{"x":1997.188,"y":0.611,"fill":"DCC"},{"x":1997.208,"y":0.649,"fill":"DCC"},{"x":1997.227,"y":0.663,"fill":"DCC"},{"x":1997.246,"y":0.685,"fill":"DCC"},{"x":1997.265,"y":0.678,"fill":"DCC"},{"x":1997.285,"y":0.702,"fill":"DCC"},{"x":1997.304,"y":0.702,"fill":"DCC"},{"x":1997.323,"y":0.703,"fill":"DCC"},{"x":1997.342,"y":0.684,"fill":"DCC"},{"x":1997.362,"y":0.688,"fill":"DCC"},{"x":1997.381,"y":0.577,"fill":"DCC"},{"x":1997.4,"y":0.57,"fill":"DCC"},{"x":1997.419,"y":0.578,"fill":"DCC"},{"x":1997.438,"y":0.594,"fill":"DCC"},{"x":1997.458,"y":0.525,"fill":"DCC"},{"x":1997.477,"y":0.503,"fill":"DCC"},{"x":1997.496,"y":0.477,"fill":"DCC"},{"x":1997.515,"y":0.504,"fill":"DCC"},{"x":1997.535,"y":0.581,"fill":"DCC"},{"x":1997.554,"y":0.553,"fill":"DCC"},{"x":1997.573,"y":0.601,"fill":"DCC"},{"x":1997.592,"y":0.574,"fill":"DCC"},{"x":1997.612,"y":0.584,"fill":"DCC"},{"x":1997.631,"y":0.607,"fill":"DCC"},{"x":1997.65,"y":0.663,"fill":"DCC"},{"x":1997.669,"y":0.683,"fill":"DCC"},{"x":1997.688,"y":0.682,"fill":"DCC"},{"x":1997.708,"y":0.688,"fill":"DCC"},{"x":1997.727,"y":0.687,"fill":"DCC"},{"x":1997.746,"y":0.697,"fill":"DCC"},{"x":1997.765,"y":0.657,"fill":"DCC"},{"x":1997.785,"y":0.664,"fill":"DCC"},{"x":1997.804,"y":0.655,"fill":"DCC"},{"x":1997.823,"y":0.649,"fill":"DCC"},{"x":1997.842,"y":0.672,"fill":"DCC"},{"x":1997.862,"y":0.705,"fill":"DCC"},{"x":1997.881,"y":0.713,"fill":"DCC"},{"x":1997.9,"y":0.703,"fill":"DCC"},{"x":1997.919,"y":0.711,"fill":"DCC"},{"x":1997.938,"y":0.704,"fill":"DCC"},{"x":1997.958,"y":0.711,"fill":"DCC"},{"x":1997.977,"y":0.722,"fill":"DCC"},{"x":1997.996,"y":0.723,"fill":"DCC"},{"x":1998.015,"y":0.71,"fill":"DCC"},{"x":1998.035,"y":0.716,"fill":"DCC"},{"x":1998.054,"y":0.709,"fill":"DCC"},{"x":1998.073,"y":0.714,"fill":"DCC"},{"x":1998.092,"y":0.696,"fill":"DCC"},{"x":1998.112,"y":0.707,"fill":"DCC"},{"x":1998.131,"y":0.717,"fill":"DCC"},{"x":1998.15,"y":0.719,"fill":"DCC"},{"x":1998.169,"y":0.726,"fill":"DCC"},{"x":1998.188,"y":0.729,"fill":"DCC"},{"x":1998.208,"y":0.753,"fill":"DCC"},{"x":1998.227,"y":0.744,"fill":"DCC"},{"x":1998.246,"y":0.645,"fill":"DCC"},{"x":1998.265,"y":0.653,"fill":"DCC"},{"x":1998.285,"y":0.647,"fill":"DCC"},{"x":1998.304,"y":0.66,"fill":"DCC"},{"x":1998.323,"y":0.621,"fill":"DCC"},{"x":1998.342,"y":0.631,"fill":"DCC"},{"x":1998.362,"y":0.686,"fill":"DCC"},{"x":1998.381,"y":0.681,"fill":"DCC"},{"x":1998.4,"y":0.673,"fill":"DCC"},{"x":1998.419,"y":0.683,"fill":"DCC"},{"x":1998.438,"y":0.7,"fill":"DCC"},{"x":1998.458,"y":0.716,"fill":"DCC"},{"x":1998.477,"y":0.68,"fill":"DCC"},{"x":1998.496,"y":0.699,"fill":"DCC"},{"x":1998.515,"y":0.704,"fill":"DCC"},{"x":1998.535,"y":0.705,"fill":"DCC"},{"x":1998.554,"y":0.696,"fill":"DCC"},{"x":1998.573,"y":0.699,"fill":"DCC"},{"x":1998.592,"y":0.709,"fill":"DCC"},{"x":1998.612,"y":0.692,"fill":"DCC"},{"x":1998.631,"y":0.715,"fill":"DCC"},{"x":1991.727,"y":0.69,"fill":"60-day rolling"},{"x":1991.746,"y":0.686,"fill":"60-day rolling"},{"x":1991.765,"y":0.697,"fill":"60-day rolling"},{"x":1991.785,"y":0.708,"fill":"60-day rolling"},{"x":1991.804,"y":0.695,"fill":"60-day rolling"},{"x":1991.823,"y":0.675,"fill":"60-day rolling"},{"x":1991.842,"y":0.67,"fill":"60-day rolling"},{"x":1991.862,"y":0.532,"fill":"60-day rolling"},{"x":1991.881,"y":0.482,"fill":"60-day rolling"},{"x":1991.9,"y":0.473,"fill":"60-day rolling"},{"x":1991.919,"y":0.485,"fill":"60-day rolling"},{"x":1991.938,"y":0.475,"fill":"60-day rolling"},{"x":1991.958,"y":0.522,"fill":"60-day rolling"},{"x":1991.977,"y":0.558,"fill":"60-day rolling"},{"x":1991.996,"y":0.557,"fill":"60-day rolling"},{"x":1992.015,"y":0.492,"fill":"60-day rolling"},{"x":1992.035,"y":0.531,"fill":"60-day rolling"},{"x":1992.054,"y":0.536,"fill":"60-day rolling"},{"x":1992.073,"y":0.557,"fill":"60-day rolling"},{"x":1992.092,"y":0.535,"fill":"60-day rolling"},{"x":1992.112,"y":0.455,"fill":"60-day rolling"},{"x":1992.131,"y":0.457,"fill":"60-day rolling"},{"x":1992.15,"y":0.449,"fill":"60-day rolling"},{"x":1992.169,"y":0.468,"fill":"60-day rolling"},{"x":1992.188,"y":0.457,"fill":"60-day rolling"},{"x":1992.208,"y":0.462,"fill":"60-day rolling"},{"x":1992.227,"y":0.475,"fill":"60-day rolling"},{"x":1992.246,"y":0.592,"fill":"60-day rolling"},{"x":1992.265,"y":0.615,"fill":"60-day rolling"},{"x":1992.285,"y":0.475,"fill":"60-day rolling"},{"x":1992.304,"y":0.467,"fill":"60-day rolling"},{"x":1992.323,"y":0.451,"fill":"60-day rolling"},{"x":1992.342,"y":0.469,"fill":"60-day rolling"},{"x":1992.362,"y":0.466,"fill":"60-day rolling"},{"x":1992.381,"y":0.461,"fill":"60-day rolling"},{"x":1992.4,"y":0.452,"fill":"60-day rolling"},{"x":1992.419,"y":0.46,"fill":"60-day rolling"},{"x":1992.438,"y":0.451,"fill":"60-day rolling"},{"x":1992.458,"y":0.449,"fill":"60-day rolling"},{"x":1992.477,"y":0.447,"fill":"60-day rolling"},{"x":1992.496,"y":0.453,"fill":"60-day rolling"},{"x":1992.515,"y":0.531,"fill":"60-day rolling"},{"x":1992.535,"y":0.519,"fill":"60-day rolling"},{"x":1992.554,"y":0.626,"fill":"60-day rolling"},{"x":1992.573,"y":0.594,"fill":"60-day rolling"},{"x":1992.592,"y":0.603,"fill":"60-day rolling"},{"x":1992.612,"y":0.571,"fill":"60-day rolling"},{"x":1992.631,"y":0.566,"fill":"60-day rolling"},{"x":1992.65,"y":0.604,"fill":"60-day rolling"},{"x":1992.669,"y":0.633,"fill":"60-day rolling"},{"x":1992.688,"y":0.676,"fill":"60-day rolling"},{"x":1992.708,"y":0.703,"fill":"60-day rolling"},{"x":1992.727,"y":0.588,"fill":"60-day rolling"},{"x":1992.746,"y":0.601,"fill":"60-day rolling"},{"x":1992.765,"y":0.669,"fill":"60-day rolling"},{"x":1992.785,"y":0.672,"fill":"60-day rolling"},{"x":1992.804,"y":0.67,"fill":"60-day rolling"},{"x":1992.823,"y":0.663,"fill":"60-day rolling"},{"x":1992.842,"y":0.673,"fill":"60-day rolling"},{"x":1992.862,"y":0.657,"fill":"60-day rolling"},{"x":1992.881,"y":0.628,"fill":"60-day rolling"},{"x":1992.9,"y":0.623,"fill":"60-day rolling"},{"x":1992.919,"y":0.608,"fill":"60-day rolling"},{"x":1992.938,"y":0.607,"fill":"60-day rolling"},{"x":1992.958,"y":0.742,"fill":"60-day rolling"},{"x":1992.977,"y":0.768,"fill":"60-day rolling"},{"x":1992.996,"y":0.583,"fill":"60-day rolling"},{"x":1993.015,"y":0.547,"fill":"60-day rolling"},{"x":1993.035,"y":0.522,"fill":"60-day rolling"},{"x":1993.054,"y":0.459,"fill":"60-day rolling"},{"x":1993.073,"y":0.489,"fill":"60-day rolling"},{"x":1993.092,"y":0.471,"fill":"60-day rolling"},{"x":1993.112,"y":0.443,"fill":"60-day rolling"},{"x":1993.131,"y":0.446,"fill":"60-day rolling"},{"x":1993.15,"y":0.457,"fill":"60-day rolling"},{"x":1993.169,"y":0.47,"fill":"60-day rolling"},{"x":1993.188,"y":0.432,"fill":"60-day rolling"},{"x":1993.208,"y":0.425,"fill":"60-day rolling"},{"x":1993.227,"y":0.478,"fill":"60-day rolling"},{"x":1993.246,"y":0.485,"fill":"60-day rolling"},{"x":1993.265,"y":0.484,"fill":"60-day rolling"},{"x":1993.285,"y":0.522,"fill":"60-day rolling"},{"x":1993.304,"y":0.515,"fill":"60-day rolling"},{"x":1993.323,"y":0.552,"fill":"60-day rolling"},{"x":1993.342,"y":0.554,"fill":"60-day rolling"},{"x":1993.362,"y":0.554,"fill":"60-day rolling"},{"x":1993.381,"y":0.523,"fill":"60-day rolling"},{"x":1993.4,"y":0.465,"fill":"60-day rolling"},{"x":1993.419,"y":0.498,"fill":"60-day rolling"},{"x":1993.438,"y":0.453,"fill":"60-day rolling"},{"x":1993.458,"y":0.425,"fill":"60-day rolling"},{"x":1993.477,"y":0.46,"fill":"60-day rolling"},{"x":1993.496,"y":0.493,"fill":"60-day rolling"},{"x":1993.515,"y":0.488,"fill":"60-day rolling"},{"x":1993.535,"y":0.34,"fill":"60-day rolling"},{"x":1993.554,"y":0.297,"fill":"60-day rolling"},{"x":1993.573,"y":0.326,"fill":"60-day rolling"},{"x":1993.592,"y":0.185,"fill":"60-day rolling"},{"x":1993.612,"y":0.142,"fill":"60-day rolling"},{"x":1993.631,"y":0.168,"fill":"60-day rolling"},{"x":1993.65,"y":0.205,"fill":"60-day rolling"},{"x":1993.669,"y":0.221,"fill":"60-day rolling"},{"x":1993.688,"y":0.236,"fill":"60-day rolling"},{"x":1993.708,"y":0.249,"fill":"60-day rolling"},{"x":1993.727,"y":0.262,"fill":"60-day rolling"},{"x":1993.746,"y":0.256,"fill":"60-day rolling"},{"x":1993.765,"y":0.356,"fill":"60-day rolling"},{"x":1993.785,"y":0.406,"fill":"60-day rolling"},{"x":1993.804,"y":0.415,"fill":"60-day rolling"},{"x":1993.823,"y":0.528,"fill":"60-day rolling"},{"x":1993.842,"y":0.59,"fill":"60-day rolling"},{"x":1993.862,"y":0.633,"fill":"60-day rolling"},{"x":1993.881,"y":0.627,"fill":"60-day rolling"},{"x":1993.9,"y":0.668,"fill":"60-day rolling"},{"x":1993.919,"y":0.646,"fill":"60-day rolling"},{"x":1993.938,"y":0.64,"fill":"60-day rolling"},{"x":1993.958,"y":0.687,"fill":"60-day rolling"},{"x":1993.977,"y":0.689,"fill":"60-day rolling"},{"x":1993.996,"y":0.663,"fill":"60-day rolling"},{"x":1994.015,"y":0.555,"fill":"60-day rolling"},{"x":1994.035,"y":0.525,"fill":"60-day rolling"},{"x":1994.054,"y":0.539,"fill":"60-day rolling"},{"x":1994.073,"y":0.499,"fill":"60-day rolling"},{"x":1994.092,"y":0.447,"fill":"60-day rolling"},{"x":1994.112,"y":0.52,"fill":"60-day rolling"},{"x":1994.131,"y":0.481,"fill":"60-day rolling"},{"x":1994.15,"y":0.524,"fill":"60-day rolling"},{"x":1994.169,"y":0.567,"fill":"60-day rolling"},{"x":1994.188,"y":0.598,"fill":"60-day rolling"},{"x":1994.208,"y":0.614,"fill":"60-day rolling"},{"x":1994.227,"y":0.62,"fill":"60-day rolling"},{"x":1994.246,"y":0.64,"fill":"60-day rolling"},{"x":1994.265,"y":0.662,"fill":"60-day rolling"},{"x":1994.285,"y":0.703,"fill":"60-day rolling"},{"x":1994.304,"y":0.736,"fill":"60-day rolling"},{"x":1994.323,"y":0.729,"fill":"60-day rolling"},{"x":1994.342,"y":0.739,"fill":"60-day rolling"},{"x":1994.362,"y":0.734,"fill":"60-day rolling"},{"x":1994.381,"y":0.712,"fill":"60-day rolling"},{"x":1994.4,"y":0.655,"fill":"60-day rolling"},{"x":1994.419,"y":0.661,"fill":"60-day rolling"},{"x":1994.438,"y":0.633,"fill":"60-day rolling"},{"x":1994.458,"y":0.636,"fill":"60-day rolling"},{"x":1994.477,"y":0.714,"fill":"60-day rolling"},{"x":1994.496,"y":0.684,"fill":"60-day rolling"},{"x":1994.515,"y":0.695,"fill":"60-day rolling"},{"x":1994.535,"y":0.716,"fill":"60-day rolling"},{"x":1994.554,"y":0.722,"fill":"60-day rolling"},{"x":1994.573,"y":0.726,"fill":"60-day rolling"},{"x":1994.592,"y":0.725,"fill":"60-day rolling"},{"x":1994.612,"y":0.747,"fill":"60-day rolling"},{"x":1994.631,"y":0.742,"fill":"60-day rolling"},{"x":1994.65,"y":0.716,"fill":"60-day rolling"},{"x":1994.669,"y":0.726,"fill":"60-day rolling"},{"x":1994.688,"y":0.697,"fill":"60-day rolling"},{"x":1994.708,"y":0.667,"fill":"60-day rolling"},{"x":1994.727,"y":0.737,"fill":"60-day rolling"},{"x":1994.746,"y":0.723,"fill":"60-day rolling"},{"x":1994.765,"y":0.695,"fill":"60-day rolling"},{"x":1994.785,"y":0.703,"fill":"60-day rolling"},{"x":1994.804,"y":0.667,"fill":"60-day rolling"},{"x":1994.823,"y":0.686,"fill":"60-day rolling"},{"x":1994.842,"y":0.696,"fill":"60-day rolling"},{"x":1994.862,"y":0.715,"fill":"60-day rolling"},{"x":1994.881,"y":0.732,"fill":"60-day rolling"},{"x":1994.9,"y":0.728,"fill":"60-day rolling"},{"x":1994.919,"y":0.752,"fill":"60-day rolling"},{"x":1994.938,"y":0.751,"fill":"60-day rolling"},{"x":1994.958,"y":0.742,"fill":"60-day rolling"},{"x":1994.977,"y":0.732,"fill":"60-day rolling"},{"x":1994.996,"y":0.761,"fill":"60-day rolling"},{"x":1995.015,"y":0.748,"fill":"60-day rolling"},{"x":1995.035,"y":0.795,"fill":"60-day rolling"},{"x":1995.054,"y":0.784,"fill":"60-day rolling"},{"x":1995.073,"y":0.783,"fill":"60-day rolling"},{"x":1995.092,"y":0.762,"fill":"60-day rolling"},{"x":1995.112,"y":0.737,"fill":"60-day rolling"},{"x":1995.131,"y":0.742,"fill":"60-day rolling"},{"x":1995.15,"y":0.718,"fill":"60-day rolling"},{"x":1995.169,"y":0.75,"fill":"60-day rolling"},{"x":1995.188,"y":0.75,"fill":"60-day rolling"},{"x":1995.208,"y":0.727,"fill":"60-day rolling"},{"x":1995.227,"y":0.72,"fill":"60-day rolling"},{"x":1995.246,"y":0.714,"fill":"60-day rolling"},{"x":1995.265,"y":0.749,"fill":"60-day rolling"},{"x":1995.285,"y":0.76,"fill":"60-day rolling"},{"x":1995.304,"y":0.748,"fill":"60-day rolling"},{"x":1995.323,"y":0.766,"fill":"60-day rolling"},{"x":1995.342,"y":0.755,"fill":"60-day rolling"},{"x":1995.362,"y":0.756,"fill":"60-day rolling"},{"x":1995.381,"y":0.759,"fill":"60-day rolling"},{"x":1995.4,"y":0.738,"fill":"60-day rolling"},{"x":1995.419,"y":0.724,"fill":"60-day rolling"},{"x":1995.438,"y":0.705,"fill":"60-day rolling"},{"x":1995.458,"y":0.717,"fill":"60-day rolling"},{"x":1995.477,"y":0.743,"fill":"60-day rolling"},{"x":1995.496,"y":0.62,"fill":"60-day rolling"},{"x":1995.515,"y":0.604,"fill":"60-day rolling"},{"x":1995.535,"y":0.634,"fill":"60-day rolling"},{"x":1995.554,"y":0.619,"fill":"60-day rolling"},{"x":1995.573,"y":0.629,"fill":"60-day rolling"},{"x":1995.592,"y":0.601,"fill":"60-day rolling"},{"x":1995.612,"y":0.638,"fill":"60-day rolling"},{"x":1995.631,"y":0.649,"fill":"60-day rolling"},{"x":1995.65,"y":0.634,"fill":"60-day rolling"},{"x":1995.669,"y":0.638,"fill":"60-day rolling"},{"x":1995.688,"y":0.628,"fill":"60-day rolling"},{"x":1995.708,"y":0.626,"fill":"60-day rolling"},{"x":1995.727,"y":0.7,"fill":"60-day rolling"},{"x":1995.746,"y":0.692,"fill":"60-day rolling"},{"x":1995.765,"y":0.701,"fill":"60-day rolling"},{"x":1995.785,"y":0.717,"fill":"60-day rolling"},{"x":1995.804,"y":0.735,"fill":"60-day rolling"},{"x":1995.823,"y":0.768,"fill":"60-day rolling"},{"x":1995.842,"y":0.722,"fill":"60-day rolling"},{"x":1995.862,"y":0.706,"fill":"60-day rolling"},{"x":1995.881,"y":0.724,"fill":"60-day rolling"},{"x":1995.9,"y":0.714,"fill":"60-day rolling"},{"x":1995.919,"y":0.686,"fill":"60-day rolling"},{"x":1995.938,"y":0.691,"fill":"60-day rolling"},{"x":1995.958,"y":0.657,"fill":"60-day rolling"},{"x":1995.977,"y":0.672,"fill":"60-day rolling"},{"x":1995.996,"y":0.647,"fill":"60-day rolling"},{"x":1996.015,"y":0.62,"fill":"60-day rolling"},{"x":1996.035,"y":0.541,"fill":"60-day rolling"},{"x":1996.054,"y":0.488,"fill":"60-day rolling"},{"x":1996.073,"y":0.494,"fill":"60-day rolling"},{"x":1996.092,"y":0.5,"fill":"60-day rolling"},{"x":1996.112,"y":0.487,"fill":"60-day rolling"},{"x":1996.131,"y":0.507,"fill":"60-day rolling"},{"x":1996.15,"y":0.527,"fill":"60-day rolling"},{"x":1996.169,"y":0.544,"fill":"60-day rolling"},{"x":1996.188,"y":0.559,"fill":"60-day rolling"},{"x":1996.208,"y":0.558,"fill":"60-day rolling"},{"x":1996.227,"y":0.495,"fill":"60-day rolling"},{"x":1996.246,"y":0.455,"fill":"60-day rolling"},{"x":1996.265,"y":0.441,"fill":"60-day rolling"},{"x":1996.285,"y":0.433,"fill":"60-day rolling"},{"x":1996.304,"y":0.446,"fill":"60-day rolling"},{"x":1996.323,"y":0.447,"fill":"60-day rolling"},{"x":1996.342,"y":0.465,"fill":"60-day rolling"},{"x":1996.362,"y":0.471,"fill":"60-day rolling"},{"x":1996.381,"y":0.473,"fill":"60-day rolling"},{"x":1996.4,"y":0.481,"fill":"60-day rolling"},{"x":1996.419,"y":0.485,"fill":"60-day rolling"},{"x":1996.438,"y":0.402,"fill":"60-day rolling"},{"x":1996.458,"y":0.504,"fill":"60-day rolling"},{"x":1996.477,"y":0.622,"fill":"60-day rolling"},{"x":1996.496,"y":0.641,"fill":"60-day rolling"},{"x":1996.515,"y":0.603,"fill":"60-day rolling"},{"x":1996.535,"y":0.575,"fill":"60-day rolling"},{"x":1996.554,"y":0.599,"fill":"60-day rolling"},{"x":1996.573,"y":0.679,"fill":"60-day rolling"},{"x":1996.592,"y":0.72,"fill":"60-day rolling"},{"x":1996.612,"y":0.744,"fill":"60-day rolling"},{"x":1996.631,"y":0.744,"fill":"60-day rolling"},{"x":1996.65,"y":0.758,"fill":"60-day rolling"},{"x":1996.669,"y":0.786,"fill":"60-day rolling"},{"x":1996.688,"y":0.763,"fill":"60-day rolling"},{"x":1996.708,"y":0.758,"fill":"60-day rolling"},{"x":1996.727,"y":0.79,"fill":"60-day rolling"},{"x":1996.746,"y":0.824,"fill":"60-day rolling"},{"x":1996.765,"y":0.807,"fill":"60-day rolling"},{"x":1996.785,"y":0.771,"fill":"60-day rolling"},{"x":1996.804,"y":0.712,"fill":"60-day rolling"},{"x":1996.823,"y":0.686,"fill":"60-day rolling"},{"x":1996.842,"y":0.668,"fill":"60-day rolling"},{"x":1996.862,"y":0.666,"fill":"60-day rolling"},{"x":1996.881,"y":0.607,"fill":"60-day rolling"},{"x":1996.9,"y":0.586,"fill":"60-day rolling"},{"x":1996.919,"y":0.574,"fill":"60-day rolling"},{"x":1996.938,"y":0.559,"fill":"60-day rolling"},{"x":1996.958,"y":0.662,"fill":"60-day rolling"},{"x":1996.977,"y":0.703,"fill":"60-day rolling"},{"x":1996.996,"y":0.704,"fill":"60-day rolling"},{"x":1997.015,"y":0.715,"fill":"60-day rolling"},{"x":1997.035,"y":0.751,"fill":"60-day rolling"},{"x":1997.054,"y":0.755,"fill":"60-day rolling"},{"x":1997.073,"y":0.754,"fill":"60-day rolling"},{"x":1997.092,"y":0.728,"fill":"60-day rolling"},{"x":1997.112,"y":0.741,"fill":"60-day rolling"},{"x":1997.131,"y":0.751,"fill":"60-day rolling"},{"x":1997.15,"y":0.769,"fill":"60-day rolling"},{"x":1997.169,"y":0.752,"fill":"60-day rolling"},{"x":1997.188,"y":0.681,"fill":"60-day rolling"},{"x":1997.208,"y":0.644,"fill":"60-day rolling"},{"x":1997.227,"y":0.714,"fill":"60-day rolling"},{"x":1997.246,"y":0.697,"fill":"60-day rolling"},{"x":1997.265,"y":0.668,"fill":"60-day rolling"},{"x":1997.285,"y":0.692,"fill":"60-day rolling"},{"x":1997.304,"y":0.71,"fill":"60-day rolling"},{"x":1997.323,"y":0.708,"fill":"60-day rolling"},{"x":1997.342,"y":0.714,"fill":"60-day rolling"},{"x":1997.362,"y":0.701,"fill":"60-day rolling"},{"x":1997.381,"y":0.627,"fill":"60-day rolling"},{"x":1997.4,"y":0.613,"fill":"60-day rolling"},{"x":1997.419,"y":0.625,"fill":"60-day rolling"},{"x":1997.438,"y":0.578,"fill":"60-day rolling"},{"x":1997.458,"y":0.497,"fill":"60-day rolling"},{"x":1997.477,"y":0.485,"fill":"60-day rolling"},{"x":1997.496,"y":0.436,"fill":"60-day rolling"},{"x":1997.515,"y":0.362,"fill":"60-day rolling"},{"x":1997.535,"y":0.403,"fill":"60-day rolling"},{"x":1997.554,"y":0.412,"fill":"60-day rolling"},{"x":1997.573,"y":0.453,"fill":"60-day rolling"},{"x":1997.592,"y":0.461,"fill":"60-day rolling"},{"x":1997.612,"y":0.521,"fill":"60-day rolling"},{"x":1997.631,"y":0.565,"fill":"60-day rolling"},{"x":1997.65,"y":0.639,"fill":"60-day rolling"},{"x":1997.669,"y":0.689,"fill":"60-day rolling"},{"x":1997.688,"y":0.729,"fill":"60-day rolling"},{"x":1997.708,"y":0.725,"fill":"60-day rolling"},{"x":1997.727,"y":0.756,"fill":"60-day rolling"},{"x":1997.746,"y":0.756,"fill":"60-day rolling"},{"x":1997.765,"y":0.723,"fill":"60-day rolling"},{"x":1997.785,"y":0.724,"fill":"60-day rolling"},{"x":1997.804,"y":0.746,"fill":"60-day rolling"},{"x":1997.823,"y":0.742,"fill":"60-day rolling"},{"x":1997.842,"y":0.759,"fill":"60-day rolling"},{"x":1997.862,"y":0.78,"fill":"60-day rolling"},{"x":1997.881,"y":0.769,"fill":"60-day rolling"},{"x":1997.9,"y":0.765,"fill":"60-day rolling"},{"x":1997.919,"y":0.759,"fill":"60-day rolling"},{"x":1997.938,"y":0.763,"fill":"60-day rolling"},{"x":1997.958,"y":0.755,"fill":"60-day rolling"},{"x":1997.977,"y":0.744,"fill":"60-day rolling"},{"x":1997.996,"y":0.776,"fill":"60-day rolling"},{"x":1998.015,"y":0.789,"fill":"60-day rolling"},{"x":1998.035,"y":0.784,"fill":"60-day rolling"},{"x":1998.054,"y":0.797,"fill":"60-day rolling"},{"x":1998.073,"y":0.769,"fill":"60-day rolling"},{"x":1998.092,"y":0.741,"fill":"60-day rolling"},{"x":1998.112,"y":0.739,"fill":"60-day rolling"},{"x":1998.131,"y":0.723,"fill":"60-day rolling"},{"x":1998.15,"y":0.725,"fill":"60-day rolling"},{"x":1998.169,"y":0.746,"fill":"60-day rolling"},{"x":1998.188,"y":0.762,"fill":"60-day rolling"},{"x":1998.208,"y":0.792,"fill":"60-day rolling"},{"x":1998.227,"y":0.772,"fill":"60-day rolling"},{"x":1998.246,"y":0.679,"fill":"60-day rolling"},{"x":1998.265,"y":0.691,"fill":"60-day rolling"},{"x":1998.285,"y":0.652,"fill":"60-day rolling"},{"x":1998.304,"y":0.686,"fill":"60-day rolling"},{"x":1998.323,"y":0.666,"fill":"60-day rolling"},{"x":1998.342,"y":0.695,"fill":"60-day rolling"},{"x":1998.362,"y":0.688,"fill":"60-day rolling"},{"x":1998.381,"y":0.692,"fill":"60-day rolling"},{"x":1998.4,"y":0.693,"fill":"60-day rolling"},{"x":1998.419,"y":0.677,"fill":"60-day rolling"},{"x":1998.438,"y":0.675,"fill":"60-day rolling"},{"x":1998.458,"y":0.693,"fill":"60-day rolling"},{"x":1998.477,"y":0.743,"fill":"60-day rolling"},{"x":1998.496,"y":0.752,"fill":"60-day rolling"},{"x":1998.515,"y":0.762,"fill":"60-day rolling"},{"x":1998.535,"y":0.757,"fill":"60-day rolling"},{"x":1998.554,"y":0.772,"fill":"60-day rolling"},{"x":1998.573,"y":0.735,"fill":"60-day rolling"},{"x":1998.592,"y":0.745,"fill":"60-day rolling"},{"x":1998.612,"y":0.75,"fill":"60-day rolling"},{"x":1998.631,"y":0.781,"fill":"60-day rolling"}],"geoms":["point","boxplot"],"x":"year","y":"correlation","code":{"point":"ggplot(df, aes(year, correlation, colour = group)) +\n  geom_point(size = 1)","boxplot":"ggplot(df, aes(group, correlation)) +\n  geom_boxplot()"}}

In the points view the DCC path stays in a narrower band than the 60-day path. In the box plot view the DCC plot spans a narrower range of correlations, from one whisker to the other.

The block below makes the same comparison on all days from day 60 to day 1,859, so its numbers do not depend on the thinning.

```r
# Compare the DCC path with the 60-day rolling correlation over days 60 to 1,859
days <- 60:nrow(x)
dcc_path <- rho[days]
roll_path <- rc60[days]
compare <- rbind(DCC = c(min = min(dcc_path), max = max(dcc_path), sd = sd(dcc_path)),
                 rolling = c(min = min(roll_path), max = max(roll_path), sd = sd(roll_path)))
round(compare, 3)
#>           min   max    sd
#> DCC     0.319 0.754 0.078
#> rolling 0.138 0.848 0.132
round(cor(dcc_path, roll_path), 3)
#> [1] 0.918
# Compare the typical size of a one-day change in each path
round(c(DCC = median(abs(diff(dcc_path))), rolling = median(abs(diff(roll_path)))), 4)
#>     DCC rolling
#>  0.0035  0.0065
```

The DCC path ranges from 0.319 to 0.754 with a standard deviation of 0.078. The 60-day path ranges from 0.138 to 0.848 with a standard deviation of 0.132. The two paths correlate at 0.918, so they follow the same overall pattern, but the median one-day change is 0.0035 for the DCC path against 0.0065 for the 60-day path.

The DCC path also has a value for each of the first 59 days, which a 60-day window cannot give.

=== step === quiz
## Quick check: what do alpha and beta say about the DCC path?

The DCC path changed by a median of 0.0035 a day, against 0.0065 for the 60-day path. In the fit, alpha is 0.0181 and beta is 0.9742. What do those two values say about how the DCC path moves?

::quiz {"correct": 3, "gate": true, "difficulty": "intermediate"}
- Beta is the correlation itself, so the path stays close to 0.9742. ::no
- Alpha plus beta is close to 1, so the correlation is close to 1 on every day. ::no
- A day's co-movement enters Q with weight 0.0181 and 0.9742 of yesterday's Q carries over, so the correlation changes in small steps. ::ok Yes. Each day moves Q only a little, and most of yesterday's Q stays, so one day cannot shift the path far. That fits the median one-day change of 0.0035 for the DCC path.
- The DCC path uses fewer days than the 60-day window, so it has less noise. ::no Each of these mixes up what the parameters do. Alpha and beta are weights in the update of Q, not correlations, and the path ran from 0.319 to 0.754. Alpha plus beta of 0.9923 says how slowly a deviation of Q from its long-run level fades, and it does not push the correlation towards 1. The fit also uses all 1,859 days, because earlier days count through the Q that is carried over.

=== step === widget
## Correlation on volatile days

Correlations between stock indices are often said to rise when markets are turbulent. The fitted path lets us check that in this data.

The widget below plots each day's DCC correlation against the DAX conditional standard deviation, and colours the volatile days. A volatile day here is a day when the DAX conditional standard deviation is above its 90th percentile.

::widget chart-plotter {"data":[{"x":1.03,"y":0.622,"fill":"other"},{"x":1.028,"y":0.599,"fill":"other"},{"x":1.002,"y":0.602,"fill":"other"},{"x":0.993,"y":0.608,"fill":"other"},{"x":0.963,"y":0.602,"fill":"other"},{"x":0.943,"y":0.606,"fill":"other"},{"x":0.966,"y":0.615,"fill":"other"},{"x":0.945,"y":0.618,"fill":"other"},{"x":0.921,"y":0.616,"fill":"other"},{"x":0.907,"y":0.602,"fill":"other"},{"x":0.882,"y":0.586,"fill":"other"},{"x":0.876,"y":0.561,"fill":"other"},{"x":0.867,"y":0.557,"fill":"other"},{"x":0.859,"y":0.561,"fill":"other"},{"x":0.839,"y":0.56,"fill":"other"},{"x":0.82,"y":0.559,"fill":"other"},{"x":0.805,"y":0.555,"fill":"other"},{"x":0.812,"y":0.558,"fill":"other"},{"x":0.808,"y":0.557,"fill":"other"},{"x":0.807,"y":0.546,"fill":"other"},{"x":0.791,"y":0.547,"fill":"other"},{"x":0.793,"y":0.543,"fill":"other"},{"x":0.778,"y":0.542,"fill":"other"},{"x":0.765,"y":0.542,"fill":"other"},{"x":0.754,"y":0.54,"fill":"other"},{"x":0.744,"y":0.53,"fill":"other"},{"x":0.752,"y":0.538,"fill":"other"},{"x":0.789,"y":0.557,"fill":"other"},{"x":0.776,"y":0.557,"fill":"other"},{"x":0.764,"y":0.533,"fill":"other"},{"x":0.763,"y":0.533,"fill":"other"},{"x":0.834,"y":0.541,"fill":"other"},{"x":0.816,"y":0.53,"fill":"other"},{"x":0.801,"y":0.532,"fill":"other"},{"x":0.786,"y":0.532,"fill":"other"},{"x":2.65,"y":0.703,"fill":"volatile"},{"x":2.534,"y":0.703,"fill":"volatile"},{"x":2.732,"y":0.71,"fill":"volatile"},{"x":2.599,"y":0.708,"fill":"volatile"},{"x":2.467,"y":0.707,"fill":"volatile"},{"x":2.346,"y":0.706,"fill":"volatile"},{"x":2.224,"y":0.703,"fill":"volatile"},{"x":2.107,"y":0.702,"fill":"volatile"},{"x":1.997,"y":0.7,"fill":"volatile"},{"x":1.895,"y":0.699,"fill":"volatile"},{"x":1.799,"y":0.688,"fill":"volatile"},{"x":1.709,"y":0.686,"fill":"volatile"},{"x":1.631,"y":0.686,"fill":"volatile"},{"x":1.553,"y":0.685,"fill":"volatile"},{"x":1.48,"y":0.684,"fill":"volatile"},{"x":1.418,"y":0.683,"fill":"volatile"},{"x":1.372,"y":0.682,"fill":"volatile"},{"x":1.311,"y":0.681,"fill":"other"},{"x":1.255,"y":0.678,"fill":"other"},{"x":1.203,"y":0.674,"fill":"other"},{"x":1.155,"y":0.669,"fill":"other"},{"x":1.111,"y":0.665,"fill":"other"},{"x":1.098,"y":0.666,"fill":"other"},{"x":1.058,"y":0.666,"fill":"other"},{"x":1.032,"y":0.659,"fill":"other"},{"x":0.997,"y":0.649,"fill":"other"},{"x":0.974,"y":0.647,"fill":"other"},{"x":0.945,"y":0.636,"fill":"other"},{"x":0.937,"y":0.636,"fill":"other"},{"x":0.91,"y":0.635,"fill":"other"},{"x":0.895,"y":0.616,"fill":"other"},{"x":0.872,"y":0.61,"fill":"other"},{"x":0.852,"y":0.611,"fill":"other"},{"x":0.832,"y":0.605,"fill":"other"},{"x":0.815,"y":0.605,"fill":"other"},{"x":0.845,"y":0.614,"fill":"other"},{"x":0.835,"y":0.612,"fill":"other"},{"x":0.855,"y":0.618,"fill":"other"},{"x":0.835,"y":0.614,"fill":"other"},{"x":0.816,"y":0.609,"fill":"other"},{"x":0.8,"y":0.604,"fill":"other"},{"x":0.812,"y":0.601,"fill":"other"},{"x":0.841,"y":0.594,"fill":"other"},{"x":0.835,"y":0.585,"fill":"other"},{"x":0.818,"y":0.585,"fill":"other"},{"x":0.804,"y":0.562,"fill":"other"},{"x":0.793,"y":0.55,"fill":"other"},{"x":0.805,"y":0.547,"fill":"other"},{"x":0.847,"y":0.564,"fill":"other"},{"x":0.827,"y":0.563,"fill":"other"},{"x":0.816,"y":0.551,"fill":"other"},{"x":0.811,"y":0.546,"fill":"other"},{"x":0.797,"y":0.535,"fill":"other"},{"x":0.791,"y":0.538,"fill":"other"},{"x":0.788,"y":0.542,"fill":"other"},{"x":0.78,"y":0.544,"fill":"other"},{"x":0.781,"y":0.547,"fill":"other"},{"x":0.772,"y":0.549,"fill":"other"},{"x":0.769,"y":0.55,"fill":"other"},{"x":0.877,"y":0.563,"fill":"other"},{"x":0.86,"y":0.565,"fill":"other"},{"x":0.886,"y":0.574,"fill":"other"},{"x":0.877,"y":0.577,"fill":"other"},{"x":0.872,"y":0.581,"fill":"other"},{"x":0.85,"y":0.578,"fill":"other"},{"x":0.905,"y":0.6,"fill":"other"},{"x":0.924,"y":0.611,"fill":"other"},{"x":0.897,"y":0.61,"fill":"other"},{"x":0.897,"y":0.599,"fill":"other"},{"x":0.876,"y":0.599,"fill":"other"},{"x":0.869,"y":0.591,"fill":"other"},{"x":0.868,"y":0.595,"fill":"other"},{"x":0.88,"y":0.604,"fill":"other"},{"x":0.859,"y":0.602,"fill":"other"},{"x":0.889,"y":0.603,"fill":"other"},{"x":0.942,"y":0.599,"fill":"other"},{"x":0.914,"y":0.598,"fill":"other"},{"x":0.892,"y":0.599,"fill":"other"},{"x":0.868,"y":0.591,"fill":"other"},{"x":0.848,"y":0.59,"fill":"other"},{"x":0.831,"y":0.588,"fill":"other"},{"x":0.838,"y":0.595,"fill":"other"},{"x":0.825,"y":0.597,"fill":"other"},{"x":0.812,"y":0.585,"fill":"other"},{"x":0.801,"y":0.586,"fill":"other"},{"x":0.793,"y":0.589,"fill":"other"},{"x":0.796,"y":0.578,"fill":"other"},{"x":0.788,"y":0.562,"fill":"other"},{"x":0.8,"y":0.571,"fill":"other"},{"x":0.821,"y":0.586,"fill":"other"},{"x":0.807,"y":0.587,"fill":"other"},{"x":0.791,"y":0.567,"fill":"other"},{"x":0.777,"y":0.568,"fill":"other"},{"x":0.764,"y":0.568,"fill":"other"},{"x":0.827,"y":0.589,"fill":"other"},{"x":0.833,"y":0.585,"fill":"other"},{"x":0.815,"y":0.531,"fill":"other"},{"x":0.798,"y":0.532,"fill":"other"},{"x":0.849,"y":0.518,"fill":"other"},{"x":0.833,"y":0.52,"fill":"other"},{"x":0.814,"y":0.52,"fill":"other"},{"x":0.822,"y":0.524,"fill":"other"},{"x":0.832,"y":0.53,"fill":"other"},{"x":0.858,"y":0.543,"fill":"other"},{"x":0.866,"y":0.52,"fill":"other"},{"x":0.849,"y":0.522,"fill":"other"},{"x":0.839,"y":0.527,"fill":"other"},{"x":0.974,"y":0.532,"fill":"other"},{"x":0.944,"y":0.532,"fill":"other"},{"x":0.918,"y":0.531,"fill":"other"},{"x":0.921,"y":0.532,"fill":"other"},{"x":0.895,"y":0.532,"fill":"other"},{"x":0.879,"y":0.537,"fill":"other"},{"x":0.869,"y":0.534,"fill":"other"},{"x":0.849,"y":0.535,"fill":"other"},{"x":0.866,"y":0.549,"fill":"other"},{"x":0.846,"y":0.547,"fill":"other"},{"x":0.861,"y":0.547,"fill":"other"},{"x":0.857,"y":0.546,"fill":"other"},{"x":0.837,"y":0.544,"fill":"other"},{"x":0.818,"y":0.544,"fill":"other"},{"x":0.811,"y":0.545,"fill":"other"},{"x":0.8,"y":0.538,"fill":"other"},{"x":0.786,"y":0.539,"fill":"other"},{"x":0.772,"y":0.532,"fill":"other"},{"x":0.762,"y":0.52,"fill":"other"},{"x":0.756,"y":0.52,"fill":"other"},{"x":0.748,"y":0.511,"fill":"other"},{"x":0.742,"y":0.512,"fill":"other"},{"x":0.738,"y":0.516,"fill":"other"},{"x":0.749,"y":0.529,"fill":"other"},{"x":0.747,"y":0.534,"fill":"other"},{"x":0.745,"y":0.54,"fill":"other"},{"x":0.797,"y":0.535,"fill":"other"},{"x":0.782,"y":0.536,"fill":"other"},{"x":0.813,"y":0.548,"fill":"other"},{"x":0.826,"y":0.556,"fill":"other"},{"x":0.896,"y":0.568,"fill":"other"},{"x":0.872,"y":0.568,"fill":"other"},{"x":0.85,"y":0.569,"fill":"other"},{"x":0.83,"y":0.566,"fill":"other"},{"x":0.836,"y":0.571,"fill":"other"},{"x":0.818,"y":0.572,"fill":"other"},{"x":0.801,"y":0.564,"fill":"other"},{"x":0.824,"y":0.565,"fill":"other"},{"x":0.811,"y":0.567,"fill":"other"},{"x":0.795,"y":0.553,"fill":"other"},{"x":0.809,"y":0.562,"fill":"other"},{"x":0.834,"y":0.579,"fill":"other"},{"x":0.828,"y":0.56,"fill":"other"},{"x":0.831,"y":0.561,"fill":"other"},{"x":0.823,"y":0.566,"fill":"other"},{"x":0.808,"y":0.565,"fill":"other"},{"x":0.796,"y":0.563,"fill":"other"},{"x":0.783,"y":0.558,"fill":"other"},{"x":0.816,"y":0.566,"fill":"other"},{"x":0.799,"y":0.564,"fill":"other"},{"x":0.784,"y":0.565,"fill":"other"},{"x":0.771,"y":0.563,"fill":"other"},{"x":0.821,"y":0.583,"fill":"other"},{"x":0.835,"y":0.58,"fill":"other"},{"x":0.817,"y":0.574,"fill":"other"},{"x":0.824,"y":0.586,"fill":"other"},{"x":0.84,"y":0.572,"fill":"other"},{"x":0.831,"y":0.577,"fill":"other"},{"x":0.875,"y":0.586,"fill":"other"},{"x":0.854,"y":0.586,"fill":"other"},{"x":0.908,"y":0.588,"fill":"other"},{"x":0.892,"y":0.583,"fill":"other"},{"x":0.877,"y":0.492,"fill":"other"},{"x":0.858,"y":0.489,"fill":"other"},{"x":0.839,"y":0.49,"fill":"other"},{"x":0.83,"y":0.496,"fill":"other"},{"x":0.812,"y":0.496,"fill":"other"},{"x":0.796,"y":0.497,"fill":"other"},{"x":0.781,"y":0.498,"fill":"other"},{"x":0.768,"y":0.498,"fill":"other"},{"x":0.758,"y":0.493,"fill":"other"},{"x":0.759,"y":0.491,"fill":"other"},{"x":0.748,"y":0.487,"fill":"other"},{"x":0.74,"y":0.485,"fill":"other"},{"x":0.754,"y":0.484,"fill":"other"},{"x":0.743,"y":0.483,"fill":"other"},{"x":0.736,"y":0.485,"fill":"other"},{"x":0.727,"y":0.486,"fill":"other"},{"x":0.72,"y":0.486,"fill":"other"},{"x":0.713,"y":0.487,"fill":"other"},{"x":0.724,"y":0.5,"fill":"other"},{"x":0.721,"y":0.5,"fill":"other"},{"x":0.719,"y":0.489,"fill":"other"},{"x":0.712,"y":0.49,"fill":"other"},{"x":0.707,"y":0.493,"fill":"other"},{"x":0.703,"y":0.494,"fill":"other"},{"x":0.719,"y":0.505,"fill":"other"},{"x":0.754,"y":0.507,"fill":"other"},{"x":0.98,"y":0.493,"fill":"other"},{"x":0.949,"y":0.493,"fill":"other"},{"x":0.956,"y":0.496,"fill":"other"},{"x":0.928,"y":0.497,"fill":"other"},{"x":0.945,"y":0.501,"fill":"other"},{"x":0.922,"y":0.501,"fill":"other"},{"x":0.918,"y":0.505,"fill":"other"},{"x":0.9,"y":0.508,"fill":"other"},{"x":0.875,"y":0.509,"fill":"other"},{"x":0.872,"y":0.514,"fill":"other"},{"x":0.86,"y":0.518,"fill":"other"},{"x":0.84,"y":0.518,"fill":"other"},{"x":0.851,"y":0.533,"fill":"other"},{"x":0.833,"y":0.533,"fill":"other"},{"x":0.816,"y":0.534,"fill":"other"},{"x":0.8,"y":0.529,"fill":"other"},{"x":0.788,"y":0.532,"fill":"other"},{"x":0.776,"y":0.533,"fill":"other"},{"x":0.779,"y":0.543,"fill":"other"},{"x":0.771,"y":0.534,"fill":"other"},{"x":0.789,"y":0.54,"fill":"other"},{"x":0.782,"y":0.545,"fill":"other"},{"x":0.78,"y":0.551,"fill":"other"},{"x":0.767,"y":0.536,"fill":"other"},{"x":0.755,"y":0.533,"fill":"other"},{"x":0.75,"y":0.536,"fill":"other"},{"x":0.74,"y":0.536,"fill":"other"},{"x":0.748,"y":0.548,"fill":"other"},{"x":0.738,"y":0.544,"fill":"other"},{"x":0.753,"y":0.555,"fill":"other"},{"x":0.742,"y":0.548,"fill":"other"},{"x":0.733,"y":0.548,"fill":"other"},{"x":0.727,"y":0.529,"fill":"other"},{"x":0.719,"y":0.528,"fill":"other"},{"x":0.748,"y":0.54,"fill":"other"},{"x":0.746,"y":0.546,"fill":"other"},{"x":0.738,"y":0.532,"fill":"other"},{"x":0.766,"y":0.545,"fill":"other"},{"x":0.761,"y":0.55,"fill":"other"},{"x":0.767,"y":0.551,"fill":"other"},{"x":0.812,"y":0.554,"fill":"other"},{"x":0.797,"y":0.555,"fill":"other"},{"x":0.783,"y":0.555,"fill":"other"},{"x":0.772,"y":0.556,"fill":"other"},{"x":0.906,"y":0.615,"fill":"other"},{"x":1.155,"y":0.62,"fill":"other"},{"x":1.11,"y":0.619,"fill":"other"},{"x":1.107,"y":0.628,"fill":"other"},{"x":1.093,"y":0.615,"fill":"other"},{"x":1.066,"y":0.619,"fill":"other"},{"x":1.029,"y":0.603,"fill":"other"},{"x":0.994,"y":0.595,"fill":"other"},{"x":1.011,"y":0.61,"fill":"other"},{"x":1.012,"y":0.612,"fill":"other"},{"x":1.007,"y":0.615,"fill":"other"},{"x":0.976,"y":0.607,"fill":"other"},{"x":0.947,"y":0.602,"fill":"other"},{"x":0.947,"y":0.582,"fill":"other"},{"x":0.927,"y":0.586,"fill":"other"},{"x":0.908,"y":0.588,"fill":"other"},{"x":1.044,"y":0.598,"fill":"other"},{"x":1.054,"y":0.604,"fill":"other"},{"x":1.046,"y":0.604,"fill":"other"},{"x":1.009,"y":0.602,"fill":"other"},{"x":0.991,"y":0.605,"fill":"other"},{"x":0.965,"y":0.594,"fill":"other"},{"x":1.019,"y":0.604,"fill":"other"},{"x":0.991,"y":0.599,"fill":"other"},{"x":1.008,"y":0.596,"fill":"other"},{"x":1.034,"y":0.592,"fill":"other"},{"x":1.279,"y":0.644,"fill":"other"},{"x":1.284,"y":0.653,"fill":"other"},{"x":1.243,"y":0.652,"fill":"other"},{"x":1.381,"y":0.66,"fill":"volatile"},{"x":1.32,"y":0.66,"fill":"other"},{"x":1.273,"y":0.658,"fill":"other"},{"x":1.244,"y":0.66,"fill":"other"},{"x":1.193,"y":0.657,"fill":"other"},{"x":1.237,"y":0.669,"fill":"other"},{"x":1.198,"y":0.671,"fill":"other"},{"x":1.15,"y":0.671,"fill":"other"},{"x":1.107,"y":0.664,"fill":"other"},{"x":1.091,"y":0.665,"fill":"other"},{"x":1.052,"y":0.664,"fill":"other"},{"x":1.015,"y":0.659,"fill":"other"},{"x":1.53,"y":0.673,"fill":"volatile"},{"x":1.503,"y":0.675,"fill":"volatile"},{"x":1.451,"y":0.675,"fill":"volatile"},{"x":1.411,"y":0.577,"fill":"volatile"},{"x":1.387,"y":0.583,"fill":"volatile"},{"x":1.45,"y":0.576,"fill":"volatile"},{"x":1.393,"y":0.57,"fill":"volatile"},{"x":1.355,"y":0.57,"fill":"volatile"},{"x":1.302,"y":0.561,"fill":"other"},{"x":1.327,"y":0.563,"fill":"volatile"},{"x":1.377,"y":0.573,"fill":"volatile"},{"x":1.316,"y":0.573,"fill":"other"},{"x":1.285,"y":0.574,"fill":"other"},{"x":1.254,"y":0.577,"fill":"other"},{"x":1.216,"y":0.579,"fill":"other"},{"x":1.78,"y":0.644,"fill":"volatile"},{"x":1.725,"y":0.647,"fill":"volatile"},{"x":1.655,"y":0.648,"fill":"volatile"},{"x":1.586,"y":0.649,"fill":"volatile"},{"x":1.52,"y":0.648,"fill":"volatile"},{"x":1.45,"y":0.648,"fill":"volatile"},{"x":1.479,"y":0.65,"fill":"volatile"},{"x":1.449,"y":0.65,"fill":"volatile"},{"x":1.383,"y":0.647,"fill":"volatile"},{"x":1.322,"y":0.647,"fill":"other"},{"x":1.317,"y":0.641,"fill":"other"},{"x":1.33,"y":0.65,"fill":"volatile"},{"x":1.282,"y":0.641,"fill":"other"},{"x":1.25,"y":0.641,"fill":"other"},{"x":1.232,"y":0.641,"fill":"other"},{"x":1.183,"y":0.639,"fill":"other"},{"x":1.136,"y":0.639,"fill":"other"},{"x":1.203,"y":0.64,"fill":"other"},{"x":1.186,"y":0.64,"fill":"other"},{"x":1.142,"y":0.636,"fill":"other"},{"x":1.107,"y":0.623,"fill":"other"},{"x":1.066,"y":0.621,"fill":"other"},{"x":1.056,"y":0.623,"fill":"other"},{"x":1.045,"y":0.626,"fill":"other"},{"x":1.009,"y":0.625,"fill":"other"},{"x":1.036,"y":0.609,"fill":"other"},{"x":1.005,"y":0.61,"fill":"other"},{"x":0.978,"y":0.612,"fill":"other"},{"x":1.089,"y":0.622,"fill":"other"},{"x":1.049,"y":0.616,"fill":"other"},{"x":1.012,"y":0.614,"fill":"other"},{"x":0.985,"y":0.612,"fill":"other"},{"x":0.954,"y":0.607,"fill":"other"},{"x":0.934,"y":0.605,"fill":"other"},{"x":0.908,"y":0.603,"fill":"other"},{"x":0.982,"y":0.599,"fill":"other"},{"x":0.951,"y":0.6,"fill":"other"},{"x":0.954,"y":0.605,"fill":"other"},{"x":0.937,"y":0.608,"fill":"other"},{"x":0.915,"y":0.609,"fill":"other"},{"x":0.922,"y":0.614,"fill":"other"},{"x":0.896,"y":0.613,"fill":"other"},{"x":0.934,"y":0.626,"fill":"other"},{"x":0.907,"y":0.626,"fill":"other"},{"x":0.887,"y":0.627,"fill":"other"},{"x":0.873,"y":0.628,"fill":"other"},{"x":0.884,"y":0.606,"fill":"other"},{"x":0.863,"y":0.605,"fill":"other"},{"x":0.946,"y":0.619,"fill":"other"},{"x":0.922,"y":0.62,"fill":"other"},{"x":0.895,"y":0.62,"fill":"other"},{"x":0.871,"y":0.62,"fill":"other"},{"x":0.851,"y":0.613,"fill":"other"},{"x":0.837,"y":0.608,"fill":"other"},{"x":0.906,"y":0.637,"fill":"other"},{"x":0.953,"y":0.641,"fill":"other"},{"x":0.925,"y":0.633,"fill":"other"},{"x":0.902,"y":0.624,"fill":"other"},{"x":0.878,"y":0.624,"fill":"other"},{"x":0.855,"y":0.624,"fill":"other"},{"x":0.898,"y":0.61,"fill":"other"},{"x":0.875,"y":0.601,"fill":"other"},{"x":0.864,"y":0.605,"fill":"other"},{"x":0.843,"y":0.602,"fill":"other"},{"x":0.824,"y":0.602,"fill":"other"},{"x":0.807,"y":0.598,"fill":"other"},{"x":0.83,"y":0.542,"fill":"other"},{"x":0.815,"y":0.544,"fill":"other"},{"x":0.831,"y":0.548,"fill":"other"},{"x":0.832,"y":0.556,"fill":"other"},{"x":0.824,"y":0.561,"fill":"other"},{"x":0.827,"y":0.539,"fill":"other"},{"x":0.913,"y":0.544,"fill":"other"},{"x":0.928,"y":0.55,"fill":"other"},{"x":1.015,"y":0.54,"fill":"other"},{"x":1.066,"y":0.524,"fill":"other"},{"x":1.04,"y":0.528,"fill":"other"},{"x":1.004,"y":0.527,"fill":"other"},{"x":0.978,"y":0.529,"fill":"other"},{"x":0.966,"y":0.531,"fill":"other"},{"x":1.011,"y":0.535,"fill":"other"},{"x":0.978,"y":0.494,"fill":"other"},{"x":0.979,"y":0.494,"fill":"other"},{"x":0.962,"y":0.482,"fill":"other"},{"x":0.932,"y":0.482,"fill":"other"},{"x":0.939,"y":0.499,"fill":"other"},{"x":0.919,"y":0.503,"fill":"other"},{"x":0.956,"y":0.524,"fill":"other"},{"x":0.938,"y":0.519,"fill":"other"},{"x":1.006,"y":0.499,"fill":"other"},{"x":0.973,"y":0.5,"fill":"other"},{"x":0.953,"y":0.503,"fill":"other"},{"x":0.925,"y":0.5,"fill":"other"},{"x":0.93,"y":0.507,"fill":"other"},{"x":0.918,"y":0.501,"fill":"other"},{"x":0.97,"y":0.492,"fill":"other"},{"x":1.015,"y":0.515,"fill":"other"},{"x":0.982,"y":0.516,"fill":"other"},{"x":0.974,"y":0.524,"fill":"other"},{"x":0.96,"y":0.523,"fill":"other"},{"x":0.933,"y":0.524,"fill":"other"},{"x":0.972,"y":0.537,"fill":"other"},{"x":0.946,"y":0.537,"fill":"other"},{"x":0.926,"y":0.54,"fill":"other"},{"x":0.938,"y":0.556,"fill":"other"},{"x":0.924,"y":0.56,"fill":"other"},{"x":0.908,"y":0.558,"fill":"other"},{"x":0.902,"y":0.517,"fill":"other"},{"x":0.883,"y":0.52,"fill":"other"},{"x":0.86,"y":0.519,"fill":"other"},{"x":0.87,"y":0.535,"fill":"other"},{"x":0.858,"y":0.529,"fill":"other"},{"x":0.838,"y":0.53,"fill":"other"},{"x":0.826,"y":0.531,"fill":"other"},{"x":0.87,"y":0.556,"fill":"other"},{"x":0.88,"y":0.555,"fill":"other"},{"x":0.862,"y":0.556,"fill":"other"},{"x":0.86,"y":0.564,"fill":"other"},{"x":0.844,"y":0.561,"fill":"other"},{"x":0.841,"y":0.544,"fill":"other"},{"x":0.955,"y":0.576,"fill":"other"},{"x":0.929,"y":0.577,"fill":"other"},{"x":0.923,"y":0.572,"fill":"other"},{"x":0.899,"y":0.574,"fill":"other"},{"x":0.876,"y":0.574,"fill":"other"},{"x":0.86,"y":0.568,"fill":"other"},{"x":0.854,"y":0.573,"fill":"other"},{"x":0.851,"y":0.553,"fill":"other"},{"x":0.84,"y":0.553,"fill":"other"},{"x":0.85,"y":0.557,"fill":"other"},{"x":0.83,"y":0.541,"fill":"other"},{"x":0.822,"y":0.534,"fill":"other"},{"x":0.835,"y":0.539,"fill":"other"},{"x":0.817,"y":0.539,"fill":"other"},{"x":0.8,"y":0.54,"fill":"other"},{"x":0.785,"y":0.541,"fill":"other"},{"x":0.795,"y":0.553,"fill":"other"},{"x":0.781,"y":0.552,"fill":"other"},{"x":0.768,"y":0.553,"fill":"other"},{"x":0.757,"y":0.543,"fill":"other"},{"x":0.754,"y":0.545,"fill":"other"},{"x":0.754,"y":0.511,"fill":"other"},{"x":0.778,"y":0.483,"fill":"other"},{"x":0.789,"y":0.49,"fill":"other"},{"x":0.869,"y":0.535,"fill":"other"},{"x":0.874,"y":0.546,"fill":"other"},{"x":0.861,"y":0.538,"fill":"other"},{"x":0.847,"y":0.538,"fill":"other"},{"x":0.855,"y":0.543,"fill":"other"},{"x":0.842,"y":0.547,"fill":"other"},{"x":0.826,"y":0.547,"fill":"other"},{"x":0.835,"y":0.543,"fill":"other"},{"x":0.826,"y":0.526,"fill":"other"},{"x":0.832,"y":0.532,"fill":"other"},{"x":0.833,"y":0.522,"fill":"other"},{"x":0.824,"y":0.526,"fill":"other"},{"x":0.809,"y":0.524,"fill":"other"},{"x":0.847,"y":0.541,"fill":"other"},{"x":0.828,"y":0.538,"fill":"other"},{"x":0.813,"y":0.539,"fill":"other"},{"x":0.798,"y":0.535,"fill":"other"},{"x":0.807,"y":0.541,"fill":"other"},{"x":0.822,"y":0.557,"fill":"other"},{"x":0.804,"y":0.558,"fill":"other"},{"x":0.795,"y":0.553,"fill":"other"},{"x":0.787,"y":0.542,"fill":"other"},{"x":0.803,"y":0.547,"fill":"other"},{"x":0.795,"y":0.54,"fill":"other"},{"x":0.816,"y":0.541,"fill":"other"},{"x":0.807,"y":0.546,"fill":"other"},{"x":0.792,"y":0.547,"fill":"other"},{"x":0.778,"y":0.545,"fill":"other"},{"x":0.765,"y":0.545,"fill":"other"},{"x":0.754,"y":0.541,"fill":"other"},{"x":0.751,"y":0.51,"fill":"other"},{"x":0.814,"y":0.52,"fill":"other"},{"x":0.797,"y":0.521,"fill":"other"},{"x":0.823,"y":0.538,"fill":"other"},{"x":0.805,"y":0.539,"fill":"other"},{"x":0.793,"y":0.539,"fill":"other"},{"x":0.779,"y":0.528,"fill":"other"},{"x":0.767,"y":0.529,"fill":"other"},{"x":0.757,"y":0.531,"fill":"other"},{"x":0.761,"y":0.536,"fill":"other"},{"x":0.752,"y":0.537,"fill":"other"},{"x":0.755,"y":0.546,"fill":"other"},{"x":0.744,"y":0.547,"fill":"other"},{"x":0.745,"y":0.551,"fill":"other"},{"x":0.735,"y":0.55,"fill":"other"},{"x":0.733,"y":0.541,"fill":"other"},{"x":0.746,"y":0.546,"fill":"other"},{"x":0.753,"y":0.553,"fill":"other"},{"x":0.744,"y":0.545,"fill":"other"},{"x":0.736,"y":0.547,"fill":"other"},{"x":0.727,"y":0.531,"fill":"other"},{"x":0.721,"y":0.532,"fill":"other"},{"x":0.729,"y":0.536,"fill":"other"},{"x":0.875,"y":0.488,"fill":"other"},{"x":1.21,"y":0.407,"fill":"other"},{"x":1.16,"y":0.409,"fill":"other"},{"x":1.123,"y":0.399,"fill":"other"},{"x":1.081,"y":0.399,"fill":"other"},{"x":1.048,"y":0.397,"fill":"other"},{"x":1.021,"y":0.399,"fill":"other"},{"x":1.032,"y":0.396,"fill":"other"},{"x":0.998,"y":0.399,"fill":"other"},{"x":0.975,"y":0.407,"fill":"other"},{"x":0.949,"y":0.412,"fill":"other"},{"x":0.924,"y":0.415,"fill":"other"},{"x":0.898,"y":0.417,"fill":"other"},{"x":0.958,"y":0.439,"fill":"other"},{"x":0.951,"y":0.376,"fill":"other"},{"x":0.947,"y":0.371,"fill":"other"},{"x":0.929,"y":0.335,"fill":"other"},{"x":0.902,"y":0.336,"fill":"other"},{"x":0.882,"y":0.33,"fill":"other"},{"x":1.016,"y":0.32,"fill":"other"},{"x":0.982,"y":0.322,"fill":"other"},{"x":0.958,"y":0.324,"fill":"other"},{"x":0.933,"y":0.33,"fill":"other"},{"x":0.917,"y":0.319,"fill":"other"},{"x":0.896,"y":0.326,"fill":"other"},{"x":0.96,"y":0.372,"fill":"other"},{"x":0.947,"y":0.373,"fill":"other"},{"x":0.924,"y":0.374,"fill":"other"},{"x":0.922,"y":0.377,"fill":"other"},{"x":0.916,"y":0.388,"fill":"other"},{"x":0.901,"y":0.393,"fill":"other"},{"x":0.881,"y":0.39,"fill":"other"},{"x":0.947,"y":0.395,"fill":"other"},{"x":0.949,"y":0.406,"fill":"other"},{"x":0.937,"y":0.41,"fill":"other"},{"x":0.914,"y":0.414,"fill":"other"},{"x":0.959,"y":0.408,"fill":"other"},{"x":0.961,"y":0.421,"fill":"other"},{"x":0.966,"y":0.417,"fill":"other"},{"x":0.936,"y":0.419,"fill":"other"},{"x":0.917,"y":0.425,"fill":"other"},{"x":0.892,"y":0.421,"fill":"other"},{"x":0.878,"y":0.429,"fill":"other"},{"x":0.868,"y":0.431,"fill":"other"},{"x":0.965,"y":0.451,"fill":"other"},{"x":0.944,"y":0.453,"fill":"other"},{"x":0.916,"y":0.455,"fill":"other"},{"x":0.892,"y":0.455,"fill":"other"},{"x":0.871,"y":0.448,"fill":"other"},{"x":0.853,"y":0.448,"fill":"other"},{"x":0.869,"y":0.472,"fill":"other"},{"x":0.856,"y":0.477,"fill":"other"},{"x":0.885,"y":0.47,"fill":"other"},{"x":0.999,"y":0.444,"fill":"other"},{"x":0.966,"y":0.446,"fill":"other"},{"x":0.991,"y":0.433,"fill":"other"},{"x":0.959,"y":0.433,"fill":"other"},{"x":0.947,"y":0.43,"fill":"other"},{"x":0.971,"y":0.449,"fill":"other"},{"x":0.941,"y":0.45,"fill":"other"},{"x":0.919,"y":0.453,"fill":"other"},{"x":0.893,"y":0.454,"fill":"other"},{"x":0.878,"y":0.455,"fill":"other"},{"x":0.874,"y":0.467,"fill":"other"},{"x":0.986,"y":0.484,"fill":"other"},{"x":0.988,"y":0.494,"fill":"other"},{"x":0.957,"y":0.495,"fill":"other"},{"x":0.973,"y":0.506,"fill":"other"},{"x":0.948,"y":0.509,"fill":"other"},{"x":0.923,"y":0.512,"fill":"other"},{"x":0.9,"y":0.514,"fill":"other"},{"x":0.878,"y":0.512,"fill":"other"},{"x":0.923,"y":0.541,"fill":"other"},{"x":0.902,"y":0.544,"fill":"other"},{"x":0.878,"y":0.541,"fill":"other"},{"x":0.863,"y":0.516,"fill":"other"},{"x":0.869,"y":0.53,"fill":"other"},{"x":0.951,"y":0.528,"fill":"other"},{"x":0.97,"y":0.538,"fill":"other"},{"x":0.956,"y":0.544,"fill":"other"},{"x":0.934,"y":0.547,"fill":"other"},{"x":0.918,"y":0.55,"fill":"other"},{"x":0.901,"y":0.552,"fill":"other"},{"x":0.877,"y":0.551,"fill":"other"},{"x":0.879,"y":0.545,"fill":"other"},{"x":0.857,"y":0.546,"fill":"other"},{"x":0.92,"y":0.556,"fill":"other"},{"x":1.063,"y":0.617,"fill":"other"},{"x":1.03,"y":0.618,"fill":"other"},{"x":1.077,"y":0.624,"fill":"other"},{"x":1.075,"y":0.617,"fill":"other"},{"x":1.036,"y":0.617,"fill":"other"},{"x":1,"y":0.617,"fill":"other"},{"x":1.011,"y":0.601,"fill":"other"},{"x":1.015,"y":0.598,"fill":"other"},{"x":0.981,"y":0.59,"fill":"other"},{"x":0.951,"y":0.591,"fill":"other"},{"x":0.925,"y":0.59,"fill":"other"},{"x":1.126,"y":0.629,"fill":"other"},{"x":1.086,"y":0.628,"fill":"other"},{"x":1.05,"y":0.626,"fill":"other"},{"x":1.045,"y":0.633,"fill":"other"},{"x":1.024,"y":0.616,"fill":"other"},{"x":0.991,"y":0.614,"fill":"other"},{"x":0.959,"y":0.601,"fill":"other"},{"x":1.032,"y":0.631,"fill":"other"},{"x":1.002,"y":0.627,"fill":"other"},{"x":1.026,"y":0.624,"fill":"other"},{"x":1.001,"y":0.622,"fill":"other"},{"x":0.973,"y":0.621,"fill":"other"},{"x":1.045,"y":0.64,"fill":"other"},{"x":1.009,"y":0.639,"fill":"other"},{"x":0.976,"y":0.639,"fill":"other"},{"x":0.945,"y":0.639,"fill":"other"},{"x":1.023,"y":0.629,"fill":"other"},{"x":0.988,"y":0.62,"fill":"other"},{"x":0.969,"y":0.623,"fill":"other"},{"x":0.946,"y":0.625,"fill":"other"},{"x":0.995,"y":0.635,"fill":"other"},{"x":0.965,"y":0.633,"fill":"other"},{"x":0.977,"y":0.634,"fill":"other"},{"x":0.967,"y":0.639,"fill":"other"},{"x":0.937,"y":0.636,"fill":"other"},{"x":1.009,"y":0.616,"fill":"other"},{"x":1.041,"y":0.607,"fill":"other"},{"x":1.01,"y":0.572,"fill":"other"},{"x":1.016,"y":0.532,"fill":"other"},{"x":0.982,"y":0.532,"fill":"other"},{"x":0.973,"y":0.529,"fill":"other"},{"x":0.99,"y":0.532,"fill":"other"},{"x":0.98,"y":0.54,"fill":"other"},{"x":0.963,"y":0.524,"fill":"other"},{"x":0.934,"y":0.516,"fill":"other"},{"x":0.907,"y":0.517,"fill":"other"},{"x":0.882,"y":0.51,"fill":"other"},{"x":1.027,"y":0.543,"fill":"other"},{"x":1.11,"y":0.543,"fill":"other"},{"x":1.072,"y":0.54,"fill":"other"},{"x":1.127,"y":0.523,"fill":"other"},{"x":1.097,"y":0.527,"fill":"other"},{"x":1.056,"y":0.52,"fill":"other"},{"x":1.109,"y":0.516,"fill":"other"},{"x":1.116,"y":0.501,"fill":"other"},{"x":1.146,"y":0.49,"fill":"other"},{"x":1.123,"y":0.498,"fill":"other"},{"x":1.172,"y":0.479,"fill":"other"},{"x":1.128,"y":0.481,"fill":"other"},{"x":1.153,"y":0.49,"fill":"other"},{"x":1.183,"y":0.511,"fill":"other"},{"x":1.145,"y":0.513,"fill":"other"},{"x":1.101,"y":0.506,"fill":"other"},{"x":1.211,"y":0.522,"fill":"other"},{"x":1.163,"y":0.518,"fill":"other"},{"x":1.278,"y":0.554,"fill":"other"},{"x":1.224,"y":0.553,"fill":"other"},{"x":1.189,"y":0.547,"fill":"other"},{"x":1.142,"y":0.543,"fill":"other"},{"x":1.108,"y":0.546,"fill":"other"},{"x":1.071,"y":0.548,"fill":"other"},{"x":1.087,"y":0.558,"fill":"other"},{"x":1.047,"y":0.557,"fill":"other"},{"x":1.058,"y":0.556,"fill":"other"},{"x":1.083,"y":0.572,"fill":"other"},{"x":1.096,"y":0.583,"fill":"other"},{"x":1.056,"y":0.579,"fill":"other"},{"x":1.065,"y":0.578,"fill":"other"},{"x":1.258,"y":0.628,"fill":"other"},{"x":1.211,"y":0.624,"fill":"other"},{"x":1.208,"y":0.632,"fill":"other"},{"x":1.303,"y":0.653,"fill":"other"},{"x":1.348,"y":0.656,"fill":"volatile"},{"x":1.326,"y":0.65,"fill":"volatile"},{"x":1.328,"y":0.656,"fill":"volatile"},{"x":1.436,"y":0.659,"fill":"volatile"},{"x":1.374,"y":0.654,"fill":"volatile"},{"x":1.317,"y":0.654,"fill":"other"},{"x":1.262,"y":0.651,"fill":"other"},{"x":1.244,"y":0.656,"fill":"other"},{"x":1.442,"y":0.667,"fill":"volatile"},{"x":1.379,"y":0.665,"fill":"volatile"},{"x":1.326,"y":0.665,"fill":"volatile"},{"x":1.272,"y":0.662,"fill":"other"},{"x":1.246,"y":0.666,"fill":"other"},{"x":1.202,"y":0.666,"fill":"other"},{"x":1.159,"y":0.666,"fill":"other"},{"x":1.14,"y":0.626,"fill":"other"},{"x":1.122,"y":0.632,"fill":"other"},{"x":1.08,"y":0.631,"fill":"other"},{"x":1.075,"y":0.626,"fill":"other"},{"x":1.039,"y":0.626,"fill":"other"},{"x":1.014,"y":0.628,"fill":"other"},{"x":0.988,"y":0.629,"fill":"other"},{"x":0.956,"y":0.629,"fill":"other"},{"x":0.927,"y":0.629,"fill":"other"},{"x":0.984,"y":0.639,"fill":"other"},{"x":0.955,"y":0.639,"fill":"other"},{"x":0.946,"y":0.633,"fill":"other"},{"x":0.918,"y":0.633,"fill":"other"},{"x":0.923,"y":0.64,"fill":"other"},{"x":0.914,"y":0.631,"fill":"other"},{"x":0.889,"y":0.628,"fill":"other"},{"x":0.892,"y":0.631,"fill":"other"},{"x":0.881,"y":0.633,"fill":"other"},{"x":0.86,"y":0.617,"fill":"other"},{"x":0.893,"y":0.617,"fill":"other"},{"x":0.87,"y":0.609,"fill":"other"},{"x":0.848,"y":0.609,"fill":"other"},{"x":0.869,"y":0.62,"fill":"other"},{"x":0.857,"y":0.623,"fill":"other"},{"x":0.914,"y":0.626,"fill":"other"},{"x":0.903,"y":0.631,"fill":"other"},{"x":0.91,"y":0.637,"fill":"other"},{"x":0.898,"y":0.631,"fill":"other"},{"x":0.886,"y":0.627,"fill":"other"},{"x":0.866,"y":0.626,"fill":"other"},{"x":0.88,"y":0.636,"fill":"other"},{"x":0.861,"y":0.632,"fill":"other"},{"x":0.865,"y":0.628,"fill":"other"},{"x":0.865,"y":0.629,"fill":"other"},{"x":0.879,"y":0.64,"fill":"other"},{"x":0.859,"y":0.637,"fill":"other"},{"x":0.838,"y":0.636,"fill":"other"},{"x":0.824,"y":0.623,"fill":"other"},{"x":0.823,"y":0.616,"fill":"other"},{"x":0.809,"y":0.613,"fill":"other"},{"x":0.812,"y":0.614,"fill":"other"},{"x":0.804,"y":0.609,"fill":"other"},{"x":0.794,"y":0.606,"fill":"other"},{"x":0.779,"y":0.602,"fill":"other"},{"x":0.985,"y":0.601,"fill":"other"},{"x":1.141,"y":0.652,"fill":"other"},{"x":1.1,"y":0.651,"fill":"other"},{"x":1.141,"y":0.667,"fill":"other"},{"x":1.114,"y":0.664,"fill":"other"},{"x":1.074,"y":0.663,"fill":"other"},{"x":1.081,"y":0.672,"fill":"other"},{"x":1.043,"y":0.66,"fill":"other"},{"x":1.105,"y":0.658,"fill":"other"},{"x":1.064,"y":0.657,"fill":"other"},{"x":1.103,"y":0.65,"fill":"other"},{"x":1.07,"y":0.65,"fill":"other"},{"x":1.046,"y":0.651,"fill":"other"},{"x":1.018,"y":0.653,"fill":"other"},{"x":1.236,"y":0.669,"fill":"other"},{"x":1.186,"y":0.666,"fill":"other"},{"x":1.157,"y":0.661,"fill":"other"},{"x":1.164,"y":0.664,"fill":"other"},{"x":1.139,"y":0.664,"fill":"other"},{"x":1.252,"y":0.688,"fill":"other"},{"x":1.267,"y":0.695,"fill":"other"},{"x":1.36,"y":0.694,"fill":"volatile"},{"x":1.344,"y":0.674,"fill":"volatile"},{"x":1.338,"y":0.675,"fill":"volatile"},{"x":1.281,"y":0.668,"fill":"other"},{"x":1.255,"y":0.668,"fill":"other"},{"x":1.227,"y":0.671,"fill":"other"},{"x":1.213,"y":0.675,"fill":"other"},{"x":1.187,"y":0.677,"fill":"other"},{"x":1.167,"y":0.681,"fill":"other"},{"x":1.178,"y":0.677,"fill":"other"},{"x":1.133,"y":0.676,"fill":"other"},{"x":1.109,"y":0.678,"fill":"other"},{"x":1.068,"y":0.677,"fill":"other"},{"x":1.061,"y":0.681,"fill":"other"},{"x":1.062,"y":0.684,"fill":"other"},{"x":1.024,"y":0.672,"fill":"other"},{"x":1.015,"y":0.676,"fill":"other"},{"x":1.057,"y":0.68,"fill":"other"},{"x":1.031,"y":0.679,"fill":"other"},{"x":1.005,"y":0.679,"fill":"other"},{"x":0.98,"y":0.68,"fill":"other"},{"x":0.95,"y":0.68,"fill":"other"},{"x":0.954,"y":0.682,"fill":"other"},{"x":0.927,"y":0.682,"fill":"other"},{"x":0.925,"y":0.682,"fill":"other"},{"x":0.965,"y":0.694,"fill":"other"},{"x":0.935,"y":0.69,"fill":"other"},{"x":0.93,"y":0.674,"fill":"other"},{"x":0.908,"y":0.675,"fill":"other"},{"x":0.957,"y":0.692,"fill":"other"},{"x":0.929,"y":0.691,"fill":"other"},{"x":0.921,"y":0.692,"fill":"other"},{"x":0.904,"y":0.693,"fill":"other"},{"x":0.884,"y":0.69,"fill":"other"},{"x":0.905,"y":0.684,"fill":"other"},{"x":0.882,"y":0.682,"fill":"other"},{"x":0.871,"y":0.684,"fill":"other"},{"x":0.898,"y":0.67,"fill":"other"},{"x":0.873,"y":0.669,"fill":"other"},{"x":0.876,"y":0.666,"fill":"other"},{"x":0.867,"y":0.665,"fill":"other"},{"x":0.869,"y":0.665,"fill":"other"},{"x":0.854,"y":0.66,"fill":"other"},{"x":0.921,"y":0.666,"fill":"other"},{"x":0.898,"y":0.665,"fill":"other"},{"x":0.883,"y":0.666,"fill":"other"},{"x":0.891,"y":0.673,"fill":"other"},{"x":0.968,"y":0.684,"fill":"other"},{"x":0.979,"y":0.675,"fill":"other"},{"x":0.957,"y":0.676,"fill":"other"},{"x":0.928,"y":0.676,"fill":"other"},{"x":0.941,"y":0.685,"fill":"other"},{"x":0.921,"y":0.684,"fill":"other"},{"x":0.944,"y":0.651,"fill":"other"},{"x":0.938,"y":0.656,"fill":"other"},{"x":0.916,"y":0.654,"fill":"other"},{"x":0.897,"y":0.635,"fill":"other"},{"x":0.919,"y":0.649,"fill":"other"},{"x":0.893,"y":0.648,"fill":"other"},{"x":0.869,"y":0.647,"fill":"other"},{"x":0.981,"y":0.672,"fill":"other"},{"x":0.957,"y":0.671,"fill":"other"},{"x":1.015,"y":0.69,"fill":"other"},{"x":0.981,"y":0.688,"fill":"other"},{"x":1.091,"y":0.706,"fill":"other"},{"x":1.054,"y":0.695,"fill":"other"},{"x":1.019,"y":0.694,"fill":"other"},{"x":1.026,"y":0.69,"fill":"other"},{"x":1.117,"y":0.699,"fill":"other"},{"x":1.075,"y":0.697,"fill":"other"},{"x":1.047,"y":0.698,"fill":"other"},{"x":1.236,"y":0.719,"fill":"other"},{"x":1.201,"y":0.695,"fill":"other"},{"x":1.152,"y":0.68,"fill":"other"},{"x":1.124,"y":0.668,"fill":"other"},{"x":1.226,"y":0.686,"fill":"other"},{"x":1.199,"y":0.689,"fill":"other"},{"x":1.16,"y":0.689,"fill":"other"},{"x":1.435,"y":0.689,"fill":"volatile"},{"x":1.45,"y":0.697,"fill":"volatile"},{"x":1.399,"y":0.682,"fill":"volatile"},{"x":1.402,"y":0.689,"fill":"volatile"},{"x":1.344,"y":0.675,"fill":"volatile"},{"x":1.319,"y":0.664,"fill":"other"},{"x":1.308,"y":0.67,"fill":"other"},{"x":1.266,"y":0.671,"fill":"other"},{"x":1.218,"y":0.67,"fill":"other"},{"x":1.242,"y":0.678,"fill":"other"},{"x":1.192,"y":0.676,"fill":"other"},{"x":1.201,"y":0.683,"fill":"other"},{"x":1.164,"y":0.68,"fill":"other"},{"x":1.136,"y":0.682,"fill":"other"},{"x":1.191,"y":0.697,"fill":"other"},{"x":1.145,"y":0.694,"fill":"other"},{"x":1.101,"y":0.693,"fill":"other"},{"x":1.117,"y":0.694,"fill":"other"},{"x":1.105,"y":0.697,"fill":"other"},{"x":1.067,"y":0.694,"fill":"other"},{"x":1.086,"y":0.702,"fill":"other"},{"x":1.057,"y":0.698,"fill":"other"},{"x":1.101,"y":0.708,"fill":"other"},{"x":1.063,"y":0.707,"fill":"other"},{"x":1.074,"y":0.713,"fill":"other"},{"x":1.055,"y":0.715,"fill":"other"},{"x":1.047,"y":0.718,"fill":"other"},{"x":1.01,"y":0.716,"fill":"other"},{"x":1.013,"y":0.719,"fill":"other"},{"x":0.98,"y":0.718,"fill":"other"},{"x":0.952,"y":0.713,"fill":"other"},{"x":0.976,"y":0.722,"fill":"other"},{"x":1.042,"y":0.738,"fill":"other"},{"x":1.03,"y":0.736,"fill":"other"},{"x":0.996,"y":0.735,"fill":"other"},{"x":0.967,"y":0.729,"fill":"other"},{"x":0.959,"y":0.715,"fill":"other"},{"x":0.962,"y":0.718,"fill":"other"},{"x":0.947,"y":0.716,"fill":"other"},{"x":0.92,"y":0.713,"fill":"other"},{"x":0.943,"y":0.713,"fill":"other"},{"x":0.955,"y":0.716,"fill":"other"},{"x":0.927,"y":0.715,"fill":"other"},{"x":0.901,"y":0.715,"fill":"other"},{"x":0.91,"y":0.721,"fill":"other"},{"x":0.929,"y":0.728,"fill":"other"},{"x":0.921,"y":0.724,"fill":"other"},{"x":0.933,"y":0.731,"fill":"other"},{"x":0.918,"y":0.723,"fill":"other"},{"x":0.91,"y":0.724,"fill":"other"},{"x":0.887,"y":0.715,"fill":"other"},{"x":0.877,"y":0.717,"fill":"other"},{"x":0.873,"y":0.717,"fill":"other"},{"x":0.853,"y":0.716,"fill":"other"},{"x":0.833,"y":0.716,"fill":"other"},{"x":0.815,"y":0.715,"fill":"other"},{"x":0.805,"y":0.712,"fill":"other"},{"x":0.81,"y":0.695,"fill":"other"},{"x":0.849,"y":0.706,"fill":"other"},{"x":0.872,"y":0.693,"fill":"other"},{"x":0.885,"y":0.686,"fill":"other"},{"x":0.874,"y":0.683,"fill":"other"},{"x":0.853,"y":0.677,"fill":"other"},{"x":0.881,"y":0.684,"fill":"other"},{"x":0.861,"y":0.677,"fill":"other"},{"x":0.844,"y":0.678,"fill":"other"},{"x":0.829,"y":0.677,"fill":"other"},{"x":0.811,"y":0.675,"fill":"other"},{"x":0.796,"y":0.673,"fill":"other"},{"x":0.782,"y":0.672,"fill":"other"},{"x":0.82,"y":0.684,"fill":"other"},{"x":0.81,"y":0.684,"fill":"other"},{"x":0.794,"y":0.683,"fill":"other"},{"x":0.785,"y":0.682,"fill":"other"},{"x":0.86,"y":0.7,"fill":"other"},{"x":0.979,"y":0.724,"fill":"other"},{"x":0.963,"y":0.725,"fill":"other"},{"x":0.934,"y":0.721,"fill":"other"},{"x":0.92,"y":0.723,"fill":"other"},{"x":0.906,"y":0.71,"fill":"other"},{"x":0.884,"y":0.705,"fill":"other"},{"x":0.862,"y":0.705,"fill":"other"},{"x":0.884,"y":0.712,"fill":"other"},{"x":0.871,"y":0.697,"fill":"other"},{"x":0.978,"y":0.701,"fill":"other"},{"x":0.949,"y":0.7,"fill":"other"},{"x":0.924,"y":0.7,"fill":"other"},{"x":0.901,"y":0.699,"fill":"other"},{"x":0.946,"y":0.708,"fill":"other"},{"x":0.924,"y":0.708,"fill":"other"},{"x":0.906,"y":0.706,"fill":"other"},{"x":0.886,"y":0.698,"fill":"other"},{"x":0.866,"y":0.697,"fill":"other"},{"x":0.898,"y":0.706,"fill":"other"},{"x":0.877,"y":0.701,"fill":"other"},{"x":0.885,"y":0.708,"fill":"other"},{"x":0.862,"y":0.707,"fill":"other"},{"x":0.845,"y":0.707,"fill":"other"},{"x":0.899,"y":0.719,"fill":"other"},{"x":0.884,"y":0.72,"fill":"other"},{"x":0.876,"y":0.722,"fill":"other"},{"x":0.862,"y":0.723,"fill":"other"},{"x":0.909,"y":0.735,"fill":"other"},{"x":0.896,"y":0.733,"fill":"other"},{"x":0.921,"y":0.735,"fill":"other"},{"x":0.951,"y":0.742,"fill":"other"},{"x":0.998,"y":0.751,"fill":"other"},{"x":0.98,"y":0.735,"fill":"other"},{"x":1.091,"y":0.716,"fill":"other"},{"x":1.078,"y":0.717,"fill":"other"},{"x":1.142,"y":0.713,"fill":"other"},{"x":1.258,"y":0.731,"fill":"other"},{"x":1.262,"y":0.726,"fill":"other"},{"x":1.235,"y":0.721,"fill":"other"},{"x":1.284,"y":0.712,"fill":"other"},{"x":1.23,"y":0.702,"fill":"other"},{"x":1.18,"y":0.7,"fill":"other"},{"x":1.137,"y":0.698,"fill":"other"},{"x":1.243,"y":0.681,"fill":"other"},{"x":1.191,"y":0.677,"fill":"other"},{"x":1.149,"y":0.677,"fill":"other"},{"x":1.132,"y":0.681,"fill":"other"},{"x":1.092,"y":0.681,"fill":"other"},{"x":1.125,"y":0.692,"fill":"other"},{"x":1.189,"y":0.707,"fill":"other"},{"x":1.17,"y":0.705,"fill":"other"},{"x":1.191,"y":0.714,"fill":"other"},{"x":1.145,"y":0.713,"fill":"other"},{"x":1.102,"y":0.712,"fill":"other"},{"x":1.061,"y":0.711,"fill":"other"},{"x":1.023,"y":0.709,"fill":"other"},{"x":0.989,"y":0.707,"fill":"other"},{"x":0.967,"y":0.708,"fill":"other"},{"x":0.945,"y":0.707,"fill":"other"},{"x":0.916,"y":0.706,"fill":"other"},{"x":0.891,"y":0.706,"fill":"other"},{"x":0.952,"y":0.706,"fill":"other"},{"x":0.937,"y":0.708,"fill":"other"},{"x":0.92,"y":0.706,"fill":"other"},{"x":0.984,"y":0.715,"fill":"other"},{"x":0.962,"y":0.707,"fill":"other"},{"x":0.998,"y":0.699,"fill":"other"},{"x":0.998,"y":0.7,"fill":"other"},{"x":0.968,"y":0.699,"fill":"other"},{"x":0.943,"y":0.698,"fill":"other"},{"x":0.915,"y":0.697,"fill":"other"},{"x":0.917,"y":0.703,"fill":"other"},{"x":0.891,"y":0.699,"fill":"other"},{"x":0.869,"y":0.698,"fill":"other"},{"x":0.867,"y":0.701,"fill":"other"},{"x":0.852,"y":0.698,"fill":"other"},{"x":0.866,"y":0.697,"fill":"other"},{"x":0.859,"y":0.698,"fill":"other"},{"x":0.878,"y":0.707,"fill":"other"},{"x":0.874,"y":0.692,"fill":"other"},{"x":0.865,"y":0.689,"fill":"other"},{"x":0.866,"y":0.67,"fill":"other"},{"x":0.887,"y":0.666,"fill":"other"},{"x":0.868,"y":0.666,"fill":"other"},{"x":0.886,"y":0.676,"fill":"other"},{"x":0.947,"y":0.687,"fill":"other"},{"x":0.937,"y":0.678,"fill":"other"},{"x":0.946,"y":0.685,"fill":"other"},{"x":0.918,"y":0.685,"fill":"other"},{"x":1.032,"y":0.688,"fill":"other"},{"x":0.997,"y":0.687,"fill":"other"},{"x":0.974,"y":0.683,"fill":"other"},{"x":0.967,"y":0.684,"fill":"other"},{"x":0.963,"y":0.689,"fill":"other"},{"x":0.945,"y":0.687,"fill":"other"},{"x":0.917,"y":0.666,"fill":"other"},{"x":0.924,"y":0.661,"fill":"other"},{"x":0.926,"y":0.663,"fill":"other"},{"x":0.899,"y":0.661,"fill":"other"},{"x":0.957,"y":0.682,"fill":"other"},{"x":0.958,"y":0.68,"fill":"other"},{"x":0.93,"y":0.679,"fill":"other"},{"x":0.903,"y":0.677,"fill":"other"},{"x":0.88,"y":0.668,"fill":"other"},{"x":0.862,"y":0.669,"fill":"other"},{"x":0.906,"y":0.671,"fill":"other"},{"x":0.9,"y":0.67,"fill":"other"},{"x":0.877,"y":0.669,"fill":"other"},{"x":0.854,"y":0.656,"fill":"other"},{"x":0.834,"y":0.646,"fill":"other"},{"x":0.823,"y":0.605,"fill":"other"},{"x":0.814,"y":0.602,"fill":"other"},{"x":0.933,"y":0.617,"fill":"other"},{"x":0.906,"y":0.617,"fill":"other"},{"x":0.885,"y":0.607,"fill":"other"},{"x":0.87,"y":0.609,"fill":"other"},{"x":0.855,"y":0.611,"fill":"other"},{"x":0.838,"y":0.604,"fill":"other"},{"x":0.825,"y":0.605,"fill":"other"},{"x":1.018,"y":0.661,"fill":"other"},{"x":1.011,"y":0.65,"fill":"other"},{"x":0.982,"y":0.65,"fill":"other"},{"x":0.952,"y":0.646,"fill":"other"},{"x":0.928,"y":0.646,"fill":"other"},{"x":0.903,"y":0.646,"fill":"other"},{"x":0.884,"y":0.647,"fill":"other"},{"x":0.89,"y":0.652,"fill":"other"},{"x":0.875,"y":0.641,"fill":"other"},{"x":0.867,"y":0.641,"fill":"other"},{"x":0.857,"y":0.642,"fill":"other"},{"x":0.928,"y":0.642,"fill":"other"},{"x":0.901,"y":0.642,"fill":"other"},{"x":0.878,"y":0.641,"fill":"other"},{"x":0.855,"y":0.64,"fill":"other"},{"x":0.877,"y":0.621,"fill":"other"},{"x":0.855,"y":0.619,"fill":"other"},{"x":0.848,"y":0.622,"fill":"other"},{"x":0.934,"y":0.652,"fill":"other"},{"x":0.926,"y":0.657,"fill":"other"},{"x":0.9,"y":0.656,"fill":"other"},{"x":0.878,"y":0.655,"fill":"other"},{"x":0.862,"y":0.657,"fill":"other"},{"x":0.862,"y":0.653,"fill":"other"},{"x":0.855,"y":0.652,"fill":"other"},{"x":0.842,"y":0.653,"fill":"other"},{"x":0.861,"y":0.663,"fill":"other"},{"x":0.897,"y":0.651,"fill":"other"},{"x":0.887,"y":0.655,"fill":"other"},{"x":0.864,"y":0.655,"fill":"other"},{"x":0.851,"y":0.652,"fill":"other"},{"x":0.831,"y":0.647,"fill":"other"},{"x":0.825,"y":0.647,"fill":"other"},{"x":0.808,"y":0.642,"fill":"other"},{"x":0.8,"y":0.638,"fill":"other"},{"x":0.785,"y":0.638,"fill":"other"},{"x":0.801,"y":0.632,"fill":"other"},{"x":0.797,"y":0.636,"fill":"other"},{"x":0.814,"y":0.627,"fill":"other"},{"x":0.826,"y":0.637,"fill":"other"},{"x":0.813,"y":0.635,"fill":"other"},{"x":0.826,"y":0.637,"fill":"other"},{"x":0.808,"y":0.637,"fill":"other"},{"x":0.792,"y":0.626,"fill":"other"},{"x":0.779,"y":0.627,"fill":"other"},{"x":0.766,"y":0.627,"fill":"other"},{"x":0.754,"y":0.626,"fill":"other"},{"x":0.744,"y":0.626,"fill":"other"},{"x":0.827,"y":0.649,"fill":"other"},{"x":0.809,"y":0.649,"fill":"other"},{"x":0.794,"y":0.648,"fill":"other"},{"x":0.805,"y":0.657,"fill":"other"},{"x":0.809,"y":0.657,"fill":"other"},{"x":0.808,"y":0.632,"fill":"other"},{"x":0.824,"y":0.629,"fill":"other"},{"x":1.171,"y":0.668,"fill":"other"},{"x":1.128,"y":0.664,"fill":"other"},{"x":1.105,"y":0.666,"fill":"other"},{"x":1.176,"y":0.685,"fill":"other"},{"x":1.134,"y":0.685,"fill":"other"},{"x":1.106,"y":0.686,"fill":"other"},{"x":1.067,"y":0.682,"fill":"other"},{"x":1.028,"y":0.681,"fill":"other"},{"x":1.005,"y":0.683,"fill":"other"},{"x":1.005,"y":0.678,"fill":"other"},{"x":0.992,"y":0.681,"fill":"other"},{"x":0.99,"y":0.686,"fill":"other"},{"x":0.994,"y":0.687,"fill":"other"},{"x":0.979,"y":0.688,"fill":"other"},{"x":0.95,"y":0.67,"fill":"other"},{"x":1.067,"y":0.689,"fill":"other"},{"x":1.042,"y":0.69,"fill":"other"},{"x":1.012,"y":0.687,"fill":"other"},{"x":0.986,"y":0.687,"fill":"other"},{"x":0.993,"y":0.689,"fill":"other"},{"x":1.024,"y":0.697,"fill":"other"},{"x":1.067,"y":0.7,"fill":"other"},{"x":1.03,"y":0.699,"fill":"other"},{"x":1.039,"y":0.691,"fill":"other"},{"x":1.003,"y":0.686,"fill":"other"},{"x":1.047,"y":0.692,"fill":"other"},{"x":1.104,"y":0.687,"fill":"other"},{"x":1.078,"y":0.689,"fill":"other"},{"x":1.054,"y":0.678,"fill":"other"},{"x":1.017,"y":0.677,"fill":"other"},{"x":0.994,"y":0.679,"fill":"other"},{"x":0.962,"y":0.675,"fill":"other"},{"x":0.933,"y":0.675,"fill":"other"},{"x":0.911,"y":0.676,"fill":"other"},{"x":0.887,"y":0.674,"fill":"other"},{"x":0.87,"y":0.675,"fill":"other"},{"x":0.878,"y":0.677,"fill":"other"},{"x":0.856,"y":0.676,"fill":"other"},{"x":0.836,"y":0.665,"fill":"other"},{"x":0.817,"y":0.646,"fill":"other"},{"x":0.801,"y":0.646,"fill":"other"},{"x":0.789,"y":0.647,"fill":"other"},{"x":0.776,"y":0.642,"fill":"other"},{"x":0.77,"y":0.619,"fill":"other"},{"x":0.758,"y":0.605,"fill":"other"},{"x":0.76,"y":0.61,"fill":"other"},{"x":0.857,"y":0.618,"fill":"other"},{"x":0.84,"y":0.618,"fill":"other"},{"x":0.823,"y":0.618,"fill":"other"},{"x":0.807,"y":0.619,"fill":"other"},{"x":0.8,"y":0.616,"fill":"other"},{"x":0.788,"y":0.613,"fill":"other"},{"x":0.778,"y":0.609,"fill":"other"},{"x":0.766,"y":0.608,"fill":"other"},{"x":0.776,"y":0.617,"fill":"other"},{"x":0.784,"y":0.599,"fill":"other"},{"x":0.77,"y":0.591,"fill":"other"},{"x":0.758,"y":0.592,"fill":"other"},{"x":0.747,"y":0.592,"fill":"other"},{"x":0.737,"y":0.592,"fill":"other"},{"x":0.729,"y":0.585,"fill":"other"},{"x":0.889,"y":0.638,"fill":"other"},{"x":0.866,"y":0.633,"fill":"other"},{"x":0.893,"y":0.647,"fill":"other"},{"x":0.87,"y":0.642,"fill":"other"},{"x":0.857,"y":0.645,"fill":"other"},{"x":0.837,"y":0.645,"fill":"other"},{"x":0.818,"y":0.645,"fill":"other"},{"x":0.801,"y":0.639,"fill":"other"},{"x":0.791,"y":0.638,"fill":"other"},{"x":0.795,"y":0.623,"fill":"other"},{"x":0.78,"y":0.623,"fill":"other"},{"x":0.927,"y":0.572,"fill":"other"},{"x":0.92,"y":0.58,"fill":"other"},{"x":0.896,"y":0.579,"fill":"other"},{"x":0.897,"y":0.583,"fill":"other"},{"x":0.9,"y":0.589,"fill":"other"},{"x":0.888,"y":0.585,"fill":"other"},{"x":0.876,"y":0.578,"fill":"other"},{"x":0.862,"y":0.582,"fill":"other"},{"x":0.874,"y":0.576,"fill":"other"},{"x":0.855,"y":0.577,"fill":"other"},{"x":0.854,"y":0.583,"fill":"other"},{"x":0.835,"y":0.585,"fill":"other"},{"x":0.828,"y":0.587,"fill":"other"},{"x":0.817,"y":0.585,"fill":"other"},{"x":0.808,"y":0.582,"fill":"other"},{"x":0.791,"y":0.578,"fill":"other"},{"x":0.9,"y":0.584,"fill":"other"},{"x":0.876,"y":0.579,"fill":"other"},{"x":0.862,"y":0.577,"fill":"other"},{"x":0.853,"y":0.576,"fill":"other"},{"x":0.852,"y":0.571,"fill":"other"},{"x":0.834,"y":0.571,"fill":"other"},{"x":0.819,"y":0.567,"fill":"other"},{"x":0.816,"y":0.538,"fill":"other"},{"x":0.932,"y":0.569,"fill":"other"},{"x":0.929,"y":0.564,"fill":"other"},{"x":0.902,"y":0.557,"fill":"other"},{"x":0.945,"y":0.566,"fill":"other"},{"x":0.947,"y":0.566,"fill":"other"},{"x":0.922,"y":0.562,"fill":"other"},{"x":0.898,"y":0.563,"fill":"other"},{"x":0.88,"y":0.563,"fill":"other"},{"x":0.858,"y":0.547,"fill":"other"},{"x":0.839,"y":0.548,"fill":"other"},{"x":0.916,"y":0.568,"fill":"other"},{"x":0.907,"y":0.575,"fill":"other"},{"x":0.931,"y":0.576,"fill":"other"},{"x":0.926,"y":0.58,"fill":"other"},{"x":0.942,"y":0.571,"fill":"other"},{"x":0.923,"y":0.571,"fill":"other"},{"x":0.902,"y":0.573,"fill":"other"},{"x":0.957,"y":0.583,"fill":"other"},{"x":0.929,"y":0.583,"fill":"other"},{"x":0.902,"y":0.579,"fill":"other"},{"x":0.878,"y":0.575,"fill":"other"},{"x":0.872,"y":0.567,"fill":"other"},{"x":0.85,"y":0.565,"fill":"other"},{"x":0.833,"y":0.564,"fill":"other"},{"x":0.883,"y":0.594,"fill":"other"},{"x":0.921,"y":0.612,"fill":"other"},{"x":0.897,"y":0.607,"fill":"other"},{"x":0.873,"y":0.607,"fill":"other"},{"x":0.864,"y":0.611,"fill":"other"},{"x":0.881,"y":0.557,"fill":"other"},{"x":0.869,"y":0.562,"fill":"other"},{"x":0.854,"y":0.565,"fill":"other"},{"x":0.836,"y":0.563,"fill":"other"},{"x":0.827,"y":0.565,"fill":"other"},{"x":0.857,"y":0.547,"fill":"other"},{"x":0.907,"y":0.495,"fill":"other"},{"x":0.888,"y":0.499,"fill":"other"},{"x":0.882,"y":0.503,"fill":"other"},{"x":0.89,"y":0.499,"fill":"other"},{"x":0.881,"y":0.478,"fill":"other"},{"x":0.864,"y":0.482,"fill":"other"},{"x":0.845,"y":0.484,"fill":"other"},{"x":0.852,"y":0.485,"fill":"other"},{"x":0.836,"y":0.487,"fill":"other"},{"x":0.817,"y":0.489,"fill":"other"},{"x":0.8,"y":0.49,"fill":"other"},{"x":0.792,"y":0.49,"fill":"other"},{"x":0.79,"y":0.493,"fill":"other"},{"x":0.8,"y":0.506,"fill":"other"},{"x":0.804,"y":0.516,"fill":"other"},{"x":0.799,"y":0.523,"fill":"other"},{"x":0.785,"y":0.52,"fill":"other"},{"x":0.828,"y":0.532,"fill":"other"},{"x":0.81,"y":0.532,"fill":"other"},{"x":0.801,"y":0.536,"fill":"other"},{"x":0.795,"y":0.531,"fill":"other"},{"x":0.78,"y":0.529,"fill":"other"},{"x":0.812,"y":0.537,"fill":"other"},{"x":0.805,"y":0.536,"fill":"other"},{"x":0.789,"y":0.535,"fill":"other"},{"x":0.858,"y":0.552,"fill":"other"},{"x":0.852,"y":0.545,"fill":"other"},{"x":0.832,"y":0.544,"fill":"other"},{"x":0.868,"y":0.564,"fill":"other"},{"x":0.848,"y":0.55,"fill":"other"},{"x":0.829,"y":0.551,"fill":"other"},{"x":0.811,"y":0.539,"fill":"other"},{"x":0.805,"y":0.544,"fill":"other"},{"x":0.789,"y":0.543,"fill":"other"},{"x":0.825,"y":0.558,"fill":"other"},{"x":0.808,"y":0.559,"fill":"other"},{"x":0.852,"y":0.568,"fill":"other"},{"x":0.834,"y":0.568,"fill":"other"},{"x":0.815,"y":0.564,"fill":"other"},{"x":0.816,"y":0.573,"fill":"other"},{"x":0.808,"y":0.577,"fill":"other"},{"x":0.819,"y":0.578,"fill":"other"},{"x":0.821,"y":0.587,"fill":"other"},{"x":0.804,"y":0.586,"fill":"other"},{"x":0.789,"y":0.587,"fill":"other"},{"x":0.775,"y":0.587,"fill":"other"},{"x":0.766,"y":0.588,"fill":"other"},{"x":0.764,"y":0.574,"fill":"other"},{"x":0.767,"y":0.583,"fill":"other"},{"x":0.768,"y":0.58,"fill":"other"},{"x":0.779,"y":0.562,"fill":"other"},{"x":0.767,"y":0.563,"fill":"other"},{"x":0.755,"y":0.564,"fill":"other"},{"x":0.747,"y":0.565,"fill":"other"},{"x":0.779,"y":0.591,"fill":"other"},{"x":0.782,"y":0.597,"fill":"other"},{"x":0.786,"y":0.605,"fill":"other"},{"x":0.773,"y":0.602,"fill":"other"},{"x":0.762,"y":0.603,"fill":"other"},{"x":0.786,"y":0.603,"fill":"other"},{"x":0.773,"y":0.603,"fill":"other"},{"x":0.76,"y":0.602,"fill":"other"},{"x":0.755,"y":0.602,"fill":"other"},{"x":0.761,"y":0.611,"fill":"other"},{"x":0.763,"y":0.601,"fill":"other"},{"x":0.763,"y":0.586,"fill":"other"},{"x":0.765,"y":0.54,"fill":"other"},{"x":0.757,"y":0.531,"fill":"other"},{"x":0.779,"y":0.542,"fill":"other"},{"x":0.785,"y":0.554,"fill":"other"},{"x":0.771,"y":0.554,"fill":"other"},{"x":0.765,"y":0.553,"fill":"other"},{"x":0.753,"y":0.552,"fill":"other"},{"x":0.75,"y":0.554,"fill":"other"},{"x":0.749,"y":0.559,"fill":"other"},{"x":0.744,"y":0.56,"fill":"other"},{"x":0.734,"y":0.559,"fill":"other"},{"x":0.731,"y":0.562,"fill":"other"},{"x":0.734,"y":0.568,"fill":"other"},{"x":0.741,"y":0.577,"fill":"other"},{"x":0.763,"y":0.593,"fill":"other"},{"x":0.947,"y":0.663,"fill":"other"},{"x":0.942,"y":0.668,"fill":"other"},{"x":0.916,"y":0.664,"fill":"other"},{"x":0.895,"y":0.656,"fill":"other"},{"x":0.933,"y":0.666,"fill":"other"},{"x":0.927,"y":0.671,"fill":"other"},{"x":0.959,"y":0.684,"fill":"other"},{"x":0.93,"y":0.683,"fill":"other"},{"x":0.904,"y":0.679,"fill":"other"},{"x":0.879,"y":0.679,"fill":"other"},{"x":0.86,"y":0.679,"fill":"other"},{"x":0.873,"y":0.688,"fill":"other"},{"x":0.859,"y":0.689,"fill":"other"},{"x":0.852,"y":0.692,"fill":"other"},{"x":0.832,"y":0.688,"fill":"other"},{"x":0.815,"y":0.687,"fill":"other"},{"x":0.808,"y":0.689,"fill":"other"},{"x":0.797,"y":0.688,"fill":"other"},{"x":0.782,"y":0.687,"fill":"other"},{"x":0.771,"y":0.687,"fill":"other"},{"x":0.773,"y":0.69,"fill":"other"},{"x":0.761,"y":0.688,"fill":"other"},{"x":0.75,"y":0.686,"fill":"other"},{"x":0.778,"y":0.697,"fill":"other"},{"x":0.777,"y":0.698,"fill":"other"},{"x":0.765,"y":0.696,"fill":"other"},{"x":0.811,"y":0.691,"fill":"other"},{"x":0.83,"y":0.694,"fill":"other"},{"x":0.812,"y":0.692,"fill":"other"},{"x":0.801,"y":0.69,"fill":"other"},{"x":0.789,"y":0.687,"fill":"other"},{"x":0.78,"y":0.678,"fill":"other"},{"x":0.772,"y":0.675,"fill":"other"},{"x":0.777,"y":0.679,"fill":"other"},{"x":0.765,"y":0.677,"fill":"other"},{"x":0.761,"y":0.68,"fill":"other"},{"x":0.751,"y":0.672,"fill":"other"},{"x":0.742,"y":0.672,"fill":"other"},{"x":0.738,"y":0.672,"fill":"other"},{"x":0.73,"y":0.672,"fill":"other"},{"x":0.743,"y":0.666,"fill":"other"},{"x":0.734,"y":0.665,"fill":"other"},{"x":0.747,"y":0.673,"fill":"other"},{"x":0.777,"y":0.687,"fill":"other"},{"x":0.777,"y":0.686,"fill":"other"},{"x":0.766,"y":0.686,"fill":"other"},{"x":0.757,"y":0.686,"fill":"other"},{"x":0.746,"y":0.684,"fill":"other"},{"x":0.75,"y":0.667,"fill":"other"},{"x":0.763,"y":0.675,"fill":"other"},{"x":0.771,"y":0.657,"fill":"other"},{"x":0.779,"y":0.663,"fill":"other"},{"x":0.765,"y":0.663,"fill":"other"},{"x":0.756,"y":0.656,"fill":"other"},{"x":0.748,"y":0.652,"fill":"other"},{"x":0.738,"y":0.628,"fill":"other"},{"x":0.783,"y":0.635,"fill":"other"},{"x":0.769,"y":0.633,"fill":"other"},{"x":0.775,"y":0.64,"fill":"other"},{"x":0.762,"y":0.639,"fill":"other"},{"x":0.751,"y":0.638,"fill":"other"},{"x":0.764,"y":0.648,"fill":"other"},{"x":0.753,"y":0.647,"fill":"other"},{"x":0.745,"y":0.645,"fill":"other"},{"x":0.738,"y":0.645,"fill":"other"},{"x":0.745,"y":0.646,"fill":"other"},{"x":0.75,"y":0.653,"fill":"other"},{"x":0.747,"y":0.656,"fill":"other"},{"x":0.741,"y":0.657,"fill":"other"},{"x":0.732,"y":0.656,"fill":"other"},{"x":0.735,"y":0.66,"fill":"other"},{"x":0.845,"y":0.673,"fill":"other"},{"x":0.826,"y":0.658,"fill":"other"},{"x":0.811,"y":0.658,"fill":"other"},{"x":0.801,"y":0.656,"fill":"other"},{"x":0.837,"y":0.671,"fill":"other"},{"x":0.827,"y":0.673,"fill":"other"},{"x":0.811,"y":0.673,"fill":"other"},{"x":0.795,"y":0.664,"fill":"other"},{"x":0.783,"y":0.651,"fill":"other"},{"x":0.843,"y":0.612,"fill":"other"},{"x":0.84,"y":0.615,"fill":"other"},{"x":0.83,"y":0.617,"fill":"other"},{"x":0.814,"y":0.618,"fill":"other"},{"x":0.798,"y":0.617,"fill":"other"},{"x":0.84,"y":0.623,"fill":"other"},{"x":0.822,"y":0.619,"fill":"other"},{"x":0.812,"y":0.616,"fill":"other"},{"x":0.807,"y":0.621,"fill":"other"},{"x":0.852,"y":0.6,"fill":"other"},{"x":0.838,"y":0.603,"fill":"other"},{"x":0.835,"y":0.608,"fill":"other"},{"x":0.817,"y":0.608,"fill":"other"},{"x":0.8,"y":0.568,"fill":"other"},{"x":0.832,"y":0.584,"fill":"other"},{"x":0.815,"y":0.586,"fill":"other"},{"x":0.813,"y":0.591,"fill":"other"},{"x":0.857,"y":0.574,"fill":"other"},{"x":0.852,"y":0.574,"fill":"other"},{"x":0.832,"y":0.569,"fill":"other"},{"x":0.912,"y":0.575,"fill":"other"},{"x":0.908,"y":0.581,"fill":"other"},{"x":0.889,"y":0.581,"fill":"other"},{"x":1.043,"y":0.648,"fill":"other"},{"x":1.059,"y":0.66,"fill":"other"},{"x":1.036,"y":0.662,"fill":"other"},{"x":1.125,"y":0.681,"fill":"other"},{"x":1.085,"y":0.681,"fill":"other"},{"x":1.089,"y":0.682,"fill":"other"},{"x":1.071,"y":0.684,"fill":"other"},{"x":1.081,"y":0.684,"fill":"other"},{"x":1.042,"y":0.678,"fill":"other"},{"x":1.009,"y":0.677,"fill":"other"},{"x":0.979,"y":0.677,"fill":"other"},{"x":0.949,"y":0.677,"fill":"other"},{"x":0.921,"y":0.676,"fill":"other"},{"x":0.895,"y":0.675,"fill":"other"},{"x":0.871,"y":0.675,"fill":"other"},{"x":0.858,"y":0.671,"fill":"other"},{"x":0.855,"y":0.675,"fill":"other"},{"x":0.834,"y":0.674,"fill":"other"},{"x":0.816,"y":0.674,"fill":"other"},{"x":0.976,"y":0.709,"fill":"other"},{"x":1.016,"y":0.715,"fill":"other"},{"x":1.008,"y":0.716,"fill":"other"},{"x":0.985,"y":0.717,"fill":"other"},{"x":0.982,"y":0.714,"fill":"other"},{"x":0.989,"y":0.703,"fill":"other"},{"x":0.978,"y":0.707,"fill":"other"},{"x":1.009,"y":0.718,"fill":"other"},{"x":0.991,"y":0.715,"fill":"other"},{"x":0.96,"y":0.714,"fill":"other"},{"x":0.943,"y":0.716,"fill":"other"},{"x":0.918,"y":0.715,"fill":"other"},{"x":0.896,"y":0.715,"fill":"other"},{"x":0.872,"y":0.715,"fill":"other"},{"x":0.875,"y":0.717,"fill":"other"},{"x":0.856,"y":0.715,"fill":"other"},{"x":0.969,"y":0.682,"fill":"other"},{"x":0.942,"y":0.679,"fill":"other"},{"x":0.959,"y":0.684,"fill":"other"},{"x":0.971,"y":0.691,"fill":"other"},{"x":0.954,"y":0.693,"fill":"other"},{"x":0.937,"y":0.691,"fill":"other"},{"x":0.934,"y":0.671,"fill":"other"},{"x":0.907,"y":0.671,"fill":"other"},{"x":0.961,"y":0.671,"fill":"other"},{"x":0.934,"y":0.664,"fill":"other"},{"x":0.951,"y":0.674,"fill":"other"},{"x":0.94,"y":0.669,"fill":"other"},{"x":0.913,"y":0.668,"fill":"other"},{"x":0.899,"y":0.664,"fill":"other"},{"x":0.943,"y":0.668,"fill":"other"},{"x":0.918,"y":0.663,"fill":"other"},{"x":0.895,"y":0.66,"fill":"other"},{"x":0.907,"y":0.658,"fill":"other"},{"x":0.903,"y":0.632,"fill":"other"},{"x":0.886,"y":0.632,"fill":"other"},{"x":0.864,"y":0.624,"fill":"other"},{"x":0.867,"y":0.624,"fill":"other"},{"x":0.941,"y":0.619,"fill":"other"},{"x":0.916,"y":0.61,"fill":"other"},{"x":0.914,"y":0.611,"fill":"other"},{"x":0.895,"y":0.611,"fill":"other"},{"x":0.871,"y":0.611,"fill":"other"},{"x":1.08,"y":0.651,"fill":"other"},{"x":1.063,"y":0.647,"fill":"other"},{"x":1.036,"y":0.646,"fill":"other"},{"x":1.012,"y":0.649,"fill":"other"},{"x":0.979,"y":0.648,"fill":"other"},{"x":0.948,"y":0.648,"fill":"other"},{"x":0.999,"y":0.655,"fill":"other"},{"x":0.974,"y":0.656,"fill":"other"},{"x":0.98,"y":0.663,"fill":"other"},{"x":1.091,"y":0.689,"fill":"other"},{"x":1.121,"y":0.691,"fill":"other"},{"x":1.084,"y":0.676,"fill":"other"},{"x":1.152,"y":0.695,"fill":"other"},{"x":1.151,"y":0.685,"fill":"other"},{"x":1.11,"y":0.664,"fill":"other"},{"x":1.202,"y":0.683,"fill":"other"},{"x":1.247,"y":0.687,"fill":"other"},{"x":1.223,"y":0.679,"fill":"other"},{"x":1.172,"y":0.678,"fill":"other"},{"x":1.126,"y":0.678,"fill":"other"},{"x":1.478,"y":0.709,"fill":"volatile"},{"x":1.526,"y":0.705,"fill":"volatile"},{"x":1.454,"y":0.701,"fill":"volatile"},{"x":1.397,"y":0.702,"fill":"volatile"},{"x":1.575,"y":0.706,"fill":"volatile"},{"x":1.506,"y":0.706,"fill":"volatile"},{"x":1.46,"y":0.707,"fill":"volatile"},{"x":1.397,"y":0.701,"fill":"volatile"},{"x":1.363,"y":0.702,"fill":"volatile"},{"x":1.316,"y":0.703,"fill":"other"},{"x":1.372,"y":0.71,"fill":"volatile"},{"x":1.324,"y":0.706,"fill":"volatile"},{"x":1.27,"y":0.705,"fill":"other"},{"x":1.217,"y":0.703,"fill":"other"},{"x":1.198,"y":0.688,"fill":"other"},{"x":1.159,"y":0.689,"fill":"other"},{"x":1.12,"y":0.685,"fill":"other"},{"x":1.098,"y":0.681,"fill":"other"},{"x":1.104,"y":0.684,"fill":"other"},{"x":1.068,"y":0.684,"fill":"other"},{"x":1.101,"y":0.695,"fill":"other"},{"x":1.063,"y":0.694,"fill":"other"},{"x":1.025,"y":0.693,"fill":"other"},{"x":1.061,"y":0.688,"fill":"other"},{"x":1.155,"y":0.664,"fill":"other"},{"x":1.119,"y":0.612,"fill":"other"},{"x":1.081,"y":0.607,"fill":"other"},{"x":1.042,"y":0.595,"fill":"other"},{"x":1.007,"y":0.577,"fill":"other"},{"x":1.061,"y":0.59,"fill":"other"},{"x":1.057,"y":0.574,"fill":"other"},{"x":1.038,"y":0.569,"fill":"other"},{"x":1.02,"y":0.57,"fill":"other"},{"x":0.986,"y":0.57,"fill":"other"},{"x":0.954,"y":0.558,"fill":"other"},{"x":1.011,"y":0.574,"fill":"other"},{"x":1.148,"y":0.584,"fill":"other"},{"x":1.121,"y":0.579,"fill":"other"},{"x":1.125,"y":0.578,"fill":"other"},{"x":1.129,"y":0.571,"fill":"other"},{"x":1.087,"y":0.568,"fill":"other"},{"x":1.088,"y":0.567,"fill":"other"},{"x":1.049,"y":0.566,"fill":"other"},{"x":1.15,"y":0.594,"fill":"other"},{"x":1.128,"y":0.544,"fill":"other"},{"x":1.16,"y":0.53,"fill":"other"},{"x":1.115,"y":0.531,"fill":"other"},{"x":1.095,"y":0.535,"fill":"other"},{"x":1.059,"y":0.525,"fill":"other"},{"x":1.05,"y":0.498,"fill":"other"},{"x":1.013,"y":0.489,"fill":"other"},{"x":0.979,"y":0.49,"fill":"other"},{"x":1.046,"y":0.501,"fill":"other"},{"x":1.014,"y":0.503,"fill":"other"},{"x":0.98,"y":0.501,"fill":"other"},{"x":0.974,"y":0.511,"fill":"other"},{"x":0.944,"y":0.507,"fill":"other"},{"x":0.967,"y":0.497,"fill":"other"},{"x":0.939,"y":0.477,"fill":"other"},{"x":0.957,"y":0.482,"fill":"other"},{"x":0.93,"y":0.484,"fill":"other"},{"x":0.982,"y":0.502,"fill":"other"},{"x":0.951,"y":0.501,"fill":"other"},{"x":0.926,"y":0.504,"fill":"other"},{"x":0.952,"y":0.517,"fill":"other"},{"x":1.028,"y":0.557,"fill":"other"},{"x":1.013,"y":0.56,"fill":"other"},{"x":1.085,"y":0.582,"fill":"other"},{"x":1.045,"y":0.581,"fill":"other"},{"x":1.07,"y":0.571,"fill":"other"},{"x":1.043,"y":0.551,"fill":"other"},{"x":1.007,"y":0.551,"fill":"other"},{"x":0.992,"y":0.548,"fill":"other"},{"x":1.064,"y":0.553,"fill":"other"},{"x":1.107,"y":0.568,"fill":"other"},{"x":1.066,"y":0.562,"fill":"other"},{"x":1.146,"y":0.581,"fill":"other"},{"x":1.111,"y":0.582,"fill":"other"},{"x":1.167,"y":0.601,"fill":"other"},{"x":1.122,"y":0.585,"fill":"other"},{"x":1.445,"y":0.577,"fill":"volatile"},{"x":1.469,"y":0.579,"fill":"volatile"},{"x":1.458,"y":0.579,"fill":"volatile"},{"x":1.417,"y":0.574,"fill":"volatile"},{"x":1.364,"y":0.574,"fill":"volatile"},{"x":1.312,"y":0.572,"fill":"other"},{"x":1.338,"y":0.583,"fill":"volatile"},{"x":1.321,"y":0.585,"fill":"other"},{"x":1.334,"y":0.584,"fill":"volatile"},{"x":1.295,"y":0.583,"fill":"other"},{"x":1.246,"y":0.58,"fill":"other"},{"x":1.213,"y":0.583,"fill":"other"},{"x":1.219,"y":0.593,"fill":"other"},{"x":1.283,"y":0.607,"fill":"other"},{"x":1.23,"y":0.607,"fill":"other"},{"x":1.205,"y":0.612,"fill":"other"},{"x":1.447,"y":0.636,"fill":"volatile"},{"x":1.408,"y":0.636,"fill":"volatile"},{"x":1.545,"y":0.663,"fill":"volatile"},{"x":1.472,"y":0.661,"fill":"volatile"},{"x":1.559,"y":0.674,"fill":"volatile"},{"x":1.529,"y":0.677,"fill":"volatile"},{"x":1.489,"y":0.669,"fill":"volatile"},{"x":1.601,"y":0.683,"fill":"volatile"},{"x":1.528,"y":0.683,"fill":"volatile"},{"x":1.558,"y":0.679,"fill":"volatile"},{"x":1.484,"y":0.678,"fill":"volatile"},{"x":1.555,"y":0.688,"fill":"volatile"},{"x":1.487,"y":0.682,"fill":"volatile"},{"x":1.512,"y":0.688,"fill":"volatile"},{"x":1.644,"y":0.702,"fill":"volatile"},{"x":1.623,"y":0.689,"fill":"volatile"},{"x":1.555,"y":0.689,"fill":"volatile"},{"x":1.488,"y":0.688,"fill":"volatile"},{"x":1.461,"y":0.68,"fill":"volatile"},{"x":1.406,"y":0.681,"fill":"volatile"},{"x":1.436,"y":0.687,"fill":"volatile"},{"x":1.655,"y":0.694,"fill":"volatile"},{"x":1.705,"y":0.687,"fill":"volatile"},{"x":1.691,"y":0.692,"fill":"volatile"},{"x":1.806,"y":0.705,"fill":"volatile"},{"x":1.725,"y":0.697,"fill":"volatile"},{"x":1.652,"y":0.697,"fill":"volatile"},{"x":1.579,"y":0.697,"fill":"volatile"},{"x":1.667,"y":0.704,"fill":"volatile"},{"x":1.587,"y":0.698,"fill":"volatile"},{"x":1.553,"y":0.701,"fill":"volatile"},{"x":1.511,"y":0.701,"fill":"volatile"},{"x":1.45,"y":0.657,"fill":"volatile"},{"x":1.39,"y":0.657,"fill":"volatile"},{"x":1.347,"y":0.658,"fill":"volatile"},{"x":1.444,"y":0.668,"fill":"volatile"},{"x":1.378,"y":0.667,"fill":"volatile"},{"x":1.317,"y":0.664,"fill":"other"},{"x":1.307,"y":0.648,"fill":"other"},{"x":1.255,"y":0.647,"fill":"other"},{"x":1.236,"y":0.651,"fill":"other"},{"x":1.31,"y":0.656,"fill":"other"},{"x":1.258,"y":0.655,"fill":"other"},{"x":1.258,"y":0.662,"fill":"other"},{"x":1.208,"y":0.662,"fill":"other"},{"x":1.199,"y":0.665,"fill":"other"},{"x":1.158,"y":0.66,"fill":"other"},{"x":1.294,"y":0.649,"fill":"other"},{"x":1.243,"y":0.631,"fill":"other"},{"x":1.352,"y":0.621,"fill":"volatile"},{"x":1.33,"y":0.626,"fill":"volatile"},{"x":1.603,"y":0.673,"fill":"volatile"},{"x":1.526,"y":0.672,"fill":"volatile"},{"x":1.637,"y":0.69,"fill":"volatile"},{"x":2.224,"y":0.692,"fill":"volatile"},{"x":2.383,"y":0.705,"fill":"volatile"},{"x":2.294,"y":0.707,"fill":"volatile"},{"x":2.172,"y":0.705,"fill":"volatile"},{"x":2.152,"y":0.708,"fill":"volatile"},{"x":2.088,"y":0.707,"fill":"volatile"},{"x":2.014,"y":0.705,"fill":"volatile"},{"x":1.921,"y":0.705,"fill":"volatile"},{"x":1.953,"y":0.713,"fill":"volatile"},{"x":1.854,"y":0.712,"fill":"volatile"},{"x":1.761,"y":0.711,"fill":"volatile"},{"x":1.696,"y":0.71,"fill":"volatile"},{"x":1.613,"y":0.71,"fill":"volatile"},{"x":1.548,"y":0.703,"fill":"volatile"},{"x":1.76,"y":0.724,"fill":"volatile"},{"x":1.681,"y":0.72,"fill":"volatile"},{"x":1.612,"y":0.716,"fill":"volatile"},{"x":1.574,"y":0.718,"fill":"volatile"},{"x":1.499,"y":0.711,"fill":"volatile"},{"x":1.617,"y":0.721,"fill":"volatile"},{"x":1.543,"y":0.716,"fill":"volatile"},{"x":1.552,"y":0.715,"fill":"volatile"},{"x":1.494,"y":0.712,"fill":"volatile"},{"x":1.425,"y":0.704,"fill":"volatile"},{"x":1.675,"y":0.715,"fill":"volatile"},{"x":1.606,"y":0.703,"fill":"volatile"},{"x":1.537,"y":0.703,"fill":"volatile"},{"x":1.555,"y":0.711,"fill":"volatile"},{"x":1.493,"y":0.711,"fill":"volatile"},{"x":1.426,"y":0.709,"fill":"volatile"},{"x":1.369,"y":0.709,"fill":"volatile"},{"x":1.387,"y":0.712,"fill":"volatile"},{"x":1.48,"y":0.724,"fill":"volatile"},{"x":1.438,"y":0.722,"fill":"volatile"},{"x":1.391,"y":0.699,"fill":"volatile"},{"x":1.53,"y":0.708,"fill":"volatile"},{"x":1.458,"y":0.707,"fill":"volatile"},{"x":1.391,"y":0.705,"fill":"volatile"},{"x":1.503,"y":0.723,"fill":"volatile"},{"x":1.496,"y":0.715,"fill":"volatile"},{"x":1.426,"y":0.714,"fill":"volatile"},{"x":1.362,"y":0.711,"fill":"volatile"},{"x":1.301,"y":0.711,"fill":"other"},{"x":1.245,"y":0.71,"fill":"other"},{"x":1.444,"y":0.725,"fill":"volatile"},{"x":1.405,"y":0.718,"fill":"volatile"},{"x":1.341,"y":0.717,"fill":"volatile"},{"x":1.283,"y":0.716,"fill":"other"},{"x":1.485,"y":0.716,"fill":"volatile"},{"x":1.447,"y":0.718,"fill":"volatile"},{"x":1.426,"y":0.713,"fill":"volatile"},{"x":1.368,"y":0.713,"fill":"volatile"},{"x":1.34,"y":0.706,"fill":"volatile"},{"x":1.331,"y":0.709,"fill":"volatile"},{"x":1.434,"y":0.718,"fill":"volatile"},{"x":1.371,"y":0.717,"fill":"volatile"},{"x":1.311,"y":0.715,"fill":"other"},{"x":1.255,"y":0.705,"fill":"other"},{"x":1.287,"y":0.714,"fill":"other"},{"x":1.307,"y":0.708,"fill":"other"},{"x":1.255,"y":0.707,"fill":"other"},{"x":1.263,"y":0.702,"fill":"other"},{"x":1.213,"y":0.701,"fill":"other"},{"x":1.17,"y":0.696,"fill":"other"},{"x":1.152,"y":0.7,"fill":"other"},{"x":1.143,"y":0.704,"fill":"other"},{"x":1.169,"y":0.707,"fill":"other"},{"x":1.172,"y":0.71,"fill":"other"},{"x":1.126,"y":0.707,"fill":"other"},{"x":1.189,"y":0.721,"fill":"other"},{"x":1.142,"y":0.72,"fill":"other"},{"x":1.105,"y":0.72,"fill":"other"},{"x":1.069,"y":0.717,"fill":"other"},{"x":1.055,"y":0.717,"fill":"other"},{"x":1.024,"y":0.717,"fill":"other"},{"x":1.011,"y":0.715,"fill":"other"},{"x":0.979,"y":0.714,"fill":"other"},{"x":0.984,"y":0.719,"fill":"other"},{"x":0.954,"y":0.719,"fill":"other"},{"x":0.927,"y":0.717,"fill":"other"},{"x":1.033,"y":0.733,"fill":"other"},{"x":1.003,"y":0.729,"fill":"other"},{"x":0.989,"y":0.727,"fill":"other"},{"x":0.957,"y":0.726,"fill":"other"},{"x":0.938,"y":0.719,"fill":"other"},{"x":0.911,"y":0.714,"fill":"other"},{"x":1.04,"y":0.733,"fill":"other"},{"x":1.006,"y":0.73,"fill":"other"},{"x":0.973,"y":0.729,"fill":"other"},{"x":1.052,"y":0.733,"fill":"other"},{"x":1.024,"y":0.733,"fill":"other"},{"x":1.067,"y":0.742,"fill":"other"},{"x":1.033,"y":0.741,"fill":"other"},{"x":1.099,"y":0.753,"fill":"other"},{"x":1.112,"y":0.754,"fill":"other"},{"x":1.076,"y":0.753,"fill":"other"},{"x":1.038,"y":0.751,"fill":"other"},{"x":1.012,"y":0.752,"fill":"other"},{"x":0.992,"y":0.744,"fill":"other"},{"x":0.973,"y":0.741,"fill":"other"},{"x":0.963,"y":0.743,"fill":"other"},{"x":0.957,"y":0.702,"fill":"other"},{"x":0.95,"y":0.702,"fill":"other"},{"x":1.039,"y":0.645,"fill":"other"},{"x":1.019,"y":0.644,"fill":"other"},{"x":1.014,"y":0.648,"fill":"other"},{"x":1.009,"y":0.636,"fill":"other"},{"x":1.076,"y":0.65,"fill":"other"},{"x":1.053,"y":0.653,"fill":"other"},{"x":1.015,"y":0.65,"fill":"other"},{"x":0.989,"y":0.651,"fill":"other"},{"x":0.973,"y":0.651,"fill":"other"},{"x":0.964,"y":0.654,"fill":"other"},{"x":1.001,"y":0.647,"fill":"other"},{"x":1.062,"y":0.651,"fill":"other"},{"x":1.042,"y":0.651,"fill":"other"},{"x":1.031,"y":0.656,"fill":"other"},{"x":1.016,"y":0.66,"fill":"other"},{"x":0.982,"y":0.66,"fill":"other"},{"x":0.951,"y":0.659,"fill":"other"},{"x":0.957,"y":0.651,"fill":"other"},{"x":0.929,"y":0.65,"fill":"other"},{"x":0.965,"y":0.665,"fill":"other"},{"x":0.947,"y":0.621,"fill":"other"},{"x":0.993,"y":0.623,"fill":"other"},{"x":0.978,"y":0.621,"fill":"other"},{"x":0.999,"y":0.624,"fill":"other"},{"x":1.001,"y":0.629,"fill":"other"},{"x":1.145,"y":0.631,"fill":"other"},{"x":1.33,"y":0.675,"fill":"volatile"},{"x":1.383,"y":0.687,"fill":"volatile"},{"x":1.33,"y":0.681,"fill":"volatile"},{"x":1.493,"y":0.699,"fill":"volatile"},{"x":1.423,"y":0.686,"fill":"volatile"},{"x":1.434,"y":0.677,"fill":"volatile"},{"x":1.482,"y":0.675,"fill":"volatile"},{"x":1.424,"y":0.674,"fill":"volatile"},{"x":1.455,"y":0.681,"fill":"volatile"},{"x":1.479,"y":0.681,"fill":"volatile"},{"x":1.458,"y":0.686,"fill":"volatile"},{"x":1.408,"y":0.685,"fill":"volatile"},{"x":1.377,"y":0.684,"fill":"volatile"},{"x":1.315,"y":0.682,"fill":"other"},{"x":1.271,"y":0.673,"fill":"other"},{"x":1.269,"y":0.679,"fill":"other"},{"x":1.298,"y":0.684,"fill":"other"},{"x":1.286,"y":0.685,"fill":"other"},{"x":1.231,"y":0.683,"fill":"other"},{"x":1.182,"y":0.683,"fill":"other"},{"x":1.168,"y":0.677,"fill":"other"},{"x":1.14,"y":0.677,"fill":"other"},{"x":1.376,"y":0.706,"fill":"volatile"},{"x":1.326,"y":0.702,"fill":"volatile"},{"x":1.287,"y":0.7,"fill":"other"},{"x":1.232,"y":0.697,"fill":"other"},{"x":1.186,"y":0.696,"fill":"other"},{"x":1.165,"y":0.699,"fill":"other"},{"x":1.133,"y":0.701,"fill":"other"},{"x":1.214,"y":0.716,"fill":"other"},{"x":1.194,"y":0.717,"fill":"other"},{"x":1.148,"y":0.716,"fill":"other"},{"x":1.108,"y":0.708,"fill":"other"},{"x":1.067,"y":0.668,"fill":"other"},{"x":1.294,"y":0.68,"fill":"other"},{"x":1.264,"y":0.683,"fill":"other"},{"x":1.222,"y":0.683,"fill":"other"},{"x":1.291,"y":0.697,"fill":"other"},{"x":1.262,"y":0.697,"fill":"other"},{"x":1.23,"y":0.699,"fill":"other"},{"x":1.18,"y":0.696,"fill":"other"},{"x":1.216,"y":0.702,"fill":"other"},{"x":1.175,"y":0.702,"fill":"other"},{"x":1.212,"y":0.706,"fill":"other"},{"x":1.166,"y":0.704,"fill":"other"},{"x":1.15,"y":0.7,"fill":"other"},{"x":1.184,"y":0.706,"fill":"other"},{"x":1.173,"y":0.71,"fill":"other"},{"x":1.127,"y":0.705,"fill":"other"},{"x":1.109,"y":0.705,"fill":"other"},{"x":1.072,"y":0.704,"fill":"other"},{"x":1.041,"y":0.704,"fill":"other"},{"x":1.019,"y":0.701,"fill":"other"},{"x":0.989,"y":0.701,"fill":"other"},{"x":0.958,"y":0.696,"fill":"other"},{"x":0.931,"y":0.696,"fill":"other"},{"x":0.96,"y":0.702,"fill":"other"},{"x":0.93,"y":0.698,"fill":"other"},{"x":0.903,"y":0.695,"fill":"other"},{"x":0.905,"y":0.699,"fill":"other"},{"x":0.884,"y":0.698,"fill":"other"},{"x":0.861,"y":0.695,"fill":"other"},{"x":0.956,"y":0.72,"fill":"other"},{"x":0.943,"y":0.719,"fill":"other"},{"x":0.916,"y":0.709,"fill":"other"},{"x":1.221,"y":0.688,"fill":"other"},{"x":1.172,"y":0.687,"fill":"other"},{"x":1.141,"y":0.683,"fill":"other"},{"x":1.145,"y":0.689,"fill":"other"},{"x":1.122,"y":0.692,"fill":"other"},{"x":1.154,"y":0.691,"fill":"other"},{"x":1.141,"y":0.695,"fill":"other"},{"x":1.204,"y":0.709,"fill":"other"},{"x":1.231,"y":0.71,"fill":"other"},{"x":1.221,"y":0.715,"fill":"other"},{"x":1.348,"y":0.727,"fill":"volatile"},{"x":1.554,"y":0.751,"fill":"volatile"},{"x":1.555,"y":0.749,"fill":"volatile"},{"x":1.491,"y":0.748,"fill":"volatile"}],"geoms":["point"],"x":"dax_sd","y":"rho","code":{"point":"ggplot(df, aes(dax_sd, rho, colour = group)) +\n  geom_point(size = 1)"}}

The points slope upward, and the widget reads r = 0.4. So the days with a higher DAX conditional standard deviation tend to have a higher DCC correlation.

The block below finds the 90th percentile, then compares the DCC correlation and the correlation of the raw returns on the volatile days and on the other days.

```r
# Compare the correlation on volatile days with the other days
dax_sd <- s[, "DAX"]
cutoff <- unname(quantile(dax_sd, 0.9))
volatile <- dax_sd > cutoff
round(cutoff, 4)
#> [1] 1.3225
sum(volatile)
#> [1] 186
round(c(volatile = mean(rho[volatile]), other = mean(rho[!volatile])), 4)
#> volatile    other
#>   0.6829   0.6109
round(c(volatile = cor(x[volatile, 1], x[volatile, 2]), other = cor(x[!volatile, 1], x[!volatile, 2])), 4)
#> volatile    other
#>   0.6811   0.6286
round(cor(dax_sd, rho), 4)
#> [1] 0.3954
```

The 90th percentile of the DAX conditional standard deviation is 1.3225, which leaves 186 volatile days. The mean of the DCC path is 0.6829 on those days and 0.6109 on the others. The correlation in the widget is 0.3954 to four decimals.

The raw returns show the same gap without any model. Their correlation is 0.6811 on the volatile days and 0.6286 on the others.

[WARNING]
Split the days on the conditional standard deviation, not on the size of the return.

The block below shows what happens if you split on the return instead, using the 5 percent of days with the lowest DAX returns.

```r
# Select on the return instead: the lowest 5 percent of DAX returns
cutoff_low <- unname(quantile(x[, "DAX"], 0.05))
worst <- x[, "DAX"] < cutoff_low
round(cutoff_low, 3)
#> [1] -1.578
sum(worst)
#> [1] 93
round(c(worst = cor(x[worst, 1], x[worst, 2]), other = cor(x[!worst, 1], x[!worst, 2])), 4)
#>  worst  other
#> 0.5187 0.5612
```

On the 93 days with the lowest DAX returns, those below -1.578, the raw correlation is 0.5187 against 0.5612 on the other days. Choosing days by how low one return was truncates that variable, and truncation lowers the correlation by itself. The conditional standard deviation does not have this problem, because it is set by earlier data and does not pick days by the size of the day's own return.

=== step === concept
## What time-varying correlation does to portfolio risk

Now the DCC path goes into the risk calculation. On each day the portfolio's standard deviation is \(\sqrt{\mathbf{w}^{\top}\mathbf{H}_t\mathbf{w}}\), which is the portfolio formula from the start with that day's conditional standard deviations and that day's \(\rho_t\).

To see what DCC changes, we compute the 50/50 portfolio's standard deviation on every day twice: once with \(\rho_t\), and once with the constant correlation of 0.6222 from the standardised residuals. Both use the same conditional standard deviations.

```r
# Compute the portfolio standard deviation for every day with DCC and with a constant correlation
port_sd <- function(s, rho, w) {
  sqrt(w[1]^2 * s[, 1]^2 + w[2]^2 * s[, 2]^2 + 2 * w[1] * w[2] * rho * s[, 1] * s[, 2])
}
sp_dcc <- port_sd(s, rho, w)
sp_const <- port_sd(s, rep(rho_const, nrow(s)), w)
round(c(dcc_mean = mean(sp_dcc), constant_mean = mean(sp_const)), 4)
#>      dcc_mean constant_mean
#>        0.8043        0.8041
round(range(sp_dcc / sp_const), 3)
#> [1] 0.907 1.039
```

Averaged over the 1,859 days the two are almost the same: 0.8043 with DCC and 0.8041 with the constant correlation. But day by day the DCC value runs from 0.907 to 1.039 times the constant-correlation value.

As a check, the block below computes the last day's value from \(\mathbf{w}^{\top}\mathbf{H}_t\mathbf{w}\), with \(\mathbf{H}_t = \mathbf{D}_t\mathbf{R}_t\mathbf{D}_t\), and compares it with the formula.

```r
# Check the formula against sqrt(w' H w) on the last day
last <- nrow(s)
D <- diag(s[last, ])
R <- matrix(c(1, rho[last], rho[last], 1), nrow = 2)
H <- D %*% R %*% D
round(s[last, ], 4)
#>    DAX   FTSE
#> 1.4915 1.1825
round(rho[last], 4)
#> [1] 0.7478
round(drop(sqrt(t(w) %*% H %*% w)), 4)
#> [1] 1.251
round(c(dcc = sp_dcc[last], constant = sp_const[last]), 4)
#>      dcc constant
#>    1.251    1.206
```

Both routes give 1.251 for the last day. The correlation that day was 0.7478, well above 0.6222, and the DCC standard deviation is 1.251 against 1.206 for the constant correlation.

Where does this matter most? The block below divides each day's portfolio standard deviation by the weighted sum of the two standard deviations, which is the value at a correlation of 1. One minus that share is the part of the weighted sum that diversification removes.

```r
# Compare the share of the weighted standard deviation that remains on volatile days and other days
weighted_sd <- w[1] * s[, 1] + w[2] * s[, 2]
share <- sp_dcc / weighted_sd
shares <- c(volatile = mean(share[volatile]), other = mean(share[!volatile]))
round(shares, 4)
#> volatile    other
#>   0.9213   0.8993
round(100 * (1 - shares), 1)
#> volatile    other
#>      7.9     10.1
# Recompute the volatile days with the correlation set to the mean of the other days
rho_other <- mean(rho[!volatile])
sp_swap <- port_sd(s[volatile, ], rep(rho_other, sum(volatile)), w)
share_swap <- mean(sp_swap / weighted_sd[volatile])
round(c(volatile = shares[["volatile"]], other = shares[["other"]], volatile_at_other_rho = share_swap), 4)
#>              volatile                 other volatile_at_other_rho
#>                0.9213                0.8993                0.9026
```

On volatile days the portfolio's standard deviation is 0.9213 of the weighted sum, and on the other days 0.8993. So diversification removes 7.9 percent of the weighted standard deviation on volatile days against 10.1 percent on the others.

With the correlation set to 0.6109 on the volatile days, their share falls from 0.9213 to 0.9026. The higher correlation therefore accounts for 0.0187 of the 0.0220 gap between 0.9213 and 0.8993. The other 0.0033 comes from the sizes of the two conditional standard deviations on those days.

[KEY INSIGHT]
Averaged over all days, DCC and a constant correlation give nearly the same portfolio risk. The difference is in which days carry the risk: on volatile days the correlation is higher and diversification removes less.

=== step === quiz
## Quick check: what does diversification remove on volatile days?

On the volatile days the portfolio's standard deviation is 0.9213 of the weighted sum, and on the other days 0.8993. The mean DCC correlation is 0.6829 on the volatile days and 0.6109 on the others. Which statement reads those numbers correctly?

::quiz {"correct": 3, "gate": true, "difficulty": "intermediate"}
- A share of 0.9213 means the portfolio's standard deviation is 92 percent below the weighted sum. ::no
- The high correlation on volatile days caused the volatility. ::no
- Diversification removes less risk on volatile days, mostly because the correlation is higher then. ::ok Yes. On volatile days diversification removes 7.9 percent of the weighted standard deviation against 10.1 percent on the others. With the correlation set to 0.6109 on those days the share falls to 0.9026, so the higher correlation accounts for 0.0187 of the 0.0220 gap.
- The correlation of 0.5187 on the lowest-return days shows that diversification works best in a crash. ::no Three of these four read the numbers wrongly. A share of 0.9213 means 7.9 percent of the weighted sum is removed, not 92. The comparison shows two things happening on the same days and says nothing about which caused which. And the 0.5187 comes from choosing days by the size of one return, which lowers the correlation on its own, so it says nothing about diversification in a crash.

=== step === tryit
## Your turn: portfolio risk on the last day at 70/30

Take a portfolio with 70 percent in the DAX and 30 percent in the FTSE. Compute its standard deviation on the last day at the DCC correlation `rho_last`, and again at the constant correlation `rho_const`.

The function `sd_p()` below takes a correlation as `rho_day`. Write the portfolio formula inside it, then press Check.

```r
# Compute the last day's 70/30 portfolio standard deviation at the DCC and constant correlations
w70 <- c(0.7, 0.3)
s_last <- unname(s[nrow(s), ])
rho_last <- rho[nrow(s)]
sd_p <- function(rho_day) {
  # Write the variance from the portfolio formula, then return its square root
  NA
}
round(c(dcc = sd_p(rho_last), constant = sd_p(rho_const)), 4)
```
::check {"regex": "^(?=[\\s\\S]*(sqrt\\s*[(]|[\\^]\\s*[(]?0?[.]5))(?=[\\s\\S]*rho_day[\\s\\S]*rho_day)", "gate": true, "difficulty": "intermediate", "ok": "Yes: 1.3303 at the DCC correlation and 1.2949 at the constant one. The weighted sum is 1.3988, so diversification removes 4.9 percent of it at the DCC correlation and 7.4 percent at the constant one.", "no": "Write the variance with the portfolio formula, using the weights in w70, the two values in s_last and rho_day for the correlation. Then return the square root of that variance."}
::solution
```r
# Compute the last day's 70/30 portfolio standard deviation at both correlations
sd_p <- function(rho_day) {
  variance <- w70[1]^2 * s_last[1]^2 + w70[2]^2 * s_last[2]^2 +
    2 * w70[1] * w70[2] * rho_day * s_last[1] * s_last[2]
  sqrt(variance)
}
round(c(dcc = sd_p(rho_last), constant = sd_p(rho_const)), 4)
#>      dcc constant
#>   1.3303   1.2949
# The weighted sum of the two standard deviations, for comparison
round(sum(w70 * s_last), 4)
#> [1] 1.3988
```

The last day's correlation of 0.7478 is above the constant 0.6222, so the DCC standard deviation is higher. Both are below the weighted sum of 1.3988, the value at a correlation of 1.

=== step === concept
## References

- [Dynamic conditional correlation: a simple class of multivariate GARCH models](https://doi.org/10.1198/073500102288618487) - Engle (2002), Journal of Business & Economic Statistics 20(3), 339-350. The paper that introduced DCC-GARCH and the two-step estimation used here.
- Tsay, R. S. (2014). Multivariate Time Series Analysis: With R and Financial Applications. Wiley. The book behind the MTS package, including `dccPre()`.
- [No contagion, only interdependence: measuring stock market comovements](https://doi.org/10.1111/0022-1082.00494) - Forbes and Rigobon (2002), Journal of Finance 57(5), 2223-2261. Why correlations measured on volatile days need care.
- [rmgarch: Multivariate GARCH Models](https://cran.r-project.org/package=rmgarch) - Ghalanos, R package on CRAN. The `dccspec()` and `dccfit()` workflow.

=== step === complete
## What you can do now

You can now measure the risk of a two-asset portfolio when the correlation between its assets changes from day to day. To summarize:

- The portfolio's standard deviation depends on the correlation: for the 50/50 DAX and FTSE position it is 0.8281 at 0.6395 and 0.9129 at 1.
- A 60-day rolling correlation cannot separate real change from sampling noise. With the correlation fixed at 0.6395, 60-day windows still ranged from 0.308 to 0.831.
- Stage 1 fits a GARCH(1,1) to each series and divides each return by its conditional standard deviation. Stage 2 updates Q each day with weight 0.0181 on yesterday's co-movement and 0.9742 on yesterday's Q, then rescales it to the correlation.
- The fitted DCC correlation ran from 0.319 to 0.754, and it was higher on volatile days: 0.6829 against 0.6109.
- That makes diversification remove less on volatile days: 7.9 percent of the weighted standard deviation against 10.1 percent.

So when someone asks how risky a DAX and FTSE position is, you can say: "It depends on the correlation that day, and DCC-GARCH gives us that correlation for every day."

The next section moves from volatility to several series that drive each other, with vector autoregressions (VAR).
