---
title: "Time Series Decomposition Lesson 2: STL decomposition in practice"
catalog_blurb: "How to choose STL's windows and settings so a real decomposition holds up."
description: "Learn how feasts' STL() decomposes a real retail series: choosing trend and season windows, fitting robustly around an outlier, and reading components()."
keywords: "STL decomposition in R, feasts STL(), trend window, season window, robust STL fitting, components() dable, autoplot decomposition, seasonal and trend decomposition using loess, aus_retail tsibble"
post_type: "LESSON"
curriculum_id: "5.20.2"
webr: true
mathjax: false
lesson_access: "pro"
course_id: "ts-decomposition"
course_title: "Time Series Decomposition"
course_lesson: "2"
course_total: "6"
course_landing: "Time-Series-Decomposition-Course.html"
course_next: "Seasonal-Adjustment-with-X13-and-STL.html"
course_prev: "Moving-Averages-and-Classical-Decomposition.html"
---

=== step === cover
## STL decomposition in practice

Today let's take one real retail series and pull it apart with STL, a decomposition method flexible enough to bend where the data actually bends.

Victoria's monthly turnover for cafes, restaurants and takeaway food services is tracked by the Australian Bureau of Statistics every month. The series runs 441 months, from April 1982 to December 2018, climbing from $81.3 million a month to $1,066.2 million a month over that time.

Here is the whole series, plotted in the order the months actually happened.

::widget chart-plotter {"data":[{"x":1,"y":85.1},{"x":2,"y":85.1},{"x":3,"y":82.8},{"x":4,"y":82.1},{"x":5,"y":81.8},{"x":6,"y":84.6},{"x":7,"y":91.7},{"x":8,"y":97.7},{"x":9,"y":109.3},{"x":10,"y":94.6},{"x":11,"y":88.2},{"x":12,"y":92.0},{"x":13,"y":85.2},{"x":14,"y":86.8},{"x":15,"y":81.3},{"x":16,"y":85.6},{"x":17,"y":90.5},{"x":18,"y":90.8},{"x":19,"y":92.7},{"x":20,"y":95.8},{"x":21,"y":111.7},{"x":22,"y":92.7},{"x":23,"y":94.4},{"x":24,"y":97.8},{"x":25,"y":92.9},{"x":26,"y":101.0},{"x":27,"y":92.1},{"x":28,"y":92.5},{"x":29,"y":94.4},{"x":30,"y":90.4},{"x":31,"y":95.7},{"x":32,"y":100.6},{"x":33,"y":112.4},{"x":34,"y":96.3},{"x":35,"y":93.9},{"x":36,"y":98.0},{"x":37,"y":98.4},{"x":38,"y":101.8},{"x":39,"y":90.8},{"x":40,"y":98.3},{"x":41,"y":107.0},{"x":42,"y":103.2},{"x":43,"y":111.8},{"x":44,"y":112.3},{"x":45,"y":126.8},{"x":46,"y":113.8},{"x":47,"y":104.4},{"x":48,"y":109.7},{"x":49,"y":110.2},{"x":50,"y":118.0},{"x":51,"y":108.2},{"x":52,"y":123.5},{"x":53,"y":131.7},{"x":54,"y":132.9},{"x":55,"y":142.8},{"x":56,"y":138.3},{"x":57,"y":159.5},{"x":58,"y":138.9},{"x":59,"y":130.9},{"x":60,"y":136.3},{"x":61,"y":142.7},{"x":62,"y":144.2},{"x":63,"y":137.9},{"x":64,"y":149.0},{"x":65,"y":146.4},{"x":66,"y":146.4},{"x":67,"y":157.3},{"x":68,"y":155.3},{"x":69,"y":186.5},{"x":70,"y":143.3},{"x":71,"y":146.7},{"x":72,"y":159.6},{"x":73,"y":158.7},{"x":74,"y":151.7},{"x":75,"y":155.7},{"x":76,"y":154.0},{"x":77,"y":159.9},{"x":78,"y":165.3},{"x":79,"y":167.8},{"x":80,"y":176.4},{"x":81,"y":186.2},{"x":82,"y":167.2},{"x":83,"y":167.9},{"x":84,"y":180.6},{"x":85,"y":179.4},{"x":86,"y":182.9},{"x":87,"y":177.5},{"x":88,"y":183.3},{"x":89,"y":177.4},{"x":90,"y":188.3},{"x":91,"y":203.0},{"x":92,"y":203.6},{"x":93,"y":236.8},{"x":94,"y":198.3},{"x":95,"y":183.5},{"x":96,"y":204.6},{"x":97,"y":183.9},{"x":98,"y":183.5},{"x":99,"y":182.1},{"x":100,"y":193.4},{"x":101,"y":186.7},{"x":102,"y":182.9},{"x":103,"y":185.2},{"x":104,"y":183.1},{"x":105,"y":209.1},{"x":106,"y":187.8},{"x":107,"y":166.9},{"x":108,"y":174.1},{"x":109,"y":169.5},{"x":110,"y":177.7},{"x":111,"y":179.0},{"x":112,"y":179.0},{"x":113,"y":181.2},{"x":114,"y":183.2},{"x":115,"y":183.9},{"x":116,"y":189.0},{"x":117,"y":227.5},{"x":118,"y":192.3},{"x":119,"y":184.5},{"x":120,"y":197.9},{"x":121,"y":195.6},{"x":122,"y":193.9},{"x":123,"y":169.3},{"x":124,"y":177.9},{"x":125,"y":173.4},{"x":126,"y":190.6},{"x":127,"y":192.4},{"x":128,"y":195.4},{"x":129,"y":234.0},{"x":130,"y":207.4},{"x":131,"y":182.1},{"x":132,"y":191.1},{"x":133,"y":189.8},{"x":134,"y":192.1},{"x":135,"y":185.7},{"x":136,"y":200.2},{"x":137,"y":192.4},{"x":138,"y":195.1},{"x":139,"y":192.5},{"x":140,"y":202.3},{"x":141,"y":235.9},{"x":142,"y":194.1},{"x":143,"y":185.3},{"x":144,"y":194.6},{"x":145,"y":181.8},{"x":146,"y":179.9},{"x":147,"y":180.0},{"x":148,"y":194.6},{"x":149,"y":193.7},{"x":150,"y":206.0},{"x":151,"y":225.1},{"x":152,"y":219.9},{"x":153,"y":246.3},{"x":154,"y":222.3},{"x":155,"y":207.2},{"x":156,"y":238.1},{"x":157,"y":229.0},{"x":158,"y":222.4},{"x":159,"y":221.5},{"x":160,"y":225.4},{"x":161,"y":227.4},{"x":162,"y":233.4},{"x":163,"y":230.2},{"x":164,"y":240.4},{"x":165,"y":259.4},{"x":166,"y":239.1},{"x":167,"y":219.0},{"x":168,"y":238.4},{"x":169,"y":236.4},{"x":170,"y":235.6},{"x":171,"y":225.8},{"x":172,"y":229.9},{"x":173,"y":228.8},{"x":174,"y":219.2},{"x":175,"y":225.5},{"x":176,"y":233.3},{"x":177,"y":254.6},{"x":178,"y":242.1},{"x":179,"y":216.1},{"x":180,"y":249.9},{"x":181,"y":250.8},{"x":182,"y":252.7},{"x":183,"y":235.8},{"x":184,"y":237.5},{"x":185,"y":237.8},{"x":186,"y":235.0},{"x":187,"y":243.4},{"x":188,"y":238.5},{"x":189,"y":264.3},{"x":190,"y":241.5},{"x":191,"y":218.0},{"x":192,"y":245.4},{"x":193,"y":235.8},{"x":194,"y":240.2},{"x":195,"y":226.9},{"x":196,"y":248.4},{"x":197,"y":255.5},{"x":198,"y":248.0},{"x":199,"y":268.0},{"x":200,"y":260.5},{"x":201,"y":284.2},{"x":202,"y":267.7},{"x":203,"y":248.6},{"x":204,"y":283.3},{"x":205,"y":285.6},{"x":206,"y":299.1},{"x":207,"y":295.2},{"x":208,"y":321.5},{"x":209,"y":331.3},{"x":210,"y":340.2},{"x":211,"y":345.6},{"x":212,"y":352.3},{"x":213,"y":392.1},{"x":214,"y":331.1},{"x":215,"y":295.7},{"x":216,"y":337.2},{"x":217,"y":283.7},{"x":218,"y":308.9},{"x":219,"y":306.3},{"x":220,"y":301.3},{"x":221,"y":307.6},{"x":222,"y":296.9},{"x":223,"y":326.2},{"x":224,"y":324.8},{"x":225,"y":359.9},{"x":226,"y":336.3},{"x":227,"y":311.7},{"x":228,"y":358.4},{"x":229,"y":367.0},{"x":230,"y":354.4},{"x":231,"y":347.5},{"x":232,"y":371.3},{"x":233,"y":391.5},{"x":234,"y":349.1},{"x":235,"y":361.9},{"x":236,"y":366.2},{"x":237,"y":409.1},{"x":238,"y":385.2},{"x":239,"y":356.0},{"x":240,"y":399.2},{"x":241,"y":372.7},{"x":242,"y":368.8},{"x":243,"y":355.6},{"x":244,"y":414.5},{"x":245,"y":410.0},{"x":246,"y":392.5},{"x":247,"y":377.5},{"x":248,"y":393.1},{"x":249,"y":441.2},{"x":250,"y":446.4},{"x":251,"y":378.4},{"x":252,"y":418.4},{"x":253,"y":406.2},{"x":254,"y":426.2},{"x":255,"y":399.1},{"x":256,"y":449.0},{"x":257,"y":437.6},{"x":258,"y":434.9},{"x":259,"y":479.9},{"x":260,"y":473.8},{"x":261,"y":529.9},{"x":262,"y":478.1},{"x":263,"y":457.0},{"x":264,"y":499.3},{"x":265,"y":471.8},{"x":266,"y":468.5},{"x":267,"y":438.1},{"x":268,"y":468.4},{"x":269,"y":468.4},{"x":270,"y":490.9},{"x":271,"y":473.9},{"x":272,"y":463.0},{"x":273,"y":509.6},{"x":274,"y":432.0},{"x":275,"y":408.1},{"x":276,"y":436.7},{"x":277,"y":439.4},{"x":278,"y":430.9},{"x":279,"y":427.2},{"x":280,"y":451.1},{"x":281,"y":448.6},{"x":282,"y":441.9},{"x":283,"y":474.4},{"x":284,"y":474.2},{"x":285,"y":506.6},{"x":286,"y":468.2},{"x":287,"y":433.3},{"x":288,"y":503.8},{"x":289,"y":501.8},{"x":290,"y":522.5},{"x":291,"y":495.4},{"x":292,"y":507.1},{"x":293,"y":520.6},{"x":294,"y":513.5},{"x":295,"y":504.3},{"x":296,"y":528.6},{"x":297,"y":584.8},{"x":298,"y":523.9},{"x":299,"y":481.2},{"x":300,"y":545.1},{"x":301,"y":531.1},{"x":302,"y":510.3},{"x":303,"y":490.1},{"x":304,"y":497.6},{"x":305,"y":526.4},{"x":306,"y":494.6},{"x":307,"y":540.9},{"x":308,"y":547.9},{"x":309,"y":596.3},{"x":310,"y":539.6},{"x":311,"y":523.1},{"x":312,"y":550.6},{"x":313,"y":541.1},{"x":314,"y":548.6},{"x":315,"y":516.2},{"x":316,"y":541.8},{"x":317,"y":557.8},{"x":318,"y":537.3},{"x":319,"y":591.2},{"x":320,"y":584.0},{"x":321,"y":673.1},{"x":322,"y":647.8},{"x":323,"y":576.0},{"x":324,"y":634.5},{"x":325,"y":622.2},{"x":326,"y":631.6},{"x":327,"y":594.2},{"x":328,"y":613.4},{"x":329,"y":642.4},{"x":330,"y":615.6},{"x":331,"y":636.5},{"x":332,"y":654.1},{"x":333,"y":742.0},{"x":334,"y":657.9},{"x":335,"y":611.4},{"x":336,"y":704.2},{"x":337,"y":697.6},{"x":338,"y":692.0},{"x":339,"y":669.7},{"x":340,"y":724.2},{"x":341,"y":748.9},{"x":342,"y":735.8},{"x":343,"y":705.0},{"x":344,"y":693.9},{"x":345,"y":806.9},{"x":346,"y":649.4},{"x":347,"y":597.8},{"x":348,"y":689.6},{"x":349,"y":707.6},{"x":350,"y":699.1},{"x":351,"y":672.5},{"x":352,"y":694.0},{"x":353,"y":694.7},{"x":354,"y":686.9},{"x":355,"y":682.1},{"x":356,"y":681.5},{"x":357,"y":761.4},{"x":358,"y":638.4},{"x":359,"y":594.5},{"x":360,"y":679.6},{"x":361,"y":632.5},{"x":362,"y":666.8},{"x":363,"y":661.9},{"x":364,"y":676.4},{"x":365,"y":681.5},{"x":366,"y":662.4},{"x":367,"y":684.9},{"x":368,"y":707.0},{"x":369,"y":750.8},{"x":370,"y":655.5},{"x":371,"y":605.2},{"x":372,"y":683.2},{"x":373,"y":682.8},{"x":374,"y":682.0},{"x":375,"y":651.6},{"x":376,"y":656.7},{"x":377,"y":664.9},{"x":378,"y":665.7},{"x":379,"y":686.0},{"x":380,"y":707.5},{"x":381,"y":792.2},{"x":382,"y":721.2},{"x":383,"y":631.6},{"x":384,"y":725.5},{"x":385,"y":722.1},{"x":386,"y":718.8},{"x":387,"y":693.6},{"x":388,"y":753.8},{"x":389,"y":784.4},{"x":390,"y":791.9},{"x":391,"y":789.5},{"x":392,"y":778.2},{"x":393,"y":838.1},{"x":394,"y":786.6},{"x":395,"y":689.1},{"x":396,"y":753.4},{"x":397,"y":737.5},{"x":398,"y":740.3},{"x":399,"y":726.1},{"x":400,"y":780.8},{"x":401,"y":795.0},{"x":402,"y":795.8},{"x":403,"y":811.7},{"x":404,"y":832.6},{"x":405,"y":896.7},{"x":406,"y":790.8},{"x":407,"y":732.4},{"x":408,"y":793.3},{"x":409,"y":805.4},{"x":410,"y":808.9},{"x":411,"y":769.0},{"x":412,"y":828.7},{"x":413,"y":866.3},{"x":414,"y":878.3},{"x":415,"y":886.3},{"x":416,"y":879.5},{"x":417,"y":961.8},{"x":418,"y":861.4},{"x":419,"y":753.6},{"x":420,"y":868.4},{"x":421,"y":859.7},{"x":422,"y":845.2},{"x":423,"y":828.7},{"x":424,"y":857.6},{"x":425,"y":874.1},{"x":426,"y":872.4},{"x":427,"y":917.7},{"x":428,"y":925.7},{"x":429,"y":1008.1},{"x":430,"y":887.3},{"x":431,"y":810.6},{"x":432,"y":909.7},{"x":433,"y":898.6},{"x":434,"y":866.4},{"x":435,"y":873.1},{"x":436,"y":916.1},{"x":437,"y":943.8},{"x":438,"y":933.8},{"x":439,"y":960.0},{"x":440,"y":981.8},{"x":441,"y":1066.2}],"geoms":["line"],"x":"month","y":"turnover"}

The turnover keeps rising for decades, dips hard around 2008 and 2009, then keeps climbing again. Any decomposition of this series has to make three real choices: how much to smooth the trend, how much to let the yearly pattern drift, and what to do about a month like that 2008-2009 dip that does not behave like the rest. STL is the method built to make all three of those choices explicit.

=== step === concept
## What STL stands for, and what its formula computes

STL stands for Seasonal and Trend decomposition using Loess. Loess (pronounced "low-ess") fits a smooth curve through data by working point by point: at each month it fits a small weighted regression using only the months nearby, reads off the fitted value there, then slides forward and repeats. Because it never assumes one fixed shape for the whole series, it can bend where the data actually bends.

Build the Victoria series as a tsibble first, the data structure `feasts` expects, keeping just the month and the turnover.

```r
# Build the Victoria cafe, restaurant and takeaway turnover series as a tsibble
library(tsibble)
library(tsibbledata)
library(dplyr)

cafe <- tsibbledata::aus_retail |>
  filter(State == "Victoria", Industry == "Cafes, restaurants and takeaway food services") |>
  select(Month, Turnover)

cafe
#> # A tsibble: 441 x 2 [1M]
#>       Month Turnover
#>       <mth>    <dbl>
#>  1 1982 Apr     85.1
#>  2 1982 May     85.1
#>  3 1982 Jun     82.8
#>  4 1982 Jul     82.1
#>  5 1982 Aug     81.8
#>  6 1982 Sep     84.6
#>  7 1982 Oct     91.7
#>  8 1982 Nov     97.7
#>  9 1982 Dec    109. 
#> 10 1983 Jan     94.6
#> # ℹ 431 more rows
```

Fit STL with `feasts`' `STL()` function inside `model()`. It takes a formula: the series on the left, and on the right a `trend()` term that sets how many months the trend's Loess window covers, and a `season()` term that sets the same thing for the yearly pattern.

```r
# Fit STL with a first choice of windows and preview components()
library(feasts)
library(fabletools)

fit0 <- cafe |> model(STL(Turnover ~ trend(window = 21) + season(window = 11)))
comp0 <- fit0 |> components()

comp0 |> as_tibble() |> select(Month, Turnover, trend, season_year, remainder, season_adjust) |> head(5)
#> # A tibble: 5 × 6
#>      Month Turnover trend season_year remainder season_adjust
#>      <mth>    <dbl> <dbl>       <dbl>     <dbl>         <dbl>
#> 1 1982 Apr     85.1  87.2       -3.48     1.35           88.6
#> 2 1982 May     85.1  87.6       -1.53    -0.944          86.6
#> 3 1982 Jun     82.8  87.9       -8.56     3.43           91.4
#> 4 1982 Jul     82.1  88.3       -4.19    -1.98           86.3
#> 5 1982 Aug     81.8  88.6       -1.93    -4.85           83.7
```

`components()` hands back four columns beyond the ones you already had.

- **trend** is the smoothed level.
- **season_year** is STL's own name for the repeating yearly pattern (not `seasonal`, which is what classical decomposition calls the same idea).
- **remainder** is whatever is left once trend and season are taken out.
- **season_adjust** is the observed turnover with only the season removed, trend and remainder still inside it.

STL always adds these three together to rebuild the observed value: Turnover = trend + season_year + remainder, in every row, every month. Unlike the classical decomposition, STL never offers a multiplicative version. If a series' season grows with its level, you would transform the series first and let STL fit the additive model on the transformed scale.

=== step === concept
## The trend window: how far STL looks to smooth the level

`trend(window = m)` tells STL to fit the trend's Loess curve using a moving window of m consecutive months. A small m looks at only a few months at a time, so the trend can bend quickly. A large m looks at many months at once, so the trend can only bend slowly.

Fit the series twice, once with a short trend window and once with a very long one, and count how often each trend line changes direction, from rising to falling or back again.

```r
# Fit STL with two very different trend windows and compare their shapes
fit_short <- cafe |> model(STL(Turnover ~ trend(window = 13) + season(window = 7)))
fit_long  <- cafe |> model(STL(Turnover ~ trend(window = 105) + season(window = "periodic")))

trend_short <- components(fit_short)$trend
trend_long  <- components(fit_long)$trend

# A reversal is a month where the trend switches from rising to falling, or back
count_reversals <- function(trend) {
  change <- sign(diff(trend))
  change <- change[change != 0]
  sum(diff(change) != 0)
}

c(short_window_13 = count_reversals(trend_short), long_window_105 = count_reversals(trend_long))
#> short_window_13 long_window_105 
#>              26               0 

round(c(trend_long_start = trend_long[1], trend_long_end = trend_long[length(trend_long)]), 2)
#> trend_long_start   trend_long_end 
#>            74.87           942.57 
```

The short window, 13 months, reverses direction 26 separate times across the series. One of those sits around April 1984.

```r
# Look at the actual wiggle around one of those 26 reversals
comp_short <- components(fit_short)
idx <- which(comp_short$Month == yearmonth("1984 Apr"))
vals <- comp_short$trend[(idx - 1):(idx + 1)]
names(vals) <- as.character(comp_short$Month[(idx - 1):(idx + 1)])
round(vals, 2)
#> 1984 Mar 1984 Apr 1984 May 
#>    96.83    97.81    97.76 
```

The trend rises from 96.83 to 97.81, then immediately falls back to 97.76 the very next month, a wiggle of about a tenth of a point that has nothing to do with the real shape of the series.

The long window, 105 months, never reverses direction once. Its trend climbs in a straight line from $74.87 million in April 1982 all the way to $942.57 million in December 2018, passing straight through the 2008-2009 slowdown as if it never happened.

Neither window is simply better. The short one is sensitive enough to catch a real slowdown, but it also chases ordinary month to month noise, like the tiny wiggle at April 1984. The long one ignores that kind of noise completely, but it also ignores a real event along the way.

=== step === widget
## Trading smoothness for responsiveness

That trade-off, chase every wiggle or flatten out a real bend, is not unique to STL. It shows up whenever you fit a smooth curve through noisy data with a tunable window.

The widget below fits a spline, a different smoothing tool, to a different, generic curve. It is not the Victoria series, but the slider controls exactly the same knob you just moved by hand: how far the smoother looks around each point before deciding how much to bend.

::widget spline-smoother {}

Push the slider toward the stiff end and the fitted curve barely bends, the way `trend(window = 105)` smoothed straight through the 2008-2009 slowdown. Push it toward the flexible end and the curve chases every wiggle, the way `trend(window = 13)` reversed direction 26 times. Somewhere in between, the curve settles close to the true shape underneath, the same middle ground a well-chosen trend window gives STL.

=== step === concept
## The season window: letting the shape drift, or fixing it forever

`season(window = m)` works the same way as the trend window, but for the yearly pattern. A numeric window lets the shape of that pattern evolve slowly from one year to the next. Setting `season(window = "periodic")` instead forces one identical shape, repeated exactly the same way every single year.

Look at July's contribution to the season under both rules, using the two fits from the last step. `fit_short` used a numeric `season(window = 7)`. `fit_long` used `season(window = "periodic")`.

```r
# Compare July's seasonal value under a drifting window and a fixed one
comp_long <- components(fit_long)

july_drift <- comp_short |> as_tibble() |> filter(lubridate::month(Month) == 7) |>
  filter(row_number() %in% c(1, n())) |> select(Month, season_year)
july_drift
#> # A tibble: 2 × 2
#>      Month season_year
#>      <mth>       <dbl>
#> 1 1982 Jul       -5.23
#> 2 2018 Jul       -6.12

july_fixed <- comp_long |> as_tibble() |> filter(lubridate::month(Month) == 7) |>
  filter(row_number() %in% c(1, n())) |> select(Month, season_year)
july_fixed
#> # A tibble: 2 × 2
#>      Month season_year
#>      <mth>       <dbl>
#> 1 1982 Jul       -3.05
#> 2 2018 Jul       -3.05
```

With the numeric window, July's seasonal value moves from -5.23 in 1982 to -6.12 in 2018, a real drift of almost a point across the decades. With `season(window = "periodic")`, July's value is exactly -3.05 in both years, and every year in between, because a periodic season is not allowed to change at all.

Real seasonal patterns often do drift a little as habits change over the decades. A numeric season window can follow that drift. `"periodic"` cannot, by design, so it is the right choice only when you are confident the yearly shape genuinely stays fixed.

=== step === quiz
## Quick check: choosing trend and season windows

::quiz {"correct": 2, "gate": true, "difficulty": "intermediate"}
- A bigger trend window is always the safer choice, since it smooths away more noise. ::no
- A short trend window can reverse direction on ordinary month to month noise, and a long enough window can smooth straight through a real slowdown and hide it completely. ::ok Right. trend(window = 13) reversed direction 26 separate times across the series, while trend(window = 105) never reversed once, even straight through the 2008-2009 slowdown. A longer window is not automatically safer, it can iron out a real event along with the noise.
- season(window = "periodic") lets the seasonal shape drift a little more each year than a numeric season window does. ::no
- The trend window and the season window must always be set to the same number. ::no A bigger trend window is not automatically safer: trend(window = 105) smoothed straight through the 2008-2009 slowdown and hid it completely. And it is the numeric season window that lets the shape drift; season(window = "periodic") is the one that stays fixed at the same value every year. The trend and season windows are also chosen independently of each other.

=== step === concept
## Robust fitting: the outlier that does not disappear

January 2009 sits right in the middle of the global financial crisis, and Victoria's cafe and restaurant turnover that month, $647.8 million, does not fit the pattern around it. Fit STL with `trend(window = 21)` and `season(window = 11)` again, without robust fitting yet, and check which month gets the largest remainder.

```r
# Fit STL without robust weighting and find the largest remainder
fit_nr <- cafe |> model(STL(Turnover ~ trend(window = 21) + season(window = 11), robust = FALSE))
comp_nr <- components(fit_nr)

comp_nr |> as_tibble() |> filter(abs(remainder) == max(abs(remainder))) |>
  select(Month, Turnover, trend, season_year, remainder)
#> # A tibble: 1 × 5
#>      Month Turnover trend season_year remainder
#>      <mth>    <dbl> <dbl>       <dbl>     <dbl>
#> 1 2009 Jan     648.  603.       -4.69      49.7
```

January 2009 has the single largest remainder in the whole series, 49.7, against a trend of 603 and a season of -4.69. The ordinary fit treats January 2009 like any other month: it fits trend and season straight through it the same way, and whatever those two components leave unaccounted for lands in the remainder.

Set `robust = TRUE` and refit. Robust fitting downweights points with a large remainder before it re-estimates trend and season, so an unusual month influences its neighbours less.

```r
# Refit with robust = TRUE and compare January and February 2009 both ways
fit_r <- cafe |> model(STL(Turnover ~ trend(window = 21) + season(window = 11), robust = TRUE))
comp_r <- components(fit_r)

comp_r |> as_tibble() |> filter(Month %in% yearmonth(c("2009 Jan", "2009 Feb"))) |>
  select(Month, trend, season_year, remainder)
#> # A tibble: 2 × 4
#>      Month trend season_year remainder
#>      <mth> <dbl>       <dbl>     <dbl>
#> 1 2009 Jan  595.       -2.33      55.4
#> 2 2009 Feb  601.      -58.3       33.2

comp_nr |> as_tibble() |> filter(Month %in% yearmonth(c("2009 Jan", "2009 Feb"))) |>
  select(Month, trend, season_year, remainder)
#> # A tibble: 2 × 4
#>      Month trend season_year remainder
#>      <mth> <dbl>       <dbl>     <dbl>
#> 1 2009 Jan  603.       -4.69      49.7
#> 2 2009 Feb  609.      -51.9       19.3
```

At January 2009, the trend moves from 603 down to 595 and the season moves from -4.69 to -2.33. But the remainder does not shrink. It grows, from 49.7 to 55.4. At February 2009, right next door, the season shifts from -51.9 to -58.3, because that month's estimate is no longer being pulled around by January's outlier sitting beside it.

That is the real effect of `robust = TRUE`. It protects the trend and season estimates for the months around an outlier. It does not, and cannot, make the outlier's own remainder any smaller, because the remainder is whatever trend and season could not explain, and an outlier is by definition the hardest month of all to explain.

=== step === concept
## What components() returns, and how to read the scaled bars in autoplot

You have now seen all four columns `components()` returns: `trend`, `season_year`, `remainder` and `season_adjust`. Put a number on how much each one actually moves, using the robust fit from the last step.

```r
# Compare the range of the observed series against each fitted component
comp_r |> as_tibble() |> summarise(
  Turnover = diff(range(Turnover)),
  trend = diff(range(trend, na.rm = TRUE)),
  season_year = diff(range(season_year, na.rm = TRUE)),
  remainder = diff(range(remainder, na.rm = TRUE))
)
#> # A tibble: 1 × 4
#>   Turnover trend season_year remainder
#>      <dbl> <dbl>       <dbl>     <dbl>
#> 1     985.  871.        171.      123.
```

The observed turnover ranges over 984.9, from its lowest month to its highest. Trend alone ranges over 871.2 of that, season_year over 171.2, and remainder over only 123.5. Trend is carrying almost the whole climb; remainder is the smallest, flattest piece of the four.

`autoplot()` on a fitted STL model draws these same four columns as stacked panels, and next to each panel it draws a small grey bar. Every one of those bars is the same absolute length, measured in the series' own units. A panel whose own range is already close to the full range of the data barely needs stretching to fill its box, so it ends up with a small bar next to it. A panel whose own range is small has to be stretched a lot to be visible, so it ends up with a tall bar.

A small bar therefore marks the component carrying most of the real movement, and a tall bar marks the one carrying the least. Trend, at 871.2 of the observed 984.9, gets the small bar here. Remainder, at only 123.5, gets the tall one.

=== step === widget
## Seeing STL's four components side by side

Put a picture next to those four numbers. The widget below plots Observed, Trend, Season and Remainder from the same robust fit, either combined on one chart or split into four small multiples, one panel per component.

::widget facet-grid {"data":[{"x":1,"y":85.1,"facet":"Observed"},{"x":2,"y":85.1,"facet":"Observed"},{"x":3,"y":82.8,"facet":"Observed"},{"x":4,"y":82.1,"facet":"Observed"},{"x":5,"y":81.8,"facet":"Observed"},{"x":6,"y":84.6,"facet":"Observed"},{"x":7,"y":91.7,"facet":"Observed"},{"x":8,"y":97.7,"facet":"Observed"},{"x":9,"y":109.3,"facet":"Observed"},{"x":10,"y":94.6,"facet":"Observed"},{"x":11,"y":88.2,"facet":"Observed"},{"x":12,"y":92.0,"facet":"Observed"},{"x":13,"y":85.2,"facet":"Observed"},{"x":14,"y":86.8,"facet":"Observed"},{"x":15,"y":81.3,"facet":"Observed"},{"x":16,"y":85.6,"facet":"Observed"},{"x":17,"y":90.5,"facet":"Observed"},{"x":18,"y":90.8,"facet":"Observed"},{"x":19,"y":92.7,"facet":"Observed"},{"x":20,"y":95.8,"facet":"Observed"},{"x":21,"y":111.7,"facet":"Observed"},{"x":22,"y":92.7,"facet":"Observed"},{"x":23,"y":94.4,"facet":"Observed"},{"x":24,"y":97.8,"facet":"Observed"},{"x":25,"y":92.9,"facet":"Observed"},{"x":26,"y":101.0,"facet":"Observed"},{"x":27,"y":92.1,"facet":"Observed"},{"x":28,"y":92.5,"facet":"Observed"},{"x":29,"y":94.4,"facet":"Observed"},{"x":30,"y":90.4,"facet":"Observed"},{"x":31,"y":95.7,"facet":"Observed"},{"x":32,"y":100.6,"facet":"Observed"},{"x":33,"y":112.4,"facet":"Observed"},{"x":34,"y":96.3,"facet":"Observed"},{"x":35,"y":93.9,"facet":"Observed"},{"x":36,"y":98.0,"facet":"Observed"},{"x":37,"y":98.4,"facet":"Observed"},{"x":38,"y":101.8,"facet":"Observed"},{"x":39,"y":90.8,"facet":"Observed"},{"x":40,"y":98.3,"facet":"Observed"},{"x":41,"y":107.0,"facet":"Observed"},{"x":42,"y":103.2,"facet":"Observed"},{"x":43,"y":111.8,"facet":"Observed"},{"x":44,"y":112.3,"facet":"Observed"},{"x":45,"y":126.8,"facet":"Observed"},{"x":46,"y":113.8,"facet":"Observed"},{"x":47,"y":104.4,"facet":"Observed"},{"x":48,"y":109.7,"facet":"Observed"},{"x":49,"y":110.2,"facet":"Observed"},{"x":50,"y":118.0,"facet":"Observed"},{"x":51,"y":108.2,"facet":"Observed"},{"x":52,"y":123.5,"facet":"Observed"},{"x":53,"y":131.7,"facet":"Observed"},{"x":54,"y":132.9,"facet":"Observed"},{"x":55,"y":142.8,"facet":"Observed"},{"x":56,"y":138.3,"facet":"Observed"},{"x":57,"y":159.5,"facet":"Observed"},{"x":58,"y":138.9,"facet":"Observed"},{"x":59,"y":130.9,"facet":"Observed"},{"x":60,"y":136.3,"facet":"Observed"},{"x":61,"y":142.7,"facet":"Observed"},{"x":62,"y":144.2,"facet":"Observed"},{"x":63,"y":137.9,"facet":"Observed"},{"x":64,"y":149.0,"facet":"Observed"},{"x":65,"y":146.4,"facet":"Observed"},{"x":66,"y":146.4,"facet":"Observed"},{"x":67,"y":157.3,"facet":"Observed"},{"x":68,"y":155.3,"facet":"Observed"},{"x":69,"y":186.5,"facet":"Observed"},{"x":70,"y":143.3,"facet":"Observed"},{"x":71,"y":146.7,"facet":"Observed"},{"x":72,"y":159.6,"facet":"Observed"},{"x":73,"y":158.7,"facet":"Observed"},{"x":74,"y":151.7,"facet":"Observed"},{"x":75,"y":155.7,"facet":"Observed"},{"x":76,"y":154.0,"facet":"Observed"},{"x":77,"y":159.9,"facet":"Observed"},{"x":78,"y":165.3,"facet":"Observed"},{"x":79,"y":167.8,"facet":"Observed"},{"x":80,"y":176.4,"facet":"Observed"},{"x":81,"y":186.2,"facet":"Observed"},{"x":82,"y":167.2,"facet":"Observed"},{"x":83,"y":167.9,"facet":"Observed"},{"x":84,"y":180.6,"facet":"Observed"},{"x":85,"y":179.4,"facet":"Observed"},{"x":86,"y":182.9,"facet":"Observed"},{"x":87,"y":177.5,"facet":"Observed"},{"x":88,"y":183.3,"facet":"Observed"},{"x":89,"y":177.4,"facet":"Observed"},{"x":90,"y":188.3,"facet":"Observed"},{"x":91,"y":203.0,"facet":"Observed"},{"x":92,"y":203.6,"facet":"Observed"},{"x":93,"y":236.8,"facet":"Observed"},{"x":94,"y":198.3,"facet":"Observed"},{"x":95,"y":183.5,"facet":"Observed"},{"x":96,"y":204.6,"facet":"Observed"},{"x":97,"y":183.9,"facet":"Observed"},{"x":98,"y":183.5,"facet":"Observed"},{"x":99,"y":182.1,"facet":"Observed"},{"x":100,"y":193.4,"facet":"Observed"},{"x":101,"y":186.7,"facet":"Observed"},{"x":102,"y":182.9,"facet":"Observed"},{"x":103,"y":185.2,"facet":"Observed"},{"x":104,"y":183.1,"facet":"Observed"},{"x":105,"y":209.1,"facet":"Observed"},{"x":106,"y":187.8,"facet":"Observed"},{"x":107,"y":166.9,"facet":"Observed"},{"x":108,"y":174.1,"facet":"Observed"},{"x":109,"y":169.5,"facet":"Observed"},{"x":110,"y":177.7,"facet":"Observed"},{"x":111,"y":179.0,"facet":"Observed"},{"x":112,"y":179.0,"facet":"Observed"},{"x":113,"y":181.2,"facet":"Observed"},{"x":114,"y":183.2,"facet":"Observed"},{"x":115,"y":183.9,"facet":"Observed"},{"x":116,"y":189.0,"facet":"Observed"},{"x":117,"y":227.5,"facet":"Observed"},{"x":118,"y":192.3,"facet":"Observed"},{"x":119,"y":184.5,"facet":"Observed"},{"x":120,"y":197.9,"facet":"Observed"},{"x":121,"y":195.6,"facet":"Observed"},{"x":122,"y":193.9,"facet":"Observed"},{"x":123,"y":169.3,"facet":"Observed"},{"x":124,"y":177.9,"facet":"Observed"},{"x":125,"y":173.4,"facet":"Observed"},{"x":126,"y":190.6,"facet":"Observed"},{"x":127,"y":192.4,"facet":"Observed"},{"x":128,"y":195.4,"facet":"Observed"},{"x":129,"y":234.0,"facet":"Observed"},{"x":130,"y":207.4,"facet":"Observed"},{"x":131,"y":182.1,"facet":"Observed"},{"x":132,"y":191.1,"facet":"Observed"},{"x":133,"y":189.8,"facet":"Observed"},{"x":134,"y":192.1,"facet":"Observed"},{"x":135,"y":185.7,"facet":"Observed"},{"x":136,"y":200.2,"facet":"Observed"},{"x":137,"y":192.4,"facet":"Observed"},{"x":138,"y":195.1,"facet":"Observed"},{"x":139,"y":192.5,"facet":"Observed"},{"x":140,"y":202.3,"facet":"Observed"},{"x":141,"y":235.9,"facet":"Observed"},{"x":142,"y":194.1,"facet":"Observed"},{"x":143,"y":185.3,"facet":"Observed"},{"x":144,"y":194.6,"facet":"Observed"},{"x":145,"y":181.8,"facet":"Observed"},{"x":146,"y":179.9,"facet":"Observed"},{"x":147,"y":180.0,"facet":"Observed"},{"x":148,"y":194.6,"facet":"Observed"},{"x":149,"y":193.7,"facet":"Observed"},{"x":150,"y":206.0,"facet":"Observed"},{"x":151,"y":225.1,"facet":"Observed"},{"x":152,"y":219.9,"facet":"Observed"},{"x":153,"y":246.3,"facet":"Observed"},{"x":154,"y":222.3,"facet":"Observed"},{"x":155,"y":207.2,"facet":"Observed"},{"x":156,"y":238.1,"facet":"Observed"},{"x":157,"y":229.0,"facet":"Observed"},{"x":158,"y":222.4,"facet":"Observed"},{"x":159,"y":221.5,"facet":"Observed"},{"x":160,"y":225.4,"facet":"Observed"},{"x":161,"y":227.4,"facet":"Observed"},{"x":162,"y":233.4,"facet":"Observed"},{"x":163,"y":230.2,"facet":"Observed"},{"x":164,"y":240.4,"facet":"Observed"},{"x":165,"y":259.4,"facet":"Observed"},{"x":166,"y":239.1,"facet":"Observed"},{"x":167,"y":219.0,"facet":"Observed"},{"x":168,"y":238.4,"facet":"Observed"},{"x":169,"y":236.4,"facet":"Observed"},{"x":170,"y":235.6,"facet":"Observed"},{"x":171,"y":225.8,"facet":"Observed"},{"x":172,"y":229.9,"facet":"Observed"},{"x":173,"y":228.8,"facet":"Observed"},{"x":174,"y":219.2,"facet":"Observed"},{"x":175,"y":225.5,"facet":"Observed"},{"x":176,"y":233.3,"facet":"Observed"},{"x":177,"y":254.6,"facet":"Observed"},{"x":178,"y":242.1,"facet":"Observed"},{"x":179,"y":216.1,"facet":"Observed"},{"x":180,"y":249.9,"facet":"Observed"},{"x":181,"y":250.8,"facet":"Observed"},{"x":182,"y":252.7,"facet":"Observed"},{"x":183,"y":235.8,"facet":"Observed"},{"x":184,"y":237.5,"facet":"Observed"},{"x":185,"y":237.8,"facet":"Observed"},{"x":186,"y":235.0,"facet":"Observed"},{"x":187,"y":243.4,"facet":"Observed"},{"x":188,"y":238.5,"facet":"Observed"},{"x":189,"y":264.3,"facet":"Observed"},{"x":190,"y":241.5,"facet":"Observed"},{"x":191,"y":218.0,"facet":"Observed"},{"x":192,"y":245.4,"facet":"Observed"},{"x":193,"y":235.8,"facet":"Observed"},{"x":194,"y":240.2,"facet":"Observed"},{"x":195,"y":226.9,"facet":"Observed"},{"x":196,"y":248.4,"facet":"Observed"},{"x":197,"y":255.5,"facet":"Observed"},{"x":198,"y":248.0,"facet":"Observed"},{"x":199,"y":268.0,"facet":"Observed"},{"x":200,"y":260.5,"facet":"Observed"},{"x":201,"y":284.2,"facet":"Observed"},{"x":202,"y":267.7,"facet":"Observed"},{"x":203,"y":248.6,"facet":"Observed"},{"x":204,"y":283.3,"facet":"Observed"},{"x":205,"y":285.6,"facet":"Observed"},{"x":206,"y":299.1,"facet":"Observed"},{"x":207,"y":295.2,"facet":"Observed"},{"x":208,"y":321.5,"facet":"Observed"},{"x":209,"y":331.3,"facet":"Observed"},{"x":210,"y":340.2,"facet":"Observed"},{"x":211,"y":345.6,"facet":"Observed"},{"x":212,"y":352.3,"facet":"Observed"},{"x":213,"y":392.1,"facet":"Observed"},{"x":214,"y":331.1,"facet":"Observed"},{"x":215,"y":295.7,"facet":"Observed"},{"x":216,"y":337.2,"facet":"Observed"},{"x":217,"y":283.7,"facet":"Observed"},{"x":218,"y":308.9,"facet":"Observed"},{"x":219,"y":306.3,"facet":"Observed"},{"x":220,"y":301.3,"facet":"Observed"},{"x":221,"y":307.6,"facet":"Observed"},{"x":222,"y":296.9,"facet":"Observed"},{"x":223,"y":326.2,"facet":"Observed"},{"x":224,"y":324.8,"facet":"Observed"},{"x":225,"y":359.9,"facet":"Observed"},{"x":226,"y":336.3,"facet":"Observed"},{"x":227,"y":311.7,"facet":"Observed"},{"x":228,"y":358.4,"facet":"Observed"},{"x":229,"y":367.0,"facet":"Observed"},{"x":230,"y":354.4,"facet":"Observed"},{"x":231,"y":347.5,"facet":"Observed"},{"x":232,"y":371.3,"facet":"Observed"},{"x":233,"y":391.5,"facet":"Observed"},{"x":234,"y":349.1,"facet":"Observed"},{"x":235,"y":361.9,"facet":"Observed"},{"x":236,"y":366.2,"facet":"Observed"},{"x":237,"y":409.1,"facet":"Observed"},{"x":238,"y":385.2,"facet":"Observed"},{"x":239,"y":356.0,"facet":"Observed"},{"x":240,"y":399.2,"facet":"Observed"},{"x":241,"y":372.7,"facet":"Observed"},{"x":242,"y":368.8,"facet":"Observed"},{"x":243,"y":355.6,"facet":"Observed"},{"x":244,"y":414.5,"facet":"Observed"},{"x":245,"y":410.0,"facet":"Observed"},{"x":246,"y":392.5,"facet":"Observed"},{"x":247,"y":377.5,"facet":"Observed"},{"x":248,"y":393.1,"facet":"Observed"},{"x":249,"y":441.2,"facet":"Observed"},{"x":250,"y":446.4,"facet":"Observed"},{"x":251,"y":378.4,"facet":"Observed"},{"x":252,"y":418.4,"facet":"Observed"},{"x":253,"y":406.2,"facet":"Observed"},{"x":254,"y":426.2,"facet":"Observed"},{"x":255,"y":399.1,"facet":"Observed"},{"x":256,"y":449.0,"facet":"Observed"},{"x":257,"y":437.6,"facet":"Observed"},{"x":258,"y":434.9,"facet":"Observed"},{"x":259,"y":479.9,"facet":"Observed"},{"x":260,"y":473.8,"facet":"Observed"},{"x":261,"y":529.9,"facet":"Observed"},{"x":262,"y":478.1,"facet":"Observed"},{"x":263,"y":457.0,"facet":"Observed"},{"x":264,"y":499.3,"facet":"Observed"},{"x":265,"y":471.8,"facet":"Observed"},{"x":266,"y":468.5,"facet":"Observed"},{"x":267,"y":438.1,"facet":"Observed"},{"x":268,"y":468.4,"facet":"Observed"},{"x":269,"y":468.4,"facet":"Observed"},{"x":270,"y":490.9,"facet":"Observed"},{"x":271,"y":473.9,"facet":"Observed"},{"x":272,"y":463.0,"facet":"Observed"},{"x":273,"y":509.6,"facet":"Observed"},{"x":274,"y":432.0,"facet":"Observed"},{"x":275,"y":408.1,"facet":"Observed"},{"x":276,"y":436.7,"facet":"Observed"},{"x":277,"y":439.4,"facet":"Observed"},{"x":278,"y":430.9,"facet":"Observed"},{"x":279,"y":427.2,"facet":"Observed"},{"x":280,"y":451.1,"facet":"Observed"},{"x":281,"y":448.6,"facet":"Observed"},{"x":282,"y":441.9,"facet":"Observed"},{"x":283,"y":474.4,"facet":"Observed"},{"x":284,"y":474.2,"facet":"Observed"},{"x":285,"y":506.6,"facet":"Observed"},{"x":286,"y":468.2,"facet":"Observed"},{"x":287,"y":433.3,"facet":"Observed"},{"x":288,"y":503.8,"facet":"Observed"},{"x":289,"y":501.8,"facet":"Observed"},{"x":290,"y":522.5,"facet":"Observed"},{"x":291,"y":495.4,"facet":"Observed"},{"x":292,"y":507.1,"facet":"Observed"},{"x":293,"y":520.6,"facet":"Observed"},{"x":294,"y":513.5,"facet":"Observed"},{"x":295,"y":504.3,"facet":"Observed"},{"x":296,"y":528.6,"facet":"Observed"},{"x":297,"y":584.8,"facet":"Observed"},{"x":298,"y":523.9,"facet":"Observed"},{"x":299,"y":481.2,"facet":"Observed"},{"x":300,"y":545.1,"facet":"Observed"},{"x":301,"y":531.1,"facet":"Observed"},{"x":302,"y":510.3,"facet":"Observed"},{"x":303,"y":490.1,"facet":"Observed"},{"x":304,"y":497.6,"facet":"Observed"},{"x":305,"y":526.4,"facet":"Observed"},{"x":306,"y":494.6,"facet":"Observed"},{"x":307,"y":540.9,"facet":"Observed"},{"x":308,"y":547.9,"facet":"Observed"},{"x":309,"y":596.3,"facet":"Observed"},{"x":310,"y":539.6,"facet":"Observed"},{"x":311,"y":523.1,"facet":"Observed"},{"x":312,"y":550.6,"facet":"Observed"},{"x":313,"y":541.1,"facet":"Observed"},{"x":314,"y":548.6,"facet":"Observed"},{"x":315,"y":516.2,"facet":"Observed"},{"x":316,"y":541.8,"facet":"Observed"},{"x":317,"y":557.8,"facet":"Observed"},{"x":318,"y":537.3,"facet":"Observed"},{"x":319,"y":591.2,"facet":"Observed"},{"x":320,"y":584.0,"facet":"Observed"},{"x":321,"y":673.1,"facet":"Observed"},{"x":322,"y":647.8,"facet":"Observed"},{"x":323,"y":576.0,"facet":"Observed"},{"x":324,"y":634.5,"facet":"Observed"},{"x":325,"y":622.2,"facet":"Observed"},{"x":326,"y":631.6,"facet":"Observed"},{"x":327,"y":594.2,"facet":"Observed"},{"x":328,"y":613.4,"facet":"Observed"},{"x":329,"y":642.4,"facet":"Observed"},{"x":330,"y":615.6,"facet":"Observed"},{"x":331,"y":636.5,"facet":"Observed"},{"x":332,"y":654.1,"facet":"Observed"},{"x":333,"y":742.0,"facet":"Observed"},{"x":334,"y":657.9,"facet":"Observed"},{"x":335,"y":611.4,"facet":"Observed"},{"x":336,"y":704.2,"facet":"Observed"},{"x":337,"y":697.6,"facet":"Observed"},{"x":338,"y":692.0,"facet":"Observed"},{"x":339,"y":669.7,"facet":"Observed"},{"x":340,"y":724.2,"facet":"Observed"},{"x":341,"y":748.9,"facet":"Observed"},{"x":342,"y":735.8,"facet":"Observed"},{"x":343,"y":705.0,"facet":"Observed"},{"x":344,"y":693.9,"facet":"Observed"},{"x":345,"y":806.9,"facet":"Observed"},{"x":346,"y":649.4,"facet":"Observed"},{"x":347,"y":597.8,"facet":"Observed"},{"x":348,"y":689.6,"facet":"Observed"},{"x":349,"y":707.6,"facet":"Observed"},{"x":350,"y":699.1,"facet":"Observed"},{"x":351,"y":672.5,"facet":"Observed"},{"x":352,"y":694.0,"facet":"Observed"},{"x":353,"y":694.7,"facet":"Observed"},{"x":354,"y":686.9,"facet":"Observed"},{"x":355,"y":682.1,"facet":"Observed"},{"x":356,"y":681.5,"facet":"Observed"},{"x":357,"y":761.4,"facet":"Observed"},{"x":358,"y":638.4,"facet":"Observed"},{"x":359,"y":594.5,"facet":"Observed"},{"x":360,"y":679.6,"facet":"Observed"},{"x":361,"y":632.5,"facet":"Observed"},{"x":362,"y":666.8,"facet":"Observed"},{"x":363,"y":661.9,"facet":"Observed"},{"x":364,"y":676.4,"facet":"Observed"},{"x":365,"y":681.5,"facet":"Observed"},{"x":366,"y":662.4,"facet":"Observed"},{"x":367,"y":684.9,"facet":"Observed"},{"x":368,"y":707.0,"facet":"Observed"},{"x":369,"y":750.8,"facet":"Observed"},{"x":370,"y":655.5,"facet":"Observed"},{"x":371,"y":605.2,"facet":"Observed"},{"x":372,"y":683.2,"facet":"Observed"},{"x":373,"y":682.8,"facet":"Observed"},{"x":374,"y":682.0,"facet":"Observed"},{"x":375,"y":651.6,"facet":"Observed"},{"x":376,"y":656.7,"facet":"Observed"},{"x":377,"y":664.9,"facet":"Observed"},{"x":378,"y":665.7,"facet":"Observed"},{"x":379,"y":686.0,"facet":"Observed"},{"x":380,"y":707.5,"facet":"Observed"},{"x":381,"y":792.2,"facet":"Observed"},{"x":382,"y":721.2,"facet":"Observed"},{"x":383,"y":631.6,"facet":"Observed"},{"x":384,"y":725.5,"facet":"Observed"},{"x":385,"y":722.1,"facet":"Observed"},{"x":386,"y":718.8,"facet":"Observed"},{"x":387,"y":693.6,"facet":"Observed"},{"x":388,"y":753.8,"facet":"Observed"},{"x":389,"y":784.4,"facet":"Observed"},{"x":390,"y":791.9,"facet":"Observed"},{"x":391,"y":789.5,"facet":"Observed"},{"x":392,"y":778.2,"facet":"Observed"},{"x":393,"y":838.1,"facet":"Observed"},{"x":394,"y":786.6,"facet":"Observed"},{"x":395,"y":689.1,"facet":"Observed"},{"x":396,"y":753.4,"facet":"Observed"},{"x":397,"y":737.5,"facet":"Observed"},{"x":398,"y":740.3,"facet":"Observed"},{"x":399,"y":726.1,"facet":"Observed"},{"x":400,"y":780.8,"facet":"Observed"},{"x":401,"y":795.0,"facet":"Observed"},{"x":402,"y":795.8,"facet":"Observed"},{"x":403,"y":811.7,"facet":"Observed"},{"x":404,"y":832.6,"facet":"Observed"},{"x":405,"y":896.7,"facet":"Observed"},{"x":406,"y":790.8,"facet":"Observed"},{"x":407,"y":732.4,"facet":"Observed"},{"x":408,"y":793.3,"facet":"Observed"},{"x":409,"y":805.4,"facet":"Observed"},{"x":410,"y":808.9,"facet":"Observed"},{"x":411,"y":769.0,"facet":"Observed"},{"x":412,"y":828.7,"facet":"Observed"},{"x":413,"y":866.3,"facet":"Observed"},{"x":414,"y":878.3,"facet":"Observed"},{"x":415,"y":886.3,"facet":"Observed"},{"x":416,"y":879.5,"facet":"Observed"},{"x":417,"y":961.8,"facet":"Observed"},{"x":418,"y":861.4,"facet":"Observed"},{"x":419,"y":753.6,"facet":"Observed"},{"x":420,"y":868.4,"facet":"Observed"},{"x":421,"y":859.7,"facet":"Observed"},{"x":422,"y":845.2,"facet":"Observed"},{"x":423,"y":828.7,"facet":"Observed"},{"x":424,"y":857.6,"facet":"Observed"},{"x":425,"y":874.1,"facet":"Observed"},{"x":426,"y":872.4,"facet":"Observed"},{"x":427,"y":917.7,"facet":"Observed"},{"x":428,"y":925.7,"facet":"Observed"},{"x":429,"y":1008.1,"facet":"Observed"},{"x":430,"y":887.3,"facet":"Observed"},{"x":431,"y":810.6,"facet":"Observed"},{"x":432,"y":909.7,"facet":"Observed"},{"x":433,"y":898.6,"facet":"Observed"},{"x":434,"y":866.4,"facet":"Observed"},{"x":435,"y":873.1,"facet":"Observed"},{"x":436,"y":916.1,"facet":"Observed"},{"x":437,"y":943.8,"facet":"Observed"},{"x":438,"y":933.8,"facet":"Observed"},{"x":439,"y":960.0,"facet":"Observed"},{"x":440,"y":981.8,"facet":"Observed"},{"x":441,"y":1066.2,"facet":"Observed"},{"x":1,"y":87.1,"facet":"Trend"},{"x":2,"y":87.5,"facet":"Trend"},{"x":3,"y":87.8,"facet":"Trend"},{"x":4,"y":88.2,"facet":"Trend"},{"x":5,"y":88.5,"facet":"Trend"},{"x":6,"y":88.8,"facet":"Trend"},{"x":7,"y":89.1,"facet":"Trend"},{"x":8,"y":89.4,"facet":"Trend"},{"x":9,"y":89.7,"facet":"Trend"},{"x":10,"y":90.0,"facet":"Trend"},{"x":11,"y":90.3,"facet":"Trend"},{"x":12,"y":90.6,"facet":"Trend"},{"x":13,"y":90.9,"facet":"Trend"},{"x":14,"y":91.0,"facet":"Trend"},{"x":15,"y":91.2,"facet":"Trend"},{"x":16,"y":91.3,"facet":"Trend"},{"x":17,"y":91.8,"facet":"Trend"},{"x":18,"y":92.2,"facet":"Trend"},{"x":19,"y":92.6,"facet":"Trend"},{"x":20,"y":93.3,"facet":"Trend"},{"x":21,"y":94.0,"facet":"Trend"},{"x":22,"y":94.7,"facet":"Trend"},{"x":23,"y":95.1,"facet":"Trend"},{"x":24,"y":95.5,"facet":"Trend"},{"x":25,"y":95.9,"facet":"Trend"},{"x":26,"y":96.1,"facet":"Trend"},{"x":27,"y":96.3,"facet":"Trend"},{"x":28,"y":96.5,"facet":"Trend"},{"x":29,"y":96.6,"facet":"Trend"},{"x":30,"y":96.8,"facet":"Trend"},{"x":31,"y":96.9,"facet":"Trend"},{"x":32,"y":97.2,"facet":"Trend"},{"x":33,"y":97.5,"facet":"Trend"},{"x":34,"y":97.9,"facet":"Trend"},{"x":35,"y":98.7,"facet":"Trend"},{"x":36,"y":99.6,"facet":"Trend"},{"x":37,"y":100.4,"facet":"Trend"},{"x":38,"y":101.6,"facet":"Trend"},{"x":39,"y":102.7,"facet":"Trend"},{"x":40,"y":103.8,"facet":"Trend"},{"x":41,"y":105.0,"facet":"Trend"},{"x":42,"y":106.1,"facet":"Trend"},{"x":43,"y":107.2,"facet":"Trend"},{"x":44,"y":108.7,"facet":"Trend"},{"x":45,"y":110.2,"facet":"Trend"},{"x":46,"y":111.7,"facet":"Trend"},{"x":47,"y":113.9,"facet":"Trend"},{"x":48,"y":116.0,"facet":"Trend"},{"x":49,"y":118.2,"facet":"Trend"},{"x":50,"y":120.6,"facet":"Trend"},{"x":51,"y":122.9,"facet":"Trend"},{"x":52,"y":125.3,"facet":"Trend"},{"x":53,"y":127.6,"facet":"Trend"},{"x":54,"y":130.0,"facet":"Trend"},{"x":55,"y":132.4,"facet":"Trend"},{"x":56,"y":134.5,"facet":"Trend"},{"x":57,"y":136.7,"facet":"Trend"},{"x":58,"y":138.8,"facet":"Trend"},{"x":59,"y":140.4,"facet":"Trend"},{"x":60,"y":142.0,"facet":"Trend"},{"x":61,"y":143.6,"facet":"Trend"},{"x":62,"y":145.0,"facet":"Trend"},{"x":63,"y":146.3,"facet":"Trend"},{"x":64,"y":147.7,"facet":"Trend"},{"x":65,"y":149.0,"facet":"Trend"},{"x":66,"y":150.4,"facet":"Trend"},{"x":67,"y":151.7,"facet":"Trend"},{"x":68,"y":152.8,"facet":"Trend"},{"x":69,"y":154.0,"facet":"Trend"},{"x":70,"y":155.1,"facet":"Trend"},{"x":71,"y":156.2,"facet":"Trend"},{"x":72,"y":157.4,"facet":"Trend"},{"x":73,"y":158.5,"facet":"Trend"},{"x":74,"y":159.7,"facet":"Trend"},{"x":75,"y":161.0,"facet":"Trend"},{"x":76,"y":162.2,"facet":"Trend"},{"x":77,"y":163.9,"facet":"Trend"},{"x":78,"y":165.7,"facet":"Trend"},{"x":79,"y":167.4,"facet":"Trend"},{"x":80,"y":169.4,"facet":"Trend"},{"x":81,"y":171.5,"facet":"Trend"},{"x":82,"y":173.5,"facet":"Trend"},{"x":83,"y":175.8,"facet":"Trend"},{"x":84,"y":178.1,"facet":"Trend"},{"x":85,"y":180.3,"facet":"Trend"},{"x":86,"y":182.8,"facet":"Trend"},{"x":87,"y":185.2,"facet":"Trend"},{"x":88,"y":187.6,"facet":"Trend"},{"x":89,"y":189.1,"facet":"Trend"},{"x":90,"y":190.6,"facet":"Trend"},{"x":91,"y":192.1,"facet":"Trend"},{"x":92,"y":192.7,"facet":"Trend"},{"x":93,"y":193.3,"facet":"Trend"},{"x":94,"y":193.9,"facet":"Trend"},{"x":95,"y":193.7,"facet":"Trend"},{"x":96,"y":193.5,"facet":"Trend"},{"x":97,"y":193.3,"facet":"Trend"},{"x":98,"y":192.0,"facet":"Trend"},{"x":99,"y":190.6,"facet":"Trend"},{"x":100,"y":189.3,"facet":"Trend"},{"x":101,"y":187.8,"facet":"Trend"},{"x":102,"y":186.4,"facet":"Trend"},{"x":103,"y":184.9,"facet":"Trend"},{"x":104,"y":184.1,"facet":"Trend"},{"x":105,"y":183.3,"facet":"Trend"},{"x":106,"y":182.5,"facet":"Trend"},{"x":107,"y":182.3,"facet":"Trend"},{"x":108,"y":182.1,"facet":"Trend"},{"x":109,"y":181.9,"facet":"Trend"},{"x":110,"y":182.5,"facet":"Trend"},{"x":111,"y":183.1,"facet":"Trend"},{"x":112,"y":183.8,"facet":"Trend"},{"x":113,"y":185.1,"facet":"Trend"},{"x":114,"y":186.3,"facet":"Trend"},{"x":115,"y":187.6,"facet":"Trend"},{"x":116,"y":188.3,"facet":"Trend"},{"x":117,"y":189.1,"facet":"Trend"},{"x":118,"y":189.8,"facet":"Trend"},{"x":119,"y":190.1,"facet":"Trend"},{"x":120,"y":190.3,"facet":"Trend"},{"x":121,"y":190.6,"facet":"Trend"},{"x":122,"y":191.1,"facet":"Trend"},{"x":123,"y":191.5,"facet":"Trend"},{"x":124,"y":192.0,"facet":"Trend"},{"x":125,"y":192.1,"facet":"Trend"},{"x":126,"y":192.2,"facet":"Trend"},{"x":127,"y":192.2,"facet":"Trend"},{"x":128,"y":192.7,"facet":"Trend"},{"x":129,"y":193.2,"facet":"Trend"},{"x":130,"y":193.7,"facet":"Trend"},{"x":131,"y":194.5,"facet":"Trend"},{"x":132,"y":195.2,"facet":"Trend"},{"x":133,"y":196.0,"facet":"Trend"},{"x":134,"y":196.2,"facet":"Trend"},{"x":135,"y":196.5,"facet":"Trend"},{"x":136,"y":196.7,"facet":"Trend"},{"x":137,"y":196.5,"facet":"Trend"},{"x":138,"y":196.3,"facet":"Trend"},{"x":139,"y":196.1,"facet":"Trend"},{"x":140,"y":195.9,"facet":"Trend"},{"x":141,"y":195.6,"facet":"Trend"},{"x":142,"y":195.4,"facet":"Trend"},{"x":143,"y":196.1,"facet":"Trend"},{"x":144,"y":196.7,"facet":"Trend"},{"x":145,"y":197.4,"facet":"Trend"},{"x":146,"y":199.0,"facet":"Trend"},{"x":147,"y":200.7,"facet":"Trend"},{"x":148,"y":202.3,"facet":"Trend"},{"x":149,"y":204.9,"facet":"Trend"},{"x":150,"y":207.4,"facet":"Trend"},{"x":151,"y":210.0,"facet":"Trend"},{"x":152,"y":213.0,"facet":"Trend"},{"x":153,"y":216.0,"facet":"Trend"},{"x":154,"y":219.0,"facet":"Trend"},{"x":155,"y":221.3,"facet":"Trend"},{"x":156,"y":223.5,"facet":"Trend"},{"x":157,"y":225.8,"facet":"Trend"},{"x":158,"y":227.2,"facet":"Trend"},{"x":159,"y":228.6,"facet":"Trend"},{"x":160,"y":230.1,"facet":"Trend"},{"x":161,"y":231.0,"facet":"Trend"},{"x":162,"y":231.9,"facet":"Trend"},{"x":163,"y":232.7,"facet":"Trend"},{"x":164,"y":233.1,"facet":"Trend"},{"x":165,"y":233.6,"facet":"Trend"},{"x":166,"y":234.0,"facet":"Trend"},{"x":167,"y":233.8,"facet":"Trend"},{"x":168,"y":233.6,"facet":"Trend"},{"x":169,"y":233.5,"facet":"Trend"},{"x":170,"y":233.2,"facet":"Trend"},{"x":171,"y":233.0,"facet":"Trend"},{"x":172,"y":232.8,"facet":"Trend"},{"x":173,"y":233.3,"facet":"Trend"},{"x":174,"y":233.7,"facet":"Trend"},{"x":175,"y":234.1,"facet":"Trend"},{"x":176,"y":234.9,"facet":"Trend"},{"x":177,"y":235.7,"facet":"Trend"},{"x":178,"y":236.5,"facet":"Trend"},{"x":179,"y":237.4,"facet":"Trend"},{"x":180,"y":238.4,"facet":"Trend"},{"x":181,"y":239.3,"facet":"Trend"},{"x":182,"y":239.9,"facet":"Trend"},{"x":183,"y":240.6,"facet":"Trend"},{"x":184,"y":241.2,"facet":"Trend"},{"x":185,"y":241.0,"facet":"Trend"},{"x":186,"y":240.8,"facet":"Trend"},{"x":187,"y":240.6,"facet":"Trend"},{"x":188,"y":240.4,"facet":"Trend"},{"x":189,"y":240.3,"facet":"Trend"},{"x":190,"y":240.1,"facet":"Trend"},{"x":191,"y":241.2,"facet":"Trend"},{"x":192,"y":242.4,"facet":"Trend"},{"x":193,"y":243.6,"facet":"Trend"},{"x":194,"y":245.6,"facet":"Trend"},{"x":195,"y":247.6,"facet":"Trend"},{"x":196,"y":249.6,"facet":"Trend"},{"x":197,"y":252.8,"facet":"Trend"},{"x":198,"y":256.0,"facet":"Trend"},{"x":199,"y":259.2,"facet":"Trend"},{"x":200,"y":263.8,"facet":"Trend"},{"x":201,"y":268.5,"facet":"Trend"},{"x":202,"y":273.1,"facet":"Trend"},{"x":203,"y":278.5,"facet":"Trend"},{"x":204,"y":283.8,"facet":"Trend"},{"x":205,"y":289.2,"facet":"Trend"},{"x":206,"y":293.4,"facet":"Trend"},{"x":207,"y":297.5,"facet":"Trend"},{"x":208,"y":301.7,"facet":"Trend"},{"x":209,"y":304.9,"facet":"Trend"},{"x":210,"y":308.1,"facet":"Trend"},{"x":211,"y":311.4,"facet":"Trend"},{"x":212,"y":313.7,"facet":"Trend"},{"x":213,"y":316.1,"facet":"Trend"},{"x":214,"y":318.4,"facet":"Trend"},{"x":215,"y":319.1,"facet":"Trend"},{"x":216,"y":319.7,"facet":"Trend"},{"x":217,"y":320.4,"facet":"Trend"},{"x":218,"y":320.8,"facet":"Trend"},{"x":219,"y":321.2,"facet":"Trend"},{"x":220,"y":321.6,"facet":"Trend"},{"x":221,"y":322.9,"facet":"Trend"},{"x":222,"y":324.3,"facet":"Trend"},{"x":223,"y":325.7,"facet":"Trend"},{"x":224,"y":328.9,"facet":"Trend"},{"x":225,"y":332.1,"facet":"Trend"},{"x":226,"y":335.3,"facet":"Trend"},{"x":227,"y":339.0,"facet":"Trend"},{"x":228,"y":342.8,"facet":"Trend"},{"x":229,"y":346.5,"facet":"Trend"},{"x":230,"y":350.1,"facet":"Trend"},{"x":231,"y":353.7,"facet":"Trend"},{"x":232,"y":357.3,"facet":"Trend"},{"x":233,"y":360.6,"facet":"Trend"},{"x":234,"y":364.0,"facet":"Trend"},{"x":235,"y":367.3,"facet":"Trend"},{"x":236,"y":369.9,"facet":"Trend"},{"x":237,"y":372.5,"facet":"Trend"},{"x":238,"y":375.1,"facet":"Trend"},{"x":239,"y":378.3,"facet":"Trend"},{"x":240,"y":381.4,"facet":"Trend"},{"x":241,"y":384.5,"facet":"Trend"},{"x":242,"y":387.1,"facet":"Trend"},{"x":243,"y":389.7,"facet":"Trend"},{"x":244,"y":392.4,"facet":"Trend"},{"x":245,"y":394.9,"facet":"Trend"},{"x":246,"y":397.4,"facet":"Trend"},{"x":247,"y":400.0,"facet":"Trend"},{"x":248,"y":403.4,"facet":"Trend"},{"x":249,"y":406.7,"facet":"Trend"},{"x":250,"y":410.1,"facet":"Trend"},{"x":251,"y":413.8,"facet":"Trend"},{"x":252,"y":417.4,"facet":"Trend"},{"x":253,"y":421.1,"facet":"Trend"},{"x":254,"y":426.5,"facet":"Trend"},{"x":255,"y":431.9,"facet":"Trend"},{"x":256,"y":437.4,"facet":"Trend"},{"x":257,"y":442.3,"facet":"Trend"},{"x":258,"y":447.1,"facet":"Trend"},{"x":259,"y":452.0,"facet":"Trend"},{"x":260,"y":455.2,"facet":"Trend"},{"x":261,"y":458.4,"facet":"Trend"},{"x":262,"y":461.6,"facet":"Trend"},{"x":263,"y":463.9,"facet":"Trend"},{"x":264,"y":466.1,"facet":"Trend"},{"x":265,"y":468.3,"facet":"Trend"},{"x":266,"y":467.9,"facet":"Trend"},{"x":267,"y":467.6,"facet":"Trend"},{"x":268,"y":467.2,"facet":"Trend"},{"x":269,"y":465.0,"facet":"Trend"},{"x":270,"y":462.9,"facet":"Trend"},{"x":271,"y":460.8,"facet":"Trend"},{"x":272,"y":459.3,"facet":"Trend"},{"x":273,"y":457.9,"facet":"Trend"},{"x":274,"y":456.4,"facet":"Trend"},{"x":275,"y":456.0,"facet":"Trend"},{"x":276,"y":455.5,"facet":"Trend"},{"x":277,"y":455.0,"facet":"Trend"},{"x":278,"y":455.3,"facet":"Trend"},{"x":279,"y":455.7,"facet":"Trend"},{"x":280,"y":456.0,"facet":"Trend"},{"x":281,"y":458.6,"facet":"Trend"},{"x":282,"y":461.1,"facet":"Trend"},{"x":283,"y":463.6,"facet":"Trend"},{"x":284,"y":468.1,"facet":"Trend"},{"x":285,"y":472.6,"facet":"Trend"},{"x":286,"y":477.1,"facet":"Trend"},{"x":287,"y":481.9,"facet":"Trend"},{"x":288,"y":486.6,"facet":"Trend"},{"x":289,"y":491.4,"facet":"Trend"},{"x":290,"y":495.4,"facet":"Trend"},{"x":291,"y":499.5,"facet":"Trend"},{"x":292,"y":503.5,"facet":"Trend"},{"x":293,"y":507.3,"facet":"Trend"},{"x":294,"y":511.0,"facet":"Trend"},{"x":295,"y":514.8,"facet":"Trend"},{"x":296,"y":516.8,"facet":"Trend"},{"x":297,"y":518.8,"facet":"Trend"},{"x":298,"y":520.9,"facet":"Trend"},{"x":299,"y":521.6,"facet":"Trend"},{"x":300,"y":522.3,"facet":"Trend"},{"x":301,"y":523.0,"facet":"Trend"},{"x":302,"y":524.0,"facet":"Trend"},{"x":303,"y":524.9,"facet":"Trend"},{"x":304,"y":525.8,"facet":"Trend"},{"x":305,"y":526.9,"facet":"Trend"},{"x":306,"y":527.9,"facet":"Trend"},{"x":307,"y":529.0,"facet":"Trend"},{"x":308,"y":530.9,"facet":"Trend"},{"x":309,"y":532.8,"facet":"Trend"},{"x":310,"y":534.8,"facet":"Trend"},{"x":311,"y":538.0,"facet":"Trend"},{"x":312,"y":541.1,"facet":"Trend"},{"x":313,"y":544.3,"facet":"Trend"},{"x":314,"y":548.5,"facet":"Trend"},{"x":315,"y":552.7,"facet":"Trend"},{"x":316,"y":556.8,"facet":"Trend"},{"x":317,"y":563.0,"facet":"Trend"},{"x":318,"y":569.3,"facet":"Trend"},{"x":319,"y":575.5,"facet":"Trend"},{"x":320,"y":581.9,"facet":"Trend"},{"x":321,"y":588.3,"facet":"Trend"},{"x":322,"y":594.8,"facet":"Trend"},{"x":323,"y":601.0,"facet":"Trend"},{"x":324,"y":607.3,"facet":"Trend"},{"x":325,"y":613.5,"facet":"Trend"},{"x":326,"y":619.4,"facet":"Trend"},{"x":327,"y":625.2,"facet":"Trend"},{"x":328,"y":631.1,"facet":"Trend"},{"x":329,"y":636.8,"facet":"Trend"},{"x":330,"y":642.6,"facet":"Trend"},{"x":331,"y":648.3,"facet":"Trend"},{"x":332,"y":654.3,"facet":"Trend"},{"x":333,"y":660.3,"facet":"Trend"},{"x":334,"y":666.3,"facet":"Trend"},{"x":335,"y":670.9,"facet":"Trend"},{"x":336,"y":675.5,"facet":"Trend"},{"x":337,"y":680.1,"facet":"Trend"},{"x":338,"y":682.3,"facet":"Trend"},{"x":339,"y":684.6,"facet":"Trend"},{"x":340,"y":686.8,"facet":"Trend"},{"x":341,"y":687.5,"facet":"Trend"},{"x":342,"y":688.3,"facet":"Trend"},{"x":343,"y":689.1,"facet":"Trend"},{"x":344,"y":689.5,"facet":"Trend"},{"x":345,"y":689.9,"facet":"Trend"},{"x":346,"y":690.3,"facet":"Trend"},{"x":347,"y":690.1,"facet":"Trend"},{"x":348,"y":689.8,"facet":"Trend"},{"x":349,"y":689.6,"facet":"Trend"},{"x":350,"y":688.6,"facet":"Trend"},{"x":351,"y":687.6,"facet":"Trend"},{"x":352,"y":686.6,"facet":"Trend"},{"x":353,"y":684.7,"facet":"Trend"},{"x":354,"y":682.9,"facet":"Trend"},{"x":355,"y":681.0,"facet":"Trend"},{"x":356,"y":679.6,"facet":"Trend"},{"x":357,"y":678.1,"facet":"Trend"},{"x":358,"y":676.7,"facet":"Trend"},{"x":359,"y":675.9,"facet":"Trend"},{"x":360,"y":675.2,"facet":"Trend"},{"x":361,"y":674.5,"facet":"Trend"},{"x":362,"y":674.6,"facet":"Trend"},{"x":363,"y":674.8,"facet":"Trend"},{"x":364,"y":675.0,"facet":"Trend"},{"x":365,"y":675.4,"facet":"Trend"},{"x":366,"y":675.9,"facet":"Trend"},{"x":367,"y":676.3,"facet":"Trend"},{"x":368,"y":676.6,"facet":"Trend"},{"x":369,"y":676.9,"facet":"Trend"},{"x":370,"y":677.3,"facet":"Trend"},{"x":371,"y":677.7,"facet":"Trend"},{"x":372,"y":678.1,"facet":"Trend"},{"x":373,"y":678.5,"facet":"Trend"},{"x":374,"y":680.3,"facet":"Trend"},{"x":375,"y":682.1,"facet":"Trend"},{"x":376,"y":683.9,"facet":"Trend"},{"x":377,"y":687.0,"facet":"Trend"},{"x":378,"y":690.1,"facet":"Trend"},{"x":379,"y":693.2,"facet":"Trend"},{"x":380,"y":696.7,"facet":"Trend"},{"x":381,"y":700.1,"facet":"Trend"},{"x":382,"y":703.5,"facet":"Trend"},{"x":383,"y":708.4,"facet":"Trend"},{"x":384,"y":713.2,"facet":"Trend"},{"x":385,"y":718.0,"facet":"Trend"},{"x":386,"y":722.5,"facet":"Trend"},{"x":387,"y":727.0,"facet":"Trend"},{"x":388,"y":731.6,"facet":"Trend"},{"x":389,"y":735.6,"facet":"Trend"},{"x":390,"y":739.6,"facet":"Trend"},{"x":391,"y":743.6,"facet":"Trend"},{"x":392,"y":747.8,"facet":"Trend"},{"x":393,"y":752.1,"facet":"Trend"},{"x":394,"y":756.3,"facet":"Trend"},{"x":395,"y":760.9,"facet":"Trend"},{"x":396,"y":765.5,"facet":"Trend"},{"x":397,"y":770.2,"facet":"Trend"},{"x":398,"y":774.6,"facet":"Trend"},{"x":399,"y":779.1,"facet":"Trend"},{"x":400,"y":783.6,"facet":"Trend"},{"x":401,"y":787.8,"facet":"Trend"},{"x":402,"y":792.1,"facet":"Trend"},{"x":403,"y":796.3,"facet":"Trend"},{"x":404,"y":799.7,"facet":"Trend"},{"x":405,"y":803.1,"facet":"Trend"},{"x":406,"y":806.5,"facet":"Trend"},{"x":407,"y":810.3,"facet":"Trend"},{"x":408,"y":814.0,"facet":"Trend"},{"x":409,"y":817.7,"facet":"Trend"},{"x":410,"y":822.5,"facet":"Trend"},{"x":411,"y":827.2,"facet":"Trend"},{"x":412,"y":832.0,"facet":"Trend"},{"x":413,"y":836.0,"facet":"Trend"},{"x":414,"y":840.0,"facet":"Trend"},{"x":415,"y":844.0,"facet":"Trend"},{"x":416,"y":847.9,"facet":"Trend"},{"x":417,"y":851.8,"facet":"Trend"},{"x":418,"y":855.7,"facet":"Trend"},{"x":419,"y":858.5,"facet":"Trend"},{"x":420,"y":861.2,"facet":"Trend"},{"x":421,"y":863.9,"facet":"Trend"},{"x":422,"y":866.7,"facet":"Trend"},{"x":423,"y":869.5,"facet":"Trend"},{"x":424,"y":872.3,"facet":"Trend"},{"x":425,"y":875.7,"facet":"Trend"},{"x":426,"y":879.2,"facet":"Trend"},{"x":427,"y":882.6,"facet":"Trend"},{"x":428,"y":887.0,"facet":"Trend"},{"x":429,"y":891.3,"facet":"Trend"},{"x":430,"y":895.7,"facet":"Trend"},{"x":431,"y":901.1,"facet":"Trend"},{"x":432,"y":906.5,"facet":"Trend"},{"x":433,"y":912.0,"facet":"Trend"},{"x":434,"y":917.6,"facet":"Trend"},{"x":435,"y":923.2,"facet":"Trend"},{"x":436,"y":928.9,"facet":"Trend"},{"x":437,"y":934.7,"facet":"Trend"},{"x":438,"y":940.5,"facet":"Trend"},{"x":439,"y":946.3,"facet":"Trend"},{"x":440,"y":952.3,"facet":"Trend"},{"x":441,"y":958.3,"facet":"Trend"},{"x":1,"y":-3.22,"facet":"Season"},{"x":2,"y":-1.41,"facet":"Season"},{"x":3,"y":-8.36,"facet":"Season"},{"x":4,"y":-4.09,"facet":"Season"},{"x":5,"y":-1.83,"facet":"Season"},{"x":6,"y":-2.48,"facet":"Season"},{"x":7,"y":3.39,"facet":"Season"},{"x":8,"y":4.57,"facet":"Season"},{"x":9,"y":20.61,"facet":"Season"},{"x":10,"y":-0.59,"facet":"Season"},{"x":11,"y":-6.20,"facet":"Season"},{"x":12,"y":-0.41,"facet":"Season"},{"x":13,"y":-3.21,"facet":"Season"},{"x":14,"y":-1.50,"facet":"Season"},{"x":15,"y":-8.40,"facet":"Season"},{"x":16,"y":-4.02,"facet":"Season"},{"x":17,"y":-1.89,"facet":"Season"},{"x":18,"y":-2.44,"facet":"Season"},{"x":19,"y":3.48,"facet":"Season"},{"x":20,"y":4.57,"facet":"Season"},{"x":21,"y":20.91,"facet":"Season"},{"x":22,"y":-0.69,"facet":"Season"},{"x":23,"y":-6.42,"facet":"Season"},{"x":24,"y":-0.36,"facet":"Season"},{"x":25,"y":-3.21,"facet":"Season"},{"x":26,"y":-1.61,"facet":"Season"},{"x":27,"y":-8.43,"facet":"Season"},{"x":28,"y":-3.96,"facet":"Season"},{"x":29,"y":-1.94,"facet":"Season"},{"x":30,"y":-2.40,"facet":"Season"},{"x":31,"y":3.56,"facet":"Season"},{"x":32,"y":4.56,"facet":"Season"},{"x":33,"y":21.20,"facet":"Season"},{"x":34,"y":-0.80,"facet":"Season"},{"x":35,"y":-6.66,"facet":"Season"},{"x":36,"y":-0.32,"facet":"Season"},{"x":37,"y":-3.22,"facet":"Season"},{"x":38,"y":-1.74,"facet":"Season"},{"x":39,"y":-8.55,"facet":"Season"},{"x":40,"y":-3.79,"facet":"Season"},{"x":41,"y":-1.96,"facet":"Season"},{"x":42,"y":-2.32,"facet":"Season"},{"x":43,"y":3.75,"facet":"Season"},{"x":44,"y":4.47,"facet":"Season"},{"x":45,"y":21.83,"facet":"Season"},{"x":46,"y":-1.02,"facet":"Season"},{"x":47,"y":-7.24,"facet":"Season"},{"x":48,"y":-0.30,"facet":"Season"},{"x":49,"y":-3.22,"facet":"Season"},{"x":50,"y":-1.85,"facet":"Season"},{"x":51,"y":-8.65,"facet":"Season"},{"x":52,"y":-3.59,"facet":"Season"},{"x":53,"y":-1.95,"facet":"Season"},{"x":54,"y":-2.20,"facet":"Season"},{"x":55,"y":3.97,"facet":"Season"},{"x":56,"y":4.43,"facet":"Season"},{"x":57,"y":22.50,"facet":"Season"},{"x":58,"y":-1.21,"facet":"Season"},{"x":59,"y":-7.78,"facet":"Season"},{"x":60,"y":-0.27,"facet":"Season"},{"x":61,"y":-3.51,"facet":"Season"},{"x":62,"y":-2.55,"facet":"Season"},{"x":63,"y":-8.68,"facet":"Season"},{"x":64,"y":-3.26,"facet":"Season"},{"x":65,"y":-2.58,"facet":"Season"},{"x":66,"y":-2.10,"facet":"Season"},{"x":67,"y":4.03,"facet":"Season"},{"x":68,"y":4.26,"facet":"Season"},{"x":69,"y":25.03,"facet":"Season"},{"x":70,"y":-0.95,"facet":"Season"},{"x":71,"y":-8.90,"facet":"Season"},{"x":72,"y":0.08,"facet":"Season"},{"x":73,"y":-3.92,"facet":"Season"},{"x":74,"y":-3.37,"facet":"Season"},{"x":75,"y":-8.81,"facet":"Season"},{"x":76,"y":-3.02,"facet":"Season"},{"x":77,"y":-3.27,"facet":"Season"},{"x":78,"y":-2.04,"facet":"Season"},{"x":79,"y":4.09,"facet":"Season"},{"x":80,"y":4.10,"facet":"Season"},{"x":81,"y":27.61,"facet":"Season"},{"x":82,"y":-0.62,"facet":"Season"},{"x":83,"y":-9.94,"facet":"Season"},{"x":84,"y":0.54,"facet":"Season"},{"x":85,"y":-4.14,"facet":"Season"},{"x":86,"y":-3.61,"facet":"Season"},{"x":87,"y":-9.08,"facet":"Season"},{"x":88,"y":-3.42,"facet":"Season"},{"x":89,"y":-4.79,"facet":"Season"},{"x":90,"y":-2.18,"facet":"Season"},{"x":91,"y":2.82,"facet":"Season"},{"x":92,"y":3.98,"facet":"Season"},{"x":93,"y":30.53,"facet":"Season"},{"x":94,"y":0.69,"facet":"Season"},{"x":95,"y":-10.24,"facet":"Season"},{"x":96,"y":1.04,"facet":"Season"},{"x":97,"y":-4.37,"facet":"Season"},{"x":98,"y":-3.87,"facet":"Season"},{"x":99,"y":-9.36,"facet":"Season"},{"x":100,"y":-3.84,"facet":"Season"},{"x":101,"y":-6.34,"facet":"Season"},{"x":102,"y":-2.35,"facet":"Season"},{"x":103,"y":1.54,"facet":"Season"},{"x":104,"y":3.86,"facet":"Season"},{"x":105,"y":33.46,"facet":"Season"},{"x":106,"y":2.01,"facet":"Season"},{"x":107,"y":-10.51,"facet":"Season"},{"x":108,"y":1.58,"facet":"Season"},{"x":109,"y":-4.86,"facet":"Season"},{"x":110,"y":-4.18,"facet":"Season"},{"x":111,"y":-10.37,"facet":"Season"},{"x":112,"y":-3.96,"facet":"Season"},{"x":113,"y":-6.75,"facet":"Season"},{"x":114,"y":-2.17,"facet":"Season"},{"x":115,"y":1.00,"facet":"Season"},{"x":116,"y":4.01,"facet":"Season"},{"x":117,"y":34.05,"facet":"Season"},{"x":118,"y":3.22,"facet":"Season"},{"x":119,"y":-11.08,"facet":"Season"},{"x":120,"y":2.18,"facet":"Season"},{"x":121,"y":-5.24,"facet":"Season"},{"x":122,"y":-4.41,"facet":"Season"},{"x":123,"y":-11.33,"facet":"Season"},{"x":124,"y":-4.08,"facet":"Season"},{"x":125,"y":-7.19,"facet":"Season"},{"x":126,"y":-2.06,"facet":"Season"},{"x":127,"y":0.35,"facet":"Season"},{"x":128,"y":4.01,"facet":"Season"},{"x":129,"y":34.45,"facet":"Season"},{"x":130,"y":4.23,"facet":"Season"},{"x":131,"y":-11.86,"facet":"Season"},{"x":132,"y":2.57,"facet":"Season"},{"x":133,"y":-3.71,"facet":"Season"},{"x":134,"y":-3.60,"facet":"Season"},{"x":135,"y":-11.42,"facet":"Season"},{"x":136,"y":-4.31,"facet":"Season"},{"x":137,"y":-6.88,"facet":"Season"},{"x":138,"y":-2.61,"facet":"Season"},{"x":139,"y":-0.13,"facet":"Season"},{"x":140,"y":3.76,"facet":"Season"},{"x":141,"y":32.65,"facet":"Season"},{"x":142,"y":4.23,"facet":"Season"},{"x":143,"y":-13.28,"facet":"Season"},{"x":144,"y":3.66,"facet":"Season"},{"x":145,"y":-1.98,"facet":"Season"},{"x":146,"y":-2.61,"facet":"Season"},{"x":147,"y":-11.35,"facet":"Season"},{"x":148,"y":-4.40,"facet":"Season"},{"x":149,"y":-6.44,"facet":"Season"},{"x":150,"y":-3.06,"facet":"Season"},{"x":151,"y":-0.55,"facet":"Season"},{"x":152,"y":3.54,"facet":"Season"},{"x":153,"y":30.85,"facet":"Season"},{"x":154,"y":4.21,"facet":"Season"},{"x":155,"y":-14.73,"facet":"Season"},{"x":156,"y":4.71,"facet":"Season"},{"x":157,"y":-1.27,"facet":"Season"},{"x":158,"y":-1.78,"facet":"Season"},{"x":159,"y":-10.76,"facet":"Season"},{"x":160,"y":-3.20,"facet":"Season"},{"x":161,"y":-5.27,"facet":"Season"},{"x":162,"y":-3.99,"facet":"Season"},{"x":163,"y":0.33,"facet":"Season"},{"x":164,"y":2.78,"facet":"Season"},{"x":165,"y":28.18,"facet":"Season"},{"x":166,"y":3.86,"facet":"Season"},{"x":167,"y":-17.11,"facet":"Season"},{"x":168,"y":5.98,"facet":"Season"},{"x":169,"y":-0.49,"facet":"Season"},{"x":170,"y":-0.90,"facet":"Season"},{"x":171,"y":-10.12,"facet":"Season"},{"x":172,"y":-1.93,"facet":"Season"},{"x":173,"y":-4.03,"facet":"Season"},{"x":174,"y":-4.85,"facet":"Season"},{"x":175,"y":1.28,"facet":"Season"},{"x":176,"y":2.09,"facet":"Season"},{"x":177,"y":25.57,"facet":"Season"},{"x":178,"y":3.58,"facet":"Season"},{"x":179,"y":-19.43,"facet":"Season"},{"x":180,"y":7.31,"facet":"Season"},{"x":181,"y":-0.02,"facet":"Season"},{"x":182,"y":-0.09,"facet":"Season"},{"x":183,"y":-9.66,"facet":"Season"},{"x":184,"y":0.51,"facet":"Season"},{"x":185,"y":-3.45,"facet":"Season"},{"x":186,"y":-7.02,"facet":"Season"},{"x":187,"y":1.29,"facet":"Season"},{"x":188,"y":0.44,"facet":"Season"},{"x":189,"y":25.24,"facet":"Season"},{"x":190,"y":4.08,"facet":"Season"},{"x":191,"y":-21.39,"facet":"Season"},{"x":192,"y":8.93,"facet":"Season"},{"x":193,"y":0.38,"facet":"Season"},{"x":194,"y":0.67,"facet":"Season"},{"x":195,"y":-9.22,"facet":"Season"},{"x":196,"y":2.96,"facet":"Season"},{"x":197,"y":-2.82,"facet":"Season"},{"x":198,"y":-9.09,"facet":"Season"},{"x":199,"y":1.43,"facet":"Season"},{"x":200,"y":-1.05,"facet":"Season"},{"x":201,"y":25.08,"facet":"Season"},{"x":202,"y":4.77,"facet":"Season"},{"x":203,"y":-23.17,"facet":"Season"},{"x":204,"y":10.72,"facet":"Season"},{"x":205,"y":-2.07,"facet":"Season"},{"x":206,"y":0.08,"facet":"Season"},{"x":207,"y":-11.89,"facet":"Season"},{"x":208,"y":6.91,"facet":"Season"},{"x":209,"y":-1.74,"facet":"Season"},{"x":210,"y":-10.05,"facet":"Season"},{"x":211,"y":2.45,"facet":"Season"},{"x":212,"y":-1.68,"facet":"Season"},{"x":213,"y":27.49,"facet":"Season"},{"x":214,"y":5.62,"facet":"Season"},{"x":215,"y":-24.93,"facet":"Season"},{"x":216,"y":12.03,"facet":"Season"},{"x":217,"y":-4.85,"facet":"Season"},{"x":218,"y":-0.80,"facet":"Season"},{"x":219,"y":-14.83,"facet":"Season"},{"x":220,"y":10.65,"facet":"Season"},{"x":221,"y":-0.81,"facet":"Season"},{"x":222,"y":-11.13,"facet":"Season"},{"x":223,"y":3.41,"facet":"Season"},{"x":224,"y":-2.34,"facet":"Season"},{"x":225,"y":29.91,"facet":"Season"},{"x":226,"y":6.49,"facet":"Season"},{"x":227,"y":-26.66,"facet":"Season"},{"x":228,"y":13.37,"facet":"Season"},{"x":229,"y":-5.87,"facet":"Season"},{"x":230,"y":-1.56,"facet":"Season"},{"x":231,"y":-18.48,"facet":"Season"},{"x":232,"y":10.75,"facet":"Season"},{"x":233,"y":-0.73,"facet":"Season"},{"x":234,"y":-12.12,"facet":"Season"},{"x":235,"y":5.20,"facet":"Season"},{"x":236,"y":-0.82,"facet":"Season"},{"x":237,"y":34.07,"facet":"Season"},{"x":238,"y":7.07,"facet":"Season"},{"x":239,"y":-29.92,"facet":"Season"},{"x":240,"y":15.27,"facet":"Season"},{"x":241,"y":-7.00,"facet":"Season"},{"x":242,"y":-2.42,"facet":"Season"},{"x":243,"y":-22.25,"facet":"Season"},{"x":244,"y":10.74,"facet":"Season"},{"x":245,"y":-0.76,"facet":"Season"},{"x":246,"y":-13.24,"facet":"Season"},{"x":247,"y":6.88,"facet":"Season"},{"x":248,"y":0.58,"facet":"Season"},{"x":249,"y":38.11,"facet":"Season"},{"x":250,"y":7.52,"facet":"Season"},{"x":251,"y":-33.29,"facet":"Season"},{"x":252,"y":17.05,"facet":"Season"},{"x":253,"y":-5.34,"facet":"Season"},{"x":254,"y":-3.43,"facet":"Season"},{"x":255,"y":-25.72,"facet":"Season"},{"x":256,"y":8.15,"facet":"Season"},{"x":257,"y":-0.10,"facet":"Season"},{"x":258,"y":-14.81,"facet":"Season"},{"x":259,"y":8.64,"facet":"Season"},{"x":260,"y":2.87,"facet":"Season"},{"x":261,"y":44.17,"facet":"Season"},{"x":262,"y":6.13,"facet":"Season"},{"x":263,"y":-37.02,"facet":"Season"},{"x":264,"y":17.56,"facet":"Season"},{"x":265,"y":-3.58,"facet":"Season"},{"x":266,"y":-4.36,"facet":"Season"},{"x":267,"y":-29.11,"facet":"Season"},{"x":268,"y":5.61,"facet":"Season"},{"x":269,"y":0.60,"facet":"Season"},{"x":270,"y":-16.36,"facet":"Season"},{"x":271,"y":10.41,"facet":"Season"},{"x":272,"y":5.19,"facet":"Season"},{"x":273,"y":50.25,"facet":"Season"},{"x":274,"y":4.77,"facet":"Season"},{"x":275,"y":-40.71,"facet":"Season"},{"x":276,"y":18.15,"facet":"Season"},{"x":277,"y":-1.04,"facet":"Season"},{"x":278,"y":-3.32,"facet":"Season"},{"x":279,"y":-30.38,"facet":"Season"},{"x":280,"y":1.33,"facet":"Season"},{"x":281,"y":0.44,"facet":"Season"},{"x":282,"y":-20.60,"facet":"Season"},{"x":283,"y":11.28,"facet":"Season"},{"x":284,"y":6.43,"facet":"Season"},{"x":285,"y":58.02,"facet":"Season"},{"x":286,"y":2.99,"facet":"Season"},{"x":287,"y":-44.02,"facet":"Season"},{"x":288,"y":18.96,"facet":"Season"},{"x":289,"y":1.68,"facet":"Season"},{"x":290,"y":-2.15,"facet":"Season"},{"x":291,"y":-31.58,"facet":"Season"},{"x":292,"y":-2.93,"facet":"Season"},{"x":293,"y":0.22,"facet":"Season"},{"x":294,"y":-24.96,"facet":"Season"},{"x":295,"y":11.95,"facet":"Season"},{"x":296,"y":7.41,"facet":"Season"},{"x":297,"y":65.47,"facet":"Season"},{"x":298,"y":0.87,"facet":"Season"},{"x":299,"y":-47.72,"facet":"Season"},{"x":300,"y":19.39,"facet":"Season"},{"x":301,"y":4.46,"facet":"Season"},{"x":302,"y":0.14,"facet":"Season"},{"x":303,"y":-30.18,"facet":"Season"},{"x":304,"y":-5.23,"facet":"Season"},{"x":305,"y":1.02,"facet":"Season"},{"x":306,"y":-26.66,"facet":"Season"},{"x":307,"y":11.15,"facet":"Season"},{"x":308,"y":6.83,"facet":"Season"},{"x":309,"y":69.61,"facet":"Season"},{"x":310,"y":-0.78,"facet":"Season"},{"x":311,"y":-53.03,"facet":"Season"},{"x":312,"y":17.66,"facet":"Season"},{"x":313,"y":7.64,"facet":"Season"},{"x":314,"y":2.82,"facet":"Season"},{"x":315,"y":-28.38,"facet":"Season"},{"x":316,"y":-7.15,"facet":"Season"},{"x":317,"y":2.17,"facet":"Season"},{"x":318,"y":-28.06,"facet":"Season"},{"x":319,"y":10.61,"facet":"Season"},{"x":320,"y":6.46,"facet":"Season"},{"x":321,"y":73.90,"facet":"Season"},{"x":322,"y":-2.33,"facet":"Season"},{"x":323,"y":-58.28,"facet":"Season"},{"x":324,"y":15.96,"facet":"Season"},{"x":325,"y":8.92,"facet":"Season"},{"x":326,"y":3.56,"facet":"Season"},{"x":327,"y":-26.40,"facet":"Season"},{"x":328,"y":-6.11,"facet":"Season"},{"x":329,"y":3.37,"facet":"Season"},{"x":330,"y":-26.29,"facet":"Season"},{"x":331,"y":9.81,"facet":"Season"},{"x":332,"y":7.10,"facet":"Season"},{"x":333,"y":77.39,"facet":"Season"},{"x":334,"y":-6.05,"facet":"Season"},{"x":335,"y":-64.92,"facet":"Season"},{"x":336,"y":13.81,"facet":"Season"},{"x":337,"y":10.35,"facet":"Season"},{"x":338,"y":4.48,"facet":"Season"},{"x":339,"y":-24.24,"facet":"Season"},{"x":340,"y":-4.88,"facet":"Season"},{"x":341,"y":4.77,"facet":"Season"},{"x":342,"y":-24.35,"facet":"Season"},{"x":343,"y":9.19,"facet":"Season"},{"x":344,"y":7.88,"facet":"Season"},{"x":345,"y":80.98,"facet":"Season"},{"x":346,"y":-9.72,"facet":"Season"},{"x":347,"y":-71.57,"facet":"Season"},{"x":348,"y":11.59,"facet":"Season"},{"x":349,"y":10.28,"facet":"Season"},{"x":350,"y":3.88,"facet":"Season"},{"x":351,"y":-23.96,"facet":"Season"},{"x":352,"y":-2.39,"facet":"Season"},{"x":353,"y":6.14,"facet":"Season"},{"x":354,"y":-20.76,"facet":"Season"},{"x":355,"y":8.15,"facet":"Season"},{"x":356,"y":11.31,"facet":"Season"},{"x":357,"y":83.14,"facet":"Season"},{"x":358,"y":-13.36,"facet":"Season"},{"x":359,"y":-73.37,"facet":"Season"},{"x":360,"y":8.74,"facet":"Season"},{"x":361,"y":9.65,"facet":"Season"},{"x":362,"y":2.81,"facet":"Season"},{"x":363,"y":-24.04,"facet":"Season"},{"x":364,"y":-0.14,"facet":"Season"},{"x":365,"y":7.41,"facet":"Season"},{"x":366,"y":-17.14,"facet":"Season"},{"x":367,"y":7.30,"facet":"Season"},{"x":368,"y":15.05,"facet":"Season"},{"x":369,"y":85.73,"facet":"Season"},{"x":370,"y":-16.49,"facet":"Season"},{"x":371,"y":-74.57,"facet":"Season"},{"x":372,"y":6.52,"facet":"Season"},{"x":373,"y":6.30,"facet":"Season"},{"x":374,"y":0.22,"facet":"Season"},{"x":375,"y":-26.54,"facet":"Season"},{"x":376,"y":-1.11,"facet":"Season"},{"x":377,"y":7.55,"facet":"Season"},{"x":378,"y":-13.70,"facet":"Season"},{"x":379,"y":8.39,"facet":"Season"},{"x":380,"y":19.86,"facet":"Season"},{"x":381,"y":87.92,"facet":"Season"},{"x":382,"y":-14.53,"facet":"Season"},{"x":383,"y":-75.56,"facet":"Season"},{"x":384,"y":5.90,"facet":"Season"},{"x":385,"y":2.57,"facet":"Season"},{"x":386,"y":-2.76,"facet":"Season"},{"x":387,"y":-29.47,"facet":"Season"},{"x":388,"y":-2.49,"facet":"Season"},{"x":389,"y":7.29,"facet":"Season"},{"x":390,"y":-10.62,"facet":"Season"},{"x":391,"y":9.15,"facet":"Season"},{"x":392,"y":24.38,"facet":"Season"},{"x":393,"y":89.88,"facet":"Season"},{"x":394,"y":-12.75,"facet":"Season"},{"x":395,"y":-76.68,"facet":"Season"},{"x":396,"y":5.20,"facet":"Season"},{"x":397,"y":0.72,"facet":"Season"},{"x":398,"y":-3.93,"facet":"Season"},{"x":399,"y":-31.49,"facet":"Season"},{"x":400,"y":-3.67,"facet":"Season"},{"x":401,"y":7.17,"facet":"Season"},{"x":402,"y":-9.77,"facet":"Season"},{"x":403,"y":10.09,"facet":"Season"},{"x":404,"y":25.84,"facet":"Season"},{"x":405,"y":91.29,"facet":"Season"},{"x":406,"y":-12.22,"facet":"Season"},{"x":407,"y":-76.85,"facet":"Season"},{"x":408,"y":5.17,"facet":"Season"},{"x":409,"y":-0.84,"facet":"Season"},{"x":410,"y":-4.86,"facet":"Season"},{"x":411,"y":-33.33,"facet":"Season"},{"x":412,"y":-4.72,"facet":"Season"},{"x":413,"y":7.13,"facet":"Season"},{"x":414,"y":-8.89,"facet":"Season"},{"x":415,"y":11.00,"facet":"Season"},{"x":416,"y":27.24,"facet":"Season"},{"x":417,"y":92.60,"facet":"Season"},{"x":418,"y":-11.80,"facet":"Season"},{"x":419,"y":-77.16,"facet":"Season"},{"x":420,"y":5.00,"facet":"Season"},{"x":421,"y":-1.52,"facet":"Season"},{"x":422,"y":-5.47,"facet":"Season"},{"x":423,"y":-34.20,"facet":"Season"},{"x":424,"y":-5.10,"facet":"Season"},{"x":425,"y":7.09,"facet":"Season"},{"x":426,"y":-8.51,"facet":"Season"},{"x":427,"y":11.45,"facet":"Season"},{"x":428,"y":27.87,"facet":"Season"},{"x":429,"y":93.25,"facet":"Season"},{"x":430,"y":-11.48,"facet":"Season"},{"x":431,"y":-77.28,"facet":"Season"},{"x":432,"y":4.95,"facet":"Season"},{"x":433,"y":-2.14,"facet":"Season"},{"x":434,"y":-6.03,"facet":"Season"},{"x":435,"y":-35.03,"facet":"Season"},{"x":436,"y":-5.44,"facet":"Season"},{"x":437,"y":7.09,"facet":"Season"},{"x":438,"y":-8.12,"facet":"Season"},{"x":439,"y":11.91,"facet":"Season"},{"x":440,"y":28.49,"facet":"Season"},{"x":441,"y":93.90,"facet":"Season"},{"x":1,"y":1.2,"facet":"Remainder"},{"x":2,"y":-1.0,"facet":"Remainder"},{"x":3,"y":3.3,"facet":"Remainder"},{"x":4,"y":-2.0,"facet":"Remainder"},{"x":5,"y":-4.9,"facet":"Remainder"},{"x":6,"y":-1.7,"facet":"Remainder"},{"x":7,"y":-0.8,"facet":"Remainder"},{"x":8,"y":3.7,"facet":"Remainder"},{"x":9,"y":-1.0,"facet":"Remainder"},{"x":10,"y":5.2,"facet":"Remainder"},{"x":11,"y":4.1,"facet":"Remainder"},{"x":12,"y":1.8,"facet":"Remainder"},{"x":13,"y":-2.5,"facet":"Remainder"},{"x":14,"y":-2.7,"facet":"Remainder"},{"x":15,"y":-1.5,"facet":"Remainder"},{"x":16,"y":-1.7,"facet":"Remainder"},{"x":17,"y":0.6,"facet":"Remainder"},{"x":18,"y":1.0,"facet":"Remainder"},{"x":19,"y":-3.4,"facet":"Remainder"},{"x":20,"y":-2.1,"facet":"Remainder"},{"x":21,"y":-3.2,"facet":"Remainder"},{"x":22,"y":-1.3,"facet":"Remainder"},{"x":23,"y":5.7,"facet":"Remainder"},{"x":24,"y":2.6,"facet":"Remainder"},{"x":25,"y":0.2,"facet":"Remainder"},{"x":26,"y":6.5,"facet":"Remainder"},{"x":27,"y":4.2,"facet":"Remainder"},{"x":28,"y":0.0,"facet":"Remainder"},{"x":29,"y":-0.3,"facet":"Remainder"},{"x":30,"y":-4.0,"facet":"Remainder"},{"x":31,"y":-4.8,"facet":"Remainder"},{"x":32,"y":-1.2,"facet":"Remainder"},{"x":33,"y":-6.3,"facet":"Remainder"},{"x":34,"y":-0.8,"facet":"Remainder"},{"x":35,"y":1.8,"facet":"Remainder"},{"x":36,"y":-1.2,"facet":"Remainder"},{"x":37,"y":1.2,"facet":"Remainder"},{"x":38,"y":2.0,"facet":"Remainder"},{"x":39,"y":-3.3,"facet":"Remainder"},{"x":40,"y":-1.8,"facet":"Remainder"},{"x":41,"y":4.0,"facet":"Remainder"},{"x":42,"y":-0.6,"facet":"Remainder"},{"x":43,"y":0.8,"facet":"Remainder"},{"x":44,"y":-0.9,"facet":"Remainder"},{"x":45,"y":-5.3,"facet":"Remainder"},{"x":46,"y":3.1,"facet":"Remainder"},{"x":47,"y":-2.3,"facet":"Remainder"},{"x":48,"y":-6.0,"facet":"Remainder"},{"x":49,"y":-4.8,"facet":"Remainder"},{"x":50,"y":-0.7,"facet":"Remainder"},{"x":51,"y":-6.1,"facet":"Remainder"},{"x":52,"y":1.8,"facet":"Remainder"},{"x":53,"y":6.0,"facet":"Remainder"},{"x":54,"y":5.1,"facet":"Remainder"},{"x":55,"y":6.5,"facet":"Remainder"},{"x":56,"y":-0.6,"facet":"Remainder"},{"x":57,"y":0.3,"facet":"Remainder"},{"x":58,"y":1.3,"facet":"Remainder"},{"x":59,"y":-1.7,"facet":"Remainder"},{"x":60,"y":-5.4,"facet":"Remainder"},{"x":61,"y":2.6,"facet":"Remainder"},{"x":62,"y":1.8,"facet":"Remainder"},{"x":63,"y":0.3,"facet":"Remainder"},{"x":64,"y":4.6,"facet":"Remainder"},{"x":65,"y":0.0,"facet":"Remainder"},{"x":66,"y":-1.9,"facet":"Remainder"},{"x":67,"y":1.6,"facet":"Remainder"},{"x":68,"y":-1.8,"facet":"Remainder"},{"x":69,"y":7.5,"facet":"Remainder"},{"x":70,"y":-10.9,"facet":"Remainder"},{"x":71,"y":-0.6,"facet":"Remainder"},{"x":72,"y":2.1,"facet":"Remainder"},{"x":73,"y":4.1,"facet":"Remainder"},{"x":74,"y":-4.7,"facet":"Remainder"},{"x":75,"y":3.5,"facet":"Remainder"},{"x":76,"y":-5.2,"facet":"Remainder"},{"x":77,"y":-0.8,"facet":"Remainder"},{"x":78,"y":1.7,"facet":"Remainder"},{"x":79,"y":-3.7,"facet":"Remainder"},{"x":80,"y":2.9,"facet":"Remainder"},{"x":81,"y":-12.9,"facet":"Remainder"},{"x":82,"y":-5.7,"facet":"Remainder"},{"x":83,"y":2.0,"facet":"Remainder"},{"x":84,"y":2.0,"facet":"Remainder"},{"x":85,"y":3.2,"facet":"Remainder"},{"x":86,"y":3.8,"facet":"Remainder"},{"x":87,"y":1.4,"facet":"Remainder"},{"x":88,"y":-0.9,"facet":"Remainder"},{"x":89,"y":-6.9,"facet":"Remainder"},{"x":90,"y":-0.1,"facet":"Remainder"},{"x":91,"y":8.0,"facet":"Remainder"},{"x":92,"y":6.9,"facet":"Remainder"},{"x":93,"y":12.9,"facet":"Remainder"},{"x":94,"y":3.7,"facet":"Remainder"},{"x":95,"y":0.0,"facet":"Remainder"},{"x":96,"y":10.0,"facet":"Remainder"},{"x":97,"y":-5.0,"facet":"Remainder"},{"x":98,"y":-4.6,"facet":"Remainder"},{"x":99,"y":0.8,"facet":"Remainder"},{"x":100,"y":8.0,"facet":"Remainder"},{"x":101,"y":5.2,"facet":"Remainder"},{"x":102,"y":-1.1,"facet":"Remainder"},{"x":103,"y":-1.2,"facet":"Remainder"},{"x":104,"y":-4.9,"facet":"Remainder"},{"x":105,"y":-7.7,"facet":"Remainder"},{"x":106,"y":3.3,"facet":"Remainder"},{"x":107,"y":-4.9,"facet":"Remainder"},{"x":108,"y":-9.6,"facet":"Remainder"},{"x":109,"y":-7.5,"facet":"Remainder"},{"x":110,"y":-0.6,"facet":"Remainder"},{"x":111,"y":6.2,"facet":"Remainder"},{"x":112,"y":-0.8,"facet":"Remainder"},{"x":113,"y":2.9,"facet":"Remainder"},{"x":114,"y":-0.9,"facet":"Remainder"},{"x":115,"y":-4.7,"facet":"Remainder"},{"x":116,"y":-3.3,"facet":"Remainder"},{"x":117,"y":4.4,"facet":"Remainder"},{"x":118,"y":-0.7,"facet":"Remainder"},{"x":119,"y":5.5,"facet":"Remainder"},{"x":120,"y":5.4,"facet":"Remainder"},{"x":121,"y":10.2,"facet":"Remainder"},{"x":122,"y":7.2,"facet":"Remainder"},{"x":123,"y":-10.9,"facet":"Remainder"},{"x":124,"y":-10.0,"facet":"Remainder"},{"x":125,"y":-11.5,"facet":"Remainder"},{"x":126,"y":0.5,"facet":"Remainder"},{"x":127,"y":-0.2,"facet":"Remainder"},{"x":128,"y":-1.3,"facet":"Remainder"},{"x":129,"y":6.3,"facet":"Remainder"},{"x":130,"y":9.5,"facet":"Remainder"},{"x":131,"y":-0.5,"facet":"Remainder"},{"x":132,"y":-6.7,"facet":"Remainder"},{"x":133,"y":-2.5,"facet":"Remainder"},{"x":134,"y":-0.5,"facet":"Remainder"},{"x":135,"y":0.7,"facet":"Remainder"},{"x":136,"y":7.8,"facet":"Remainder"},{"x":137,"y":2.8,"facet":"Remainder"},{"x":138,"y":1.4,"facet":"Remainder"},{"x":139,"y":-3.5,"facet":"Remainder"},{"x":140,"y":2.6,"facet":"Remainder"},{"x":141,"y":7.6,"facet":"Remainder"},{"x":142,"y":-5.5,"facet":"Remainder"},{"x":143,"y":2.5,"facet":"Remainder"},{"x":144,"y":-5.8,"facet":"Remainder"},{"x":145,"y":-13.6,"facet":"Remainder"},{"x":146,"y":-16.5,"facet":"Remainder"},{"x":147,"y":-9.3,"facet":"Remainder"},{"x":148,"y":-3.3,"facet":"Remainder"},{"x":149,"y":-4.7,"facet":"Remainder"},{"x":150,"y":1.6,"facet":"Remainder"},{"x":151,"y":15.7,"facet":"Remainder"},{"x":152,"y":3.4,"facet":"Remainder"},{"x":153,"y":-0.6,"facet":"Remainder"},{"x":154,"y":-0.9,"facet":"Remainder"},{"x":155,"y":0.7,"facet":"Remainder"},{"x":156,"y":9.8,"facet":"Remainder"},{"x":157,"y":4.5,"facet":"Remainder"},{"x":158,"y":-3.0,"facet":"Remainder"},{"x":159,"y":3.6,"facet":"Remainder"},{"x":160,"y":-1.5,"facet":"Remainder"},{"x":161,"y":1.7,"facet":"Remainder"},{"x":162,"y":5.5,"facet":"Remainder"},{"x":163,"y":-2.9,"facet":"Remainder"},{"x":164,"y":4.5,"facet":"Remainder"},{"x":165,"y":-2.3,"facet":"Remainder"},{"x":166,"y":1.3,"facet":"Remainder"},{"x":167,"y":2.3,"facet":"Remainder"},{"x":168,"y":-1.2,"facet":"Remainder"},{"x":169,"y":3.4,"facet":"Remainder"},{"x":170,"y":3.3,"facet":"Remainder"},{"x":171,"y":2.9,"facet":"Remainder"},{"x":172,"y":-1.0,"facet":"Remainder"},{"x":173,"y":-0.4,"facet":"Remainder"},{"x":174,"y":-9.6,"facet":"Remainder"},{"x":175,"y":-9.9,"facet":"Remainder"},{"x":176,"y":-3.7,"facet":"Remainder"},{"x":177,"y":-6.7,"facet":"Remainder"},{"x":178,"y":2.0,"facet":"Remainder"},{"x":179,"y":-1.9,"facet":"Remainder"},{"x":180,"y":4.2,"facet":"Remainder"},{"x":181,"y":11.5,"facet":"Remainder"},{"x":182,"y":12.9,"facet":"Remainder"},{"x":183,"y":4.9,"facet":"Remainder"},{"x":184,"y":-4.2,"facet":"Remainder"},{"x":185,"y":0.2,"facet":"Remainder"},{"x":186,"y":1.2,"facet":"Remainder"},{"x":187,"y":1.5,"facet":"Remainder"},{"x":188,"y":-2.4,"facet":"Remainder"},{"x":189,"y":-1.2,"facet":"Remainder"},{"x":190,"y":-2.6,"facet":"Remainder"},{"x":191,"y":-1.8,"facet":"Remainder"},{"x":192,"y":-5.9,"facet":"Remainder"},{"x":193,"y":-8.2,"facet":"Remainder"},{"x":194,"y":-6.0,"facet":"Remainder"},{"x":195,"y":-11.4,"facet":"Remainder"},{"x":196,"y":-4.1,"facet":"Remainder"},{"x":197,"y":5.6,"facet":"Remainder"},{"x":198,"y":1.1,"facet":"Remainder"},{"x":199,"y":7.4,"facet":"Remainder"},{"x":200,"y":-2.3,"facet":"Remainder"},{"x":201,"y":-9.3,"facet":"Remainder"},{"x":202,"y":-10.2,"facet":"Remainder"},{"x":203,"y":-6.7,"facet":"Remainder"},{"x":204,"y":-11.2,"facet":"Remainder"},{"x":205,"y":-1.5,"facet":"Remainder"},{"x":206,"y":5.7,"facet":"Remainder"},{"x":207,"y":9.6,"facet":"Remainder"},{"x":208,"y":12.9,"facet":"Remainder"},{"x":209,"y":28.1,"facet":"Remainder"},{"x":210,"y":42.1,"facet":"Remainder"},{"x":211,"y":31.8,"facet":"Remainder"},{"x":212,"y":40.3,"facet":"Remainder"},{"x":213,"y":48.5,"facet":"Remainder"},{"x":214,"y":7.0,"facet":"Remainder"},{"x":215,"y":1.6,"facet":"Remainder"},{"x":216,"y":5.5,"facet":"Remainder"},{"x":217,"y":-31.8,"facet":"Remainder"},{"x":218,"y":-11.1,"facet":"Remainder"},{"x":219,"y":0.0,"facet":"Remainder"},{"x":220,"y":-30.9,"facet":"Remainder"},{"x":221,"y":-14.5,"facet":"Remainder"},{"x":222,"y":-16.3,"facet":"Remainder"},{"x":223,"y":-2.9,"facet":"Remainder"},{"x":224,"y":-1.7,"facet":"Remainder"},{"x":225,"y":-2.1,"facet":"Remainder"},{"x":226,"y":-5.5,"facet":"Remainder"},{"x":227,"y":-0.7,"facet":"Remainder"},{"x":228,"y":2.3,"facet":"Remainder"},{"x":229,"y":26.3,"facet":"Remainder"},{"x":230,"y":5.8,"facet":"Remainder"},{"x":231,"y":12.2,"facet":"Remainder"},{"x":232,"y":3.2,"facet":"Remainder"},{"x":233,"y":31.6,"facet":"Remainder"},{"x":234,"y":-2.7,"facet":"Remainder"},{"x":235,"y":-10.6,"facet":"Remainder"},{"x":236,"y":-2.9,"facet":"Remainder"},{"x":237,"y":2.5,"facet":"Remainder"},{"x":238,"y":3.0,"facet":"Remainder"},{"x":239,"y":7.7,"facet":"Remainder"},{"x":240,"y":2.6,"facet":"Remainder"},{"x":241,"y":-4.8,"facet":"Remainder"},{"x":242,"y":-15.9,"facet":"Remainder"},{"x":243,"y":-11.9,"facet":"Remainder"},{"x":244,"y":11.4,"facet":"Remainder"},{"x":245,"y":15.9,"facet":"Remainder"},{"x":246,"y":8.3,"facet":"Remainder"},{"x":247,"y":-29.4,"facet":"Remainder"},{"x":248,"y":-10.8,"facet":"Remainder"},{"x":249,"y":-3.6,"facet":"Remainder"},{"x":250,"y":28.8,"facet":"Remainder"},{"x":251,"y":-2.1,"facet":"Remainder"},{"x":252,"y":-16.1,"facet":"Remainder"},{"x":253,"y":-9.5,"facet":"Remainder"},{"x":254,"y":3.1,"facet":"Remainder"},{"x":255,"y":-7.1,"facet":"Remainder"},{"x":256,"y":3.5,"facet":"Remainder"},{"x":257,"y":-4.6,"facet":"Remainder"},{"x":258,"y":2.6,"facet":"Remainder"},{"x":259,"y":19.2,"facet":"Remainder"},{"x":260,"y":15.7,"facet":"Remainder"},{"x":261,"y":27.3,"facet":"Remainder"},{"x":262,"y":10.3,"facet":"Remainder"},{"x":263,"y":30.2,"facet":"Remainder"},{"x":264,"y":15.7,"facet":"Remainder"},{"x":265,"y":7.1,"facet":"Remainder"},{"x":266,"y":4.9,"facet":"Remainder"},{"x":267,"y":-0.3,"facet":"Remainder"},{"x":268,"y":-4.4,"facet":"Remainder"},{"x":269,"y":2.7,"facet":"Remainder"},{"x":270,"y":44.3,"facet":"Remainder"},{"x":271,"y":2.7,"facet":"Remainder"},{"x":272,"y":-1.5,"facet":"Remainder"},{"x":273,"y":1.5,"facet":"Remainder"},{"x":274,"y":-29.2,"facet":"Remainder"},{"x":275,"y":-7.2,"facet":"Remainder"},{"x":276,"y":-36.9,"facet":"Remainder"},{"x":277,"y":-14.6,"facet":"Remainder"},{"x":278,"y":-21.1,"facet":"Remainder"},{"x":279,"y":1.9,"facet":"Remainder"},{"x":280,"y":-6.3,"facet":"Remainder"},{"x":281,"y":-10.4,"facet":"Remainder"},{"x":282,"y":1.4,"facet":"Remainder"},{"x":283,"y":-0.5,"facet":"Remainder"},{"x":284,"y":-0.4,"facet":"Remainder"},{"x":285,"y":-24.1,"facet":"Remainder"},{"x":286,"y":-11.9,"facet":"Remainder"},{"x":287,"y":-4.6,"facet":"Remainder"},{"x":288,"y":-1.8,"facet":"Remainder"},{"x":289,"y":8.8,"facet":"Remainder"},{"x":290,"y":29.2,"facet":"Remainder"},{"x":291,"y":27.5,"facet":"Remainder"},{"x":292,"y":6.5,"facet":"Remainder"},{"x":293,"y":13.1,"facet":"Remainder"},{"x":294,"y":27.4,"facet":"Remainder"},{"x":295,"y":-22.4,"facet":"Remainder"},{"x":296,"y":4.4,"facet":"Remainder"},{"x":297,"y":0.5,"facet":"Remainder"},{"x":298,"y":2.2,"facet":"Remainder"},{"x":299,"y":7.3,"facet":"Remainder"},{"x":300,"y":3.4,"facet":"Remainder"},{"x":301,"y":3.6,"facet":"Remainder"},{"x":302,"y":-13.8,"facet":"Remainder"},{"x":303,"y":-4.6,"facet":"Remainder"},{"x":304,"y":-23.0,"facet":"Remainder"},{"x":305,"y":-1.5,"facet":"Remainder"},{"x":306,"y":-6.7,"facet":"Remainder"},{"x":307,"y":0.8,"facet":"Remainder"},{"x":308,"y":10.2,"facet":"Remainder"},{"x":309,"y":-6.2,"facet":"Remainder"},{"x":310,"y":5.6,"facet":"Remainder"},{"x":311,"y":38.2,"facet":"Remainder"},{"x":312,"y":-8.2,"facet":"Remainder"},{"x":313,"y":-10.9,"facet":"Remainder"},{"x":314,"y":-2.7,"facet":"Remainder"},{"x":315,"y":-8.1,"facet":"Remainder"},{"x":316,"y":-7.9,"facet":"Remainder"},{"x":317,"y":-7.4,"facet":"Remainder"},{"x":318,"y":-3.9,"facet":"Remainder"},{"x":319,"y":5.1,"facet":"Remainder"},{"x":320,"y":-4.4,"facet":"Remainder"},{"x":321,"y":10.9,"facet":"Remainder"},{"x":322,"y":55.4,"facet":"Remainder"},{"x":323,"y":33.2,"facet":"Remainder"},{"x":324,"y":11.3,"facet":"Remainder"},{"x":325,"y":-0.3,"facet":"Remainder"},{"x":326,"y":8.7,"facet":"Remainder"},{"x":327,"y":-4.6,"facet":"Remainder"},{"x":328,"y":-11.6,"facet":"Remainder"},{"x":329,"y":2.2,"facet":"Remainder"},{"x":330,"y":-0.7,"facet":"Remainder"},{"x":331,"y":-21.6,"facet":"Remainder"},{"x":332,"y":-7.3,"facet":"Remainder"},{"x":333,"y":4.3,"facet":"Remainder"},{"x":334,"y":-2.3,"facet":"Remainder"},{"x":335,"y":5.4,"facet":"Remainder"},{"x":336,"y":14.9,"facet":"Remainder"},{"x":337,"y":7.1,"facet":"Remainder"},{"x":338,"y":5.2,"facet":"Remainder"},{"x":339,"y":9.4,"facet":"Remainder"},{"x":340,"y":42.3,"facet":"Remainder"},{"x":341,"y":56.6,"facet":"Remainder"},{"x":342,"y":71.8,"facet":"Remainder"},{"x":343,"y":6.8,"facet":"Remainder"},{"x":344,"y":-3.5,"facet":"Remainder"},{"x":345,"y":36.0,"facet":"Remainder"},{"x":346,"y":-31.2,"facet":"Remainder"},{"x":347,"y":-20.7,"facet":"Remainder"},{"x":348,"y":-11.8,"facet":"Remainder"},{"x":349,"y":7.7,"facet":"Remainder"},{"x":350,"y":6.6,"facet":"Remainder"},{"x":351,"y":8.9,"facet":"Remainder"},{"x":352,"y":9.8,"facet":"Remainder"},{"x":353,"y":3.8,"facet":"Remainder"},{"x":354,"y":24.8,"facet":"Remainder"},{"x":355,"y":-7.1,"facet":"Remainder"},{"x":356,"y":-9.4,"facet":"Remainder"},{"x":357,"y":0.1,"facet":"Remainder"},{"x":358,"y":-24.9,"facet":"Remainder"},{"x":359,"y":-8.1,"facet":"Remainder"},{"x":360,"y":-4.3,"facet":"Remainder"},{"x":361,"y":-51.6,"facet":"Remainder"},{"x":362,"y":-10.6,"facet":"Remainder"},{"x":363,"y":11.1,"facet":"Remainder"},{"x":364,"y":1.6,"facet":"Remainder"},{"x":365,"y":-1.3,"facet":"Remainder"},{"x":366,"y":3.7,"facet":"Remainder"},{"x":367,"y":1.3,"facet":"Remainder"},{"x":368,"y":15.3,"facet":"Remainder"},{"x":369,"y":-11.9,"facet":"Remainder"},{"x":370,"y":-5.3,"facet":"Remainder"},{"x":371,"y":2.1,"facet":"Remainder"},{"x":372,"y":-1.4,"facet":"Remainder"},{"x":373,"y":-2.0,"facet":"Remainder"},{"x":374,"y":1.5,"facet":"Remainder"},{"x":375,"y":-3.9,"facet":"Remainder"},{"x":376,"y":-26.1,"facet":"Remainder"},{"x":377,"y":-29.6,"facet":"Remainder"},{"x":378,"y":-10.7,"facet":"Remainder"},{"x":379,"y":-15.6,"facet":"Remainder"},{"x":380,"y":-9.0,"facet":"Remainder"},{"x":381,"y":4.2,"facet":"Remainder"},{"x":382,"y":32.2,"facet":"Remainder"},{"x":383,"y":-1.2,"facet":"Remainder"},{"x":384,"y":6.4,"facet":"Remainder"},{"x":385,"y":1.5,"facet":"Remainder"},{"x":386,"y":-1.0,"facet":"Remainder"},{"x":387,"y":-4.0,"facet":"Remainder"},{"x":388,"y":24.7,"facet":"Remainder"},{"x":389,"y":41.5,"facet":"Remainder"},{"x":390,"y":62.9,"facet":"Remainder"},{"x":391,"y":36.7,"facet":"Remainder"},{"x":392,"y":6.0,"facet":"Remainder"},{"x":393,"y":-3.8,"facet":"Remainder"},{"x":394,"y":43.1,"facet":"Remainder"},{"x":395,"y":4.9,"facet":"Remainder"},{"x":396,"y":-17.3,"facet":"Remainder"},{"x":397,"y":-33.4,"facet":"Remainder"},{"x":398,"y":-30.4,"facet":"Remainder"},{"x":399,"y":-21.5,"facet":"Remainder"},{"x":400,"y":0.9,"facet":"Remainder"},{"x":401,"y":0.0,"facet":"Remainder"},{"x":402,"y":13.5,"facet":"Remainder"},{"x":403,"y":5.3,"facet":"Remainder"},{"x":404,"y":7.0,"facet":"Remainder"},{"x":405,"y":2.3,"facet":"Remainder"},{"x":406,"y":-3.5,"facet":"Remainder"},{"x":407,"y":-1.0,"facet":"Remainder"},{"x":408,"y":-25.9,"facet":"Remainder"},{"x":409,"y":-11.5,"facet":"Remainder"},{"x":410,"y":-8.7,"facet":"Remainder"},{"x":411,"y":-24.9,"facet":"Remainder"},{"x":412,"y":1.4,"facet":"Remainder"},{"x":413,"y":23.2,"facet":"Remainder"},{"x":414,"y":47.2,"facet":"Remainder"},{"x":415,"y":31.3,"facet":"Remainder"},{"x":416,"y":4.3,"facet":"Remainder"},{"x":417,"y":17.4,"facet":"Remainder"},{"x":418,"y":17.5,"facet":"Remainder"},{"x":419,"y":-27.7,"facet":"Remainder"},{"x":420,"y":2.2,"facet":"Remainder"},{"x":421,"y":-2.7,"facet":"Remainder"},{"x":422,"y":-16.0,"facet":"Remainder"},{"x":423,"y":-6.6,"facet":"Remainder"},{"x":424,"y":-9.6,"facet":"Remainder"},{"x":425,"y":-8.7,"facet":"Remainder"},{"x":426,"y":1.7,"facet":"Remainder"},{"x":427,"y":23.6,"facet":"Remainder"},{"x":428,"y":10.9,"facet":"Remainder"},{"x":429,"y":23.5,"facet":"Remainder"},{"x":430,"y":3.1,"facet":"Remainder"},{"x":431,"y":-13.2,"facet":"Remainder"},{"x":432,"y":-1.8,"facet":"Remainder"},{"x":433,"y":-11.2,"facet":"Remainder"},{"x":434,"y":-45.2,"facet":"Remainder"},{"x":435,"y":-15.1,"facet":"Remainder"},{"x":436,"y":-7.3,"facet":"Remainder"},{"x":437,"y":2.0,"facet":"Remainder"},{"x":438,"y":1.4,"facet":"Remainder"},{"x":439,"y":1.8,"facet":"Remainder"},{"x":440,"y":1.0,"facet":"Remainder"},{"x":441,"y":14.0,"facet":"Remainder"}],"geom":"line","x":"Month","y":"Turnover","facetVar":"Component"}

Switch to the small multiples and each component gets its own scale. Trend climbs in almost a straight line, carrying the series' long climb from around $85 million a month to over $1,000 million, with none of the yearly bumps left in it. Season repeats a similar up and down shape every single year, drifting slowly rather than staying frozen. Remainder is the flattest panel of the four, sitting close to zero almost everywhere, the small leftover once trend and season have done their work.

=== step === concept
## Choosing windows on this retail series
::prose-only ties together the trend window, season window and robust-fitting numbers already computed in earlier steps; no new computation

Put the pieces from the last few steps together into one concrete choice for this series.

`trend(window = 21)` is short enough to still reflect a real slowdown like 2008-2009, the way `trend(window = 13)` did, without reversing direction 26 times the way that shorter window did. It is long enough to avoid chasing every month's wiggle, the way `trend(window = 105)` avoided noise, without going so long that it smooths straight through a real event the way that window did.

`season(window = 11)` is short enough to let a real multi-decade drift in the yearly pattern show through, the same kind of drift you saw in July's seasonal value moving from -5.23 to -6.12 across the decades. It is not so short that it starts refitting on noise instead of on a genuine shift in the pattern.

`robust = TRUE` is worth using on this series because January 2009 is a genuine outlier, not a data error. Without it, that one month pulls the trend and the neighbouring months' seasons toward it. With it, January 2009 keeps its own large remainder, 55.4, while the months around it are estimated as if that one outlier were not sitting right next to them.

=== step === quiz
## Quick check: robust fitting and window choice together

::quiz {"correct": 2, "gate": true, "difficulty": "advanced"}
- It removes the outlier from the series before fitting, so it no longer appears in the components() output. ::no
- It downweights the outlier's influence on the trend and season estimates for the months around it, while the outlier's own remainder can grow rather than shrink. ::ok Right. At January 2009 the remainder grew from 49.7 with robust = FALSE to 55.4 with robust = TRUE, while the neighbouring February 2009 season moved from -51.9 to -58.3. Robust fitting protects the months around an outlier. It does not shrink the outlier's own leftover.
- It only matters when the trend window is very long, since a short window already ignores outliers on its own. ::no
- It switches STL from an additive decomposition to a multiplicative one. ::no robust = TRUE never removes a point from the series, and January 2009's own remainder actually grew, from 49.7 to 55.4, rather than shrinking. A short trend window does not ignore outliers either, and robust fitting never changes STL's structure: it always fits Turnover as trend + season_year + remainder, added together.

=== step === tryit
## Your turn: fit STL yourself and read the components

`cafe` still holds the Victoria tsibble, with columns `Month` and `Turnover`. Fit STL with the windows you just settled on, `trend(window = 21)` and `season(window = 11)`, with `robust = TRUE`, pull out `components()`, then compute the range of `trend`, `season_year` and `remainder` to check them against the 871.2, 171.2 and 123.5 you read off two steps back.

```r
# cafe already holds the Victoria tsibble with columns Month and Turnover.
# 1. Fit model(cafe, STL(Turnover ~ trend(window = 21) + season(window = 11), robust = TRUE)).
# 2. Pull out components() from that fit.
# 3. Compute range() on the trend, season_year and remainder columns.
# Press Check when you have all three.
```
::check {"regex": "(?=[\\s\\S]*STL[(])(?=[\\s\\S]*components[(])(?=[\\s\\S]*range[(])[\\s\\S]*", "gate": true, "difficulty": "intermediate", "ok": "Right: trend's range comes out to 871.2, season_year's to 171.2 and remainder's to only 123.5, the same three numbers you read off two steps back. Trend carries almost the whole 984.9 span of the raw data; remainder carries the least.", "no": "Three calls in order: model(cafe, STL(Turnover ~ trend(window = 21) + season(window = 11), robust = TRUE)) to fit it, components() on that fit to pull out trend, season_year and remainder, then range() on each of those three columns."}
::solution
```r
# Fit STL with the chosen windows and robust weighting, then read the components
fit_final <- cafe |> model(STL(Turnover ~ trend(window = 21) + season(window = 11), robust = TRUE))
comp_final <- fit_final |> components()

names(comp_final)
#> [1] ".model"        "Month"         "Turnover"      "trend"        
#> [5] "season_year"   "remainder"     "season_adjust"

round(c(trend = diff(range(comp_final$trend, na.rm = TRUE)),
        season_year = diff(range(comp_final$season_year, na.rm = TRUE)),
        remainder = diff(range(comp_final$remainder, na.rm = TRUE))), 1)
#>       trend season_year   remainder 
#>       871.2       171.2       123.5 

jan09 <- comp_final |> filter(Month == yearmonth("2009 Jan"))
round(c(trend = jan09$trend, remainder = jan09$remainder), 1)
#>     trend remainder 
#>     594.8      55.4 
```

=== step === concept
## References

- Cleveland, R.B., Cleveland, W.S., McRae, J.E. & Terpenning, I. (1990), "STL: A Seasonal-Trend Decomposition Procedure Based on Loess," Journal of Official Statistics, 6(1) - the original method feasts::STL() implements.
- [Forecasting: Principles and Practice (3rd ed.), section 3.6 "STL decomposition"](https://otexts.com/fpp3/stl.html) - Hyndman, R.J. & Athanasopoulos, G., OTexts.
- [feasts::STL() reference](https://feasts.tidyverts.org/reference/STL.html) - the feasts package documentation for the function fit throughout this lesson.
- [tsibbledata::aus_retail documentation](https://tsibbledata.tidyverts.org/reference/aus_retail.html) - the dataset used throughout this lesson.
- [Retail Trade, Australia](https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia) - Australian Bureau of Statistics, catalogue 8501.0, table 11, the source behind aus_retail.

=== step === complete
## Quick recap

You decomposed a real 37-year retail series with STL, and you know exactly what each of its choices does.

- STL stands for Seasonal and Trend decomposition using Loess, and it always fits Turnover as trend + season_year + remainder, added together.
- The trend window trades smoothness for responsiveness: trend(window = 13) reversed direction 26 times, while trend(window = 105) never reversed once but smoothed straight through the 2008-2009 slowdown.
- The season window works the same way for the yearly pattern: a numeric window let July's effect drift from -5.23 to -6.12 across the decades, while season(window = "periodic") held it fixed at -3.05 every year.
- robust = TRUE protects the trend and season estimates for the months around an outlier. It does not shrink the outlier's own remainder, which actually grew from 49.7 to 55.4 at January 2009.
- components() returns trend, season_year, remainder and season_adjust, and the grey bars in autoplot() show which of the first three carries the most of the series' real movement, trend here, at 871.2 of the observed 984.9.

The next part covers seasonal adjustment: what it means to publish a series with only the seasonal part removed, and why that is not the same thing as forecasting it.
