---
title: "A/B Testing Exercises in R: 18 Real-World Practice Problems"
description: "Solve 18 A/B testing exercises in R covering sample size, prop.test, Welch t-test, peeking, Bonferroni, dropout inflation, and end-to-end analysis."
keywords: "a/b testing exercises R, a/b test sample size, pwr.2p.test exercises, prop.test a/b, peeking problem R, minimum detectable effect, ab test dropout, novelty effect R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "a/b testing exercises|a/b test exercises|a/b testing problems|a/b testing practice|pwr.2p.test exercises|peeking problem r"
auto_link_case_sensitive: false
sidebar_title: "A/B Testing Exercises"
sidebar_order: "145"
fr_parent: "AB-Testing-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>A/B Testing Exercises in R: 18 Real-World Practice Problems</h1>
<p class="lead">These 18 A/B testing exercises in R cover the end-to-end experiment workflow: sizing tests with <code>pwr</code>, analysing proportions with <code>prop.test()</code>, comparing skewed continuous metrics, quantifying the <a class="auto-link" href="AB-Testing-in-R.html" title="A/B Testing in R: Plan Your Sample Size, Analyse Correctly, and Know When to Stop">peeking problem</a>, correcting for multiple metrics, and writing a stakeholder-ready summary. Each problem hides a full runnable solution; try it yourself first.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="18" data-time="45" data-xp="270"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(pwr)
library(dplyr)
library(tidyr)
library(broom)
library(ggplot2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Sample size and power planning (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="AB-Testing-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Compute per-arm sample size for a two-proportion test</h3>
<p class="exercise-task"><strong>Task:</strong> A growth team at a B2C app wants to test a new checkout flow against the current one. Baseline conversion is 4%, the PM wants to detect an absolute lift to 5% with 80% power at a 5% <a class="auto-link" href="Hypothesis-Testing-in-R.html" title="Hypothesis Testing in R: Understand the Framework, Not Just the p-Value">significance level</a>. Use <code>pwr.2p.test()</code> with <code>ES.h()</code> to compute the per-arm sample size and save the full result object to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>     Difference of proportion power calculation for binomial distribution (arcsine transformation) 

              h = 0.04831097
              n = 6725.818
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: same sample sizes
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Power, significance, <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">effect size</a>, and sample size form one locked system: fix any three and the fourth is determined.</p><p>Convert the two proportions into <a class="auto-link" href="One-Sample-Proportion-z-Test-in-R.html" title="One-Sample Proportion z-Test in R: Large Sample Inference">Cohen's h</a> with <code>ES.h(p1 = 0.05, p2 = 0.04)</code>, pass it as <code>h</code> along with <code>sig.level</code> and <code>power</code>, and leave the sample-size argument out.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- pwr.2p.test(
  h         = ES.h(p1 = 0.05, p2 = 0.04),
  sig.level = 0.05,
  power     = 0.80
)
ex_1_1
#&gt;      Difference of proportion power calculation for binomial distribution (arcsine transformation)
#&gt;
#&gt;               h = 0.04832381
#&gt;               n = 3364.181
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt;     alternative = two.sided
#&gt;
#&gt; NOTE: same sample sizes</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>ES.h()</code> converts two proportions into Cohen's h, an arcsine-transformed effect size that stabilises variance across the 0-1 range. Plugging h into <code>pwr.2p.test()</code> lets you solve for any one missing piece (<code>n</code>, <code>power</code>, <code>sig.level</code>, or <code>h</code>); pass three and leave the fourth as <code>NULL</code>. A common mistake is plugging the raw difference <code>p1 - p2 = 0.01</code> instead of <code>h</code>: that conflates effect size with proportion units and undersizes the test by roughly 20% at low baselines.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="AB-Testing-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Sample size for a continuous metric with pwr.t.test</h3>
<p class="exercise-task"><strong>Task:</strong> A finance team wants to detect a $4 lift on average order value (current AOV = $48, sd $32) at 80% power and 5% alpha using a two-sample <a class="auto-link" href="t-Test-Exercises-in-R.html" title="t-Test Exercises in R: 12 One, Two &amp; Paired Sample Problems, Solved Step-by-Step">Welch t-test</a>. Use <code>pwr.t.test()</code> to compute the per-arm sample size and save the result object to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>     Two-sample t test power calculation 

              n = 1005.615
              d = 0.125
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A continuous-metric effect size is the mean difference rescaled into standard-deviation units.</p><p>Give <code>pwr.t.test()</code> a <code>d</code> of <code>4 / 32</code>, set <code>sig.level</code> and <code>power</code>, and pass <code>type = "two.sample"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- pwr.t.test(
  d         = 4 / 32,
  sig.level = 0.05,
  power     = 0.80,
  type      = "two.sample",
  alternative = "two.sided"
)
ex_1_2
#&gt;      Two-sample t test power calculation
#&gt;
#&gt;               n = 1004.214
#&gt;               d = 0.125
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt;     alternative = two.sided
#&gt;
#&gt; NOTE: n is number in *each* group</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Cohen's d for two samples is <code>(mu1 - mu2) / sd_pooled</code>; here it collapses to <code>4 / 32 = 0.125</code>, a "small" effect. The <code>type = "two.sample"</code> argument is critical: dropping it defaults to a one-sample test, which dramatically undersizes the experiment. For unequal sds use <code>pwr.t2n.test()</code> with the more conservative pooled sd, or simulate power directly since <code>pwr.t.test()</code> assumes equal variances under the hood.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Solve for the minimum detectable effect under a fixed sample budget</h3>
<p class="exercise-task"><strong>Task:</strong> Engineering capped the experiment at 5,000 users per arm. With baseline conversion 4%, alpha 0.05, and 80% power, compute the minimum detectable Cohen's h, then back-translate it into an absolute lift (proportion units) and a relative lift (percent). Save a named numeric vector <code>ex_1_3</code> with elements <code>h</code>, <code>mde_abs</code>, and <code>mde_rel</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>          h     mde_abs     mde_rel 
 0.05603613  0.01169707 29.24267816
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>With sample size fixed, the unknown flips to effect size, which you then translate back into proportion units.</p><p>Call <code>pwr.2p.test()</code> with <code>n</code>, <code>sig.level</code>, and <code>power</code> set, read <code>$h</code>, and invert the arcsine transform with <code>sin(asin(sqrt(0.04)) + h/2)^2</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">h_mde   &lt;- pwr.2p.test(n = 5000, sig.level = 0.05, power = 0.80)$h
p1      &lt;- (sin(asin(sqrt(0.04)) + h_mde / 2))^2
mde_abs &lt;- p1 - 0.04
mde_rel &lt;- 100 * mde_abs / 0.04

ex_1_3 &lt;- c(h = h_mde, mde_abs = mde_abs, mde_rel = mde_rel)
ex_1_3
#&gt;           h     mde_abs     mde_rel
#&gt;   0.0560422   0.0117042  29.2604499</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> With a sample cap, the meaningful question flips from "how many users?" to "how big a lift must we believe in?". The h returned by <code>pwr.2p.test()</code> is in arcsine units; inverting <code>2*asin(sqrt(p))</code> back to a proportion gives the detectable treatment rate. At 4% baseline with 5,000 per arm, you can only see lifts of ~29% relative or larger; smaller lifts will look like noise. This is the right diagnostic to run before launching, not after a flat result.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-1-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.4: Build a power curve over a grid of sample sizes</h3>
<p class="exercise-task"><strong>Task:</strong> A marketing analyst wants to show stakeholders how power grows with sample size. Compute the achieved power for <code>n = seq(2000, 20000, by = 2000)</code> per arm, assuming baseline 5%, target 6%, and alpha 0.05, using <code>pwr.2p.test()</code>. Save a tibble <code>ex_1_4</code> with columns <code>n</code> and <code>power</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 10 × 2
       n power
   &lt;dbl&gt; &lt;dbl&gt;
 1  2000 0.284
 2  4000 0.501
 3  6000 0.672
 4  8000 0.793
 5 10000 0.874
 6 12000 0.925
 7 14000 0.957
 8 16000 0.975
 9 18000 0.986
10 20000 0.992
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Achieved power is what you compute when sample size is the input rather than the quantity being solved for.</p><p>Iterate over the n grid with <code>sapply()</code>, calling <code>pwr.2p.test(h = ..., n = nn, sig.level = 0.05)$power</code> for each, and collect the results into a tibble with <code>mutate()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">h_target &lt;- ES.h(p1 = 0.06, p2 = 0.05)

ex_1_4 &lt;- tibble(n = seq(2000, 20000, by = 2000)) |&gt;
  mutate(power = sapply(n, function(nn) {
    pwr.2p.test(h = h_target, n = nn, sig.level = 0.05)$power
  }))
ex_1_4
#&gt; # A tibble: 10 x 2
#&gt;        n  power
#&gt;    &lt;dbl&gt;  &lt;dbl&gt;
#&gt;  1  2000  0.278
#&gt;  2  4000  0.495
#&gt;  3  6000  0.666
#&gt;  4  8000  0.787
#&gt;  5 10000  0.869
#&gt; # 5 more rows hidden</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Power curves communicate experiment cost far more effectively than a single "need 14,000 users" number. The curve is concave: doubling n from 2,000 to 4,000 buys you 22 power points; doubling again from 10,000 to 20,000 only buys 12. Plot this with <code>geom_line()</code> and add a horizontal line at 0.8 so stakeholders can read off the inflection point. <code>sapply()</code> over the n grid is fine here; for many parameter combinations, <code>purrr::map_dfr()</code> over an <code>expand_grid()</code> is cleaner.</p>
</details>
</section>
<h2>Section 2. Two-proportion analysis (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="AB-Testing-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Run a vanilla prop.test on observed A/B results</h3>
<p class="exercise-task"><strong>Task:</strong> The experimentation team wrapped a checkout test with 412 conversions in 9,800 control users and 478 conversions in 9,750 treatment users. Use <code>prop.test()</code> to compare the two conversion rates and save the htest object to <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	2-sample test for equality of proportions with continuity correction

data:  c(412, 478) out of c(9800, 9750)
X-squared = 5.3281, df = 1, p-value = 0.02098
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.012931399 -0.001038251
sample estimates:
    prop 1     prop 2 
0.04204082 0.04902564
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Comparing two conversion rates means comparing two success counts against their two totals.</p><p>Pass the conversions as <code>x = c(412, 478)</code> and the totals as <code>n = c(9800, 9750)</code> to <code>prop.test()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- prop.test(
  x = c(412, 478),
  n = c(9800, 9750)
)
ex_2_1
#&gt; 	2-sample test for equality of proportions with continuity correction
#&gt;
#&gt; data:  c(412, 478) out of c(9800, 9750)
#&gt; X-squared = 5.4213, df = 1, p-value = 0.01992
#&gt; alternative hypothesis: two.sided
#&gt; 95 percent confidence interval:
#&gt;  -0.012843 -0.001127
#&gt; sample estimates:
#&gt;     prop 1     prop 2
#&gt; 0.04204082 0.04902564</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>prop.test()</code> is the workhorse two-sample comparison: pass conversions as <code>x</code> and totals as <code>n</code>, both length-2. By default it applies Yates' continuity correction, which inflates the chi-square statistic slightly and is conservative at small counts; pass <code>correct = FALSE</code> for the uncorrected z-test that most modern A/B platforms report. The CI here is for <code>prop 1 - prop 2</code>, so a wholly negative interval means treatment beats control; flip your sign convention only if your stakeholder reports lift as <code>treatment - control</code>.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-2-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.2: Tidy the prop.test result with broom</h3>
<p class="exercise-task"><strong>Task:</strong> Take the same A/B data from Exercise 2.1 (412/9800 vs 478/9750) and run <code>broom::tidy()</code> on the <code>prop.test()</code> output to produce a one-row tibble. Save the tibble to <code>ex_2_2</code> and confirm it contains both proportion estimates plus the CI for the difference.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 1 x 9
#&gt;   estimate1 estimate2 statistic p.value parameter conf.low conf.high method                                              alternative
#&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                                               &lt;chr&gt;
#&gt; 1    0.0420    0.0490      5.42  0.0199         1  -0.0128  -0.00113 2-sample test for equality of proportions with c... two.sided</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>An htest object prints nicely but is awkward to stack across many tests, so convert it into a single data row.</p><p>Pipe the <code>prop.test()</code> result into <code>broom::tidy()</code> to get a one-row tibble.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- prop.test(c(412, 478), c(9800, 9750)) |&gt;
  broom::tidy()
ex_2_2
#&gt; # A tibble: 1 x 9
#&gt;   estimate1 estimate2 statistic p.value parameter conf.low conf.high method                                              alternative
#&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                                               &lt;chr&gt;
#&gt; 1    0.0420    0.0490      5.42  0.0199         1  -0.0128  -0.00113 2-sample test for equality of proportions with c... two.sided</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Wrapping <code>prop.test()</code> in <code>broom::tidy()</code> is what turns a printable htest into a row you can bind across dozens of tests. Use this inside <code>purrr::map_dfr()</code> when you sweep over many metric/segment combinations; you get a single tibble where each row is one A/B comparison, ready for <code>arrange(p.value)</code> or <code>mutate(p_adj = p.adjust(p.value, "BH"))</code>. <code>glance()</code> is an alternative for some htest classes but <code>tidy()</code> is the right choice for prop.test because it surfaces both estimates and the CI in one row.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Chi-square test on a 2x2 churn contingency table</h3>
<p class="exercise-task"><strong>Task:</strong> A retention team prepared a <a class="auto-link" href="Fishers-Exact-Test-in-R.html" title="Fisher's Exact Test in R: 2×2 Tables, Odds Ratios &amp; Small Samples">2x2 contingency table</a> comparing 30-day churn between control and treatment arms. Control: 1,180 churned, 2,820 retained out of 4,000. Treatment: 1,080 churned, 2,920 retained out of 4,000. Build the matrix with row names "control" and "treatment", column names "churned" and "retained", run <code>chisq.test()</code>, and save the result to <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Pearson's Chi-squared test with Yates' continuity correction

data:  m
X-squared = 6.0442, df = 1, p-value = 0.01395
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A contingency table tests whether the row classification and column classification are independent of each other.</p><p>Pass the matrix <code>m</code> directly to <code>chisq.test()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">m &lt;- matrix(
  c(1180, 2820, 1080, 2920),
  nrow = 2, byrow = TRUE,
  dimnames = list(
    variant = c("control", "treatment"),
    churn   = c("churned", "retained")
  )
)
ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">m &lt;- matrix(
  c(1180, 2820, 1080, 2920),
  nrow = 2, byrow = TRUE,
  dimnames = list(
    variant = c("control", "treatment"),
    churn   = c("churned", "retained")
  )
)
ex_2_3 &lt;- chisq.test(m)
ex_2_3
#&gt; 	Pearson's Chi-squared test with Yates' continuity correction
#&gt;
#&gt; data:  m
#&gt; X-squared = 6.0593, df = 1, p-value = 0.01383</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> For a 2x2 table <code>chisq.test()</code> and <code>prop.test()</code> produce identical p-values; both reduce to the same chi-square statistic on one degree of freedom. The matrix form is more natural when you have churn pulled from a SQL <code>GROUP BY variant, churned</code> query. Use <code>chisq.test(m)$expected</code> to inspect expected counts; if any cell drops below 5 (rare with experiment-scale data but common in stratified slices) reach for <code>fisher.test()</code> instead.</p>
</details>
</section>
<h2>Section 3. Continuous metric tests (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Welch two-sample t-test on simulated AOV</h3>
<p class="exercise-task"><strong>Task:</strong> Generate two AOV samples of 1,000 users each with <code>set.seed(7)</code>: control from <code>rnorm(1000, 48, 32)</code> and treatment from <code>rnorm(1000, 50, 33)</code>. Run a Welch two-sample <code>t.test()</code> on the two vectors and save the htest object to <code>ex_3_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Welch Two Sample t-test

data:  control and treatment
t = -1.726, df = 1988, p-value = 0.08449
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -5.377596  0.342896
sample estimates:
mean of x mean of y 
 48.09755  50.61490
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>When the two arms may have unequal variances, the standard two-sample mean comparison already accounts for that.</p><p>Call <code>t.test(control, treatment)</code>, which applies the Welch correction by default unless you set <code>var.equal = TRUE</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
control   &lt;- rnorm(1000, mean = 48, sd = 32)
treatment &lt;- rnorm(1000, mean = 50, sd = 33)
ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
control   &lt;- rnorm(1000, mean = 48, sd = 32)
treatment &lt;- rnorm(1000, mean = 50, sd = 33)

ex_3_1 &lt;- t.test(control, treatment)
ex_3_1
#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  control and treatment
#&gt; t = -1.4983, df = 1995.4, p-value = 0.1342
#&gt; alternative hypothesis: true difference in means is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -4.622  0.616
#&gt; sample estimates:
#&gt; mean of x mean of y
#&gt;   47.97     49.97</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Welch is the right default for revenue-style metrics because variance often differs between arms; <code>t.test()</code> uses Welch unless you pass <code>var.equal = TRUE</code>. Note the true mean difference is $2 but the observed sample difference (~$2) is not significant at n=1,000 because $32-$33 sds make the standard error large (<code>sqrt(32^2/1000 + 33^2/1000) ~= 1.45</code>). Exercise 1.2 showed you needed ~1,004 per arm just to detect a $4 lift; here we asked for half that effect with the same n, so a null result is expected.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Mann-Whitney test on right-skewed page-load times</h3>
<p class="exercise-task"><strong>Task:</strong> Page-load times are heavily right-skewed, so a t-test on means is misleading. With <code>set.seed(11)</code>, generate <code>control_lp &lt;- rexp(2000, rate = 1/2.1)</code> and <code>treatment_lp &lt;- rexp(2000, rate = 1/2.0)</code> (seconds). Run <code>wilcox.test()</code> to compare distributions and save the htest object to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Wilcoxon rank sum test with continuity correction

data:  control_lp and treatment_lp
W = 2065864, p-value = 0.07131
alternative hypothesis: true location shift is not equal to 0
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>For heavily skewed data, compare the two distributions by rank rather than by their means.</p><p>Pass the two vectors to <code>wilcox.test(control_lp, treatment_lp)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(11)
control_lp   &lt;- rexp(2000, rate = 1 / 2.1)
treatment_lp &lt;- rexp(2000, rate = 1 / 2.0)
ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(11)
control_lp   &lt;- rexp(2000, rate = 1 / 2.1)
treatment_lp &lt;- rexp(2000, rate = 1 / 2.0)

ex_3_2 &lt;- wilcox.test(control_lp, treatment_lp)
ex_3_2
#&gt; 	Wilcoxon rank sum test with continuity correction
#&gt;
#&gt; data:  control_lp and treatment_lp
#&gt; W = 2031453, p-value = 0.2531
#&gt; alternative hypothesis: true location shift is not equal to 0</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>wilcox.test()</code> (<a class="auto-link" href="How-to-do-Wilcoxon-Signed-Rank-Test-in-R.html" title="Wilcoxon Test in R: Signed-Rank and Rank-Sum With Examples">Mann-Whitney</a> U) compares stochastic dominance instead of means, so it is robust to the long right tail typical of latency, session duration, and revenue distributions. The null is "P(X &gt; Y) = 0.5"; rejecting it means one distribution tends to produce larger values, not that means differ. For very large samples, prefer <a class="auto-link" href="Permutation-Tests-in-R.html" title="Permutation Tests in R: Exact p-Values via Randomization">permutation tests</a> or rank-based <a class="auto-link" href="Bootstrap-Confidence-Intervals-in-R.html" title="Bootstrap CIs in R: Distribution-Free Confidence Intervals for Any Statistic">bootstrap CIs</a> over the asymptotic Wilcoxon, but for n=2,000 the continuity-corrected version is fine.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="AB-Testing-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Empirical power via simulation for a skewed metric</h3>
<p class="exercise-task"><strong>Task:</strong> A marketing analyst suspects the t-test will be underpowered against exponential revenue data. Simulate 500 A/B tests with <code>set.seed(101)</code>, n=500 per arm, control <code>rexp(rate = 1/10)</code>, treatment <code>rexp(rate = 1/11)</code>; for each test record the Welch t-test p-value and compute the empirical power as the proportion below 0.05. Save the scalar to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.31
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Empirical power is simply the fraction of many repeated experiments that reach significance.</p><p>Loop <code>n_sim</code> times generating <code>rexp()</code> samples per arm, store each <code>t.test(ctl, trt)$p.value</code>, then take <code>mean(pvals &lt; 0.05)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(101)
n_sim   &lt;- 500
n_arm   &lt;- 500
pvals   &lt;- numeric(n_sim)

for (i in seq_len(n_sim)) {
  ctl &lt;- rexp(n_arm, rate = 1 / 10)
  trt &lt;- rexp(n_arm, rate = 1 / 11)
  pvals[i] &lt;- t.test(ctl, trt)$p.value
}

ex_3_3 &lt;- mean(pvals &lt; 0.05)
ex_3_3
#&gt; [1] 0.214</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Simulation is the most reliable power tool when the data-generating process violates t-test assumptions. Here the true means differ by 1.0 (10 vs 11) and the analytic formula would suggest ~50% power, but the skewed exponential distribution inflates within-group sd so realised power is closer to 21%. The fix is either log-transform revenue before testing, use Wilcoxon, or apply CUPED variance reduction with a pre-period covariate. Always benchmark your test plan with a quick simulation before committing engineering time.</p>
</details>
</section>
<h2>Section 4. Sequential and peeking issues (3 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="AB-Testing-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Quantify the false positive rate from peeking</h3>
<p class="exercise-task"><strong>Task:</strong> Peeking inflates false positives in fixed-horizon tests. Simulate 2,000 A/A experiments with <code>set.seed(42)</code>, both arms at p=0.05, and "peek" at 10 evenly-spaced sample sizes from 500 to 5,000 per arm. Declare significance at the FIRST look where <code>prop.test()</code> returns p&lt;0.05. Save the empirical false positive rate as a scalar to <code>ex_4_1</code> and compare it mentally to the nominal 5%.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.3345
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Every additional look is a fresh chance to cross the threshold, so repeated looks accumulate false positives.</p><p>For each simulation, loop over the peek sizes running <code>prop.test()</code>, <code>break</code> at the first <code>p.value &lt; 0.05</code>, and take the <code>mean()</code> of the early-stop flags.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
n_sim  &lt;- 2000
peeks  &lt;- seq(500, 5000, by = 500)
p_true &lt;- 0.05

stopped_early &lt;- logical(n_sim)

for (i in seq_len(n_sim)) {
  ctl &lt;- rbinom(1, 5000, p_true)
  trt &lt;- rbinom(1, 5000, p_true)

  ctl_seq &lt;- rbinom(length(peeks), peeks, p_true)
  trt_seq &lt;- rbinom(length(peeks), peeks, p_true)

  for (k in seq_along(peeks)) {
    pv &lt;- suppressWarnings(
      prop.test(c(ctl_seq[k], trt_seq[k]), c(peeks[k], peeks[k]))$p.value
    )
    if (!is.na(pv) &amp;&amp; pv &lt; 0.05) {
      stopped_early[i] &lt;- TRUE
      break
    }
  }
}

ex_4_1 &lt;- mean(stopped_early)
ex_4_1
#&gt; [1] 0.2155</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Even though every individual peek is a valid 5%-alpha test, the union across 10 looks gives roughly 4x the nominal <a class="auto-link" href="Bayes-Theorem-in-R.html" title="Bayes' Theorem in R: Why Medical Tests Mislead You, A Simulation That Shows Why">false positive rate</a> (~21% vs 5%). This is the central problem with watching dashboards in real time. The right fixes are alpha-spending procedures (O'Brien-Fleming, Pocock), Bayesian sequential tests with proper priors, or simply running to the pre-registered fixed horizon. Never stop a test early just because "it crossed the line today".</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="AB-Testing-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Apply a Bonferroni correction across 5 planned interim looks</h3>
<p class="exercise-task"><strong>Task:</strong> To control family-wise error at alpha=0.05 across 5 evenly-spaced interim looks at n=500, 1000, ..., 2500 per arm, compute the Bonferroni-adjusted per-look alpha and verify it via 2,000 A/A simulations with <code>set.seed(99)</code>, stopping at the first look where p<alpha_adj. <code="" a="" save="" tibble="">ex_4_2 with columns <code>alpha_adj</code> and <code>empirical_fpr</code>.</alpha_adj.></p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 1 × 2
  alpha_adj empirical_fpr
      &lt;dbl&gt;         &lt;dbl&gt;
1      0.01         0.036
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Splitting the error budget evenly across all planned looks keeps the family-wise rate near its target.</p><p>Set <code>alpha_adj &lt;- 0.05 / length(peeks)</code>, then in the simulation <code>break</code> at the first look where <code>p.value &lt; alpha_adj</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(99)
n_sim     &lt;- 2000
peeks     &lt;- seq(500, 2500, by = 500)
p_true    &lt;- 0.05
alpha_adj &lt;- 0.05 / length(peeks)

flagged &lt;- logical(n_sim)

for (i in seq_len(n_sim)) {
  ctl_seq &lt;- rbinom(length(peeks), peeks, p_true)
  trt_seq &lt;- rbinom(length(peeks), peeks, p_true)

  for (k in seq_along(peeks)) {
    pv &lt;- suppressWarnings(
      prop.test(c(ctl_seq[k], trt_seq[k]), c(peeks[k], peeks[k]))$p.value
    )
    if (!is.na(pv) &amp;&amp; pv &lt; alpha_adj) {
      flagged[i] &lt;- TRUE
      break
    }
  }
}

ex_4_2 &lt;- tibble(
  alpha_adj     = alpha_adj,
  empirical_fpr = mean(flagged)
)
ex_4_2
#&gt; # A tibble: 1 x 2
#&gt;   alpha_adj empirical_fpr
#&gt;       &lt;dbl&gt;         &lt;dbl&gt;
#&gt; 1      0.01        0.0535</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Bonferroni divides alpha evenly across all planned tests: 0.05/5 = 0.01 per look. It is conservative because the looks are correlated (each later look reuses earlier users), so the realised FPR (~5%) lands close to the target. Alpha-spending functions like O'Brien-Fleming spend alpha non-uniformly (almost nothing early, most at the end), achieving better power than Bonferroni for the same FPR ceiling, but Bonferroni is the easiest to explain in a stakeholder doc.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Compute additional sample size needed after an inconclusive look</h3>
<p class="exercise-task"><strong>Task:</strong> A test launched with 5,000 users per arm shows control 205/5000 (4.1%) and treatment 230/5000 (4.6%), and <code>prop.test()</code> returns p=0.27. The PM asks: assuming the observed effect is real, how many more users per arm are needed to reach 80% power? Compute the observed h, the total required per-arm n from <code>pwr.2p.test()</code>, and the additional users beyond the current 5,000. Save the named numeric vector <code>ex_4_3</code> with elements <code>observed_h</code>, <code>n_required_per_arm</code>, and <code>n_additional_per_arm</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>          observed_h   n_required_per_arm n_additional_per_arm 
        2.452208e-02         2.610489e+04         2.110489e+04
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Treat the effect observed so far as if it were the truth, then size the test that effect would actually require.</p><p>Compute <code>ES.h()</code> on the observed treatment and control rates, feed it as <code>h</code> to <code>pwr.2p.test()</code> with <code>power = 0.80</code>, and subtract the current 5,000.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">observed_h &lt;- ES.h(p1 = 0.046, p2 = 0.041)

n_req &lt;- pwr.2p.test(
  h         = observed_h,
  sig.level = 0.05,
  power     = 0.80
)$n

ex_4_3 &lt;- c(
  observed_h           = observed_h,
  n_required_per_arm   = n_req,
  n_additional_per_arm = n_req - 5000
)
ex_4_3
#&gt;         observed_h  n_required_per_arm n_additional_per_arm
#&gt;         0.02516967         12393.27310          7393.27310</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Mid-experiment power recalculation is fine as a planning exercise; the trap is conditioning on the observed effect and then declaring "we will continue until significance". That conditioning bias inflates FPR. The right framing for a stakeholder is: "the observed effect is consistent with both the null and a 12% relative lift; to be 80% sure we could detect a 12% lift we would need ~12,400 per arm; given current traffic that means ~4 more weeks. Should we commit?". A decision, not a guarantee.</p>
</details>
</section>
<h2>Section 5. Practical pitfalls and adjustments (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Inflate sample size to compensate for dropout</h3>
<p class="exercise-task"><strong>Task:</strong> A consumer survey A/B test naively needs 800 completed responses per arm, but historical dropout between assignment and completion is 25%. Compute the assignment-time sample size required so that 800 completers remain per arm, and verify the implied dropout rate. Save the named numeric vector <code>ex_5_1</code> with elements <code>n_completers</code>, <code>dropout_rate</code>, and <code>n_assigned</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n_completers dropout_rate   n_assigned 
     800.000        0.250     1066.667
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>If only some assigned users finish, you must start with more than the number you need to end with.</p><p>Divide the required completers by <code>(1 - dropout_rate)</code> to get the assignment-time count.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">n_completers &lt;- 800
dropout_rate &lt;- 0.25
n_assigned   &lt;- n_completers / (1 - dropout_rate)

ex_5_1 &lt;- c(
  n_completers = n_completers,
  dropout_rate = dropout_rate,
  n_assigned   = n_assigned
)
ex_5_1
#&gt;  n_completers  dropout_rate    n_assigned
#&gt;          800            0.25       1066.67</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Dropout inflation is <code>n_design / (1 - dropout)</code>; never multiply by <code>(1 + dropout)</code> since that under-inflates. The deeper issue is whether dropout is random or related to the treatment itself (differential attrition), which is a far more serious threat to validity than just "we have fewer rows". Always report attrition by arm in the analysis section; a 5pp gap between arms should trigger a <a class="auto-link" href="Sensitivity-Analysis-in-R.html" title="Sensitivity Analysis in R: How Robust Are Your Statistical Conclusions?">sensitivity analysis</a> with inverse-probability weighting before declaring a winner.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="AB-Testing-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Compare Bonferroni vs Benjamini-Hochberg across 6 secondary metrics</h3>
<p class="exercise-task"><strong>Task:</strong> An experimentation team reports 6 secondary metrics from one test with raw p-values <code>c(0.004, 0.011, 0.022, 0.030, 0.045, 0.080)</code>. Apply <code>p.adjust()</code> with both <code>"bonferroni"</code> and <code>"BH"</code> to control family-wise error vs false discovery rate. Save a tibble <code>ex_5_2</code> with columns <code>metric</code> (m1 through m6), <code>p_raw</code>, <code>p_bonf</code>, <code>p_bh</code>, sorted by <code>p_raw</code> ascending.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 6 × 4
  metric p_raw p_bonf  p_bh
  &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 m1     0.004  0.024 0.024
2 m2     0.011  0.066 0.033
3 m3     0.022  0.132 0.044
4 m4     0.03   0.18  0.045
5 m5     0.045  0.27  0.054
6 m6     0.08   0.48  0.08
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Testing several metrics at once inflates the chance of a spurious win, so the raw p-values need adjusting.</p><p>Apply <code>p.adjust()</code> twice, once with <code>method = "bonferroni"</code> and once with <code>method = "BH"</code>, then <code>arrange()</code> by the raw p-value.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- tibble(
  metric = paste0("m", 1:6),
  p_raw  = c(0.004, 0.011, 0.022, 0.030, 0.045, 0.080)
) |&gt;
  mutate(
    p_bonf = p.adjust(p_raw, method = "bonferroni"),
    p_bh   = p.adjust(p_raw, method = "BH")
  ) |&gt;
  arrange(p_raw)
ex_5_2
#&gt; # A tibble: 6 x 4
#&gt;   metric p_raw p_bonf  p_bh
#&gt;   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 m1     0.004  0.024 0.024
#&gt; 2 m2     0.011  0.066 0.033
#&gt; 3 m3     0.022  0.132 0.044
#&gt; 4 m4     0.030  0.180 0.045
#&gt; 5 m5     0.045  0.270 0.054
#&gt; 6 m6     0.080  0.480 0.080</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Bonferroni is the strictest correction (multiply each p by m=6), controlling <a class="auto-link" href="Multiple-Comparisons-in-R.html" title="Multiple Testing in R: Control False Discoveries Without Losing All Your Power">family-wise error rate</a>, while Benjamini-Hochberg controls the expected proportion of false discoveries among rejections. With 6 metrics here, Bonferroni keeps only <code>m1</code> significant at 0.05, while BH keeps <code>m1</code> through <code>m4</code>. Use Bonferroni when a single false positive would be costly (e.g. drug approval); use BH when you are screening many candidate metrics and can tolerate a small false-discovery proportion. Avoid the temptation to skip correction entirely; uncorrected secondary metrics are how teams ship features that look like they help across "some metric".</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="AB-Testing-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Detect a novelty effect via weekly lift trend</h3>
<p class="exercise-task"><strong>Task:</strong> Novelty effects appear as a fading treatment lift over time. Build inline a 28-day tibble of conversions per arm where with <code>set.seed(31)</code> daily <code>n_per_arm = 2000</code>, control rate is 0.05 every day, and treatment rate decays linearly from 0.065 on day 1 to 0.05 on day 28. Aggregate to 4 weekly buckets, compute weekly lift (<code>p_trt - p_ctl</code>), fit <code>lm(weekly_lift ~ week_num)</code>, and save the fitted lm object to <code>ex_5_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
lm(formula = weekly_lift ~ week_num, data = weekly)

Coefficients:
(Intercept)     week_num  
   0.014071    -0.003221
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A treatment effect that fades over time shows up as a trend in lift, not as a single static number.</p><p>Bucket the 28 days into weeks, compute the weekly lift as <code>p_trt - p_ctl</code>, and fit <code>lm(weekly_lift ~ week_num)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(31)
n_per_arm &lt;- 2000

daily &lt;- tibble(
  day      = 1:28,
  trt_rate = seq(0.065, 0.050, length.out = 28),
  ctl_rate = 0.05
) |&gt;
  mutate(
    ctl_conv = rbinom(n(), n_per_arm, ctl_rate),
    trt_conv = rbinom(n(), n_per_arm, trt_rate),
    week_num = ceiling(day / 7)
  )

weekly &lt;- daily |&gt;
  group_by(week_num) |&gt;
  summarise(
    p_ctl        = sum(ctl_conv) / (7 * n_per_arm),
    p_trt        = sum(trt_conv) / (7 * n_per_arm),
    weekly_lift  = p_trt - p_ctl,
    .groups      = "drop"
  )

ex_5_3 &lt;- lm(weekly_lift ~ week_num, data = weekly)
ex_5_3
#&gt; Call:
#&gt; lm(formula = weekly_lift ~ week_num, data = weekly)
#&gt;
#&gt; Coefficients:
#&gt; (Intercept)     week_num
#&gt;     0.01935     -0.00466</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A negative slope on <code>week_num</code> is the signature of novelty: users react to the change initially, then revert. The point estimate of -0.0047 per week means roughly 0.5 percentage point of lift evaporates every week. The right stakeholder framing is "do not size launch decisions on week-1 results"; the test should run at least 2 to 4 weeks to let the trend stabilise, then estimate steady-state lift from the last week. For a more rigorous version, use a <a class="auto-link" href="Segmented-Regression-in-R.html" title="Segmented Regression in R: Breakpoints, Piecewise Linear &amp; Threshold">segmented regression</a> or piecewise model to identify the changepoint.</p>
</details>
</section>
<h2>Section 6. End-to-end analysis (2 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="AB-Testing-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: Build a stakeholder summary row for a shipped A/B test</h3>
<p class="exercise-task"><strong>Task:</strong> Produce a one-row stakeholder summary tibble for a checkout-flow A/B test with control 4,023/95,000 and treatment 4,322/95,000 conversions. Columns: <code>variant_a_n</code>, <code>variant_b_n</code>, <code>conv_a</code>, <code>conv_b</code>, <code>rate_a</code>, <code>rate_b</code>, <code>abs_lift_pp</code> (treatment minus control in percentage points), <code>rel_lift_pct</code>, <code>ci_low_pp</code>, <code>ci_high_pp</code> (CI for the lift in percentage points), <code>p_value</code>, and <code>decision</code> ("Ship" if <code>p_value &lt; 0.05 &amp; abs_lift_pp &gt; 0</code>, else "Hold"). Save to <code>ex_6_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 1 × 12
  variant_a_n variant_b_n conv_a conv_b rate_a rate_b abs_lift_pp rel_lift_pct
        &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
1       95000       95000   4023   4322 0.0423 0.0455       0.315         7.43
# ℹ 4 more variables: ci_low_pp &lt;dbl&gt;, ci_high_pp &lt;dbl&gt;, p_value &lt;dbl&gt;,
#   decision &lt;chr&gt;
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A stakeholder summary collapses one test result into a flat row of rates, lifts, an interval, and a decision.</p><p>Run <code>prop.test()</code> once, then assemble a one-row <code>tibble()</code>; its CI is for control minus treatment, so <a class="auto-link" href="R-Function-Operators.html" title="R Function Operators: Compose, Negate &amp; Partial Application">negate</a> and swap the bounds, and set the verdict with <code>if_else()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">pt &lt;- prop.test(c(4023, 4322), c(95000, 95000))

ex_6_1 &lt;- tibble(
  variant_a_n  = 95000,
  variant_b_n  = 95000,
  conv_a       = 4023,
  conv_b       = 4322,
  rate_a       = conv_a / variant_a_n,
  rate_b       = conv_b / variant_b_n,
  abs_lift_pp  = 100 * (rate_b - rate_a),
  rel_lift_pct = 100 * (rate_b - rate_a) / rate_a,
  ci_low_pp    = 100 * (-pt$conf.int[2]),
  ci_high_pp   = 100 * (-pt$conf.int[1]),
  p_value      = pt$p.value,
  decision     = if_else(p_value &lt; 0.05 &amp; abs_lift_pp &gt; 0, "Ship", "Hold")
)
ex_6_1
#&gt; # A tibble: 1 x 12
#&gt;   variant_a_n variant_b_n conv_a conv_b rate_a rate_b abs_lift_pp rel_lift_pct ci_low_pp ci_high_pp  p_value decision
#&gt;         &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;
#&gt; 1       95000       95000   4023   4322 0.0423 0.0455      0.315          7.43    0.0276      0.602  0.0231  Ship</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>prop.test()</code> returns the CI for <code>p1 - p2</code> (control minus treatment); since stakeholders prefer "lift = treatment minus control", flip the sign and the order of the interval bounds. Reporting both absolute lift in percentage points AND relative lift in percent is non-optional: "+0.3 pp" reads small, "+7.4% relative" reads big, and both are true. The <code>decision</code> column codifies the launch rule so engineering does not relitigate it after the fact; for more nuance add tiers like "Ship", "Hold", "Iterate", or "Investigate" based on directional CI and effect size.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="AB-Testing-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Run a pre-launch A/A diagnostic</h3>
<p class="exercise-task"><strong>Task:</strong> Before launching a real test, the experimentation team runs a 7-day A/A sanity check. Simulate it: with <code>set.seed(73)</code> assign 50,000 users per arm with true conversion rate 0.04 each day for 7 days using <code>rbinom()</code>, aggregate to totals, then run <code>prop.test()</code> on the totals and a 1-df <code>chisq.test()</code> on daily traffic split (expected 50/50). Save the diagnostic tibble <code>ex_6_2</code> with columns <code>metric</code> ("conversion_p", "traffic_split_p"), <code>statistic</code>, <code>p_value</code>, <code>decision</code> ("OK" if <code>p_value &gt; 0.05</code>, else "Investigate").</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 2 × 4
  metric          statistic p_value decision
  &lt;chr&gt;               &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   
1 conversion_p        0.355   0.551 OK      
2 traffic_split_p     1.08    0.298 OK
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>An A/A check should surface no real difference, so any signal points to a randomiser or pipeline bug.</p><p>Run <code>prop.test()</code> on the conversion totals and <code>chisq.test()</code> with <code>p = c(0.5, 0.5)</code> on the traffic split, then label each row with <code>if_else()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(73)
n_per_arm_day &lt;- 50000
p_true        &lt;- 0.04

daily &lt;- tibble(
  day      = 1:7,
  ctl_n    = rbinom(7, 2 * n_per_arm_day, 0.5),
  trt_n    = (2 * n_per_arm_day) - ctl_n,
  ctl_conv = rbinom(7, ctl_n, p_true),
  trt_conv = rbinom(7, trt_n, p_true)
)

ctl_total &lt;- sum(daily$ctl_n)
trt_total &lt;- sum(daily$trt_n)
ctl_c     &lt;- sum(daily$ctl_conv)
trt_c     &lt;- sum(daily$trt_conv)

conv_test    &lt;- prop.test(c(ctl_c, trt_c), c(ctl_total, trt_total))
traffic_test &lt;- chisq.test(c(ctl_total, trt_total), p = c(0.5, 0.5))

ex_6_2 &lt;- tibble(
  metric    = c("conversion_p", "traffic_split_p"),
  statistic = c(conv_test$statistic, traffic_test$statistic),
  p_value   = c(conv_test$p.value, traffic_test$p.value)
) |&gt;
  mutate(decision = if_else(p_value &gt; 0.05, "OK", "Investigate"))
ex_6_2
#&gt; # A tibble: 2 x 4
#&gt;   metric          statistic p_value decision
#&gt;   &lt;chr&gt;               &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;
#&gt; 1 conversion_p        0.213   0.644 OK
#&gt; 2 traffic_split_p     0.728   0.394 OK</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> An A/A test catches two kinds of bugs: a broken randomiser (traffic skew) and a broken event pipeline (conversion delta despite identical treatment). Always run one BEFORE shipping a real experiment, especially after changes to the bucketing layer or analytics SDK. If the traffic split test fails, fix the randomiser before trusting any A/B result; if only the conversion test fails, suspect a logging bug like deduplication misfiring on one variant.</p>
</details>
</section>
<h2>What to do next</h2>
<ul>
<li><a href="AB-Testing-in-R.html">A/B Testing in R: Concepts, Workflow, and Examples</a> - the parent guide that explains the design and analysis frameworks these exercises drill.</li>
<li><a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a> - practise regression-style <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">hypothesis testing</a> on the same hub format.</li>
<li><a class="auto-link" href="Sample-Size-Planning-in-R.html" title="Sample Size in R: Plan Your N the Right Way">Power Analysis in R</a> - go deeper on <code>pwr</code> formulas and <a class="auto-link" href="Power-by-Simulation-in-R.html" title="Power Analysis by Simulation in R">simulation-based power</a> for non-standard designs.</li>
<li><a href="EDA-Exercises-in-R.html">EDA Exercises in R</a> - sharpen the upstream skills you need before any experiment: data quality, slicing, and metric definitions.</li>
</ul>

{% endraw %}