---
title: "ANOVA Exercises in R: 15 One-Way and Two-Way Practice Problems"
description: "15 ANOVA R exercises with runnable solutions: one-way, two-way, interactions, Tukey HSD, Levene's, Welch's, effect size, contrasts, and assumption checks."
keywords: "ANOVA R exercises, ANOVA exercises in R, one-way ANOVA practice, two-way ANOVA R, Tukey HSD R, Welch's ANOVA, Levene's test R, eta squared R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "anova exercises|anova practice problems|anova exercises in r|one-way anova practice|two-way anova practice"
auto_link_case_sensitive: false
sidebar_title: "ANOVA Exercises (15)"
sidebar_order: "415"
fr_parent: "One-Way-ANOVA-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>ANOVA Exercises in R: 15 One-Way and Two-Way Practice Problems</h1>

<p class="lead">Fifteen ANOVA exercises that walk you from a single-factor <code>aov()</code> fit through two-way interactions, <a class="auto-link" href="One-Way-ANOVA-in-R.html" title="One-Way ANOVA in R: F-Test, Levene's Test, and Post-Hoc, Complete Walkthrough">Tukey HSD</a>, Levene's and Welch's tests, effect sizes, and custom contrasts. Each problem has a runnable code stub plus a hidden solution with explanation, so you can attempt first and verify second.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="40" data-exercises="15" data-xp="225"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(car)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. One-way ANOVA on a single grouping factor (3 problems)</h2>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-1-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Fit a one-way ANOVA on PlantGrowth weight by treatment group</h3>

<p class="exercise-task"><strong>Task:</strong> An agronomist running a small greenhouse experiment wants to know whether dry-weight yield differs across the three groups in the built-in <code>PlantGrowth</code> dataset (control, treatment 1, treatment 2). Fit a one-way ANOVA with <code>aov()</code> using <code>weight ~ group</code>, then save the fitted model object to <code>ex_1_1</code> and print its <code>summary()</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; group        2  3.766  1.8832   4.846 0.0159 *
#&gt; Residuals   27 10.492  0.3886
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Think about which model object compares a continuous response across several groups, and how a formula expresses "the response depends on the group".</p><p>Pass the formula <code>weight ~ group</code> and <code>data = PlantGrowth</code> to <code>aov()</code>, then assign the fitted model to <code>ex_1_1</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
summary(ex_1_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- aov(weight ~ group, data = PlantGrowth)
summary(ex_1_1)
#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; group        2  3.766  1.8832   4.846 0.0159 *
#&gt; Residuals   27 10.492  0.3886</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>aov()</code> is a thin wrapper around <code>lm()</code> whose <code>summary.aov</code> method prints the classical ANOVA table instead of a regression coefficient table. The F-statistic is the ratio of between-group mean square to within-group mean square; under the null of equal group means it follows an <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">F distribution</a> with (k-1, N-k) degrees of freedom. A p-value of 0.016 rejects equal means at the 5% level, but does not tell you which pair differs (that needs a post-hoc test like Tukey HSD).</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-1-2" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.2: Test whether iris sepal length differs across species</h3>

<p class="exercise-task"><strong>Task:</strong> A botany student is comparing the three species in the built-in <code>iris</code> dataset on <code>Sepal.Length</code>. Fit a one-way ANOVA with <code>aov(Sepal.Length ~ Species, data = iris)</code> and save the fitted model to <code>ex_1_2</code>. Use <code>summary()</code> to print the ANOVA table so you can read off the F value and the p-value for the species factor.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;              Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; Species       2  63.21  31.606   119.3 &lt;2e-16 ***
#&gt; Residuals   147  38.96   0.265
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A one-way ANOVA models a single continuous outcome against one grouping factor, here sepal length against the three species.</p><p>Call <code>aov()</code> with the formula <code>Sepal.Length ~ Species</code> and <code>data = iris</code>, storing the result in <code>ex_1_2</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
summary(ex_1_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- aov(Sepal.Length ~ Species, data = iris)
summary(ex_1_2)
#&gt;              Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; Species       2  63.21  31.606   119.3 &lt;2e-16 ***
#&gt; Residuals   147  38.96   0.265</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The F value of 119 is extremely large because between-species variance dominates within-species variance for sepal length: setosa is much shorter than virginica on average. With three species the numerator df is 2 and the denominator df is 150 minus 3 = 147. A p-value reported as <code>&lt;2e-16</code> is at the machine-precision floor; you can pull the exact number with <code>summary(ex_1_2)[[1]][[&quot;Pr(&gt;F)&quot;]][1]</code>. Always pair an "obviously significant" F test with effect size (eta-squared) and a plot, because significance alone says nothing about practical magnitude.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-1-3" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.3: One-way ANOVA on ToothGrowth length by supplement</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>ToothGrowth</code> dataset (guinea-pig odontoblast length under two vitamin C supplement types), fit a one-way ANOVA of <code>len</code> on <code>supp</code> with <code>aov(len ~ supp, data = ToothGrowth)</code> and save the fitted model to <code>ex_1_3</code>. Print the ANOVA table so you can decide whether supplement type alone explains the observed differences.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; supp         1  205.4   205.4   3.668 0.0604 .
#&gt; Residuals   58 3246.9    56.0
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>This is the same single-factor model again, with tooth length as the response and supplement type as the only grouping factor.</p><p>Use <code>aov(len ~ supp, data = ToothGrowth)</code> and assign the fitted model to <code>ex_1_3</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
summary(ex_1_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- aov(len ~ supp, data = ToothGrowth)
summary(ex_1_3)
#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)
#&gt; supp         1  205.4   205.4   3.668 0.0604 .
#&gt; Residuals   58 3246.9    56.0</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The single-factor model lumps all dose levels together, which inflates the residual sum of squares because dose is a real (and large) source of variance left unmodelled. That is why supplement looks only marginally significant here (p = 0.060) but jumps to p = 0.0004 once you add <code>dose</code> as a second factor in Exercise 3.1. Treat a borderline p-value from a one-way ANOVA as a hint that an important covariate may be missing from the right-hand side.</p>

</details>

</section>

<h2>Section 2. Reading the output and post-hoc comparisons (3 problems)</h2>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-2-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.1: Extract the F statistic and p-value as a named numeric vector</h3>

<p class="exercise-task"><strong>Task:</strong> A reporting analyst preparing a CSV summary of several ANOVA results needs the F statistic and the p-value pulled out of the model object as a named numeric vector. From <code>ex_1_1</code> (the PlantGrowth fit), extract the F value and the <code>Pr(&gt;F)</code> for the <code>group</code> row and save them as a named numeric vector <code>c(F = ..., p = ...)</code> to <code>ex_2_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;          F          p
#&gt; 4.84609 0.01591</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The ANOVA table lives inside the model's summary object; you need to reach into it and pull two numbers from the factor row.</p><p>Take <code>summary(ex_1_1)[[1]]</code>, index its <code>&quot;F value&quot;</code> and <code>&quot;Pr(&gt;F)&quot;</code> columns at row 1, and combine them with <code>c(F = ..., p = ...)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">tab &lt;- summary(ex_1_1)[[1]]
ex_2_1 &lt;- c(F = tab[[&quot;F value&quot;]][1], p = tab[[&quot;Pr(&gt;F)&quot;]][1])
round(ex_2_1, 5)
#&gt;          F          p
#&gt; 4.84609 0.01591</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>summary.aov</code> returns a list whose first element is a data frame with columns <code>Df</code>, <code>Sum Sq</code>, <code>Mean Sq</code>, <code>F value</code>, <code>Pr(&gt;F)</code>. The first row is the factor effect and the second row is the residual (which has no F or p). Indexing with <code>[[1]]</code> and then a column name gives a numeric vector you can subset. For programmatic pipelines, <code>broom::tidy(ex_1_1)</code> returns the same numbers as a tibble with stable column names and is friendlier than positional indexing.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-2-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: Run Tukey HSD on the PlantGrowth one-way ANOVA</h3>

<p class="exercise-task"><strong>Task:</strong> A reviewer wants to know which specific pairs of <code>PlantGrowth</code> groups differ, not just whether at least one pair differs. Run Tukey's Honest Significant Differences post-hoc on the model <code>ex_1_1</code> with <code>TukeyHSD()</code> and save the returned object to <code>ex_2_2</code>. Print it so the pairwise differences, <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence intervals</a>, and adjusted p-values are visible.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   Tukey multiple comparisons of means
#&gt;     95% family-wise confidence level
#&gt;
#&gt; Fit: aov(formula = weight ~ group, data = PlantGrowth)
#&gt;
#&gt; $group
#&gt;             diff        lwr       upr     p adj
#&gt; trt1-ctrl -0.371 -1.0622161 0.3202161 0.3908711
#&gt; trt2-ctrl  0.494 -0.1972161 1.1852161 0.1979960
#&gt; trt2-trt1  0.865  0.1737839 1.5562161 0.0120064</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Once the omnibus F test flags a difference, a post-hoc procedure tells you which specific pairs of groups actually differ.</p><p>Pass the fitted model <code>ex_1_1</code> to <code>TukeyHSD()</code> and assign the returned object to <code>ex_2_2</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- TukeyHSD(ex_1_1)
ex_2_2
#&gt;   Tukey multiple comparisons of means
#&gt;     95% family-wise confidence level
#&gt;
#&gt; Fit: aov(formula = weight ~ group, data = PlantGrowth)
#&gt;
#&gt; $group
#&gt;             diff        lwr       upr     p adj
#&gt; trt1-ctrl -0.371 -1.0622161 0.3202161 0.3908711
#&gt; trt2-ctrl  0.494 -0.1972161 1.1852161 0.1979960
#&gt; trt2-trt1  0.865  0.1737839 1.5562161 0.0120064</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Tukey HSD inverts the studentized range distribution to control the <a class="auto-link" href="Multiple-Comparisons-in-R.html" title="Multiple Testing in R: Control False Discoveries Without Losing All Your Power">family-wise error rate</a> at 5%, so the three pairwise p-values are already adjusted (you do not apply Bonferroni on top). The only significant pair is trt2 vs trt1; both treatments versus control are non-significant. This is a common pattern with three-arm trials: the two treatments together "move the needle" enough to flag the omnibus F test, but only the most extreme pair survives a controlled pairwise comparison.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-2-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.3: Pairwise t-tests with Bonferroni correction on PlantGrowth</h3>

<p class="exercise-task"><strong>Task:</strong> A statistician wants to compare Tukey HSD against the more conservative Bonferroni adjustment as a sanity check. Run <code>pairwise.t.test()</code> on <code>PlantGrowth$weight</code> grouped by <code>PlantGrowth$group</code> with <code>p.adjust.method = &quot;bonferroni&quot;</code> and save the returned object to <code>ex_2_3</code>. Print the object so the adjusted-p matrix is shown.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   Pairwise comparisons using t tests with pooled SD
#&gt;
#&gt; data:  PlantGrowth$weight and PlantGrowth$group
#&gt;
#&gt;      ctrl  trt1
#&gt; trt1 0.582 -
#&gt; trt2 0.263 0.013
#&gt;
#&gt; P value adjustment method: bonferroni</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Compare every pair of groups with multiple t-tests, but adjust the p-values so the family-wise error stays controlled.</p><p>Call <code>pairwise.t.test()</code> on <code>PlantGrowth$weight</code> and <code>PlantGrowth$group</code> with <code>p.adjust.method = &quot;bonferroni&quot;</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- pairwise.t.test(
  PlantGrowth$weight, PlantGrowth$group,
  p.adjust.method = &quot;bonferroni&quot;
)
ex_2_3
#&gt;   Pairwise comparisons using t tests with pooled SD
#&gt;
#&gt; data:  PlantGrowth$weight and PlantGrowth$group
#&gt;
#&gt;      ctrl  trt1
#&gt; trt1 0.582 -
#&gt; trt2 0.263 0.013
#&gt;
#&gt; P value adjustment method: bonferroni</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Bonferroni multiplies each raw p-value by the number of comparisons (here 3) and caps at 1. It is the most conservative of the common corrections, which is why the trt2 vs trt1 adjusted p of 0.013 is slightly larger than Tukey's 0.012. With more comparisons (six groups: 15 pairs) Bonferroni quickly becomes underpowered; Tukey HSD or Holm are usually preferable for many comparisons. Use the pooled-SD variant when you trust the equal-variance assumption from <a class="auto-link" href="Normality-and-Variance-Tests-in-R.html" title="Test Normality and Equal Variance in R: What the Tests Can and Can't Tell You">Levene's test</a>; otherwise pass <code>pool.sd = FALSE</code> for a Welch-style version.</p>

</details>

</section>

<h2>Section 3. Two-way ANOVA and interaction effects (3 problems)</h2>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-3-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.1: Additive two-way ANOVA on ToothGrowth supp + dose</h3>

<p class="exercise-task"><strong>Task:</strong> Reanalyse <code>ToothGrowth</code> with both factors in the model: supplement type (<code>supp</code>) and dose level coerced to a factor with <code>factor(dose)</code>. Fit the additive (no-interaction) two-way model <code>aov(len ~ supp + factor(dose), data = ToothGrowth)</code> and save the result to <code>ex_3_1</code>. Print the ANOVA table to see whether supplement still looks marginal after dose is controlled for.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;              Df Sum Sq Mean Sq F value   Pr(&gt;F)
#&gt; supp          1  205.4   205.4   14.02  0.000429 ***
#&gt; factor(dose)  2 2426.4  1213.2   82.81  &lt; 2e-16 ***
#&gt; Residuals    56  820.4    14.7
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A two-way additive model puts a second grouping factor on the right side without letting the two factors interact.</p><p>Use <code>aov()</code> with the formula <code>len ~ supp + factor(dose)</code> and <code>data = ToothGrowth</code>, wrapping dose in <code>factor()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
summary(ex_3_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- aov(len ~ supp + factor(dose), data = ToothGrowth)
summary(ex_3_1)
#&gt;              Df Sum Sq Mean Sq F value   Pr(&gt;F)
#&gt; supp          1  205.4   205.4   14.02  0.000429 ***
#&gt; factor(dose)  2 2426.4  1213.2   82.81  &lt; 2e-16 ***
#&gt; Residuals    56  820.4    14.7</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Once dose is added to the right-hand side, the residual mean square drops from 56 (one-way) to 14.7 because most of that variance was really dose, not noise. Supplement now has an F of 14 and a p of 0.0004 instead of being marginal: a clean illustration of why omitting a strong covariate inflates within-group variance and hides real effects. Wrap dose in <code>factor()</code> so it is treated as three discrete levels (0.5, 1, 2) with two degrees of freedom; leaving it numeric would force a linear trend with only one degree of freedom.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-3-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.2: Full factorial supp * dose with interaction term</h3>

<p class="exercise-task"><strong>Task:</strong> Extend the model from Exercise 3.1 to allow the supplement effect to differ across doses. Fit the full factorial <code>aov(len ~ supp * factor(dose), data = ToothGrowth)</code> and save it to <code>ex_3_2</code>. Print the ANOVA table; the new row <code>supp:factor(dose)</code> is the interaction test that asks whether the OJ-vs-VC gap depends on dose.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;                    Df Sum Sq Mean Sq F value   Pr(&gt;F)
#&gt; supp                1  205.4   205.4   15.57  0.000231 ***
#&gt; factor(dose)        2 2426.4  1213.2   92.00  &lt; 2e-16 ***
#&gt; supp:factor(dose)   2  108.3    54.2    4.11  0.021860 *
#&gt; Residuals          54  712.1    13.2
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>To let one factor's effect change across the levels of another, the model must include their interaction, not just their separate effects.</p><p>Replace the <code>+</code> with <code>*</code> in the formula, fitting <code>len ~ supp * factor(dose)</code> with <code>aov()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
summary(ex_3_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- aov(len ~ supp * factor(dose), data = ToothGrowth)
summary(ex_3_2)
#&gt;                    Df Sum Sq Mean Sq F value   Pr(&gt;F)
#&gt; supp                1  205.4   205.4   15.57  0.000231 ***
#&gt; factor(dose)        2 2426.4  1213.2   92.00  &lt; 2e-16 ***
#&gt; supp:factor(dose)   2  108.3    54.2    4.11  0.021860 *
#&gt; Residuals          54  712.1    13.2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The interaction row is significant (p = 0.022), so the supplement effect is NOT the same at every dose. From the cell means you will see OJ outperforms VC at 0.5 and 1 mg, but the two are nearly tied at 2 mg. When the interaction is significant, you should interpret main effects with care or pivot to simple-effect tests within each dose level rather than reporting one aggregate "supp effect". <code>*</code> expands to all main effects plus the interaction; <code>(supp + factor(dose))^2</code> would give the same model for two factors.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-3-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.3: Build a 6-row cell means table for supp x dose</h3>

<p class="exercise-task"><strong>Task:</strong> Before interpreting the interaction you ran in Exercise 3.2, <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summarise</a> the underlying cell means. Use <code>aggregate(len ~ supp + factor(dose), data = ToothGrowth, FUN = mean)</code> to build a 6-row table (one row per supp x dose cell) and save it to <code>ex_3_3</code>. The table should have three columns: <code>supp</code>, <code>factor(dose)</code>, and <code>len</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   supp factor(dose)    len
#&gt; 1   OJ          0.5 13.230
#&gt; 2   VC          0.5  7.980
#&gt; 3   OJ          1   22.700
#&gt; 4   VC          1   16.770
#&gt; 5   OJ          2   26.060
#&gt; 6   VC          2   26.140</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>You want the average response within each combination of the two factors, producing one number per supp-by-dose cell.</p><p>Call <code>aggregate()</code> with <code>len ~ supp + factor(dose)</code>, <code>data = ToothGrowth</code>, and <code>FUN = mean</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- aggregate(
  len ~ supp + factor(dose),
  data = ToothGrowth,
  FUN = mean
)
ex_3_3
#&gt;   supp factor(dose)    len
#&gt; 1   OJ          0.5 13.230
#&gt; 2   VC          0.5  7.980
#&gt; 3   OJ          1   22.700
#&gt; 4   VC          1   16.770
#&gt; 5   OJ          2   26.060
#&gt; 6   VC          2   26.140</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The OJ-minus-VC gap is +5.25 at 0.5 mg, +5.93 at 1 mg, but only -0.08 at 2 mg. That collapsing gap is exactly the interaction the ANOVA flagged. Cell means tables are the most important diagnostic before reading any interaction p-value, because a "significant interaction" can be ordinal (lines stay in the same rank order) or disordinal (lines cross), and the interpretation differs. For tidyverse users, the equivalent is <code>ToothGrowth |&gt; group_by(supp, dose) |&gt; summarise(mean = mean(len))</code>.</p>

</details>

</section>

<h2>Section 4. Assumption checks before you trust the F test (3 problems)</h2>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-4-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.1: Levene's test for homogeneity of variance on PlantGrowth</h3>

<p class="exercise-task"><strong>Task:</strong> Before reporting the one-way ANOVA F test from Exercise 1.1, an auditor asks for the standard equal-variance check. Use <code>leveneTest(weight ~ group, data = PlantGrowth)</code> from the <code>car</code> package and save the returned object to <code>ex_4_1</code>. Print it; a non-significant p means the equal-variance assumption is acceptable and the classical F test is valid.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Levene's Test for Homogeneity of Variance (center = median)
#&gt;       Df F value Pr(&gt;F)
#&gt; group  2  1.1192 0.3412
#&gt;       27</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Before trusting the F test, check whether the groups have roughly equal spread around their centers.</p><p>Use <code>leveneTest()</code> from the <code>car</code> package with <code>weight ~ group</code> and <code>data = PlantGrowth</code>, assigning the result to <code>ex_4_1</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- leveneTest(weight ~ group, data = PlantGrowth)
ex_4_1
#&gt; Levene's Test for Homogeneity of Variance (center = median)
#&gt;       Df F value Pr(&gt;F)
#&gt; group  2  1.1192 0.3412
#&gt;       27</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Levene's test runs a one-way ANOVA on the absolute deviations from each group's center (median by default, which is the robust Brown-Forsythe variant). A non-significant result (p = 0.34) means there is not enough evidence to reject equal variances; classical <code>aov()</code> is fine. If Levene's were significant you would either transform <code>weight</code> (often <code>log()</code>), fit a Welch-style ANOVA via <code>oneway.test(..., var.equal = FALSE)</code>, or move to a non-parametric test like <a class="auto-link" href="Wilcoxon-Mann-Whitney-and-Kruskal-Wallis-in-R.html" title="Wilcoxon, Mann-Whitney, and Kruskal-Wallis in R: Non-Parametric When Normality Fails">Kruskal-Wallis</a>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-4-2" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.2: Shapiro-Wilk normality on the ANOVA residuals</h3>

<p class="exercise-task"><strong>Task:</strong> The classical ANOVA F test assumes the residuals are approximately normal. Pull the residuals from <code>ex_1_1</code> with <code>residuals()</code>, pass them to <code>shapiro.test()</code>, and save the htest object to <code>ex_4_2</code>. Print it; a non-significant Shapiro p-value means you cannot reject the normality assumption from this sample size.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   Shapiro-Wilk normality test
#&gt;
#&gt; data:  residuals(ex_1_1)
#&gt; W = 0.96607, p-value = 0.4379</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The normality assumption concerns the model's leftover errors, so extract those from the fitted model before testing anything.</p><p>Feed <code>residuals(ex_1_1)</code> into <code>shapiro.test()</code> and store the htest object in <code>ex_4_2</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- shapiro.test(residuals(ex_1_1))
ex_4_2
#&gt;   Shapiro-Wilk normality test
#&gt;
#&gt; data:  residuals(ex_1_1)
#&gt; W = 0.96607, p-value = 0.4379</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Test the model's residuals, not the raw response, because ANOVA assumes Normal(0, sigma^2) errors conditional on the predictors. With n = 30 the Shapiro test has modest power, so a non-significant p (0.44) is weak evidence of normality, not proof; always pair it with a QQ-plot <code>plot(ex_1_1, which = 2)</code>. ANOVA is also robust to mild non-normality when sample sizes are equal across groups, so a borderline Shapiro result on balanced data rarely overturns the substantive conclusion.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-4-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 4.3: Welch's ANOVA for unequal variances</h3>

<p class="exercise-task"><strong>Task:</strong> Suppose Levene's test had flagged unequal variances and you need a Welch-corrected ANOVA. Run <code>oneway.test(weight ~ group, data = PlantGrowth, var.equal = FALSE)</code> and save the htest object to <code>ex_4_3</code>. Print it; the Welch test uses Satterthwaite-style fractional denominator degrees of freedom and is robust to heteroscedastic groups.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   One-way analysis of means (not assuming equal variances)
#&gt;
#&gt; data:  weight and group
#&gt; F = 5.181, num df = 2.000, denom df = 17.128, p-value = 0.01739</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>When variances differ across groups, you need a version of the ANOVA that does not assume equal spread.</p><p>Call <code>oneway.test()</code> with <code>weight ~ group</code>, <code>data = PlantGrowth</code>, and <code>var.equal = FALSE</code>, saving the result to <code>ex_4_3</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- oneway.test(weight ~ group, data = PlantGrowth, var.equal = FALSE)
ex_4_3
#&gt;   One-way analysis of means (not assuming equal variances)
#&gt;
#&gt; data:  weight and group
#&gt; F = 5.181, num df = 2.000, denom df = 17.128, p-value = 0.01739</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <a class="auto-link" href="Welchs-ANOVA-in-R.html" title="Welch's ANOVA in R: When Group Variances Are Unequal">Welch's ANOVA</a> is the F-test analogue of <a class="auto-link" href="t-Tests-in-R.html" title="t-Tests in R: Every Variant With the Decision Rule for Choosing Between Them">Welch's t-test</a>: it weights each group by its own variance and shrinks the denominator degrees of freedom so the test stays calibrated when variances differ. Notice the denom df here is a non-integer 17.13, smaller than the classical 27, which costs some power but buys robustness. For pairwise follow-ups under unequal variances, use <code>pairwise.t.test(..., pool.sd = FALSE)</code>; the Games-Howell post-hoc (from package <code>rstatix</code> or <code>userfriendlyscience</code>) is the Welch-style analogue of Tukey HSD.</p>

</details>

</section>

<h2>Section 5. Effect size, custom contrasts, and applied workflow (3 problems)</h2>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-5-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.1: Compute eta-squared by hand from the ANOVA table</h3>

<p class="exercise-task"><strong>Task:</strong> A reviewer wants the effect size alongside the F test from Exercise 1.1. Compute eta-squared as the group sum of squares divided by the total sum of squares (group + residual) from <code>summary(ex_1_1)</code>. Save the single numeric value to <code>ex_5_1</code>, rounded to three decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.264</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Effect size here is the share of total variation explained by the factor, so you need the sums of squares from the ANOVA table.</p><p>Pull the <code>&quot;Sum Sq&quot;</code> column from <code>summary(ex_1_1)[[1]]</code>, divide the group value by the group-plus-residual total, and <code>round(..., 3)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">tab &lt;- summary(ex_1_1)[[1]]
ss_group &lt;- tab[[&quot;Sum Sq&quot;]][1]
ss_resid &lt;- tab[[&quot;Sum Sq&quot;]][2]
ex_5_1 &lt;- round(ss_group / (ss_group + ss_resid), 3)
ex_5_1
#&gt; [1] 0.264</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Eta-squared is the proportion of total variance in the outcome attributable to the factor, the ANOVA analogue of R-squared. Cohen's rough benchmarks call 0.01 small, 0.06 medium, and 0.14 large; the PlantGrowth effect of 0.26 is large. Eta-squared is upward-biased for small samples; partial eta-squared and <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">omega-squared</a> correct for that and are reported by <code>effectsize::eta_squared()</code> and <code>effectsize::omega_squared()</code>. Always report an effect size next to the F value because significance scales with sample size while effect size does not.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-5-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.2: Custom contrast: control versus the average of two treatments</h3>

<p class="exercise-task"><strong>Task:</strong> Rather than three <a class="auto-link" href="Post-Hoc-Tests-After-ANOVA.html" title="ANOVA Post-Hoc Tests in R: Tukey, Bonferroni, and Scheffé, Clear Decision Rules">pairwise comparisons</a>, you only care about one scientific question: does the average of the two treatments differ from control? Set up a custom contrast on <code>PlantGrowth$group</code> that maps <code>ctrl</code> to +2 and each treatment to -1, refit with <code>lm()</code>, and save the coefficient table (from <code>summary(...)$coefficients</code>) to <code>ex_5_2</code>. Print <code>ex_5_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;                Estimate Std. Error   t value  Pr(&gt;|t|)
#&gt; (Intercept)   5.0730000  0.1138682 44.551103 1.105e-26
#&gt; group1       -0.0615000  0.1610458 -0.381881   0.70554
#&gt; group2       -0.6180000  0.2789274 -2.215624   0.03524</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>With the contrasts already assigned to the factor and the model refitted, the answer is simply the coefficient table the summary produces.</p><p>Assign <code>summary(fit)$coefficients</code> to <code>ex_5_2</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pg &lt;- PlantGrowth
contrasts(pg$group) &lt;- cbind(
  ctrl_vs_trts = c(2, -1, -1),
  trt1_vs_trt2 = c(0, 1, -1)
)
fit &lt;- lm(weight ~ group, data = pg)
ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pg &lt;- PlantGrowth
contrasts(pg$group) &lt;- cbind(
  ctrl_vs_trts = c(2, -1, -1),
  trt1_vs_trt2 = c(0, 1, -1)
)
fit &lt;- lm(weight ~ group, data = pg)
ex_5_2 &lt;- summary(fit)$coefficients
ex_5_2
#&gt;                Estimate Std. Error   t value  Pr(&gt;|t|)
#&gt; (Intercept)   5.0730000  0.1138682 44.551103 1.105e-26
#&gt; group1       -0.0615000  0.1610458 -0.381881   0.70554
#&gt; group2       -0.6180000  0.2789274 -2.215624   0.03524</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Assigning a contrast matrix to a factor changes what the lm coefficients estimate without refitting any new data. The two columns must be orthogonal and sum to zero within each column; <code>c(2, -1, -1)</code> and <code>c(0, 1, -1)</code> qualify. <code>group1</code> is one-third of the ctrl-versus-mean-of-treatments contrast (the +2/-1/-1 coding scales it), and its non-significant p (0.71) says the two treatments together do NOT differ from control on average. <code>group2</code> tests trt1 versus trt2 and is significant (p = 0.035), matching the Tukey HSD finding from Exercise 2.2. Custom contrasts let you test one targeted scientific question per degree of freedom instead of all pairs.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ANOVA-Exercises-in-R-ex-5-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.3: Full diagnostic workflow: ANOVA vs Welch vs Kruskal-Wallis</h3>

<p class="exercise-task"><strong>Task:</strong> Put the whole flow together: for <code>PlantGrowth weight ~ group</code>, run Levene's test, Shapiro on the aov residuals, classical ANOVA, Welch's ANOVA, and Kruskal-Wallis. Extract the p-values from each and assemble them into a named numeric vector <code>c(levene_p, shapiro_p, aov_p, welch_p, kruskal_p)</code> saved to <code>ex_5_3</code>. Round to four decimals and print.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; levene_p shapiro_p     aov_p   welch_p kruskal_p
#&gt;   0.3412    0.4379    0.0159    0.0174    0.0184</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Run each test separately, then reach into each result object for its single p-value and label the five numbers in one vector.</p><p>Combine the p-values from <code>leveneTest()</code>, <code>shapiro.test()</code>, <code>summary(ex_1_1)[[1]]</code>, <code>oneway.test()</code>, and <code>kruskal.test()</code> with <code>c()</code>, then <code>round(..., 4)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">lev &lt;- leveneTest(weight ~ group, data = PlantGrowth)
sha &lt;- shapiro.test(residuals(ex_1_1))
av  &lt;- summary(ex_1_1)[[1]]
wel &lt;- oneway.test(weight ~ group, data = PlantGrowth, var.equal = FALSE)
kru &lt;- kruskal.test(weight ~ group, data = PlantGrowth)

ex_5_3 &lt;- round(c(
  levene_p  = lev[[&quot;Pr(&gt;F)&quot;]][1],
  shapiro_p = sha$p.value,
  aov_p     = av[[&quot;Pr(&gt;F)&quot;]][1],
  welch_p   = wel$p.value,
  kruskal_p = kru$p.value
), 4)
ex_5_3
#&gt; levene_p shapiro_p     aov_p   welch_p kruskal_p
#&gt;   0.3412    0.4379    0.0159    0.0174    0.0184</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> All three group-difference tests (classical, Welch, Kruskal-Wallis) agree on the conclusion at the 5% level, which is the reassuring case: the decision is robust to choice of test. When tests disagree, prefer the one whose assumptions are satisfied: classical F if Levene and Shapiro both pass, Welch's F if Levene flags unequal variances, Kruskal-Wallis if Shapiro flags clearly non-normal residuals (especially with small or unbalanced groups). Reporting all three is overkill for a paper, but during analysis it is a useful sensitivity check.</p>

</details>

</section>

<h2>What to do next</h2>

<p>You have rehearsed every step of a one-way and <a class="auto-link" href="Two-Way-ANOVA-in-R.html" title="Two-Way ANOVA in R: Main Effects, Interactions, and Interaction Plots Interpreted">two-way ANOVA</a> workflow in R. To go deeper:</p>

<ul>

<li>Review the <a href="One-Way-ANOVA-in-R.html">One-Way ANOVA in R</a> tutorial for a guided walk-through of the math and assumptions.</li>

<li>Practise the related <code>lm</code> workflow with <a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>, since <code>aov()</code> is just <code>lm()</code> with a different summary method.</li>

<li>For tests where the response is a count or proportion rather than a continuous outcome, switch over to <a href="Chi-Squared-Test-Exercises-in-R.html">Chi-Squared Test Exercises in R</a>.</li>

<li>Compare ANOVA against its two-group ancestor in <a href="t-test-Exercises-in-R.html">t-test Exercises in R</a>.</li>

</ul>

{% endraw %}