---
title: "Binomial Distribution Exercises in R: 17 Practice Problems"
description: "Practice 17 binomial distribution exercises in R covering dbinom, pbinom, qbinom, rbinom and binom.test with full runnable solutions and explanations."
keywords: "binomial distribution exercises in R, dbinom exercises, pbinom practice, qbinom problems, rbinom simulation, binom.test R, binomial probability R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "binomial distribution exercises|dbinom exercises|pbinom practice|qbinom exercises|rbinom simulation|binom.test exercises"
auto_link_case_sensitive: false
sidebar_title: "Binomial Distribution Exercises"
sidebar_order: "305"
fr_parent: "Binomial-and-Poisson-Distributions-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>Binomial Distribution Exercises in R: 17 Practice Problems</h1>
<p class="lead">Seventeen runnable <a class="auto-link" href="Binomial-and-Poisson-Distributions-in-R.html" title="Binomial vs Poisson in R: Understand When Each Distribution Fits Your Counts">binomial distribution</a> exercises in R, grouped by the four core functions (<code>dbinom</code>, <code>pbinom</code>, <code>qbinom</code>, <code>rbinom</code>) plus <code>binom.test</code> inference. Each problem ships with a hidden solution and a written explanation so you can self-check the moment you finish coding.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="17" data-time="35" data-xp="255"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(ggplot2)
set.seed(2026)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Exact probabilities with dbinom (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Probability of exactly 5 heads in 10 fair flips</h3>
<p class="exercise-task"><strong>Task:</strong> A friend hands you a coin claimed to be fair and asks for the probability of getting exactly 5 heads in 10 flips. Use <code>dbinom()</code> with <code>size = 10</code> and <code>prob = 0.5</code> to compute $P(X = 5)$. Save the scalar to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.2460938</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>The phrase "exactly 5" points to the mass at a single specific count, not the chance of a whole range of counts.</p><p>Reach for the probability-mass function: pass the count 5 as the first argument, then size = 10 and prob = 0.5.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- dbinom(5, size = 10, prob = 0.5)
ex_1_1
#&gt; [1] 0.2460938</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>dbinom(x, size, prob)</code> returns the probability mass at exactly <code>x</code> successes. The first argument is the count you want a probability for, not a vector of trial outcomes. For a fair coin the answer is $\binom{10}{5} \cdot 0.5^{10} = 252 / 1024 \approx 0.2461$. A common mistake is using <code>pbinom()</code> here, which would return the cumulative probability $P(X \le 5)$ instead of the exact-equality mass.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Quality control: exactly 2 defective widgets in a batch of 50</h3>
<p class="exercise-task"><strong>Task:</strong> A quality engineer at a parts supplier samples 50 widgets from a production line with a 3 percent defect rate. Compute the probability that exactly 2 widgets in the sample are defective using <code>dbinom()</code>. Save the result to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.2555182</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A 3 percent defect rate is the per-trial success probability, and you want the chance of one exact defective count in the batch.</p><p>Use dbinom() with x = 2, size = 50, and prob = 0.03.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- dbinom(2, size = 50, prob = 0.03)
ex_1_2
#&gt; [1] 0.2555182</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Every trial is one widget, success means defective, and the trials are assumed independent with constant probability 0.03, which is the textbook binomial setup. Around 25.5 percent is the single most likely count near the mean $np = 1.5$. If the defect rate were estimated from a small pilot rather than known, you would want a Beta-binomial or a <a class="auto-link" href="Bayesian-Statistics-in-R.html" title="Bayesian Statistics in R: Build Genuine Intuition Before Opening Stan or brms">credible interval</a> on $p$ before treating the answer as exact.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-1-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 1.3: Plot the PMF of Binomial(20, 0.3) with a bar chart</h3>
<p class="exercise-task"><strong>Task:</strong> Build a bar chart showing $P(X = k)$ for $k = 0, 1, \ldots, 20$ under <code>Binomial(size = 20, prob = 0.3)</code>. Use <code>ggplot2</code> with <code>geom_col()</code>, label the axes, and save the ggplot object to <code>ex_1_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A ggplot bar chart with k on the x-axis (0..20) and dbinom(k, 20, 0.3) on the y-axis.
# Peak bar sits around k=6 (the mean np=6). Tails are visibly skinny beyond k=12.
# Axes: x = "Successes (k)", y = "P(X = k)".</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Ask for the probability at every possible success count at once, so you have a full table of point probabilities to draw as bars.</p><p>Build a data frame with k = 0:20 and dbinom(k, size = 20, prob = 0.3), then plot it with <a class="auto-link" href="ggplot2-Tutorial-With-R.html" title="ggplot2 Short Tutorial">ggplot()</a> and <a class="auto-link" href="ggplot2-Bar-Charts.html" title="ggplot2 Bar Charts: geom_bar(), geom_col(), Stacked, Dodged and Ordered">geom_col()</a>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">k  &lt;- 0:20
pmf &lt;- data.frame(k = k, p = dbinom(k, size = 20, prob = 0.3))

ex_1_3 &lt;- ggplot(pmf, aes(x = k, y = p)) +
  geom_col(fill = "#3a7bd5") +
  labs(x = "Successes (k)", y = "P(X = k)",
       title = "PMF of Binomial(20, 0.3)") +
  theme_minimal()
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Passing a vector <code>0:20</code> to <code>dbinom()</code> vectorizes the call and returns 21 probabilities in one shot, which is the cleanest way to build a PMF table for plotting. The peak at $k = 6$ matches $np$, the mean of the distribution. For larger <code>size</code> the bars start to look bell-shaped, foreshadowing the <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">normal approximation</a> you will see in Section 4.</p>
</details>
</section>
<h2>Section 2. Cumulative and tail probabilities with pbinom (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: At most 2 heads in 10 fair flips</h3>
<p class="exercise-task"><strong>Task:</strong> Continuing with the fair-coin scenario, compute the probability of getting at most 2 heads in 10 flips. Use <code>pbinom()</code> to evaluate $P(X \le 2)$ with <code>size = 10</code> and <code>prob = 0.5</code>. Save the scalar to <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.0546875</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>"At most 2" is a cumulative range running from 0 up through 2, not the mass at a single count.</p><p>Use pbinom() with q = 2, size = 10, prob = 0.5; the default lower tail already gives P(X &lt;= q).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- pbinom(2, size = 10, prob = 0.5)
ex_2_1
#&gt; [1] 0.0546875</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>pbinom(q, size, prob)</code> returns the lower-tail probability $P(X \le q)$ by default, so passing <code>q = 2</code> includes the masses at 0, 1, and 2. You could verify by hand with <code>sum(dbinom(0:2, 10, 0.5))</code>, which returns the same value. Many beginners reach for <code>dbinom(2, ...)</code> here and get the at-exactly-2 mass instead of the at-most-2 cumulative.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Survival probability: 8 or more successes out of 20</h3>
<p class="exercise-task"><strong>Task:</strong> A clinical trial enrolls 20 patients in a single arm, each with response probability 0.30. Compute the probability that 8 or more patients respond using <code>pbinom()</code> with <code>lower.tail = FALSE</code>. Save the upper-tail probability to <code>ex_2_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.2277282</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>"8 or more" is an upper-tail range, and because the distribution is discrete you must watch which boundary count gets included.</p><p>Use pbinom() with lower.tail = FALSE and pass q = 7, so P(X &gt; 7) captures P(X &gt;= 8).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- pbinom(7, size = 20, prob = 0.3, lower.tail = FALSE)
ex_2_2
#&gt; [1] 0.2277282</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The trick is the offset: <code>pbinom(q, ..., lower.tail = FALSE)</code> returns $P(X &gt; q)$, strictly greater than, so to capture $P(X \ge 8)$ you pass <code>q = 7</code>. Equivalently you can write <code>1 - pbinom(7, 20, 0.3)</code>, but the <code>lower.tail = FALSE</code> path is numerically more stable for probabilities near 1 because it avoids <code>1 - x</code> cancellation when <code>x</code> is tiny.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Email marketing: open rate between 40 and 60 on 100 sends</h3>
<p class="exercise-task"><strong>Task:</strong> A growth team blasts 100 emails with a historical open rate of 0.5 and wants the probability that the number opened lies between 40 and 60 inclusive. Use the difference of two <code>pbinom()</code> calls to compute $P(40 \le X \le 60)$. Save the interval probability to <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.9647998</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>An inclusive between-range is the cumulative probability up to the top bound minus everything strictly below the bottom bound.</p><p>Subtract two pbinom() calls: pbinom(60, 100, 0.5) minus pbinom(39, 100, 0.5).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- pbinom(60, 100, 0.5) - pbinom(39, 100, 0.5)
ex_2_3
#&gt; [1] 0.9647998</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Inclusive interval probabilities use a discrete-aware offset: $<a class="auto-link" href="Conditional-Probability-in-R.html" title="Conditional Probability in R: P(A|B), Independence, and Bayes — With Real Examples">P(a</a> \le X \le b) = P(X \le b) - P(X \le a - 1)$. Passing 39 instead of 40 is the most common mistake here. The answer roughly 96.5 percent is close to but not exactly the 95 percent you would read off a continuous normal approximation, which is a reminder that the normal CDF is a smoothing of this <a class="auto-link" href="ggplot2-geom_step-in-R.html" title="ggplot2 geom_step() in R: Step Function Lines">step function</a>.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-2-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.4: Recompute pbinom by summing dbinom</h3>
<p class="exercise-task"><strong>Task:</strong> Verify your understanding of the binomial CDF by recomputing $P(X \le 5)$ for <code>Binomial(12, 0.3)</code> two ways: with <code>pbinom()</code>, and by summing <code>dbinom()</code> over $k = 0, 1, \ldots, 5$. Save both results in a named numeric vector with elements <code>cdf</code> and <code>pmf_sum</code> to <code>ex_2_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>      cdf   pmf_sum 
0.8821513 0.8821513
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The cumulative probability is simply the <a class="auto-link" href="purrr-accumulate-in-R.html" title="purrr accumulate() in R: Running Reductions Over a List">running total</a> of the individual point probabilities up to that count.</p><p>Combine pbinom(5, size = 12, prob = 0.3) with sum(dbinom(0:5, size = 12, prob = 0.3)) inside c(cdf = ..., pmf_sum = ...).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_4 &lt;- # your code here
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_4 &lt;- c(
  cdf     = pbinom(5, size = 12, prob = 0.3),
  pmf_sum = sum(dbinom(0:5, size = 12, prob = 0.3))
)
ex_2_4
#&gt;      cdf  pmf_sum
#&gt; 0.882131 0.882131</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The CDF is defined as the cumulative sum of the PMF, so the two values must agree to floating-point precision. This identity is the reason <code>pbinom()</code> and <code>sum(dbinom(...))</code> are interchangeable for small <code>size</code>, but <code>pbinom()</code> is preferred for large <code>size</code> because R uses a stable algorithm rather than summing many tiny floats. Exercises like this one are also useful when sanity-checking custom probability code against the built-in family.</p>
</details>
</section>
<h2>Section 3. Quantiles and prediction with qbinom (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Find the 95th percentile of Binomial(100, 0.5)</h3>
<p class="exercise-task"><strong>Task:</strong> Use <code>qbinom()</code> to find the smallest integer $k$ such that $P(X \le k) \ge 0.95$ when $X \sim \text{Binomial}(100, 0.5)$. Save this critical value to <code>ex_3_1</code> and verify it returns a numeric value.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 58
#&gt; [1] "numeric"</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You want the smallest count whose cumulative probability reaches a target level - the inverse direction of a cumulative lookup.</p><p>Use qbinom() with p = 0.95, size = 100, prob = 0.5.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1
class(ex_3_1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- qbinom(0.95, size = 100, prob = 0.5)
ex_3_1
#&gt; [1] 58
class(ex_3_1)
#&gt; [1] "numeric"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>qbinom(p, ...)</code> returns the smallest integer $k$ with cumulative probability at least <code>p</code>, so it is the discrete inverse of <code>pbinom()</code>. The answer 58 says that in 100 fair flips you would expect to see 58 or fewer heads at least 95 percent of the time. A common confusion is to expect the normal approximation $\mu + 1.645\sigma = 58.2$ to round to 58 exactly, which it does here but does not always.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Build a 95 percent prediction interval for daily conversions</h3>
<p class="exercise-task"><strong>Task:</strong> A site averages 2000 visitors per day with a 5 percent conversion rate. The analytics lead wants a 95 percent prediction interval for the number of daily conversions. Use <code>qbinom()</code> at probabilities 0.025 and 0.975 to compute the lower and upper bounds. Save them as a length-2 numeric vector with names <code>lower</code> and <code>upper</code> to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; lower upper
#&gt;    81   120</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A central 95 percent interval is bounded by the two quantiles that leave 2.5 percent of probability in each tail.</p><p>Call qbinom() twice, at p = 0.025 and p = 0.975, with size = 2000 and prob = 0.05, naming the results lower and upper.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- c(
  lower = qbinom(0.025, size = 2000, prob = 0.05),
  upper = qbinom(0.975, size = 2000, prob = 0.05)
)
ex_3_2
#&gt; lower upper
#&gt;    81   120</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> This is a prediction interval, not a <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence interval</a>. It says where future daily conversion counts should fall under the assumed model, holding <code>prob = 0.05</code> fixed. A confidence interval would instead quantify uncertainty about <code>prob</code> itself. Reviewers sometimes flag <a class="auto-link" href="Prediction-Intervals-in-R.html" title="Prediction Intervals in R: Quantify Forecast Uncertainty">prediction intervals</a> that are too narrow because the analyst forgot to account for parameter uncertainty, especially when <code>prob</code> was estimated from a small sample.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Compare qbinom to the empirical 0.9 quantile of rbinom</h3>
<p class="exercise-task"><strong>Task:</strong> Draw 50000 samples from <code>Binomial(40, 0.25)</code> with <code>rbinom()</code>, then compute the 0.9 sample quantile and compare it with <code>qbinom(0.9, 40, 0.25)</code>. Save both numbers in a named vector with elements <code>theoretical</code> and <code>empirical</code> to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; theoretical   empirical
#&gt;          14          14</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Compare the count predicted by theory against the same percentile read off a large simulated sample.</p><p>Generate draws with rbinom(50000, size = 40, prob = 0.25), then pair qbinom(0.9, 40, 0.25) with quantile(samp, 0.9, type = 1).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">samp &lt;- rbinom(50000, size = 40, prob = 0.25)
ex_3_3 &lt;- c(
  theoretical = qbinom(0.9, 40, 0.25),
  empirical   = unname(quantile(samp, 0.9, type = 1))
)
ex_3_3
#&gt; theoretical   empirical
#&gt;          14          14</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Empirical and theoretical quantiles should match for large <code>n</code>, and 50000 is well past the regime where Monte Carlo noise matters here. Passing <code>type = 1</code> to <code>quantile()</code> is important because it uses the inverse of the <a class="auto-link" href="Kolmogorov-Smirnov-Two-Sample-Test-in-R.html" title="Kolmogorov-Smirnov Two-Sample Test in R: Compare Two Distributions">empirical CDF</a>, which matches the discrete-aware definition <code>qbinom()</code> uses. Other <code>type</code> values interpolate between adjacent <a class="auto-link" href="Order-Statistics-in-R.html" title="Order Statistics in R: Min, Max, Sample Quantiles — Theory &amp; Simulation">order statistics</a> and can drift off by 1 for skewed discrete distributions.</p>
</details>
</section>
<h2>Section 4. Simulation and parameter estimation with rbinom (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Estimate the head probability from 10000 simulated flips</h3>
<p class="exercise-task"><strong>Task:</strong> Simulate 10000 Bernoulli trials of a fair coin using <code>rbinom(n = 10000, size = 1, prob = 0.5)</code>, then compute the sample mean as your estimate of <code>prob</code>. Save the proportion to <code>ex_4_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.5014
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Each simulated flip is a 0 or a 1, and averaging those zeros and ones estimates the underlying success rate.</p><p>Generate the trials with rbinom(n = 10000, size = 1, prob = 0.5) and take <a class="auto-link" href="Descriptive-Statistics-in-R.html" title="Descriptive Statistics in R: The 8 Numbers That Tell You What Your Data Is Doing">mean()</a> of the result.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">flips  &lt;- rbinom(10000, size = 1, prob = 0.5)
ex_4_1 &lt;- mean(flips)
ex_4_1
#&gt; [1] 0.4977</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Setting <code>size = 1</code> makes <code>rbinom()</code> generate Bernoulli outcomes (0 or 1), and the sample mean of those is the maximum likelihood estimate of <code>prob</code>. With 10000 draws the standard error is $\sqrt{0.5 \cdot 0.5 / 10000} = 0.005$, so values near 0.495 to 0.505 are routine. Cranking <code>n</code> higher tightens that band, while shrinking <code>n</code> widens it and makes Monte Carlo estimation noticeably noisier.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Estimate p with standard error from a sample of 200 customers</h3>
<p class="exercise-task"><strong>Task:</strong> A survey draws 200 customers, of whom 56 click the promo banner. Treat this as a single Binomial(200, p) observation. Compute the point estimate $\hat p = 56/200$ and its standard error $\sqrt{\hat p (1 - \hat p) / 200}$. Save both to a named numeric vector with elements <code>phat</code> and <code>se</code> and assign it to <code>ex_4_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>      phat         se 
0.28000000 0.03174902
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The point estimate is just the observed success fraction, and its uncertainty shrinks with the square root of the <a class="auto-link" href="AB-Testing-Interview-Cases.html" title="A/B Testing Interview Cases: 20 Solved in R">sample size</a>.</p><p>Compute phat = 56 / 200 and se = sqrt(phat * (1 - phat) / 200), then combine them with c(phat = ..., se = ...).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">x  &lt;- 56
n  &lt;- 200
phat &lt;- x / n
se   &lt;- sqrt(phat * (1 - phat) / n)
ex_4_2 &lt;- c(phat = phat, se = se)
ex_4_2
#&gt;    phat      se
#&gt; 0.28000 0.03175</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> $\hat p$ is the sample success proportion and is the MLE of the binomial probability parameter. Its Wald standard error uses $\hat p$ in place of the unknown true $p$, which is why the formula plugs in 0.28 rather than a hypothesized 0.5. For small samples or proportions near 0 or 1, Wald standard errors overstate precision; in those regimes prefer Wilson or Agresti-Coull intervals returned by <code>binom.test()</code> and <code>prop.test()</code>.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Compare empirical to theoretical mean and variance</h3>
<p class="exercise-task"><strong>Task:</strong> Draw 5000 samples from <code>Binomial(20, 0.3)</code> with <code>rbinom()</code>. Compute the sample mean and sample variance, then compute the theoretical values $np$ and $np(1-p)$. Save all four as a named numeric vector with elements <code>emp_mean</code>, <code>emp_var</code>, <code>theo_mean</code>, <code>theo_var</code> and assign to <code>ex_4_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code> emp_mean   emp_var theo_mean  theo_var 
 6.038600  4.241158  6.000000  4.200000
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A simulated sample's average and spread should land near the distribution's theoretical center and dispersion.</p><p>Take mean() and var() of rbinom(5000, size = 20, prob = 0.3), and pair them with 20 <em> 0.3 and 20 </em> 0.3 * (1 - 0.3).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">draws &lt;- rbinom(5000, size = 20, prob = 0.3)
ex_4_3 &lt;- c(
  emp_mean  = mean(draws),
  emp_var   = var(draws),
  theo_mean = 20 * 0.3,
  theo_var  = 20 * 0.3 * (1 - 0.3)
)
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The theoretical mean of $\text{Binomial}(n, p)$ is $np$ and the variance is $np(1 - p)$, both classic results derived from summing $n$ independent Bernoulli variables. Empirical estimates from 5000 draws should be within a few percent of these targets. If you saw the empirical variance systematically above the theoretical value, that would signal <a class="auto-link" href="Poisson-Regression-in-R.html" title="Poisson Regression in R: Model Count Data and Handle Overdispersion">overdispersion</a> and you might switch to a Beta-binomial or quasi-binomial fit.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-4-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.4: Simulate free-throw streaks for an 85 percent shooter</h3>
<p class="exercise-task"><strong>Task:</strong> Simulate one season of 1000 free-throw attempts for a player with a true make rate of 0.85, then count the longest consecutive run of makes (a streak). Use <code>rbinom()</code> to generate the 1000 outcomes and <code>rle()</code> to find the longest run of 1s. Save the longest streak length to <code>ex_4_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 30
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A streak is a stretch of consecutive identical outcomes, so you need a way to measure runs of equal values in the simulated sequence.</p><p>Generate outcomes with rbinom(1000, size = 1, prob = 0.85), pass them to rle(), then take max() of the lengths where values equal 1.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_4 &lt;- # your code here
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">makes  &lt;- rbinom(1000, size = 1, prob = 0.85)
runs   &lt;- rle(makes)
ex_4_4 &lt;- max(runs$lengths[runs$values == 1])
ex_4_4
#&gt; [1] 41</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rle()</code> returns run-length encoding of a vector: the lengths and the values of consecutive equal stretches, which is exactly the streak structure you want here. Filtering <code>runs$values == 1</code> keeps the make-streaks and drops the miss-streaks. The expected longest run for $p = 0.85$ and $n = 1000$ grows like $\log_{1/p}(n) \approx 28$, but tail values in the 30s and 40s are routine because the maximum of geometric-like streak lengths has a heavy right tail.</p>
</details>
</section>
<h2>Section 5. Inference with binom.test (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Two-sided exact test for coin fairness</h3>
<p class="exercise-task"><strong>Task:</strong> Suppose 40 heads were observed in 100 flips. Run an exact two-sided test of $H_0: p = 0.5$ with <code>binom.test()</code> and extract the p-value. Save just the p-value as a scalar to <code>ex_5_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.05688793</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>An exact test of a hypothesized success rate measures how surprising the observed count is, and you only need that single summary number.</p><p>Run binom.test(40, 100, p = 0.5, alternative = "two.sided") and pull out the $p.value element.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">test_5_1 &lt;- binom.test(40, 100, p = 0.5, alternative = "two.sided")
ex_5_1   &lt;- test_5_1$p.value
ex_5_1
#&gt; [1] 0.05688793</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>binom.test()</code> returns a list (an <code>htest</code> object) and the p-value lives in <code>$p.value</code>. For two-sided tests R uses the rule of summing probabilities of all outcomes at least as unlikely as the observed one, which is exact and discrete-aware, not the lazy <code>2 * pbinom(...)</code> shortcut. The 5.7 percent value is famously just over the 5 percent threshold, a good talking point about the arbitrariness of alpha cutoffs.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: A/B test: 125 clicks out of 1000 against a 10 percent baseline</h3>
<p class="exercise-task"><strong>Task:</strong> A product team ships a new landing page expecting at least a 10 percent click-through rate and observes 125 clicks in 1000 visits. Run a two-sided <code>binom.test()</code> of $H_0: p = 0.10$ and extract both the p-value and the 95 percent confidence interval. Save them as a named numeric vector with elements <code>pvalue</code>, <code>ci_lo</code>, <code>ci_hi</code> and assign to <code>ex_5_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>     pvalue       ci_lo       ci_hi 
0.009779736 0.105129762 0.147106983
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>The test yields both a measure of surprise against the null and a plausible range for the true success rate.</p><p>Run binom.test(125, 1000, p = 0.10), then read $p.value and the two entries of $conf.int into a named vector.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">test_5_2 &lt;- binom.test(125, 1000, p = 0.10, alternative = "two.sided")
ex_5_2   &lt;- c(
  pvalue = test_5_2$p.value,
  ci_lo  = test_5_2$conf.int[1],
  ci_hi  = test_5_2$conf.int[2]
)
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The 95 percent interval <code>binom.test()</code> returns is Clopper-Pearson, the exact interval inverted from the binomial CDF. It is wider than the Wald or Wilson alternatives but guarantees coverage at least 95 percent. The interval here excludes the null value 0.10, consistent with the small p-value, but you should still report the effect size (12.5 percent observed versus 10 percent baseline) since statistical and <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">practical significance</a> are not the same.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Binomial-Distribution-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Exact binom.test versus normal-approximation prop.test</h3>
<p class="exercise-task"><strong>Task:</strong> Run both <code>binom.test(35, 100, p = 0.40)</code> and <code>prop.test(35, 100, p = 0.40, correct = FALSE)</code> and compare their p-values to see how the normal approximation tracks the exact test. Save the two p-values to a named numeric vector with elements <code>exact</code> and <code>normal</code> and assign to <code>ex_5_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>    exact    normal 
0.3583710 0.3074342
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>One test computes the answer exactly from the discrete distribution, the other leans on a normal approximation - compare their summary numbers.</p><p>Pull $p.value from both binom.test(35, 100, p = 0.40) and prop.test(35, 100, p = 0.40, correct = FALSE) into a named vector.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- c(
  exact  = binom.test(35, 100, p = 0.40)$p.value,
  normal = prop.test(35, 100, p = 0.40, correct = FALSE)$p.value
)
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>prop.test()</code> uses a <a class="auto-link" href="How-to-do-Chi-Square-Independence-Test-in-R.html" title="Chi-Square Test of Independence in R: chisq.test() Guide">chi-squared</a> statistic that is a normal approximation to the binomial, and <code>correct = FALSE</code> turns off Yates continuity correction so the comparison is apples-to-apples. The two p-values agree to about two significant figures here because $n = 100$ and the success count is comfortably away from 0 and $n$. For very small $n$ or extreme proportions the gap widens and the exact test is the safer default.</p>
</details>
</section>
<h2>What to do next</h2>
<ul>
<li>Review the parent lesson: <a href="Binomial-and-Poisson-Distributions-in-R.html">Binomial and Poisson Distributions in R</a> for the underlying theory and worked walk-throughs.</li>
<li>Move on to count-data inference: <a href="Poisson-Distribution-Exercises-in-R.html">Poisson Distribution Exercises in R</a>.</li>
<li>Reinforce the inference muscles with <a href="Hypothesis-Testing-Exercises-in-R.html">Hypothesis Testing Exercises in R</a>.</li>
<li>For more probability practice, try <a class="auto-link" href="The-Normal-Distribution-Explained-in-R.html" title="The Normal Distribution in R: Where It Comes From">Normal Distribution</a> Exercises in R.</li>
</ul>

{% endraw %}