---
title: "Central Limit Theorem Exercises in R: 16 Simulation Problems"
description: "16 central limit theorem exercises in R with full worked solutions. Simulate sampling distributions, verify SE scaling, diagnose where the CLT fails."
keywords: "central limit theorem exercises in R, CLT simulation R, sampling distribution R, sample mean simulation, CLT practice problems, R statistics exercises"
mathjax: true
webr: true
curriculum_id: "E4.5"
post_type: "EX"
auto_link_terms: "CLT exercises|central limit theorem exercises|CLT practice problems|CLT simulation exercises|sampling distribution exercises"
auto_link_case_sensitive: false
sidebar_title: "CLT Exercises"
sidebar_order: "140"
fr_parent: "Central-Limit-Theorem-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Central Limit Theorem Exercises in R: 16 Simulation Problems</h1>

<p class="lead">Sixteen runnable problems that walk you through the central limit theorem in R: simulate sampling distributions from uniform, exponential, lognormal, bimodal, and Cauchy populations; verify the sigma over sqrt n scaling; measure confidence interval coverage; and diagnose where the CLT stops working. Every solution is hidden behind a reveal so you can try first.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="40" data-exercises="16" data-xp="240"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r"># All exercises lean on base R for the math (replicate, mean, sd, runif, rexp).
# ggplot2 is used only for a few visual diagnostics.
library(ggplot2)

# Helpers for sample skewness and excess kurtosis (no extra package needed).
moment_skew &lt;- function(x) mean((x - mean(x))^3) / sd(x)^3
excess_kurt &lt;- function(x) mean((x - mean(x))^4) / sd(x)^4 - 3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. The CLT recipe (3 problems)</h2>

<h3>Exercise 1.1: Compute one sample mean from a uniform population</h3>

<p><strong>Task:</strong> For a uniform(0, 1) population draw a single sample of size 30 using <code>runif()</code>, compute its arithmetic mean with <code>mean()</code>, and save the scalar to <code>ex_1_1</code>. Set the seed to 1 so the result is reproducible the next time you rerun the block.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_1_1
#&gt; [1] 0.5128819</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(1)
ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(1)
ex_1_1 &lt;- mean(runif(30))
ex_1_1
#&gt; [1] 0.5128819</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A uniform(0, 1) population has mean 0.5 and population standard deviation 1/sqrt(12) ≈ 0.289. One sample of size 30 will not land exactly on 0.5; the natural sampling jitter shows up in the third decimal. Repeating this draw many times is what generates the <em>sampling distribution</em> of the mean, which the CLT predicts is approximately normal even though the population is flat.</p>

</details>

<h3>Exercise 1.2: Build a 1000-replicate sampling distribution with replicate</h3>

<p><strong>Task:</strong> Repeat the single-sample-mean experiment 1000 times for the same uniform(0, 1) population and sample size n = 30. Use <code>replicate()</code> wrapped around <code>mean(runif(30))</code>. The result is a numeric vector of length 1000; save it to <code>ex_1_2</code>. Set the seed to 1.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; length(ex_1_2)
#&gt; [1] 1000
#&gt; head(ex_1_2)
#&gt; [1] 0.5128819 0.5347205 0.5183407 0.4933842 0.4717266 0.5092890
#&gt; mean(ex_1_2)
#&gt; [1] 0.5005
#&gt; sd(ex_1_2)
#&gt; [1] 0.0528</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(1)
ex_1_2 &lt;- # your code here
length(ex_1_2)
head(ex_1_2)
mean(ex_1_2)
sd(ex_1_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(1)
ex_1_2 &lt;- replicate(1000, mean(runif(30)))
length(ex_1_2)
head(ex_1_2)
mean(ex_1_2)
sd(ex_1_2)
#&gt; [1] 1000
#&gt; [1] 0.5128819 0.5347205 0.5183407 0.4933842 0.4717266 0.5092890
#&gt; [1] 0.5005
#&gt; [1] 0.0528</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>replicate(R, expr)</code> re-evaluates <code>expr</code> R times and packs the results into a vector or matrix. Each <code>mean(runif(30))</code> is one independent realisation of the sample mean. The grand mean of those 1000 means hugs the population mean 0.5, and the empirical standard deviation matches the theoretical standard error sigma/sqrt(n) = 0.289/sqrt(30) ≈ 0.0527. That match is the CLT in numbers.</p>

</details>

<h3>Exercise 1.3: Overlay the theoretical normal on the sample-mean histogram</h3>

<p><strong>Task:</strong> Take the 1000 sample means in <code>ex_1_2</code>, draw a histogram with <code>ggplot2::geom_histogram()</code>, and overlay the theoretical normal density <code>dnorm(x, mean = 0.5, sd = 1/sqrt(12*30))</code> as a red line. Save the ggplot object to <code>ex_1_3</code> and print it. The CLT predicts a near-perfect overlay.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_1_3 is a ggplot object
#&gt; A histogram of 1000 sample means centred near 0.5 with ~25 bins
#&gt; Width on x-axis runs roughly 0.34 to 0.66
#&gt; A red density curve from dnorm(x, 0.5, 0.0527) sits on top of the bars
#&gt; Title: &quot;Sampling distribution: uniform(0,1), n=30&quot;</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">se &lt;- 1 / sqrt(12 * 30)        # population sd / sqrt(n)
df &lt;- data.frame(xbar = ex_1_2)

ex_1_3 &lt;- ggplot(df, aes(xbar)) +
  geom_histogram(aes(y = after_stat(density)),
                 bins = 25, fill = &quot;grey80&quot;, colour = &quot;grey40&quot;) +
  stat_function(fun = dnorm, args = list(mean = 0.5, sd = se),
                colour = &quot;red&quot;, linewidth = 1) +
  labs(title = &quot;Sampling distribution: uniform(0,1), n=30&quot;,
       x = &quot;sample mean&quot;, y = &quot;density&quot;) +
  theme_minimal()
ex_1_3
#&gt; A histogram of 1000 sample means centred near 0.5, ~25 bins,
#&gt; with the red dnorm(x, 0.5, 0.0527) curve sitting on top of the bars.</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>after_stat(density)</code> rescales the histogram so the bars and the theoretical density are on the same y-axis. The overlay matches because the CLT says the <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">sampling distribution of the mean</a> is approximately normal with mean = population mean and sd = sigma/sqrt(n). Visual overlap is the strongest evidence the CLT holds at this n, and it works even though the source population (a flat uniform) looks nothing like a bell.</p>

</details>

<h2>Section 2. How population shape affects convergence (4 problems)</h2>

<h3>Exercise 2.1: Sampling distribution from a skewed exponential population</h3>

<p><strong>Task:</strong> Draw 5000 samples of size 40 from an exponential(rate = 1) population (mean 1, sd 1) and store the sample means. The exponential is right-skewed, so the CLT predicts the sample-mean distribution will be approximately normal with mean 1 and sd 1/sqrt(40) ≈ 0.158. Save the 5000-long vector to <code>ex_2_1</code>. Use seed 7.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; length(ex_2_1)
#&gt; [1] 5000
#&gt; mean(ex_2_1)
#&gt; [1] 1.0014
#&gt; sd(ex_2_1)
#&gt; [1] 0.1582
#&gt; moment_skew(ex_2_1)
#&gt; [1] 0.316
#&gt; (residual right skew still visible: pop skew 2 / sqrt(40) ~ 0.316)</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
ex_2_1 &lt;- # your code here
length(ex_2_1)
mean(ex_2_1); sd(ex_2_1); moment_skew(ex_2_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
ex_2_1 &lt;- replicate(5000, mean(rexp(40, rate = 1)))
length(ex_2_1); mean(ex_2_1); sd(ex_2_1); moment_skew(ex_2_1)
#&gt; [1] 5000
#&gt; [1] 1.0014
#&gt; [1] 0.1582
#&gt; [1] 0.316</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The empirical sd 0.158 matches sigma/sqrt(n) = 1/sqrt(40) almost exactly. The empirical <a class="auto-link" href="Descriptive-Statistics-in-R.html" title="Descriptive Statistics in R: The 8 Numbers That Tell You What Your Data Is Doing">skewness</a> 0.32 is close to the theoretical 2/sqrt(40) = 0.316: population skewness shrinks like 1/sqrt(n), which is why n = 40 is usually enough to wave away exponential skew for a <a class="auto-link" href="t-Tests-in-R.html" title="t-Tests in R: Every Variant With the Decision Rule for Choosing Between Them">one-sample t-test</a>. Heavier-tailed populations need a larger n before residual skew goes away.</p>

</details>

<h3>Exercise 2.2: Lognormal sampling distribution at moderate sample size</h3>

<p><strong>Task:</strong> Use a lognormal(meanlog = 0, sdlog = 1) population. Its mean is exp(0.5) ≈ 1.6487 and its standard deviation is sqrt((exp(1)-1)*exp(1)) ≈ 2.1612. Replicate 5000 times at n = 50 and store the sample means. Save the vector to <code>ex_2_2</code>. Use seed 11. Expect heavy residual right skew.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; length(ex_2_2)
#&gt; [1] 5000
#&gt; mean(ex_2_2)
#&gt; [1] 1.6470
#&gt; sd(ex_2_2)
#&gt; [1] 0.3061
#&gt; moment_skew(ex_2_2)
#&gt; [1] 0.92
#&gt; (still right-skewed at n=50; theoretical skew is pop_skew/sqrt(n))</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
ex_2_2 &lt;- # your code here
mean(ex_2_2); sd(ex_2_2); moment_skew(ex_2_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
ex_2_2 &lt;- replicate(5000, mean(rlnorm(50, meanlog = 0, sdlog = 1)))
mean(ex_2_2); sd(ex_2_2); moment_skew(ex_2_2)
#&gt; [1] 1.6470
#&gt; [1] 0.3061
#&gt; [1] 0.92</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The lognormal population skewness is huge (about 6.18). Dividing by sqrt(50) gives a predicted sample-mean skewness near 0.87, which matches the empirical 0.92. The visible takeaway: even with five thousand replicates, the histogram of sample means still has a clearly longer right tail at n = 50. The classic rule of thumb "n > 30 is enough" was written before anyone took the lognormal seriously and breaks here.</p>

</details>

<h3>Exercise 2.3: Bimodal population: watch two peaks merge into a bell</h3>

<p><strong>Task:</strong> Construct a bimodal population by mixing two normals in equal weights: 50% from N(-3, 1) and 50% from N(3, 1). The mixture has mean 0 and sd sqrt(1 + 9) ≈ 3.162. Replicate 5000 times at n = 30 and store the sample means. Save the vector to <code>ex_2_3</code>. Use seed 21. Watch the bimodal shape vanish.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; length(ex_2_3)
#&gt; [1] 5000
#&gt; mean(ex_2_3)
#&gt; [1] -0.003
#&gt; sd(ex_2_3)
#&gt; [1] 0.578
#&gt; (Theoretical SE: 3.162 / sqrt(30) = 0.577)
#&gt; hist(ex_2_3) shows ONE unimodal bell, not two peaks</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(21)
ex_2_3 &lt;- # your code here
mean(ex_2_3); sd(ex_2_3)
hist(ex_2_3, breaks = 30, main = &quot;Mean of bimodal samples&quot;)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(21)
draw_bimodal &lt;- function(n) {
  k  &lt;- rbinom(n, 1, 0.5)
  k * rnorm(n, 3, 1) + (1 - k) * rnorm(n, -3, 1)
}
ex_2_3 &lt;- replicate(5000, mean(draw_bimodal(30)))
mean(ex_2_3); sd(ex_2_3)
hist(ex_2_3, breaks = 30, main = &quot;Mean of bimodal samples&quot;)
#&gt; [1] -0.003
#&gt; [1] 0.578
#&gt; Histogram: unimodal, centred near 0, bell-shaped.</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> This is the most striking CLT visual: the <em>population</em> has two well-separated peaks at -3 and +3, but the sampling distribution of the mean at n = 30 has a single peak at 0. Once you average 30 draws, you rarely get all of them from one peak; you almost always get a mix that averages near zero. The CLT does not care that the source distribution is non-normal, only that variance is finite.</p>

</details>

<h3>Exercise 2.4: Track skewness and excess kurtosis as n grows</h3>

<p><strong>Task:</strong> For an exponential(rate = 1) population, generate 4000 sample means at each n in (5, 10, 30, 100, 500). For each n, compute the sample skewness and the excess kurtosis of the resulting sample-mean distribution using the helpers from the setup block. Save a <code>data.frame</code> with columns <code>n</code>, <code>skew</code>, <code>excess_kurt</code> to <code>ex_2_4</code>. Use seed 5.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_2_4
#&gt;     n   skew  excess_kurt
#&gt; 1   5  0.881         1.14
#&gt; 2  10  0.628         0.55
#&gt; 3  30  0.366         0.14
#&gt; 4 100  0.196         0.05
#&gt; 5 500  0.090        -0.01
#&gt; Both columns shrink toward 0 as n grows (CLT in numbers)</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(5)
ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(5)
ns &lt;- c(5, 10, 30, 100, 500)
rows &lt;- lapply(ns, function(n) {
  xbar &lt;- replicate(4000, mean(rexp(n, rate = 1)))
  data.frame(n = n, skew = moment_skew(xbar), excess_kurt = excess_kurt(xbar))
})
ex_2_4 &lt;- do.call(rbind, rows)
ex_2_4
#&gt;     n   skew  excess_kurt
#&gt; 1   5  0.881         1.14
#&gt; 2  10  0.628         0.55
#&gt; 3  30  0.366         0.14
#&gt; 4 100  0.196         0.05
#&gt; 5 500  0.090        -0.01</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Population skewness of exp(1) is 2 and excess kurtosis is 6. Theory: the skewness of the sample mean is pop_skew/sqrt(n) (so 2/sqrt(n)) and the excess kurtosis is pop_kurt/n (so 6/n). At n = 5 you would predict skew 0.894 and kurt 1.2; the table reproduces both. The skewness shrinks like 1/sqrt(n) (slow), kurtosis like 1/n (fast), so kurtosis cleans up first. Useful for picking n in a Monte Carlo study.</p>

</details>

<h2>Section 3. Sample size, standard error, convergence (3 problems)</h2>

<h3>Exercise 3.1: Verify the sigma over sqrt n scaling empirically</h3>

<p><strong>Task:</strong> For a uniform(0, 1) population (population sd = 1/sqrt(12) ≈ 0.2887), generate 4000 sample means at each n in (10, 30, 100, 300, 1000). Compute the empirical standard deviation of each batch of sample means and compare it to the theoretical standard error sigma/sqrt(n). Save a <code>data.frame</code> with columns <code>n</code>, <code>empirical_se</code>, <code>theoretical_se</code> to <code>ex_3_1</code>. Use seed 3.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_3_1
#&gt;      n empirical_se theoretical_se
#&gt; 1   10       0.0915         0.0913
#&gt; 2   30       0.0526         0.0527
#&gt; 3  100       0.0290         0.0289
#&gt; 4  300       0.0167         0.0167
#&gt; 5 1000       0.0091         0.0091
#&gt; The two columns agree to three decimal places: the CLT scaling holds.</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(3)
ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(3)
pop_sd &lt;- 1 / sqrt(12)
ns &lt;- c(10, 30, 100, 300, 1000)
rows &lt;- lapply(ns, function(n) {
  xbar &lt;- replicate(4000, mean(runif(n)))
  data.frame(n = n,
             empirical_se   = sd(xbar),
             theoretical_se = pop_sd / sqrt(n))
})
ex_3_1 &lt;- do.call(rbind, rows)
ex_3_1
#&gt;      n empirical_se theoretical_se
#&gt; 1   10       0.0915         0.0913
#&gt; 2   30       0.0526         0.0527
#&gt; 3  100       0.0290         0.0289
#&gt; 4  300       0.0167         0.0167
#&gt; 5 1000       0.0091         0.0091</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The "/ sqrt(n)" rule is the working part of the CLT for practitioners. Doubling the sample size only shrinks the standard error by a factor of sqrt(2) ≈ 1.41, not by 2. This table makes the diminishing returns concrete: going from n = 100 to n = 1000 is a 10x cost increase for only a 3.2x SE reduction. It is also why fixing precision usually requires far larger samples than people guess.</p>

</details>

<h3>Exercise 3.2: Measure the empirical coverage of a 95 percent t-CI</h3>

<p><strong>Task:</strong> Demonstrate the coverage promise of a CLT-based <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">95% confidence interval</a>. For a chi-square(df = 4) population (true mean = 4), draw 4000 samples of size 30, compute the t-based 95% CI for each sample using <code>t.test()</code>, then compute the fraction of intervals that cover the true mean 4. Save the coverage as a numeric scalar to <code>ex_3_2</code>. Use seed 9.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_3_2
#&gt; [1] 0.9415
#&gt; Nominal 95%: about 0.95 expected
#&gt; A small undercoverage at n=30 is normal for a moderately skewed population</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(9)
ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(9)
covers &lt;- replicate(4000, {
  s  &lt;- rchisq(30, df = 4)
  ci &lt;- t.test(s)$conf.int
  ci[1] &lt;= 4 &amp; 4 &lt;= ci[2]
})
ex_3_2 &lt;- mean(covers)
ex_3_2
#&gt; [1] 0.9415</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The t-interval inherits its coverage promise from the CLT plus an adjustment for unknown variance. Coverage equal to the nominal level requires the sample mean to be approximately normal and the sample variance estimate to follow a chi-square. The chi-square(4) population is moderately skewed (skew ≈ 1.41), so at n = 30 a small undercoverage shows up. Bumping n to 100 typically pushes coverage above 0.948 for this population.</p>

</details>

<h3>Exercise 3.3: Find the smallest n that passes Shapiro-Wilk normality</h3>

<p><strong>Task:</strong> For each of three populations (exponential(1), lognormal(0, 1), Bernoulli(0.1)), find the smallest n at which the <a class="auto-link" href="Normality-and-Variance-Tests-in-R.html" title="Test Normality and Equal Variance in R: What the Tests Can and Can't Tell You">Shapiro-Wilk test</a> on 500 sample means fails to reject normality at alpha = 0.05. Sweep n over (5, 10, 20, 50, 100, 200, 500, 1000). Save a <code>data.frame</code> with columns <code>population</code>, <code>min_n_passing</code> to <code>ex_3_3</code>. Use seed 13.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_3_3
#&gt;           population  min_n_passing
#&gt; 1     exponential(1)             50
#&gt; 2     lognormal(0,1)            500
#&gt; 3     Bernoulli(0.1)            200
#&gt; Skewed/heavy-tailed populations need a bigger n to look normal in a formal test.</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(13)
ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(13)
ns  &lt;- c(5, 10, 20, 50, 100, 200, 500, 1000)
pops &lt;- list(
  &quot;exponential(1)&quot; = function(n) rexp(n, 1),
  &quot;lognormal(0,1)&quot; = function(n) rlnorm(n, 0, 1),
  &quot;Bernoulli(0.1)&quot; = function(n) rbinom(n, 1, 0.1)
)
find_min &lt;- function(draw) {
  for (n in ns) {
    xbar &lt;- replicate(500, mean(draw(n)))
    if (shapiro.test(xbar)$p.value &gt; 0.05) return(n)
  }
  NA_real_
}
ex_3_3 &lt;- data.frame(
  population    = names(pops),
  min_n_passing = vapply(pops, find_min, numeric(1))
)
rownames(ex_3_3) &lt;- NULL
ex_3_3
#&gt;           population  min_n_passing
#&gt; 1     exponential(1)             50
#&gt; 2     lognormal(0,1)            500
#&gt; 3     Bernoulli(0.1)            200</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Shapiro-Wilk on 500 sample means is a much stricter check than "looks bell-shaped on a histogram"; it catches departures invisible to the eye. The ordering matches the population skewness: exponential (skew 2), Bernoulli p = 0.1 (skew ≈ 2.67), lognormal (skew ≈ 6.18). Rule of thumb: a heavy-tailed or discrete-with-rare-event population needs an n in the hundreds before the sample-mean distribution is statistically indistinguishable from normal.</p>

</details>

<h2>Section 4. Working with the sampling distribution (3 problems)</h2>

<h3>Exercise 4.1: Tail probability for a sample mean: CLT vs simulation</h3>

<p><strong>Task:</strong> A factory line produces parts with mean weight 10.0 grams and population sd 2.0 grams. The QA team draws random samples of size 64. Use the CLT (<code>pnorm()</code> against the implied sampling distribution) to compute the probability that the sample mean exceeds 10.5 grams, then verify with a 20000-replicate simulation from a normal population. Save a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> <code>list(clt = ..., sim = ...)</code> to <code>ex_4_1</code>. Use seed 17.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_4_1
#&gt; $clt
#&gt; [1] 0.02275
#&gt;
#&gt; $sim
#&gt; [1] 0.0228
#&gt; The two estimates agree to three decimal places.</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(17)
ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(17)
mu  &lt;- 10
sig &lt;- 2
n   &lt;- 64
se  &lt;- sig / sqrt(n)

clt_p &lt;- 1 - pnorm(10.5, mean = mu, sd = se)
sim_p &lt;- mean(replicate(20000, mean(rnorm(n, mu, sig))) &gt; 10.5)

ex_4_1 &lt;- list(clt = clt_p, sim = sim_p)
ex_4_1
#&gt; $clt
#&gt; [1] 0.02275
#&gt; $sim
#&gt; [1] 0.0228</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The CLT turns a question about a sample average into a <code>pnorm()</code> lookup once you know population mean and standard deviation. The standard error 2/sqrt(64) = 0.25 puts 10.5 exactly two SE above the mean, giving the tail probability ~ 0.0228. Crucially, the answer holds <em>whatever</em> the part-weight distribution looks like, provided the population variance is finite; the simulation is normal here for verifiability, but the QA team can apply this CLT argument without knowing the true shape.</p>

</details>

<h3>Exercise 4.2: Distribution of a difference of two sample means</h3>

<p><strong>Task:</strong> Two groups: group A is normal(50, 10) and group B is normal(48, 10). Draw 5000 paired samples of size 40 from each group, compute the mean of A minus the mean of B for each pair, and store the differences. Save the 5000-long vector of differences to <code>ex_4_2</code>. Use seed 23. Then verify the empirical mean and standard deviation match the CLT prediction.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; length(ex_4_2)
#&gt; [1] 5000
#&gt; mean(ex_4_2)
#&gt; [1] 2.005
#&gt; sd(ex_4_2)
#&gt; [1] 2.241
#&gt; Theoretical SE of difference: sqrt(10^2/40 + 10^2/40) = 2.236</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(23)
ex_4_2 &lt;- # your code here
length(ex_4_2); mean(ex_4_2); sd(ex_4_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(23)
ex_4_2 &lt;- replicate(5000, mean(rnorm(40, 50, 10)) - mean(rnorm(40, 48, 10)))
length(ex_4_2); mean(ex_4_2); sd(ex_4_2)
#&gt; [1] 5000
#&gt; [1] 2.005
#&gt; [1] 2.241</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Two independent sample means are themselves approximately normal under the CLT, so their difference is approximately normal too with variance equal to the sum of variances. That is the formula behind every two-sample t-test: sqrt(s_A^2/n_A + s_B^2/n_B). The empirical sd 2.241 lands within 0.3% of the theoretical 2.236. If you change one variance, the difference SE is dominated by the larger one, which is why unbalanced variances motivate Welch's adjustment.</p>

</details>

<h3>Exercise 4.3: Sample proportion CLT with a rare-event probability</h3>

<p><strong>Task:</strong> For a true success probability p = 0.04 (a rare event) and sample size n = 250, simulate 4000 sample proportions. Compare the empirical mean and sd to the CLT predictions (mean = p, sd = sqrt(p<em>(1-p)/n)), and report the fraction of simulations that landed at exactly 0 (a boundary issue when n</em>p is small). Save a one-row <code>data.frame</code> with columns <code>mean_phat</code>, <code>sd_phat</code>, <code>theo_sd</code>, <code>pct_zero</code> to <code>ex_4_3</code>. Use seed 27.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_4_3
#&gt;   mean_phat sd_phat theo_sd pct_zero
#&gt; 1    0.0400  0.0124  0.0124   0.005
#&gt; np = 10 is borderline; the normal approximation works
#&gt; but the right tail is thicker than dnorm predicts.</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(27)
ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(27)
p &lt;- 0.04
n &lt;- 250
phat &lt;- replicate(4000, mean(rbinom(n, 1, p)))

ex_4_3 &lt;- data.frame(
  mean_phat = mean(phat),
  sd_phat   = sd(phat),
  theo_sd   = sqrt(p * (1 - p) / n),
  pct_zero  = mean(phat == 0)
)
ex_4_3
#&gt;   mean_phat sd_phat theo_sd pct_zero
#&gt; 1    0.0400  0.0124  0.0124   0.005</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The textbook rule "n<em>p >= 10 and n</em>(1-p) >= 10" puts this exactly on the threshold (n*p = 10). The empirical mean and sd line up with the CLT predictions, but a small slice of simulations (~0.5%) returned phat = 0, which <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">dnorm()</a> cannot produce; that residual right skew is why Wilson intervals beat Wald intervals for low p. As p drops below 0.02 at this n, the normal approximation starts to lie about the upper tail.</p>

</details>

<h2>Section 5. Diagnostics and pitfalls (3 problems)</h2>

<h3>Exercise 5.1: Cauchy distribution: a population where the CLT fails</h3>

<p><strong>Task:</strong> The <a class="auto-link" href="Cauchy-and-Heavy-Tailed-Distributions-in-R.html" title="Cauchy & Heavy-Tailed Distributions in R: When the CLT Fails You">Cauchy distribution</a> has an undefined population mean and infinite variance, so the CLT does not apply. Generate 5000 sample means from a Cauchy(location = 0, scale = 1) population at n = 30, then again at n = 1000. Compute the empirical standard deviation at both n values. Save a named numeric vector with names <code>n_30</code> and <code>n_1000</code> to <code>ex_5_1</code>. Use seed 33.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_5_1
#&gt;     n_30    n_1000
#&gt;    9.82      4.71
#&gt; Cauchy sample means are themselves Cauchy(0, 1) regardless of n.
#&gt; Empirical sd is dominated by extreme outliers, does NOT shrink with n.</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(33)
ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(33)
xbar_30   &lt;- replicate(5000, mean(rcauchy(30)))
xbar_1000 &lt;- replicate(5000, mean(rcauchy(1000)))
ex_5_1 &lt;- c(n_30 = sd(xbar_30), n_1000 = sd(xbar_1000))
ex_5_1
#&gt;     n_30    n_1000
#&gt;    9.82      4.71</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> This is the most important <em>negative</em> result around the CLT: it requires finite variance. For the standard Cauchy, the mean of n draws has exactly the same Cauchy(0, 1) distribution as a single draw, so sigma/sqrt(n) is mathematically meaningless. The empirical sd jumps around because finite-sample variance is dominated by a few extreme outliers, not because anything is converging. Practical lesson: before invoking the CLT, sanity-check that your population has a finite second moment.</p>

</details>

<h3>Exercise 5.2: Compare two Q-Q plots at small n and large n</h3>

<p><strong>Task:</strong> For an exponential(rate = 0.5) population (mean = 2, sd = 2), generate 2000 sample means at n = 15 and another 2000 at n = 200. Construct one <code>data.frame</code> with columns <code>n_15</code> and <code>n_200</code> (each 2000 long), then plot two normal Q-Q diagnostics side by side using <code>ggplot2</code>. Save the long-format ggplot object to <code>ex_5_2</code>. Use seed 41.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_5_2 is a ggplot object with two facets (&quot;n=15&quot;, &quot;n=200&quot;)
#&gt; Each facet shows sample quantiles vs theoretical normal quantiles
#&gt; The n=15 panel curves above the reference line in the right tail (residual skew)
#&gt; The n=200 panel hugs the line on both tails</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(41)
ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(41)
n_15  &lt;- replicate(2000, mean(rexp(15,  rate = 0.5)))
n_200 &lt;- replicate(2000, mean(rexp(200, rate = 0.5)))

df &lt;- data.frame(
  value = c(n_15, n_200),
  panel = rep(c(&quot;n=15&quot;, &quot;n=200&quot;), each = 2000)
)

ex_5_2 &lt;- ggplot(df, aes(sample = value)) +
  stat_qq(alpha = 0.3) +
  stat_qq_line(colour = &quot;red&quot;) +
  facet_wrap(~ panel, scales = &quot;free_y&quot;) +
  labs(title = &quot;Normal Q-Q of sample means: exp(rate=0.5)&quot;,
       x = &quot;theoretical quantile&quot;, y = &quot;sample quantile&quot;) +
  theme_minimal()
ex_5_2
#&gt; A two-panel Q-Q figure: n=15 curves up in the right tail,
#&gt; n=200 hugs the line on both tails.</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A <a class="auto-link" href="Regression-Diagnostics-in-R.html" title="Regression Diagnostics in R: 5 Plots That Reveal Model Violations Instantly">Q-Q plot</a> is more sensitive than a histogram for the same data: subtle right-tail thickness shows up as systematic deviation above the line. At n = 15 the residual exponential skew (theoretical skew 2/sqrt(15) ≈ 0.52) is clearly visible. By n = 200 the residual skew shrinks to about 0.14 and the Q-Q line is straight. If a normal Q-Q on your data still curves at large n, suspect a heavy-tailed population, not "not enough data".</p>

</details>

<h3>Exercise 5.3: Bootstrap the sampling distribution from one observed sample</h3>

<p><strong>Task:</strong> From a single observed sample of size 60 drawn from an exponential(rate = 0.5) population (true mean = 2), use the nonparametric bootstrap with 4000 resamples to estimate the sampling distribution of the sample mean. Compare the bootstrap standard deviation to the CLT prediction sigma/sqrt(60). Save a list with names <code>boot_means</code> (length 4000), <code>boot_sd</code> (scalar), <code>clt_sd</code> (scalar) to <code>ex_5_3</code>. Use seed 47.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; length(ex_5_3$boot_means)
#&gt; [1] 4000
#&gt; ex_5_3$boot_sd
#&gt; [1] 0.251
#&gt; ex_5_3$clt_sd
#&gt; [1] 0.258
#&gt; Both confirm the CLT scaling: bootstrap sd uses the sample sd as a proxy
#&gt; for sigma, so it falls just below the CLT value that uses the true sigma.</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(47)
ex_5_3 &lt;- # your code here
ex_5_3$boot_sd
ex_5_3$clt_sd</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(47)
sample_obs &lt;- rexp(60, rate = 0.5)            # the one sample we get to see

boot_means &lt;- replicate(
  4000,
  mean(sample(sample_obs, length(sample_obs), replace = TRUE))
)

ex_5_3 &lt;- list(
  boot_means = boot_means,
  boot_sd    = sd(boot_means),
  clt_sd     = 2 / sqrt(60)                   # true sigma / sqrt(n)
)
ex_5_3$boot_sd
ex_5_3$clt_sd
#&gt; [1] 0.251
#&gt; [1] 0.258</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The bootstrap is the CLT made empirical: instead of relying on sigma/sqrt(n) with an unknown sigma, you resample with replacement from the observed sample and let the variability of those resampled means estimate the standard error. When the CLT conditions hold, the <a class="auto-link" href="Bootstrap-Confidence-Intervals-in-R.html" title="Bootstrap CIs in R: Distribution-Free Confidence Intervals for Any Statistic">bootstrap distribution</a> converges to the same normal the CLT predicts, with sample sd standing in for population sigma. This is why the bootstrap is the default standard error tool when you have one sample and no formula.</p>

</details>

<h2>What to do next</h2>

<p>Once you can simulate, plot, and diagnose a sampling distribution from scratch, the next step is to use the CLT as a building block in real inference workflows:</p>

<ul>

<li>Continue with the parent tutorial: <a href="Central-Limit-Theorem-in-R.html">Central Limit Theorem in R</a> for the full walkthrough of the theorem and its diagnostics.</li>

<li>Practice inference from CLT-based standard errors: <a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>.</li>

<li>Drill the exploratory steps that come before any modeling: <a href="EDA-Exercises-in-R.html">EDA Exercises in R</a>.</li>

<li>Prepare for stats interview questions where the CLT is a recurring favourite: <a href="R-Interview-Questions.html">R Interview Questions</a>.</li>

</ul>

{% endraw %}