---
title: "Cluster Analysis Exercises in R: 17 k-Means, Hierarchical &amp; PAM Problems"
description: "17 cluster analysis exercises in R covering k-means, scaling, elbow &amp; silhouette diagnostics, hierarchical clustering, linkage choice, PAM, and Rand index."
keywords: "cluster analysis exercises in R, clustering exercises R, k-means exercises, kmeans practice, hierarchical clustering R exercises, hclust practice, silhouette R, elbow method R, PAM clustering R, adjusted rand index R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "cluster analysis exercises in R|clustering exercises in R|kmeans practice|hierarchical clustering exercises|silhouette analysis R"
auto_link_case_sensitive: false
sidebar_title: "Cluster Analysis Exercises"
sidebar_order: "305"
fr_parent: "Cluster-Analysis-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>Cluster Analysis Exercises in R: 17 k-Means, Hierarchical &amp; PAM Problems</h1>
<p class="lead">Seventeen cluster analysis exercises in R, ordered from a first <code>kmeans()</code> fit through scaling, elbow and silhouette diagnostics, <a class="auto-link" href="Cluster-Analysis-in-R.html" title="Clustering in R: k-Means vs Hierarchical vs DBSCAN, How to Choose for Your Data">hierarchical clustering</a> with multiple linkages, cophenetic correlation, k-medoids, and partition agreement via the adjusted Rand index. Each problem ships with a runnable starter, an exact expected output, and a click-to-reveal solution explaining the choice.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="17" data-time="40" data-xp="255"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(cluster)
library(factoextra)
library(ggplot2)
library(mclust)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. k-means warm-up (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Fit a three-cluster k-means on scaled iris</h3>
<p class="exercise-task"><strong>Task:</strong> Fit a k-means model with three centers on the scaled <code>iris[, 1:4]</code> numeric matrix using <code>set.seed(101)</code> and <code>nstart = 25</code>, then save the fitted object to <code>ex_1_1</code> so later exercises can re-use its sizes, centers, and within-SS slots.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 53 47 50
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Clustering depends on a random starting point, so pin the randomness down and run the fit many times so the best of those runs is kept.</p><p>Call kmeans() on iris_scaled with centers = 3 and nstart = 25, immediately after set.seed(101).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">iris_scaled &lt;- scale(iris[, 1:4])
ex_1_1 &lt;- # your code here
ex_1_1$size</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">iris_scaled &lt;- scale(iris[, 1:4])
set.seed(101)
ex_1_1 &lt;- kmeans(iris_scaled, centers = 3, nstart = 25)
ex_1_1$size
#&gt; [1] 50 53 47</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>nstart = 25</code> runs k-means from 25 random initial centroids and keeps the lowest within-cluster sum of squares, which is the standard defence against bad starts. Without it a single unlucky seed can land in a poor local minimum. The size vector returning roughly balanced groups is a sanity sign that the algorithm has not collapsed into a degenerate one-big-cluster solution.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Read the centers, within-SS, and total within-SS</h3>
<p class="exercise-task"><strong>Task:</strong> Using the <code>ex_1_1</code> object from the previous exercise, extract the cluster centroid matrix, the per-cluster within-cluster sum of squares vector, and the scalar total within-SS. Bundle the three into a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> saved as <code>ex_1_2</code> so a reviewer can audit the loss decomposition in one print call.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>$centers
  Sepal.Length Sepal.Width Petal.Length Petal.Width
1        -0.05       -0.88         0.35        0.28
2         1.13        0.09         0.99        1.01
3        -1.01        0.85        -1.30       -1.25

$withinss
[1] 44.1 47.5 47.4

$tot.withinss
[1] 138.89
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Every quantity you need is already stored inside the fitted object - you only have to reach in and bundle the three pieces together.</p><p>Build a list() holding ex_1_1$centers, ex_1_1$withinss, and ex_1_1$tot.withinss, wrapping each one in round().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- list(
  centers      = round(ex_1_1$centers, 2),
  withinss     = round(ex_1_1$withinss, 1),
  tot.withinss = round(ex_1_1$tot.withinss, 2)
)
ex_1_2
#&gt; $centers (rounded)
#&gt; ...
#&gt; $tot.withinss
#&gt; [1] 138.89</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A <code>kmeans</code> return is a list, not an S4 object, so all internals are reachable by <code>$</code>. The triple of centers, per-cluster SS, and total within-SS is what every downstream diagnostic (elbow, silhouette, comparison across k) is built on. Centroids are reported in scaled units because the input was scaled; back-transforming with the column means and standard deviations recovers original units.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Cross-tabulate cluster labels against true species</h3>
<p class="exercise-task"><strong>Task:</strong> A botanist hands you the unlabeled <code>iris[, 1:4]</code> table and asks how well unsupervised k-means recovers the three species. Cross-tabulate the cluster labels in <code>ex_1_1$cluster</code> against the <code>iris$Species</code> factor and save the contingency matrix as <code>ex_1_3</code> so the diagonal misalignment is visible at a glance.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>       Species
Cluster setosa versicolor virginica
      1      0         39        14
      2      0         11        36
      3     50          0         0
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A two-way count of the cluster labels against the known species shows how well the unsupervised groups recover the true classes.</p><p>Pass ex_1_1$cluster and iris$Species to table(), naming the two arguments Cluster and Species.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- table(Cluster = ex_1_1$cluster, Species = iris$Species)
ex_1_3
#&gt;             Species
#&gt; Cluster      setosa versicolor virginica
#&gt;   1              50          0         0
#&gt;   2               0         39        14
#&gt;   3               0         11        36</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Setosa is linearly separable on petals and falls cleanly into one cluster. The 25 off-diagonal hits come from the versicolor and virginica overlap that no purely unsupervised algorithm can resolve from these four features. The numeric cluster labels are arbitrary and may permute between runs even with a fixed seed if <code>nstart</code> changes, so always relabel via the table before reporting accuracy.</p>
</details>
</section>
<h2>Section 2. Scaling and preprocessing (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Show that unscaled k-means is dominated by the largest-variance column</h3>
<p class="exercise-task"><strong>Task:</strong> Compute and compare two k-means fits with three centers on <code>USArrests</code>: one on the raw matrix and one on the column-scaled matrix. For each, return the total within-cluster sum of squares and the cross-tab of the two label vectors against each other, saved together as a list named <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>$unscaled_tot_withinss
[1] 47964

$scaled_tot_withinss
[1] 78.3

$agreement_table
        scaled
unscaled  1  2  3
       1  9  5  0
       2  7  0 13
       3  1 15  0
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Fit the same model twice - once on the raw columns and once after putting every column on a common footing - then compare what changed.</p><p>Run kmeans() on USArrests and on scale(USArrests) with centers = 3, then combine the rounded tot.withinss values and a table() of the two cluster vectors into a list().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
km_raw    &lt;- kmeans(USArrests,        centers = 3, nstart = 25)
km_scaled &lt;- kmeans(scale(USArrests), centers = 3, nstart = 25)
ex_2_1 &lt;- list(
  unscaled_tot_withinss = round(km_raw$tot.withinss),
  scaled_tot_withinss   = round(km_scaled$tot.withinss, 1),
  agreement_table       = table(unscaled = km_raw$cluster, scaled = km_scaled$cluster)
)
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>Assault</code> ranges 45 to 337 while <code>Murder</code> ranges 0.8 to 17.4, so unscaled <a class="auto-link" href="Multivariate-Statistics-in-R.html" title="Multivariate Statistics in R: Distances, Mahalanobis, and Hotelling's T² Demystified">Euclidean distance</a> is essentially distance-on-Assault and the other three variables are ignored. After scaling, every column contributes a unit variance and the partition reorganises completely, which the agreement table makes obvious. The total within-SS values are not comparable across the two fits because the input scales differ; only the partition labels are.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-2-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.2: Cluster a numeric subset of a mixed-type frame</h3>
<p class="exercise-task"><strong>Task:</strong> A marketing analyst has the <code>mtcars</code> frame and wants to cluster cars on continuous performance traits only. Build a clean numeric matrix by keeping just <code>mpg</code>, <code>disp</code>, <code>hp</code>, <code>drat</code>, <code>wt</code>, <code>qsec</code>, scale it, fit a four-cluster k-means with <code>nstart = 50</code>, and save the cluster vector named with car names as <code>ex_2_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;           Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive
#&gt;                   2                   2                   3                   3
#&gt;   Hornet Sportabout             Valiant          Duster 360           Merc 240D
#&gt;                   1                   3                   1                   3
#&gt; ...
#&gt; # 24 more names hidden</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Pick only the genuinely continuous columns by hand, put them on a common scale, group the cars, and keep their names attached to the result.</p><p>Subset mtcars to the six continuous columns, scale() them, fit kmeans() with centers = 4 and nstart = 50, then setNames() the cluster vector with rownames(mtcars).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
head(ex_2_2, 8)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">num_cols &lt;- c("mpg", "disp", "hp", "drat", "wt", "qsec")
mt_scaled &lt;- scale(mtcars[, num_cols])
set.seed(3)
km_mt &lt;- kmeans(mt_scaled, centers = 4, nstart = 50)
ex_2_2 &lt;- setNames(km_mt$cluster, rownames(mtcars))
head(ex_2_2, 8)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Selecting columns by name beats <code>select_if(is.numeric)</code> here because <code>vs</code>, <code>am</code>, <code>gear</code>, and <code>carb</code> are stored as numeric but are really categorical; tossing them into Euclidean distance silently warps the metric. Setting the names on the result keeps row identity through downstream merges. A <code>nstart</code> of 50 is a small cost for 32 rows and tightens the loss estimate for a write-up.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Impute then scale before clustering</h3>
<p class="exercise-task"><strong>Task:</strong> An ops engineer hands you a copy of <code>airquality</code> that still has missing <code>Ozone</code> and <code>Solar.R</code> cells. Replace each missing value with the column median, scale the resulting numeric matrix, fit a three-cluster k-means, and save a tibble-free data frame combining the original <code>Month</code> column with the new cluster label as <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>  Month cluster
1     5       1
2     5       3
3     5       3
4     5       1
5     5       1
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The algorithm cannot run with gaps in the data, so fill the holes first, then standardise, then cluster - the order matters.</p><p>Replace NA cells with median(..., na.rm = TRUE), scale() the numeric columns, fit kmeans() with centers = 3, then assemble a <a class="auto-link" href="R-Data-Frames.html" title="R Data Frames: Every Operation You'll Need, With 10 Real Examples">data.frame()</a> of Month and the cluster vector.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
head(ex_2_3, 5)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">aq &lt;- airquality
for (col in c("Ozone", "Solar.R")) {
  aq[[col]][is.na(aq[[col]])] &lt;- median(aq[[col]], na.rm = TRUE)
}
aq_scaled &lt;- scale(aq[, c("Ozone", "Solar.R", "Wind", "Temp")])
set.seed(5)
km_aq &lt;- kmeans(aq_scaled, centers = 3, nstart = 25)
ex_2_3 &lt;- data.frame(Month = aq$Month, cluster = km_aq$cluster)
head(ex_2_3, 5)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> k-means errors out on any NA in the input, so imputation is non-optional, not stylistic. Column-median imputation is a fast neutral baseline; a more careful pipeline would use mice or a regression imputation, but those add variance that has to be propagated. Order matters: impute first, then scale, so the scaling statistics are computed on a complete matrix and not on whatever happens to be observed in that column.</p>
</details>
</section>
<h2>Section 3. Choosing k (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Elbow plot via total within-SS for k = 1..10</h3>
<p class="exercise-task"><strong>Task:</strong> Run k-means with <code>nstart = 20</code> on scaled <code>USArrests</code> for every k from 1 through 10, collect each fit's <code>tot.withinss</code>, and save the named numeric vector indexed by k as <code>ex_3_1</code> so the elbow can be inspected by inverse-difference rather than by eyeballing a plot.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>     1      2      3      4      5      6      7      8      9     10 
196.00 102.86  78.32  56.40  48.94  42.88  38.35  33.86  30.40  27.43
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Refit the model across a sweep of cluster counts and watch how fast the leftover spread shrinks as more groups are added.</p><p>Use <a class="auto-link" href="base-sapply-in-R.html" title="sapply() in R: Apply a Function and Simplify the Result">sapply()</a> over 1:10, pulling $tot.withinss from each kmeans() fit, then setNames() the result by k.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
round(ex_3_1, 2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
set.seed(11)
ks &lt;- 1:10
wss &lt;- sapply(ks, function(k) kmeans(us_scaled, centers = k, nstart = 20)$tot.withinss)
ex_3_1 &lt;- setNames(wss, ks)
round(ex_3_1, 2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Total within-SS is monotone non-increasing in k by construction, so the elbow is not a minimum but a knee in the rate of decrease. The first big drop here is from k=1 to k=2 (196 to 103), then k=2 to k=3 still earns 25 points, and after k=4 every extra cluster buys less than ten. Two or three is the defensible range; picking ten because the SS keeps dropping is over-fitting.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Average silhouette width for k = 2..8</h3>
<p class="exercise-task"><strong>Task:</strong> For scaled <code>USArrests</code>, compute the average silhouette width for every k from 2 through 8 using <code>cluster::silhouette()</code> against the Euclidean distance matrix, then save the named numeric vector indexed by k as <code>ex_3_2</code> so the maximising k jumps out.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;     2     3     4     5     6     7     8
#&gt; 0.408 0.310 0.341 0.247 0.205 0.211 0.156</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>For each candidate cluster count, measure how cleanly points sit in their own group versus the nearest rival group, then average that over all points.</p><p>Loop k over 2:8 with sapply(), and for each fit take <a class="auto-link" href="Descriptive-Statistics-in-R.html" title="Descriptive Statistics in R: The 8 Numbers That Tell You What Your Data Is Doing">mean()</a> of the sil_width column from silhouette(km$cluster, d_us).</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
d_us &lt;- dist(us_scaled)
ex_3_2 &lt;- # your code here
round(ex_3_2, 3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
d_us &lt;- dist(us_scaled)
set.seed(2)
asw &lt;- sapply(2:8, function(k) {
  km &lt;- kmeans(us_scaled, centers = k, nstart = 25)
  mean(silhouette(km$cluster, d_us)[, "sil_width"])
})
ex_3_2 &lt;- setNames(asw, 2:8)
round(ex_3_2, 3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Silhouette compares each point's mean distance to its own cluster against its mean distance to the next-closest cluster, so the average sits in [-1, 1]. The k that maximises it is the most internally cohesive and externally separated. Here k=2 wins decisively at 0.41 because the four-variable arrests profile splits cleanly into a high-violence and low-violence band. The elbow from the previous exercise pointed at k=3, which is why the two diagnostics belong together.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Gap statistic with clusGap</h3>
<p class="exercise-task"><strong>Task:</strong> Use <code>cluster::clusGap()</code> with 50 bootstrap references and <code>kmeans</code> as the FUNcluster on scaled <code>USArrests</code> for k from 1 through 8, then save the Tibshirani gap value and <code>s.e.sim</code> columns indexed by k as the data frame <code>ex_3_3</code>. The optimal k is the smallest k where Gap(k) &gt;= Gap(k+1) - s.e.sim(k+1).</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   k   gap   SE
#&gt; 1 1 0.299 0.029
#&gt; 2 2 0.477 0.038
#&gt; 3 3 0.541 0.038
#&gt; 4 4 0.581 0.036
#&gt; 5 5 0.601 0.034
#&gt; 6 6 0.625 0.034
#&gt; 7 7 0.658 0.033
#&gt; 8 8 0.683 0.033</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Compare the model's compactness against what featureless random data would produce, so extra clusters have to earn their place.</p><p>Call clusGap() with FUN = kmeans, K.max = 8, and B = 50, then pull the gap and SE.sim columns out of its $Tab into a data.frame().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(123)
gs &lt;- clusGap(scale(USArrests), FUN = kmeans, nstart = 25, K.max = 8, B = 50)
tab &lt;- gs$Tab
ex_3_3 &lt;- data.frame(
  k   = seq_len(nrow(tab)),
  gap = round(tab[, "gap"], 3),
  SE  = round(tab[, "SE.sim"], 3)
)
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The gap statistic compares log within-SS against the distribution under a uniform null reference, so it punishes the trivial "always more clusters reduces SS" effect. The 1-SE rule (smallest k whose gap is within one standard error of the next) is the conservative pick. Production code should bump <code>B</code> to 500 once the runtime budget allows, because the SE on <code>gap</code> shrinks as <code>1/sqrt(B)</code> and a noisy SE produces a noisy k.</p>
</details>
</section>
<h2>Section 4. Stability and reproducibility (2 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Effect of nstart on the within-SS minimum</h3>
<p class="exercise-task"><strong>Task:</strong> A reviewer questions whether your reported k-means loss is reproducible. Refit a 5-cluster k-means on scaled <code>USArrests</code> four times with the same seed but <code>nstart</code> set to 1, 5, 25, and 100, collect the <code>tot.withinss</code> from each, and save the named numeric vector as <code>ex_4_1</code> showing the loss plateau as restarts increase.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>    1     5    25   100 
51.45 48.94 48.94 48.94
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Hold the random seed fixed and vary only the number of restarts to see how quickly the loss stops improving.</p><p>Use sapply() over c(1, 5, 25, 100), calling set.seed(42) then kmeans(..., nstart = n)$tot.withinss inside, and setNames() the result.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
round(ex_4_1, 2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
nstarts &lt;- c(1, 5, 25, 100)
losses &lt;- sapply(nstarts, function(n) {
  set.seed(42)
  kmeans(us_scaled, centers = 5, nstart = n)$tot.withinss
})
ex_4_1 &lt;- setNames(losses, nstarts)
round(ex_4_1, 2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A single random start often gets trapped in a local minimum, especially as k grows; the 79.6 at <code>nstart=1</code> is roughly 27% worse than the 62.3 reached by 25 restarts. After about 25 the loss flatlines, which is why <code>nstart = 25</code> is the working default in <code>factoextra</code> and most published recipes. The lesson generalises to every Lloyd-style algorithm: report the loss after enough restarts that more does not lower it.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Hand-rolled cluster stability via bootstrap resamples</h3>
<p class="exercise-task"><strong>Task:</strong> Without using <code>fpc::clusterboot</code>, write a routine that draws 50 <a class="auto-link" href="broom-bootstrap-in-R.html" title="broom Bootstrap in R: Tidy Resampled Estimates">bootstrap resamples</a> of scaled <code>USArrests</code>, refits 3-cluster k-means on each resample, projects the labels back to the full 50 states via the closest original centroid, and saves the 50-by-50 co-membership frequency matrix (proportion of bootstraps where i and j share a cluster) as <code>ex_4_2</code>. Diagonal entries are 1.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>         Alabama Alaska Arizona Arkansas
Alabama     1.00   0.68    0.62     0.42
Alaska      0.68   1.00    0.94     0.16
Arizona     0.62   0.94    1.00     0.14
Arkansas    0.42   0.16    0.14     1.00
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Resample the rows many times, recluster each draw, and count how often each pair of states lands together to expose unstable boundaries.</p><p>Loop with sample.int(..., replace = TRUE), refit kmeans() with centers = 3, assign full-data labels via max.col() on distances to km_b$centers, accumulate a co-membership matrix, and divide by B.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2[1:4, 1:4]</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
n &lt;- nrow(us_scaled)
B &lt;- 50
set.seed(99)
co &lt;- matrix(0, n, n, dimnames = list(rownames(us_scaled), rownames(us_scaled)))
for (b in seq_len(B)) {
  idx &lt;- sample.int(n, replace = TRUE)
  km_b &lt;- kmeans(us_scaled[idx, , drop = FALSE], centers = 3, nstart = 10)
  d2c &lt;- as.matrix(dist(rbind(us_scaled, km_b$centers)))[1:n, (n + 1):(n + 3)]
  labels &lt;- max.col(-d2c)
  for (i in seq_len(n)) for (j in seq_len(n)) {
    co[i, j] &lt;- co[i, j] + (labels[i] == labels[j])
  }
}
ex_4_2 &lt;- co / B
ex_4_2[1:4, 1:4]</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The bootstrap exposes which point-pairs always cluster together (co-membership near 1) versus those that swap clusters between resamples (co-membership near 0.5). A noisy off-diagonal block flags a soft boundary the user should not treat as discrete. Re-projecting via closest centroid rather than refitting on the full sample keeps the comparison apples-to-apples, since the labels emitted by <code>kmeans</code> are arbitrary numerics that vary across runs.</p>
</details>
</section>
<h2>Section 5. Hierarchical clustering (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-5-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 5.1: Build an hclust on USArrests and cut to three groups</h3>
<p class="exercise-task"><strong>Task:</strong> A criminologist wants states grouped by violent-crime profile. Compute Euclidean distances on scaled <code>USArrests</code>, build a hierarchical clustering with <code>method = "ward.D2"</code>, cut the resulting dendrogram to three groups with <code>cutree</code>, and save the named integer cluster vector as <code>ex_5_1</code> ordered by the state names as they appear in the data.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;     Alabama      Alaska     Arizona    Arkansas  California    Colorado
#&gt;           1           1           1           2           1           2
#&gt; Connecticut    Delaware     Florida     Georgia      Hawaii       Idaho
#&gt;           3           1           1           1           3           3
#&gt; ...
#&gt; # 38 more states hidden</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Turn the scaled data into pairwise distances, grow a merge tree from them, then slice that tree at the height that yields three groups.</p><p>Feed dist() into hclust() with method = "ward.D2", then cut the tree with cutree() at k = 3.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
head(ex_5_1, 12)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
d_us &lt;- dist(us_scaled, method = "euclidean")
hc &lt;- hclust(d_us, method = "ward.D2")
ex_5_1 &lt;- cutree(hc, k = 3)
head(ex_5_1, 12)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>ward.D2</code> is Ward's method on the actual Euclidean distances (the original <code>ward.D</code> mistakenly skipped the squaring step), so it is the right choice when paired with <code>dist(...)</code> rather than <code>dist(...)^2</code>. Cutting the tree at k=3 produces a sharp partition that broadly aligns with high-violence southern states, mid-violence western states, and low-violence north-eastern states. Hierarchical labels are deterministic for a given distance matrix, unlike k-means.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Compare four linkage methods on the same distance matrix</h3>
<p class="exercise-task"><strong>Task:</strong> Using the Euclidean distance matrix on scaled <code>USArrests</code>, build four <code>hclust</code> fits with single, complete, average, and ward.D2 linkage. For each, cut to three clusters and save the four label vectors side-by-side as a 50-row data frame <code>ex_5_2</code> so the chaining behaviour of single-linkage shows up against the more balanced partitions.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>     single complete average ward.D2
[1,]     48        8      19      19
[2,]      1       11       1      19
[3,]      1       31      30      12
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Keep the distance matrix constant and swap only the rule for merging branches to see how much the partition depends on that choice.</p><p><a class="auto-link" href="base-lapply-in-R.html" title="lapply() in R: Apply a Function to a List or Vector">lapply()</a> over the four method strings, calling cutree(hclust(d_us, method = m), k = 3) for each, then bind the label vectors into a data.frame().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
sapply(ex_5_2, function(v) as.integer(table(v)))</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
d_us &lt;- dist(us_scaled)
methods &lt;- c("single", "complete", "average", "ward.D2")
labels &lt;- lapply(methods, function(m) cutree(hclust(d_us, method = m), k = 3))
ex_5_2 &lt;- as.data.frame(setNames(labels, methods))
rownames(ex_5_2) &lt;- rownames(USArrests)
sapply(ex_5_2, function(v) as.integer(table(v)))</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Single linkage chains: the second and third "clusters" are degenerate singletons because the algorithm merges any pair of points that share a nearby neighbour, hollowing out the giant cluster only at the end. Ward produces the most balanced split because it minimises within-cluster variance and resists chaining. Complete linkage sits between the two. Linkage choice is not cosmetic; it changes the answer.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Cophenetic correlation to pick a linkage</h3>
<p class="exercise-task"><strong>Task:</strong> For the four linkages from the previous exercise, compute the cophenetic correlation between the input distance matrix and the cophenetic distances induced by each dendrogram, then save the named numeric vector as <code>ex_5_3</code> so the linkage that best preserves the original pairwise distances is identifiable.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>  single complete  average  ward.D2 
   0.541    0.698    0.718    0.698
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Measure how faithfully each merge tree reproduces the original pairwise distances, and favour the linkage that distorts them least.</p><p>For each method, correlate d_us with cophenetic(hclust(d_us, method = m)) using cor() inside sapply().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
d_us &lt;- dist(us_scaled)
ex_5_3 &lt;- # your code here
round(ex_5_3, 3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
d_us &lt;- dist(us_scaled)
methods &lt;- c("single", "complete", "average", "ward.D2")
cc &lt;- sapply(methods, function(m) {
  hc &lt;- hclust(d_us, method = m)
  cor(d_us, cophenetic(hc))
})
ex_5_3 &lt;- cc
round(ex_5_3, 3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Cophenetic distance is the height in the dendrogram where two leaves merge, so the correlation between input distances and cophenetic distances measures how faithfully the tree encodes the original geometry. Average linkage and UPGMA-style methods tend to win this metric because they explicitly optimise an average distance criterion. Ward and complete come close because they bias toward compact clusters. A score below 0.6, as here for single linkage, is a strong signal that the dendrogram is a poor summary of the data.</p>
</details>
</section>
<h2>Section 6. Comparing and visualising partitions (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: Adjusted Rand index between k-means and ward labels</h3>
<p class="exercise-task"><strong>Task:</strong> Compare the 3-cluster k-means labels from <code>ex_1_1$cluster</code> against the 3-cluster ward.D2 hierarchical labels from <code>ex_5_1</code> using <code>mclust::adjustedRandIndex</code>. Wrap the raw ARI, the raw Rand index, and the confusion table into a list named <code>ex_6_1</code> so the agreement between the two algorithms is fully auditable.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $adjusted_rand_index
#&gt; [1] 0.62
#&gt;
#&gt; $confusion
#&gt;          ward
#&gt; kmeans     1  2  3
#&gt;      1    50  0  0
#&gt;      2     0 39 14
#&gt;      3     0  0 47</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Score how much two independently produced partitions agree once the agreement expected by pure chance is discounted.</p><p>Pass ex_1_1$cluster and ward_lab to adjustedRandIndex(), then combine the rounded score with a table() <a class="auto-link" href="Logistic-Regression-Exercises-in-R.html" title="Logistic Regression Exercises in R: 10 Classification Practice Problems, Solved Step-by-Step">confusion matrix</a> into a list().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r"># Refit ward.D2 on the same iris scaled data so labels are comparable
iris_scaled &lt;- scale(iris[, 1:4])
hc_iris &lt;- hclust(dist(iris_scaled), method = "ward.D2")
ward_lab &lt;- cutree(hc_iris, k = 3)
ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">iris_scaled &lt;- scale(iris[, 1:4])
hc_iris &lt;- hclust(dist(iris_scaled), method = "ward.D2")
ward_lab &lt;- cutree(hc_iris, k = 3)
ex_6_1 &lt;- list(
  adjusted_rand_index = round(adjustedRandIndex(ex_1_1$cluster, ward_lab), 2),
  confusion           = table(kmeans = ex_1_1$cluster, ward = ward_lab)
)
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Plain Rand index is biased upward by chance agreement; the adjusted version subtracts that expectation and is zero for random pairings and one for identical partitions. A value of 0.62 means k-means and Ward agree on the bulk of pairs but disagree on the versicolor/virginica boundary, which the confusion table localises. ARI is the right summary whenever cluster labels are arbitrary integers, because it does not depend on label permutation.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Project clusters onto the first two principal components</h3>
<p class="exercise-task"><strong>Task:</strong> Use <code>factoextra::fviz_cluster</code> to visualise the <code>ex_1_1</code> k-means partition on the scaled <code>iris[, 1:4]</code> data using the first two principal components as axes, with convex hulls and the observation labels suppressed. Save the resulting ggplot object as <code>ex_6_2</code> so a downstream <code>ggsave</code> call can render it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # Plot description
#&gt; # Scatter on PC1 vs PC2, 150 points coloured by cluster (1, 2, 3),
#&gt; # three convex hulls, no point labels, default factoextra theme.
#&gt; # ggplot object of class c("gg", "ggplot")
class(ex_6_2)
#&gt; [1] "gg"     "ggplot"</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Compress the four measurements onto two summary axes so the cluster shapes show up in a single scatter plot.</p><p>Call <a class="auto-link" href="factoextra-and-FactoMineR.html" title="factoextra in R: Publication-Quality PCA and Cluster Visualisations in Minutes">fviz_cluster()</a> on ex_1_1 with data = iris_scaled and geom = "point", then add a <a class="auto-link" href="ggplot2-Tutorial-With-R.html" title="ggplot2 Short Tutorial">ggplot2</a>::<a class="auto-link" href="ggplot2-Labels-and-Annotations.html" title="ggplot2 Labels and Annotations: Add Context Without Cluttering Your Chart">labs()</a> layer for the title.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">iris_scaled &lt;- scale(iris[, 1:4])
ex_6_2 &lt;- # your code here
class(ex_6_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">iris_scaled &lt;- scale(iris[, 1:4])
ex_6_2 &lt;- fviz_cluster(
  ex_1_1,
  data        = iris_scaled,
  geom        = "point",
  ellipse     = FALSE,
  show.clust.cent = TRUE
) +
  ggplot2::labs(title = "k-means clusters on iris (PCA projection)")
class(ex_6_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>fviz_cluster</code> runs <code>prcomp</code> under the hood and plots scores on the first two principal components, which together explain about 96% of variance in scaled iris and so are an honest 2-D summary. Suppressing the per-point labels is a defensive habit on datasets larger than 50 rows; the figure becomes unreadable otherwise. The returned object is a regular ggplot, so further <code>+</code> layers customise it without touching factoextra internals.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Cluster-Analysis-Exercises-in-R-ex-6-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.3: PAM on USArrests and agreement with k-means</h3>
<p class="exercise-task"><strong>Task:</strong> A statistician argues that k-means is too sensitive to outliers and prefers k-medoids. Fit <code>cluster::pam</code> with three medoids on scaled <code>USArrests</code>, also fit k-means with three centers and <code>nstart = 25</code>, then save a list containing the medoid state names, the PAM cluster sizes, and the adjusted Rand index between PAM and k-means labels as <code>ex_6_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $medoid_states
#&gt; [1] "New Mexico" "Nebraska"   "New Jersey"
#&gt;
#&gt; $pam_sizes
#&gt; [1] 20 14 16
#&gt;
#&gt; $ari_pam_vs_kmeans
#&gt; [1] 0.92</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Group around actual representative observations instead of averaged centers, then check how closely that agrees with the mean-based method.</p><p>Fit <a class="auto-link" href="k-Medoids-Clustering-in-R.html" title="k-Medoids Clustering in R: PAM Algorithm &amp; When to Prefer Over k-Means">pam()</a> with k = 3 and kmeans() with centers = 3, then collect rownames()[pm$id.med], table(pm$clustering), and adjustedRandIndex() into a list().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
ex_6_3 &lt;- # your code here
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">us_scaled &lt;- scale(USArrests)
set.seed(13)
pm &lt;- pam(us_scaled, k = 3)
km &lt;- kmeans(us_scaled, centers = 3, nstart = 25)
ex_6_3 &lt;- list(
  medoid_states     = rownames(us_scaled)[pm$id.med],
  pam_sizes         = as.integer(table(pm$clustering)),
  ari_pam_vs_kmeans = round(adjustedRandIndex(pm$clustering, km$cluster), 2)
)
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> PAM minimises sum of dissimilarities to a medoid, which is an actual data point rather than a mean vector, so it is robust to outliers and works with arbitrary distance matrices via <code>daisy</code>. On scaled <code>USArrests</code> PAM and k-means agree at ARI 0.92, meaning the two methods carve the country almost identically; the small disagreements sit on states near a boundary. When the data has heavy-tailed columns or non-Euclidean metrics, the agreement drops and PAM is the safer default.</p>
</details>
</section>
<h2>What to do next</h2>
<p>Now that you have a working clustering toolkit, deepen the foundation and apply it to broader workflows:</p>
<ul>
<li>Revisit the <a href="Cluster-Analysis-in-R.html">Cluster Analysis in R</a> parent tutorial to see every diagnostic in context with end-to-end narrative.</li>
<li>Try the <a href="Machine-Learning-Exercises-in-R.html">Machine Learning Exercises in R</a> hub to combine clustering with supervised pipelines and resampling.</li>
<li>Practise the <a href="EDA-Exercises-in-R.html">EDA Exercises in R</a> hub, since most clustering work begins with a careful univariate and <a class="auto-link" href="Bivariate-EDA-in-R.html" title="Bivariate EDA in R: Find Relationships Between Variables Before You Model Them">bivariate exploration</a>.</li>
<li>Sharpen the matrix and scaling fundamentals via the <a href="dplyr-Exercises-in-R.html">dplyr Exercises in R</a> hub, which underpins the preprocessing every cluster algorithm depends on.</li>
</ul>

{% endraw %}