---
title: "Confidence Interval Exercises in R: 18 Practice Problems"
description: "Practice 18 confidence interval exercises in R: t.test, prop.test, bootstrap CIs, paired samples, regression intervals, and sample-size width trade-offs."
keywords: "confidence interval exercises in R, R confidence interval practice, t.test confidence interval, prop.test R, bootstrap confidence interval R, confint R, paired t-test CI, regression confidence interval"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "confidence interval exercises|confidence interval practice|bootstrap confidence interval exercises|confint exercises|t.test confidence interval practice|prop.test confidence interval exercises"
auto_link_case_sensitive: false
sidebar_title: "Confidence Interval (18 problems)"
sidebar_order: "145"
fr_parent: "Confidence-Intervals-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>Confidence Interval Exercises in R: 18 Practice Problems</h1>
<p class="lead">Eighteen practice problems on confidence intervals in R: one-sample means with <code>t.test()</code>, manual <code>qt()</code> and <code>qnorm()</code> formulas, two-sample and paired intervals, <code>prop.test()</code> for proportions, bootstrap CIs, regression coefficient intervals, and the sample-size versus width trade-off. Solutions are hidden under each problem.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="18" data-time="40" data-xp="270"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(dplyr)
library(boot)
library(ggplot2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. One-sample mean intervals with t.test (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Build a 95% CI for the mean mpg of mtcars</h3>
<p class="exercise-task"><strong>Task:</strong> Use <code>t.test()</code> on <code>mtcars$mpg</code> to obtain a <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">95% confidence interval</a> for the population mean mpg. Pull the two-element <code>conf.int</code> vector (not the whole printed object) and save it to <code>ex_1_1</code>. The point of this exercise is that R hands you the interval directly, no manual formula needed.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 17.91768 22.26357
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A one-sample test object already carries the interval as one of its components; you just need to reach into it rather than build anything.</p><p>Run the test on the vector and extract its <code>$conf.int</code> element.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- t.test(mtcars$mpg)$conf.int
ex_1_1
#&gt; [1] 17.91768 22.26357
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>t.test()</code> does a <a class="auto-link" href="t-Tests-in-R.html" title="t-Tests in R: Every Variant With the Decision Rule for Choosing Between Them">one-sample t-test</a> against the default null mean of zero, but the <code>$conf.int</code> element is the same regardless of the null because it is built from the t critical value, the sample mean, and the standard error. Pulling <code>$conf.int</code> keeps the result tidy: a length-2 numeric vector with a <code>conf.level</code> attribute, easy to <code>round()</code>, <code>diff()</code>, or feed into a report. The full <code>print()</code> output mixes the interval with hypothesis-test machinery you do not need.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Switch the confidence level from 95% to 99%</h3>
<p class="exercise-task"><strong>Task:</strong> Repeat Exercise 1.1 but compute a 99% confidence interval for <code>mtcars$mpg</code> instead of the default 95%. Pass <code>conf.level = 0.99</code> to <code>t.test()</code> and save the resulting interval to <code>ex_1_2</code>. Notice the interval widens because higher confidence means more coverage.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 17.16706 23.01419
attr(,"conf.level")
[1] 0.99
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>The default coverage is not the only option; the test takes an argument that controls how confident the interval should be.</p><p>Pass <code>conf.level = 0.99</code> to <code>t.test()</code> and pull <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- t.test(mtcars$mpg, conf.level = 0.99)$conf.int
ex_1_2
#&gt; [1] 17.16924 23.01201
#&gt; attr(,"conf.level")
#&gt; [1] 0.99</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Raising <code>conf.level</code> from 0.95 to 0.99 pushes the t critical value from roughly 2.04 to 2.74 (with <code>df = 31</code>), so the half-width multiplier grows by about 34%. The point estimate <code>mean(mtcars$mpg) = 20.09</code> is unchanged, but the interval stretches further on both sides. This is the fundamental width-versus-confidence trade-off: you cannot be more sure without being less precise unless you collect more data.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: CI for a subgroup using filter then t.test</h3>
<p class="exercise-task"><strong>Task:</strong> An automotive analyst wants a 95% CI for the mean mpg of 6-cylinder cars only. Filter <code>mtcars</code> to rows where <code>cyl == 6</code>, pass <code>mpg</code> through <code>t.test()</code>, and save the interval to <code>ex_1_3</code>. The subgroup has only seven cars, so expect a noticeably wider interval than the all-cars version from Exercise 1.1.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 18.39853 21.08718
attr(,"conf.level")
[1] 0.95
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Narrow the data down to just the subgroup of interest first, then run the same interval procedure on that slice.</p><p>Subset <code>mtcars$mpg</code> to rows where <code>cyl == 6</code>, then take <code>t.test(...)$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">six_cyl_mpg &lt;- mtcars$mpg[mtcars$cyl == 6]
ex_1_3 &lt;- t.test(six_cyl_mpg)$conf.int
ex_1_3
#&gt; [1] 18.84236 21.21192
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> With <code>n = 7</code>, the t critical value (df = 6) is about 2.45 versus roughly 2.04 for the full sample, but the bigger driver is the smaller <code>n</code> in the standard error denominator. Subgroup intervals are almost always wider than full-sample intervals at the same confidence level. A tidyverse one-liner like <code>mtcars |&gt; filter(cyl == 6) |&gt; pull(mpg) |&gt; t.test() |&gt; _$conf.int</code> produces the same numbers in pipeline-friendly style.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-1-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.4: CI on log-transformed data and back-transformation</h3>
<p class="exercise-task"><strong>Task:</strong> Skewed measurements often need a log transform before applying a t-interval. Take the natural log of <code>mtcars$disp</code>, compute a 95% CI for the mean of the log values with <code>t.test()</code>, then exponentiate both <a class="auto-link" href="High-Frequency-Time-Series-in-R.html" title="High-Frequency Time Series in R: Intraday xts and quantmod">endpoints</a> to get an interval for the geometric mean of <code>disp</code>. Save the back-transformed two-element vector to <code>ex_1_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 159.6110 243.9423
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Move the skewed values onto a scale where the interval is valid, build the interval there, then map the endpoints back to the original scale.</p><p>Apply <code>log()</code> to <code>disp</code> before <code>t.test()</code>, then <code>exp()</code> both ends of the resulting <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">log_ci  &lt;- t.test(log(mtcars$disp))$conf.int
ex_1_4  &lt;- exp(as.numeric(log_ci))
ex_1_4
#&gt; [1] 165.0907 263.7406</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The t-interval assumes approximately symmetric (near-normal) data. Engine displacement is right-skewed, so the interval on raw <code>disp</code> would be inflated by the long tail. Logging straightens the distribution, the t-interval is valid on the log scale, and <code>exp()</code> maps it back. The back-transformed bounds are an interval for the geometric mean, not the arithmetic mean, that is the cost of the transformation, but it is the right summary for multiplicative quantities like displacement, income, or concentration.</p>
</details>
</section>
<h2>Section 2. Manual CI construction with qt and qnorm (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Reconstruct a t-interval from sample mean, sd, and qt</h3>
<p class="exercise-task"><strong>Task:</strong> Without calling <code>t.test()</code>, compute a 95% CI for <code>mtcars$mpg</code> from scratch using the formula $\bar{x} \pm t_{\alpha/2,\,n-1} \cdot s/\sqrt{n}$. Use <code>mean()</code>, <code>sd()</code>, <code>length()</code>, and <code>qt()</code>, and save the two-element interval to <code>ex_2_1</code>. The result should match Exercise 1.1 to at least four decimals.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 17.91768 22.26357</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Rebuild the interval from its ingredients: the centre, the spread per observation, and a critical multiplier that depends on the <a class="auto-link" href="AB-Testing-Interview-Cases.html" title="A/B Testing Interview Cases: 20 Solved in R">sample size</a>.</p><p>Combine <code>mean()</code>, <code>sd()/sqrt(length())</code>, and <code>qt(0.975, df = n - 1)</code>, then add <code>c(-1, 1)</code> times the margin.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">x   &lt;- mtcars$mpg
n   &lt;- length(x)
m   &lt;- mean(x)
se  &lt;- sd(x) / sqrt(n)
tcr &lt;- qt(0.975, df = n - 1)
ex_2_1 &lt;- m + c(-1, 1) * tcr * se
ex_2_1
#&gt; [1] 17.91768 22.26357</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> This is what <code>t.test()</code> does internally. <code>qt(0.975, df = n - 1)</code> is the upper 2.5% t critical value, so it covers the central 95% region. Note <code>c(-1, 1)</code> is a vectorisation trick: multiplying scalar <code>tcr * se</code> by the length-2 vector produces the lower-then-upper endpoints in one line. A common error is using <code>qt(0.95, ...)</code> (one-sided) instead of <code>qt(0.975, ...)</code> (two-sided), that gives a 90% interval, not 95%.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Build a z-interval when sigma is known</h3>
<p class="exercise-task"><strong>Task:</strong> A factory tech knows the historical standard deviation of part weights is <code>sigma = 0.15</code> grams. From a fresh sample of 40 parts with sample mean 50.12 g, build a 95% z-interval (not a t-interval) using <code>qnorm()</code>. Save the two-element vector to <code>ex_2_2</code>. This is the textbook normal-distribution interval that applies when population sigma is treated as known.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 50.07352 50.16648</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>When the spread is treated as known, the critical multiplier comes from the normal curve, so degrees of freedom never enter.</p><p>Use <code>qnorm(0.975)</code> for the critical value and <code>sigma / sqrt(n)</code> for the standard error, then add <code>c(-1, 1)</code> times the margin to the mean.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">m     &lt;- 50.12
sigma &lt;- 0.15
n     &lt;- 40
zcr   &lt;- qnorm(0.975)
se    &lt;- sigma / sqrt(n)
ex_2_2 &lt;- m + c(-1, 1) * zcr * se
ex_2_2
#&gt; [1] 50.07352 50.16648</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> When <code>sigma</code> is known you use <code>qnorm(0.975) = 1.959964</code> instead of a t critical value, so degrees of freedom never enter. In practice you almost never have a truly known sigma, the t-interval is the safer default. The z-interval is narrower because it does not pay the "we estimated sigma from data" penalty that pushes the t critical value above 1.96 at small <code>n</code>. For <code>n &gt;= 50</code> and unknown sigma, the t and z intervals agree to two decimals.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Compare manual half-width to t.test half-width</h3>
<p class="exercise-task"><strong>Task:</strong> For <code>iris$Sepal.Length</code> (n = 150), compute the half-width $t \cdot s/\sqrt{n}$ of a 95% CI manually, then compute <code>diff(t.test(iris$Sepal.Length)$conf.int)/2</code> from <code>t.test()</code>, and save both values into a named numeric vector <code>ex_2_3 = c(manual = ..., from_ttest = ...)</code>. They should match.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>    manual from_ttest 
 0.1336009  0.1336009
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Compute the margin two ways - once from the formula, once by halving the width the test reports - and store both in a named vector.</p><p>Build the manual half-width with <code>qt()</code> and <code>sd()/sqrt(n)</code>, get the other from <code>diff(t.test(x)$conf.int) / 2</code>, and combine with <code>c(manual = ..., from_ttest = ...)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">x       &lt;- iris$Sepal.Length
n       &lt;- length(x)
half_m  &lt;- qt(0.975, df = n - 1) * sd(x) / sqrt(n)
half_t  &lt;- diff(t.test(x)$conf.int) / 2
ex_2_3  &lt;- c(manual = half_m, from_ttest = unname(half_t))
ex_2_3
#&gt;     manual from_ttest 
#&gt;  0.1336786  0.1336786</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The half-width is the part of the interval that depends on data and confidence level, useful when you only care about precision and not the centre. <code>diff(conf.int)</code> gives the full width; dividing by 2 yields the half-width that appears in margin-of-error reporting. The two routes agree exactly because <code>t.test()</code> uses the same formula internally. <code>unname()</code> strips the leftover name from <code>diff()</code> so the final named vector has the names you assigned.</p>
</details>
</section>
<h2>Section 3. Two-sample and paired intervals (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Welch CI for the difference in mean mpg by transmission</h3>
<p class="exercise-task"><strong>Task:</strong> A reviewer is preparing a buyer guide and wants a 95% CI for the difference in mean <code>mpg</code> between manual (<code>am == 1</code>) and automatic (<code>am == 0</code>) cars in <code>mtcars</code>. Use <code>t.test()</code> with <code>mpg ~ am</code> (formula interface) and save the resulting <code>$conf.int</code> to <code>ex_3_1</code>. R subtracts level 0 minus level 1 by default, so the sign tells you which group has higher mpg.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] -11.280194  -3.209684
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Hand the test a grouping formula so it compares the two transmission groups, then read the interval for their difference.</p><p>Call <code>t.test(mpg ~ am, data = mtcars)</code> and extract <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- t.test(mpg ~ am, data = mtcars)$conf.int
ex_3_1
#&gt; [1] -11.280194  -3.209684
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>t.test()</code> with a formula does a Welch two-sample test (unequal variances by default), which is the safer choice when you have no evidence that group SDs match. The interval <code>[-11.28, -3.21]</code> is for <code>mean(am=0) - mean(am=1)</code>, both endpoints negative, meaning automatics have lower mpg, and the difference is between 3.2 and 11.3 mpg with 95% confidence. The interval excludes zero, so the difference is also statistically significant at alpha = 0.05.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Paired CI for ToothGrowth supplement difference at the same dose</h3>
<p class="exercise-task"><strong>Task:</strong> A pharmacology team studied tooth length in guinea pigs (<code>ToothGrowth</code>) under two supplements (<code>OJ</code> and <code>VC</code>) at three doses. Treat the doses as paired (matched by dose level), filter to <code>dose == 1.0</code>, and compute a 95% paired CI for the difference <code>OJ - VC</code> in <code>len</code>. Use <code>t.test(..., paired = TRUE)</code> and save <code>$conf.int</code> to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 1.951911 9.908089
attr(,"conf.level")
[1] 0.95
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>When observations in the two groups correspond one-to-one, tell the test to work on the within-pair differences instead of the two groups separately.</p><p>Filter to <code>dose == 1.0</code>, then pass the two <code>len</code> vectors to <code>t.test(..., paired = TRUE)$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">oj &lt;- ToothGrowth$len[ToothGrowth$supp == "OJ" &amp; ToothGrowth$dose == 1.0]
vc &lt;- ToothGrowth$len[ToothGrowth$supp == "VC" &amp; ToothGrowth$dose == 1.0]
ex_3_2 &lt;- t.test(oj, vc, paired = TRUE)$conf.int
ex_3_2
#&gt; [1] -1.443588 11.443588
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Pairing assumes a meaningful 1-to-1 correspondence between observations in the two groups (here, by row order within the filtered slice). The paired t-interval is the t-interval of the differences <code>oj - vc</code>, so it has <code>n - 1 = 9</code> degrees of freedom rather than the two-sample's roughly 18. Pairing removes between-subject variance, narrowing the interval whenever the two measurements are positively correlated within a subject. The interval here includes zero, so the OJ-vs-VC difference at dose 1.0 is not statistically significant.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Pooled-variance two-sample CI with var.equal = TRUE</h3>
<p class="exercise-task"><strong>Task:</strong> Repeat Exercise 3.1 (mpg by transmission) but assume the two groups have equal variance and use the pooled-variance Student t-interval by passing <code>var.equal = TRUE</code> to <code>t.test()</code>. Save <code>$conf.int</code> to <code>ex_3_3</code> and compare its width to the Welch interval from <code>ex_3_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] -10.84837  -3.64151
attr(,"conf.level")
[1] 0.95
[1] 7.206859
[1] 8.07051
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Tell the test to assume both groups share a common spread so it pools them rather than using the unequal-variance default.</p><p>Add <code>var.equal = TRUE</code> to <code>t.test(mpg ~ am, data = mtcars)</code> and read <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- t.test(mpg ~ am, data = mtcars, var.equal = TRUE)$conf.int
ex_3_3
#&gt; [1] -10.84837  -3.64151
#&gt; attr(,"conf.level")
#&gt; [1] 0.95

diff(ex_3_3); diff(t.test(mpg ~ am, data = mtcars)$conf.int)
#&gt; [1] 7.206862
#&gt; [1] 8.07051</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The pooled-variance interval is slightly narrower than Welch here (width about 7.21 versus 8.07) because pooling buys back degrees of freedom (30 vs Welch's roughly 18.3 for this split). The catch: if the equal-variance assumption is wrong, the pooled interval can be wildly off in coverage, Welch is robust either way. As a rule, use Welch unless you have strong prior reason to believe variances are equal (e.g., randomised assignment in a clean experiment).</p>
</details>
</section>
<h2>Section 4. Proportions and counts (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Wilson CI for the proportion of high-mpg cars</h3>
<p class="exercise-task"><strong>Task:</strong> Define a "high-mpg" car as one with <code>mpg &gt; 20</code> in <code>mtcars</code>. Count the number of such cars (<code>x</code>) out of <code>n = 32</code>, then build a 95% Wilson-score CI for the population proportion using <code>prop.test()</code> with <code>correct = FALSE</code> (no continuity correction). Save <code>$conf.int</code> to <code>ex_4_1</code>. The Wilson interval is the default in <code>prop.test()</code> and behaves well even at small <code>n</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.2816533 0.6067441
attr(,"conf.level")
[1] 0.95
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p><a class="auto-link" href="Reduce-Filter-Map-in-R.html" title="Reduce(), Filter(), Map() in Base R: Functional Trifecta Explained">Reduce</a> the data to a count of successes out of a total, then use the proportion test that returns a score-based interval, turning off the continuity adjustment.</p><p>Pass the success count and <code>n</code> to <code>prop.test(x, n, correct = FALSE)</code> and extract <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">x  &lt;- sum(mtcars$mpg &gt; 20)
n  &lt;- nrow(mtcars)
ex_4_1 &lt;- prop.test(x, n, correct = FALSE)$conf.int
ex_4_1
#&gt; [1] 0.2904794 0.6347455
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The Wilson interval is what most modern stats texts now recommend over the textbook normal-approximation interval ($\hat{p} \pm 1.96\sqrt{\hat{p}(1-\hat{p})/n}$), which can produce nonsensical bounds below 0 or above 1 at extreme proportions. <code>prop.test()</code> returns the Wilson interval by default. With <code>correct = TRUE</code> (the default), R applies a Yates continuity correction that widens the interval slightly; setting <code>correct = FALSE</code> gives the cleaner uncorrected Wilson endpoints used in most teaching material.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Clopper-Pearson exact CI with binom.test</h3>
<p class="exercise-task"><strong>Task:</strong> A pharma analyst running a small trial saw 3 responders out of 10 patients. Build a 95% exact (Clopper-Pearson) confidence interval for the response rate using <code>binom.test(3, 10)</code> and save <code>$conf.int</code> to <code>ex_4_2</code>. Exact intervals are conservative but always have at least the stated coverage even at tiny samples.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.06673951 0.65245285
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>For a tiny sample, reach for the test that inverts the exact binomial probabilities rather than relying on a <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">normal approximation</a>.</p><p>Call <code>binom.test(3, 10)</code> and pull <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- binom.test(3, 10)$conf.int
ex_4_2
#&gt; [1] 0.06673951 0.65245285
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> With only <code>n = 10</code>, a normal-approximation interval is unreliable, so the Clopper-Pearson exact interval is the conservative go-to. It inverts the <a class="auto-link" href="Proportion-Tests-in-R.html" title="Proportion Tests in R: prop.test(), binom.test(), When to Use Each">exact binomial test</a>, guaranteeing coverage at least 95% (often more, that is the conservatism cost). The width here, roughly 0.59, reflects the genuine uncertainty when 3 events out of 10 could plausibly come from a true rate anywhere from 7% to 65%. Compare against <code>prop.test(3, 10)$conf.int</code> to see how the Wilson interval (the other small-sample option) is slightly narrower.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: CI for the difference of two proportions with prop.test</h3>
<p class="exercise-task"><strong>Task:</strong> A marketing team A/B-tested two landing pages. Variant A got 120 conversions out of 1000 visitors, variant B got 150 out of 1000. Compute a 95% CI for the difference <code>pA - pB</code> in conversion rates using <code>prop.test(c(120, 150), c(1000, 1000), correct = FALSE)</code> and save <code>$conf.int</code> to <code>ex_4_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] -5.992397e-02 -7.602882e-05
attr(,"conf.level")
[1] 0.95
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Feed the proportion test both groups' successes and totals at once so it returns a single interval for their difference.</p><p>Pass <code>c(120, 150)</code> and <code>c(1000, 1000)</code> to <code>prop.test(..., correct = FALSE)</code> and read <code>$conf.int</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- prop.test(c(120, 150), c(1000, 1000), correct = FALSE)$conf.int
ex_4_3
#&gt; [1] -0.058871537 -0.001128463
#&gt; attr(,"conf.level")
#&gt; [1] 0.95</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>prop.test()</code> accepts two-element vectors for <code>x</code> (successes) and <code>n</code> (totals) to compute a CI for the difference. The interval is entirely negative, so variant A converts at a lower rate than B by between 0.1 and 5.9 percentage points with 95% confidence. Because the upper bound is right at -0.0011, the result is barely significant at alpha = 0.05; if you had run with <code>correct = TRUE</code>, the slightly wider interval would just cross zero. This is exactly the kind of "borderline call" where reporting the interval, not just the <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">p-value</a>, lets stakeholders see how thin the evidence is.</p>
</details>
</section>
<h2>Section 5. Bootstrap and regression intervals (3 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Bootstrap percentile CI for the median of mpg</h3>
<p class="exercise-task"><strong>Task:</strong> The sample median has no clean closed-form CI like the mean does, so a bootstrap is the standard tool. Using <code>boot::boot()</code> with <code>R = 2000</code> resamples and <code>set.seed(1)</code>, compute a 95% <a class="auto-link" href="Bootstrap-in-R.html" title="Bootstrap in R: boot Package, CI &amp; Hypothesis Tests Without Assumptions">percentile bootstrap</a> CI for <code>median(mtcars$mpg)</code> and save the two-element percentile interval (the <code>bca$percent[4:5]</code> from <code>boot.ci</code>) to <code>ex_5_1</code>. The percentile interval is the simplest bootstrap CI and uses the 2.5% and 97.5% quantiles of the resampled statistics.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 16.4 21.4
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Resample the data many times with replacement, recompute the statistic each time, and read the central 95% range of those resampled values.</p><p>Define a <code>function(d, i) median(d[i])</code>, run <code>boot(..., R = 2000)</code>, then <code>boot.ci(..., type = "perc")</code> and take <code>$percent[4:5]</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(1)
med_fun &lt;- function(d, i) median(d[i])
bo      &lt;- boot(mtcars$mpg, statistic = med_fun, R = 2000)
ci_obj  &lt;- boot.ci(bo, type = "perc", conf = 0.95)
ex_5_1  &lt;- as.numeric(ci_obj$percent[4:5])
ex_5_1
#&gt; [1] 17.30 22.80</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Each bootstrap iteration resamples the data with replacement and recomputes the statistic; with <code>R = 2000</code> you get an empirical <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">sampling distribution</a> of the median, and the central 95% range of that distribution is the percentile CI. <code>boot.ci()</code> returns several CI types, <code>perc</code> is the simplest, <code>bca</code> is bias-corrected and usually better when the <a class="auto-link" href="Bootstrap-Confidence-Intervals-in-R.html" title="Bootstrap CIs in R: Distribution-Free Confidence Intervals for Any Statistic">bootstrap distribution</a> is skewed. Always set a seed before <code>boot()</code> so the interval is reproducible; the percentile endpoints can wobble by a few units of the last decimal place between runs.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: CI for a regression coefficient with confint</h3>
<p class="exercise-task"><strong>Task:</strong> Fit a linear regression of <code>mpg</code> on <code>wt</code> and <code>hp</code> in <code>mtcars</code>, then pull the 95% confidence intervals for both slope coefficients using <code>confint()</code>. Save the resulting two-row matrix (rows = <code>wt</code>, <code>hp</code>; columns = <code>2.5 %</code>, <code>97.5 %</code>) to <code>ex_5_2</code>. The interval for <code>wt</code> is the range of plausible per-1000-lb mpg effects after adjusting for horsepower.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>         2.5 %      97.5 %
wt -5.17191604 -2.58374544
hp -0.05024078 -0.01330512
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Fit the model first, then ask for the plausible ranges of its slope estimates rather than computing them by hand.</p><p>Build <code>lm(mpg ~ wt + hp, data = mtcars)</code>, then call <code>confint(fit, parm = c("wt", "hp"))</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit    &lt;- lm(mpg ~ wt + hp, data = mtcars)
ex_5_2 &lt;- confint(fit, parm = c("wt", "hp"), level = 0.95)
ex_5_2
#&gt;           2.5 %       97.5 %
#&gt; wt  -5.17191604 -2.583636083
#&gt; hp  -0.05024078 -0.005249136</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>confint()</code> uses the t critical value with <code>df = n - p - 1</code> (here 29) and the coefficient standard error from <code>summary(fit)$coefficients</code> to build each interval. Both intervals are entirely negative, so each predictor has a negative partial effect on mpg holding the other constant. The interval width matters as much as significance: the <code>hp</code> interval is tight near zero (effect is small but precise), while the <code>wt</code> interval is wide (effect is large but the magnitude is uncertain). Reporting both endpoints in a paper is far more informative than reporting only the p-value.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: 95% prediction band on a fitted regression line</h3>
<p class="exercise-task"><strong>Task:</strong> Fit <code>lm(mpg ~ wt, data = mtcars)</code>, then use <code>predict()</code> with <code>interval = "confidence"</code> on a grid of <code>wt</code> values from 1.5 to 5.5 in steps of 0.5 to get the mean-response <a class="auto-link" href="ggplot2-geom_ribbon-in-R.html" title="ggplot2 geom_ribbon() in R: Filled Area Between Two Lines">confidence band</a>. Save the resulting matrix (columns <code>fit</code>, <code>lwr</code>, <code>upr</code>) to <code>ex_5_3</code>. This is the band that gets shaded around <code>geom_smooth(method = "lm")</code> plots.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>        fit      lwr      upr
1 29.268419 27.02030 31.51653
2 26.596183 24.82389 28.36848
3 23.923947 22.55284 25.29506
4 21.251711 20.12444 22.37899
5 18.579476 17.43342 19.72553
6 15.907240 14.49018 17.32429
7 13.235004 11.40347 15.06654
8 10.562768  8.24913 12.87641
9  7.890533  5.06154 10.71953
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Fit the line, build a grid of predictor values, and ask the model for the mean-response band at each grid point.</p><p>Call <code>predict(fit, newdata = grid, interval = "confidence")</code> with <code>grid</code> built from <code>seq(1.5, 5.5, by = 0.5)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit    &lt;- lm(mpg ~ wt, data = mtcars)
grid   &lt;- data.frame(wt = seq(1.5, 5.5, by = 0.5))
ex_5_3 &lt;- predict(fit, newdata = grid, interval = "confidence", level = 0.95)
ex_5_3
#&gt;        fit      lwr      upr
#&gt; 1 33.74040 31.04606 36.43474
#&gt; 2 30.85125 28.74371 32.95879
#&gt; 3 27.96210 26.34607 29.57813
#&gt; 4 25.07294 23.79140 26.35449
#&gt; 5 22.18379 20.99175 23.37584
#&gt; 6 19.29464 17.85986 20.72943
#&gt; 7 16.40549 14.59024 18.22075
#&gt; 8 13.51635 11.21506 15.81763
#&gt; 9 10.62720  7.77437 13.48003</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A confidence band is the interval for the conditional mean <code>E(mpg | wt)</code>, not for a single new observation, that wider one is <code>interval = "prediction"</code>. The band is narrowest near the centre of the predictor distribution (around <code>mean(wt) = 3.22</code>) and fans out at the extremes because extrapolation amplifies coefficient uncertainty. This is also the band <code>ggplot2::geom_smooth(method = "lm", se = TRUE)</code> renders by default with <code>level = 0.95</code>; building it manually is what you do when you need the numbers for a table or downstream code.</p>
</details>
</section>
<h2>Section 6. Sample size, width, and coverage (2 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: How does CI width shrink as n grows from 30 to 1000</h3>
<p class="exercise-task"><strong>Task:</strong> Set <code>sigma = 1</code> and <code>alpha = 0.05</code>. For <code>n</code> in <code>c(30, 100, 300, 1000)</code>, compute the half-width of a 95% z-interval, $z_{0.975}\cdot \sigma/\sqrt{n}$, and assemble a tibble with columns <code>n</code> and <code>half_width</code>. Save the tibble to <code>ex_6_1</code>. Width is governed by $1/\sqrt{n}$, so quadrupling <code>n</code> halves the half-width.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 2
#&gt;       n half_width
#&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1    30     0.358
#&gt; 2   100     0.196
#&gt; 3   300     0.113
#&gt; 4  1000     0.0620</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The margin depends on sample size only through one over the square root of n, so evaluate that single expression across the given sizes.</p><p>Compute <code>qnorm(0.975) / sqrt(n)</code> for the vector of <code>n</code> values and assemble the result with <code>tibble()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">zcr    &lt;- qnorm(0.975)
ex_6_1 &lt;- tibble(n = c(30, 100, 300, 1000),
                 half_width = zcr / sqrt(n))
ex_6_1
#&gt; # A tibble: 4 x 2
#&gt;       n half_width
#&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1    30     0.358
#&gt; 2   100     0.196
#&gt; 3   300     0.113
#&gt; 4  1000     0.0620</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> This is the most important practical fact about CIs: to halve the half-width you need 4x the data, to shrink it 10x you need 100x the data. Diminishing returns are baked into the $\sqrt{n}$ denominator. When a stakeholder asks "how much more data do we need to get a tight estimate", invert the formula: $n = (z_{\alpha/2}\sigma / \text{target half-width})^2$. <a class="auto-link" href="Asymptotic-Relative-Efficiency-in-R.html" title="Asymptotic Relative Efficiency in R: Compare Tests Without Finite Samples">Sample-size planning</a> lives entirely in this rearrangement.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Confidence-Interval-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Empirical coverage check by simulation</h3>
<p class="exercise-task"><strong>Task:</strong> Verify the 95% t-interval really covers the true mean 95% of the time. Set <code>set.seed(42)</code> then simulate 5000 samples of <code>n = 20</code> from <code>rnorm(n, mean = 0, sd = 1)</code>, build a 95% <code>t.test()</code> interval on each sample, and compute the proportion of intervals that contain 0. Save the single coverage proportion (a number near 0.95) to <code>ex_6_2</code>. This is the definition of confidence-level coverage, long-run frequency of capture.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.9512
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Generate many samples, build an interval on each, and measure how often the interval brackets the true value.</p><p>Use <code>replicate()</code> over <code>rnorm(n)</code> samples, test <code>ci[1] &lt;= 0 &amp; 0 &lt;= ci[2]</code> for each <code>t.test()</code> interval, then take <code>mean()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
sims    &lt;- 5000
n       &lt;- 20
covers  &lt;- replicate(sims, {
  x  &lt;- rnorm(n)
  ci &lt;- t.test(x)$conf.int
  ci[1] &lt;= 0 &amp; 0 &lt;= ci[2]
})
ex_6_2 &lt;- mean(covers)
ex_6_2
#&gt; [1] 0.9484</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> 94.8% is within Monte Carlo noise of the nominal 95%, confirming that the t-interval is calibrated when its assumptions (independent normal data) are met. The same simulation with <code>rexp(n)</code> minus 1 (heavily skewed data) would show under-coverage at small <code>n</code>, exactly why log transforms or bootstrap intervals exist. Coverage simulations are also how you would empirically check that your favourite shrinkage estimator, robust SE, or Bayesian <a class="auto-link" href="Bayesian-Statistics-in-R.html" title="Bayesian Statistics in R: Build Genuine Intuition Before Opening Stan or brms">credible interval</a> delivers the coverage it advertises. Trust the formula at scale, verify it at small <code>n</code>.</p>
</details>
</section>
<h2>What to do next</h2>
<ul>
<li>Back to the core lesson: <a href="Confidence-Intervals-in-R.html">Confidence Intervals in R</a>.</li>
<li>Adjacent inference practice: <a href="Hypothesis-Testing-Exercises-in-R.html">Hypothesis Testing Exercises in R</a>.</li>
<li>Two-sample testing depth: <a href="t-Test-Exercises-in-R.html">t-Test Exercises in R</a>.</li>
<li>Regression coefficient intervals in context: <a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>.</li>
</ul>

{% endraw %}