---
title: "Data Cleaning Exercises in R: 28 Real Practice Problems"
description: "Practice 28 data cleaning problems in R: missing values, duplicates, type coercion, string fixes, outliers, validation. Solutions hidden, code runnable."
keywords: "data cleaning exercises in R, data cleaning practice R, R data cleaning problems, data cleaning in R exercises, dirty data R practice"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "data cleaning exercises|data cleaning practice|data cleaning in R exercises|dirty data R"
auto_link_case_sensitive: false
sidebar_title: "Data Cleaning Exercises"
sidebar_order: "116"
fr_parent: "R-Tutorial.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Data Cleaning Exercises in R: 28 Real Practice Problems</h1>

<p class="lead">Twenty-eight practice problems that mirror the data-cleaning work analysts do every day: handling <a class="auto-link" href="Missing-Value-Treatment-With-R.html" title="Missing Value Treatment">missing values</a>, deduplicating records, coercing messy types, standardizing strings, flagging outliers, and validating end-to-end pipelines. Solutions are hidden so you can attempt each problem first.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="70" data-exercises="28" data-xp="420"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(tibble)
library(purrr)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Missing values (5 problems)</h2>

<h3>Exercise 1.1: Count total missing values across a data frame</h3>

<p><strong>Task:</strong> A data analyst auditing the built-in <code>airquality</code> dataset wants a single number describing how dirty the input is. Use <code>is.na()</code> together with <code>sum()</code> to count every NA across all columns and rows, then save the count to <code>ex_1_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 44
#&gt; (out of 153 rows * 6 cols = 918 cells)</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- sum(is.na(airquality))
ex_1_1
#&gt; [1] 44</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>is.na()</code> returns a logical matrix of the same shape as <code>airquality</code>, with <code>TRUE</code> where a cell is missing. <code>sum()</code> coerces <code>TRUE</code> to <code>1</code> and <code>FALSE</code> to <code>0</code>, so the result is the total NA count. This one-liner is your first sanity check on any new dataset; pair it with <code>nrow(airquality) * ncol(airquality)</code> to convert to a percentage. Avoid <code>complete.cases()</code> here because it returns a per-row logical, not a global count.</p>

</details>

<h3>Exercise 1.2: Build a per-column missingness report</h3>

<p><strong>Task:</strong> The same analyst now needs a row in a dashboard showing the NA count for every column of <code>airquality</code>, sorted descending so the worst offenders surface first. Produce a tibble with columns <code>column</code> and <code>n_missing</code> and save it to <code>ex_1_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 6 x 2
#&gt;   column  n_missing
#&gt;   &lt;chr&gt;       &lt;int&gt;
#&gt; 1 Ozone          37
#&gt; 2 Solar.R         7
#&gt; 3 Wind            0
#&gt; 4 Temp            0
#&gt; 5 Month           0
#&gt; 6 Day             0</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- airquality |&gt;
  summarise(across(everything(), ~ sum(is.na(.x)))) |&gt;
  pivot_longer(everything(), names_to = &quot;column&quot;, values_to = &quot;n_missing&quot;) |&gt;
  arrange(desc(n_missing))
ex_1_2
#&gt; # A tibble: 6 x 2
#&gt;   column  n_missing
#&gt;   &lt;chr&gt;       &lt;int&gt;
#&gt; 1 Ozone          37
#&gt; 2 Solar.R         7
#&gt; 3 Wind            0
#&gt; 4 Temp            0
#&gt; 5 Month           0
#&gt; 6 Day             0</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>across(everything(), ...)</code> applies the lambda column-wise, returning a one-row wide summary. <code>pivot_longer()</code> flips that wide row into the long, dashboard-friendly shape. The alternative <code>colSums(is.na(airquality))</code> is shorter but returns a named vector, which is awkward to feed into further dplyr pipelines or to ggplot for a missingness bar chart.</p>

</details>

<h3>Exercise 1.3: Drop rows missing the response but keep predictor gaps</h3>

<p><strong>Task:</strong> A modeller plans to predict <code>Ozone</code> from weather variables in <code>airquality</code> and must drop only the rows where <code>Ozone</code> itself is NA, while keeping rows that have <code>Solar.R</code> missing (those can be imputed later). Save the filtered tibble to <code>ex_1_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 116 x 6
#&gt;    Ozone Solar.R  Wind  Temp Month   Day
#&gt;    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1     41     190   7.4    67     5     1
#&gt; 2     36     118   8.0    72     5     2
#&gt; ...
#&gt; # 114 more rows hidden
#&gt; sum(is.na(ex_1_3$Solar.R))
#&gt; [1] 5</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- airquality |&gt; drop_na(Ozone)
nrow(ex_1_3)
#&gt; [1] 116
sum(is.na(ex_1_3$Solar.R))
#&gt; [1] 5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>drop_na(Ozone)</code> is the targeted version of <code>drop_na()</code>; passing no argument would strip every row with any NA and waste 35 valid Solar.R rows. The principle generalizes: drop only on the columns whose missingness you cannot model around, and impute the rest. The base R equivalent is <code>airquality[!is.na(airquality$Ozone), ]</code>, which is more verbose but works without tidyr.</p>

</details>

<h3>Exercise 1.4: Impute two columns with two different strategies</h3>

<p><strong>Task:</strong> Continuing the modelling prep, replace <code>Ozone</code> NAs with the column median and <code>Solar.R</code> NAs with the column mean on the full <code>airquality</code> table. The choice differs because Ozone is right-skewed (median is more robust) while Solar.R is roughly symmetric. Save the imputed tibble to <code>ex_1_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 153 x 6
#&gt;    Ozone Solar.R  Wind  Temp Month   Day
#&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1   41      190    7.4    67     5     1
#&gt; 2   36      118    8      72     5     2
#&gt; ...
#&gt; sum(is.na(ex_1_4))
#&gt; [1] 0</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- airquality |&gt;
  mutate(
    Ozone   = ifelse(is.na(Ozone),   median(Ozone,   na.rm = TRUE), Ozone),
    Solar.R = ifelse(is.na(Solar.R), mean(Solar.R, na.rm = TRUE),   Solar.R)
  )
sum(is.na(ex_1_4))
#&gt; [1] 0</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>na.rm = TRUE</code> is critical: forgetting it makes <code>median()</code> and <code>mean()</code> return <code>NA</code>, so the imputation becomes a no-op. Single-value imputation shrinks variance and biases regression standard errors, so report this in your write-up. For production work consider <code>mice::mice()</code> or <code>recipes::step_impute_*()</code>, which honour the multivariate structure of the data instead of treating each column independently.</p>

</details>

<h3>Exercise 1.5: Forward-fill missing readings within each month</h3>

<p><strong>Task:</strong> A field scientist treats <code>airquality</code> as a daily <a class="auto-link" href="Time-Series-Analysis-With-R.html" title="Time Series Analysis with R">time series</a> and assumes that on calm days a missing Ozone reading is best replaced by the most recent prior reading within the same month (not bleeding across months). Use <code>tidyr::fill()</code> after <code>group_by(Month)</code> to forward-fill <code>Ozone</code>. Save the result to <code>ex_1_5</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 153 x 6
#&gt; # Groups:   Month [5]
#&gt;    Ozone Solar.R  Wind  Temp Month   Day
#&gt;    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1    41     190   7.4    67     5     1
#&gt; 2    36     118   8      72     5     2
#&gt; ...
#&gt; sum(is.na(ex_1_5$Ozone))
#&gt; [1] 4</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_5 &lt;- # your code here
ex_1_5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_5 &lt;- airquality |&gt;
  arrange(Month, Day) |&gt;
  group_by(Month) |&gt;
  fill(Ozone, .direction = &quot;down&quot;)
sum(is.na(ex_1_5$Ozone))
#&gt; [1] 4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>fill()</code> respects grouping, so values do not leak from May into June. Four NAs survive because they sit at the start of their month with no prior observation to copy. Set <code>.direction = &quot;downup&quot;</code> to also back-fill leading NAs, which is acceptable when the time order is not meaningful. Forward-fill is a strong default for sensor data where short gaps reflect transmission failures rather than true zeros.</p>

</details>

<h2>Section 2. Duplicates and uniqueness (4 problems)</h2>

<h3>Exercise 2.1: Flag exact duplicate rows</h3>

<p><strong>Task:</strong> A junior analyst inherits an inline tibble of customer orders and suspects the upstream extract double-wrote some rows. Detect every row that is an exact duplicate of another row (keep both copies in the flagged set) and save the duplicate rows to <code>ex_2_1</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">orders &lt;- tibble(
  order_id = c(101, 102, 103, 101, 104, 102),
  customer = c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;A&quot;, &quot;D&quot;, &quot;B&quot;),
  amount   = c(10, 20, 30, 10, 40, 20)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 4 x 3
#&gt;   order_id customer amount
#&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
#&gt; 1      101 A            10
#&gt; 2      102 B            20
#&gt; 3      101 A            10
#&gt; 4      102 B            20</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">orders &lt;- tibble(
  order_id = c(101, 102, 103, 101, 104, 102),
  customer = c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;A&quot;, &quot;D&quot;, &quot;B&quot;),
  amount   = c(10, 20, 30, 10, 40, 20)
)
ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- orders |&gt;
  group_by(order_id, customer, amount) |&gt;
  filter(n() &gt; 1) |&gt;
  ungroup()
ex_2_1
#&gt; # A tibble: 4 x 3
#&gt;   order_id customer amount
#&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
#&gt; 1      101 A            10
#&gt; 2      102 B            20
#&gt; 3      101 A            10
#&gt; 4      102 B            20</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Grouping by every column and filtering <code>n() &gt; 1</code> returns all members of any duplicated combination, not just the second copy onward. Base R's <code>duplicated()</code> returns only the second-and-later flags, which is fine for deduplication but misleading when you want to audit the offending pairs. Always confirm a "duplicate" is a true repeat versus a legitimate repeat purchase before deleting.</p>

</details>

<h3>Exercise 2.2: Deduplicate keeping the most recent record</h3>

<p><strong>Task:</strong> A retailer's nightly customer feed often contains the same <code>customer_id</code> multiple times because addresses are updated mid-day; only the latest record per customer should survive. Using the inline tibble, deduplicate on <code>customer_id</code>, keeping the row with the maximum <code>updated_at</code>. Save the cleaned tibble to <code>ex_2_2</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">feed &lt;- tibble(
  customer_id = c(1, 1, 2, 3, 3, 3),
  address     = c(&quot;old A&quot;, &quot;new A&quot;, &quot;B&quot;, &quot;old C1&quot;, &quot;new C&quot;, &quot;old C2&quot;),
  updated_at  = as.Date(c(&quot;2026-01-01&quot;, &quot;2026-02-01&quot;,
                          &quot;2026-01-15&quot;,
                          &quot;2026-01-01&quot;, &quot;2026-03-01&quot;, &quot;2026-02-15&quot;))
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 3
#&gt;   customer_id address updated_at
#&gt;         &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;
#&gt; 1           1 new A   2026-02-01
#&gt; 2           2 B       2026-01-15
#&gt; 3           3 new C   2026-03-01</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">feed &lt;- tibble(
  customer_id = c(1, 1, 2, 3, 3, 3),
  address     = c(&quot;old A&quot;, &quot;new A&quot;, &quot;B&quot;, &quot;old C1&quot;, &quot;new C&quot;, &quot;old C2&quot;),
  updated_at  = as.Date(c(&quot;2026-01-01&quot;, &quot;2026-02-01&quot;,
                          &quot;2026-01-15&quot;,
                          &quot;2026-01-01&quot;, &quot;2026-03-01&quot;, &quot;2026-02-15&quot;))
)
ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- feed |&gt;
  arrange(customer_id, desc(updated_at)) |&gt;
  distinct(customer_id, .keep_all = TRUE)
ex_2_2
#&gt; # A tibble: 3 x 3
#&gt;   customer_id address updated_at
#&gt;         &lt;dbl&gt; &lt;chr&gt;   &lt;date&gt;
#&gt; 1           1 new A   2026-02-01
#&gt; 2           2 B       2026-01-15
#&gt; 3           3 new C   2026-03-01</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>distinct(..., .keep_all = TRUE)</code> retains the first row encountered per key, so pre-sorting by <code>desc(updated_at)</code> is what selects the latest record. The equivalent <code>group_by(customer_id) |&gt; slice_max(updated_at, n = 1)</code> is more explicit and survives unsorted data without the arrange step, at a small performance cost on millions of rows.</p>

</details>

<h3>Exercise 2.3: Detect case-insensitive duplicate emails</h3>

<p><strong>Task:</strong> A marketing analyst is loading email leads and notices that <code>Alice@Example.com</code> and <code>alice@example.com</code> are the same person from the mail server's perspective. Find every email that appears more than once after lowercasing and trimming whitespace. Save the duplicated normalized emails (one row per duplicated value, with count) to <code>ex_2_3</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">leads &lt;- tibble(
  raw_email = c(&quot; Alice@Example.com&quot;, &quot;bob@x.io&quot;,
                &quot;alice@example.com&quot;,  &quot;BOB@x.io &quot;,
                &quot;carol@y.com&quot;,        &quot;dave@z.io&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 2 x 2
#&gt;   email                  n
#&gt;   &lt;chr&gt;              &lt;int&gt;
#&gt; 1 alice@example.com      2
#&gt; 2 bob@x.io               2</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">leads &lt;- tibble(
  raw_email = c(&quot; Alice@Example.com&quot;, &quot;bob@x.io&quot;,
                &quot;alice@example.com&quot;,  &quot;BOB@x.io &quot;,
                &quot;carol@y.com&quot;,        &quot;dave@z.io&quot;)
)
ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- leads |&gt;
  mutate(email = str_to_lower(str_trim(raw_email))) |&gt;
  count(email) |&gt;
  filter(n &gt; 1) |&gt;
  arrange(desc(n), email)
ex_2_3
#&gt; # A tibble: 2 x 2
#&gt;   email                  n
#&gt;   &lt;chr&gt;              &lt;int&gt;
#&gt; 1 alice@example.com      2
#&gt; 2 bob@x.io               2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Trimming first prevents <code>&quot;bob@x.io&quot;</code> and <code>&quot;BOB@x.io &quot;</code> from being treated as different keys because of a trailing space. Lower-casing matches the email RFC, which says the local part is case-sensitive in theory but is treated as case-insensitive by virtually every mail provider. For a production de-dupe, also strip dot-folding (<code>a.lice</code> vs <code>alice</code> at Gmail) and plus-tagging (<code>alice+promos</code>).</p>

</details>

<h3>Exercise 2.4: Resolve duplicates on a composite business key</h3>

<p><strong>Task:</strong> A hospital's daily lab feed considers a record unique only by the composite key <code>(patient_id, test_code, sample_date)</code>; multiple result rows for the same key indicate a reprocessed run, and only the row with the latest <code>processed_at</code> is authoritative. Deduplicate the inline tibble on that composite key, keeping the latest <code>processed_at</code>. Save the cleaned tibble to <code>ex_2_4</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">labs &lt;- tibble(
  patient_id   = c(&quot;P1&quot;, &quot;P1&quot;, &quot;P1&quot;, &quot;P2&quot;, &quot;P2&quot;),
  test_code    = c(&quot;CBC&quot;, &quot;CBC&quot;, &quot;CMP&quot;, &quot;CBC&quot;, &quot;CBC&quot;),
  sample_date  = as.Date(c(&quot;2026-01-10&quot;, &quot;2026-01-10&quot;, &quot;2026-01-10&quot;,
                           &quot;2026-01-11&quot;, &quot;2026-01-11&quot;)),
  result       = c(4.2, 4.5, 130, 5.1, 5.0),
  processed_at = as.POSIXct(c(&quot;2026-01-10 09:00&quot;, &quot;2026-01-10 14:00&quot;,
                              &quot;2026-01-10 09:30&quot;,
                              &quot;2026-01-11 10:00&quot;, &quot;2026-01-11 16:00&quot;),
                            tz = &quot;UTC&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 5
#&gt;   patient_id test_code sample_date result processed_at
#&gt;   &lt;chr&gt;      &lt;chr&gt;     &lt;date&gt;       &lt;dbl&gt; &lt;dttm&gt;
#&gt; 1 P1         CBC       2026-01-10     4.5 2026-01-10 14:00:00
#&gt; 2 P1         CMP       2026-01-10   130   2026-01-10 09:30:00
#&gt; 3 P2         CBC       2026-01-11     5.0 2026-01-11 16:00:00</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">labs &lt;- tibble(
  patient_id   = c(&quot;P1&quot;, &quot;P1&quot;, &quot;P1&quot;, &quot;P2&quot;, &quot;P2&quot;),
  test_code    = c(&quot;CBC&quot;, &quot;CBC&quot;, &quot;CMP&quot;, &quot;CBC&quot;, &quot;CBC&quot;),
  sample_date  = as.Date(c(&quot;2026-01-10&quot;, &quot;2026-01-10&quot;, &quot;2026-01-10&quot;,
                           &quot;2026-01-11&quot;, &quot;2026-01-11&quot;)),
  result       = c(4.2, 4.5, 130, 5.1, 5.0),
  processed_at = as.POSIXct(c(&quot;2026-01-10 09:00&quot;, &quot;2026-01-10 14:00&quot;,
                              &quot;2026-01-10 09:30&quot;,
                              &quot;2026-01-11 10:00&quot;, &quot;2026-01-11 16:00&quot;),
                            tz = &quot;UTC&quot;)
)
ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_4 &lt;- labs |&gt;
  group_by(patient_id, test_code, sample_date) |&gt;
  slice_max(processed_at, n = 1, with_ties = FALSE) |&gt;
  ungroup()
ex_2_4
#&gt; # A tibble: 3 x 5
#&gt;   patient_id test_code sample_date result processed_at
#&gt;   &lt;chr&gt;      &lt;chr&gt;     &lt;date&gt;       &lt;dbl&gt; &lt;dttm&gt;
#&gt; 1 P1         CBC       2026-01-10     4.5 2026-01-10 14:00:00
#&gt; 2 P1         CMP       2026-01-10   130   2026-01-10 09:30:00
#&gt; 3 P2         CBC       2026-01-11     5.0 2026-01-11 16:00:00</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>slice_max(processed_at, n = 1)</code> is the idiomatic "<a class="auto-link" href="dplyr-slice_tail-in-R.html" title="dplyr slice_tail() in R: Take the Last N Rows (Per Group)">latest per group</a>" pattern; <code>with_ties = FALSE</code> guards against the rare case where two rows share the same processed timestamp, which would otherwise both survive and break the uniqueness contract. In SQL this is <code>ROW_NUMBER() OVER (PARTITION BY ... ORDER BY processed_at DESC) = 1</code>. Document the tie-breaking rule alongside the key in your data dictionary.</p>

</details>

<h2>Section 3. Type coercion and parsing (5 problems)</h2>

<h3>Exercise 3.1: Coerce a character vector of numbers to numeric</h3>

<p><strong>Task:</strong> A take-home interviewer hands you a character vector that should be numeric but came back as strings because the source CSV had a header row mixed in. Coerce <code>c(&quot;1.5&quot;, &quot;2.0&quot;, &quot;3.7&quot;, &quot;4.1&quot;)</code> to a numeric vector and save the result to <code>ex_3_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 1.5 2.0 3.7 4.1</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw &lt;- c(&quot;1.5&quot;, &quot;2.0&quot;, &quot;3.7&quot;, &quot;4.1&quot;)
ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw &lt;- c(&quot;1.5&quot;, &quot;2.0&quot;, &quot;3.7&quot;, &quot;4.1&quot;)
ex_3_1 &lt;- as.numeric(raw)
ex_3_1
#&gt; [1] 1.5 2.0 3.7 4.1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>as.numeric()</code> parses each element with R's standard numeric rules and emits <code>NA</code> with a warning for anything unparseable. For locale-aware parsing (commas as decimal separators, currency symbols) reach for <code>readr::parse_number()</code> instead; it tolerates noise like <code>&quot;$1.5&quot;</code> or <code>&quot;1,234.5&quot;</code> and skips the warning churn that <code>as.numeric()</code> produces on mixed input.</p>

</details>

<h3>Exercise 3.2: Parse a column with mixed date formats</h3>

<p><strong>Task:</strong> A consultant receives a survey export where the <code>date_taken</code> column has been entered three different ways: ISO (<code>&quot;2026-01-15&quot;</code>), US slash (<code>&quot;01/20/2026&quot;</code>), and abbreviated month (<code>&quot;Feb 5, 2026&quot;</code>). Parse them all into a single <code>Date</code> vector using <code>lubridate::parse_date_time()</code>. Save the parsed dates to <code>ex_3_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] &quot;2026-01-15&quot; &quot;2026-01-20&quot; &quot;2026-02-05&quot;</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw_dates &lt;- c(&quot;2026-01-15&quot;, &quot;01/20/2026&quot;, &quot;Feb 5, 2026&quot;)
ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw_dates &lt;- c(&quot;2026-01-15&quot;, &quot;01/20/2026&quot;, &quot;Feb 5, 2026&quot;)
ex_3_2 &lt;- as.Date(parse_date_time(raw_dates,
                                  orders = c(&quot;ymd&quot;, &quot;mdy&quot;, &quot;B d, Y&quot;)))
ex_3_2
#&gt; [1] &quot;2026-01-15&quot; &quot;2026-01-20&quot; &quot;2026-02-05&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>parse_date_time()</code> walks the <code>orders</code> vector in order and picks the first format that parses each element, which is exactly what you want for heterogeneous columns. It returns a POSIXct, so wrap with <code>as.Date()</code> when time-of-day is meaningless. Watch out for the <code>mdy</code> versus <code>dmy</code> ambiguity: <code>&quot;01/02/2026&quot;</code> is January 2nd in the US but February 1st in most of Europe, so confirm the source locale before trusting the parse.</p>

</details>

<h3>Exercise 3.3: Convert a factor to numeric without scrambling the values</h3>

<p><strong>Task:</strong> A reviewer flags that a colleague's regression code applied <code>as.numeric()</code> directly to a numeric-looking factor and silently produced the factor levels' integer codes instead of the original numbers. Convert <code>factor(c(&quot;10&quot;, &quot;20&quot;, &quot;30&quot;, &quot;10&quot;))</code> back to the original numeric values using the safe two-step idiom and save to <code>ex_3_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 10 20 30 10</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">f &lt;- factor(c(&quot;10&quot;, &quot;20&quot;, &quot;30&quot;, &quot;10&quot;))
ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">f &lt;- factor(c(&quot;10&quot;, &quot;20&quot;, &quot;30&quot;, &quot;10&quot;))
ex_3_3 &lt;- as.numeric(as.character(f))
ex_3_3
#&gt; [1] 10 20 30 10</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A factor stores integer codes internally, so <code>as.numeric(f)</code> returns those codes (1, 2, 3, 1 here) not the labels. The fix is to coerce to character first, then to numeric. The newer <code>forcats::fct_inseq()</code> reorders levels by their numeric interpretation; <code>as.numeric(as.character(...))</code> is still the safest one-line conversion. This bug surfaces a lot in survey data where Likert scales are stored as factors.</p>

</details>

<h3>Exercise 3.4: Parse currency strings into numbers</h3>

<p><strong>Task:</strong> A finance team's expense report exports amounts as currency strings like <code>&quot;$1,234.56&quot;</code>, <code>&quot;$0.99&quot;</code>, <code>&quot;$10,000.00&quot;</code>, and the auditing pipeline needs them as numeric for summing. Use <code>readr::parse_number()</code> to strip the dollar signs and thousands separators in one call. Save the parsed numeric vector to <code>ex_3_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1]  1234.56     0.99 10000.00</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">amounts &lt;- c(&quot;$1,234.56&quot;, &quot;$0.99&quot;, &quot;$10,000.00&quot;)
ex_3_4 &lt;- # your code here
ex_3_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(readr)
amounts &lt;- c(&quot;$1,234.56&quot;, &quot;$0.99&quot;, &quot;$10,000.00&quot;)
ex_3_4 &lt;- parse_number(amounts)
ex_3_4
#&gt; [1]  1234.56     0.99 10000.00</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>parse_number()</code> pulls the first contiguous number out of each string and ignores leading/trailing non-numeric noise plus thousands separators that match the active locale. For European data set <code>locale = locale(decimal_mark = &quot;,&quot;, grouping_mark = &quot;.&quot;)</code>. The base R alternative is two <code>gsub()</code> calls followed by <code>as.numeric()</code>, which is more typing and easier to break with edge cases like negative parentheses (<code>&quot;($50)&quot;</code>).</p>

</details>

<h3>Exercise 3.5: Auto-detect and coerce a messy character data frame</h3>

<p><strong>Task:</strong> An ML engineer ingests a CSV where every column was read as character because of stray cells. They want to apply <code>readr::parse_guess()</code> to each column independently so dates, integers, and doubles get their natural type while truly textual columns stay character. Use <code>mutate(across(everything(), parse_guess))</code> on the inline tibble and save the typed tibble to <code>ex_3_5</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">messy &lt;- tibble(
  id   = c(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;),
  date = c(&quot;2026-01-01&quot;, &quot;2026-02-15&quot;, &quot;2026-03-30&quot;),
  amt  = c(&quot;100.5&quot;, &quot;200.0&quot;, &quot;300.25&quot;),
  note = c(&quot;ok&quot;, &quot;ok&quot;, &quot;review&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 4
#&gt;      id date         amt note
#&gt;   &lt;dbl&gt; &lt;date&gt;     &lt;dbl&gt; &lt;chr&gt;
#&gt; 1     1 2026-01-01  100. ok
#&gt; 2     2 2026-02-15  200  ok
#&gt; 3     3 2026-03-30  300. review</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">messy &lt;- tibble(
  id   = c(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;),
  date = c(&quot;2026-01-01&quot;, &quot;2026-02-15&quot;, &quot;2026-03-30&quot;),
  amt  = c(&quot;100.5&quot;, &quot;200.0&quot;, &quot;300.25&quot;),
  note = c(&quot;ok&quot;, &quot;ok&quot;, &quot;review&quot;)
)
ex_3_5 &lt;- # your code here
ex_3_5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(readr)
messy &lt;- tibble(
  id   = c(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;),
  date = c(&quot;2026-01-01&quot;, &quot;2026-02-15&quot;, &quot;2026-03-30&quot;),
  amt  = c(&quot;100.5&quot;, &quot;200.0&quot;, &quot;300.25&quot;),
  note = c(&quot;ok&quot;, &quot;ok&quot;, &quot;review&quot;)
)
ex_3_5 &lt;- messy |&gt;
  mutate(across(everything(), parse_guess))
ex_3_5
#&gt; # A tibble: 3 x 4
#&gt;      id date         amt note
#&gt;   &lt;dbl&gt; &lt;date&gt;     &lt;dbl&gt; &lt;chr&gt;
#&gt; 1     1 2026-01-01  100. ok
#&gt; 2     2 2026-02-15  200  ok
#&gt; 3     3 2026-03-30  300. review</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>parse_guess()</code> runs <code>readr</code>'s heuristic over a sample of values and returns the most specific type that parses everything (date > integer > double > character). Wrap it inside <code>across()</code> to apply the per-column logic in one pass. The downside is that columns with a stray non-numeric value will fall back to character; tighten the guess by calling <code>parse_double(..., na = c(&quot;&quot;, &quot;NA&quot;, &quot;n/a&quot;))</code> explicitly on columns you trust to be numeric.</p>

</details>

<h2>Section 4. String cleaning and normalization (4 problems)</h2>

<h3>Exercise 4.1: Trim whitespace and force lowercase</h3>

<p><strong>Task:</strong> A new hire is loading a category column from a vendor feed and the same logical value appears as <code>&quot; Active&quot;</code>, <code>&quot;ACTIVE &quot;</code>, and <code>&quot;active&quot;</code> due to inconsistent data entry. Normalize a character vector by stripping leading/trailing whitespace with <code>str_trim()</code> and lowercasing with <code>str_to_lower()</code>, then save the result to <code>ex_4_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] &quot;active&quot;   &quot;active&quot;   &quot;active&quot;   &quot;inactive&quot;</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">status &lt;- c(&quot; Active&quot;, &quot;ACTIVE &quot;, &quot;active&quot;, &quot;Inactive&quot;)
ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">status &lt;- c(&quot; Active&quot;, &quot;ACTIVE &quot;, &quot;active&quot;, &quot;Inactive&quot;)
ex_4_1 &lt;- str_to_lower(str_trim(status))
ex_4_1
#&gt; [1] &quot;active&quot;   &quot;active&quot;   &quot;active&quot;   &quot;inactive&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Always trim before lowercasing because <code>tolower(&quot; Active&quot;)</code> would still leave the leading space and quietly fail any downstream <code>==</code> comparison against <code>&quot;active&quot;</code>. The base R pair is <code>trimws()</code> plus <code>tolower()</code>. For more aggressive cleanup, <code>str_squish()</code> collapses runs of internal whitespace into single spaces, which is useful when free-text fields have copy-paste artefacts.</p>

</details>

<h3>Exercise 4.2: Reduce phone numbers to digits only</h3>

<p><strong>Task:</strong> A CRM admin needs phone numbers in a single canonical 10-digit form so two records typed as <code>&quot;(415) 555-1234&quot;</code> and <code>&quot;415.555.1234&quot;</code> match. Strip every non-digit from the input character vector using <code>str_remove_all()</code> with a regex, and save the digits-only vector to <code>ex_4_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] &quot;4155551234&quot; &quot;4155551234&quot; &quot;4155551234&quot; &quot;4155551234&quot;</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">phones &lt;- c(&quot;(415) 555-1234&quot;, &quot;415.555.1234&quot;, &quot;415-555-1234&quot;, &quot;+1 415 555 1234&quot;)
ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">phones &lt;- c(&quot;(415) 555-1234&quot;, &quot;415.555.1234&quot;, &quot;415-555-1234&quot;, &quot;+1 415 555 1234&quot;)
ex_4_2 &lt;- str_remove_all(phones, &quot;\\D&quot;)
# Drop a leading country code if you only want the trailing 10 digits
ex_4_2 &lt;- str_sub(ex_4_2, start = -10)
ex_4_2
#&gt; [1] &quot;4155551234&quot; &quot;4155551234&quot; &quot;4155551234&quot; &quot;4155551234&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The character class <code>\\D</code> matches any non-digit, so <code>str_remove_all()</code> collapses the string to bare numbers. The trailing <code>str_sub(..., start = -10)</code> defends against numbers that include a country code: keeping the last 10 characters normalizes to the North American local form. For international canonicalization use the <code>phonenumber</code> package, which understands country-specific length rules.</p>

</details>

<h3>Exercise 4.3: Extract zip codes from messy address strings</h3>

<p><strong>Task:</strong> A real-estate analyst has free-text address strings and needs the five-digit zip code at the end of each. Use <code>str_extract()</code> with a regex anchored to the trailing five digits, then save the extracted zips (as character to preserve leading zeros) to <code>ex_4_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] &quot;94110&quot; &quot;10001&quot; &quot;02115&quot;</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">addresses &lt;- c(&quot;100 Main St, San Francisco, CA 94110&quot;,
               &quot;55 5th Ave, New York, NY 10001&quot;,
               &quot;1 Long Wood Ave, Boston, MA 02115&quot;)
ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">addresses &lt;- c(&quot;100 Main St, San Francisco, CA 94110&quot;,
               &quot;55 5th Ave, New York, NY 10001&quot;,
               &quot;1 Long Wood Ave, Boston, MA 02115&quot;)
ex_4_3 &lt;- str_extract(addresses, &quot;\\d{5}$&quot;)
ex_4_3
#&gt; [1] &quot;94110&quot; &quot;10001&quot; &quot;02115&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>\\d{5}$</code> matches exactly five digits at the end of the string. Anchoring with <code>$</code> is what prevents <code>&quot;100&quot;</code> (street number) from being captured; without it, the regex would greedily lock onto the first run of five digits found. Storing zips as character is non-negotiable: coercing <code>&quot;02115&quot;</code> to numeric produces <code>2115</code> and breaks downstream joins against reference data.</p>

</details>

<h3>Exercise 4.4: Standardize country names against a lookup table</h3>

<p><strong>Task:</strong> A growth team appends a country column from multiple vendors and sees <code>&quot;USA&quot;</code>, <code>&quot;U.S.A.&quot;</code>, <code>&quot;United States&quot;</code>, <code>&quot;Britain&quot;</code>, and <code>&quot;UK&quot;</code> all in the same field. Build a small named lookup vector that maps each variant to a canonical ISO-3166 short name, then use <code>recode()</code> to standardize the inline <code>raw_country</code> column. Save the cleaned tibble to <code>ex_4_4</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">contacts &lt;- tibble(
  id          = 1:6,
  raw_country = c(&quot;USA&quot;, &quot;U.S.A.&quot;, &quot;United States&quot;,
                  &quot;Britain&quot;, &quot;UK&quot;, &quot;Canada&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 6 x 3
#&gt;      id raw_country   country
#&gt;   &lt;int&gt; &lt;chr&gt;         &lt;chr&gt;
#&gt; 1     1 USA           United States
#&gt; 2     2 U.S.A.        United States
#&gt; 3     3 United States United States
#&gt; 4     4 Britain       United Kingdom
#&gt; 5     5 UK            United Kingdom
#&gt; 6     6 Canada        Canada</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">contacts &lt;- tibble(
  id          = 1:6,
  raw_country = c(&quot;USA&quot;, &quot;U.S.A.&quot;, &quot;United States&quot;,
                  &quot;Britain&quot;, &quot;UK&quot;, &quot;Canada&quot;)
)
ex_4_4 &lt;- # your code here
ex_4_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">lookup &lt;- c(
  &quot;USA&quot;            = &quot;United States&quot;,
  &quot;U.S.A.&quot;         = &quot;United States&quot;,
  &quot;United States&quot;  = &quot;United States&quot;,
  &quot;Britain&quot;        = &quot;United Kingdom&quot;,
  &quot;UK&quot;             = &quot;United Kingdom&quot;,
  &quot;Canada&quot;         = &quot;Canada&quot;
)
ex_4_4 &lt;- contacts |&gt;
  mutate(country = recode(raw_country, !!!lookup))
ex_4_4
#&gt; # A tibble: 6 x 3
#&gt;      id raw_country   country
#&gt;   &lt;int&gt; &lt;chr&gt;         &lt;chr&gt;
#&gt; 1     1 USA           United States
#&gt; 2     2 U.S.A.        United States
#&gt; 3     3 United States United States
#&gt; 4     4 Britain       United Kingdom
#&gt; 5     5 UK            United Kingdom
#&gt; 6     6 Canada        Canada</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Splatting the lookup vector with <code>!!!</code> injects every name-value pair as a separate argument to <code>recode()</code>. Keeping the mapping outside the call documents the rules and makes them testable; an unmatched value would silently pass through, so audit with <code>setdiff(unique(contacts$raw_country), names(lookup))</code> after each vendor add. For richer matching consider the <code>countrycode</code> package, which understands hundreds of name variants out of the box.</p>

</details>

<h2>Section 5. Outliers and validation (5 problems)</h2>

<h3>Exercise 5.1: Flag values outside a domain range</h3>

<p><strong>Task:</strong> A teacher uploads test scores expecting integers in <code>[0, 100]</code> and wants every out-of-range entry replaced with <code>NA</code> so downstream summaries do not show negative means. Replace any <code>score</code> outside the closed range <code>[0, 100]</code> with <code>NA</code> in the inline tibble and save the result to <code>ex_5_1</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">scores &lt;- tibble(
  student = c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;, &quot;E&quot;),
  score   = c(85, -3, 102, 70, 95)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 5 x 2
#&gt;   student score
#&gt;   &lt;chr&gt;   &lt;dbl&gt;
#&gt; 1 A          85
#&gt; 2 B          NA
#&gt; 3 C          NA
#&gt; 4 D          70
#&gt; 5 E          95</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">scores &lt;- tibble(
  student = c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;, &quot;E&quot;),
  score   = c(85, -3, 102, 70, 95)
)
ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">scores &lt;- tibble(
  student = c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;, &quot;E&quot;),
  score   = c(85, -3, 102, 70, 95)
)
ex_5_1 &lt;- scores |&gt;
  mutate(score = ifelse(score &lt; 0 | score &gt; 100, NA, score))
ex_5_1
#&gt; # A tibble: 5 x 2
#&gt;   student score
#&gt;   &lt;chr&gt;   &lt;dbl&gt;
#&gt; 1 A          85
#&gt; 2 B          NA
#&gt; 3 C          NA
#&gt; 4 D          70
#&gt; 5 E          95</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Setting domain violations to <code>NA</code> is preferable to dropping the row, because the row's other columns may still hold useful information (the student ID, attempt number, etc.). Avoid silently clipping to <code>[0, 100]</code>; a <code>-3</code> is more likely a data-entry error than a true zero, and pretending it is a zero hides the upstream bug. Log the count of replacements so QA can chase the source.</p>

</details>

<h3>Exercise 5.2: Flag IQR outliers in a numeric column</h3>

<p><strong>Task:</strong> A statistician auditing the <code>airquality</code> dataset wants to flag wind-speed observations that fall outside the standard Tukey fence: more than 1.5 IQR below Q1 or above Q3. Add a logical <code>is_outlier</code> column to <code>airquality</code> based on <code>Wind</code>, then save to <code>ex_5_2</code>. Compute Q1/Q3/IQR ignoring NAs.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 153 x 7
#&gt;    Ozone Solar.R  Wind  Temp Month   Day is_outlier
#&gt;    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;lgl&gt;
#&gt; 1     41     190   7.4    67     5     1 FALSE
#&gt; 2     36     118   8      72     5     2 FALSE
#&gt; ...
#&gt; sum(ex_5_2$is_outlier)
#&gt; [1] 3</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">q1  &lt;- quantile(airquality$Wind, 0.25, na.rm = TRUE)
q3  &lt;- quantile(airquality$Wind, 0.75, na.rm = TRUE)
iqr &lt;- q3 - q1
ex_5_2 &lt;- airquality |&gt;
  mutate(is_outlier = Wind &lt; (q1 - 1.5 * iqr) | Wind &gt; (q3 + 1.5 * iqr))
sum(ex_5_2$is_outlier, na.rm = TRUE)
#&gt; [1] 3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The Tukey rule is robust because both Q1 and Q3 are insensitive to extreme values, unlike the mean-and-sd alternative. Three observations exceed the fence on Wind. Flagging rather than deleting preserves the audit trail; once you confirm the values are sensor errors you can drop them, but quietly removing them at the cleaning stage hides distributional information from later modelling steps.</p>

</details>

<h3>Exercise 5.3: Z-score outliers computed within groups</h3>

<p><strong>Task:</strong> A safety analyst wants Ozone readings that are unusual relative to their own month, not the year as a whole, because Ozone climbs in summer and a "high" August reading may be a typical September reading. Compute a per-month z-score for <code>Ozone</code> in <code>airquality</code> and flag absolute z greater than 2. Save the augmented tibble to <code>ex_5_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 153 x 8
#&gt; # Groups:   Month [5]
#&gt;    Ozone Solar.R  Wind  Temp Month   Day      z is_outlier
#&gt;    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;dbl&gt; &lt;lgl&gt;
#&gt; 1     41     190   7.4    67     5     1 0.624  FALSE
#&gt; 2     36     118   8      72     5     2 0.358  FALSE
#&gt; ...
#&gt; sum(ex_5_3$is_outlier, na.rm = TRUE)
#&gt; [1] 6</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- airquality |&gt;
  group_by(Month) |&gt;
  mutate(
    z          = (Ozone - mean(Ozone, na.rm = TRUE)) / sd(Ozone, na.rm = TRUE),
    is_outlier = abs(z) &gt; 2
  )
sum(ex_5_3$is_outlier, na.rm = TRUE)
#&gt; [1] 6</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Group-relative z-scoring controls for the predictable monthly drift in air quality so the <a class="auto-link" href="Outlier-Treatment-With-R.html" title="Outlier Treatment with R">outlier</a> flag tracks anomalies, not seasonality. The choice of threshold 2 is conventional but data-dependent; for small per-group samples the t-distribution fence (<code>qt(0.975, df)</code>) is more honest. The base-R shortcut <code>scale()</code> returns a matrix, so dplyr's manual formula is cleaner inside <code>mutate()</code>.</p>

</details>

<h3>Exercise 5.4: Cross-column validation: start before end</h3>

<p><strong>Task:</strong> A logistics coordinator imports shipment events and any row where <code>ship_date</code> is later than <code>delivery_date</code> is a logical impossibility that must be flagged for manual review. Build an <code>invalid_dates</code> column on the inline tibble that is <code>TRUE</code> whenever <code>ship_date &gt; delivery_date</code> (treat NA as valid until proven otherwise), and save the augmented tibble to <code>ex_5_4</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">shipments &lt;- tibble(
  shipment_id   = 1:5,
  ship_date     = as.Date(c(&quot;2026-01-10&quot;, &quot;2026-01-12&quot;, &quot;2026-02-01&quot;,
                            NA,           &quot;2026-03-05&quot;)),
  delivery_date = as.Date(c(&quot;2026-01-12&quot;, &quot;2026-01-11&quot;, &quot;2026-02-05&quot;,
                            &quot;2026-03-01&quot;, &quot;2026-03-04&quot;))
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 5 x 4
#&gt;   shipment_id ship_date  delivery_date invalid_dates
#&gt;         &lt;int&gt; &lt;date&gt;     &lt;date&gt;        &lt;lgl&gt;
#&gt; 1           1 2026-01-10 2026-01-12    FALSE
#&gt; 2           2 2026-01-12 2026-01-11    TRUE
#&gt; 3           3 2026-02-01 2026-02-05    FALSE
#&gt; 4           4 NA         2026-03-01    FALSE
#&gt; 5           5 2026-03-05 2026-03-04    TRUE</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">shipments &lt;- tibble(
  shipment_id   = 1:5,
  ship_date     = as.Date(c(&quot;2026-01-10&quot;, &quot;2026-01-12&quot;, &quot;2026-02-01&quot;,
                            NA,           &quot;2026-03-05&quot;)),
  delivery_date = as.Date(c(&quot;2026-01-12&quot;, &quot;2026-01-11&quot;, &quot;2026-02-05&quot;,
                            &quot;2026-03-01&quot;, &quot;2026-03-04&quot;))
)
ex_5_4 &lt;- # your code here
ex_5_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_4 &lt;- shipments |&gt;
  mutate(invalid_dates = !is.na(ship_date) &amp;
                         !is.na(delivery_date) &amp;
                         ship_date &gt; delivery_date)
ex_5_4
#&gt; # A tibble: 5 x 4
#&gt;   shipment_id ship_date  delivery_date invalid_dates
#&gt;         &lt;int&gt; &lt;date&gt;     &lt;date&gt;        &lt;lgl&gt;
#&gt; 1           1 2026-01-10 2026-01-12    FALSE
#&gt; 2           2 2026-01-12 2026-01-11    TRUE
#&gt; 3           3 2026-02-01 2026-02-05    FALSE
#&gt; 4           4 NA         2026-03-01    FALSE
#&gt; 5           5 2026-03-05 2026-03-04    TRUE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The NA guards in front of the comparison are crucial: in R, any comparison with <code>NA</code> returns <code>NA</code>, which would cascade into the <code>invalid_dates</code> column and pollute the validation summary. By short-circuiting through <code>!is.na()</code> first, you keep the flag strictly logical. For richer cross-column rules consider the <code>validate</code> package, which lets you declare constraints once and apply them to any data frame.</p>

</details>

<h3>Exercise 5.5: Winsorize extreme values at 1st and 99th percentiles</h3>

<p><strong>Task:</strong> A risk team prefers to cap rather than drop extreme values because dropping shrinks the sample and skews downstream variance. Winsorize the <code>Ozone</code> column of <code>airquality</code> at the 1st and 99th percentiles: every value below P1 becomes P1, every value above P99 becomes P99. Save the resulting tibble to <code>ex_5_5</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 153 x 6
#&gt;    Ozone Solar.R  Wind  Temp Month   Day
#&gt;    &lt;dbl&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1   41      190   7.4    67     5     1
#&gt; 2   36      118   8      72     5     2
#&gt; ...
#&gt; range(ex_5_5$Ozone, na.rm = TRUE)
#&gt; [1]  1.00 152.84</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_5 &lt;- # your code here
ex_5_5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">caps &lt;- quantile(airquality$Ozone, c(0.01, 0.99), na.rm = TRUE)
ex_5_5 &lt;- airquality |&gt;
  mutate(Ozone = pmin(pmax(Ozone, caps[1]), caps[2]))
range(ex_5_5$Ozone, na.rm = TRUE)
#&gt; [1]  1.00 152.84</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>pmax(x, lo)</code> lifts every element below <code>lo</code> up to <code>lo</code>; <code>pmin(..., hi)</code> brings the high tail down. Composing the two is the winsorize-in-one-step idiom. Always document the cap thresholds so reviewers can reproduce the transformation; the alternative <code>DescTools::Winsorize()</code> does the same arithmetic with a friendlier API. Use winsorizing on heavy-tailed inputs to linear models where a few extreme rows dominate the coefficient estimates.</p>

</details>

<h2>Section 6. End-to-end cleaning pipelines (5 problems)</h2>

<h3>Exercise 6.1: Standardize messy column names</h3>

<p><strong>Task:</strong> A reporting analyst inherits a CSV with column headers like <code>&quot;First Name &quot;</code>, <code>&quot;Email-Address&quot;</code>, <code>&quot;Phone #&quot;</code>. Build a cleaned tibble where every name is lowercase snake_case with no leading/trailing whitespace and no punctuation. Use <code>rename_with()</code> plus a <code>gsub()</code> chain. Save the renamed tibble to <code>ex_6_1</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw_df &lt;- tibble(
  `First Name `   = c(&quot;Ada&quot;, &quot;Bob&quot;),
  `Email-Address` = c(&quot;a@x.io&quot;, &quot;b@y.io&quot;),
  `Phone #`       = c(&quot;415-1&quot;, &quot;415-2&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 2 x 3
#&gt;   first_name email_address phone
#&gt;   &lt;chr&gt;      &lt;chr&gt;         &lt;chr&gt;
#&gt; 1 Ada        a@x.io        415-1
#&gt; 2 Bob        b@y.io        415-2</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw_df &lt;- tibble(
  `First Name `   = c(&quot;Ada&quot;, &quot;Bob&quot;),
  `Email-Address` = c(&quot;a@x.io&quot;, &quot;b@y.io&quot;),
  `Phone #`       = c(&quot;415-1&quot;, &quot;415-2&quot;)
)
ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- raw_df |&gt;
  rename_with(~ .x |&gt;
                str_trim() |&gt;
                str_to_lower() |&gt;
                str_replace_all(&quot;[^a-z0-9]+&quot;, &quot;_&quot;) |&gt;
                str_replace_all(&quot;^_|_$&quot;, &quot;&quot;) |&gt;
                str_replace(&quot;address$&quot;, &quot;address&quot;) |&gt;
                str_replace(&quot;phone_+$&quot;, &quot;phone&quot;))
ex_6_1
#&gt; # A tibble: 2 x 3
#&gt;   first_name email_address phone
#&gt;   &lt;chr&gt;      &lt;chr&gt;         &lt;chr&gt;
#&gt; 1 Ada        a@x.io        415-1
#&gt; 2 Bob        b@y.io        415-2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The trim + lower + collapse-punctuation chain reproduces the core of <code>janitor::clean_names()</code> without an extra dependency. The trailing replacements strip stray underscores left at the beginning or end after the punctuation pass. For team work standardize on <code>janitor::clean_names()</code> so naming rules survive package upgrades and onboarding handoffs.</p>

</details>

<h3>Exercise 6.2: Tidy a wide messy survey export</h3>

<p><strong>Task:</strong> A market researcher exports a survey where each row is a respondent and each scored item (<code>q1</code>, <code>q2</code>, <code>q3</code>) is its own column, but downstream modelling wants long format with one row per respondent-item pair. Pivot the inline tibble to long format with columns <code>respondent</code>, <code>question</code>, <code>score</code>. Save the long tibble to <code>ex_6_2</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">survey &lt;- tibble(
  respondent = c(&quot;R1&quot;, &quot;R2&quot;, &quot;R3&quot;),
  q1         = c(5, 4, 3),
  q2         = c(2, 5, 4),
  q3         = c(4, NA, 5)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 9 x 3
#&gt;   respondent question score
#&gt;   &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 R1         q1           5
#&gt; 2 R1         q2           2
#&gt; 3 R1         q3           4
#&gt; 4 R2         q1           4
#&gt; 5 R2         q2           5
#&gt; 6 R2         q3          NA
#&gt; 7 R3         q1           3
#&gt; 8 R3         q2           4
#&gt; 9 R3         q3           5</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">survey &lt;- tibble(
  respondent = c(&quot;R1&quot;, &quot;R2&quot;, &quot;R3&quot;),
  q1         = c(5, 4, 3),
  q2         = c(2, 5, 4),
  q3         = c(4, NA, 5)
)
ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- survey |&gt;
  pivot_longer(cols = starts_with(&quot;q&quot;),
               names_to  = &quot;question&quot;,
               values_to = &quot;score&quot;)
ex_6_2
#&gt; # A tibble: 9 x 3
#&gt;   respondent question score
#&gt;   &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 R1         q1           5
#&gt; 2 R1         q2           2
#&gt; ...</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>pivot_longer()</code> is the canonical tidy reshape; <code>starts_with(&quot;q&quot;)</code> is a tidy-select helper that ignores the respondent column without needing to <a class="auto-link" href="R-Function-Operators.html" title="R Function Operators: Compose, Negate & Partial Application">negate</a> it explicitly. Long format is what most modelling and plotting functions expect because each variable now lives in its own column. To drop NA scores instead of carrying them through, add <code>values_drop_na = TRUE</code>.</p>

</details>

<h3>Exercise 6.3: Build a one-shot data quality summary report</h3>

<p><strong>Task:</strong> An ops engineer must produce a single-tibble quality summary for <code>airquality</code> showing, per column, the number of rows, the count and percent of NAs, and the data type. Build that summary using <code>purrr::map_dfr()</code> over <code>names(airquality)</code> and save the result to <code>ex_6_3</code>. Order columns so the worst-missing one appears on top.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 6 x 5
#&gt;   column      n n_missing pct_missing type
#&gt;   &lt;chr&gt;   &lt;int&gt;     &lt;int&gt;       &lt;dbl&gt; &lt;chr&gt;
#&gt; 1 Ozone     153        37      24.2   integer
#&gt; 2 Solar.R   153         7       4.58  integer
#&gt; 3 Wind      153         0       0     numeric
#&gt; 4 Temp      153         0       0     integer
#&gt; 5 Month     153         0       0     integer
#&gt; 6 Day       153         0       0     integer</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- map_dfr(names(airquality), function(col) {
  v &lt;- airquality[[col]]
  tibble(
    column      = col,
    n           = length(v),
    n_missing   = sum(is.na(v)),
    pct_missing = round(100 * mean(is.na(v)), 2),
    type        = typeof(v)
  )
}) |&gt; arrange(desc(n_missing))
ex_6_3
#&gt; # A tibble: 6 x 5
#&gt;   column      n n_missing pct_missing type
#&gt;   &lt;chr&gt;   &lt;int&gt;     &lt;int&gt;       &lt;dbl&gt; &lt;chr&gt;
#&gt; 1 Ozone     153        37       24.2  integer
#&gt; 2 Solar.R   153         7        4.58 integer
#&gt; 3 Wind      153         0        0    double
#&gt; 4 Temp      153         0        0    integer
#&gt; 5 Month     153         0        0    integer
#&gt; 6 Day       153         0        0    integer</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Walking <code>names(df)</code> and returning a one-row tibble per column is the most portable pattern; it works on any data frame without preassuming dplyr verbs. <code>mean(is.na(v))</code> is a tight idiom for missingness fraction because <code>TRUE</code>/<code>FALSE</code> average directly. Wire this function into a daily report so any spike in <code>pct_missing</code> triggers an alert before the change reaches dashboards.</p>

</details>

<h3>Exercise 6.4: Clean and validate a small transaction log</h3>

<p><strong>Task:</strong> A fraud analyst has a daily transactions tibble that arrives with messy strings, mixed types, and rows that violate business rules (negative amounts, transactions before account creation, duplicates). Build a pipeline that (1) standardizes <code>customer_id</code> to uppercase, (2) parses <code>amount</code> from <code>&quot;$1,234.50&quot;</code> style strings, (3) drops rows where <code>amount &lt; 0</code>, (4) deduplicates on <code>(customer_id, txn_time)</code> keeping the latest amount. Save the cleaned tibble to <code>ex_6_4</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(readr)
txns &lt;- tibble(
  customer_id = c(&quot;a1&quot;, &quot;A1&quot;, &quot;b2&quot;, &quot;B2&quot;, &quot;c3&quot;),
  amount      = c(&quot;$100.00&quot;, &quot;$120.00&quot;, &quot;-$50.00&quot;, &quot;$200.00&quot;, &quot;$0.99&quot;),
  txn_time    = as.POSIXct(c(&quot;2026-04-01 09:00&quot;, &quot;2026-04-01 09:00&quot;,
                             &quot;2026-04-01 10:00&quot;, &quot;2026-04-01 11:00&quot;,
                             &quot;2026-04-01 12:00&quot;), tz = &quot;UTC&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 3
#&gt;   customer_id amount txn_time
#&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;dttm&gt;
#&gt; 1 A1             120 2026-04-01 09:00:00
#&gt; 2 B2             200 2026-04-01 11:00:00
#&gt; 3 C3               0.99 2026-04-01 12:00:00</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(readr)
txns &lt;- tibble(
  customer_id = c(&quot;a1&quot;, &quot;A1&quot;, &quot;b2&quot;, &quot;B2&quot;, &quot;c3&quot;),
  amount      = c(&quot;$100.00&quot;, &quot;$120.00&quot;, &quot;-$50.00&quot;, &quot;$200.00&quot;, &quot;$0.99&quot;),
  txn_time    = as.POSIXct(c(&quot;2026-04-01 09:00&quot;, &quot;2026-04-01 09:00&quot;,
                             &quot;2026-04-01 10:00&quot;, &quot;2026-04-01 11:00&quot;,
                             &quot;2026-04-01 12:00&quot;), tz = &quot;UTC&quot;)
)
ex_6_4 &lt;- # your code here
ex_6_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_4 &lt;- txns |&gt;
  mutate(
    customer_id = str_to_upper(customer_id),
    amount      = parse_number(amount)
  ) |&gt;
  filter(amount &gt;= 0) |&gt;
  arrange(customer_id, txn_time, desc(amount)) |&gt;
  distinct(customer_id, txn_time, .keep_all = TRUE)
ex_6_4
#&gt; # A tibble: 3 x 3
#&gt;   customer_id amount txn_time
#&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;dttm&gt;
#&gt; 1 A1          120    2026-04-01 09:00:00
#&gt; 2 B2          200    2026-04-01 11:00:00
#&gt; 3 C3            0.99 2026-04-01 12:00:00</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The order of the verbs matters: parse amounts before filtering on them (otherwise the comparison happens on character data and is silently wrong); standardize the case of the dedup key before <code>distinct()</code> (so <code>&quot;a1&quot;</code> and <code>&quot;A1&quot;</code> collapse correctly); arrange before <code>distinct()</code> to control which row wins. A common production mistake is to swap the filter and parse steps, leaving <code>&quot;-$50.00&quot;</code> in place and turning a negative into a positive when later parsed.</p>

</details>

<h3>Exercise 6.5: End-to-end pipeline with explicit step-level checks</h3>

<p><strong>Task:</strong> An MLOps engineer wants the cleaning pipeline to fail loudly when assumptions break, so each cleaning step is wrapped in a <code>stopifnot()</code> check that the data still satisfies the contract afterward. Take the inline raw tibble and build a pipeline that (a) trims whitespace on <code>name</code>, (<a class="auto-link" href="Conditional-Probability-in-R.html" title="Conditional Probability in R: P(A|B), Independence, and Bayes — With Real Examples">b)</a> parses <code>age</code> to integer, (c) drops rows missing either field, (d) asserts the cleaned <code>age</code> is in <code>[0, 120]</code>, (e) asserts no duplicate names. Save the validated tibble to <code>ex_6_5</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw &lt;- tibble(
  name = c(&quot; Ada&quot;, &quot;Bob &quot;, &quot;Cleo&quot;, &quot;Dan&quot;, &quot;Bob &quot;),
  age  = c(&quot;30&quot;, &quot;45&quot;, &quot;x&quot;, &quot;27&quot;, &quot;45&quot;)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 2
#&gt;   name    age
#&gt;   &lt;chr&gt; &lt;int&gt;
#&gt; 1 Ada      30
#&gt; 2 Bob      45
#&gt; 3 Dan      27</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw &lt;- tibble(
  name = c(&quot; Ada&quot;, &quot;Bob &quot;, &quot;Cleo&quot;, &quot;Dan&quot;, &quot;Bob &quot;),
  age  = c(&quot;30&quot;, &quot;45&quot;, &quot;x&quot;, &quot;27&quot;, &quot;45&quot;)
)
ex_6_5 &lt;- # your code here
ex_6_5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">clean &lt;- raw |&gt;
  mutate(
    name = str_trim(name),
    age  = suppressWarnings(as.integer(age))
  ) |&gt;
  drop_na(name, age)

stopifnot(all(clean$age &gt;= 0 &amp; clean$age &lt;= 120))

ex_6_5 &lt;- clean |&gt;
  distinct(name, .keep_all = TRUE)

stopifnot(!anyDuplicated(ex_6_5$name))

ex_6_5
#&gt; # A tibble: 3 x 2
#&gt;   name    age
#&gt;   &lt;chr&gt; &lt;int&gt;
#&gt; 1 Ada      30
#&gt; 2 Bob      45
#&gt; 3 Dan      27</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Inline assertions turn silent data drift into loud failures: the next time <code>age</code> arrives with <code>&quot;-5&quot;</code> or <code>&quot;300&quot;</code>, the script crashes at the source rather than the model finding it three steps downstream. <code>suppressWarnings()</code> is appropriate here because the failed parse on <code>&quot;x&quot;</code> produces an NA that <code>drop_na()</code> removes by design; without the suppression the log fills with noise. For larger pipelines promote these checks into a <code>validate::confront()</code> ruleset, which produces a structured QA report.</p>

</details>

<h2>What to do next</h2>

<p>You have practised the full data-cleaning loop: detecting missingness, deduplicating, coercing types, normalizing strings, flagging outliers, and validating end-to-end pipelines. Take the next step with these companion resources on r-statistics.co:</p>

<ul>

<li><a href="dplyr-Exercises-in-R.html">dplyr Exercises in R</a>: drill the verbs (<code>mutate</code>, <code>filter</code>, <code>summarise</code>, <code>group_by</code>) that powered most of the solutions above.</li>

<li><a href="tidyr-Exercises-in-R.html">tidyr Exercises in R</a>: focused practice on <code>pivot_longer</code>, <code>pivot_wider</code>, <code>separate_wider_*</code>, and <code>fill</code>.</li>

<li><a href="Strings-Exercises-in-R.html">Strings Exercises in R</a>: deeper drills on <code>stringr</code> regex patterns for cleaning text fields.</li>

<li><a href="Dates-and-Times-Exercises-in-R.html">Dates and Times Exercises in R</a>: sharpen the <a class="auto-link" href="lubridate-in-R.html" title="lubridate in R: Parse Dates Once, Stop Fighting Time Zones Forever">lubridate</a> parsing skills used in Section 3.</li>

</ul>

{% endraw %}