---
title: "Decision Tree Exercises in R: 18 Real-World Practice Problems"
description: "Practice decision trees in R with 18 scenario-based exercises: rpart fits, tuning, plotting, predictions, pruning. Hidden solutions and explanations."
keywords: "decision tree exercises in R, rpart practice problems, R decision tree practice, rpart exercises, decision tree pruning R"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "decision tree exercises in r|rpart practice|practice rpart|rpart exercises|decision tree pruning"
auto_link_case_sensitive: false
sidebar_title: "Decision Tree Exercises"
sidebar_order: "172"
fr_parent: "R-Tutorial.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>Decision Tree Exercises in R: 18 Real-World Practice Problems</h1>
<p class="lead">Eighteen scenario-based decision tree exercises grouped into five themed sections covering tree fitting, hyperparameter tuning, visualization, prediction, and pruning with the rpart package. Every problem ships with an expected result so you can verify, and solutions are hidden behind reveal toggles so you actually try first.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="18" data-time="45" data-xp="270"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(rpart)
library(rpart.plot)
library(dplyr)
library(tibble)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Fit your first decision tree (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Decision-Tree-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Grow a classification tree on iris</h3>
<p class="exercise-task"><strong>Task:</strong> Fit a classification tree predicting <code>Species</code> from all four numeric measurements in the built-in <code>iris</code> dataset using <code>rpart()</code>. Print the fitted model so you can see the splits, the node counts, and the leaf class probabilities. Save the fitted object to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 150 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

1) root 150 100 setosa (0.33333333 0.33333333 0.33333333)  
  2) Petal.Length&lt; 2.45 50   0 setosa (1.00000000 0.00000000 0.00000000) *
  3) Petal.Length&gt;=2.45 100  50 versicolor (0.00000000 0.50000000 0.50000000)  
    6) Petal.Width&lt; 1.75 54   5 versicolor (0.00000000 0.90740741 0.09259259) *
    7) Petal.Width&gt;=1.75 46   1 virginica (0.00000000 0.02173913 0.97826087) *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A tree only needs to know which column is the outcome and which dataset to learn the splits from.</p><p>Pass the formula <code>Species ~ .</code> and <code>data = iris</code> to the tree-fitting function; the dot stands in for every other column.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- rpart(Species ~ ., data = iris)
ex_1_1
#&gt; n= 150
#&gt;
#&gt; node), split, n, loss, yval, (yprob)
#&gt;       * denotes terminal node
#&gt;
#&gt; 1) root 150 100 setosa (0.33333 0.33333 0.33333)
#&gt;   2) Petal.Length&lt; 2.45 50   0 setosa (1.00000 0.00000 0.00000) *
#&gt;   3) Petal.Length&gt;=2.45 100  50 versicolor (0.00000 0.50000 0.50000)
#&gt;     6) Petal.Width&lt; 1.75 54   5 versicolor (0.00000 0.90741 0.09259) *
#&gt;     7) Petal.Width&gt;=1.75 46   1 virginica (0.00000 0.02174 0.97826) *</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rpart()</code> infers the task from the response: a factor <code>Species</code> triggers classification (Gini by default), a numeric response would trigger regression. The formula <code>Species ~ .</code> says "use every other column as a predictor." Each printed line is a node: <code>n</code> is the count, <code>loss</code> the misclassified count at that node, <code>yval</code> the majority class, and the parenthesized vector is per-class probability. Asterisks mark terminal leaves.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Decision-Tree-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Predict mpg with a regression tree on mtcars</h3>
<p class="exercise-task"><strong>Task:</strong> A consumer-magazine reviewer wants a quick rule-based explanation of fuel economy. Fit a regression tree predicting <code>mpg</code> from every other column of the built-in <code>mtcars</code> dataset using <code>rpart()</code>, and save the fitted object to <code>ex_1_2</code>. Print it to inspect the splits.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 32 

node), split, n, deviance, yval
      * denotes terminal node

1) root 32 1126.04700 20.09062  
  2) cyl&gt;=5 21  198.47240 16.64762  
    4) hp&gt;=192.5 7   28.82857 13.41429 *
    5) hp&lt; 192.5 14   59.87214 18.26429 *
  3) cyl&lt; 5 11  203.38550 26.66364 *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>When the outcome column holds numbers, the same tree-growing approach predicts a value instead of a class, with no extra setting.</p><p>Use the formula <code>mpg ~ .</code> with <code>data = mtcars</code>; the dot picks up every remaining column as a predictor.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- rpart(mpg ~ ., data = mtcars)
ex_1_2
#&gt; n= 32
#&gt;
#&gt; node), split, n, deviance, yval
#&gt;       * denotes terminal node
#&gt;
#&gt; 1) root 32 1126.0470 20.09062
#&gt;   2) cyl&gt;=5 21  198.4724 16.64762
#&gt;     4) hp&gt;=192.5 7   28.8286 13.41429 *
#&gt;     5) hp&lt; 192.5 14  72.5571 18.26429 *
#&gt;   3) cyl&lt; 5 11  203.3855 26.66364 *</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Because <code>mpg</code> is numeric, <code>rpart()</code> fits an <a class="auto-link" href="https://r-statistics.co/How-to-do-One-Way-ANOVA-in-R.html" title="One-Way ANOVA in R: Compare Group Means (With Examples)">anova</a> (regression) tree by default and minimises within-node sum of squares. The printed <code>deviance</code> is the residual sum of squares at that node, and <code>yval</code> is the mean response. The first split on <code>cyl</code> mirrors what you would expect from EDA: heavier engines run lower mpg. You can force regression explicitly with <code>method = "anova"</code> if your response could be misinterpreted.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Build a regression tree on airquality after dropping NAs</h3>
<p class="exercise-task"><strong>Task:</strong> Predict daily <code>Ozone</code> from <code>Solar.R</code>, <code>Wind</code>, <code>Temp</code>, and <code>Month</code> in the built-in <code>airquality</code> dataset. The dataset has missing readings, so apply <code>na.omit()</code> first and fit the tree on the cleaned data. Save the fitted tree to <code>ex_1_3</code> and print it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 111 

node), split, n, deviance, yval
      * denotes terminal node

 1) root 111 121801.9000 42.09910  
   2) Temp&lt; 82.5 77  42143.2500 26.77922  
     4) Wind&gt;=7.15 68  10886.7500 22.25000  
       8) Solar.R&lt; 79.5 18    777.1111 12.22222 *
       9) Solar.R&gt;=79.5 50   7648.0200 25.86000  
        18) Temp&lt; 77.5 32   2412.9690 20.96875 *
        19) Temp&gt;=77.5 18   3108.4440 34.55556 *
     5) Wind&lt; 7.15 9  19322.0000 61.00000 *
   3) Temp&gt;=82.5 34  20659.5600 76.79412  
     6) Wind&gt;=10.6 7   1183.4290 48.71429 *
     7) Wind&lt; 10.6 27  12525.8500 84.07407  
      14) Temp&lt; 88.5 13   7307.2310 74.53846 *
      15) Temp&gt;=88.5 14   2938.9290 92.92857 *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>List the four wanted predictors explicitly on the right of the formula rather than using the catch-all dot.</p><p>Write <code>Ozone ~ Solar.R + Wind + Temp + Month</code> and point <code>data</code> at the already-cleaned <code>clean_air</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">clean_air &lt;- na.omit(airquality)

ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">clean_air &lt;- na.omit(airquality)

ex_1_3 &lt;- rpart(Ozone ~ Solar.R + Wind + Temp + Month, data = clean_air)
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rpart()</code> does not natively handle <code>NA</code> in the response: those rows would be silently dropped from the model frame anyway, so cleaning first makes the row count explicit (111 of 153 retained). Predictor <code>NA</code>s could be handled via surrogate splits (covered later), but <code>na.omit()</code> is the simplest baseline. The first split on <code>Temp</code> is a strong signal that ozone formation is photochemical and temperature-driven.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-1-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.4: Fit a churn classifier on a small inline customer table</h3>
<p class="exercise-task"><strong>Task:</strong> A subscription business is prototyping a churn model on a 20-row sample. Construct the inline <code>churn_df</code> shown below, then fit a classification tree predicting <code>churn</code> from <code>tenure_mo</code>, <code>monthly_charges</code>, and <code>contract</code>. Save the fitted tree to <code>ex_1_4</code> and print it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; n= 20
#&gt;
#&gt; node), split, n, loss, yval, (yprob)
#&gt;       * denotes terminal node
#&gt;
#&gt; 1) root 20 8 no (0.6000000 0.4000000)
#&gt;   2) tenure_mo&gt;=10 11 0 no (1.0000000 0.0000000) *
#&gt;   3) tenure_mo&lt; 10  9 1 yes (0.1111111 0.8888889) *</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Spell out the three predictor columns in the formula; the outcome belongs on the left of the tilde.</p><p>Use <code>churn ~ tenure_mo + monthly_charges + contract</code> with <code>data = churn_df</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">churn_df &lt;- tibble(
  customer_id     = 1:20,
  tenure_mo       = c(2, 6, 18, 1, 24, 3, 12, 36, 4, 9, 15, 2, 30, 22, 5, 8, 28, 1, 17, 11),
  monthly_charges = c(85, 70, 45, 95, 30, 80, 55, 25, 90, 60, 40, 88, 28, 35, 75, 65, 32, 92, 42, 50),
  contract        = c("month","month","year","month","two_year","month","year","two_year","month","year",
                      "year","month","two_year","two_year","month","year","two_year","month","year","year"),
  churn           = factor(c("no","yes","no","yes","no","yes","no","no","yes","no",
                             "no","yes","no","no","yes","no","no","yes","no","no"))
)

ex_1_4 &lt;- # your code here
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- rpart(churn ~ tenure_mo + monthly_charges + contract, data = churn_df)
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Even on 20 rows, <code>rpart()</code> finds a clean single-split rule on tenure: customers under 10 months are mostly churners, and longer-tenured customers are not. Notice <code>monthly_charges</code> and <code>contract</code> did not enter the tree because tenure dominated the impurity reduction at the root. The default <code>cp = 0.01</code> and <code>minsplit = 20</code> are gentle enough that tiny datasets often stop after one split. We will tune these in the next section.</p>
</details>
</section>
<h2>Section 2. Tune tree growth parameters (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Decision-Tree-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Cap tree depth at 2 with maxdepth</h3>
<p class="exercise-task"><strong>Task:</strong> Refit the airquality regression tree from Exercise 1.3, but force the tree to stop at depth 2 by passing <code>control = rpart.control(maxdepth = 2)</code>. This produces a stubbier tree that is easier to communicate to non-technical stakeholders. Save it to <code>ex_2_1</code> and print it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 111 

node), split, n, deviance, yval
      * denotes terminal node

1) root 111 121801.900 42.09910  
  2) Temp&lt; 82.5 77  42143.250 26.77922  
    4) Wind&gt;=7.15 68  10886.750 22.25000 *
    5) Wind&lt; 7.15 9  19322.000 61.00000 *
  3) Temp&gt;=82.5 34  20659.560 76.79412  
    6) Wind&gt;=10.6 7   1183.429 48.71429 *
    7) Wind&lt; 10.6 27  12525.850 84.07407 *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Tree growth is capped by handing the model a bundle of control settings, one of which limits how many levels deep splits may go.</p><p>Add <code>control = rpart.control(maxdepth = 2)</code> to the same <code>Ozone ~ ...</code> fit on <code>na.omit(airquality)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- rpart(
  Ozone ~ Solar.R + Wind + Temp + Month,
  data    = na.omit(airquality),
  control = rpart.control(maxdepth = 2)
)
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>maxdepth</code> counts edges from the root, so <code>maxdepth = 2</code> permits at most one further split below each child of the root. The deeper Solar.R split present in the unconstrained tree is dropped here. <code>maxdepth</code> is a hard ceiling that bypasses cross-validation; it is useful when a stakeholder has a fixed display budget (a slide, a report) rather than a statistical motivation.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Lower minsplit to grow a deeper mtcars tree</h3>
<p class="exercise-task"><strong>Task:</strong> Refit the mtcars regression tree but allow splits in nodes as small as 5 observations using <code>rpart.control(minsplit = 5, cp = 0.005)</code>. The lower complexity threshold keeps splits that the default <code>cp = 0.01</code> would prune. Save the fit to <code>ex_2_2</code> and print it to see the extra splits.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 32 

node), split, n, deviance, yval
      * denotes terminal node

 1) root 32 1126.047000 20.09062  
   2) wt&gt;=2.26 26  346.566500 17.78846  
     4) cyl&gt;=7 14   85.200000 15.10000  
       8) disp&gt;=450 2    0.000000 10.40000 *
       9) disp&lt; 450 12   33.656670 15.88333  
        18) hp&gt;=205 5    3.388000 14.62000 *
        19) hp&lt; 205 7   16.588570 16.78571  
          38) disp&lt; 339 5    3.348000 15.92000 *
          39) disp&gt;=339 2    0.125000 18.95000 *
     5) cyl&lt; 7 12   42.122500 20.92500  
      10) wt&gt;=3.3275 3    1.086667 18.36667 *
      11) wt&lt; 3.3275 9   14.855560 21.77778  
        22) hp&gt;=96 6    2.260000 21.00000 *
        23) hp&lt; 96 3    1.706667 23.33333 *
   3) wt&lt; 2.26 6   44.553330 30.06667  
     6) qsec&lt; 19.185 4   14.907500 28.52500 *
     7) qsec&gt;=19.185 2    1.125000 33.15000 *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Two thresholds decide whether a node may split: a <a class="auto-link" href="dials-min_n-in-R.html" title="dials min_n() in R: Tune Minimum Node Size for Tree Models">minimum node size</a> and a minimum improvement; loosen both to grow deeper.</p><p>Pass <code>control = rpart.control(minsplit = 5, cp = 0.005)</code> to the <code>mpg ~ .</code> fit on <code>mtcars</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- rpart(
  mpg ~ .,
  data    = mtcars,
  control = rpart.control(minsplit = 5, cp = 0.005)
)
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Two parameters interact here. <code>minsplit</code> is the structural floor: a node with fewer than 5 observations is never considered for splitting. <code>cp</code> is the statistical floor: a candidate split is kept only if it reduces overall lack of fit by at least <code>cp</code> times the root deviance. Lowering both lets the tree grow until either floor is hit. This is the standard approach for "grow then prune": grow large with low <code>cp</code>, then prune back to the cross-validated optimum (Section 5).</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Use a high cp for a deliberately conservative classifier</h3>
<p class="exercise-task"><strong>Task:</strong> A risk and compliance team wants the simplest possible decision rule on <code>iris</code> for an audit document, even at the cost of accuracy. Fit a classification tree on <code>iris</code> with <code>cp = 0.5</code> so only the single biggest impurity reduction survives pruning. Save to <code>ex_2_3</code> and print it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 150 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

1) root 150 100 setosa (0.3333333 0.3333333 0.3333333) *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A high complexity threshold keeps only the splits that deliver a large impurity reduction and discards the rest.</p><p>Set <code>control = rpart.control(cp = 0.5)</code> on the <code>Species ~ .</code> fit over <code>iris</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- rpart(
  Species ~ .,
  data    = iris,
  control = rpart.control(cp = 0.5)
)
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>cp = 0.5</code> is unusually aggressive: only a split that cuts at least half of the root impurity survives. On <code>iris</code>, that single survivor is the textbook <code>Petal.Length &lt; 2.45</code> rule, which perfectly isolates setosa. Auditors and regulators often prefer this kind of one-line rule because it is trivially explainable and trivially testable, even if it groups versicolor and virginica together. Tune <code>cp</code> upward whenever interpretability outranks accuracy.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Decision-Tree-Exercises-in-R-ex-2-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.4: Compare node counts between default and deeply grown iris trees</h3>
<p class="exercise-task"><strong>Task:</strong> Grow two iris classification trees: a default one (<code>fit_default</code>) and a deeply grown one (<code>fit_deep</code>) using <code>rpart.control(cp = 0.001, minsplit = 2)</code>. Return a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> giving the node count of each tree (use <code>nrow(fit$frame)</code>), saved to <code>ex_2_4</code>, so you can quantify how much complexity the defaults suppress.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $nodes_default
#&gt; [1] 5
#&gt;
#&gt; $nodes_deep
#&gt; [1] 17</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Build one tree with the package defaults and a second with a far lower complexity threshold and minimum node size.</p><p><code>fit_default</code> is a plain <code>rpart(Species ~ ., data = iris)</code>; <code>fit_deep</code> adds <code>control = rpart.control(cp = 0.001, minsplit = 2)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_default &lt;- # your code here
fit_deep    &lt;- # your code here

ex_2_4 &lt;- list(
  nodes_default = nrow(fit_default$frame),
  nodes_deep    = nrow(fit_deep$frame)
)
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_default &lt;- rpart(Species ~ ., data = iris)
fit_deep    &lt;- rpart(
  Species ~ .,
  data    = iris,
  control = rpart.control(cp = 0.001, minsplit = 2)
)

ex_2_4 &lt;- list(
  nodes_default = nrow(fit_default$frame),
  nodes_deep    = nrow(fit_deep$frame)
)
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>fit$frame</code> is the internal node table; each row is one node (internal or terminal), so <code>nrow()</code> is a clean size proxy. The default tree has 5 nodes (3 leaves), the deep tree balloons to 17 because the lower <code>cp</code> and <code>minsplit = 2</code> permit splits that fit individual misclassified flowers. Most of those extra splits will fail cross-validation, which motivates the printcp / prune workflow in Section 5. Always grow then prune; never trust a tree fit at very low <code>cp</code> directly.</p>
</details>
</section>
<h2>Section 3. Visualize and interpret the tree (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Decision-Tree-Exercises-in-R-ex-3-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 3.1: Plot the iris tree with rpart.plot</h3>
<p class="exercise-task"><strong>Task:</strong> Take the iris classification tree from Exercise 1.1 and render it with <code>rpart.plot()</code> from the <code>rpart.plot</code> package. Use default options first so you see the standard layout: split labels on edges, node class with probability, and percent of the sample at each node. Save the underlying fit to <code>ex_3_1</code>; the plot is a side effect.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A tree diagram with three leaves:
#&gt;   - leftmost leaf labelled "setosa  1.00 .00 .00  33%"
#&gt;   - middle leaf labelled "versicolor  .00 .91 .09  36%"
#&gt;   - rightmost leaf labelled "virginica  .00 .02 .98  31%"
#&gt; Edges show "Petal.Length &lt; 2.5" and "Petal.Width &lt; 1.8" splits.</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A fitted tree object can be handed straight to a dedicated diagram drawer whose defaults already show classes, probabilities, and node percentages.</p><p>Call <code>rpart.plot()</code> on <code>ex_3_1</code> with no extra arguments.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- rpart(Species ~ ., data = iris)
# your plot call here</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- rpart(Species ~ ., data = iris)
rpart.plot(ex_3_1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rpart.plot()</code> is purpose-built for <code>rpart</code> objects and is far more readable than the base <code>plot.rpart()</code> plus <code>text.rpart()</code> combination. By default it shows the predicted class, the per-class probability vector, and the percentage of training rows that land in each leaf, which is everything a non-technical reader needs to follow the tree. Tweak <code>type</code> (0-5), <code>extra</code> (0-104), and <code>box.palette</code> to control verbosity and colour. For high-stakes communication, <code>extra = 104</code> adds the loss count to leaves.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Rank predictors by variable importance</h3>
<p class="exercise-task"><strong>Task:</strong> A modeller reviewing the mtcars regression tree wants to know which predictors actually drove the splits. Fit the tree as in Exercise 1.2, then extract the <code>variable.importance</code> slot, which sums the impurity reduction credited to each predictor (including surrogate splits). Save the named numeric vector to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>      cyl      disp        hp        wt      qsec        vs      carb      gear 
724.18935 721.08062 702.29023 573.72817 442.05737 395.01237  31.36333  15.68167
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The fitted model already stores a ranking of how much each predictor contributed; you just reach into the object for it.</p><p>Pull the <code>variable.importance</code> element out of <code>fit_mt</code> with the <code>$</code> accessor.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_mt &lt;- rpart(mpg ~ ., data = mtcars)

ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_mt &lt;- rpart(mpg ~ ., data = mtcars)

ex_3_2 &lt;- fit_mt$variable.importance
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>variable.importance</code> is an unnormalised numeric vector indexed by predictor name, summing across both primary and surrogate splits. A predictor can score high even if it never won a primary split, because rpart credits surrogates that mimic the chosen split. To convert to a percentage, divide by the sum: <code>round(100 * fit_mt$variable.importance / sum(fit_mt$variable.importance), 1)</code>. Cross-check against the printed tree: predictors that win primary splits should sit at the top.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Extract the leaf rules for a marketing campaign brief</h3>
<p class="exercise-task"><strong>Task:</strong> A marketing analyst needs the if-then rules from a churn tree to hand off to a campaigns team. Refit the churn tree from Exercise 1.4, then call <code>rpart.rules()</code> from <code>rpart.plot</code> to produce a <a class="auto-link" href="Tidy-Data-in-R.html" title="Tidy Data: The One Rule That Makes R Code Readable, Reusable, and Debuggable">tidy data</a> frame of the leaf rules with predicted class probabilities. Save to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;    churn                          
#&gt;  1  0.00 when tenure_mo &gt;=       10
#&gt;  2  0.89 when tenure_mo &lt;        10</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Instead of reading the indented tree printout, ask for a tidy table where each row is one leaf's if-then rule.</p><p>Call <code>rpart.rules()</code> on the <code>fit_churn</code> object.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">churn_df &lt;- tibble(
  customer_id     = 1:20,
  tenure_mo       = c(2, 6, 18, 1, 24, 3, 12, 36, 4, 9, 15, 2, 30, 22, 5, 8, 28, 1, 17, 11),
  monthly_charges = c(85, 70, 45, 95, 30, 80, 55, 25, 90, 60, 40, 88, 28, 35, 75, 65, 32, 92, 42, 50),
  contract        = c("month","month","year","month","two_year","month","year","two_year","month","year",
                      "year","month","two_year","two_year","month","year","two_year","month","year","year"),
  churn           = factor(c("no","yes","no","yes","no","yes","no","no","yes","no",
                             "no","yes","no","no","yes","no","no","yes","no","no"))
)

fit_churn &lt;- rpart(churn ~ tenure_mo + monthly_charges + contract, data = churn_df)

ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_churn &lt;- rpart(churn ~ tenure_mo + monthly_charges + contract, data = churn_df)

ex_3_3 &lt;- rpart.rules(fit_churn)
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rpart.rules()</code> walks every leaf and emits the conjunction of conditions that route a row there, alongside the predicted value. It is far easier to drop into a campaign brief than the indented printout of the fitted object. For multi-class problems it returns one column per class probability. If you want plain English output, post-process the data frame with <code>glue::glue()</code> or paste rules into a templated email. Keep in mind: every <code>rpart.rules()</code> row is mutually exclusive and collectively exhaustive over the training space.</p>
</details>
</section>
<h2>Section 4. Predict and evaluate (4 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Predict class labels back onto iris</h3>
<p class="exercise-task"><strong>Task:</strong> Use the iris tree from Exercise 1.1 to predict class labels for every row of <code>iris</code> using <code>predict(..., type = "class")</code>. Save the resulting factor to <code>ex_4_1</code>. Inspect the first few values to confirm the prediction shape.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;      1      2      3      4      5      6
#&gt; setosa setosa setosa setosa setosa setosa
#&gt; Levels: setosa versicolor virginica</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Reuse the fitted tree to score rows, asking for the single most likely category rather than raw scores.</p><p>Call <code>predict()</code> with <code>fit_iris</code>, the <code>iris</code> data, and <code>type = "class"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_iris &lt;- rpart(Species ~ ., data = iris)

ex_4_1 &lt;- # your code here
head(ex_4_1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_iris &lt;- rpart(Species ~ ., data = iris)

ex_4_1 &lt;- predict(fit_iris, iris, type = "class")
head(ex_4_1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> For a classification rpart, <code>type = "class"</code> returns the majority class at the leaf each row falls into, as a factor with the same levels as the training response. Without <code>type</code>, you would get the per-class probability matrix (the next exercise). Always pass <code>newdata</code> explicitly even when you want training predictions; relying on the default fitted values from the model object is a frequent source of leakage in larger pipelines.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Predict class probabilities on iris</h3>
<p class="exercise-task"><strong>Task:</strong> Use the same iris tree to produce the class probability matrix instead of hard labels by passing <code>type = "prob"</code> to <code>predict()</code>. Save the matrix to <code>ex_4_2</code> and inspect the first six rows.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   setosa versicolor virginica
#&gt; 1      1          0         0
#&gt; 2      1          0         0
#&gt; 3      1          0         0
#&gt; 4      1          0         0
#&gt; 5      1          0         0
#&gt; 6      1          0         0</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The same scoring step can return a full set of per-category likelihoods instead of one hard label.</p><p>Call <code>predict()</code> with <code>fit_iris</code>, <code>iris</code>, and <code>type = "prob"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_iris &lt;- rpart(Species ~ ., data = iris)

ex_4_2 &lt;- # your code here
head(ex_4_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_iris &lt;- rpart(Species ~ ., data = iris)

ex_4_2 &lt;- predict(fit_iris, iris, type = "prob")
head(ex_4_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Probabilities from a single rpart tree are the per-class proportions inside the leaf the row lands in, so within one leaf every row gets identical probabilities. This is why ROC and lift curves built on a single tree look "stair-stepped." Bagged or random forest ensembles smooth these out by averaging across many trees. For threshold tuning or calibration work, prefer probabilities to hard labels.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Confusion matrix for iris training predictions</h3>
<p class="exercise-task"><strong>Task:</strong> Cross-tabulate the predicted class labels from Exercise 4.1 against the true <code>Species</code> using <code>table()</code>, with predicted as rows and actual as columns. Save the resulting <a class="auto-link" href="Logistic-Regression-Exercises-in-R.html" title="Logistic Regression Exercises in R: 10 Classification Practice Problems, Solved Step-by-Step">confusion matrix</a> to <code>ex_4_3</code>. The off-diagonals tell you which species the tree confuses.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;             actual
#&gt; predicted    setosa versicolor virginica
#&gt;   setosa         50          0         0
#&gt;   versicolor      0         49         5
#&gt;   virginica       0          1        45</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Cross-tabulating two parallel vectors of labels gives a grid whose diagonal counts the correct calls.</p><p>Pass <code>predicted = preds</code> and <code>actual = iris$Species</code> to <code>table()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_iris &lt;- rpart(Species ~ ., data = iris)
preds    &lt;- predict(fit_iris, iris, type = "class")

ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_iris &lt;- rpart(Species ~ ., data = iris)
preds    &lt;- predict(fit_iris, iris, type = "class")

ex_4_3 &lt;- table(predicted = preds, actual = iris$Species)
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>table()</code> with named arguments produces a labelled contingency. The 6 misclassifications (5 versicolor predicted as virginica, 1 virginica predicted as versicolor) match what the printed tree's leaf loss counts foreshadowed. Note this is a training-set evaluation; on a true holdout you would expect somewhat worse numbers because of the modest amount of overfitting that even a default tree carries. For an honest performance estimate, hold out 20-30 percent of rows before fitting.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Decision-Tree-Exercises-in-R-ex-4-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.4: Compute holdout RMSE for the mtcars regression tree</h3>
<p class="exercise-task"><strong>Task:</strong> A fleet operations analyst wants an honest error estimate for the mtcars mpg tree. Set the seed to 1, sample 22 rows for training and use the remaining 10 as holdout, fit the regression tree on training, predict on holdout, and compute the root <a class="auto-link" href="Point-Estimation-in-R.html" title="Point Estimation in R: What Makes an Estimator Good? Bias, Variance, and MSE">mean squared error</a>. Save the numeric RMSE to <code>ex_4_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 2.506931
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Fit the tree on the training rows only, score the untouched holdout rows, then <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summarise</a> the gap between predictions and truth as one error number.</p><p>After <code>rpart(mpg ~ ., data = train)</code> and <code>predict()</code> on <code>holdout</code>, combine the residuals with <code>sqrt(mean(...^2))</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(1)
train_idx &lt;- sample(seq_len(nrow(mtcars)), size = 22)
train     &lt;- mtcars[train_idx, ]
holdout   &lt;- mtcars[-train_idx, ]

ex_4_4 &lt;- # your code here
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(1)
train_idx &lt;- sample(seq_len(nrow(mtcars)), size = 22)
train     &lt;- mtcars[train_idx, ]
holdout   &lt;- mtcars[-train_idx, ]

fit_train &lt;- rpart(mpg ~ ., data = train)
preds     &lt;- predict(fit_train, holdout)

ex_4_4 &lt;- sqrt(mean((preds - holdout$mpg)^2))
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> RMSE is in the same units as the response (mpg here), so a 3.18 mpg average deviation is interpretable directly: the tree is roughly within 3 mpg of the truth on cars it has not seen. Compare this to the standard deviation of <code>mpg</code> in the holdout to gauge whether the model beats a "predict the mean" baseline. With only 32 rows total, a single split like this is noisy: in production you would prefer <a class="auto-link" href="rsample-vfold_cv-in-R.html" title="rsample vfold_cv() in R: V-Fold Cross-Validation Splits">k-fold cross-validation</a> or a bootstrap to stabilise the estimate.</p>
</details>
</section>
<h2>Section 5. Prune the tree and choose complexity (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Decision-Tree-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Inspect the cp table for a deeply grown mtcars tree</h3>
<p class="exercise-task"><strong>Task:</strong> Grow an mtcars regression tree at low complexity using <code>rpart(mpg ~ ., data = mtcars, cp = 0.001)</code>, then call <code>printcp()</code> to display the full complexity-parameter table. Save the captured cp matrix to <code>ex_5_1</code> (it lives in <code>fit$cptable</code>) so you can inspect xerror against tree size.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Regression tree:
rpart(formula = mpg ~ ., data = mtcars, cp = 0.001)

Variables actually used in tree construction:
[1] cyl hp 

Root node error: 1126/32 = 35.189

n= 32 

        CP nsplit rel error  xerror    xstd
1 0.643125      0   1.00000 1.06748 0.25078
2 0.097484      1   0.35687 0.59620 0.17133
3 0.001000      2   0.25939 0.55371 0.14024
          CP nsplit rel error    xerror      xstd
1 0.64312523      0 1.0000000 1.0674814 0.2507840
2 0.09748407      1 0.3568748 0.5961968 0.1713295
3 0.00100000      2 0.2593907 0.5537056 0.1402437
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The complexity-parameter table is already stored inside the fitted tree object; you only need to read it out.</p><p>Assign the <code>cptable</code> element of <code>deep_mt</code>, reached with the <code>$</code> accessor.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">deep_mt &lt;- rpart(mpg ~ ., data = mtcars, cp = 0.001)
printcp(deep_mt)

ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">deep_mt &lt;- rpart(mpg ~ ., data = mtcars, cp = 0.001)
printcp(deep_mt)

ex_5_1 &lt;- deep_mt$cptable
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The cp table summarises every candidate subtree from a one-node stump up to the fully grown tree. <code>rel error</code> is training error relative to the root; <code>xerror</code> is the cross-validated equivalent (rpart runs 10-fold CV internally during fitting). <code>xstd</code> is the standard error of the cross-validated estimate. Pick <code>cp</code> by reading down the table for the row with smallest <code>xerror</code> (the next exercise) or the most parsimonious row within one <code>xstd</code> of that minimum (the exercise after).</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Decision-Tree-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Prune the mtcars tree to the cp with minimum xerror</h3>
<p class="exercise-task"><strong>Task:</strong> A production team wants the most accurate pruned tree. Take the deep tree from Exercise 5.1, find the row with the smallest cross-validation error in <code>fit$cptable</code>, extract that row's <code>CP</code> value, and pass it to <code>prune()</code>. Save the pruned tree to <code>ex_5_2</code> and print it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>n= 32 

node), split, n, deviance, yval
      * denotes terminal node

1) root 32 1126.04700 20.09062  
  2) cyl&gt;=5 21  198.47240 16.64762  
    4) hp&gt;=192.5 7   28.82857 13.41429 *
    5) hp&lt; 192.5 14   59.87214 18.26429 *
  3) cyl&lt; 5 11  203.38550 26.66364 *
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Find the table row with the lowest cross-validation error, take its complexity value, and cut the tree back to that size.</p><p>Use <code>which.min()</code> on the <code>"xerror"</code> column to index the <code>"CP"</code> value, then feed it to <code>prune()</code> as <code>cp</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">deep_mt &lt;- rpart(mpg ~ ., data = mtcars, cp = 0.001)

best_cp &lt;- # your code here
ex_5_2  &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">deep_mt &lt;- rpart(mpg ~ ., data = mtcars, cp = 0.001)

best_cp &lt;- deep_mt$cptable[which.min(deep_mt$cptable[, "xerror"]), "CP"]
ex_5_2  &lt;- prune(deep_mt, cp = best_cp)
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>which.min()</code> on the <code>xerror</code> column finds the cp index that minimises cross-validated error; passing that <code>CP</code> value into <code>prune()</code> returns the corresponding subtree. Because <code>xerror</code> is an estimate, the minimum can shift between runs unless you fix the seed before calling <code>rpart()</code> (rpart uses its own internal CV folds). The resulting tree is your best automatic pick for predictive accuracy, before any judgment calls about parsimony.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Decision-Tree-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Apply the 1-SE rule for a more parsimonious pruned tree</h3>
<p class="exercise-task"><strong>Task:</strong> The same team also wants a fallback tree that is as small as possible while still within one standard error of the best xerror. Implement the 1-SE rule: find <code>min(xerror) + xstd</code> at the minimum row, then pick the smallest tree (largest <code>CP</code>) whose <code>xerror</code> is below that threshold. Prune to that cp and save to <code>ex_5_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; n= 32
#&gt;
#&gt; node), split, n, deviance, yval
#&gt;       * denotes terminal node
#&gt;
#&gt; 1) root 32 1126.0470 20.09062
#&gt;   2) cyl&gt;=5 21  198.4724 16.64762 *
#&gt;   3) cyl&lt; 5 11  203.3855 26.66364 *</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Among the rows whose error sits under the threshold, the first one is the smallest tree that still qualifies; prune to its complexity value.</p><p>Use <code>which(cpt[, "xerror"] &lt;= threshold)[1]</code> to grab the <code>"CP"</code>, then call <code>prune()</code> on <code>deep_mt</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">deep_mt &lt;- rpart(mpg ~ ., data = mtcars, cp = 0.001)
cpt     &lt;- deep_mt$cptable

best_row    &lt;- which.min(cpt[, "xerror"])
threshold   &lt;- cpt[best_row, "xerror"] + cpt[best_row, "xstd"]
parsim_cp   &lt;- # your code here

ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">deep_mt &lt;- rpart(mpg ~ ., data = mtcars, cp = 0.001)
cpt     &lt;- deep_mt$cptable

best_row  &lt;- which.min(cpt[, "xerror"])
threshold &lt;- cpt[best_row, "xerror"] + cpt[best_row, "xstd"]
parsim_cp &lt;- cpt[which(cpt[, "xerror"] &lt;= threshold)[1], "CP"]

ex_5_3 &lt;- prune(deep_mt, cp = parsim_cp)
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The 1-SE rule (Breiman et al.) says: among all subtrees whose cross-validated error is statistically indistinguishable from the best one (within one xstd), pick the smallest. This guards against overfitting when the cv estimate is noisy. <code>which(cpt[, "xerror"] &lt;= threshold)[1]</code> returns the first qualifying row, which because the cp table is ordered by descending CP corresponds to the most parsimonious qualifier. The result is a more robust default for production scoring than the unconditional minimum-xerror tree.</p>
</details>
</section>
<h2>What to do next</h2>
<ul>
<li><strong><a href="Random-Forest-Exercises-in-R.html">Random Forest Exercises in R</a></strong> to practice ensembling many trees and averaging their predictions for better accuracy.</li>
<li><strong><a href="XGBoost-Exercises-in-R.html">XGBoost Exercises in R</a></strong> for gradient-boosted trees, the production-grade upgrade path.</li>
<li><strong><a href="caret-Exercises-in-R.html">caret Exercises in R</a></strong> to learn how to wrap rpart in resampling, tuning grids, and standardised performance summaries.</li>
<li><strong><a href="Practice-Exercises-in-R.html">Practice Hub</a></strong> for the full library of <a class="auto-link" href="R-Basics-Exercises.html" title="R Basics Exercises: 15 Practice Problems for Beginners (With Solutions)">R practice problems</a> across data wrangling, modelling, and visualization.</li>
</ul>

{% endraw %}