---
title: "dplyr Joins Exercises in R: 25 Practice Problems"
description: "Joins in R exercises: 25 dplyr practice problems on left, right, inner, full, semi, anti, nest, multi-key, inequality and rolling joins. Hidden solutions."
keywords: "joins in R exercises, dplyr joins practice, left_join exercises, inner_join exercises R, join_by exercises, rolling join R"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "dplyr joins exercises|joins in R exercises|left_join exercises|inner_join practice|join_by exercises|rolling join exercises"
auto_link_case_sensitive: false
sidebar_title: "dplyr Joins Exercises"
sidebar_order: "121"
fr_parent: "dplyr-joins-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>dplyr Joins Exercises in R: 25 Practice Problems</h1>
<p class="lead">Twenty-five practice problems on <a class="auto-link" href="R-Joins.html" title="R Joins With Visual Diagrams: Pick the Right Join Every Time">dplyr joins</a> covering mutating joins (left, right, inner, full, nest), filtering joins (semi, anti), multi-key joins, the modern <code>join_by()</code> helper, <a class="auto-link" href="R-Comparison-Operators-in-R.html" title="R Comparison Operators: ==, !=, &lt;, &gt;, &lt;=, &gt;= Guide">inequality</a> joins, rolling joins, NA handling, self-joins, and full end-to-end reconciliation workflows. Solutions are hidden behind a click so you can attempt each problem first.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="25" data-time="60" data-xp="375"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(dplyr)
library(tibble)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<div class="webr-container" data-block-title="Setup tables shared across the exercises">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup tables shared across the exercises</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">customers &lt;- tibble(
  customer_id = c(1L, 2L, 3L, 4L, 5L, 6L),
  name        = c("Alice","Bob","Carol","Dan","Eve","Frank"),
  segment     = c("Pro","Free","Pro","Free","Pro","Free"),
  signup      = as.Date(c("2024-01-15","2024-02-08","2024-03-22",
                          "2024-05-01","2024-06-18","2024-09-04"))
)

orders &lt;- tibble(
  order_id    = 101:110,
  customer_id = c(1L, 2L, 1L, 3L, 7L, 5L, 1L, 4L, 5L, 9L),
  order_date  = as.Date(c("2024-04-02","2024-04-15","2024-05-10",
                          "2024-05-22","2024-06-01","2024-07-04",
                          "2024-08-12","2024-09-09","2024-10-21",
                          "2024-11-30")),
  amount      = c(50, 80, 30, 65, 120, 200, 45, 75, 90, 150)
)

products &lt;- tibble(
  product_id = 1:4,
  product    = c("Widget","Gadget","Sprocket","Gizmo"),
  category   = c("Tools","Tools","Parts","Tools")
)

returns &lt;- tibble(
  order_id = c(101L, 105L, 110L),
  reason   = c("damaged","wrong size","late delivery"),
  refund   = c(50, 120, 150)
)

price_tiers &lt;- tibble(
  min_amount = c(0, 50, 100, 200),
  max_amount = c(50, 100, 200, Inf),
  tier       = c("micro","small","mid","large")
)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p>Note: <code>orders</code> deliberately contains two orphan rows (customer_id 7 and 9 do not exist in <code>customers</code>). Several exercises rely on those gaps to demonstrate how joins handle unmatched keys.</p>
<h2>Section 1. Mutating joins (5 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Augment every customer with their order history using left_join</h3>
<p class="exercise-task"><strong>Task:</strong> A customer success manager wants a single roster showing every customer plus their order history, including customers who never placed an order. Use <code>left_join()</code> to attach <code>orders</code> to <code>customers</code> on the matching <code>customer_id</code>, keeping every customer row even when no orders exist. Save the result to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 11 x 7
#&gt;    customer_id name  segment signup     order_id order_date amount
#&gt;          &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;        &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;
#&gt;  1           1 Alice Pro     2024-01-15      101 2024-04-02     50
#&gt;  2           1 Alice Pro     2024-01-15      103 2024-05-10     30
#&gt;  3           1 Alice Pro     2024-01-15      107 2024-08-12     45
#&gt;  4           2 Bob   Free    2024-02-08      102 2024-04-15     80
#&gt;  5           3 Carol Pro     2024-03-22      104 2024-05-22     65
#&gt;  6           4 Dan   Free    2024-05-01      108 2024-09-09     75
#&gt;  7           5 Eve   Pro     2024-06-18      106 2024-07-04    200
#&gt;  8           5 Eve   Pro     2024-06-18      109 2024-10-21     90
#&gt;  9           6 Frank Free    2024-09-04       NA NA             NA
#&gt; # 2 more rows where customer 1 also matches (order 101, 103, 107)</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Decide which table must keep every one of its rows even when the other side has no match, and put that table first.</p><p>Use a mutating join that preserves all left-side rows, joining on <code>customer_id</code> via the <code>by</code> argument.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- customers |&gt;
  left_join(orders, by = "customer_id")
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>left_join()</code> keeps every row of the LEFT table and pulls matching columns from the RIGHT. When the right side has no match (Frank, customer 6, never ordered), the new columns become <code>NA</code>. Use this whenever the left table is the entity you must preserve completely. <code>inner_join()</code> would silently drop Frank, which is the most common bug in customer reports.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Combine orders and products with inner_join</h3>
<p class="exercise-task"><strong>Task:</strong> Use <code>inner_join()</code> to combine <code>orders</code> and <code>products</code> so every row carries both the order details and the product details. Add a <code>product_id</code> column to <code>orders</code> first using <code>c(1, 2, 1, 3, 4, 1, 2, 3, 4, 1)</code>, then inner-join on <code>product_id</code>. Save the result to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 10 x 7
#&gt;    order_id customer_id order_date amount product_id product  category
#&gt;       &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;
#&gt;  1      101           1 2024-04-02     50          1 Widget   Tools
#&gt;  2      102           2 2024-04-15     80          2 Gadget   Tools
#&gt;  3      103           1 2024-05-10     30          1 Widget   Tools
#&gt;  4      104           3 2024-05-22     65          3 Sprocket Parts
#&gt;  5      105           7 2024-06-01    120          4 Gizmo    Tools
#&gt;  6      106           5 2024-07-04    200          1 Widget   Tools
#&gt; # 4 more rows</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>You first need a shared key column on the orders side, then a join that keeps only rows present in both tables.</p><p>Add <code>product_id</code> with <code>mutate()</code>, then <code>inner_join()</code> the products table on <code>product_id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- orders |&gt;
  mutate(product_id = c(1, 2, 1, 3, 4, 1, 2, 3, 4, 1)) |&gt;
  inner_join(products, by = "product_id")
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>inner_join()</code> keeps only rows that exist in BOTH tables. Because every assigned <code>product_id</code> (1-4) exists in <code>products</code>, no rows are dropped here. If you had typed <code>99</code> for any order, that row would vanish silently. Use <code>inner_join()</code> when the join key represents a foreign-key constraint you trust; switch to <code>left_join()</code> when you must preserve every fact-table row regardless of dimension coverage.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-1-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 1.3: Reconcile the universe of customer ids with full_join</h3>
<p class="exercise-task"><strong>Task:</strong> An auditor reconciling two ledgers wants to see every <code>customer_id</code> that appears in EITHER <code>customers</code> or <code>orders</code>, including the orphan ids 7 and 9 in <code>orders</code> that never registered as customers. Use <code>full_join()</code> to combine both tables and save the unioned result to <code>ex_1_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 12 x 7
#&gt;    customer_id name  segment signup     order_id order_date amount
#&gt;          &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;        &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;
#&gt;  1           1 Alice Pro     2024-01-15      101 2024-04-02     50
#&gt;  ...
#&gt; 10           6 Frank Free    2024-09-04       NA NA             NA
#&gt; 11           7 NA    NA      NA              105 2024-06-01    120
#&gt; 12           9 NA    NA      NA              110 2024-11-30    150</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You want every key that appears in either table, so neither side should be allowed to drop rows.</p><p>Use <code>full_join()</code> on <code>customer_id</code> to get the union of both keysets.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- customers |&gt;
  full_join(orders, by = "customer_id")
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>full_join()</code> returns the union of both keysets; anything missing on a side becomes <code>NA</code>. This is the right tool for reconciliation: rows where the LEFT columns are <code>NA</code> flag orphan orders (data integrity bugs); rows where the RIGHT columns are <code>NA</code> flag dormant customers. An inner_join would mask both signals and a left_join would only catch one of the two.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-1-4" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 1.4: Preserve the orders table with right_join</h3>
<p class="exercise-task"><strong>Task:</strong> A reporting analyst wants every order enriched with customer metadata, but rows for orphan <code>customer_id</code> values 7 and 9 must still appear with <code>NA</code> name. Use <code>right_join()</code> from <code>customers</code> to <code>orders</code> so that the right-hand <code>orders</code> table is the one preserved in full. Save to <code>ex_1_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 10 x 7
#&gt;    customer_id name  segment signup     order_id order_date amount
#&gt;          &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;        &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;
#&gt;  1           1 Alice Pro     2024-01-15      101 2024-04-02     50
#&gt;  ...
#&gt;  9           7 NA    NA      NA              105 2024-06-01    120
#&gt; 10           9 NA    NA      NA              110 2024-11-30    150</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>This time the orders table is the one that must survive in full, even though it sits on the right.</p><p>Call <code>right_join()</code> from <code>customers</code> to <code>orders</code> on <code>customer_id</code> so every order row is kept.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- customers |&gt;
  right_join(orders, by = "customer_id")
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>right_join(x, y)</code> preserves every row of <code>y</code>. It is the mirror of <code>left_join()</code>. In real pipelines most people prefer the left form because it reads naturally with the <a class="auto-link" href="R-Pipe-Operator.html" title="The Pipe Operator in R: %&gt;% vs |&gt; — Master the Most Important Concept">pipe operator</a>: <code>orders |&gt; left_join(customers, ...)</code> is the same result with the order of arguments flipped. Pick whichever orientation puts your fact table on the left.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-1-5" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.5: Nest each customer's orders into a list-column with nest_join</h3>
<p class="exercise-task"><strong>Task:</strong> A junior analyst wants every customer row to carry a nested tibble of that customer's orders, instead of duplicating the customer columns across multiple rows. Use <code>nest_join()</code> to attach a list-column called <code>orders</code> (one tibble per customer) to <code>customers</code>. Save the nested table to <code>ex_1_5</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 6 x 5
#&gt;   customer_id name  segment signup     orders
#&gt;         &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;     &lt;list&gt;
#&gt; 1           1 Alice Pro     2024-01-15 &lt;tibble [3 x 3]&gt;
#&gt; 2           2 Bob   Free    2024-02-08 &lt;tibble [1 x 3]&gt;
#&gt; 3           3 Carol Pro     2024-03-22 &lt;tibble [1 x 3]&gt;
#&gt; 4           4 Dan   Free    2024-05-01 &lt;tibble [1 x 3]&gt;
#&gt; 5           5 Eve   Pro     2024-06-18 &lt;tibble [2 x 3]&gt;
#&gt; 6           6 Frank Free    2024-09-04 &lt;tibble [0 x 3]&gt;</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You want one row per customer carrying a bundled sub-table of their orders, not duplicated customer rows.</p><p>Use <code>nest_join()</code> on <code>customer_id</code> to produce the <code>orders</code> list-column.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_5 &lt;- # your code here
ex_1_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_5 &lt;- customers |&gt;
  nest_join(orders, by = "customer_id")
ex_1_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>nest_join()</code> keeps every left-side row exactly once and adds a list-column where each entry is a tibble of matching rows from the right table. This shape is ideal for one-row-per-entity reports or for downstream <code>purrr::map()</code> work where you fit a model per customer. Frank gets an empty 0-row tibble rather than <code>NA</code>, so subsequent map calls return clean empty results instead of erroring.</p>
</details>
</section>
<h2>Section 2. Filtering joins (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Find customers who placed at least one order using semi_join</h3>
<p class="exercise-task"><strong>Task:</strong> The marketing team is preparing a thank-you email blast and wants the list of customers who have placed AT LEAST one order. Use <code>semi_join()</code> to filter <code>customers</code> down to those whose <code>customer_id</code> appears in <code>orders</code>, without bringing in any of the order columns. Save the resulting roster to <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 4
#&gt;   customer_id name  segment signup
#&gt;         &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;
#&gt; 1           1 Alice Pro     2024-01-15
#&gt; 2           2 Bob   Free    2024-02-08
#&gt; 3           3 Carol Pro     2024-03-22
#&gt; 4           4 Dan   Free    2024-05-01
#&gt; 5           5 Eve   Pro     2024-06-18</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You want to filter customers down to those with a match, without pulling in any order columns.</p><p>Use <code>semi_join()</code> of <code>customers</code> against <code>orders</code> on <code>customer_id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- customers |&gt;
  semi_join(orders, by = "customer_id")
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>semi_join()</code> is a <a class="auto-link" href="dplyr-semi_join-in-R.html" title="dplyr semi_join() in R: Filter to Rows With Match in Right">filtering join</a>: it keeps only rows of the left table that match in the right and never adds new columns. It is the dplyr equivalent of <code>customers |&gt; filter(customer_id %in% orders$customer_id)</code> but is faster on large tables and reads better with multi-column keys. Frank, who never ordered, is correctly excluded.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Detect orphan orders with anti_join</h3>
<p class="exercise-task"><strong>Task:</strong> The data team is hunting orphan records where an order references a <code>customer_id</code> that does not exist in <code>customers</code>. Use <code>anti_join()</code> to return only the orders whose <code>customer_id</code> is NOT in the customers table. Save the offending rows to <code>ex_2_2</code> so the team can file a data-quality ticket.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 4
#&gt;   order_id customer_id order_date amount
#&gt;      &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;
#&gt; 1      105           7 2024-06-01    120
#&gt; 2      110           9 2024-11-30    150</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You want to keep only the <a class="auto-link" href="dplyr-arrange-in-R.html" title="dplyr arrange() in R: Sort Rows by Column">order rows</a> that have no matching customer at all.</p><p>Use <code>anti_join()</code> of <code>orders</code> against <code>customers</code> on <code>customer_id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- orders |&gt;
  anti_join(customers, by = "customer_id")
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>anti_join()</code> is the inverse of <code>semi_join()</code>: it keeps only rows with NO match. This is the canonical pattern for data-quality reports. These two orders point to <code>customer_id</code> values that were never created, which signals either a deletion bug, a data-load race, or stale FK references. The fix is to investigate; using <code>inner_join()</code> to silently drop them would only hide the problem.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Flag dormant customers with anti_join after a date filter</h3>
<p class="exercise-task"><strong>Task:</strong> A churn analyst wants to flag customers who have NOT placed any order in the last 90 days as of <code>2024-12-01</code>. First filter <code>orders</code> to those after <code>2024-09-02</code>, then use <code>anti_join()</code> against the recent set so that only dormant customers remain. Save the dormant roster to <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 4
#&gt;   customer_id name  segment signup
#&gt;         &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;
#&gt; 1           1 Alice Pro     2024-01-15
#&gt; 2           2 Bob   Free    2024-02-08
#&gt; 3           3 Carol Pro     2024-03-22
#&gt; 4           6 Frank Free    2024-09-04</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>First define what "recent" means as a separate set, then keep customers who are absent from it.</p><p>Use <code>filter(order_date &gt;= as.Date("2024-09-02"))</code> to build the recent set, then <code>anti_join()</code> on <code>customer_id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">recent_orders &lt;- orders |&gt;
  filter(order_date &gt;= as.Date("2024-09-02"))

ex_2_3 &lt;- customers |&gt;
  anti_join(recent_orders, by = "customer_id")
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Combine <code>filter()</code> with <code>anti_join()</code> to express "in A, not in B-after-filter". This is the canonical churn-flag pattern: define what "active" means in B, then anti-join to get the inactive set. Note that <code>semi_join()</code> would give the OPPOSITE result, the active customers. Always state the question to yourself in plain language before choosing semi vs anti, since the two are easy to swap by accident.</p>
</details>
</section>
<h2>Section 3. Multi-key joins and renamed columns (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Join two tables whose key columns have different names</h3>
<p class="exercise-task"><strong>Task:</strong> Joining tables whose key columns have different names is the most common dplyr-joins gotcha. Rename <code>customers$customer_id</code> to <code>id</code>, then use <code>inner_join()</code> with <code>by = c("customer_id" = "id")</code> to merge <code>orders</code> with the renamed customers table. The result should keep the left side's column name. Save to <code>ex_3_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 8 x 7
#&gt;   order_id customer_id order_date amount name  segment signup
#&gt;      &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;
#&gt; 1      101           1 2024-04-02     50 Alice Pro     2024-01-15
#&gt; 2      102           2 2024-04-15     80 Bob   Free    2024-02-08
#&gt; 3      103           1 2024-05-10     30 Alice Pro     2024-01-15
#&gt; 4      104           3 2024-05-22     65 Carol Pro     2024-03-22
#&gt; # 4 more rows; orphan orders 105 and 110 are dropped</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>When the key columns are named differently on each side, the join needs to be told which name maps to which.</p><p>Use <code>rename(id = customer_id)</code> on customers, then <code>inner_join()</code> with <code>by = c("customer_id" = "id")</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">customers_renamed &lt;- customers |&gt;
  rename(id = customer_id)

ex_3_1 &lt;- orders |&gt;
  inner_join(customers_renamed, by = c("customer_id" = "id"))
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The named vector <code>c("customer_id" = "id")</code> reads as "left side's <code>customer_id</code> matches right side's <code>id</code>". The result keeps the LEFT side's column name. The modern <code>join_by(customer_id == id)</code> does the same thing more readably. Either form avoids the noisy alternative of renaming one side first just so the names line up.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Join on a composite key of two columns</h3>
<p class="exercise-task"><strong>Task:</strong> Build two inline tibbles <code>sales</code> and <code>targets</code> keyed jointly on <code>(region, quarter)</code>, then <code>left_join()</code> them on BOTH columns at once by passing <code>by = c("region", "quarter")</code>. Compute a <code>gap</code> column as <code>actual - target</code> so the result reads as a variance report. Save to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 6 x 5
#&gt;   region quarter actual target   gap
#&gt;   &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 West   Q1         120    100    20
#&gt; 2 West   Q2         140    150   -10
#&gt; 3 East   Q1         200    180    20
#&gt; 4 East   Q2         210    220   -10
#&gt; 5 South  Q1          90    100   -10
#&gt; 6 South  Q2         110    100    10</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A row is only the same record when both key columns agree, so the match must use the pair together.</p><p>Pass <code>by = c("region", "quarter")</code> to <code>left_join()</code>, then add <code>mutate(gap = actual - target)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">sales &lt;- tibble(
  region  = c("West","West","East","East","South","South"),
  quarter = c("Q1","Q2","Q1","Q2","Q1","Q2"),
  actual  = c(120, 140, 200, 210,  90, 110)
)
targets &lt;- tibble(
  region  = c("West","West","East","East","South","South"),
  quarter = c("Q1","Q2","Q1","Q2","Q1","Q2"),
  target  = c(100, 150, 180, 220, 100, 100)
)

ex_3_2 &lt;- sales |&gt;
  left_join(targets, by = c("region","quarter")) |&gt;
  mutate(gap = actual - target)
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Passing a character vector to <code>by</code> joins on every column listed, in the order given. If you forget one and join only on <code>region</code>, you get a many-to-many explosion (each region matches all four quarters). dplyr 1.1+ now warns about unintended many-to-many joins; previously this was a silent foot-gun that produced quietly inflated revenue numbers in dashboards.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Use the modern join_by helper for the same composite key</h3>
<p class="exercise-task"><strong>Task:</strong> A reporting analyst prefers the modern <code>join_by()</code> syntax over the older string-vector <code>by</code>. Re-do the sales-versus-targets join from Exercise 3.2, but this time pass <code>by = join_by(region, quarter)</code> to <code>inner_join()</code>. Add the same <code>gap</code> column and save to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 6 x 5
#&gt;   region quarter actual target   gap
#&gt;   &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 West   Q1         120    100    20
#&gt; 2 West   Q2         140    150   -10
#&gt; 3 East   Q1         200    180    20
#&gt; 4 East   Q2         210    220   -10
#&gt; 5 South  Q1          90    100   -10
#&gt; 6 South  Q2         110    100    10</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>This is the same composite-key match as before, just expressed with the modern unquoted key syntax.</p><p>Pass <code>by = join_by(region, quarter)</code> to <code>inner_join()</code>, then add the same <code>mutate(gap = actual - target)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- sales |&gt;
  inner_join(targets, by = join_by(region, quarter)) |&gt;
  mutate(gap = actual - target)
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>join_by()</code> (added in dplyr 1.1.0) is the recommended modern form for join keys. It accepts bare column names without quotes, supports inequalities like <code>&gt;=</code>, and exposes helpers such as <code>between()</code> and <code>closest()</code>. For plain equality joins it is a stylistic choice; for non-equi or rolling joins it is the only option. Adopting it everywhere keeps the codebase consistent.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-3-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.4: Combine an equality with closest() for an SCD-Type-2 lookup</h3>
<p class="exercise-task"><strong>Task:</strong> A trading desk wants every order joined to the SAME customer's segment AS OF the order date, not the current segment. Build inline <code>segment_history</code> (each customer can have multiple historical segment changes with <code>effective_date</code>), then use <code>inner_join()</code> with <code>join_by(customer_id, closest(order_date &gt;= effective_date))</code> so each order picks its segment as of the order date. Save to <code>ex_3_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 8 x 6
#&gt;   order_id customer_id order_date amount effective_date segment_at
#&gt;      &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt; &lt;date&gt;         &lt;chr&gt;
#&gt; 1      101           1 2024-04-02     50 2024-01-15     Free
#&gt; 2      102           2 2024-04-15     80 2024-02-08     Free
#&gt; 3      103           1 2024-05-10     30 2024-01-15     Free
#&gt; 4      104           3 2024-05-22     65 2024-03-22     Pro
#&gt; 5      106           5 2024-07-04    200 2024-06-18     Free
#&gt; 6      107           1 2024-08-12     45 2024-06-01     Pro
#&gt; 7      108           4 2024-09-09     75 2024-05-01     Free
#&gt; 8      109           5 2024-10-21     90 2024-08-01     Pro</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Each order needs the same customer plus the single history version that was effective at its date.</p><p>Combine an equality with a closest-match inequality: <code>join_by(customer_id, closest(order_date &gt;= effective_date))</code> inside <code>inner_join()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
ex_3_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">segment_history &lt;- tibble(
  customer_id    = c(1L, 1L, 2L, 3L, 4L, 5L, 5L),
  effective_date = as.Date(c("2024-01-15","2024-06-01","2024-02-08",
                             "2024-03-22","2024-05-01","2024-06-18","2024-08-01")),
  segment_at     = c("Free","Pro","Free","Pro","Free","Free","Pro")
)

ex_3_4 &lt;- orders |&gt;
  inner_join(segment_history,
             by = join_by(customer_id, closest(order_date &gt;= effective_date)))
ex_3_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Combining an equality (<code>customer_id</code>) with <code>closest()</code> is the canonical SCD-Type-2 lookup: for each fact row, find the dimension version that was effective at the fact's timestamp. Without <code>join_by()</code> you would have to inner_join on the equality, then <code>group_by()</code> and <code>slice_max()</code>, which is several times slower and harder to verify. Orphan customer ids 7 and 9 drop out because there is no history row for them.</p>
</details>
</section>
<h2>Section 4. Many-to-many and join helpers (4 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Acknowledge a many-to-many fan-out with relationship</h3>
<p class="exercise-task"><strong>Task:</strong> A platform engineer wants a deliberate <a class="auto-link" href="dplyr-cross_join-in-R.html" title="dplyr cross_join() in R: Cartesian Product of Two Tables">cartesian product</a> of orders and promo codes per customer. Build an inline <code>promos</code> tibble where customer 1 has two promo codes and customer 5 has two as well, then <code>inner_join()</code> <code>orders</code> to <code>promos</code> with <code>relationship = "many-to-many"</code> to silence the warning. Save the fanned-out table to <code>ex_4_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 11 x 6
#&gt;   order_id customer_id order_date amount promo_code pct_off
#&gt;      &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;
#&gt; 1      101           1 2024-04-02     50 WELCOME         10
#&gt; 2      101           1 2024-04-02     50 SUMMER          15
#&gt; 3      103           1 2024-05-10     30 WELCOME         10
#&gt; 4      103           1 2024-05-10     30 SUMMER          15
#&gt; # 7 more rows for customers 2 and 5</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>When both sides have duplicate keys the row count fans out, and dplyr expects you to declare that this is intentional.</p><p>Pass <code>relationship = "many-to-many"</code> to <code>inner_join()</code> on <code>customer_id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">promos &lt;- tibble(
  customer_id = c(1L, 1L, 2L, 5L, 5L),
  promo_code  = c("WELCOME","SUMMER","WELCOME","SUMMER","FALL"),
  pct_off     = c(10, 15, 10, 15, 20)
)

ex_4_1 &lt;- orders |&gt;
  inner_join(promos, by = "customer_id", relationship = "many-to-many")
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> When BOTH sides have duplicate keys, dplyr 1.1+ warns because the row count balloons unexpectedly. Setting <code>relationship = "many-to-many"</code> is your written acknowledgement that this fan-out is intentional. The cleaner alternative is to first aggregate one side to one-row-per-key, but for a true cartesian product within each key (every order paired with every promo), this is correct.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Disambiguate duplicate column names with the suffix argument</h3>
<p class="exercise-task"><strong>Task:</strong> When two tables share a non-key column name, dplyr appends <code>.x</code> and <code>.y</code> by default. Build two tibbles <code>feb_prices</code> and <code>mar_prices</code> each with columns <code>product_id</code> and <code>price</code>, then <code>inner_join()</code> them passing <code>suffix = c("_feb","_mar")</code> so the result has clearly named <code>price_feb</code> and <code>price_mar</code> columns. Save to <code>ex_4_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 3
#&gt;   product_id price_feb price_mar
#&gt;        &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1          1        10        11
#&gt; 2          2        20        19
#&gt; 3          3        30        35
#&gt; 4          4        40        38</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Both tables share a non-key column name, so you need to control how the duplicates are labelled in the result.</p><p>Pass <code>suffix = c("_feb", "_mar")</code> to <code>inner_join()</code> on <code>product_id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">feb_prices &lt;- tibble(product_id = 1:4, price = c(10, 20, 30, 40))
mar_prices &lt;- tibble(product_id = 1:4, price = c(11, 19, 35, 38))

ex_4_2 &lt;- feb_prices |&gt;
  inner_join(mar_prices, by = "product_id", suffix = c("_feb","_mar"))
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The default <code>.x</code> and <code>.y</code> suffixes become useless once a column is shadowed twice in a chain (you end up with <code>price.x.x</code>). Always pass an explicit <code>suffix</code> when joining time-series snapshots, A/B variants, or before-and-after panels. A cleaner alternative is to rename one side BEFORE the join (<code>rename(price_feb = price)</code>) so the columns survive without machine suffixes.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Force a hard failure on orphans with unmatched = "error"</h3>
<p class="exercise-task"><strong>Task:</strong> An ETL engineer wants every order to have a matching customer or the pipeline must FAIL LOUDLY rather than silently dropping rows. Use <code>inner_join()</code> with <code>unmatched = "error"</code> to force a hard error, wrap it in <code>tryCatch()</code> to capture the message, and save the captured error string (or the success string) to <code>ex_4_3</code> so the pipeline can log it.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] "could not find function \"inner_join\""
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>An unmatched row should make the pipeline fail loudly rather than silently disappear, and the failure must be captured.</p><p>Pass <code>unmatched = "error"</code> to <code>inner_join()</code> and wrap the call in <code>tryCatch()</code> with an <code>error</code> handler returning <code>conditionMessage(e)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- tryCatch(
  {
    orders |&gt;
      inner_join(customers, by = "customer_id", unmatched = "error")
    "OK: every order matched a customer"
  },
  error = function(e) conditionMessage(e)
)
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>unmatched = "error"</code> turns silent row-loss into a loud failure, which is the right behavior for ETL where data integrity matters more than a partial result. The default <code>"drop"</code> quietly removes orphans, which is dangerous in production. Pair it with <code>tryCatch()</code> so a failed batch gets logged rather than crashing the whole job. The exact error wording can vary by dplyr version.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-4-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.4: Stop NA-to-NA matches with na_matches = "never"</h3>
<p class="exercise-task"><strong>Task:</strong> When a join key has <code>NA</code> values, dplyr's default is to match <code>NA</code>-against-<code>NA</code>, which is rarely what you want. Build two tibbles <code>obs</code> (with values <code>1, 2, NA, 3</code>) and <code>lookup</code> (with values <code>1, NA, 3</code>) on a key column called <code>id</code>, then <code>left_join()</code> them with <code>na_matches = "never"</code> so the <code>NA</code> rows do NOT join. Save to <code>ex_4_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 3
#&gt;      id val_x val_y
#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
#&gt; 1     1 a     X
#&gt; 2     2 b     NA
#&gt; 3    NA c     NA
#&gt; 4     3 d     Z</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Two missing key values should not be treated as equal, so the join must be told to exclude them.</p><p>Pass <code>na_matches = "never"</code> to <code>left_join()</code> on <code>id</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_4 &lt;- # your code here
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">obs    &lt;- tibble(id = c(1, 2, NA, 3), val_x = c("a","b","c","d"))
lookup &lt;- tibble(id = c(1, NA, 3),    val_y = c("X","Y","Z"))

ex_4_4 &lt;- obs |&gt;
  left_join(lookup, by = "id", na_matches = "never")
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> By default <a class="auto-link" href="dplyr-matches-in-R.html" title="dplyr matches() in R: Select Columns by Regex">dplyr matches</a> <code>NA</code> against <code>NA</code> in join keys, which descends from R's three-valued comparison semantics. <code>na_matches = "never"</code> changes this so <code>NA</code>s are excluded, matching base R's <code>merge()</code> behavior. Using the default ('na') would have joined obs's <code>NA</code>-id row to lookup's <code>NA</code>-id row, almost always a bug rather than intent in production data.</p>
</details>
</section>
<h2>Section 5. Inequality and rolling joins (4 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Bucket each order into a price tier with an inequality join</h3>
<p class="exercise-task"><strong>Task:</strong> An accounting analyst wants to assign every order to the correct price tier from <code>price_tiers</code> (where each tier is a half-open range like <code>[0, 50)</code>). Use <code>inner_join()</code> with <code>by = join_by(amount &gt;= min_amount, amount &lt; max_amount)</code> to attach the matching tier label to each order. Save to <code>ex_5_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 10 x 6
#&gt;    order_id customer_id order_date amount min_amount tier
#&gt;       &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;
#&gt;  1      101           1 2024-04-02     50         50 small
#&gt;  2      102           2 2024-04-15     80         50 small
#&gt;  3      103           1 2024-05-10     30          0 micro
#&gt;  4      104           3 2024-05-22     65         50 small
#&gt;  5      105           7 2024-06-01    120        100 mid
#&gt;  6      106           5 2024-07-04    200        200 large
#&gt; # 4 more rows</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Each order should match the one tier whose half-open range contains its amount, which is a comparison rather than an equality.</p><p>Use <code>join_by(amount &gt;= min_amount, amount &lt; max_amount)</code> inside <code>inner_join()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- orders |&gt;
  inner_join(price_tiers,
             by = join_by(amount &gt;= min_amount, amount &lt; max_amount))
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Inequality joins (also called non-equi joins) match rows where columns satisfy a comparison rather than an exact equality. Each order picks up the single tier whose half-open range contains its <code>amount</code>. Without <code>join_by()</code> you would have to cross-join then filter, which is O(n*m) and wastes memory. dplyr 1.1+ rewrites this into an efficient interval scan internally.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Attach the most recent FX rate with a closest() rolling join</h3>
<p class="exercise-task"><strong>Task:</strong> A finance team wants to attach the most recent FX rate available on or before each transaction date. Build inline <code>transactions</code> (5 rows with <code>txn_date</code> and <code>amount_usd</code>) and <code>fx_rates</code> (4 rows with <code>rate_date</code> and <code>eur_per_usd</code>), then use <code>inner_join()</code> with <code>join_by(closest(txn_date &gt;= rate_date))</code> to pick exactly one rate per transaction. Save to <code>ex_5_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 5
#&gt;   txn_id txn_date   amount_usd rate_date  eur_per_usd
#&gt;    &lt;int&gt; &lt;date&gt;          &lt;dbl&gt; &lt;date&gt;           &lt;dbl&gt;
#&gt; 1      1 2024-03-04       1000 2024-03-01        0.92
#&gt; 2      2 2024-03-15       2500 2024-03-10        0.91
#&gt; 3      3 2024-04-01        800 2024-04-01        0.93
#&gt; 4      4 2024-04-09       1500 2024-04-01        0.93
#&gt; 5      5 2024-05-02        600 2024-05-01        0.94</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Each transaction needs exactly one rate: the most recent one dated on or before it.</p><p>Use <code>join_by(closest(txn_date &gt;= rate_date))</code> inside <code>inner_join()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">transactions &lt;- tibble(
  txn_id     = 1:5,
  txn_date   = as.Date(c("2024-03-04","2024-03-15","2024-04-01",
                         "2024-04-09","2024-05-02")),
  amount_usd = c(1000, 2500, 800, 1500, 600)
)
fx_rates &lt;- tibble(
  rate_date   = as.Date(c("2024-03-01","2024-03-10","2024-04-01","2024-05-01")),
  eur_per_usd = c(0.92, 0.91, 0.93, 0.94)
)

ex_5_2 &lt;- transactions |&gt;
  inner_join(fx_rates, by = join_by(closest(txn_date &gt;= rate_date)))
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>closest()</code> wraps an inequality and asks for the SINGLE best match per left-side row. <code>closest(txn_date &gt;= rate_date)</code> picks the latest rate that is still on-or-before the transaction date. This is the dplyr equivalent of a SQL correlated subquery with <code>LIMIT 1</code> or a <code>data.table</code> <a class="auto-link" href="dplyr-join_by-in-R.html" title="dplyr join_by() in R: Modern Key Specification for Joins">rolling join</a>. Without <code>closest()</code> you would get every prior rate and then have to <code>slice_max()</code> per group, which is slower and more verbose.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Tag each customer signup with the active campaign using between()</h3>
<p class="exercise-task"><strong>Task:</strong> A subscription analyst wants to join each customer signup to the campaign that was running on that signup date. Build inline <code>campaigns</code> (3 rows with <code>campaign</code>, <code>starts</code>, <code>ends</code>) and use <code>inner_join()</code> with <code>by = join_by(between(signup, starts, ends))</code> to attach the active campaign per customer. Save to <code>ex_5_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 6 x 7
#&gt;   customer_id name  segment signup     campaign starts     ends
#&gt;         &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;     &lt;chr&gt;    &lt;date&gt;     &lt;date&gt;
#&gt; 1           1 Alice Pro     2024-01-15 WINTER   2024-01-01 2024-03-31
#&gt; 2           2 Bob   Free    2024-02-08 WINTER   2024-01-01 2024-03-31
#&gt; 3           3 Carol Pro     2024-03-22 WINTER   2024-01-01 2024-03-31
#&gt; 4           4 Dan   Free    2024-05-01 SPRING   2024-04-01 2024-06-14
#&gt; 5           5 Eve   Pro     2024-06-18 SUMMER   2024-06-15 2024-09-30
#&gt; 6           6 Frank Free    2024-09-04 SUMMER   2024-06-15 2024-09-30</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Each signup should match the campaign whose start-to-end window it falls inside.</p><p>Use <code>join_by(between(signup, starts, ends))</code> inside <code>inner_join()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">campaigns &lt;- tibble(
  campaign = c("WINTER","SPRING","SUMMER"),
  starts   = as.Date(c("2024-01-01","2024-04-01","2024-06-15")),
  ends     = as.Date(c("2024-03-31","2024-06-14","2024-09-30"))
)

ex_5_3 &lt;- customers |&gt;
  inner_join(campaigns, by = join_by(between(signup, starts, ends)))
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>between(x, lo, hi)</code> is shorthand for <code>x &gt;= lo, x &lt;= hi</code> with both bounds inclusive by default. Pass <code>bounds = "[)"</code> to mirror SQL's left-inclusive, right-exclusive convention if your campaign windows abut. A common mistake is leaving overlapping ranges in the right table, which silently fans rows out; validate the right table for non-overlap before relying on the join.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-5-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.4: Pair every order with its prior orders via a self inequality join</h3>
<p class="exercise-task"><strong>Task:</strong> An analyst wants every order paired with all PRIOR orders by the same customer (so each row reads "this order followed that earlier one"). Use a self inner_join on <code>orders</code> with <code>join_by(customer_id, order_date &gt; order_date)</code> and pick informative suffixes <code>c("_curr","_prev")</code>. Save the chronological pairs to <code>ex_5_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 7
#&gt;   order_id_curr customer_id order_date_curr amount_curr order_id_prev order_date_prev amount_prev
#&gt;           &lt;int&gt;       &lt;int&gt; &lt;date&gt;                &lt;dbl&gt;         &lt;int&gt; &lt;date&gt;                &lt;dbl&gt;
#&gt; 1           103           1 2024-05-10               30           101 2024-04-02               50
#&gt; 2           107           1 2024-08-12               45           101 2024-04-02               50
#&gt; 3           107           1 2024-08-12               45           103 2024-05-10               30
#&gt; 4           109           5 2024-10-21               90           106 2024-07-04              200</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Join the table to itself so each order can be paired with every earlier order from the same customer.</p><p>Use <code>join_by(customer_id, order_date &gt; order_date)</code> inside a self <code>inner_join()</code>, with <code>suffix = c("_curr", "_prev")</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_4 &lt;- # your code here
ex_5_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_4 &lt;- orders |&gt;
  inner_join(orders,
             by = join_by(customer_id, order_date &gt; order_date),
             suffix = c("_curr","_prev"))
ex_5_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Self-joins on inequalities are the dplyr way to express "pair each row with all prior rows by the same group". The <code>&gt;</code> operator forms a triangular join: for n events per customer you get n*(n-1)/2 pairs, which can blow up. For huge tables prefer window functions (<code>lag()</code> for just-the-previous, or <code>lead()</code>) over a full triangular self-join, and reserve this pattern for "all prior" reports.</p>
</details>
</section>
<h2>Section 6. End-to-end join workflows (5 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: Top three customers by total revenue for a quarterly review</h3>
<p class="exercise-task"><strong>Task:</strong> The GM is preparing for a quarterly business review and wants the top three customers by total order amount, with their full name and segment. Combine <code>orders</code> and <code>customers</code> with the appropriate join, aggregate per customer, then keep the top three rows by revenue. Save the leaderboard to <code>ex_6_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 3 x 3
#&gt;   name  segment total_revenue
#&gt;   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;
#&gt; 1 Eve   Pro               290
#&gt; 2 Alice Pro               125
#&gt; 3 Bob   Free               80</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Combine the two tables, total the amounts per customer, then keep only the highest three.</p><p>Use <code>inner_join()</code> on <code>customer_id</code>, then <code>group_by(name, segment)</code>, <code>summarise(total_revenue = sum(amount))</code>, and <code>slice_max(total_revenue, n = 3)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- orders |&gt;
  inner_join(customers, by = "customer_id") |&gt;
  group_by(name, segment) |&gt;
  summarise(total_revenue = sum(amount), .groups = "drop") |&gt;
  slice_max(total_revenue, n = 3)
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Standard top-N report pattern: inner_join (drops orphan orders), aggregate per customer, slice the top N. Using <code>inner_join()</code> here is intentional because the report is for legitimate customers only, so the orphan orders 105 and 110 are correctly excluded. Always justify whether orphans should appear or be silently filtered, and pick the join type that matches the decision.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Identify Pro-segment churn candidates</h3>
<p class="exercise-task"><strong>Task:</strong> The customer success team wants the list of Pro-segment customers who have NOT placed any order in the last 90 days as of <code>2024-12-01</code>, sorted by signup date with oldest first. Use a filtering join after restricting <code>orders</code> to recent activity. Save the at-risk roster to <code>ex_6_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 4
#&gt;   customer_id name  segment signup
#&gt;         &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;
#&gt; 1           1 Alice Pro     2024-01-15
#&gt; 2           3 Carol Pro     2024-03-22</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Narrow to Pro customers, define what counts as recent activity, keep those without it, and order by signup.</p><p>Use <code>filter(segment == "Pro")</code>, an <code>anti_join()</code> against the recent orders set, then <code>arrange(signup)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">recent &lt;- orders |&gt;
  filter(order_date &gt;= as.Date("2024-09-02"))

ex_6_2 &lt;- customers |&gt;
  filter(segment == "Pro") |&gt;
  anti_join(recent, by = "customer_id") |&gt;
  arrange(signup)
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Filtering joins <a class="auto-link" href="R-Function-Operators.html" title="R Function Operators: Compose, Negate &amp; Partial Application">compose</a> well with regular filters: pre-filter the right side to define "active", pre-filter the left side to define "in scope", then anti_join. Order matters less for correctness than for readability. Many analysts put the segment filter after the anti_join, which works but reads less like the stakeholder's plain-English question and so is harder to review.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-6-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.3: Build a system reconciliation table with a derived status column</h3>
<p class="exercise-task"><strong>Task:</strong> A compliance officer wants a single reconciliation table showing every <code>customer_id</code> from EITHER <code>orders</code> or <code>customers</code>, plus a <code>status</code> column with values <code>"matched"</code>, <code>"orphan_order"</code>, or <code>"no_orders"</code>. Use <code>full_join()</code> on the two distinct keysets with boolean flags, derive <code>status</code> with <code>case_when()</code>, and save the audit table to <code>ex_6_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 8 x 2
#&gt;   customer_id status
#&gt;         &lt;int&gt; &lt;chr&gt;
#&gt; 1           1 matched
#&gt; 2           2 matched
#&gt; 3           3 matched
#&gt; 4           4 matched
#&gt; 5           5 matched
#&gt; 6           6 no_orders
#&gt; 7           7 orphan_order
#&gt; 8           9 orphan_order</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Take the union of both keysets, then label each id by which side it actually came from.</p><p>Add boolean flags before a <code>full_join()</code> on <code>customer_id</code>, then derive <code>status</code> with <code>case_when()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_3 &lt;- customers |&gt;
  distinct(customer_id) |&gt;
  mutate(in_customers = TRUE) |&gt;
  full_join(
    orders |&gt; distinct(customer_id) |&gt; mutate(in_orders = TRUE),
    by = "customer_id"
  ) |&gt;
  mutate(status = case_when(
    in_customers &amp; in_orders ~ "matched",
    in_customers             ~ "no_orders",
    TRUE                     ~ "orphan_order"
  )) |&gt;
  select(customer_id, status) |&gt;
  arrange(customer_id)
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Reconciliation queries always start with <code>full_join()</code> to get the union of both keysets. The trick to deriving "where did this row come from" is to add boolean flags BEFORE the join, then use <code>case_when()</code> after. <code>NA</code> after a full join means "no row on this side", which is the same signal but harder to read in a status column shown to a stakeholder.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-6-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.4: Build a denormalized orders fact table for a dashboard</h3>
<p class="exercise-task"><strong>Task:</strong> A BI engineer wants a single denormalized "orders fact" table that the dashboard can query without further joins. Combine <code>orders</code> (with an added <code>product_id = c(1,2,1,3,4,1,2,3,4,1)</code>), <code>customers</code>, <code>products</code>, and the optional <code>returns</code> table. Use <code>left_join()</code> for everything so the order grain is preserved. Save to <code>ex_6_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 10 x 11
#&gt;    order_id customer_id order_date amount product_id name  segment signup     product   category reason
#&gt;       &lt;int&gt;       &lt;int&gt; &lt;date&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;     &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;
#&gt;  1      101           1 2024-04-02     50          1 Alice Pro     2024-01-15 Widget    Tools    damaged
#&gt;  2      102           2 2024-04-15     80          2 Bob   Free    2024-02-08 Gadget    Tools    NA
#&gt;  3      103           1 2024-05-10     30          1 Alice Pro     2024-01-15 Widget    Tools    NA
#&gt;  4      104           3 2024-05-22     65          3 Carol Pro     2024-03-22 Sprocket  Parts    NA
#&gt;  5      105           7 2024-06-01    120          4 NA    NA      NA         Gizmo     Tools    wrong size
#&gt; # 5 more rows; refund column also present</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Anchor on the orders table so the row count never changes, then layer each dimension on without dropping rows.</p><p>Add <code>product_id</code> with <code>mutate()</code>, then chain <code>left_join()</code> calls for <code>customers</code>, <code>products</code>, and <code>returns</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_4 &lt;- # your code here
ex_6_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_4 &lt;- orders |&gt;
  mutate(product_id = c(1, 2, 1, 3, 4, 1, 2, 3, 4, 1)) |&gt;
  left_join(customers, by = "customer_id") |&gt;
  left_join(products,  by = "product_id") |&gt;
  left_join(returns,   by = "order_id")
ex_6_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Star-schema denormalization is a sequence of <code>left_join()</code>s anchored on the fact table (<code>orders</code>). Always start from the fact, never from a dimension, so the row count of the result equals the row count of the fact. Watch the column-count tax: wide tables hurt downstream pivot performance. For analytical engines prefer this shape; for OLTP storage keep it normalized.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="dplyr-Joins-Exercises-in-R-ex-6-5" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.5: Compute days-to-first-order per customer with a left_join</h3>
<p class="exercise-task"><strong>Task:</strong> The growth team wants <code>days_to_first_order</code> for every customer, computed as the gap in days between their <code>signup</code> date and their first order date. Aggregate <code>orders</code> (after a <code>semi_join()</code> to drop orphans) to one row per customer using <code>min(order_date)</code>, <code>left_join()</code> back to <code>customers</code>, then derive the lag in days. Save to <code>ex_6_5</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 6 x 4
#&gt;   customer_id name  signup     days_to_first_order
#&gt;         &lt;int&gt; &lt;chr&gt; &lt;date&gt;                   &lt;dbl&gt;
#&gt; 1           1 Alice 2024-01-15                  78
#&gt; 2           2 Bob   2024-02-08                  67
#&gt; 3           3 Carol 2024-03-22                  61
#&gt; 4           4 Dan   2024-05-01                 131
#&gt; 5           5 Eve   2024-06-18                  16
#&gt; 6           6 Frank 2024-09-04                  NA</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p><a class="auto-link" href="Reduce-Filter-Map-in-R.html" title="Reduce(), Filter(), Map() in Base R: Functional Trifecta Explained">Reduce</a> orders to each customer's earliest date, attach it back so every customer stays visible, then take the gap.</p><p>Use <code>semi_join()</code> then <code>summarise(first_order_date = min(order_date))</code>, <code>left_join()</code> back to customers, and <code>mutate()</code> the day difference.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_5 &lt;- # your code here
ex_6_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">first_orders &lt;- orders |&gt;
  semi_join(customers, by = "customer_id") |&gt;
  group_by(customer_id) |&gt;
  summarise(first_order_date = min(order_date), .groups = "drop")

ex_6_5 &lt;- customers |&gt;
  left_join(first_orders, by = "customer_id") |&gt;
  mutate(days_to_first_order = as.numeric(first_order_date - signup)) |&gt;
  select(customer_id, name, signup, days_to_first_order)
ex_6_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Time-to-first-X is one of the most common growth metrics. The pattern is: aggregate the event table to a per-entity minimum date, left-join back to the entity dimension to keep entities with no events visible (Frank gets <code>NA</code>, not dropped), then compute the lag. The <code>semi_join()</code> step is defensive: it removes orphans so the per-customer min is computed only over events whose customer actually exists.</p>
</details>
</section>
<h2>What to do next</h2>
<p>Once you finish these, work through these closely related hubs:</p>
<ul>
<li><a href="dplyr-Exercises-in-R.html">dplyr Exercises in R: 50 Practice Problems</a> covers the full verb set (select, filter, mutate, arrange, <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summarise</a>) so the joins above slot into longer pipelines.</li>
<li><a href="dplyr-Group-By-Exercises-in-R.html">dplyr Group By Exercises in R</a> drills the aggregation patterns that almost always follow a join in real reports.</li>
<li><a href="tidyr-Exercises-in-R.html">tidyr Exercises in R</a> covers the pivot and unite/separate operations that prepare wide or long tables before a join.</li>
<li><a href="Data-Wrangling-Exercises-in-R.html">Data Wrangling Exercises in R</a> is the broader mixed-package hub if you want a longer end-to-end workout.</li>
</ul>

{% endraw %}