---
title: "ggplot2 Recreation Challenge: 12 Plots to Rebuild from Scratch"
description: "ggplot2 practice recreate charts from a written spec: 12 plots to rebuild in R, from scatter, bar, and histogram basics to facets, stat summaries, and themes."
keywords: "ggplot2 practice recreate charts, ggplot2 exercises, rebuild ggplot2 plots, ggplot2 challenge, geom_point, facet_wrap, ggplot2 from scratch"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "ggplot2 practice|geom_point|facet_wrap|geom_bar|aesthetic mapping"
auto_link_case_sensitive: false
sidebar_title: "ggplot2 Recreation Challenge"
sidebar_order: "148"
fr_parent: "Complete-Ggplot2-Tutorial-Part1-With-R-Code.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>ggplot2 Recreation Challenge: 12 Plots to Rebuild from Scratch</h1>

<p class="lead">Twelve finished ggplot2 charts, described in words. Your job is to rebuild each one from scratch as a plot object named <code>p</code>. Because a picture cannot be auto-graded, every problem ends with a short fingerprint probe that inspects your plot and prints a signature: match that printed line and your recreation is correct. Solutions stay hidden until you reveal them.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="30" data-exercises="12" data-xp="180"></div>

<p>Work in order. The first four are single-geom warm-ups (scatter, histogram, bar, line); the middle four add colour, facets, and a <a class="auto-link" href="ggplot2-Position-Adjustments-in-R.html" title="Position Adjustments in ggplot2: Stack, Dodge, Jitter, Fill">position adjustment</a>; the last four layer on statistics, flipped coordinates, an annotation, and a custom theme. Read each spec carefully, because the dataset, the geoms, the aesthetic mappings, and any labels are all part of the target.</p>

<p>Every fingerprint is one line you run after building <code>p</code>. It reports things like the geom class, the number of layers, how many rows the plot's internal data has, or a label you set. None of them draw the chart, so the only thing printed to the console is the signature you are matching. Match it exactly, spaces and all.</p>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(ggplot2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Single-geom warm-ups (4 plots)</h2>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-1-1" data-grade-mode="self-check" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Rebuild a weight-versus-mileage scatterplot</h3>

<p class="exercise-task"><strong>Task:</strong> Recreate a simple scatterplot from the <code>mtcars</code> dataset: put car weight <code>wt</code> on the x axis and fuel economy <code>mpg</code> on the y axis, drawn with a single point layer, then relabel the axes to "Weight (1000 lbs)" and "Miles per gallon". Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$x)</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomPoint 32 Weight (1000 lbs)</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Every ggplot starts from a dataset and an <a class="auto-link" href="ggplot2-Aesthetics-aes-Map-Data.html" title="ggplot2 aes(): Map Any Variable to Any Visual Property — The Complete Reference">aesthetic mapping</a>; a scatterplot then needs the point geom drawn on top of that base.</p><p>Combine <code>ggplot(mtcars, aes(x = wt, y = mpg))</code> with <code>geom_point()</code>, then add <code>labs(x = &quot;Weight (1000 lbs)&quot;, y = &quot;Miles per gallon&quot;)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$x)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  labs(x = &quot;Weight (1000 lbs)&quot;, y = &quot;Miles per gallon&quot;)

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$x)
#&gt; GeomPoint 32 Weight (1000 lbs)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>geom_point()</code> draws one mark per row, so the plot's built data has 32 rows, matching the 32 cars in <code>mtcars</code>. The fingerprint reads the class of the first layer's geom, that row count, and the x-axis label you set with <code>labs()</code>. A frequent beginner mistake is quoting the column names inside <code>aes()</code>; variables in <code>aes()</code> are unquoted because they refer to columns, not strings.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-1-2" data-grade-mode="self-check" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.2: Recreate a 20-bin histogram of eruption times</h3>

<p class="exercise-task"><strong>Task:</strong> Using the built-in <code>faithful</code> dataset, build a histogram of the <code>eruptions</code> column with exactly 20 bins and give it the title "Old Faithful eruptions". The bars should show how eruption durations cluster into two groups. Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$title)</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomBar 20 Old Faithful eruptions</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A <a class="auto-link" href="ggplot2-geom_histogram-in-R.html" title="ggplot2 geom_histogram() in R: Histograms With Examples">histogram bins</a> one continuous variable and counts how many observations land in each bin, so only an x aesthetic is mapped.</p><p>Use <code>geom_histogram(bins = 20)</code> on <code>aes(x = eruptions)</code>, then add the title with <code>labs(title = ...)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$title)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(faithful, aes(x = eruptions)) +
  geom_histogram(bins = 20) +
  labs(title = &quot;Old Faithful eruptions&quot;)

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$title)
#&gt; GeomBar 20 Old Faithful eruptions</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A histogram is drawn with rectangles, so under the hood <code>geom_histogram()</code> uses the bar geom, which is why the fingerprint reports <code>GeomBar</code> rather than a dedicated histogram class. Setting <code>bins = 20</code> produces exactly 20 rows in the built data, one per bin. Leaving <code>bins</code> unset falls back to 30 and prints a "pick better value" message, so always choose a bin count deliberately.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-1-3" data-grade-mode="self-check" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.3: Recreate a count bar chart of diamond cuts</h3>

<p class="exercise-task"><strong>Task:</strong> From the <code>diamonds</code> dataset, draw a bar chart that counts how many diamonds fall into each <code>cut</code> category, and fill every bar with the constant colour "steelblue" rather than mapping colour to a variable. Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), ggplot_build(p)$data[[1]]$fill[1])</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomBar 5 steelblue</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>When the bar height should be a tally of rows in each category you do not supply a y aesthetic; the geom counts for you.</p><p>Map only <code>aes(x = cut)</code> and set the colour with <code>geom_bar(fill = &quot;steelblue&quot;)</code>, placing <code>fill</code> outside <code>aes()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), ggplot_build(p)$data[[1]]$fill[1])</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(diamonds, aes(x = cut)) +
  geom_bar(fill = &quot;steelblue&quot;)

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), ggplot_build(p)$data[[1]]$fill[1])
#&gt; GeomBar 5 steelblue</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>geom_bar()</code> applies a counting statistic, so a single categorical x with five <code>cut</code> levels yields five bars and five rows in the built data. The fill is placed outside <code>aes()</code> because it is a fixed constant, not data to be mapped; putting <code>fill = &quot;steelblue&quot;</code> inside <code>aes()</code> would treat the literal word as a one-level variable and draw a redundant legend. Use <code>geom_col()</code> instead when you already have the heights.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-1-4" data-grade-mode="self-check" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.4: Recreate the unemployment time-series line</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>economics</code> dataset, plot a line of total <code>unemploy</code> (thousands of people) over <code>date</code> so the reader sees the long-run trend and recessions as peaks. Label the y axis "Unemployed (thousands)". Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$y)</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomLine 574 Unemployed (thousands)</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A trend over time needs both a date on the x axis and the measured value on the y axis, connected in order by a line geom.</p><p>Map <code>aes(x = date, y = unemploy)</code>, add <code>geom_line()</code>, then set the y label with <code>labs(y = &quot;Unemployed (thousands)&quot;)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$y)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(economics, aes(x = date, y = unemploy)) +
  geom_line() +
  labs(y = &quot;Unemployed (thousands)&quot;)

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]), p$labels$y)
#&gt; GeomLine 574 Unemployed (thousands)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>geom_line()</code> connects the observations in ascending x order, which is exactly what you want for a monthly <a class="auto-link" href="Time-Series-Analysis-With-R.html" title="Time Series Analysis with R">time series</a>; <code>economics</code> holds 574 months, so the built data keeps all 574 vertices. The fingerprint confirms the geom, the number of points, and the y label you set. Reach for <code>geom_line()</code> over <code>geom_path()</code> here, because <code>geom_path()</code> connects rows in table order rather than sorting by the x value.</p>

</details>

</section>

<h2>Section 2. Colour, facets, and position (4 plots)</h2>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-2-1" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.1: Recreate a scatter coloured by vehicle class</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>mpg</code> dataset, plot highway mileage <code>hwy</code> against engine displacement <code>displ</code> as points, and map the point colour to the <code>class</code> variable so each vehicle type gets its own colour and a legend appears. Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], length(unique(ggplot_build(p)$data[[1]]$group)), nrow(ggplot_build(p)$data[[1]]))</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomPoint 7 234</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>To colour points by a category you map that category to the colour aesthetic inside <code>aes()</code>, which also splits the data into groups.</p><p>Add <code>colour = class</code> to <code>aes(x = displ, y = hwy, ...)</code> and keep a plain <code>geom_point()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], length(unique(ggplot_build(p)$data[[1]]$group)), nrow(ggplot_build(p)$data[[1]]))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mpg, aes(x = displ, y = hwy, colour = class)) +
  geom_point()

cat(class(p$layers[[1]]$geom)[1], length(unique(ggplot_build(p)$data[[1]]$group)), nrow(ggplot_build(p)$data[[1]]))
#&gt; GeomPoint 7 234</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Mapping <code>colour = class</code> inside <code>aes()</code> tells ggplot the colour depends on the data, so it creates one group per class (seven here) and adds a legend automatically. All 234 rows of <code>mpg</code> are still plotted, so the built data keeps 234 rows while the internal <code>group</code> column takes seven distinct values. The classic mistake is writing <code>colour = class</code> outside <code>aes()</code>, which paints every point one fixed colour and produces no legend.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-2-2" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: Recreate a small-multiples grid of scatterplots</h3>

<p class="exercise-task"><strong>Task:</strong> Take the same <code>mpg</code> scatter of <code>hwy</code> against <code>displ</code> with plain points, but split it into a grid of small panels, one panel per vehicle <code>class</code>, so each type is shown separately with shared axes. Save the plot to <code>p</code>, then run <code>cat(class(p$facet)[1], nrow(ggplot_build(p)$layout$layout))</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; FacetWrap 7</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Splitting one plot into many panels by a single categorical variable is the job of a wrapping facet, not a separate plot per group.</p><p>Add <code>facet_wrap(~ class)</code> to the base scatter of <code>aes(x = displ, y = hwy)</code> with <code>geom_point()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$facet)[1], nrow(ggplot_build(p)$layout$layout))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_wrap(~ class)

cat(class(p$facet)[1], nrow(ggplot_build(p)$layout$layout))
#&gt; FacetWrap 7</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>facet_wrap(~ class)</code> builds one panel for each of the seven classes and wraps them into a grid, sharing the x and y scales so panels are directly comparable. The plot's internal layout table holds one row per panel, which is why the count is seven. Use <code>facet_wrap()</code> for a single faceting variable and <code>facet_grid()</code> when you want a full rows-by-columns matrix from two variables.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-2-3" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.3: Recreate boxplots of mileage by drive type</h3>

<p class="exercise-task"><strong>Task:</strong> From the <code>mpg</code> dataset, draw side-by-side boxplots of highway mileage <code>hwy</code> for each drive train <code>drv</code> (four-wheel, front, and rear), and fill each box by mapping <code>fill</code> to <code>drv</code> as well. Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]))</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomBoxplot 3</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A boxplot summarises a numeric variable within each category, so the categorical goes on x and the numeric on y.</p><p>Use <code>geom_boxplot()</code> with <code>aes(x = drv, y = hwy, fill = drv)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mpg, aes(x = drv, y = hwy, fill = drv)) +
  geom_boxplot()

cat(class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]))
#&gt; GeomBoxplot 3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> There are three drive types, so ggplot computes one box per group and the built data holds three rows, each carrying the median, hinges, and whisker limits from the boxplot statistic. Mapping <code>fill</code> to the same variable as x simply colours each box, which aids scanning even though it duplicates the x information. If you only need one box per category, mapping fill is cosmetic; drop it when a legend would be redundant with the axis.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-2-4" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.4: Recreate a 100 percent stacked bar of clarity within cut</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>diamonds</code> dataset, build a bar chart with <code>cut</code> on the x axis and <code>clarity</code> mapped to fill, but stack the bars to a constant height of one so each bar shows the proportion of clarity grades within that cut rather than raw counts. Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], class(p$layers[[1]]$position)[1], nrow(ggplot_build(p)$data[[1]]))</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomBar PositionFill 40</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Turning a stacked count chart into a proportion chart is a position adjustment, not a change of geom or statistic.</p><p>Keep <code>geom_bar()</code> with <code>aes(x = cut, fill = clarity)</code> and pass <code>position = &quot;fill&quot;</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], class(p$layers[[1]]$position)[1], nrow(ggplot_build(p)$data[[1]]))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(diamonds, aes(x = cut, fill = clarity)) +
  geom_bar(position = &quot;fill&quot;)

cat(class(p$layers[[1]]$geom)[1], class(p$layers[[1]]$position)[1], nrow(ggplot_build(p)$data[[1]]))
#&gt; GeomBar PositionFill 40</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>position = &quot;fill&quot;</code> stacks the clarity segments and then rescales every bar to height one, converting counts into within-cut proportions so cuts of different sizes become comparable. With five cut levels and eight clarity grades the built data has forty segments. Swap the position to <code>&quot;stack&quot;</code> for raw counts or <code>&quot;dodge&quot;</code> to place the clarity bars side by side; the geom and mappings stay the same, only the arrangement changes.</p>

</details>

</section>

<h2>Section 3. Stats, coordinates, and polish (4 plots)</h2>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-3-1" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.1: Recreate a scatter with a linear trend line</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>mpg</code> dataset, plot highway mileage <code>hwy</code> against displacement <code>displ</code> as points, then add a second layer that fits and draws a straight linear trend line through the cloud with method <code>lm</code> and formula <code>y ~ x</code>. Save the plot to <code>p</code>, then run <code>cat(length(p$layers), class(p$layers[[2]]$geom)[1], class(p$layers[[2]]$stat)[1])</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 2 GeomSmooth StatSmooth</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A raw scatter plus a fitted trend is two separate layers stacked in order, with the trend added after the points.</p><p>Add <code>geom_smooth(method = &quot;lm&quot;, formula = y ~ x)</code> after <code>geom_point()</code> on the shared <code>aes(x = displ, y = hwy)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(length(p$layers), class(p$layers[[2]]$geom)[1], class(p$layers[[2]]$stat)[1])</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, formula = y ~ x)

cat(length(p$layers), class(p$layers[[2]]$geom)[1], class(p$layers[[2]]$stat)[1])
#&gt; 2 GeomSmooth StatSmooth</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The plot has two layers: the points and the smoother. <code>geom_smooth()</code> pairs the smooth geom with the smoothing statistic, which is why the fingerprint reports <code>GeomSmooth</code> and <code>StatSmooth</code> on the second layer. Passing <code>method = &quot;lm&quot;</code> fits a linear model and <code>formula = y ~ x</code> states the model explicitly, avoiding the automatic message ggplot prints when it guesses. Layer order matters: add the line after the points so it sits on top.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-3-2" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.2: Recreate a plot of mean mileage per class</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>mpg</code> dataset, show the average highway mileage for each vehicle <code>class</code> as a single point per class, computed on the fly rather than pre-aggregated, with the point size set to 3. Save the plot to <code>p</code>, then run <code>cat(class(p$layers[[1]]$geom)[1], class(p$layers[[1]]$stat)[1], nrow(ggplot_build(p)$data[[1]]))</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; GeomPoint StatSummary 7</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>You want one summarised value per category drawn as a point, which a summary statistic can compute inside the plot without a separate aggregation step.</p><p>Use <code>stat_summary(fun = mean, geom = &quot;point&quot;, size = 3)</code> on <code>aes(x = class, y = hwy)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$layers[[1]]$geom)[1], class(p$layers[[1]]$stat)[1], nrow(ggplot_build(p)$data[[1]]))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mpg, aes(x = class, y = hwy)) +
  stat_summary(fun = mean, geom = &quot;point&quot;, size = 3)

cat(class(p$layers[[1]]$geom)[1], class(p$layers[[1]]$stat)[1], nrow(ggplot_build(p)$data[[1]]))
#&gt; GeomPoint StatSummary 7</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>stat_summary()</code> collapses each of the seven classes to a single number, here the mean of <code>hwy</code>, and draws it with the point geom, so the built data has exactly seven rows. The fingerprint sees <code>GeomPoint</code> for the geom and <code>StatSummary</code> for the statistic. Computing the mean inside the plot keeps your pipeline short; swap <code>fun = median</code> for a robust centre, or add <code>fun.min</code> and <code>fun.max</code> to turn the same layer into <a class="auto-link" href="Communicating-Uncertainty.html" title="Communicating Uncertainty: Don't Mislead Your Audience with Data Viz">error bars</a>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-3-3" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.3: Recreate a horizontal bar chart with flipped coordinates</h3>

<p class="exercise-task"><strong>Task:</strong> From the <code>mpg</code> dataset, draw a count bar chart of vehicle <code>class</code>, then flip the coordinate system so the bars run horizontally and the class names read comfortably along the vertical axis instead of overlapping on the bottom. Save the plot to <code>p</code>, then run <code>cat(class(p$coordinates)[1], class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]))</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; CoordFlip GeomBar 7</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Making category bars horizontal so long labels stop colliding is a coordinate-system change layered on top of an ordinary bar chart.</p><p>Build <code>geom_bar()</code> on <code>aes(x = class)</code>, then add <code>coord_flip()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(class(p$coordinates)[1], class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mpg, aes(x = class)) +
  geom_bar() +
  coord_flip()

cat(class(p$coordinates)[1], class(p$layers[[1]]$geom)[1], nrow(ggplot_build(p)$data[[1]]))
#&gt; CoordFlip GeomBar 7</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>coord_flip()</code> swaps the x and y axes at draw time, so the seven counted bars stay <code>GeomBar</code> with seven rows of data while the coordinate object becomes <code>CoordFlip</code>. Flipping is the easy way to make long category labels legible without rotating text. A modern alternative that avoids <code>coord_flip()</code> entirely is to map the categorical variable directly to y, for example <code>aes(y = class)</code>, which ggplot now supports natively for bars.</p>

</details>

</section>

<section class="exercise" data-exercise-id="ggplot2-Recreation-Challenge-ex-3-4" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.4: Recreate an annotated, minimally themed scatterplot</h3>

<p class="exercise-task"><strong>Task:</strong> Rebuild the <code>mtcars</code> scatter of <code>mpg</code> against <code>wt</code> with points, then add a fixed text annotation reading "Heavier cars, lower mpg" at position x equals 4 and y equals 30, give the plot the title "Fuel economy vs weight", and apply the minimal theme. Save the plot to <code>p</code>, then run <code>cat(length(p$layers), class(p$layers[[2]]$geom)[1], p$labels$title)</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 2 GeomText Fuel economy vs weight</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A one-off text label pinned to specific coordinates is added with an annotation, which becomes a second layer without needing its own data frame.</p><p>Add <code>annotate(&quot;text&quot;, x = 4, y = 30, label = &quot;Heavier cars, lower mpg&quot;)</code>, then <code>labs(title = ...)</code> and <code>theme_minimal()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- # your code here

cat(length(p$layers), class(p$layers[[2]]$geom)[1], p$labels$title)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  annotate(&quot;text&quot;, x = 4, y = 30, label = &quot;Heavier cars, lower mpg&quot;) +
  labs(title = &quot;Fuel economy vs weight&quot;) +
  theme_minimal()

cat(length(p$layers), class(p$layers[[2]]$geom)[1], p$labels$title)
#&gt; 2 GeomText Fuel economy vs weight</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>annotate(&quot;text&quot;, ...)</code> adds a single text layer at fixed data coordinates, so the plot now has two layers and the second one is a <code>GeomText</code>. Because annotations carry their own inline values rather than a mapped column, they never spawn a legend, which is why they beat <code>geom_text()</code> for one-off labels. <code>theme_minimal()</code> strips the grey panel background for a cleaner look, and the fingerprint reads the title straight from the labels you set with <code>labs()</code>.</p>

</details>

</section>

<h2>What to do next</h2>

<p>Keep drilling ggplot2 with these related practice hubs:</p>

<ul>

<li><a href="ggplot2-Exercises-in-R.html">ggplot2 Exercises in R</a> for a broad set of plotting problems across every common chart type.</li>

<li><a href="ggplot2-Facets-Exercises-in-R.html">ggplot2 Facets Exercises in R</a> to go deeper on <a class="auto-link" href="Small-Multiples-in-R.html" title="Small Multiples in R: the 40-Tiny-Plots Workflow">small multiples</a> with <code>facet_wrap</code> and <code>facet_grid</code>.</li>

<li><a href="ggplot2-Color-Scales-Exercises-in-R.html">ggplot2 Color Scales Exercises in R</a> to master palettes, gradients, and legend control.</li>

<li><a href="Data-Visualization-Exercises-in-R.html">Data Visualization Exercises in R</a> for a wider tour of charts and design choices.</li>

</ul>

{% endraw %}