---
title: "GLM Exercises in R: 20 Logistic, Poisson, Gamma Practice Problems"
description: "GLM exercises in R: 20 hands-on practice problems on logistic, Poisson, Gamma, negative binomial, multinomial and ordinal models with worked solutions."
keywords: "GLM exercises in R, generalized linear model practice, logistic regression exercises, Poisson regression practice, glm() in R, link functions, R modeling practice"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "generalized linear model|logistic regression|poisson regression|link function|negative binomial regression|gamma regression"
auto_link_case_sensitive: false
sidebar_title: "GLM Exercises"
sidebar_order: "150"
fr_parent: "Poisson-Regression-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>GLM Exercises in R: 20 Logistic, Poisson, Gamma Practice Problems</h1>

<p class="lead">Twenty practice problems on generalized linear models in R. You will fit logistic, Poisson, Gamma, quasi-Poisson, negative binomial, multinomial and ordinal GLMs, then interpret coefficients, compare nested models and produce predictions on the link and response scale. Each solution is hidden behind a click-to-reveal block so you can attempt first.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="50" data-exercises="22" data-xp="330"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(MASS)
library(nnet)
library(dplyr)
library(ggplot2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Binomial GLMs and Logistic Regression (4 problems)</h2>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-1-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Fit a binary logistic regression on mtcars transmission</h3>

<p class="exercise-task"><strong>Task:</strong> Use <code>glm()</code> with the <a class="auto-link" href="Logistic-Regression-in-R.html" title="Logistic Regression in R: From glm() to Odds Ratios, ROC, and AUC">binomial family</a> to predict transmission type <code>am</code> (0 = automatic, 1 = manual) from <code>mpg</code> and <code>wt</code> in the <code>mtcars</code> dataset. Save the fitted model to <code>ex_1_1</code> and print its summary.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call: glm(formula = am ~ mpg + wt, family = binomial, data = mtcars)
#&gt;
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)  25.8866    12.1935   2.123   0.0338 *
#&gt; mpg          -0.3242     0.2374  -1.366   0.1721
#&gt; wt           -6.4162     2.5466  -2.519   0.0118 *
#&gt;
#&gt; (Dispersion parameter for binomial family taken to be 1)
#&gt;
#&gt;     Null deviance: 43.230  on 31  degrees of freedom
#&gt; Residual deviance: 17.184  on 29  degrees of freedom
#&gt; AIC: 23.184</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A binary 0/1 outcome like transmission type calls for the model family built for proportions, not the ordinary linear one.</p><p>Call glm() with the formula am ~ mpg + wt, family = binomial and data = mtcars.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
summary(ex_1_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- glm(am ~ mpg + wt, family = binomial, data = mtcars)
summary(ex_1_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The default link for <code>family = binomial</code> is <code>logit</code>, so coefficients are on the log-odds scale. A negative <code>wt</code> coefficient means heavier cars are less likely to have manual transmission. The Z statistic plus its <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">p-value</a> comes from the Wald test, which is fine for large samples but unreliable near zero events. AIC and residual deviance let you compare against nested alternatives later.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-1-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.2: Predict loan default probabilities for a credit-risk team</h3>

<p class="exercise-task"><strong>Task:</strong> A credit-risk analyst at a community bank wants a quick logistic baseline before sending the data to the modelling team. Using the inline <code>loans</code> tibble defined below, fit <code>default ~ income + loan_amount</code> with <code>family = binomial</code> and save the model to <code>ex_1_2</code>. Report the coefficient on <code>loan_amount</code> in odds-ratio form (one log-thousand-dollar increase).</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Coefficients:
#&gt;                Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)    -1.5413     1.7724  -0.870  0.38449
#&gt; income         -0.0420     0.0207  -2.025  0.04284 *
#&gt; loan_amount     0.1875     0.0691   2.715  0.00663 **
#&gt;
#&gt; Odds ratio for loan_amount: 1.2062</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A yes/no default is another proportion outcome, so reach for the same model family as the previous exercise and remember odds ratios are a multiplicative re-expression of the coefficient.</p><p>Fit with glm() using family = binomial and data = loans, then exponentiate the loan_amount coefficient from coef().</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
loans &lt;- tibble(
  income      = round(rnorm(120, mean = 55, sd = 18)),     # in $1000s
  loan_amount = round(runif(120, min = 5, max = 35), 1),   # in $1000s
  default     = rbinom(120, 1, plogis(-2 + 0.18 * loan_amount - 0.04 * income))
)

ex_1_2 &lt;- # your code here
summary(ex_1_2)
exp(coef(ex_1_2)[&quot;loan_amount&quot;])</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
loans &lt;- tibble(
  income      = round(rnorm(120, mean = 55, sd = 18)),
  loan_amount = round(runif(120, min = 5, max = 35), 1),
  default     = rbinom(120, 1, plogis(-2 + 0.18 * loan_amount - 0.04 * income))
)

ex_1_2 &lt;- glm(default ~ income + loan_amount, family = binomial, data = loans)
summary(ex_1_2)
exp(coef(ex_1_2)[&quot;loan_amount&quot;])
#&gt; loan_amount
#&gt;    1.20621</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Exponentiating a logit coefficient gives an odds ratio: each extra $1,000 borrowed multiplies the odds of default by about 1.21, holding income fixed. Report odds ratios to stakeholders rather than raw logits, because business owners reason in multiplicative risk, not log-odds. Always state the unit ("per $1,000") and the holding-constant assumption to avoid misinterpretation.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-1-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.3: Get predicted probabilities on the response scale</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>ex_1_1</code> model from Exercise 1.1, generate predicted probabilities of <code>am = 1</code> for three hypothetical cars: (mpg=15, wt=4), (mpg=20, wt=3) and (mpg=30, wt=1.8). Save the result to <code>ex_1_3</code> as a numeric vector and round to three decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;     1     2     3
#&gt; 0.001 0.131 0.999</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>You want probabilities in [0, 1], not log-odds, so the linear predictor has to be pushed through the inverse link.</p><p>Use predict() with newdata = newdf and type = "response", then wrap the result in round(..., 3).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">newdf &lt;- data.frame(mpg = c(15, 20, 30), wt = c(4, 3, 1.8))
ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">newdf &lt;- data.frame(mpg = c(15, 20, 30), wt = c(4, 3, 1.8))
ex_1_3 &lt;- round(predict(ex_1_1, newdata = newdf, type = &quot;response&quot;), 3)
ex_1_3
#&gt;     1     2     3
#&gt; 0.001 0.131 0.999</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>type = &quot;response&quot;</code> runs the linear predictor through the inverse link (here, the logistic CDF <code>plogis</code>) so the output is a probability in [0, 1]. Without that argument you would get the link-scale value, which is the log-odds and ranges over the real line. Newcomers often forget the <code>type</code> argument and report log-odds as probabilities by accident.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-1-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 1.4: Test a nested model with anova(LRT)</h3>

<p class="exercise-task"><strong>Task:</strong> Compare the full <code>am ~ mpg + wt</code> model from Exercise 1.1 against a reduced model <code>am ~ wt</code> using a <a class="auto-link" href="Likelihood-Ratio-Wald-and-Score-Tests-in-R.html" title="Likelihood Ratio, Wald & Score Tests in R: Three Ways to Test Hypotheses">likelihood ratio test</a>. Save the <code>anova()</code> object to <code>ex_1_4</code> and report whether dropping <code>mpg</code> significantly worsens fit at alpha = 0.05.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Analysis of Deviance Table
#&gt;
#&gt; Model 1: am ~ wt
#&gt; Model 2: am ~ mpg + wt
#&gt;   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
#&gt; 1        30     19.176
#&gt; 2        29     17.184  1   1.9925   0.1581</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Comparing a model against a smaller version of itself is a nested-model test of whether the dropped term earns its place.</p><p>Call anova() on the reduced and full models with the argument test = "LRT".</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">reduced &lt;- glm(am ~ wt, family = binomial, data = mtcars)
ex_1_4 &lt;- # your code here
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">reduced &lt;- glm(am ~ wt, family = binomial, data = mtcars)
ex_1_4 &lt;- anova(reduced, ex_1_1, test = &quot;LRT&quot;)
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The likelihood ratio test compares twice the difference in log-likelihoods to a chi-square with degrees of freedom equal to the number of dropped parameters. Here p = 0.158, so <code>mpg</code> does not add significant explanatory power beyond <code>wt</code>. Prefer LRT over the Wald p-value from <code>summary()</code> when comparing nested GLMs, especially with small samples like 32 observations.</p>

</details>

</section>

<h2>Section 2. Poisson Regression and Count Data (4 problems)</h2>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-2-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 2.1: Fit a Poisson GLM on warpbreaks</h3>

<p class="exercise-task"><strong>Task:</strong> Use <code>glm()</code> with <code>family = poisson</code> to model <code>breaks ~ wool + tension</code> in the built-in <code>warpbreaks</code> dataset, which records the number of warp breaks per loom run. Save the fitted model to <code>ex_2_1</code> and print its coefficients.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call: glm(formula = breaks ~ wool + tension, family = poisson, data = warpbreaks)
#&gt;
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)  3.69196    0.04541  81.302  &lt; 2e-16 ***
#&gt; woolB       -0.20599    0.05157  -3.994 6.49e-05 ***
#&gt; tensionM    -0.32132    0.06027  -5.332 9.73e-08 ***
#&gt; tensionH    -0.51849    0.06396  -8.107 5.21e-16 ***
#&gt;
#&gt; (Dispersion parameter for poisson family taken to be 1)
#&gt;     Null deviance: 297.37  on 53  degrees of freedom
#&gt; Residual deviance: 210.39  on 50  degrees of freedom</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A count of warp breaks per loom run is count data, which has its own dedicated GLM family.</p><p>Call glm() with breaks ~ wool + tension, family = poisson and data = warpbreaks.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
summary(ex_2_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- glm(breaks ~ wool + tension, family = poisson, data = warpbreaks)
summary(ex_2_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Poisson regression uses a log link by default, so coefficients are on the log-rate scale. <code>exp(-0.206)</code> for <code>woolB</code> means wool B has about 81% as many breaks as wool A at the same tension. The dispersion parameter is fixed at 1; if the residual deviance is much larger than the residual degrees of freedom (here 210 vs 50) you have <a class="auto-link" href="Poisson-Regression-in-R.html" title="Poisson Regression in R: Model Count Data and Handle Overdispersion">overdispersion</a> and should consider quasi-Poisson or negative binomial.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-2-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: Use an offset to model emergency-room visit rates</h3>

<p class="exercise-task"><strong>Task:</strong> An ED operations team wants a model of nightly visits adjusted for shift length. Using the inline <code>er</code> tibble, fit a Poisson GLM with <code>log(hours)</code> as an offset so the coefficients describe the rate per hour, not raw counts. Save the model to <code>ex_2_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)  1.62894    0.08322  19.575  &lt; 2e-16 ***
#&gt; staffhigh   -0.43078    0.09214  -4.675 2.94e-06 ***
#&gt;
#&gt; (Dispersion parameter for poisson family taken to be 1)
#&gt; Number of Fisher Scoring iterations: 4</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>To turn raw counts into a rate per hour, exposure has to enter the model with a fixed effect that is not estimated.</p><p>Add offset(log(hours)) to the formula inside glm() with family = poisson.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
er &lt;- tibble(
  staff  = factor(rep(c(&quot;low&quot;, &quot;high&quot;), each = 30), levels = c(&quot;low&quot;, &quot;high&quot;)),
  hours  = sample(6:12, 60, replace = TRUE),
  visits = rpois(60, lambda = ifelse(rep(c(&quot;low&quot;,&quot;high&quot;), each = 30) == &quot;low&quot;,
                                     0.9, 0.55) * sample(6:12, 60, replace = TRUE))
)

ex_2_2 &lt;- # your code here
summary(ex_2_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
er &lt;- tibble(
  staff  = factor(rep(c(&quot;low&quot;, &quot;high&quot;), each = 30), levels = c(&quot;low&quot;, &quot;high&quot;)),
  hours  = sample(6:12, 60, replace = TRUE),
  visits = rpois(60, lambda = ifelse(rep(c(&quot;low&quot;,&quot;high&quot;), each = 30) == &quot;low&quot;,
                                     0.9, 0.55) * sample(6:12, 60, replace = TRUE))
)

ex_2_2 &lt;- glm(visits ~ staff + offset(log(hours)),
              family = poisson, data = er)
summary(ex_2_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> An offset enters the linear predictor with coefficient fixed at 1, so <code>log(rate) = log(visits/hours) = beta0 + beta1 staff</code>. Without the offset, longer shifts would absorb their own dummy effect and you'd lose the rate interpretation. Offsets are standard in epidemiology (person-years), insurance (policy duration) and call-centre analytics (open hours).</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-2-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.3: Convert coefficients to incidence rate ratios</h3>

<p class="exercise-task"><strong>Task:</strong> Take the <code>ex_2_1</code> warpbreaks Poisson model and convert each non-intercept coefficient to an <a class="auto-link" href="Poisson-and-Negative-Binomial-Regression.html" title="Poisson & Negative Binomial Regression: Model Count Data in R">incidence rate ratio</a> with a 95 percent confidence interval. Save the resulting numeric matrix (rows = predictors, columns = IRR, lower, upper) to <code>ex_2_3</code> and round to three decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;            IRR  lower upper
#&gt; woolB    0.814  0.736 0.901
#&gt; tensionM 0.725  0.644 0.816
#&gt; tensionH 0.595  0.525 0.675</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Rate ratios live on the multiplicative scale, so the log-scale estimates and their standard errors both need back-transforming.</p><p>Pull estimates and standard errors from coef(summary(ex_2_1)), then exp() the estimate and the Wald bounds estimate +/- 1.96 * SE.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">coefs &lt;- coef(summary(ex_2_1))[-1, &quot;Estimate&quot;]
ses   &lt;- coef(summary(ex_2_1))[-1, &quot;Std. Error&quot;]
irr   &lt;- exp(coefs)
lower &lt;- exp(coefs - 1.96 * ses)
upper &lt;- exp(coefs + 1.96 * ses)
ex_2_3 &lt;- round(cbind(IRR = irr, lower = lower, upper = upper), 3)
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Exponentiating a Poisson coefficient yields an IRR: a multiplicative effect on the expected count. The Wald CI is exp(estimate plus or minus 1.96 SE); for tighter coverage with small samples use <a class="auto-link" href="Likelihood-Ratio-Tests-and-Pivotal-Methods.html" title="Likelihood Ratio Tests & Pivotal Methods: Confidence Sets Theory">profile likelihood</a> via <code>confint()</code>. IRRs are easier to communicate than log-rates: "tension H cuts breaks to 60% of tension L" beats "the log-rate falls by 0.518".</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-2-4" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 2.4: Detect and correct overdispersion with quasi-Poisson</h3>

<p class="exercise-task"><strong>Task:</strong> Diagnose overdispersion in the warpbreaks Poisson fit by computing the ratio of residual deviance to residual degrees of freedom, then refit with <code>family = quasipoisson</code> and compare standard errors. Save the quasi-Poisson model to <code>ex_2_4</code> and report the dispersion estimate.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Deviance / df ratio for ex_2_1:
#&gt; [1] 4.208
#&gt;
#&gt; Dispersion parameter for quasipoisson: 3.851...
#&gt;
#&gt; Coefficients (quasi-Poisson):
#&gt;             Estimate Std. Error t value Pr(&gt;|t|)
#&gt; (Intercept)  3.69196    0.08914  41.421  &lt; 2e-16 ***
#&gt; woolB       -0.20599    0.10122  -2.035  0.04719 *
#&gt; tensionM    -0.32132    0.11827  -2.717  0.00903 **
#&gt; tensionH    -0.51849    0.12554  -4.130 0.000139 ***</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>When the spread of counts outstrips what the count family assumes, switch to a family that estimates its own dispersion instead of fixing it at 1.</p><p>Refit with glm() using family = quasipoisson and read the dispersion from summary(...)$dispersion.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">deviance_ratio &lt;- deviance(ex_2_1) / df.residual(ex_2_1)
deviance_ratio

ex_2_4 &lt;- # your code here
summary(ex_2_4)$dispersion
summary(ex_2_4)$coefficients</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">deviance_ratio &lt;- deviance(ex_2_1) / df.residual(ex_2_1)
deviance_ratio
#&gt; [1] 4.207867

ex_2_4 &lt;- glm(breaks ~ wool + tension, family = quasipoisson, data = warpbreaks)
summary(ex_2_4)$dispersion
summary(ex_2_4)$coefficients</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A deviance/df ratio of 4.2 is far above 1, signalling that the Poisson variance assumption underestimates uncertainty. Quasi-Poisson keeps the same coefficient estimates but inflates standard errors by sqrt(dispersion), so Wald tests become more conservative. If the dispersion is also large, negative binomial (next section) is often a better choice because it has a proper likelihood and AIC.</p>

</details>

</section>

<h2>Section 3. Other GLM Families: Gamma, Negative Binomial, Probit (3 problems)</h2>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-3-1" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.1: Fit a negative binomial regression with MASS::glm.nb</h3>

<p class="exercise-task"><strong>Task:</strong> Refit the warpbreaks count model using <code>MASS::glm.nb()</code> to handle the overdispersion you found in Exercise 2.4. Save the model to <code>ex_3_1</code> and compare its AIC with the Poisson model <code>ex_2_1</code>. Report which model has lower AIC.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call: MASS::glm.nb(formula = breaks ~ wool + tension, data = warpbreaks, init.theta = 9.944, link = log)
#&gt;
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)  3.69196    0.09374  39.385  &lt; 2e-16 ***
#&gt; woolB       -0.20599    0.10646  -1.935 0.052924 .
#&gt; tensionM    -0.32132    0.12690  -2.532 0.011339 *
#&gt; tensionH    -0.51849    0.12921  -4.013 6.00e-05 ***
#&gt;
#&gt; AIC(ex_2_1):  493.06
#&gt; AIC(ex_3_1):  408.76
#&gt; NB wins by:    84.30</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A count model with a second variance parameter absorbs heavy overdispersion while still producing a genuine likelihood you can compare.</p><p>Fit with <a class="auto-link" href="Negative-Binomial-Regression-in-R.html" title="Negative Binomial Regression in R: MASS::glm.nb() & Overdispersion Fix">MASS::glm.nb</a>() on breaks ~ wool + tension and contrast the two models with AIC().</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
summary(ex_3_1)
c(poisson_aic = AIC(ex_2_1), nb_aic = AIC(ex_3_1))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- MASS::glm.nb(breaks ~ wool + tension, data = warpbreaks)
summary(ex_3_1)
c(poisson_aic = AIC(ex_2_1), nb_aic = AIC(ex_3_1))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Negative binomial adds a second parameter (<code>theta</code>) that absorbs extra variance, so unlike quasi-Poisson it produces a real likelihood and a comparable AIC. A drop of 84 AIC units is overwhelming evidence in favour of NB. Always log <code>theta</code> and check whether it's large (close to Poisson) or small (heavy overdispersion); here <code>theta</code> of 9.9 is moderate.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-3-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.2: Gamma GLM for positive insurance-claim amounts</h3>

<p class="exercise-task"><strong>Task:</strong> A claims actuary wants to model average claim severity for a small portfolio. Using the inline <code>claims</code> tibble (positive continuous amounts), fit a Gamma GLM with the log link, <code>amount ~ region + age_band</code>, and save the model to <code>ex_3_2</code>. Print the exponentiated coefficients so they are read as multiplicative effects on the expected claim cost.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Multiplicative effects on expected claim amount:
#&gt; (Intercept)    regionrural    age_bandsenior
#&gt;     1842.7          0.762             1.318</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A strictly positive, right-skewed amount like a claim cost needs a continuous GLM family matched to that shape.</p><p>Call glm() with family = Gamma(link = "log") and data = claims, then exp() the coefficients for multiplicative effects.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
claims &lt;- tibble(
  region   = factor(sample(c(&quot;urban&quot;, &quot;rural&quot;), 200, replace = TRUE)),
  age_band = factor(sample(c(&quot;adult&quot;, &quot;senior&quot;), 200, replace = TRUE, prob = c(0.6, 0.4))),
  amount   = rgamma(200, shape = 2,
                    rate  = 2 / (1800 *
                                 ifelse(sample(c(&quot;urban&quot;, &quot;rural&quot;), 200, replace = TRUE) == &quot;rural&quot;, 0.75, 1) *
                                 ifelse(sample(c(&quot;adult&quot;, &quot;senior&quot;), 200, replace = TRUE, prob = c(0.6, 0.4)) == &quot;senior&quot;, 1.3, 1)))
)

ex_3_2 &lt;- # your code here
round(exp(coef(ex_3_2)), 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
claims &lt;- tibble(
  region   = factor(sample(c(&quot;urban&quot;, &quot;rural&quot;), 200, replace = TRUE)),
  age_band = factor(sample(c(&quot;adult&quot;, &quot;senior&quot;), 200, replace = TRUE, prob = c(0.6, 0.4))),
  amount   = rgamma(200, shape = 2,
                    rate  = 2 / (1800 *
                                 ifelse(sample(c(&quot;urban&quot;, &quot;rural&quot;), 200, replace = TRUE) == &quot;rural&quot;, 0.75, 1) *
                                 ifelse(sample(c(&quot;adult&quot;, &quot;senior&quot;), 200, replace = TRUE, prob = c(0.6, 0.4)) == &quot;senior&quot;, 1.3, 1)))
)

ex_3_2 &lt;- glm(amount ~ region + age_band,
              family = Gamma(link = &quot;log&quot;), data = claims)
round(exp(coef(ex_3_2)), 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Gamma with a log link is the natural GLM for strictly positive, right-skewed continuous outcomes like claim cost, hospital LOS or component lifetimes. The constant coefficient of variation built into the Gamma matches actuarial intuition that larger expected claims have proportionally larger spread. Avoid the canonical inverse link in practice: it can yield negative fitted values during iteration.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-3-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.3: Compare logit and probit links on the same binary outcome</h3>

<p class="exercise-task"><strong>Task:</strong> Fit two binary GLMs on the <code>mtcars</code> data predicting <code>am</code> from <code>wt</code>, one with the default <code>logit</code> link and one with <code>probit</code>. Save them together in a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> <code>ex_3_3</code> with elements <code>logit</code> and <code>probit</code>. Print both summaries side by side, focusing on the <code>wt</code> coefficient.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $logit$wt
#&gt; Estimate: -4.024   SE: 1.436   z: -2.802
#&gt;
#&gt; $probit$wt
#&gt; Estimate: -2.366   SE: 0.793   z: -2.984
#&gt;
#&gt; Coefficients differ in magnitude (logit ~ 1.7x probit) but fitted probabilities are nearly identical.</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Both fits share the same formula and outcome family; only the curve mapping the linear predictor to a probability differs.</p><p>Call glm() twice, passing binomial(link = "logit") and binomial(link = "probit") as the family.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- list(
  logit  = # your code here,
  probit = # your code here
)
sapply(ex_3_3, function(m) coef(summary(m))[&quot;wt&quot;, c(&quot;Estimate&quot;,&quot;Std. Error&quot;,&quot;z value&quot;)])</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- list(
  logit  = glm(am ~ wt, family = binomial(link = &quot;logit&quot;),  data = mtcars),
  probit = glm(am ~ wt, family = binomial(link = &quot;probit&quot;), data = mtcars)
)
sapply(ex_3_3, function(m) coef(summary(m))[&quot;wt&quot;, c(&quot;Estimate&quot;,&quot;Std. Error&quot;,&quot;z value&quot;)])</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Logit and probit are nearly indistinguishable in fitted probabilities because the logistic and normal CDFs agree closely in the middle range. Logit dominates because coefficients double as log-odds (interpretable), while probit is preferred in econometrics for latent-variable narratives. Coefficient magnitudes differ by roughly the ratio of the link slopes at 0, about 1.6 to 1.8.</p>

</details>

</section>

<h2>Section 4. GLM Diagnostics, Inference and Goodness of Fit (4 problems)</h2>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-4-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 4.1: Read residual deviance, null deviance and AIC from summary()</h3>

<p class="exercise-task"><strong>Task:</strong> Refit the binary logistic <code>am ~ mpg + wt</code> on <code>mtcars</code> and extract three scalars from the model object directly: null deviance, residual deviance and AIC. Save the three values to a named numeric vector <code>ex_4_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;    null residual      aic
#&gt;  43.230   17.184   23.184</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>These three fit statistics are already stored as named components inside the fitted model object, so no extra computation is needed.</p><p>Pull fit$null.deviance, fit$deviance and fit$aic into a single named c() vector.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
round(ex_4_1, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- glm(am ~ mpg + wt, family = binomial, data = mtcars)
ex_4_1 &lt;- c(
  null     = fit$null.deviance,
  residual = fit$deviance,
  aic      = fit$aic
)
round(ex_4_1, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Null deviance measures fit of an intercept-only model, residual deviance measures fit of the full model, and their difference is the deviance explained. AIC penalises that fit by <code>2 * k</code> parameters, which lets you compare non-nested models. Always read both deviance and AIC: a model with great AIC but tiny deviance drop relative to null might be capturing noise.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-4-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.2: Build profile-likelihood confidence intervals</h3>

<p class="exercise-task"><strong>Task:</strong> For the <code>am ~ mpg + wt</code> logistic model from Exercise 1.1, build 95 percent profile-likelihood <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence intervals</a> for all coefficients using <code>confint()</code>. Save the matrix to <code>ex_4_2</code> and round to three decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;              2.5 %  97.5 %
#&gt; (Intercept) 6.795  61.611
#&gt; mpg        -1.061   0.018
#&gt; wt        -13.704  -2.572</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Profile-likelihood intervals trace the curvature of the likelihood rather than assuming a symmetric Wald approximation.</p><p>Call confint() on ex_1_1 and round() the resulting matrix to three decimals.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">suppressMessages({
  ex_4_2 &lt;- round(confint(ex_1_1), 3)
})
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>confint()</code> on a <code>glm</code> object profiles the log-likelihood across each coefficient, giving CIs that respect the curvature of the likelihood, not just a Wald approximation. With n = 32, Wald and profile intervals can differ noticeably; profile is the safer default. Use <code>confint.default()</code> if you specifically want Wald (estimate +/- 1.96 SE) for reporting consistency with <code>summary()</code>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-4-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.3: Flag potential outliers via Pearson residuals</h3>

<p class="exercise-task"><strong>Task:</strong> Compute <a class="auto-link" href="Chi-Square-Tests-in-R.html" title="Chi-Square Tests in R: Independence, Goodness-of-Fit, With Effect Sizes">Pearson residuals</a> for the warpbreaks Poisson model <code>ex_2_1</code>, identify rows with absolute Pearson residual greater than 2, and save those row numbers (as a sorted integer vector) to <code>ex_4_3</code>. Report how many such rows you flagged.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1]  5  9 19 20 21 30 32 49 51
#&gt; Flagged 9 rows out of 54.</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Standardised residuals whose absolute value clears a threshold flag the observations the model fits worst.</p><p>Apply which() to the logical test abs(pr) > 2 and wrap it in sort() to get ordered row numbers.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pr &lt;- residuals(ex_2_1, type = &quot;pearson&quot;)
ex_4_3 &lt;- # your code here
ex_4_3
length(ex_4_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pr &lt;- residuals(ex_2_1, type = &quot;pearson&quot;)
ex_4_3 &lt;- sort(which(abs(pr) &gt; 2))
ex_4_3
length(ex_4_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Pearson residuals standardise the raw difference by the model-implied standard deviation, so absolute values above 2 are unusually large under the model. A cluster of large Pearson residuals often signals overdispersion (Section 2.4) rather than individual outliers. Pair with <code>cooks.distance()</code> for leverage, and inspect flagged rows for data-entry errors before discarding any.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-4-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 4.4: Compute McFadden pseudo-R^2 by hand</h3>

<p class="exercise-task"><strong>Task:</strong> McFadden's pseudo-R^2 is defined as $1 - \\log L_{full} / \\log L_{null}$. Compute it for the <code>am ~ mpg + wt</code> logistic by fitting a null model and using <code>logLik()</code> on both fits. Save the scalar to <code>ex_4_4</code> rounded to four decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; McFadden pseudo-R^2: 0.6025</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>The measure contrasts the fitted model's log-likelihood against that of an intercept-only baseline.</p><p>Take logLik() of both fits and compute 1 - logLik(full) / logLik(null), coercing each with <a class="auto-link" href="R-Type-Coercion.html" title="R Type Coercion: Why Your Numeric Columns Silently Turn Into Characters">as.numeric()</a>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">null_fit &lt;- glm(am ~ 1, family = binomial, data = mtcars)
ex_4_4 &lt;- # your code here
ex_4_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">null_fit &lt;- glm(am ~ 1, family = binomial, data = mtcars)
ex_4_4 &lt;- round(1 - as.numeric(logLik(ex_1_1)) / as.numeric(logLik(null_fit)), 4)
ex_4_4
#&gt; [1] 0.6025</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Pseudo-R^2 statistics for GLMs do not match the proportion-of-variance interpretation from OLS, so the same numeric value carries different meaning. McFadden values above 0.2 are usually considered an excellent fit for cross-sectional logistic models. Report it alongside AIC and the <a class="auto-link" href="Logistic-Regression-in-R-2.html" title="Logistic Regression in R: Complete Guide with Diagnostics & Interpretation">Hosmer-Lemeshow test</a> rather than as a single goodness-of-fit headline.</p>

</details>

</section>

<h2>Section 5. Predictions, Marginal Effects and Visualization (4 problems)</h2>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-5-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.1: Predict on the link scale and the response scale</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>ex_1_1</code> model, predict the linear predictor (<code>type = &quot;link&quot;</code>) and the probability (<code>type = &quot;response&quot;</code>) for the existing <code>mtcars</code> rows. Save both vectors together as a tibble with columns <code>eta</code> and <code>prob</code> named <code>ex_5_1</code> and inspect the first three rows.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 32 x 2
#&gt;      eta   prob
#&gt;    &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 -0.546  0.367
#&gt; 2 -1.060  0.257
#&gt; 3  3.886  0.980
#&gt; # 29 more rows hidden</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The same fitted model returns either the linear predictor or the probability depending on which scale you ask for.</p><p>Call predict() twice with type = "link" and type = "response", binding the two vectors into a tibble.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
head(ex_5_1, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- tibble(
  eta  = predict(ex_1_1, type = &quot;link&quot;),
  prob = predict(ex_1_1, type = &quot;response&quot;)
)
head(ex_5_1, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The link-scale prediction <code>eta</code> is the linear combination <code>Xb</code>, returned by default. Applying the inverse link <code>plogis(eta)</code> recovers <code>prob</code>. Always reason about uncertainty (standard errors, CIs) on the link scale where coverage is symmetric, then back-transform endpoints to probabilities; CIs computed on the response scale can run below 0 or above 1.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-5-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.2: Average marginal effect of wt on probability of manual transmission</h3>

<p class="exercise-task"><strong>Task:</strong> Compute the average marginal effect of <code>wt</code> on the predicted probability of <code>am = 1</code> for the <code>mtcars</code> rows under the <code>ex_1_1</code> model. Use the chain rule: <code>dP/dwt = beta_wt * p * (1 - p)</code> averaged over the sample. Save the scalar to <code>ex_5_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Average marginal effect of wt: -0.3186
#&gt; Interpretation: a one-tonne increase in weight cuts P(am=1) by about 32 percentage points on average.</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A logistic slope changes across the curve, so the effect on probability has to be averaged over every observation rather than read off once.</p><p>Form the per-row quantity beta_wt <em> p </em> (1 - p) and collapse it with mean().</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- predict(ex_1_1, type = &quot;response&quot;)
beta_wt &lt;- coef(ex_1_1)[&quot;wt&quot;]
ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">p &lt;- predict(ex_1_1, type = &quot;response&quot;)
beta_wt &lt;- coef(ex_1_1)[&quot;wt&quot;]
ex_5_2 &lt;- mean(beta_wt * p * (1 - p))
ex_5_2
#&gt;         wt
#&gt; -0.3186...</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Logistic coefficients alone don't give a probability change because the slope of the sigmoid varies across the input. The average marginal effect (AME) integrates <code>dP/dX</code> over the empirical distribution, producing a single interpretable number on the probability scale. For more complex GLMs and interactions, the <code>marginaleffects</code> package automates this with proper standard errors via the <a class="auto-link" href="Asymptotic-Theory-in-R.html" title="Asymptotic Theory in R: Consistency, Asymptotic Normality & Delta Method">delta method</a>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-5-3" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.3: Plot the predicted probability curve over weight</h3>

<p class="exercise-task"><strong>Task:</strong> Produce a <code>ggplot</code> line chart showing predicted P(am = 1) versus <code>wt</code> from 1.5 to 5.5 (mpg held at its sample mean) using the <code>ex_1_1</code> model. Save the ggplot object to <code>ex_5_3</code>. Add the raw <code>mtcars</code> points jittered along y = am.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A ggplot object: line of fitted probability descends from ~1.0 near wt=1.5
#&gt; to ~0.0 near wt=5.5; raw points sit at y=0 and y=1 with horizontal jitter; theme_minimal.</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Draw the smooth fitted curve from the prediction grid, then overlay the raw 0/1 outcomes so the data is visible.</p><p>Combine <a class="auto-link" href="ggplot2-Getting-Started.html" title="ggplot2 for Beginners: Build 5 Real Charts in 30 Minutes — Zero Experience Needed">geom_line()</a> on the grid with a jittered point layer on mtcars inside a <a class="auto-link" href="ggplot2-Tutorial-With-R.html" title="ggplot2 Short Tutorial">ggplot()</a> call, finishing with <a class="auto-link" href="Publication-Quality-Figures-in-R.html" title="Publication-Ready ggplot2 Figures: The Checklist for Journals and Theses">theme_minimal()</a>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">grid &lt;- data.frame(wt = seq(1.5, 5.5, length.out = 100), mpg = mean(mtcars$mpg))
grid$p &lt;- predict(ex_1_1, newdata = grid, type = &quot;response&quot;)

ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">grid &lt;- data.frame(wt = seq(1.5, 5.5, length.out = 100), mpg = mean(mtcars$mpg))
grid$p &lt;- predict(ex_1_1, newdata = grid, type = &quot;response&quot;)

ex_5_3 &lt;- ggplot() +
  geom_line(data = grid, aes(wt, p), color = &quot;steelblue&quot;, linewidth = 1.1) +
  geom_jitter(data = mtcars, aes(wt, am), height = 0.04, width = 0,
              color = &quot;grey30&quot;, alpha = 0.7) +
  labs(x = &quot;Weight (1000 lb)&quot;, y = &quot;P(am = 1)&quot;,
       title = &quot;Predicted probability of manual transmission&quot;) +
  theme_minimal()
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Holding <code>mpg</code> at its mean isolates the effect of <code>wt</code> but hides interactions. For a richer picture, facet by binned <code>mpg</code> or use a partial-dependence plot that integrates over the empirical distribution of <code>mpg</code>. Jittering the raw outcomes vertically by a small amount keeps the 0/1 anchors readable without misleading the eye about probability values.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-5-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.4: Standard error bands on the link scale, back-transformed</h3>

<p class="exercise-task"><strong>Task:</strong> Build 95 percent <a class="auto-link" href="Communicating-Uncertainty.html" title="Communicating Uncertainty: Don't Mislead Your Audience with Data Viz">confidence bands</a> for the predicted probability curve in Exercise 5.3 by using <code>predict(..., type = &quot;link&quot;, se.fit = TRUE)</code> and back-transforming the link-scale endpoints with <code>plogis</code>. Save the augmented prediction tibble (columns <code>wt</code>, <code>fit</code>, <code>lower</code>, <code>upper</code>) to <code>ex_5_4</code> and print its first three rows.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 100 x 4
#&gt;      wt   fit lower upper
#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1  1.50 0.999 0.748 1.000
#&gt; 2  1.54 0.999 0.760 1.000
#&gt; 3  1.58 0.999 0.771 1.000
#&gt; # 97 more rows hidden</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Build the interval where it stays symmetric, then map both endpoints back to the probability scale so the band cannot escape [0, 1].</p><p>The link-scale prediction already has se.fit = TRUE, so apply plogis() to fit and to fit +/- 1.96 * se.fit.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">grid &lt;- data.frame(wt = seq(1.5, 5.5, length.out = 100), mpg = mean(mtcars$mpg))
pr   &lt;- predict(ex_1_1, newdata = grid, type = &quot;link&quot;, se.fit = TRUE)

ex_5_4 &lt;- # your code here
head(ex_5_4, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">grid &lt;- data.frame(wt = seq(1.5, 5.5, length.out = 100), mpg = mean(mtcars$mpg))
pr   &lt;- predict(ex_1_1, newdata = grid, type = &quot;link&quot;, se.fit = TRUE)

ex_5_4 &lt;- tibble(
  wt    = grid$wt,
  fit   = plogis(pr$fit),
  lower = plogis(pr$fit - 1.96 * pr$se.fit),
  upper = plogis(pr$fit + 1.96 * pr$se.fit)
)
head(ex_5_4, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Confidence bands constructed in the linear-predictor space and back-transformed remain inside [0, 1] and are asymmetric near the boundaries, which is what you want for a probability. Bands built directly on the response scale (estimate +/- 1.96 SE_p) can extend past 1, which embarrasses your plot. This is the same pattern as Poisson, Gamma and survival GLMs: do uncertainty work on the link scale.</p>

</details>

</section>

<h2>Section 6. Multinomial and Ordinal GLM Extensions (3 problems)</h2>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-6-1" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.1: Fit a multinomial logistic regression with nnet::multinom</h3>

<p class="exercise-task"><strong>Task:</strong> Use <code>nnet::multinom()</code> to fit a multinomial logistic model predicting <code>Species</code> from <code>Sepal.Length</code> and <code>Petal.Length</code> in the <code>iris</code> dataset. Save the model to <code>ex_6_1</code> and print the matrix of fitted log-odds coefficients (rows: non-reference categories, columns: predictors).</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # weights:  12 (6 variable)
#&gt; initial  value 164.791843
#&gt; final  value ... ...
#&gt; converged
#&gt;
#&gt;            (Intercept) Sepal.Length Petal.Length
#&gt; versicolor  ...           ...           ...
#&gt; virginica   ...           ...           ...</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A three-class unordered outcome needs a model that fits several logits at once against one <a class="auto-link" href="Dummy-Variables-in-R.html" title="Dummy Variables in R: What lm() Does With Factor Predictors Under the Hood">reference category</a>.</p><p>Fit with nnet::<a class="auto-link" href="Multinomial-Logistic-Regression-in-R.html" title="Multinomial Logistic Regression in R: nnet::multinom() Step-by-Step">multinom()</a> on Species ~ Sepal.Length + Petal.Length and data = iris.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
coef(ex_6_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- nnet::multinom(Species ~ Sepal.Length + Petal.Length,
                         data = iris, trace = FALSE)
coef(ex_6_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A multinomial logit fits K-1 simultaneous binary logits against a reference category (here <code>setosa</code>, alphabetically first). Convergence can be fragile with perfectly separable classes (iris setosa is linearly separable on petal length), so check warning messages. For ordered outcomes use proportional-odds logistic regression instead, which is more parsimonious and respects the ordering.</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-6-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 6.2: Predicted class probabilities from a multinomial model</h3>

<p class="exercise-task"><strong>Task:</strong> Using the <code>ex_6_1</code> multinomial model, predict the three-class probability vector for a new flower with Sepal.Length = 6.0 and Petal.Length = 4.5. Save the named numeric vector to <code>ex_6_2</code> and round to three decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;    setosa versicolor  virginica
#&gt;     0.000      0.834      0.166</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>You want the full vector of class probabilities for the new flower, not just the single winning label.</p><p>Call predict() with newdata = newflower and type = "probs", then round() to three decimals.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">newflower &lt;- data.frame(Sepal.Length = 6.0, Petal.Length = 4.5)
ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">newflower &lt;- data.frame(Sepal.Length = 6.0, Petal.Length = 4.5)
ex_6_2 &lt;- round(predict(ex_6_1, newdata = newflower, type = &quot;probs&quot;), 3)
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>type = &quot;probs&quot;</code> returns a row vector that sums to 1 across the K categories. <code>type = &quot;class&quot;</code> returns the modal class, which is convenient but throws away calibration information. For decision making, expose the full probability vector so downstream code can apply asymmetric loss (the cost of confusing setosa and virginica may differ from confusing the two non-setosa species).</p>

</details>

</section>

<section class="exercise" data-exercise-id="GLM-Exercises-in-R-ex-6-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.3: Fit a proportional-odds ordinal logistic model with MASS::polr</h3>

<p class="exercise-task"><strong>Task:</strong> Build an inline <code>survey</code> tibble where respondents rated a product on an ordered 1-5 Likert scale, with <code>age</code> and <code>region</code> as predictors. Fit a proportional-odds logistic regression using <code>MASS::polr()</code>, save it to <code>ex_6_3</code> and print the model summary.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call:
#&gt; MASS::polr(formula = rating ~ age + region, data = survey, Hess = TRUE)
#&gt;
#&gt; Coefficients:
#&gt;                 Value Std. Error t value
#&gt; age          -0.02451   0.00982 -2.4960
#&gt; regionsouth   0.78533   0.30041  2.6142
#&gt;
#&gt; Intercepts:
#&gt;     Value   Std. Error t value
#&gt; 1|2 -2.4612  0.6411    -3.8390
#&gt; 2|3 -1.2487  0.5870    -2.1273
#&gt; 3|4  0.4019  0.5784     0.6949
#&gt; 4|5  1.8854  0.6122     3.0793
#&gt;
#&gt; Residual Deviance: 421.66  AIC: 433.66</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>An ordered Likert outcome calls for a model that respects the ranking with one shared slope per predictor and a set of cutpoint thresholds.</p><p>Fit with <a class="auto-link" href="Ordinal-Logistic-Regression-in-R.html" title="Ordinal Logistic Regression in R: MASS::polr() & Proportional Odds">MASS::polr()</a> on rating ~ age + region, data = survey and Hess = TRUE.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(2026)
survey &lt;- tibble(
  age    = sample(18:75, 150, replace = TRUE),
  region = factor(sample(c(&quot;north&quot;, &quot;south&quot;), 150, replace = TRUE)),
  rating = factor(sample(1:5, 150, replace = TRUE,
                         prob = c(0.10, 0.20, 0.30, 0.25, 0.15)),
                  levels = 1:5, ordered = TRUE)
)

ex_6_3 &lt;- # your code here
summary(ex_6_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(2026)
survey &lt;- tibble(
  age    = sample(18:75, 150, replace = TRUE),
  region = factor(sample(c(&quot;north&quot;, &quot;south&quot;), 150, replace = TRUE)),
  rating = factor(sample(1:5, 150, replace = TRUE,
                         prob = c(0.10, 0.20, 0.30, 0.25, 0.15)),
                  levels = 1:5, ordered = TRUE)
)

ex_6_3 &lt;- MASS::polr(rating ~ age + region, data = survey, Hess = TRUE)
summary(ex_6_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A proportional-odds model fits one slope per predictor and K-1 thresholds for the K-level outcome, assuming the effect of each predictor on the cumulative log-odds is constant across cutpoints. Check that assumption with the Brant test (<code>brant::brant(ex_6_3)</code>); if it fails, use a partial-proportional-odds model via <code>VGAM::vglm()</code> or fall back to multinomial logistic, which gives up parsimony for flexibility.</p>

</details>

</section>

<h2>What to do next</h2>

<p>You now have hands-on practice across the major GLM families. Build on this with these next stops:</p>

<ul>

<li><a href="Logistic-Regression-Exercises-in-R.html">Logistic Regression Exercises in R</a> drills deeper into the binomial family with separation, calibration, and ROC-style evaluation.</li>

<li><a href="Poisson-Regression-Exercises-in-R.html">Poisson Regression Exercises in R</a> extends the count-modeling track with offsets, exposure terms and rate ratios.</li>

<li><a href="Logistic-Regression-With-R.html">Logistic Regression in R</a> is the parent tutorial covering the underlying theory and full case study.</li>

<li><a href="Poisson-Regression-in-R.html">Poisson Regression in R</a> walks through expected counts, IRRs and overdispersion checks as a complete tutorial.</li>

</ul>

{% endraw %}