---
title: "Hypothesis Testing Exercises in R: 25 Real-World Practice Problems"
description: "25 hypothesis testing exercises in R covering t-tests, proportions, chi-square, non-parametric tests, power, multiple-testing correction, and equivalence."
keywords: "hypothesis testing R, t-test exercises, p-value practice, chi-square exercises, power analysis R, Wilcoxon Mann-Whitney, multiple testing correction"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "hypothesis testing exercises|hypothesis testing practice|hypothesis test problems|p-value practice|t-test exercises|power analysis practice"
auto_link_case_sensitive: false
sidebar_title: "Hypothesis Testing Exercises"
sidebar_order: "125"
fr_parent: "Hypothesis-Testing-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Hypothesis Testing Exercises in R: 25 Real-World Practice Problems</h1>

<p class="lead">These 25 hypothesis testing exercises rebuild the full inference workflow in R: one-sample and two-sample t-tests, proportion and chi-square tests, non-parametric alternatives, power and effect size, and production patterns like multiple-testing correction and <a class="auto-link" href="Equivalence-Testing-in-R.html" title="Equivalence Testing in R: TOST for Non-Inferiority & Bioequivalence">equivalence testing</a>. Every solution is hidden behind a reveal so you can verify after coding.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="60" data-exercises="25" data-xp="375"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(dplyr)
library(ggplot2)
library(pwr)
library(broom)
library(purrr)
library(tibble)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. One-sample tests and reading the test object (4 problems)</h2>

<h3>Exercise 1.1: Two-sided one-sample t-test on iris Sepal.Width</h3>

<p><strong>Task:</strong> Run a two-sided <a class="auto-link" href="t-Tests-in-R.html" title="t-Tests in R: Every Variant With the Decision Rule for Choosing Between Them">one-sample t-test</a> on <code>iris$Sepal.Width</code> against the <a class="auto-link" href="Hypothesis-Testing-in-R.html" title="Hypothesis Testing in R: Understand the Framework, Not Just the p-Value">null hypothesis</a> that the population mean equals 3.0. Use the full 150-row dataset and the default 95% confidence level. Save the entire <code>htest</code> object to <code>ex_1_1</code> so the next exercise can pull values out of it.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  One Sample t-test
#&gt;
#&gt; data:  iris$Sepal.Width
#&gt; t = 1.6105, df = 149, p-value = 0.1094
#&gt; alternative hypothesis: true mean is not equal to 3
#&gt; 95 percent confidence interval:
#&gt;  2.986557 3.128110
#&gt; sample estimates:
#&gt; mean of x
#&gt;  3.057333</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- t.test(iris$Sepal.Width, mu = 3.0)
ex_1_1
#&gt;
#&gt;  One Sample t-test
#&gt;
#&gt; data:  iris$Sepal.Width
#&gt; t = 1.6105, df = 149, p-value = 0.1094</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>t.test(x, mu = ...)</code> runs a one-sample t-test against the hypothesised mean. The sample mean of 3.057 sits only 0.057 above 3.0, the t statistic is a modest 1.61, and p = 0.109 fails to reject H0 at the usual 0.05 cutoff. The 95% CI \[2.987, 3.128\] contains 3.0, which is the same decision expressed as an interval. Keeping the full object (not just the p-value) lets you pull every component later.</p>

</details>

<h3>Exercise 1.2: Extract p-value, statistic, and CI from a t-test object</h3>

<p><strong>Task:</strong> Using the object from Exercise 1.1, build a named numeric vector containing the t statistic, the p-value, and the two endpoints of the <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">95% confidence interval</a>. Use only <code>$</code> accessors against the <code>htest</code> object. Save the four-element named vector to <code>ex_1_2</code> so you can pipe it into a report-friendly format.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; statistic   p_value     ci_lo     ci_hi
#&gt; 1.6105000 0.1093850 2.9865568 3.1281099</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- c(
  statistic = unname(ex_1_1$statistic),
  p_value   = ex_1_1$p.value,
  ci_lo     = ex_1_1$conf.int[1],
  ci_hi     = ex_1_1$conf.int[2]
)
ex_1_2
#&gt; statistic   p_value     ci_lo     ci_hi
#&gt; 1.6105000 0.1093850 2.9865568 3.1281099</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Every <code>htest</code> object is a list, so <code>$p.value</code>, <code>$statistic</code>, <code>$conf.int</code>, and <code>$parameter</code> give you the raw numbers. <code>unname()</code> strips the "t" label R puts on the statistic element so the output vector looks clean. This pattern is the foundation of every automated reporting pipeline: run a test, pluck the numbers, drop them in a table. <code>broom::tidy(ex_1_1)</code> is the tidyverse equivalent and returns a 1-row tibble with the same columns.</p>

</details>

<h3>Exercise 1.3: One-sided alternative for an air quality cleanup target</h3>

<p><strong>Task:</strong> A regulator setting an ozone advisory wants to test whether the New York summer mean of <code>airquality$Ozone</code> is strictly greater than 40 ppb. Drop the <a class="auto-link" href="Missing-Value-Treatment-With-R.html" title="Missing Value Treatment">missing values</a>, run a one-sided one-sample t-test with <code>alternative = &quot;greater&quot;</code>, and save the test object to <code>ex_1_3</code>. State whether the regulator should reject the 40 ppb null at alpha 0.05.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  One Sample t-test
#&gt;
#&gt; data:  na.omit(airquality$Ozone)
#&gt; t = 0.5779, df = 115, p-value = 0.2822
#&gt; alternative hypothesis: true mean is greater than 40
#&gt; 95 percent confidence interval:
#&gt;  35.91368      Inf
#&gt; sample estimates:
#&gt; mean of x
#&gt;  42.12931</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- t.test(
  na.omit(airquality$Ozone),
  mu = 40,
  alternative = &quot;greater&quot;
)
ex_1_3$p.value
#&gt; [1] 0.2821847</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The one-sided alternative <code>&quot;greater&quot;</code> only counts deviations above 40, so the <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">t distribution</a>'s upper tail supplies the p-value. The sample mean is 42.13 (above 40) yet noise is large, so p = 0.28 fails to reject. The CI lower bound becomes finite (35.91) while the upper is +Inf: a one-sided CI is a half-line, not an interval. A two-sided test here would give roughly double the p-value but a symmetric finite interval.</p>

</details>

<h3>Exercise 1.4: Confidence interval and p-value give the same decision</h3>

<p><strong>Task:</strong> For the built-in vector <code>trees$Height</code>, run a two-sided one-sample t-test against <code>mu = 75</code>. Build a 2-row tibble with columns <code>mu</code> and <code>decision</code> where row 1 reports the p < 0.05 decision and row 2 reports whether 75 lies inside the 95% CI. Save the tibble to <code>ex_1_4</code> and confirm both rows agree.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 2 x 2
#&gt;   mu    decision
#&gt;   &lt;chr&gt; &lt;chr&gt;
#&gt; 1 p&lt;.05 fail to reject
#&gt; 2 inCI  fail to reject</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">tt &lt;- t.test(trees$Height, mu = 75)
in_ci &lt;- 75 &gt;= tt$conf.int[1] &amp;&amp; 75 &lt;= tt$conf.int[2]
ex_1_4 &lt;- tibble::tibble(
  mu = c(&quot;p&lt;.05&quot;, &quot;inCI&quot;),
  decision = c(
    if (tt$p.value &lt; 0.05) &quot;reject&quot; else &quot;fail to reject&quot;,
    if (in_ci) &quot;fail to reject&quot; else &quot;reject&quot;
  )
)
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The two-sided CI and the two-sided p-value are mathematically the same procedure expressed differently: the 95% CI is the set of mu values that would NOT be rejected at alpha = 0.05. If your hypothesised mu sits inside the CI, p > 0.05; if outside, p < 0.05. Always. When students see the two disagree, it is almost always a one-sided test with a half-line CI being compared against a two-sided cutoff.</p>

</details>

<h2>Section 2. Two-sample comparisons (5 problems)</h2>

<h3>Exercise 2.1: Welch two-sample t-test on iris setosa vs versicolor</h3>

<p><strong>Task:</strong> A botanist studying speciation wants to know whether setosa and versicolor irises differ in mean sepal length. Filter <code>iris</code> to those two species, run a Welch two-sample t-test on <code>Sepal.Length</code> by <code>Species</code>, and save the test object to <code>ex_2_1</code>. State the p-value and the direction of the estimated difference.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Welch Two Sample t-test
#&gt;
#&gt; data:  Sepal.Length by Species
#&gt; t = -15.386, df = 86.538, p-value &lt; 2.2e-16
#&gt; alternative hypothesis: true difference in means between group setosa and group versicolor is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -1.105533 -0.851334
#&gt; sample estimates:
#&gt;     mean in group setosa mean in group versicolor
#&gt;                    5.006                    5.936</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">two_species &lt;- iris %&gt;% filter(Species %in% c(&quot;setosa&quot;, &quot;versicolor&quot;))
two_species$Species &lt;- droplevels(two_species$Species)

ex_2_1 &lt;- t.test(Sepal.Length ~ Species, data = two_species)
ex_2_1$p.value
#&gt; [1] 8.985235e-27</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The formula interface <code>y ~ group</code> is the cleanest way to pass a two-sample test: R splits <code>Sepal.Length</code> by the factor levels. <code>droplevels()</code> removes the unused virginica level so the test labels print cleanly. Welch is the default because it does NOT assume equal variances; it adjusts the degrees of freedom (here 86.5, not 98) to compensate. The negative CI tells you setosa (the first level alphabetically) has the smaller mean.</p>

</details>

<h3>Exercise 2.2: Paired t-test on a within-subject weight change</h3>

<p><strong>Task:</strong> A trial coordinator measures weight before and after a 12-week intervention on 20 participants. Build the inline tibble below, run a paired t-test of <code>weight_after</code> against <code>weight_before</code>, and save the test object to <code>ex_2_2</code>. Decide whether the intervention produced a significant mean weight change.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pre_post &lt;- tibble::tibble(
  subject       = 1:20,
  weight_before = c(82.4, 90.1, 78.2, 85.6, 91.0, 79.3, 88.7, 84.2, 86.5, 80.9,
                   89.4, 83.1, 87.6, 81.8, 92.3, 85.0, 77.4, 88.0, 84.5, 86.8),
  weight_after  = c(80.1, 88.4, 76.7, 83.9, 88.2, 78.5, 86.1, 82.5, 84.6, 79.7,
                   86.8, 81.5, 85.9, 80.2, 89.5, 83.4, 76.2, 85.7, 82.8, 84.6)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Paired t-test
#&gt;
#&gt; data:  pre_post$weight_after and pre_post$weight_before
#&gt; t = -11.84, df = 19, p-value = 3.1e-10
#&gt; alternative hypothesis: true mean difference is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -2.310 -1.620
#&gt; sample estimates:
#&gt; mean difference
#&gt;          -1.965</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- t.test(
  pre_post$weight_after,
  pre_post$weight_before,
  paired = TRUE
)
ex_2_2$p.value
#&gt; [1] 3.1e-10</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Paired t-tests treat the 20 differences as a one-sample test against zero, so within-subject correlation is removed and <a class="auto-link" href="Sample-Size-Planning-in-R.html" title="Sample Size in R: Calculate Your N Before You Collect a Single Observation">statistical power</a> jumps compared to a two-sample t-test on the same data. The mean difference of -1.97 kg is small in absolute terms but consistent enough across subjects that the test rejects at p well below 0.001. Forgetting <code>paired = TRUE</code> here would still give a directionally correct estimate but with a much larger p-value because between-subject baseline variance is reintroduced.</p>

</details>

<h3>Exercise 2.3: Compare Welch vs equal-variance Student t-test on the same data</h3>

<p><strong>Task:</strong> A statistics reviewer wants you to demonstrate when the Welch correction matters. Take the setosa vs versicolor data from Exercise 2.1, run both <code>var.equal = FALSE</code> (Welch, the default) and <code>var.equal = TRUE</code> (Student) t-tests, and save a 2-row tibble of degrees of freedom and p-values to <code>ex_2_3</code>. Comment in your explanation on when the difference matters.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 2 x 3
#&gt;   variant      df p_value
#&gt;   &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1 welch      86.5 8.99e-27
#&gt; 2 student    98.0 3.75e-28</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">two_species &lt;- iris %&gt;%
  filter(Species %in% c(&quot;setosa&quot;, &quot;versicolor&quot;)) %&gt;%
  mutate(Species = droplevels(Species))

w &lt;- t.test(Sepal.Length ~ Species, data = two_species, var.equal = FALSE)
s &lt;- t.test(Sepal.Length ~ Species, data = two_species, var.equal = TRUE)

ex_2_3 &lt;- tibble::tibble(
  variant = c(&quot;welch&quot;, &quot;student&quot;),
  df = c(unname(w$parameter), unname(s$parameter)),
  p_value = c(w$p.value, s$p.value)
)
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Welch's correction lowers degrees of freedom whenever the sample variances differ, which widens the t distribution's tails and raises the p-value. With equal sample sizes and similar variances the two tests are nearly identical, but with unequal sizes AND unequal variances they diverge sharply. Welch should be your default: it only loses a tiny bit of power when variances really are equal but stays valid when they are not. The Student version is a relic worth knowing only because legacy code uses it.</p>

</details>

<h3>Exercise 2.4: F-test for equal variances across mtcars cylinder groups</h3>

<p><strong>Task:</strong> Before defending the equal-variance assumption you need evidence. Subset <code>mtcars</code> to 4-cylinder and 8-cylinder cars, run <code>var.test()</code> to compare the variances of <code>mpg</code> between those two groups, and save the test object to <code>ex_2_4</code>. Report whether the test rejects equal variances at alpha 0.05 and what that implies for choosing Welch vs Student.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  F test to compare two variances
#&gt;
#&gt; data:  mpg by cyl
#&gt; F = 4.3865, num df = 10, denom df = 13, p-value = 0.01415
#&gt; alternative hypothesis: true ratio of variances is not equal to 1
#&gt; 95 percent confidence interval:
#&gt;   1.357918 15.473052
#&gt; sample estimates:
#&gt; ratio of variances
#&gt;            4.38651</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">sub_mt &lt;- mtcars %&gt;% filter(cyl %in% c(4, 8))
ex_2_4 &lt;- var.test(mpg ~ cyl, data = sub_mt)
ex_2_4$p.value
#&gt; [1] 0.01415</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>var.test()</code> runs an F-test on the ratio of two sample variances against H0: ratio = 1. Here the variance of 4-cyl mpg is roughly 4.4 times that of 8-cyl mpg, and p = 0.014 rejects equal variances. That is exactly the situation where Welch matters: forcing <code>var.equal = TRUE</code> on a Student t-test would inflate Type I error. F-tests are highly sensitive to non-normality though, so for serious work use <a class="auto-link" href="Normality-and-Variance-Tests-in-R.html" title="Test Normality and Equal Variance in R: What the Tests Can and Can't Tell You">Levene's test</a> from <code>car::leveneTest()</code> (or Brown-Forsythe) which is more robust to skewed data.</p>

</details>

<h3>Exercise 2.5: Two-sample t-test from summary statistics only</h3>

<p><strong>Task:</strong> A meta-analyst with only published <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summary statistics</a> (means, sds, and sample sizes for two groups) needs to reproduce a Welch t-test without the raw data. Given group A (mean=50.2, sd=8.1, n=30) and group B (mean=46.8, sd=9.4, n=35), compute the Welch t statistic, the Welch degrees of freedom, and the two-sided p-value using base R formulas. Save a named numeric vector to <code>ex_2_5</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;      t        df p_value
#&gt; 1.5640   62.7610  0.1229</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_5 &lt;- # your code here
ex_2_5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">m1 &lt;- 50.2; s1 &lt;- 8.1; n1 &lt;- 30
m2 &lt;- 46.8; s2 &lt;- 9.4; n2 &lt;- 35

se &lt;- sqrt(s1^2 / n1 + s2^2 / n2)
t_stat &lt;- (m1 - m2) / se
df_welch &lt;- (s1^2/n1 + s2^2/n2)^2 /
  ((s1^2/n1)^2 / (n1 - 1) + (s2^2/n2)^2 / (n2 - 1))
p_value &lt;- 2 * pt(-abs(t_stat), df = df_welch)

ex_2_5 &lt;- round(c(t = t_stat, df = df_welch, p_value = p_value), 4)
ex_2_5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Welch t = (m1 - m2) / sqrt(s1^2/n1 + s2^2/n2), and the Welch-Satterthwaite degrees of freedom blend the two within-group variance estimates into a single non-integer df. The two-sided p-value is <code>2 * pt(-abs(t), df)</code>. This pattern is essential for meta-analysis, replication checks, and recomputing tests when only summary tables exist. The <code>BSDA::tsum.test()</code> function wraps the same math if you want a one-line version.</p>

</details>

<h2>Section 3. Proportions and counts (4 problems)</h2>

<h3>Exercise 3.1: One-proportion z-test on a coin flip experiment</h3>

<p><strong>Task:</strong> Test whether a coin showing 540 heads in 1000 flips deviates from fairness using <code>prop.test()</code> with <code>correct = FALSE</code> so the output matches a textbook <a class="auto-link" href="Proportion-Tests-in-R.html" title="Proportion Tests in R: prop.test(), binom.test(), When to Use Each">one-proportion z-test</a>. Use the default two-sided alternative and 95% confidence level. Save the test object to <code>ex_3_1</code> and report the p-value.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  1-sample proportions test without continuity correction
#&gt;
#&gt; data:  540 out of 1000, null probability 0.5
#&gt; X-squared = 6.4, df = 1, p-value = 0.01141
#&gt; alternative hypothesis: true p is not equal to 0.5
#&gt; 95 percent confidence interval:
#&gt;  0.5090 0.5705
#&gt; sample estimates:
#&gt;    p
#&gt; 0.54</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- prop.test(
  x = 540,
  n = 1000,
  p = 0.5,
  correct = FALSE
)
ex_3_1$p.value
#&gt; [1] 0.01141204</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>prop.test()</code> runs a score test based on the normal approximation. The X-squared statistic equals the square of the z statistic; 6.4 corresponds to z = 2.53 and a two-sided p-value of 0.011. Setting <code>correct = FALSE</code> skips Yates' continuity correction so the output lines up with the closed-form formula z = (p_hat - p0) / sqrt(p0 * (1 - p0) / n). For small n use <code>binom.test()</code> (exact binomial); for very small n the Wilson interval from <code>prop.test()</code> still works well.</p>

</details>

<h3>Exercise 3.2: Two-proportion test on A/B clickthrough rates</h3>

<p><strong>Task:</strong> A growth team runs an A/B test on a button color change. Variant A receives 12,400 impressions and 412 clicks; variant B receives 12,180 impressions and 489 clicks. Run a two-proportion test with <code>prop.test()</code> to evaluate whether the difference is statistically significant at alpha 0.05. Save the test object to <code>ex_3_2</code> and report the conclusion.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  2-sample test for equality of proportions with continuity correction
#&gt;
#&gt; data:  c(412, 489) out of c(12400, 12180)
#&gt; X-squared = 7.39, df = 1, p-value = 0.006547
#&gt; alternative hypothesis: two.sided
#&gt; 95 percent confidence interval:
#&gt;  -0.0124 -0.0021
#&gt; sample estimates:
#&gt;    prop 1    prop 2
#&gt; 0.03323   0.04014</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- prop.test(
  x = c(412, 489),
  n = c(12400, 12180)
)
ex_3_2$p.value
#&gt; [1] 0.006547</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Both <code>x</code> and <code>n</code> accept length-2 vectors and <code>prop.test()</code> computes the absolute risk difference (p1 - p2) along with its 95% CI. p = 0.0065 rejects equal proportions, and the CI \[-0.012, -0.002\] indicates B beats A by 0.2 to 1.2 percentage points. For relative effects (lift), divide the rates yourself; <code>prop.test()</code> always works on the absolute difference. Tools like <code>rstatix::pairwise_prop_test()</code> or <code>infer::prop_test()</code> make this composable inside a tidy pipeline.</p>

</details>

<h3>Exercise 3.3: Chi-square test of independence on smoking by gender</h3>

<p><strong>Task:</strong> An epidemiologist needs to test whether smoking status is independent of gender in a small cohort. Build the inline 2x3 <a class="auto-link" href="R-Mosaic-Plots.html" title="R Mosaic Plots: Visualize Categorical Variable Relationships">contingency table</a> below, run <code>chisq.test()</code> to test the null of independence, and save the test object to <code>ex_3_3</code>. Report the X-squared statistic, degrees of freedom, and p-value.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">smoke &lt;- matrix(
  c(120, 80, 50,
     90, 110, 70),
  nrow = 2, byrow = TRUE,
  dimnames = list(
    gender = c(&quot;male&quot;, &quot;female&quot;),
    status = c(&quot;never&quot;, &quot;former&quot;, &quot;current&quot;)
  )
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Pearson's Chi-squared test
#&gt;
#&gt; data:  smoke
#&gt; X-squared = 11.37, df = 2, p-value = 0.003394</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- chisq.test(smoke)
ex_3_3
#&gt;
#&gt;  Pearson's Chi-squared test
#&gt;
#&gt; data:  smoke
#&gt; X-squared = 11.37, df = 2, p-value = 0.003394</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>chisq.test()</code> on a matrix computes the Pearson chi-squared statistic comparing observed counts to those expected under independence. Degrees of freedom equal <code>(rows - 1) * (cols - 1)</code>, here 1 * 2 = 2. With p = 0.003 you reject independence and conclude smoking status varies with gender in this sample. When any expected cell drops below 5, R warns and you should switch to <code>fisher.test()</code>. Inspect <code>ex_3_3$residuals</code> to see WHICH cells drive the rejection: the largest absolute standardised residuals are the cells most out of line with the independence model.</p>

</details>

<h3>Exercise 3.4: Chi-square goodness-of-fit on a six-sided die</h3>

<p><strong>Task:</strong> You roll a suspected six-sided die 600 times and observe the counts c(95, 110, 88, 102, 115, 90). Test whether the die is fair (each face probability 1/6) using a <a class="auto-link" href="Chi-Square-Goodness-of-Fit-Test-in-R.html" title="Chi-Square Goodness-of-Fit Test in R: Does Your Data Fit a Distribution?">chi-square goodness-of-fit test</a> via <code>chisq.test(x, p = ...)</code>. Save the test object to <code>ex_3_4</code> and report your conclusion at alpha 0.05.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Chi-squared test for given probabilities
#&gt;
#&gt; data:  rolls
#&gt; X-squared = 5.34, df = 5, p-value = 0.376</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
ex_3_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">rolls &lt;- c(95, 110, 88, 102, 115, 90)
ex_3_4 &lt;- chisq.test(rolls, p = rep(1/6, 6))
ex_3_4
#&gt;
#&gt;  Chi-squared test for given probabilities
#&gt;
#&gt; data:  rolls
#&gt; X-squared = 5.34, df = 5, p-value = 0.376</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Goodness-of-fit uses a single vector of observed counts and a vector of expected probabilities. df = number of categories minus 1 (here 6 - 1 = 5). With p = 0.376 you fail to reject fairness: the observed counts are well within sampling noise for a fair die. Note that "fail to reject" is NOT "the die is fair"; you simply lack evidence to claim it is biased. A sample of 6,000 rolls instead of 600 would give a much sharper test if you wanted to rule out a 1-2 percent bias.</p>

</details>

<h2>Section 4. Non-parametric alternatives (4 problems)</h2>

<h3>Exercise 4.1: Wilcoxon signed-rank test on paired pre/post pain scores</h3>

<p><strong>Task:</strong> A physical therapist measures pain on a 0-10 ordinal scale before and after a 6-week treatment in 15 patients. Build the inline tibble below, run a <a class="auto-link" href="Wilcoxon-Signed-Rank-Test-in-R.html" title="Wilcoxon Signed-Rank Test in R: Paired Data Without Normality">Wilcoxon signed-rank test</a> on <code>after</code> vs <code>before</code> with <code>paired = TRUE</code>, and save the test object to <code>ex_4_1</code>. Note why this is the right test for ordinal pain scores.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pain &lt;- tibble::tibble(
  patient = 1:15,
  before  = c(7, 8, 6, 9, 7, 5, 8, 6, 7, 9, 8, 6, 7, 8, 7),
  after   = c(4, 5, 5, 6, 4, 4, 5, 4, 5, 7, 6, 4, 5, 6, 5)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Wilcoxon signed rank test with continuity correction
#&gt;
#&gt; data:  pain$after and pain$before
#&gt; V = 0, p-value = 0.0006619
#&gt; alternative hypothesis: true location shift is not equal to 0</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- wilcox.test(
  pain$after,
  pain$before,
  paired = TRUE
)
ex_4_1$p.value
#&gt; [1] 0.0006619</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A paired Wilcoxon ranks the absolute differences and tests whether positive and negative ranks balance under H0. It is the right choice for ordinal data like a pain scale where the interval between 5 and 6 is not guaranteed to equal the interval between 8 and 9. Here V = 0 means every difference moved the same direction (pain dropped for every patient), which yields p = 0.0007 and a clear rejection. A paired t-test on the same data would also reject, but its assumption of normally distributed differences is shaky on ordinal scales.</p>

</details>

<h3>Exercise 4.2: Mann-Whitney U on two independent groups</h3>

<p><strong>Task:</strong> Run <code>wilcox.test()</code> on <code>airquality$Ozone</code> split by whether <code>Month</code> is 5 (May) or 8 (August). Drop NA rows in the relevant columns first. The two distributions are skewed, so Mann-Whitney is more appropriate than a Welch t-test. Save the test object to <code>ex_4_2</code> and report the p-value.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Wilcoxon rank sum test with continuity correction
#&gt;
#&gt; data:  Ozone by month_label
#&gt; W = 127.5, p-value = 0.0001208
#&gt; alternative hypothesis: true location shift is not equal to 0</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">aq &lt;- airquality %&gt;%
  filter(Month %in% c(5, 8), !is.na(Ozone)) %&gt;%
  mutate(month_label = factor(Month, labels = c(&quot;May&quot;, &quot;Aug&quot;)))

ex_4_2 &lt;- wilcox.test(Ozone ~ month_label, data = aq)
ex_4_2$p.value
#&gt; [1] 0.00012</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The independent-samples Wilcoxon (also called Mann-Whitney U) ranks all observations together and asks whether ranks in group A tend to be larger or smaller than ranks in group B. It is invariant to monotone transforms of the response, so log-transforming ozone would give the same p-value. With p = 0.00012 you reject equal distributions: August ozone is reliably higher than May ozone. Note that "location shift" in R's output is a special case; the test rejects more broadly any shift in stochastic dominance.</p>

</details>

<h3>Exercise 4.3: Kruskal-Wallis across three or more groups</h3>

<p><strong>Task:</strong> Use <code>PlantGrowth</code> (groups: ctrl, trt1, trt2) and run a <a class="auto-link" href="Wilcoxon-Mann-Whitney-and-Kruskal-Wallis-in-R.html" title="Wilcoxon, Mann-Whitney, and Kruskal-Wallis in R: Non-Parametric When Normality Fails">Kruskal-Wallis test</a> on <code>weight</code> by <code>group</code>. This is the non-parametric alternative to a one-way ANOVA and you should reach for it when group sizes are small or residuals look non-normal. Save the test object to <code>ex_4_3</code> and decide whether at least one group differs.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;  Kruskal-Wallis rank sum test
#&gt;
#&gt; data:  weight by group
#&gt; Kruskal-Wallis chi-squared = 7.99, df = 2, p-value = 0.01842</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- kruskal.test(weight ~ group, data = PlantGrowth)
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Kruskal-Wallis generalises Mann-Whitney to k > 2 groups by ranking all observations and comparing rank sums. df = k - 1 = 2 here. With p = 0.018 the test rejects "all groups identical" but does NOT tell you which pair is different; follow up with <code>pairwise.wilcox.test(PlantGrowth$weight, PlantGrowth$group, p.adjust.method = &quot;BH&quot;)</code> to get adjusted <a class="auto-link" href="Post-Hoc-Tests-After-ANOVA.html" title="ANOVA Post-Hoc Tests in R: Tukey, Bonferroni, and Scheffé, Clear Decision Rules">pairwise comparisons</a>. For parametric data prefer one-way ANOVA via <code>aov()</code>; Kruskal-Wallis is the safe fallback when the residual diagnostics fail.</p>

</details>

<h3>Exercise 4.4: Bootstrap CI for the mean of a small skewed sample</h3>

<p><strong>Task:</strong> A junior analyst is uncomfortable trusting the t-distribution on a sample of 25 reaction times that look right-skewed. Build the inline vector below, draw 10,000 bootstrap resamples (with replacement) of the mean, and compute the 2.5% and 97.5% percentiles. Save a length-3 named vector with <code>mean_obs</code>, <code>ci_lo</code>, <code>ci_hi</code> to <code>ex_4_4</code> and compare against <code>t.test()</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
rt &lt;- rgamma(25, shape = 2, rate = 0.02)   # right-skewed reaction times</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; mean_obs    ci_lo    ci_hi
#&gt;   92.500   67.300  120.400</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_4 &lt;- # your code here
ex_4_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(123)
boot_means &lt;- replicate(
  10000,
  mean(sample(rt, length(rt), replace = TRUE))
)

ex_4_4 &lt;- c(
  mean_obs = mean(rt),
  ci_lo = unname(quantile(boot_means, 0.025)),
  ci_hi = unname(quantile(boot_means, 0.975))
)
ex_4_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The <a class="auto-link" href="Bootstrap-Confidence-Intervals-in-R.html" title="Bootstrap CIs in R: Distribution-Free Confidence Intervals for Any Statistic">percentile bootstrap</a> constructs a confidence interval by resampling the data, recomputing the statistic 10,000 times, and taking the 2.5/97.5 percentiles of the resulting distribution. It makes no assumption that the <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">sampling distribution of the mean</a> is symmetric, so on skewed data it produces an asymmetric CI that better reflects reality. <code>t.test(rt)$conf.int</code> on the same data forces symmetry around the sample mean and can over- or undercover. For more rigorous bootstrap CIs (BCa, studentized) use <code>boot::boot()</code> plus <code>boot::boot.ci()</code>.</p>

</details>

<h2>Section 5. Errors, power, and effect size (4 problems)</h2>

<h3>Exercise 5.1: Simulate the empirical Type I error rate under H0</h3>

<p><strong>Task:</strong> Generate 5,000 independent samples of size 30 from a standard normal (so H0 is true), run a two-sided one-sample t-test against <code>mu = 0</code> on each sample, and count the fraction with p-value below 0.05. Save the resulting empirical Type I error rate to <code>ex_5_1</code>. It should land near 0.05 since H0 holds.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.0494</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(2026)
p_values &lt;- replicate(5000, {
  x &lt;- rnorm(30)
  t.test(x, mu = 0)$p.value
})

ex_5_1 &lt;- mean(p_values &lt; 0.05)
ex_5_1
#&gt; [1] 0.0494</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> When H0 is true the p-value is uniformly distributed on \[0, 1\], so the fraction below alpha = 0.05 should equal alpha. With 5,000 simulations the Monte Carlo standard error is sqrt(0.05 * 0.95 / 5000) ~= 0.003, so any value in roughly \[0.045, 0.055\] is consistent with calibrated nominal error. Running this once gives intuition for why "p < 0.05" is a statement about long-run frequency, not about any individual experiment. Bump n_sim to 100,000 to nail down the third decimal.</p>

</details>

<h3>Exercise 5.2: Cohen's d for a two-sample comparison</h3>

<p><strong>Task:</strong> Compute Cohen's d (the standardised mean difference using the pooled standard deviation) for <code>iris$Sepal.Length</code> between setosa and versicolor. Use the textbook pooled-SD formula in base R; do not call <code>effsize::cohen.d</code>. Save the single numeric to <code>ex_5_2</code>. Interpret the magnitude using Cohen's conventional cutoffs (small 0.2, medium 0.5, large 0.8).</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] -2.10</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">setosa     &lt;- iris$Sepal.Length[iris$Species == &quot;setosa&quot;]
versicolor &lt;- iris$Sepal.Length[iris$Species == &quot;versicolor&quot;]

n1 &lt;- length(setosa); n2 &lt;- length(versicolor)
sp_sq &lt;- ((n1 - 1) * var(setosa) + (n2 - 1) * var(versicolor)) / (n1 + n2 - 2)
ex_5_2 &lt;- (mean(setosa) - mean(versicolor)) / sqrt(sp_sq)
round(ex_5_2, 2)
#&gt; [1] -2.10</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Cohen's d expresses the group mean difference in units of pooled standard deviation, so it is comparable across studies regardless of the original measurement scale. |d| = 2.10 is huge: setosa sepals are about two standard deviations shorter than versicolor sepals on average. A p-value tells you the difference is unlikely to be zero; d tells you HOW BIG the difference is. Always report both. For paired designs use the SD of the differences instead of the pooled SD (Cohen's dz).</p>

</details>

<h3>Exercise 5.3: Required sample size for 80% power with pwr.t.test</h3>

<p><strong>Task:</strong> A trial designer wants to detect a Cohen's d of 0.5 in a two-sample (independent groups) study at alpha 0.05 with 80% power. Use <code>pwr::pwr.t.test()</code> with <code>type = &quot;two.sample&quot;</code> to compute the required sample size per group. Save the whole pwr object to <code>ex_5_3</code> and read off the <code>n</code> element. Comment on what happens if d drops to 0.3.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;
#&gt;      Two-sample t test power calculation
#&gt;
#&gt;               n = 63.766
#&gt;               d = 0.5
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt;     alternative = two.sided
#&gt;
#&gt; NOTE: n is number in *each* group</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- pwr.t.test(
  d = 0.5,
  sig.level = 0.05,
  power = 0.8,
  type = &quot;two.sample&quot;,
  alternative = &quot;two.sided&quot;
)
ceiling(ex_5_3$n)
#&gt; [1] 64</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Power analysis trades off five quantities: effect size d, alpha, power (1 - beta), sample size n, and the test type. Fix any four and <code>pwr.t.test()</code> solves for the fifth (use <code>NULL</code> for the unknown). Detecting d = 0.5 needs about 64 per group; halving the effect to d = 0.25 quadruples the required n to roughly 252 per group, because power scales with n through d * sqrt(n). Always run power analysis BEFORE collecting data; running it after non-significant results to "explain" the null is <a class="auto-link" href="Statistical-Power-Analysis-in-R.html" title="Power Analysis in R: Calculate the Sample Size You Need Before You Collect Any Data">post-hoc power</a> and is statistically meaningless.</p>

</details>

<h3>Exercise 5.4: Power curve across a grid of effect sizes</h3>

<p><strong>Task:</strong> Hold n = 30 per group and alpha = 0.05 fixed. Across <code>d</code> values from 0.1 to 1.0 in steps of 0.1, compute the power of a two-sided two-sample t-test using <code>pwr::pwr.t.test()</code>. Save a tibble with columns <code>d</code> and <code>power</code> to <code>ex_5_4</code>, then plot it as a power curve (ggplot, line + points).</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 10 x 2
#&gt;      d  power
#&gt;   &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1  0.1 0.072
#&gt; 2  0.2 0.139
#&gt; ...
#&gt; # 8 more rows</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_4 &lt;- # your code here
ex_5_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_4 &lt;- tibble::tibble(d = seq(0.1, 1.0, by = 0.1)) %&gt;%
  mutate(power = purrr::map_dbl(
    d,
    ~ pwr.t.test(d = .x, n = 30, sig.level = 0.05,
                  type = &quot;two.sample&quot;)$power
  ))

ggplot(ex_5_4, aes(d, power)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0.8, linetype = &quot;dashed&quot;) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = &quot;Power vs effect size (n=30 per group)&quot;,
       x = &quot;Cohen's d&quot;, y = &quot;Power&quot;)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A power curve makes the n/d/power trade-off visible: with only 30 per group, you need a Cohen's d above ~0.74 to hit the conventional 80% power target. Below d = 0.4 you have less than a coin-flip chance of detecting a real effect, so a non-significant result tells you nothing. Power curves are essential when negotiating study scope with stakeholders ("we can detect d >= 0.5 with 80% power, anything smaller you need a bigger sample"). For three-arm trials use <code>pwr::pwr.anova.test()</code> instead.</p>

</details>

<h2>Section 6. Real-world workflows (4 problems)</h2>

<h3>Exercise 6.1: Multiple-testing correction across 20 hypothesis tests</h3>

<p><strong>Task:</strong> A bioinformatician runs 20 independent two-sample tests and gets the raw p-values below. Apply both Bonferroni and Benjamini-Hochberg (FDR) correction via <code>p.adjust()</code> and save a tibble with columns <code>raw</code>, <code>bonferroni</code>, <code>bh</code> to <code>ex_6_1</code>. Comment on how many tests are "significant" at alpha 0.05 under each method.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">raw_p &lt;- c(0.0001, 0.0008, 0.003, 0.012, 0.018, 0.022, 0.035, 0.041, 0.049, 0.060,
           0.071, 0.085, 0.120, 0.180, 0.220, 0.330, 0.450, 0.610, 0.780, 0.910)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 20 x 3
#&gt;      raw bonferroni     bh
#&gt;    &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 0.0001     0.0020 0.0020
#&gt; 2 0.0008     0.0160 0.0080
#&gt; 3 0.0030     0.0600 0.0200
#&gt; 4 0.0120     0.2400 0.0540
#&gt; ...
#&gt; # 16 more rows</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- tibble::tibble(
  raw = raw_p,
  bonferroni = p.adjust(raw_p, method = &quot;bonferroni&quot;),
  bh = p.adjust(raw_p, method = &quot;BH&quot;)
)
ex_6_1 %&gt;%
  summarise(
    sig_raw  = sum(raw &lt; 0.05),
    sig_bonf = sum(bonferroni &lt; 0.05),
    sig_bh   = sum(bh &lt; 0.05)
  )
#&gt; sig_raw sig_bonf sig_bh
#&gt;       9        2      3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Bonferroni controls the <a class="auto-link" href="Multiple-Comparisons-in-R.html" title="Multiple Testing in R: Control False Discoveries Without Losing All Your Power">family-wise error rate</a> by multiplying each p-value by the number of tests; it is the strictest method and rarely calls anything significant in high-dimensional settings. Benjamini-Hochberg controls the false discovery rate (the expected fraction of false positives AMONG rejected hypotheses), which gives more power at the cost of allowing some false positives. For genome-wide screens BH (or Storey's q-value) is the standard; for confirmatory clinical analyses Bonferroni or Holm is the default.</p>

</details>

<h3>Exercise 6.2: Run a t-test per group and tidy the results</h3>

<p><strong>Task:</strong> Using <code>mtcars</code>, split cars by <code>am</code> (0 = automatic, 1 = manual) and run a Welch t-test on <code>mpg</code> vs <code>am</code> separately within each <code>cyl</code> group (4, 6, 8). Use <code>dplyr::group_by()</code> + <code>dplyr::reframe()</code> + <code>broom::tidy()</code> (or equivalent) to produce a tibble with one row per cylinder containing the estimate, statistic, and p-value. Save to <code>ex_6_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 4
#&gt;     cyl estimate statistic p.value
#&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1     4    -5.18    -2.32   0.0418
#&gt; 2     6    -0.343   -0.207  0.846
#&gt; 3     8    -0.300   -0.247  0.811</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- mtcars %&gt;%
  group_by(cyl) %&gt;%
  reframe(broom::tidy(t.test(mpg ~ am))) %&gt;%
  select(cyl, estimate, statistic, p.value)
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>broom::tidy()</code> converts the wall-of-text <code>htest</code> print output into a clean 1-row tibble per test, which makes group-wise testing composable. With <code>group_by()</code> + <code>reframe()</code> you fan out one t-test per cyl group and stack the results vertically. This pattern is the foundation of every "tests by subgroup" report in production analytics. Beware multiple testing here: three p-values means you should bump alpha down via <code>p.adjust(ex_6_2$p.value, method = &quot;BH&quot;)</code> if you want to interpret each independently.</p>

</details>

<h3>Exercise 6.3: Permutation test for the difference in two means</h3>

<p><strong>Task:</strong> A junior researcher needs a distribution-free check on whether <code>sleep$extra</code> differs between the two <code>group</code> levels. Compute the observed difference in means, then build a null distribution by permuting the group labels 10,000 times and recomputing the difference. Save a length-2 named numeric with <code>obs_diff</code> and <code>p_value</code> (two-sided) to <code>ex_6_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; obs_diff   p_value
#&gt;  -1.580     0.078</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(2026)
extra &lt;- sleep$extra
grp &lt;- sleep$group

obs_diff &lt;- mean(extra[grp == 1]) - mean(extra[grp == 2])
perm_diffs &lt;- replicate(10000, {
  shuffled &lt;- sample(grp)
  mean(extra[shuffled == 1]) - mean(extra[shuffled == 2])
})

p_value &lt;- mean(abs(perm_diffs) &gt;= abs(obs_diff))
ex_6_3 &lt;- c(obs_diff = obs_diff, p_value = p_value)
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A <a class="auto-link" href="Permutation-Tests-in-R.html" title="Permutation Tests in R: Exact p-Values via Randomization">permutation test</a> simulates the exact null distribution by reassigning group labels at random: under H0 the labels are exchangeable, so any reassignment is equally likely. The two-sided p-value is the fraction of permuted differences as extreme as or more extreme than the observed one. It makes NO distributional assumption on the data; the cost is computational. For the 20-observation <code>sleep</code> dataset the permutation p-value lines up with the paired t-test p-value of about 0.076, but for skewed or heavy-tailed data they diverge.</p>

</details>

<h3>Exercise 6.4: Equivalence test (TOST) for "no meaningful difference"</h3>

<p><strong>Task:</strong> A regulatory analyst needs to prove two manufacturing lines produce equivalent mean fill volumes. Build the inline tibble below, define an equivalence margin of plus or minus 0.5 ml, and run two one-sided t-tests (TOST): one for <code>mu = -0.5</code> with <code>alternative = &quot;greater&quot;</code> and one for <code>mu = 0.5</code> with <code>alternative = &quot;less&quot;</code>. Save a length-3 named vector <code>p_lower</code>, <code>p_upper</code>, <code>p_tost</code> (the larger of the two) to <code>ex_6_4</code>. Equivalence is claimed if <code>p_tost &lt; 0.05</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fill &lt;- tibble::tibble(
  line_a = c(50.1, 49.9, 50.3, 50.2, 49.8, 50.0, 50.1, 49.9, 50.2, 50.0,
             50.1, 49.8, 50.2, 50.0, 49.9, 50.1, 50.3, 49.8, 50.0, 50.2),
  line_b = c(50.0, 50.2, 49.9, 50.1, 50.0, 49.8, 50.2, 50.1, 49.9, 50.0,
             50.1, 50.0, 49.8, 50.2, 50.1, 49.9, 50.0, 50.1, 50.2, 49.9)
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;  p_lower  p_upper   p_tost
#&gt; 1.5e-09  3.5e-09  3.5e-09</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_4 &lt;- # your code here
ex_6_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">diffs &lt;- fill$line_a - fill$line_b
delta &lt;- 0.5

t_lower &lt;- t.test(diffs, mu = -delta, alternative = &quot;greater&quot;)
t_upper &lt;- t.test(diffs, mu =  delta, alternative = &quot;less&quot;)

ex_6_4 &lt;- c(
  p_lower = t_lower$p.value,
  p_upper = t_upper$p.value,
  p_tost  = max(t_lower$p.value, t_upper$p.value)
)
ex_6_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The two one-sided tests (TOST) procedure flips the classical question. Instead of asking "is the difference different from zero?", you ask "is the difference inside the practically-equivalent interval \[-delta, +delta\]?". You reject non-equivalence only if BOTH one-sided tests reject, so the relevant p-value is the larger of the two. A non-significant standard t-test does NOT establish equivalence; only TOST does. Packages like <code>TOSTER::tsum_TOST()</code> automate this for both raw and standardised effect sizes.</p>

</details>

<h2>What to do next</h2>

<p>You have just run through the inference workflow R analysts use every day. To consolidate and extend:</p>

<ul>

<li>Read <a href="Hypothesis-Testing-in-R.html">Hypothesis Testing in R</a> for the conceptual map that ties t-tests, chi-square, and non-parametric alternatives together.</li>

<li>Sharpen your distribution sense with <a href="Probability-Distributions-Exercises-in-R.html">Probability Distributions Exercises in R</a>, which drills <code>dnorm</code>, <code>pnorm</code>, <code>qnorm</code>, and friends.</li>

<li>Move from group means to group structures with <a href="ANOVA-Exercises-in-R.html">ANOVA Exercises in R</a> for k-group and factorial designs.</li>

<li>Translate inference into prediction with <a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>, where the same t-statistics reappear on coefficient rows.</li>

</ul>

{% endraw %}