---
title: "leaflet Exercises in R: 20 Real-World Map Problems"
description: "20 leaflet R exercises: markers, popups, choropleth, heatmaps, layer control, dashboards. Hidden solutions, embedded business context, real workflows."
keywords: "leaflet R exercises, leaflet practice R, R interactive map exercises, choropleth R, leaflet markers R, leaflet popup R, leaflet heatmap R"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "leaflet R exercises|leaflet practice R|R interactive map exercises|choropleth R|leaflet popup R|leaflet heatmap R"
auto_link_case_sensitive: false
sidebar_title: "leaflet Exercises"
sidebar_order: "151"
fr_parent: "R-Tutorial.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>leaflet Exercises in R: 20 Real-World Map Problems</h1>
<p class="lead">Twenty hands-on leaflet exercises grouped by skill: base maps, markers and popups, polygons and choropleths, color palettes and legends, layer controls, and full ops-team dashboards. Every problem is framed around a real ask from analysts, dispatchers, and city planners. Solutions are hidden behind a click so you can attempt each one first.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="20" data-time="55" data-xp="300"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(leaflet)
library(leaflet.extras)
library(dplyr)
library(tibble)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Base maps and tile providers (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="leaflet-Exercises-in-R-ex-1-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 1.1: Render a default OpenStreetMap base layer</h3>
<p class="exercise-task"><strong>Task:</strong> A new analyst onboarding to a logistics tool needs a baseline map to confirm the leaflet stack is wired up. Initialize a leaflet widget and add the default OpenStreetMap tiles so the analyst sees a world map at the lowest zoom. Save the result to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - one base tile layer: OpenStreetMap default
#&gt;   - view: world extent, default zoom 1, center (0, 0)
#&gt;   - no markers, polygons, or overlays</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>An empty map widget shows nothing until you attach a basemap; create the widget first, then give it a tile layer.</p><p>Pipe <code>leaflet()</code> into <code>addTiles()</code> called with no arguments to get the default OpenStreetMap tiles.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- leaflet() |&gt;
  addTiles()
ex_1_1
#&gt; A leaflet htmlwidget:
#&gt;   - one base tile layer: OpenStreetMap default
#&gt;   - view: world extent, default zoom 1, center (0, 0)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>leaflet()</code> returns an empty htmlwidget; tiles are not implied. <code>addTiles()</code> with no arguments calls the OpenStreetMap provider, which is the canonical free baseline. You will <a class="auto-link" href="R-Function-Operators.html" title="R Function Operators: Compose, Negate &amp; Partial Application">compose</a> every other layer (markers, polygons, choropleths) on top of this base. Skipping the tile layer leaves a blank grey canvas, which is a common first-time gotcha.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="leaflet-Exercises-in-R-ex-1-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 1.2: Center and zoom on a specific city for a courier briefing</h3>
<p class="exercise-task"><strong>Task:</strong> Dispatch wants the morning briefing centered on Manhattan at zoom 12 so the courier team sees neighborhood-level streets, not boroughs. Build a leaflet map centered on longitude <code>-74.0060</code> and latitude <code>40.7128</code> at zoom level 12 with default tiles. Save the result to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - tile layer: OpenStreetMap
#&gt;   - center: lng = -74.0060, lat = 40.7128 (Manhattan)
#&gt;   - zoom: 12 (neighborhood-level streets visible)</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A basemap on its own opens at world extent; you need one more step to pin both the center point and the zoom level.</p><p>After <code>addTiles()</code>, call <code>setView()</code> with <code>lng = -74.0060</code>, <code>lat = 40.7128</code>, and <code>zoom = 12</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- leaflet() |&gt;
  addTiles() |&gt;
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)
ex_1_2
#&gt; A leaflet htmlwidget centered on Manhattan at zoom 12</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>setView()</code> controls both the geographic center and the zoom level simultaneously. Zoom 12 is the sweet spot for urban dispatch: streets are labeled, but a whole borough still fits in view. Compare to <code>fitBounds()</code>, which auto-fits a bounding box and is preferred when you have a set of points whose extent you want shown. Use <code>setView()</code> when the focal point is fixed regardless of data.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="leaflet-Exercises-in-R-ex-1-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 1.3: Compare three tile providers for a real-estate listing page</h3>
<p class="exercise-task"><strong>Task:</strong> A real-estate marketing team is <a class="auto-link" href="AB-Testing-in-R.html" title="A/B Testing in R: Plan Your Sample Size, Analyse Correctly, and Know When to Stop">A/B testing</a> the base-map style on listing pages. Render three <a class="auto-link" href="Interactive-Maps-in-R-with-leaflet.html" title="Interactive Maps in R with leaflet: Markers, Popups, Tile Layers, and Heatmaps">leaflet maps</a> centered on San Francisco (lng <code>-122.42</code>, lat <code>37.77</code>, zoom 12) using OpenStreetMap, CartoDB <a class="auto-link" href="Positron-vs-RStudio.html" title="Positron vs RStudio in 2026: Should You Switch? A Feature-by-Feature Verdict">Positron</a>, and Esri WorldImagery. Save the three maps as a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> to <code>ex_1_3</code> with names <code>"osm"</code>, <code>"carto"</code>, and <code>"esri"</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>List of 3
 $ osm  :List of 8
  ..- attr(*, "class")= chr [1:2] "leaflet" "htmlwidget"
  ..- attr(*, "package")= chr "leaflet"
 $ carto:List of 8
  ..- attr(*, "class")= chr [1:2] "leaflet" "htmlwidget"
  ..- attr(*, "package")= chr "leaflet"
 $ esri :List of 8
  ..- attr(*, "class")= chr [1:2] "leaflet" "htmlwidget"
  ..- attr(*, "package")= chr "leaflet"
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Each map is built the same way but with a different basemap style; collect the three into a named container.</p><p>Use <code>addProviderTiles()</code> with <code>providers$CartoDB.Positron</code> and <code>providers$Esri.WorldImagery</code>, plain <code>addTiles()</code> for OSM, all inside a <code>list()</code> with names osm/carto/esri.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
str(ex_1_3, max.level = 1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">make_map &lt;- function(provider) {
  leaflet() |&gt;
    addProviderTiles(provider) |&gt;
    setView(lng = -122.42, lat = 37.77, zoom = 12)
}

ex_1_3 &lt;- list(
  osm   = leaflet() |&gt; addTiles() |&gt; setView(-122.42, 37.77, 12),
  carto = make_map(providers$CartoDB.Positron),
  esri  = make_map(providers$Esri.WorldImagery)
)
str(ex_1_3, max.level = 1)
#&gt; List of 3
#&gt;  $ osm  :List of 8
#&gt;  $ carto:List of 8
#&gt;  $ esri :List of 8</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>addProviderTiles()</code> switches to any of 200+ free tile providers exposed through the <code>providers</code> object. Positron is the de facto choice for analytics dashboards because its muted palette lets data colors pop. Esri WorldImagery is the satellite default. For commercial use, check provider terms: OpenStreetMap requires attribution, and some providers cap free tile requests per day.</p>
</details>
</section>
<h2>Section 2. Markers, popups, and labels (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="leaflet-Exercises-in-R-ex-2-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.1: Drop a single marker with a popup for a store opening</h3>
<p class="exercise-task"><strong>Task:</strong> A retail expansion lead is announcing the new Brooklyn flagship and wants a one-pin map for the press release. Add one marker at lng <code>-73.9442</code>, lat <code>40.6782</code> with a popup that reads <code>"Brooklyn Flagship Opening Sept 2026"</code>. Use OpenStreetMap tiles centered on the marker at zoom 13. Save to <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - tile layer: OpenStreetMap
#&gt;   - center: (-73.9442, 40.6782), zoom 13
#&gt;   - one marker with popup "Brooklyn Flagship Opening Sept 2026"</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Set up the basemap and view first, then drop a single point that carries a click message.</p><p>Call <code>addMarkers()</code> with <code>lng</code>, <code>lat</code>, and <code>popup = "Brooklyn Flagship Opening Sept 2026"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- leaflet() |&gt;
  addTiles() |&gt;
  setView(lng = -73.9442, lat = 40.6782, zoom = 13) |&gt;
  addMarkers(
    lng = -73.9442,
    lat = 40.6782,
    popup = "Brooklyn Flagship Opening Sept 2026"
  )
ex_2_1
#&gt; A leaflet htmlwidget with one marker and popup</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>addMarkers()</code> accepts either inline coordinates or a <code>data</code> frame with <code>lng</code>/<code>lat</code> columns. Popups appear on click; for hover behavior you would use <code>label = ...</code> instead. Popups support HTML by default, so something like <code>popup = "&lt;b&gt;Brooklyn&lt;/b&gt;&lt;br&gt;Sept 2026"</code> will render bold. For untrusted content always sanitize, or pass <code>popup = htmlEscape(text)</code> to avoid XSS through user-submitted strings.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-2-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.2: Plot multiple store locations from a data frame</h3>
<p class="exercise-task"><strong>Task:</strong> The retail ops team has a tibble of US flagship stores with <code>name</code>, <code>lng</code>, and <code>lat</code>. Plot all five stores as markers on a leaflet map with each popup showing the store name. Use OpenStreetMap tiles and let <code>fitBounds()</code> auto-zoom to show all five. Build the data inline first. Save the map to <code>ex_2_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - tile layer: OpenStreetMap
#&gt;   - 5 markers (NYC, Chicago, LA, Austin, Seattle)
#&gt;   - view auto-fit to bounding box of all 5
#&gt;   - each popup shows the store name on click</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Hand the table to the map up front so columns can be referenced by name, then let the view auto-frame to all points.</p><p>Pass <code>stores</code> to <code>leaflet()</code>, use <code>addMarkers(lng = ~lng, lat = ~lat, popup = ~name)</code>, then <code>fitBounds()</code> with the min and max of the lng and lat columns.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">stores &lt;- tibble::tribble(
  ~name,        ~lng,      ~lat,
  "NYC",        -74.0060,  40.7128,
  "Chicago",    -87.6298,  41.8781,
  "Los Angeles",-118.2437, 34.0522,
  "Austin",     -97.7431,  30.2672,
  "Seattle",    -122.3321, 47.6062
)

ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">stores &lt;- tibble::tribble(
  ~name,        ~lng,      ~lat,
  "NYC",        -74.0060,  40.7128,
  "Chicago",    -87.6298,  41.8781,
  "Los Angeles",-118.2437, 34.0522,
  "Austin",     -97.7431,  30.2672,
  "Seattle",    -122.3321, 47.6062
)

ex_2_2 &lt;- leaflet(stores) |&gt;
  addTiles() |&gt;
  addMarkers(lng = ~lng, lat = ~lat, popup = ~name) |&gt;
  fitBounds(
    lng1 = min(stores$lng), lat1 = min(stores$lat),
    lng2 = max(stores$lng), lat2 = max(stores$lat)
  )
ex_2_2
#&gt; A leaflet htmlwidget with 5 popup-labeled markers and auto-fit bounds</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Passing the data frame to <code>leaflet(data = stores)</code> lets you reference columns with formula notation (<code>~lng</code>, <code>~lat</code>, <code>~name</code>). This is far cleaner than passing vectors. <code>fitBounds()</code> auto-zooms to the smallest box that contains all points, which is exactly what you want for a multi-store overview. For a single-coast subset you would use <code>setView()</code> with a hardcoded center to keep the framing stable across updates.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-2-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.3: Use awesome icons to encode store status</h3>
<p class="exercise-task"><strong>Task:</strong> The retail ops dashboard needs to flag store status visually: <code>"open"</code> stores use a green storefront icon, <code>"closing_soon"</code> uses an orange clock, and <code>"closed"</code> uses a red ban icon. Use <code>awesomeIcons()</code> from the FontAwesome library. Build a tibble with three stores, one per status, then render them with status-driven icons. Save to <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Map each status category to a color and a glyph through lookup vectors, then build one vectorized icon definition.</p><p>Use <code>awesomeIcons()</code> with <code>library = "fa"</code> and named lookup vectors for <code>icon</code> and <code>markerColor</code>, then render with <code>addAwesomeMarkers(icon = icons)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">status_stores &lt;- tibble::tribble(
  ~name,          ~lng,      ~lat,    ~status,
  "Open Store",   -74.0060,  40.7128, "open",
  "Soon-To-Close",-87.6298,  41.8781, "closing_soon",
  "Closed Store", -97.7431,  30.2672, "closed"
)

ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">status_stores &lt;- tibble::tribble(
  ~name,          ~lng,      ~lat,    ~status,
  "Open Store",   -74.0060,  40.7128, "open",
  "Soon-To-Close",-87.6298,  41.8781, "closing_soon",
  "Closed Store", -97.7431,  30.2672, "closed"
)

icon_lookup &lt;- c(open = "store", closing_soon = "clock", closed = "ban")
color_lookup &lt;- c(open = "green", closing_soon = "orange", closed = "red")

icons &lt;- awesomeIcons(
  icon       = icon_lookup[status_stores$status],
  markerColor= color_lookup[status_stores$status],
  library    = "fa",
  iconColor  = "white"
)

ex_2_3 &lt;- leaflet(status_stores) |&gt;
  addTiles() |&gt;
  addAwesomeMarkers(lng = ~lng, lat = ~lat, icon = icons, popup = ~name)
ex_2_3
#&gt; A leaflet htmlwidget with 3 color-coded awesome-icon markers</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>awesomeIcons()</code> builds a vectorized icon definition; you pass parallel vectors for <code>icon</code>, <code>markerColor</code>, and <code>iconColor</code>. Named lookup vectors are the idiomatic way to map a categorical column to icon properties without nested <code>if_else()</code>. <code>library = "fa"</code> selects FontAwesome; alternatives are <code>"ion"</code>, <code>"glyphicon"</code>, <code>"mdi"</code>. Always pick icons that read clearly at the smallest zoom you support, since FA icons rasterize poorly below 16px.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-2-4" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.4: Cluster dense markers for a sales call list</h3>
<p class="exercise-task"><strong>Task:</strong> A regional sales rep loaded 80 prospect accounts inside the New York metro and the map is unreadable from the overlap. Use <code>clusterOptions = markerClusterOptions()</code> to collapse overlapping markers into expandable cluster bubbles. Generate the 80 points by sampling around NYC and render with <a class="auto-link" href="Clustering-with-R.html" title="Clustering with R">clustering</a>. Save to <code>ex_2_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - tile layer: OpenStreetMap
#&gt;   - 80 prospect markers clustered into ~6 expandable bubbles
#&gt;   - clicking a cluster zooms in and splits the bubble
#&gt;   - center: NYC, zoom 10</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>When points pile up in a small area, group them so overlapping pins collapse into expandable bubbles.</p><p>Pass <code>clusterOptions = markerClusterOptions()</code> to <code>addMarkers()</code>, and <code>setView()</code> on NYC at zoom 10.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
prospects &lt;- tibble::tibble(
  account_id = paste0("A", 1:80),
  lng        = rnorm(80, mean = -74.0060, sd = 0.15),
  lat        = rnorm(80, mean = 40.7128,  sd = 0.10)
)

ex_2_4 &lt;- # your code here
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
prospects &lt;- tibble::tibble(
  account_id = paste0("A", 1:80),
  lng        = rnorm(80, mean = -74.0060, sd = 0.15),
  lat        = rnorm(80, mean = 40.7128,  sd = 0.10)
)

ex_2_4 &lt;- leaflet(prospects) |&gt;
  addTiles() |&gt;
  setView(lng = -74.0060, lat = 40.7128, zoom = 10) |&gt;
  addMarkers(
    lng = ~lng, lat = ~lat, popup = ~account_id,
    clusterOptions = markerClusterOptions()
  )
ex_2_4
#&gt; A leaflet htmlwidget with clustered prospect markers</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>markerClusterOptions()</code> activates the MarkerCluster plugin, which bundles overlapping markers into a single bubble showing the count. Clicking the bubble zooms in and splits the cluster recursively. This is essential for any dataset over ~50 points in a small area, where individual markers stack and become useless. Tune visual density with <code>maxClusterRadius</code> and <code>disableClusteringAtZoom</code> to control when clusters dissolve into raw markers.</p>
</details>
</section>
<h2>Section 3. Shapes, lines, and polygons (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-3-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 3.1: Draw a delivery route as a polyline</h3>
<p class="exercise-task"><strong>Task:</strong> A last-mile dispatcher needs to visualize today's planned route between four Manhattan dropoffs in sequence. Build a tibble with the four stops in order, draw a blue polyline connecting them with <code>addPolylines()</code>, and overlay numbered markers at each stop. Use OpenStreetMap tiles, <code>fitBounds()</code> for framing. Save to <code>ex_3_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - tile layer: OpenStreetMap
#&gt;   - 1 blue polyline connecting 4 stops in order
#&gt;   - 4 markers labeled "Stop 1", "Stop 2", "Stop 3", "Stop 4"
#&gt;   - view auto-fit to route bounding box</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Connect the stops in their table order with a line, then layer the points on top and frame the whole route.</p><p>Use <code>addPolylines(lng = ~lng, lat = ~lat, color = "blue")</code>, then <code>addMarkers(popup = ~stop)</code>, then <code>fitBounds()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">route &lt;- tibble::tribble(
  ~stop,    ~lng,      ~lat,
  "Stop 1", -74.0060,  40.7128,
  "Stop 2", -73.9857,  40.7484,
  "Stop 3", -73.9683,  40.7851,
  "Stop 4", -73.9442,  40.6782
)

ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">route &lt;- tibble::tribble(
  ~stop,    ~lng,      ~lat,
  "Stop 1", -74.0060,  40.7128,
  "Stop 2", -73.9857,  40.7484,
  "Stop 3", -73.9683,  40.7851,
  "Stop 4", -73.9442,  40.6782
)

ex_3_1 &lt;- leaflet(route) |&gt;
  addTiles() |&gt;
  addPolylines(lng = ~lng, lat = ~lat, color = "blue", weight = 3) |&gt;
  addMarkers(lng = ~lng, lat = ~lat, popup = ~stop) |&gt;
  fitBounds(
    lng1 = min(route$lng), lat1 = min(route$lat),
    lng2 = max(route$lng), lat2 = max(route$lat)
  )
ex_3_1
#&gt; A leaflet htmlwidget with one polyline and 4 stop markers</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>addPolylines()</code> connects points in the order they appear in the data frame, so route ordering matters. The line is a straight geodesic between consecutive points; for real road-following lines you would call a routing service like OSRM or Mapbox Directions and feed the returned coordinate string back in. Use <code>weight</code> for line thickness and <code>dashArray = "5,5"</code> for dashed lines (useful for planned vs actual routes).</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-3-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 3.2: Size circles by sales volume for a territory map</h3>
<p class="exercise-task"><strong>Task:</strong> The VP of Sales wants a map where each city's circle radius is proportional to its quarterly revenue, so high-grossing markets are visually obvious. Use <code>addCircles()</code> with <code>radius</code> scaled to revenue (treat radius in meters). Tooltip should show <code>name</code> and <code>revenue</code>. Save to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 5 circles, radius proportional to revenue
#&gt;   - LA circle largest (revenue 5.2M), Austin smallest (1.1M)
#&gt;   - hover label shows "&lt;name&gt;: $&lt;revenue&gt;M"
#&gt;   - view auto-fit to all 5 cities</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Drive each circle's ground size from the revenue column, scaled by a constant so the biggest market reads clearly.</p><p>Use <code>addCircles()</code> with <code>radius = ~revenue * 25000</code> and <code>label = ~paste0(name, ": $", revenue, "M")</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">sales &lt;- tibble::tribble(
  ~name,         ~lng,      ~lat,    ~revenue,
  "NYC",         -74.0060,  40.7128, 4.8,
  "Chicago",     -87.6298,  41.8781, 3.4,
  "Los Angeles", -118.2437, 34.0522, 5.2,
  "Austin",      -97.7431,  30.2672, 1.1,
  "Seattle",     -122.3321, 47.6062, 2.7
)

ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">sales &lt;- tibble::tribble(
  ~name,         ~lng,      ~lat,    ~revenue,
  "NYC",         -74.0060,  40.7128, 4.8,
  "Chicago",     -87.6298,  41.8781, 3.4,
  "Los Angeles", -118.2437, 34.0522, 5.2,
  "Austin",      -97.7431,  30.2672, 1.1,
  "Seattle",     -122.3321, 47.6062, 2.7
)

ex_3_2 &lt;- leaflet(sales) |&gt;
  addTiles() |&gt;
  addCircles(
    lng = ~lng, lat = ~lat,
    radius = ~revenue * 25000,
    color = "darkred", fillOpacity = 0.5,
    label = ~paste0(name, ": $", revenue, "M")
  ) |&gt;
  fitBounds(
    lng1 = min(sales$lng), lat1 = min(sales$lat),
    lng2 = max(sales$lng), lat2 = max(sales$lat)
  )
ex_3_2
#&gt; A leaflet htmlwidget with revenue-sized circles and hover labels</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>addCircles()</code> interprets <code>radius</code> in meters on the ground, so the visual size changes with zoom (geographic). For a marker that keeps a constant pixel size regardless of zoom, use <code>addCircleMarkers()</code> where <code>radius</code> is in pixels. The 25000 multiplier is empirical: pick a value so the largest bubble fits the city footprint at your default zoom. For perceptual accuracy, scale by <code>sqrt(revenue)</code> so circle AREA (not radius) is proportional to the metric.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-3-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 3.3: Rectangles for delivery-zone bounding boxes</h3>
<p class="exercise-task"><strong>Task:</strong> A logistics planner divides New York into three rectangular delivery zones (Lower Manhattan, Midtown, Uptown) and wants to overlay them as semi-transparent rectangles with hover labels showing the zone name. Use <code>addRectangles()</code> with <code>lng1</code>/<code>lat1</code>/<code>lng2</code>/<code>lat2</code>. Save the map to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 3 semi-transparent rectangles tiling Manhattan
#&gt;   - colors: Lower (red), Midtown (green), Uptown (blue)
#&gt;   - hover label shows zone name
#&gt;   - view centered on Manhattan, zoom 12</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Each zone is defined by two opposite corners, so a simple box overlay fits without a coordinate list.</p><p>Use <code>addRectangles()</code> with the <code>lng1</code>/<code>lat1</code>/<code>lng2</code>/<code>lat2</code> columns, <code>fillOpacity = 0.3</code>, and <code>label</code> set to the zone name.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">zones &lt;- tibble::tribble(
  ~zone,     ~lng1,    ~lat1,   ~lng2,    ~lat2,   ~color,
  "Lower",   -74.020,  40.700,  -73.990,  40.730,  "red",
  "Midtown", -74.000,  40.730,  -73.960,  40.770,  "green",
  "Uptown",  -73.985,  40.770,  -73.930,  40.820,  "blue"
)

ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">zones &lt;- tibble::tribble(
  ~zone,     ~lng1,    ~lat1,   ~lng2,    ~lat2,   ~color,
  "Lower",   -74.020,  40.700,  -73.990,  40.730,  "red",
  "Midtown", -74.000,  40.730,  -73.960,  40.770,  "green",
  "Uptown",  -73.985,  40.770,  -73.930,  40.820,  "blue"
)

ex_3_3 &lt;- leaflet() |&gt;
  addTiles() |&gt;
  setView(-73.98, 40.76, zoom = 12) |&gt;
  addRectangles(
    lng1 = zones$lng1, lat1 = zones$lat1,
    lng2 = zones$lng2, lat2 = zones$lat2,
    color = zones$color, fillOpacity = 0.3,
    label = zones$zone
  )
ex_3_3
#&gt; A leaflet htmlwidget with 3 colored zone rectangles</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>addRectangles()</code> is the simplest geometric overlay because you specify two opposite corners, not a coordinate list. For non-rectangular zones use <code>addPolygons()</code> with a list of <code>lng</code>/<code>lat</code> vectors. Note that the data frame's columns are passed as raw vectors here rather than with <code>~</code> formula notation: this works when you call <code>leaflet()</code> without <code>data =</code>. Both styles are valid; pick one per project for consistency.</p>
</details>
</section>
<h2>Section 4. Choropleth and color scales (4 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-4-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 4.1: Build a continuous color palette with colorNumeric</h3>
<p class="exercise-task"><strong>Task:</strong> A city analyst wants to color neighborhoods on a 0-100 deprivation index, going from light yellow to dark red. Build a continuous palette function with <code>colorNumeric(palette = "YlOrRd", domain = 0:100)</code>. Then apply it to a vector of five scores and return both the palette function and the colors as a named list. Save to <code>ex_4_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; List of 2:
#&gt;  $ pal   : function (x) ... (colorNumeric palette)
#&gt;  $ colors: chr [1:5] "#FFFFCC" "#FED976" "#FD8D3C" "#E31A1C" "#800026"
#&gt;    (5 colors going light yellow to dark red for scores 10, 30, 55, 80, 95)</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Build a reusable mapping from a fixed numeric range onto a yellow-to-red color ramp, then apply it to the scores.</p><p>Call <code>colorNumeric(palette = "YlOrRd", domain = 0:100)</code> and store both that function and its output on <code>scores</code> in a <code>list()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">scores &lt;- c(10, 30, 55, 80, 95)

ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">scores &lt;- c(10, 30, 55, 80, 95)

pal &lt;- colorNumeric(palette = "YlOrRd", domain = 0:100)

ex_4_1 &lt;- list(
  pal    = pal,
  colors = pal(scores)
)
ex_4_1$colors
#&gt; [1] "#FFFFCC" "#FED976" "#FD8D3C" "#E31A1C" "#800026"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>colorNumeric()</code> returns a <a class="auto-link" href="R-Closures.html" title="R Closures: Functions That Remember Their Defining Environment">CLOSURE</a>: a function that, given a numeric vector, returns a vector of hex colors. The <code>domain</code> argument fixes the scale so the same score always maps to the same color across different subsets of your data, which is critical for comparable maps. For discrete bins use <code>colorBin()</code>, for quantile-based binning use <code>colorQuantile()</code>, and for <a class="auto-link" href="Categorical-Data-in-R.html" title="Categorical Data in R: Frequency Tables, Crosstabs &amp; Mosaic Plots">categorical data</a> use <code>colorFactor()</code>.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-4-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 4.2: Bin a continuous metric into 5 quantile-based colors</h3>
<p class="exercise-task"><strong>Task:</strong> A retail planner wants to color 30 zip codes by foot-traffic into 5 <a class="auto-link" href="dplyr-ntile-in-R.html" title="dplyr ntile() in R: Bin Values into N Equal-Count Groups">quantile bins</a> so the top quintile pops. Generate 30 random foot-traffic counts, build a 5-quintile palette with <code>colorQuantile()</code>, and return a tibble with the count, the bin index, and the hex color. Save to <code>ex_4_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 30 x 3
#&gt;    foot_traffic   bin color
#&gt;           &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;
#&gt;  1         2350     3 #FD8D3C
#&gt;  2         8200     5 #BD0026
#&gt;  3          450     1 #FFFFB2
#&gt;  ...
#&gt;  # 27 more rows hidden; bin values 1-5; colors light yellow to dark red</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Skewed counts need equal-count bins rather than equal-width ones, so each color holds the same number of zip codes.</p><p>Use <code>colorQuantile(palette = "YlOrRd", domain = foot_traffic, n = 5)</code> and derive the bin index with <code>cut()</code> over <code>quantile()</code> breaks.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(11)
foot_traffic &lt;- sample(100:10000, 30)

ex_4_2 &lt;- # your code here
head(ex_4_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(11)
foot_traffic &lt;- sample(100:10000, 30)

pal_q &lt;- colorQuantile(palette = "YlOrRd", domain = foot_traffic, n = 5)

ex_4_2 &lt;- tibble::tibble(
  foot_traffic = foot_traffic,
  bin          = as.integer(cut(foot_traffic,
                  breaks = quantile(foot_traffic, probs = seq(0, 1, 0.2)),
                  include.lowest = TRUE)),
  color        = pal_q(foot_traffic)
)
head(ex_4_2)
#&gt; # A tibble: 6 x 3
#&gt;   foot_traffic   bin color
#&gt;          &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;
#&gt; 1         2350     3 #FD8D3C
#&gt; ...</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>colorQuantile()</code> is the right tool when raw values are highly skewed: equal-width bins (<code>colorBin()</code>) would lump 90% of zip codes into one color and leave the top 10% as outliers. Quantile binning guarantees each bin holds the same number of observations, so the visual contrast is preserved even when distributions are heavy-tailed. The trade-off is that bin boundaries are no longer round numbers; document them in the legend.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="leaflet-Exercises-in-R-ex-4-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 4.3: Choropleth polygons with a continuous palette and legend</h3>
<p class="exercise-task"><strong>Task:</strong> A real-estate marketing team wants a choropleth of 4 neighborhood polygons colored by median home price, with a legend in the bottom-right. Build the neighborhood polygons inline as a tibble of <code>lng</code>/<code>lat</code> vectors per neighborhood. Use <code>colorNumeric</code> for the fill, <code>addPolygons()</code>, and <code>addLegend()</code>. Save to <code>ex_4_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 4 polygon overlays, fill color by median_price
#&gt;   - palette: YlGnBu (light yellow to dark blue), domain 200k-1.2M
#&gt;   - legend in "bottomright" titled "Median Price ($)"
#&gt;   - hover label shows neighborhood name and price</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Color each neighborhood polygon from a shared price scale, then add a key so the colors are decodable.</p><p>Build the palette with <code>colorNumeric("YlGnBu", ...)</code>, loop <code>addPolygons(fillColor = pal(price))</code>, and finish with <code>addLegend(position = "bottomright")</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">nbhds &lt;- list(
  list(name = "Downtown",  price =  900000,
       lng = c(-74.02,-74.00,-74.00,-74.02),
       lat = c( 40.70, 40.70, 40.72, 40.72)),
  list(name = "Midtown",   price = 1200000,
       lng = c(-74.00,-73.97,-73.97,-74.00),
       lat = c( 40.74, 40.74, 40.77, 40.77)),
  list(name = "Uptown",    price =  600000,
       lng = c(-73.97,-73.94,-73.94,-73.97),
       lat = c( 40.78, 40.78, 40.82, 40.82)),
  list(name = "Outerring", price =  250000,
       lng = c(-73.94,-73.90,-73.90,-73.94),
       lat = c( 40.65, 40.65, 40.68, 40.68))
)

ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">nbhds &lt;- list(
  list(name = "Downtown",  price =  900000,
       lng = c(-74.02,-74.00,-74.00,-74.02),
       lat = c( 40.70, 40.70, 40.72, 40.72)),
  list(name = "Midtown",   price = 1200000,
       lng = c(-74.00,-73.97,-73.97,-74.00),
       lat = c( 40.74, 40.74, 40.77, 40.77)),
  list(name = "Uptown",    price =  600000,
       lng = c(-73.97,-73.94,-73.94,-73.97),
       lat = c( 40.78, 40.78, 40.82, 40.82)),
  list(name = "Outerring", price =  250000,
       lng = c(-73.94,-73.90,-73.90,-73.94),
       lat = c( 40.65, 40.65, 40.68, 40.68))
)

prices &lt;- sapply(nbhds, \(n) n$price)
pal    &lt;- colorNumeric("YlGnBu", domain = range(prices))

m &lt;- leaflet() |&gt; addTiles() |&gt; setView(-73.97, 40.74, 11)

for (n in nbhds) {
  m &lt;- m |&gt; addPolygons(
    lng = n$lng, lat = n$lat,
    fillColor = pal(n$price), fillOpacity = 0.7,
    color = "white", weight = 1,
    label = sprintf("%s: $%s", n$name, format(n$price, big.mark = ","))
  )
}

ex_4_3 &lt;- m |&gt; addLegend(
  position = "bottomright", pal = pal, values = prices,
  title    = "Median Price ($)", labFormat = labelFormat(prefix = "$")
)
ex_4_3
#&gt; A leaflet htmlwidget with 4 choropleth polygons and a price legend</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Iterating with a <code>for</code> loop is the most readable pattern when each polygon has its own vector of coordinates rather than a tidy long table. For a real project you would typically load a shapefile or GeoJSON with <code>sf::st_read()</code> and pass the resulting sf object directly to <code>addPolygons(data = sf_obj, fillColor = ~pal(price))</code>. <code>addLegend()</code> rounds out the choropleth: a colored polygon without a legend is unreadable.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-4-4" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 4.4: Highlight polygons on hover for an interactive choropleth</h3>
<p class="exercise-task"><strong>Task:</strong> The same real-estate map from 4.3 should highlight the polygon under the cursor (thicker border, full opacity) so the user can clearly see which neighborhood they are inspecting. Wrap <code>addPolygons()</code> with <code>highlightOptions()</code>. Reuse the same data. Save to <code>ex_4_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - same choropleth as ex_4_3
#&gt;   - hovering a polygon thickens its border to 3px and lifts opacity to 1.0
#&gt;   - hover label still shows name + price</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Give each polygon a temporary style that activates only while the cursor is hovering over it.</p><p>Add <code>highlightOptions = highlightOptions(weight = 3, fillOpacity = 1.0, bringToFront = TRUE)</code> to the <code>addPolygons()</code> call.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_4 &lt;- # your code here, reuse nbhds and pal from ex_4_3
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">prices &lt;- sapply(nbhds, \(n) n$price)
pal    &lt;- colorNumeric("YlGnBu", domain = range(prices))

m &lt;- leaflet() |&gt; addTiles() |&gt; setView(-73.97, 40.74, 11)

for (n in nbhds) {
  m &lt;- m |&gt; addPolygons(
    lng = n$lng, lat = n$lat,
    fillColor = pal(n$price), fillOpacity = 0.7,
    color = "white", weight = 1,
    label = sprintf("%s: $%s", n$name, format(n$price, big.mark = ",")),
    highlightOptions = highlightOptions(
      color = "black", weight = 3, fillOpacity = 1.0, bringToFront = TRUE
    )
  )
}

ex_4_4 &lt;- m |&gt; addLegend(
  position = "bottomright", pal = pal, values = prices,
  title    = "Median Price ($)", labFormat = labelFormat(prefix = "$")
)
ex_4_4
#&gt; A leaflet htmlwidget with hover-highlight choropleth polygons</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>highlightOptions()</code> swaps in temporary styling on <code>mouseover</code>, then restores the original style on <code>mouseout</code>. <code>bringToFront = TRUE</code> ensures the highlighted polygon overlaps its neighbors visually, which matters when borders touch. This is the single biggest readability win for choropleths shown to non-technical viewers: it converts a static color blob into something users can explore.</p>
</details>
</section>
<h2>Section 5. Layer control and interactive features (3 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-5-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 5.1: Toggle two base maps and two overlay groups</h3>
<p class="exercise-task"><strong>Task:</strong> A city dashboard needs the user to toggle between OpenStreetMap and CartoDB.Positron base layers, and to toggle two overlay groups: "Police Stations" (10 markers) and "Fire Stations" (5 markers). Use <code>addLayersControl()</code>. Generate both station tibbles inline by sampling around Chicago. Save the map to <code>ex_5_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 2 base layers selectable via radio: "OSM", "Positron"
#&gt;   - 2 overlay groups toggleable via checkbox: "Police", "Fire"
#&gt;   - 10 blue police markers, 5 red fire markers
#&gt;   - layer control collapsed by default in top-right</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Tag every layer with a group name, then expose those groups as switchable base maps and toggleable overlays.</p><p>Pass <code>group =</code> to each <code>addTiles</code>/<code>addProviderTiles</code>/<code>addCircleMarkers</code> call, then <code>addLayersControl(baseGroups = ..., overlayGroups = ...)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(3)
police &lt;- tibble::tibble(
  lng = rnorm(10, -87.6298, 0.08),
  lat = rnorm(10,  41.8781, 0.06)
)
fire &lt;- tibble::tibble(
  lng = rnorm(5, -87.6298, 0.10),
  lat = rnorm(5,  41.8781, 0.07)
)

ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(3)
police &lt;- tibble::tibble(
  lng = rnorm(10, -87.6298, 0.08),
  lat = rnorm(10,  41.8781, 0.06)
)
fire &lt;- tibble::tibble(
  lng = rnorm(5, -87.6298, 0.10),
  lat = rnorm(5,  41.8781, 0.07)
)

ex_5_1 &lt;- leaflet() |&gt;
  addTiles(group = "OSM") |&gt;
  addProviderTiles(providers$CartoDB.Positron, group = "Positron") |&gt;
  addCircleMarkers(
    data = police, lng = ~lng, lat = ~lat,
    color = "blue", radius = 5, group = "Police"
  ) |&gt;
  addCircleMarkers(
    data = fire, lng = ~lng, lat = ~lat,
    color = "red", radius = 6, group = "Fire"
  ) |&gt;
  addLayersControl(
    baseGroups    = c("OSM", "Positron"),
    overlayGroups = c("Police", "Fire"),
    options       = layersControlOptions(collapsed = TRUE)
  )
ex_5_1
#&gt; A leaflet htmlwidget with 2 base maps and 2 toggleable overlay groups</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Layer groups are the leaflet idiom for showing/hiding sets of features as a unit. Pass <code>group = "name"</code> to every <code>add*()</code> call you want grouped, then list those groups in <code>addLayersControl()</code>. <code>baseGroups</code> are mutually exclusive (radio buttons); <code>overlayGroups</code> are independent (checkboxes). For dashboards with many layers, set <code>collapsed = TRUE</code> so the control starts as a small icon and expands on hover.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-5-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 5.2: Add fullscreen and scale-bar controls</h3>
<p class="exercise-task"><strong>Task:</strong> The retail leadership reviews territory maps on a projector in the boardroom and needs the map to expand to fullscreen with one click, plus a scale bar so they can eyeball distances. Use <code>addFullscreenControl()</code> from leaflet.extras and <code>addScaleBar()</code> from leaflet. Build a five-store map and add both controls. Save to <code>ex_5_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 5 sales markers (NYC, Chicago, LA, Austin, Seattle)
#&gt;   - fullscreen button in top-left corner
#&gt;   - scale bar in bottom-left, units "metric" (km)
#&gt;   - view auto-fit to all 5 cities</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Build the five-store map first, then bolt on two presentation widgets - one to expand the view, one to show distance.</p><p>Add <code>addFullscreenControl(position = "topleft")</code> and <code>addScaleBar(position = "bottomleft", options = scaleBarOptions(imperial = FALSE))</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">sales &lt;- tibble::tribble(
  ~name,         ~lng,      ~lat,
  "NYC",         -74.0060,  40.7128,
  "Chicago",     -87.6298,  41.8781,
  "Los Angeles", -118.2437, 34.0522,
  "Austin",      -97.7431,  30.2672,
  "Seattle",     -122.3321, 47.6062
)

ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">sales &lt;- tibble::tribble(
  ~name,         ~lng,      ~lat,
  "NYC",         -74.0060,  40.7128,
  "Chicago",     -87.6298,  41.8781,
  "Los Angeles", -118.2437, 34.0522,
  "Austin",      -97.7431,  30.2672,
  "Seattle",     -122.3321, 47.6062
)

ex_5_2 &lt;- leaflet(sales) |&gt;
  addTiles() |&gt;
  addMarkers(lng = ~lng, lat = ~lat, popup = ~name) |&gt;
  fitBounds(
    lng1 = min(sales$lng), lat1 = min(sales$lat),
    lng2 = max(sales$lng), lat2 = max(sales$lat)
  ) |&gt;
  addFullscreenControl(position = "topleft") |&gt;
  addScaleBar(position = "bottomleft",
              options = scaleBarOptions(imperial = FALSE))
ex_5_2
#&gt; A leaflet htmlwidget with fullscreen control and metric scale bar</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Boardroom and conference-room maps benefit enormously from <code>addFullscreenControl()</code>: a projected map at 1024x768 with a sidebar of controls is unreadable, but fullscreen mode reclaims the entire screen. <code>addScaleBar()</code> is the cheapest credibility win on any geographic figure presented to non-technical stakeholders. Set <code>imperial = TRUE</code> for US audiences; metric for international. The scale bar auto-adjusts to the current zoom level.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-5-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 5.3: Custom HTML popup styling a delivery zone</h3>
<p class="exercise-task"><strong>Task:</strong> A logistics ops team wants a polygon overlay for the Newark delivery zone with a click-popup that styles content in HTML: bold zone name, 2-row table of "Orders today" and "Avg delivery time". Use <code>addPolygons()</code> with a custom HTML popup string. Save to <code>ex_5_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 1 blue polygon outlining Newark delivery zone
#&gt;   - click triggers popup with HTML table:
#&gt;     - &lt;b&gt;Newark Zone&lt;/b&gt;
#&gt;     - Orders today: 142
#&gt;     - Avg delivery time: 38 min</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Assemble a small HTML snippet with a bold heading and a two-row table, then attach it as the polygon's click content.</p><p>Build the string with <code>paste(...)</code> and pass it to <code>addPolygons()</code> through the <code>popup</code> argument.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">newark &lt;- list(
  lng = c(-74.20, -74.14, -74.14, -74.20),
  lat = c( 40.70,  40.70,  40.76,  40.76)
)

ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">newark &lt;- list(
  lng = c(-74.20, -74.14, -74.14, -74.20),
  lat = c( 40.70,  40.70,  40.76,  40.76)
)

popup_html &lt;- paste(
  "&lt;b&gt;Newark Zone&lt;/b&gt;",
  "&lt;table style='font-size:11px'&gt;",
  "&lt;tr&gt;&lt;td&gt;Orders today&lt;/td&gt;&lt;td&gt;&lt;b&gt;142&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;",
  "&lt;tr&gt;&lt;td&gt;Avg delivery&lt;/td&gt;&lt;td&gt;&lt;b&gt;38 min&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;",
  "&lt;/table&gt;",
  sep = ""
)

ex_5_3 &lt;- leaflet() |&gt;
  addTiles() |&gt;
  setView(-74.17, 40.73, zoom = 12) |&gt;
  addPolygons(
    lng = newark$lng, lat = newark$lat,
    color = "blue", fillOpacity = 0.3,
    popup = popup_html
  )
ex_5_3
#&gt; A leaflet htmlwidget with one polygon and a styled HTML popup</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Popups support arbitrary HTML, so you can embed tables, images (<code>&lt;img&gt;</code>), and links to operational dashboards. For data-driven popups across many polygons, build the HTML strings vectorized with <code>glue::glue()</code> or <code>sprintf()</code> and pass them as a vector. Keep popup HTML lean: every popup is rendered on first click, so embedding large images can slow down dense maps. For richer interactivity (forms, charts), use Shiny instead.</p>
</details>
</section>
<h2>Section 6. Realistic ops-team dashboards (3 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-6-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 6.1: Build a daily delivery-coverage map with depot and route layers</h3>
<p class="exercise-task"><strong>Task:</strong> A regional logistics dispatcher wants a daily ops map showing one depot, three delivery zones as rectangles, and the planned routes from depot to each zone center as polylines. Color rectangles by load (light=low, dark=high). Toggle "Zones" and "Routes" via layer control. Use the inline data below. Save the map to <code>ex_6_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 1 depot marker (red, "Newark Depot")
#&gt;   - 3 zone rectangles fill-colored by load (light yellow to dark red)
#&gt;   - 3 dashed polylines from depot to each zone center
#&gt;   - layer control: "Zones" and "Routes" toggleable, OSM base</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Combine a fixed depot, metric-colored zone boxes, and depot-to-zone lines, tagging zones and routes so each can be toggled.</p><p>Compute zone centers with <code>mutate()</code>, color with <code>colorNumeric("YlOrRd", ...)</code>, loop <code>addRectangles(group = "Zones")</code> and <code>addPolylines(group = "Routes", dashArray = "6,6")</code>, then <code>addLayersControl()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">depot &lt;- list(name = "Newark Depot", lng = -74.17, lat = 40.73)
zones &lt;- tibble::tribble(
  ~zone,     ~lng1,    ~lat1,   ~lng2,    ~lat2,   ~load,
  "Newark",  -74.20,   40.70,   -74.14,   40.76,   180,
  "JC",      -74.10,   40.70,   -74.04,   40.75,    90,
  "Hoboken", -74.04,   40.73,   -74.01,   40.76,    45
)

ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">depot &lt;- list(name = "Newark Depot", lng = -74.17, lat = 40.73)
zones &lt;- tibble::tribble(
  ~zone,     ~lng1,    ~lat1,   ~lng2,    ~lat2,   ~load,
  "Newark",  -74.20,   40.70,   -74.14,   40.76,   180,
  "JC",      -74.10,   40.70,   -74.04,   40.75,    90,
  "Hoboken", -74.04,   40.73,   -74.01,   40.76,    45
)

zones &lt;- zones |&gt;
  mutate(
    cx = (lng1 + lng2) / 2,
    cy = (lat1 + lat2) / 2
  )

pal &lt;- colorNumeric("YlOrRd", domain = zones$load)

m &lt;- leaflet() |&gt;
  addTiles() |&gt;
  setView(-74.10, 40.73, zoom = 11) |&gt;
  addAwesomeMarkers(
    lng = depot$lng, lat = depot$lat,
    icon = awesomeIcons(icon = "truck", library = "fa", markerColor = "red"),
    popup = depot$name
  )

for (i in seq_len(nrow(zones))) {
  z &lt;- zones[i, ]
  m &lt;- m |&gt;
    addRectangles(
      lng1 = z$lng1, lat1 = z$lat1, lng2 = z$lng2, lat2 = z$lat2,
      fillColor = pal(z$load), fillOpacity = 0.6,
      color = "white", weight = 1,
      label = sprintf("%s: %d orders", z$zone, z$load),
      group = "Zones"
    ) |&gt;
    addPolylines(
      lng = c(depot$lng, z$cx), lat = c(depot$lat, z$cy),
      color = "blue", weight = 2, dashArray = "6,6",
      group = "Routes"
    )
}

ex_6_1 &lt;- m |&gt;
  addLegend(position = "bottomright", pal = pal, values = zones$load,
            title = "Orders / Zone") |&gt;
  addLayersControl(
    overlayGroups = c("Zones", "Routes"),
    options = layersControlOptions(collapsed = FALSE)
  )
ex_6_1
#&gt; A leaflet htmlwidget with depot, color-coded zones, dashed routes, and toggles</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> This pattern is the backbone of a dispatch dashboard: one fixed asset (depot), several variable assets (zones) styled by a metric (load), and the relationships between them (routes). The loop builds the layers incrementally rather than vectorizing because each zone has unique coordinates. In production you would swap in real polygons (a shapefile) and real road-following routes from a routing API. The toggle control lets dispatchers focus on one perspective at a time.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-6-2" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 6.2: Crime hotspot heatmap for a city analyst</h3>
<p class="exercise-task"><strong>Task:</strong> A city analyst wants to surface crime hotspots from a sample of 200 incident points clustered around three latent epicenters in Chicago. Render a heatmap with <code>addHeatmap()</code> from leaflet.extras, with <code>radius = 20</code> and <code>blur = 15</code>. Center on Chicago at zoom 11. Save to <code>ex_6_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - tile layer: CartoDB.DarkMatter
#&gt;   - heatmap of 200 incident points, 3 visible hotspots
#&gt;   - red core for dense areas, fading through orange/yellow to blue
#&gt;   - center: Chicago (-87.63, 41.88), zoom 11</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Turn the scattered incident points into a smooth density surface, and use a dark basemap so the hot cores stand out.</p><p>Use <code>addHeatmap(lng = ~lng, lat = ~lat, radius = 20, blur = 15)</code> on top of <code>providers$CartoDB.DarkMatter</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
centers &lt;- list(c(-87.65, 41.87), c(-87.62, 41.90), c(-87.66, 41.92))
incidents &lt;- do.call(rbind, lapply(centers, \(c) data.frame(
  lng = rnorm(67, c[1], 0.005),
  lat = rnorm(67, c[2], 0.005)
)))[1:200, ]

ex_6_2 &lt;- # your code here
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
centers &lt;- list(c(-87.65, 41.87), c(-87.62, 41.90), c(-87.66, 41.92))
incidents &lt;- do.call(rbind, lapply(centers, \(c) data.frame(
  lng = rnorm(67, c[1], 0.005),
  lat = rnorm(67, c[2], 0.005)
)))[1:200, ]

ex_6_2 &lt;- leaflet(incidents) |&gt;
  addProviderTiles(providers$CartoDB.DarkMatter) |&gt;
  setView(-87.63, 41.88, zoom = 11) |&gt;
  addHeatmap(
    lng = ~lng, lat = ~lat,
    radius = 20, blur = 15, max = 0.05
  )
ex_6_2
#&gt; A leaflet htmlwidget with a heatmap of 200 incident points and 3 hotspots</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>addHeatmap()</code> aggregates point density into a smooth gradient using a kernel: <code>radius</code> is the influence radius in pixels and <code>blur</code> softens transitions between bands. The <code>max</code> parameter sets the intensity ceiling and is the single most consequential knob: too high and the map looks flat, too low and a few points saturate. CartoDB.DarkMatter is the conventional base for heatmaps because dark backgrounds make red/orange peaks pop visually. For high-precision hotspot detection, consider <code>addCluster()</code> or formal spatial statistics like Getis-Ord G*.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="leaflet-Exercises-in-R-ex-6-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 6.3: Multi-layer sales territory dashboard</h3>
<p class="exercise-task"><strong>Task:</strong> A VP of Sales wants a single map showing three territories: each territory's polygon colored by Q1 revenue (choropleth), markers for top accounts inside each territory, and the territory headquarters as a starred icon. Toggle "Territories", "Top Accounts", and "HQs" independently. Reuse a single color palette across the choropleth and the legend. Save to <code>ex_6_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; A leaflet htmlwidget:
#&gt;   - 3 colored territory polygons (West, Central, East)
#&gt;   - 6 top-account circle markers (2 per territory)
#&gt;   - 3 starred HQ markers
#&gt;   - layer control with 3 overlay groups, all visible by default
#&gt;   - legend bottom-right titled "Q1 Revenue ($M)"</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Stack three feature types - colored territory polygons, account points, and HQ icons - each in its own toggleable group sharing one revenue scale.</p><p>Build one <code>colorNumeric("YlGnBu", ...)</code> palette, loop <code>addPolygons(group = "Territories")</code> and <code>addAwesomeMarkers(icon = awesomeIcons(icon = "star"), group = "HQs")</code>, add <code>addCircleMarkers(group = "Top Accounts")</code>, then <code>addLegend()</code> and <code>addLayersControl()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">territories &lt;- list(
  list(name="West",    rev=4.2,
       lng=c(-122,-115,-115,-122), lat=c(33,33,42,42),
       hq=c(-118.24, 34.05)),
  list(name="Central", rev=3.1,
       lng=c(-105,-90,-90,-105),  lat=c(30,30,42,42),
       hq=c(-97.74, 30.27)),
  list(name="East",    rev=5.8,
       lng=c(-83,-71,-71,-83),    lat=c(36,36,44,44),
       hq=c(-74.01, 40.71))
)
top_accounts &lt;- tibble::tribble(
  ~name,    ~lng,     ~lat,    ~territory,
  "Acme W", -119.4,   35.3,    "West",
  "Beta W", -117.1,   38.9,    "West",
  "Acme C", -98.5,    32.8,    "Central",
  "Beta C", -94.6,    38.6,    "Central",
  "Acme E", -75.2,    39.7,    "East",
  "Beta E", -76.6,    42.3,    "East"
)

ex_6_3 &lt;- # your code here
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">territories &lt;- list(
  list(name="West",    rev=4.2,
       lng=c(-122,-115,-115,-122), lat=c(33,33,42,42),
       hq=c(-118.24, 34.05)),
  list(name="Central", rev=3.1,
       lng=c(-105,-90,-90,-105),  lat=c(30,30,42,42),
       hq=c(-97.74, 30.27)),
  list(name="East",    rev=5.8,
       lng=c(-83,-71,-71,-83),    lat=c(36,36,44,44),
       hq=c(-74.01, 40.71))
)
top_accounts &lt;- tibble::tribble(
  ~name,    ~lng,     ~lat,    ~territory,
  "Acme W", -119.4,   35.3,    "West",
  "Beta W", -117.1,   38.9,    "West",
  "Acme C", -98.5,    32.8,    "Central",
  "Beta C", -94.6,    38.6,    "Central",
  "Acme E", -75.2,    39.7,    "East",
  "Beta E", -76.6,    42.3,    "East"
)

revs &lt;- sapply(territories, \(t) t$rev)
pal  &lt;- colorNumeric("YlGnBu", domain = revs)

m &lt;- leaflet() |&gt;
  addProviderTiles(providers$CartoDB.Positron) |&gt;
  setView(-95, 38, zoom = 4)

for (t in territories) {
  m &lt;- m |&gt;
    addPolygons(
      lng = t$lng, lat = t$lat,
      fillColor = pal(t$rev), fillOpacity = 0.5,
      color = "white", weight = 1,
      label = sprintf("%s: $%.1fM", t$name, t$rev),
      group = "Territories"
    ) |&gt;
    addAwesomeMarkers(
      lng = t$hq[1], lat = t$hq[2],
      icon = awesomeIcons(icon = "star", library = "fa", markerColor = "darkblue"),
      popup = paste(t$name, "HQ"),
      group = "HQs"
    )
}

m &lt;- m |&gt;
  addCircleMarkers(
    data = top_accounts, lng = ~lng, lat = ~lat,
    radius = 6, color = "black", fillColor = "yellow",
    fillOpacity = 1, weight = 1,
    label = ~paste(name, "(", territory, ")"),
    group = "Top Accounts"
  )

ex_6_3 &lt;- m |&gt;
  addLegend(position = "bottomright", pal = pal, values = revs,
            title = "Q1 Revenue ($M)") |&gt;
  addLayersControl(
    overlayGroups = c("Territories", "Top Accounts", "HQs"),
    options       = layersControlOptions(collapsed = FALSE)
  )
ex_6_3
#&gt; A leaflet htmlwidget combining choropleth, account markers, HQ icons, legend, toggles</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Production dashboards stack five to ten layer types on one map; this exercise compresses that pattern into three. Two design rules to remember: keep one palette per metric (the legend implicitly trusts a single domain), and always assign every overlay a <code>group =</code> so the user has fine-grained control. For very large datasets (10k+ markers), pair this pattern with marker clustering or feature-group simplification to keep render time under one second.</p>
</details>
</section>
<h2>What to do next</h2>
<ul>
<li>Brush up on the core API with the <a href="Leaflet-in-R.html">leaflet for R tutorial</a> parent post.</li>
<li>Practice manipulating the data that feeds these maps with <a href="dplyr-Exercises-in-R.html">dplyr Exercises</a>.</li>
<li>For shapefile and GeoJSON handling, work through the <a href="sf-Exercises-in-R.html">sf package Exercises</a>.</li>
<li>Compare with a different mapping toolkit in the <a href="ggplot2-Maps-Exercises-in-R.html">ggplot2 Maps Exercises</a>.</li>
</ul>

{% endraw %}