---
title: "Logistic Regression Exercises in R: 25 Practice Problems"
description: "Logistic regression R exercises: 25 binary classification problems covering glm(), odds ratios, ROC/AUC, threshold tuning, and end-to-end model workflows."
keywords: "logistic regression R exercises, glm R practice, binary classification R, odds ratio R, ROC AUC R, logistic regression practice problems"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "logistic regression in r|glm in r|binary classification|odds ratio|roc curve|confusion matrix"
auto_link_case_sensitive: false
sidebar_title: "Logistic Regression Exercises"
sidebar_order: "127"
fr_parent: "Logistic-Regression-With-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Logistic Regression Exercises in R: 25 Practice Problems</h1>

<p class="lead">Twenty-five graded logistic regression problems in R, from fitting your first <code>glm()</code> and reading odds ratios to ROC/AUC scoring, threshold tuning, and an end-to-end churn pipeline. Each problem ships with an Expected result and a hidden solution so you can self-check.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="60" data-exercises="25" data-xp="375"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(stats)
library(dplyr)
library(tibble)
library(pROC)
library(broom)
library(ggplot2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Fit, predict, and interpret a binary logistic model (4 problems)</h2>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-1-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Fit a one-predictor logistic regression on mtcars</h3>

<p class="exercise-task"><strong>Task:</strong> Use <code>glm()</code> with <code>family = binomial</code> to fit a logistic regression predicting transmission type (<code>am</code>, 1 = manual) from miles per gallon (<code>mpg</code>) on the built-in <code>mtcars</code> dataset. Save the fitted model object to <code>ex_1_1</code> and print its summary coefficients.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Coefficients:
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)  -6.6035     2.3514  -2.808  0.00498 **
#&gt; mpg           0.3070     0.1148   2.673  0.00751 **</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A logistic regression is a <a class="auto-link" href="GLM-Exercises-in-R.html" title="GLM Exercises in R: 10 Poisson, Binomial & Gamma Practice Problems, Solved Step-by-Step">generalized linear model</a> with a binomial response; the model formula puts the outcome on the left and the predictor on the right.</p><p>Call <code>glm()</code> with the formula <code>am ~ mpg</code>, <code>data = mtcars</code>, and <code>family = binomial</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
summary(ex_1_1)$coefficients</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- glm(am ~ mpg, data = mtcars, family = binomial)
summary(ex_1_1)$coefficients
#&gt;             Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)  -6.6035     2.3514  -2.808  0.00498
#&gt; mpg           0.3070     0.1148   2.673  0.00751</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>glm()</code> with <code>family = binomial</code> fits a logistic regression by maximum likelihood. The default link is <code>logit</code>, so coefficients are on the log-odds scale: a one-MPG increase raises the log-odds of a manual transmission by 0.307. The Wald z-value tests whether each coefficient differs from zero. Use <code>family = binomial(link = &quot;probit&quot;)</code> if you ever need the probit alternative.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-1-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.2: Predict response-scale probabilities for new mpg values</h3>

<p class="exercise-task"><strong>Task:</strong> Using the model <code>ex_1_1</code>, predict the probability of a manual transmission for cars with <code>mpg</code> values of 10, 20, and 30. Use <code>predict()</code> with <code>type = &quot;response&quot;</code> so the output is on the probability scale, not log-odds. Save the named numeric result to <code>ex_1_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;          1          2          3
#&gt; 0.02672 0.36625 0.92293</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Predicting for unseen predictor values means supplying a fresh data frame and asking for output on the probability scale rather than the log-odds scale.</p><p>Use <code>predict()</code> with <code>newdata = data.frame(mpg = c(10, 20, 30))</code> and <code>type = &quot;response&quot;</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- predict(ex_1_1, newdata = data.frame(mpg = c(10, 20, 30)), type = &quot;response&quot;)
ex_1_2
#&gt;          1          2          3
#&gt; 0.02672    0.36625    0.92293</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The default <code>type = &quot;link&quot;</code> returns log-odds; <code>type = &quot;response&quot;</code> applies the inverse logit so values sit in (0, 1). For a thin-tailed sigmoid like this one, the probability jumps fastest near the decision boundary (mpg around 21.5 where log-odds = 0). Always pass a data frame with the same column name as the predictor, not a bare vector.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-1-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.3: Convert log-odds to probabilities with plogis()</h3>

<p class="exercise-task"><strong>Task:</strong> Manually compute fitted probabilities for the first six rows of <code>mtcars</code> by extracting the linear predictor from <code>ex_1_1</code> and passing it through <code>plogis()</code>. Compare against <code>predict(type = &quot;response&quot;)</code> and save the manual probability vector to <code>ex_1_3</code>. They must match to numerical precision.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;         Mazda RX4    Mazda RX4 Wag       Datsun 710   Hornet 4 Drive
#&gt;             0.523            0.523            0.578            0.499
#&gt; Hornet Sportabout          Valiant
#&gt;             0.376            0.318</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The inverse-link transformation turns a model's linear predictor on the log-odds scale into fitted probabilities.</p><p>Extract the linear predictor with <code>predict(ex_1_1, type = &quot;link&quot;)</code>, then pass it through <code>plogis()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
head(ex_1_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">log_odds &lt;- predict(ex_1_1, type = &quot;link&quot;)
ex_1_3   &lt;- plogis(log_odds)
head(ex_1_3)
#&gt;         Mazda RX4    Mazda RX4 Wag       Datsun 710   Hornet 4 Drive
#&gt;             0.523            0.523            0.578            0.499
#&gt; Hornet Sportabout          Valiant
#&gt;             0.376            0.318</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>plogis(x)</code> is <code>1/(1 + exp(-x))</code>, the inverse logit. It maps any real number to (0, 1). Useful when you have raw linear predictors from <code>predict(type = &quot;link&quot;)</code>, hand-computed log-odds, or coefficients from a paper. Its companion <code>qlogis()</code> goes the other way (probability to log-odds), handy for plotting on the logit scale.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-1-4" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.4: Inspect deviance residuals and null vs residual deviance</h3>

<p class="exercise-task"><strong>Task:</strong> Run <code>summary(ex_1_1)</code> and extract the null deviance, residual deviance, and <a class="auto-link" href="Model-Selection-in-R.html" title="Model Selection in R">AIC</a> into a named numeric vector. These three numbers together describe how much a single predictor improved fit over an intercept-only model. Save the named vector to <code>ex_1_4</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; null_dev resid_dev      aic
#&gt;   43.230    29.675    33.675</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A fitted model object stores its goodness-of-fit numbers as named components you can pull out directly.</p><p>Combine <code>ex_1_1$null.deviance</code>, <code>ex_1_1$deviance</code>, and <code>ex_1_1$aic</code> into a named vector with <code>c()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- c(
  null_dev  = ex_1_1$null.deviance,
  resid_dev = ex_1_1$deviance,
  aic       = ex_1_1$aic
)
ex_1_4
#&gt; null_dev resid_dev      aic
#&gt;   43.230    29.675    33.675</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Null deviance measures the fit of an intercept-only model; residual deviance measures the fit with predictors. The drop (43.2 to 29.7, a difference of 13.5) is the model's improvement. Compared to a <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">chi-squared distribution</a> with <code>df = 1</code>, that drop is highly significant. AIC penalizes deviance by <code>2 * p</code>, so it can rank non-nested models with different predictor sets.</p>

</details>

</section>

<h2>Section 2. Coefficients, odds ratios, and inference (4 problems)</h2>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-2-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.1: Convert coefficients to odds ratios</h3>

<p class="exercise-task"><strong>Task:</strong> Compute the odds ratios for the <code>ex_1_1</code> model by exponentiating its coefficients. The OR for <code>mpg</code> answers "by what factor do the odds of a manual transmission multiply for each additional MPG?" Save the named numeric vector of odds ratios to <code>ex_2_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; (Intercept)         mpg
#&gt;     0.00136     1.35945</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Logistic coefficients live on the log-odds scale; exponentiating moves them onto the multiplicative odds-ratio scale.</p><p>Apply <code>exp()</code> to <code>coef(ex_1_1)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- exp(coef(ex_1_1))
ex_2_1
#&gt; (Intercept)         mpg
#&gt;     0.00136     1.35945</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Logistic coefficients are log-odds, so <code>exp()</code> returns the multiplicative effect on the odds. An OR of 1.36 for <code>mpg</code> means the odds rise about 36% for every extra MPG. ORs above 1 mean positive association, below 1 negative, and exactly 1 no effect. The intercept's OR (0.00136) is the baseline odds when <code>mpg = 0</code>, which is rarely interesting on its own.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-2-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: 95% confidence intervals for odds ratios</h3>

<p class="exercise-task"><strong>Task:</strong> A reviewer wants both the point estimate and 95% CI for each <a class="auto-link" href="Logistic-Regression-in-R.html" title="Logistic Regression in R: From glm() to Odds Ratios, ROC, and AUC">odds ratio</a> in <code>ex_1_1</code>. Use <code>confint()</code> to get log-odds CIs, then exponentiate the matrix to put them on the odds-ratio scale. Save the resulting 2-column matrix (with columns <code>2.5 %</code> and <code>97.5 %</code>) to <code>ex_2_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;                2.5 %  97.5 %
#&gt; (Intercept) 1.07e-06 0.04929
#&gt; mpg         1.13e+00 1.79038</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Confidence interval bounds computed on the log-odds scale must be exponentiated before they can be read as odds-ratio bounds.</p><p>Wrap <code>confint(ex_1_1)</code> in <code>exp()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- exp(confint(ex_1_1))
ex_2_2
#&gt;                 2.5 %    97.5 %
#&gt; (Intercept) 1.07e-06   0.04929
#&gt; mpg         1.13e+00   1.79038</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>confint()</code> uses a profile-likelihood CI by default (slower but more accurate than the Wald CI from <code>confint.default()</code>). Because the mpg CI [1.13, 1.79] excludes 1, the effect is significant at the 5% level: every extra MPG multiplies the odds of a manual by between 13% and 79%. CIs that span 1 mean the predictor is not statistically distinguishable from no effect.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-2-3" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 2.3: Interpret a single coefficient as a percent change in odds</h3>

<p class="exercise-task"><strong>Task:</strong> A junior analyst onboarding needs a one-line interpretation. Compute the percent change in odds per unit increase of <code>mpg</code> from <code>ex_1_1</code> (<code>(OR - 1) * 100</code>). Round to one decimal place. Save the single scalar value to <code>ex_2_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 35.9</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A percent change in odds is just the odds ratio re-expressed relative to a baseline of one.</p><p>Take <code>exp(coef(ex_1_1)[&quot;mpg&quot;])</code>, compute <code>(or - 1) * 100</code>, and <code>round()</code> it to one decimal.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">or       &lt;- exp(coef(ex_1_1)[&quot;mpg&quot;])
ex_2_3   &lt;- round((or - 1) * 100, 1)
names(ex_2_3) &lt;- NULL
ex_2_3
#&gt; [1] 35.9</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Reporting "odds increase 35.9% per MPG" is more readable than an OR of 1.36 for non-technical audiences. The conversion is <code>(OR - 1) * 100</code>. If the OR were below 1 (say 0.80), you would report "odds decrease 20%". For very small effect sizes, log-odds and the <code>(OR - 1) * 100</code> value are approximately equal because <code>log(1 + x) ≈ x</code> near zero.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-2-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 2.4: Likelihood ratio test of nested models</h3>

<p class="exercise-task"><strong>Task:</strong> Compare a one-predictor model (<code>am ~ mpg</code>) to a two-predictor model (<code>am ~ mpg + wt</code>) using a <a class="auto-link" href="Likelihood-Ratio-Wald-and-Score-Tests-in-R.html" title="Likelihood Ratio, Wald & Score Tests in R: Three Ways to Test Hypotheses">likelihood ratio test</a> with <code>anova(..., test = &quot;LRT&quot;)</code>. The test asks whether adding <code>wt</code> significantly improves fit. Save the <code>anova</code> table to <code>ex_2_4</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Analysis of Deviance Table
#&gt;
#&gt; Model 1: am ~ mpg
#&gt; Model 2: am ~ mpg + wt
#&gt;   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
#&gt; 1        30     29.675
#&gt; 2        29     19.176  1  10.4995 0.001195 **</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Comparing two nested models tests whether the extra term produces a significant drop in deviance.</p><p>Fit <code>m2</code> as <code>glm(am ~ mpg + wt, ...)</code>, then call <code>anova(m1, m2, test = &quot;LRT&quot;)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">m1     &lt;- glm(am ~ mpg,      data = mtcars, family = binomial)
m2     &lt;- # your code here
ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">m1     &lt;- glm(am ~ mpg,      data = mtcars, family = binomial)
m2     &lt;- glm(am ~ mpg + wt, data = mtcars, family = binomial)
ex_2_4 &lt;- anova(m1, m2, test = &quot;LRT&quot;)
ex_2_4
#&gt; Analysis of Deviance Table
#&gt;
#&gt; Model 1: am ~ mpg
#&gt; Model 2: am ~ mpg + wt
#&gt;   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
#&gt; 1        30     29.675
#&gt; 2        29     19.176  1  10.4995 0.001195</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The LRT statistic equals the deviance drop (10.5) and follows a chi-squared distribution with <code>df</code> equal to the parameter difference (1). A <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">p-value</a> of 0.0012 rejects the null that the smaller model is adequate. Use <code>test = &quot;LRT&quot;</code> (or <code>&quot;Chisq&quot;</code>) for nested logistic models. For comparing non-nested or different-family models, use AIC instead.</p>

</details>

</section>

<h2>Section 3. Multiple predictors, factors, and interactions (4 problems)</h2>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-3-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.1: Fit a multi-predictor logistic regression on iris</h3>

<p class="exercise-task"><strong>Task:</strong> Subset <code>iris</code> to the two species <code>setosa</code> and <code>versicolor</code>, then fit a logistic regression of species (coded as 1 for versicolor) on <code>Sepal.Length</code>, <code>Sepal.Width</code>, and <code>Petal.Length</code>. Save the model to <code>ex_3_1</code> and inspect with <code>coef()</code>. (Setosa and versicolor are nearly linearly separable; expect large coefficient magnitudes and a warning about fitted probabilities at 0 or 1, which is fine for this drill.)</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; (Intercept)  Sepal.Length  Sepal.Width  Petal.Length
#&gt;      -50.53          7.79       -10.13         18.29</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Adding predictors just means listing more terms on the right side of the model formula.</p><p>Call <code>glm(y ~ Sepal.Length + Sepal.Width + Petal.Length, data = iris2, family = binomial)</code>, wrapping it in <code>suppressWarnings()</code> for the separation warning.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">iris2  &lt;- iris |&gt;
  filter(Species %in% c(&quot;setosa&quot;, &quot;versicolor&quot;)) |&gt;
  mutate(y = as.integer(Species == &quot;versicolor&quot;))
ex_3_1 &lt;- # your code here
coef(ex_3_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">iris2  &lt;- iris |&gt;
  filter(Species %in% c(&quot;setosa&quot;, &quot;versicolor&quot;)) |&gt;
  mutate(y = as.integer(Species == &quot;versicolor&quot;))

ex_3_1 &lt;- suppressWarnings(
  glm(y ~ Sepal.Length + Sepal.Width + Petal.Length, data = iris2, family = binomial)
)
coef(ex_3_1)
#&gt; (Intercept)  Sepal.Length  Sepal.Width  Petal.Length
#&gt;      -50.53          7.79       -10.13         18.29</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Multi-predictor logistic models are fit the same way as univariate ones, just with more terms on the right side of the formula. Each coefficient is the partial log-odds effect holding the others constant. The "fitted probabilities 0 or 1" warning means the classes are (nearly) perfectly separable: log-likelihood can be increased indefinitely by inflating coefficients. For real classification you would penalize this with <code>glmnet::glmnet()</code> or <code>arm::bayesglm()</code>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-3-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.2: Use a factor predictor with multiple levels</h3>

<p class="exercise-task"><strong>Task:</strong> Convert <code>cyl</code> in <code>mtcars</code> to a factor and fit <code>am ~ factor(cyl)</code>. R will create two dummy variables (4 is the reference, 6 and 8 get their own coefficient). Extract the exponentiated coefficients to read off the odds ratios for 6-cylinder and 8-cylinder cars versus 4-cylinder. Save the named odds-ratio vector to <code>ex_3_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   (Intercept) factor(cyl)6 factor(cyl)8
#&gt;          2.67         0.50         0.16</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A categorical predictor with several levels enters the model as dummy variables measured against a reference level, and exponentiated coefficients read as odds ratios.</p><p>Fit <code>glm(am ~ factor(cyl), ...)</code>, then apply <code>exp()</code> to <code>coef()</code> and <code>round()</code> to two decimals.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit    &lt;- glm(am ~ factor(cyl), data = mtcars, family = binomial)
ex_3_2 &lt;- round(exp(coef(fit)), 2)
ex_3_2
#&gt;   (Intercept) factor(cyl)6 factor(cyl)8
#&gt;          2.67         0.50         0.16</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A factor predictor with K levels becomes K-1 dummies. The intercept's OR (2.67) is the baseline odds of a manual for 4-cylinder cars. The OR for <code>factor(cyl)6</code> of 0.50 means 6-cylinder cars have half the odds of a manual versus 4-cylinder; 8-cylinder cars drop to 16%. Change the <a class="auto-link" href="Dummy-Variables-in-R.html" title="Dummy Variables in R: What lm() Does With Factor Predictors Under the Hood">reference category</a> with <code>relevel(factor(cyl), ref = &quot;8&quot;)</code> if you want 8-cyl as the baseline.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-3-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.3: Add an interaction term and read the joint effect</h3>

<p class="exercise-task"><strong>Task:</strong> The marketing team suspects that the effect of price discount on conversion is stronger for new customers than for returning ones. Using the inline <code>signups</code> tibble, fit <code>converted ~ discount * new_customer</code> and save the model to <code>ex_3_3</code>. Report the coefficients with <code>summary()</code>'s <code>$coefficients</code> table.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
signups &lt;- tibble::tibble(
  discount     = rep(c(0, 10, 20), times = 60),
  new_customer = rep(c(0, 1),     each = 90),
  converted    = rbinom(180, 1,
                        plogis(-1.5 + 0.05 * rep(c(0, 10, 20), times = 60) +
                               1.0  * rep(c(0, 1), each = 90) +
                               0.08 * rep(c(0, 10, 20), times = 60) *
                                      rep(c(0, 1), each = 90)))
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;                        Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)              -1.583     0.4283  -3.696 2.19e-04
#&gt; discount                  0.0518    0.0349   1.485 1.38e-01
#&gt; new_customer              1.114     0.5524   2.018 4.36e-02
#&gt; discount:new_customer     0.0708    0.0462   1.532 1.26e-01</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>An interaction lets one predictor's effect depend on the level of another predictor.</p><p>Use the <code>discount * new_customer</code> shorthand as the formula inside <code>glm()</code> with <code>family = binomial</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
summary(ex_3_3)$coefficients</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- glm(converted ~ discount * new_customer, data = signups, family = binomial)
summary(ex_3_3)$coefficients
#&gt;                        Estimate Std. Error z value Pr(&gt;|z|)
#&gt; (Intercept)              -1.583     0.4283  -3.696 2.19e-04
#&gt; discount                  0.0518    0.0349   1.485 1.38e-01
#&gt; new_customer              1.114     0.5524   2.018 4.36e-02
#&gt; discount:new_customer     0.0708    0.0462   1.532 1.26e-01</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>discount * new_customer</code> is shorthand for <code>discount + new_customer + discount:new_customer</code>. The interaction coefficient (0.071 on the log-odds scale) means each extra discount point lifts the log-odds of conversion an additional 0.071 for new customers, on top of the <a class="auto-link" href="Factorial-Experiments-in-R.html" title="Factorial Designs in R: 2^k Experiments, Main Effects, Confounding, and Interactions">main effect</a> of 0.052. Always interpret interactions before main effects; main-effect coefficients are conditional when one variable is zero.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-3-4" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.4: Standardize numeric predictors before fitting</h3>

<p class="exercise-task"><strong>Task:</strong> Fit a logistic regression on <code>mtcars</code> predicting <code>am</code> from <code>mpg</code>, <code>hp</code>, and <code>wt</code>. Standardize the three predictors first using <code>scale()</code> so the coefficients are on a comparable z-score scale and easier to rank by importance. Save the model to <code>ex_3_4</code> and print its coefficients rounded to 3 decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; (Intercept)         mpg          hp          wt
#&gt;      -1.052       3.205       7.330      -9.567</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Once the predictors are already on a z-score scale, fitting proceeds exactly like any other multi-predictor model.</p><p>Call <code>glm(am ~ mpg + hp + wt, data = mtcars_z, family = binomial)</code> inside <code>suppressWarnings()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mtcars_z &lt;- mtcars |&gt;
  mutate(across(c(mpg, hp, wt), ~ as.numeric(scale(.))))
ex_3_4   &lt;- # your code here
round(coef(ex_3_4), 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mtcars_z &lt;- mtcars |&gt;
  mutate(across(c(mpg, hp, wt), ~ as.numeric(scale(.))))

ex_3_4 &lt;- suppressWarnings(
  glm(am ~ mpg + hp + wt, data = mtcars_z, family = binomial)
)
round(coef(ex_3_4), 3)
#&gt; (Intercept)         mpg          hp          wt
#&gt;      -1.052       3.205       7.330      -9.567</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> After standardizing, each coefficient is the log-odds change per one-standard-deviation move in that predictor, so magnitudes are comparable. Here <code>wt</code> has the largest absolute effect (-9.57), then <code>hp</code> (+7.33), then <code>mpg</code> (+3.21). Standardization does NOT change predictions or p-values, only the coefficient scale and interpretation; use it for ranking importance, not for changing model fit.</p>

</details>

</section>

<h2>Section 4. Model evaluation: confusion matrix, ROC, deviance (4 problems)</h2>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-4-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.1: Build a confusion matrix at threshold 0.5</h3>

<p class="exercise-task"><strong>Task:</strong> Using <code>ex_1_1</code> (the single-predictor model), turn fitted probabilities into predicted classes with cutoff 0.5, then compute a 2x2 confusion matrix against the actual <code>am</code> values in <code>mtcars</code>. Rows should be predicted class (0, 1) and columns actual class. Save the table object to <code>ex_4_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;     actual
#&gt; pred  0  1
#&gt;    0 17  3
#&gt;    1  2 10</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A confusion matrix cross-tabulates predicted classes against actual classes once a probability cutoff has been applied.</p><p>Threshold <code>predict(ex_1_1, type = &quot;response&quot;)</code> at 0.5 with <code>ifelse()</code>, then cross-tabulate predicted vs <code>mtcars$am</code> using <code>table()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">probs  &lt;- predict(ex_1_1, type = &quot;response&quot;)
pred   &lt;- ifelse(probs &gt; 0.5, 1, 0)
ex_4_1 &lt;- table(pred = pred, actual = mtcars$am)
ex_4_1
#&gt;     actual
#&gt; pred  0  1
#&gt;    0 17  3
#&gt;    1  2 10</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A confusion matrix is the foundation of every classification metric. Diagonal entries (17 + 10 = 27 correct) divided by total (32) gives accuracy of 0.844. Off-diagonals split into 3 false negatives (predicted 0, actually 1) and 2 false positives. Pick the cutoff to match business cost: lower it to catch more positives, raise it to be more confident before flagging. The choice is decision-theoretic, not statistical.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-4-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.2: Compute accuracy, sensitivity, and specificity</h3>

<p class="exercise-task"><strong>Task:</strong> From the confusion matrix in <code>ex_4_1</code>, compute three classification metrics: accuracy (overall correct rate), sensitivity (true positive rate, also called recall), and specificity (true negative rate). Save them as a named numeric vector with names <code>accuracy</code>, <code>sensitivity</code>, <code>specificity</code> to <code>ex_4_2</code>, rounded to 3 decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;    accuracy sensitivity specificity
#&gt;       0.844       0.769       0.895</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Each classification metric is a ratio built from specific cells of the confusion matrix.</p><p>Pull the TP, TN, FP, and FN cells out of <code>ex_4_1</code>, then combine the three ratios into a named <code>c()</code> and <code>round()</code> to three decimals.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">cm &lt;- ex_4_1
TN &lt;- cm[&quot;0&quot;, &quot;0&quot;]; FP &lt;- cm[&quot;1&quot;, &quot;0&quot;]
FN &lt;- cm[&quot;0&quot;, &quot;1&quot;]; TP &lt;- cm[&quot;1&quot;, &quot;1&quot;]

ex_4_2 &lt;- round(c(
  accuracy    = (TP + TN) / sum(cm),
  sensitivity = TP / (TP + FN),
  specificity = TN / (TN + FP)
), 3)
ex_4_2
#&gt;    accuracy sensitivity specificity
#&gt;       0.844       0.769       0.895</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <a class="auto-link" href="Bayes-Theorem-in-R.html" title="Bayes' Theorem in R: Why Medical Tests Mislead You, A Simulation That Shows Why">Sensitivity and specificity</a> are conditional rates, not unconditional. Sensitivity asks "of the actual positives, what share did we catch?"; specificity asks "of the actual negatives, what share did we correctly rule out?". They trade off as you slide the threshold. Accuracy alone is misleading under class imbalance: a 99% no-event base rate makes "always predict no" hit 99% accuracy while catching zero positives.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-4-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.3: ROC curve and AUC with pROC</h3>

<p class="exercise-task"><strong>Task:</strong> Compute the ROC curve and area under the curve (AUC) for <code>ex_1_1</code> using <code>pROC::roc()</code>. Suppress the <code>auto-direction</code> message with <code>quiet = TRUE</code>. Save the AUC value (a scalar, class <code>auc</code>) to <code>ex_4_3</code> and print it rounded to 3 decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Area under the curve: 0.892</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The area under the ROC curve summarizes how well the model ranks positives above negatives across every possible threshold.</p><p>Build the curve with <code>pROC::roc()</code> passing <code>quiet = TRUE</code>, then extract the area with <code>pROC::auc()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">probs  &lt;- predict(ex_1_1, type = &quot;response&quot;)
roc_obj &lt;- pROC::roc(mtcars$am, probs, quiet = TRUE)
ex_4_3 &lt;- pROC::auc(roc_obj)
ex_4_3
#&gt; Area under the curve: 0.892</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> AUC integrates the ROC across all thresholds, giving one threshold-free summary of how well the model ranks positives above negatives. AUC of 0.5 is random; 1.0 is perfect ranking; 0.892 is strong. Equivalent interpretation: pick a random positive and a random negative; AUC is the probability the model assigns the positive a higher score. For severely imbalanced data, prefer area under the precision-recall curve instead.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-4-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 4.4: McFadden pseudo-R-squared</h3>

<p class="exercise-task"><strong>Task:</strong> Logistic regression has no R-squared in the OLS sense. Compute McFadden's pseudo-R-squared for <code>ex_1_1</code> as <code>1 - (residual deviance / null deviance)</code>. Values between 0.2 and 0.4 indicate excellent fit by McFadden's own guideline (this is a much stricter scale than OLS R-squared). Save the scalar (rounded to 3 decimals) to <code>ex_4_4</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.314</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>McFadden's measure expresses how far the fitted model's deviance falls below the null model's deviance.</p><p>Compute <code>1 - (ex_1_1$deviance / ex_1_1$null.deviance)</code> and <code>round()</code> to three decimals.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_4 &lt;- # your code here
ex_4_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_4 &lt;- round(1 - (ex_1_1$deviance / ex_1_1$null.deviance), 3)
ex_4_4
#&gt; [1] 0.314</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> McFadden's pseudo-R-squared compares the log-likelihood of the fitted model to that of an intercept-only model. Unlike OLS R-squared, it is bounded by 1 only in the limit and McFadden suggested values of 0.2 to 0.4 indicate "excellent" fit. Other variants exist (Cox-Snell, Nagelkerke, Tjur), and they disagree by design, so always name the one you report. Computed here without packages, but <code>pscl::pR2()</code> returns five of them at once.</p>

</details>

</section>

<h2>Section 5. Class imbalance and threshold tuning (5 problems)</h2>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-5-1" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.1: Find the threshold that maximizes accuracy</h3>

<p class="exercise-task"><strong>Task:</strong> The fraud team wants the threshold for <code>ex_1_1</code> that maximizes overall accuracy on the training data. Sweep cutoffs from 0.05 to 0.95 in steps of 0.05, compute accuracy at each, and return the cutoff (rounded to 2 decimals) that achieves the maximum. Save it to <code>ex_5_1</code> as a single scalar.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.45</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>The accuracy-maximizing cutoff is found by scanning a grid of candidate thresholds and keeping the one that scores best.</p><p>Build the grid with <code>seq(0.05, 0.95, by = 0.05)</code>, compute accuracy at each threshold, and pick the winner with <code>which.max()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">probs  &lt;- predict(ex_1_1, type = &quot;response&quot;)
thr    &lt;- seq(0.05, 0.95, by = 0.05)
acc    &lt;- sapply(thr, function(t) mean(ifelse(probs &gt; t, 1, 0) == mtcars$am))
ex_5_1 &lt;- thr[which.max(acc)]
ex_5_1
#&gt; [1] 0.45</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The "best" threshold is not always 0.5: it depends on class balance and cost asymmetry. Tuning by accuracy on training data risks overfitting and ignores the cost of false positives versus false negatives. In production, optimize on a holdout set and target a business metric (expected dollar value, F1, recall at fixed precision) rather than raw accuracy. Youden's J (<code>sensitivity + specificity - 1</code>) is also a popular threshold criterion.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-5-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.2: Downsample the majority class for balanced training</h3>

<p class="exercise-task"><strong>Task:</strong> The compliance officer has a highly imbalanced inline fraud dataset where only 10% of transactions are fraud. Downsample the non-fraud class with <code>dplyr::slice_sample()</code> so both classes have the same count, then fit a logistic regression <code>fraud ~ amount + risk_score</code> and save it to <code>ex_5_2</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
n_clean &lt;- 900; n_fraud &lt;- 100
tx &lt;- tibble::tibble(
  fraud      = c(rep(0L, n_clean), rep(1L, n_fraud)),
  amount     = c(rnorm(n_clean, mean = 50, sd = 30),
                 rnorm(n_fraud, mean = 250, sd = 80)),
  risk_score = c(rnorm(n_clean, mean = 0.2, sd = 0.1),
                 rnorm(n_fraud, mean = 0.6, sd = 0.15))
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; (Intercept)      amount  risk_score
#&gt;      -8.812       0.011      14.062</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Balancing the classes means drawing a random subset of the majority class so its count matches the minority class.</p><p>Use <code>slice_sample()</code> on the non-fraud rows, <code>bind_rows()</code> them with the fraud rows, then fit <code>glm(fraud ~ amount + risk_score, ...)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
round(coef(ex_5_2), 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(99)
tx_bal &lt;- bind_rows(
  tx |&gt; filter(fraud == 0) |&gt; slice_sample(n = sum(tx$fraud == 1)),
  tx |&gt; filter(fraud == 1)
)

ex_5_2 &lt;- glm(fraud ~ amount + risk_score, data = tx_bal, family = binomial)
round(coef(ex_5_2), 3)
#&gt; (Intercept)      amount  risk_score
#&gt;      -8.812       0.011      14.062</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Logistic regression trained on highly imbalanced data tends to under-predict the rare class because the intercept is pulled toward the prevalence. Downsampling the majority class restores a balanced <a class="auto-link" href="rsample-training-in-R.html" title="rsample training() in R: Get the Training Set From a Split">training set</a> but throws away information; upsampling the minority (e.g., <code>slice_sample(replace = TRUE)</code>) or <code>ROSE::ovun.sample()</code> are alternatives. Always evaluate on the original imbalanced <a class="auto-link" href="rsample-testing-in-R.html" title="rsample testing() in R: Get the Test Set From a Split">test set</a>, not on balanced data, to get realistic performance.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-5-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.3: F1 score at a chosen threshold</h3>

<p class="exercise-task"><strong>Task:</strong> The growth team prefers F1 over accuracy on imbalanced data. Compute the F1 score for <code>ex_5_2</code> predictions on the balanced training data at threshold 0.5. F1 is <code>2 * precision * recall / (precision + recall)</code>. Save the scalar F1 value (rounded to 3 decimals) to <code>ex_5_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.97</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The F1 score blends precision and recall into a single harmonic mean.</p><p>Threshold the predicted probabilities at 0.5, count TP, FP, and FN, then compute <code>2 * precision * recall / (precision + recall)</code> and <code>round()</code> to three decimals.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(99)
tx_bal &lt;- bind_rows(
  tx |&gt; filter(fraud == 0) |&gt; slice_sample(n = sum(tx$fraud == 1)),
  tx |&gt; filter(fraud == 1)
)

probs &lt;- predict(ex_5_2, type = &quot;response&quot;)
pred  &lt;- ifelse(probs &gt; 0.5, 1L, 0L)
TP    &lt;- sum(pred == 1L &amp; tx_bal$fraud == 1L)
FP    &lt;- sum(pred == 1L &amp; tx_bal$fraud == 0L)
FN    &lt;- sum(pred == 0L &amp; tx_bal$fraud == 1L)

precision &lt;- TP / (TP + FP)
recall    &lt;- TP / (TP + FN)
ex_5_3    &lt;- round(2 * precision * recall / (precision + recall), 3)
ex_5_3
#&gt; [1] 0.97</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> F1 is the harmonic mean of precision and recall, giving low values whenever either is low. It is preferred to accuracy under class imbalance because it ignores true negatives, which dominate accuracy on rare-event problems. The <code>MLmetrics::F1_Score()</code> and <code>yardstick::f_meas()</code> helpers compute it in one call, but writing it from scratch reinforces the formula. F-beta lets you weight recall versus precision asymmetrically.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-5-4" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.4: Precision-recall trade-off across thresholds</h3>

<p class="exercise-task"><strong>Task:</strong> The performance reviewer wants a single table showing precision and recall for <code>ex_5_2</code> at thresholds 0.1, 0.3, 0.5, 0.7, 0.9. Build a tibble with columns <code>threshold</code>, <code>precision</code>, <code>recall</code>. Save it to <code>ex_5_4</code>, rounded to 3 decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 3
#&gt;   threshold precision recall
#&gt;       &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1       0.1     0.917  1
#&gt; 2       0.3     0.971  0.99
#&gt; 3       0.5     0.96   0.96
#&gt; 4       0.7     0.978  0.91
#&gt; 5       0.9     1      0.78</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Precision and recall move in opposite directions as the cutoff shifts, so a table at several thresholds exposes the trade-off.</p><p>Loop the thresholds with <code>sapply()</code>, compute precision and recall at each, and assemble the columns inside a <code>tibble()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_4 &lt;- # your code here
ex_5_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(99)
tx_bal &lt;- bind_rows(
  tx |&gt; filter(fraud == 0) |&gt; slice_sample(n = sum(tx$fraud == 1)),
  tx |&gt; filter(fraud == 1)
)
probs &lt;- predict(ex_5_2, type = &quot;response&quot;)
thr   &lt;- c(0.1, 0.3, 0.5, 0.7, 0.9)

ex_5_4 &lt;- tibble::tibble(
  threshold = thr,
  precision = sapply(thr, function(t) {
    p &lt;- ifelse(probs &gt; t, 1L, 0L)
    TP &lt;- sum(p == 1L &amp; tx_bal$fraud == 1L); FP &lt;- sum(p == 1L &amp; tx_bal$fraud == 0L)
    if ((TP + FP) == 0) NA_real_ else TP / (TP + FP)
  }),
  recall    = sapply(thr, function(t) {
    p &lt;- ifelse(probs &gt; t, 1L, 0L)
    TP &lt;- sum(p == 1L &amp; tx_bal$fraud == 1L); FN &lt;- sum(p == 0L &amp; tx_bal$fraud == 1L)
    TP / (TP + FN)
  })
) |&gt;
  mutate(across(c(precision, recall), \(x) round(x, 3)))
ex_5_4
#&gt; # A tibble: 5 x 3
#&gt;   threshold precision recall
#&gt;       &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1       0.1     0.917  1.000
#&gt; 2       0.3     0.971  0.990
#&gt; 3       0.5     0.960  0.960
#&gt; 4       0.7     0.978  0.910
#&gt; 5       0.9     1.000  0.780</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A precision-recall table at a handful of thresholds is the simplest way to expose the trade-off without a chart. Increasing the threshold raises precision (fewer false alarms) at the cost of recall (more missed positives). For ranking workflows (rank-and-review fraud queues), pick the threshold that hits the team's daily review capacity. For automated <a class="auto-link" href="Experimental-Design-Principles-in-R.html" title="Experimental Design in R: The Three Principles That Make Results Valid and Generalisable">blocking</a>, pick a precision floor and read off the matching recall.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-5-5" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.5: Use weights to penalize misclassifying the rare class</h3>

<p class="exercise-task"><strong>Task:</strong> Instead of resampling, refit a logistic regression on the imbalanced <code>tx</code> dataset using <code>weights = ifelse(fraud == 1, 9, 1)</code> (inverse to prevalence: there are 9x more clean than fraud). Save the weighted model to <code>ex_5_5</code> and contrast its intercept with the unweighted intercept.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; unweighted_int   weighted_int
#&gt;          -7.91          -3.45</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Instead of resampling, you can tell the fitting routine to count rare-class rows more heavily so the intercept shifts toward a balanced one.</p><p>Pass <code>weights = ifelse(tx$fraud == 1, 9, 1)</code> to <code>glm(fraud ~ amount + risk_score, ...)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_5 &lt;- # your code here
c(unweighted_int = round(coef(glm(fraud ~ amount + risk_score, data = tx, family = binomial))[1], 2),
  weighted_int   = round(coef(ex_5_5)[1], 2))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_5 &lt;- glm(
  fraud ~ amount + risk_score,
  data    = tx,
  family  = binomial,
  weights = ifelse(tx$fraud == 1, 9, 1)
)
c(unweighted_int = round(coef(glm(fraud ~ amount + risk_score, data = tx, family = binomial))[1], 2),
  weighted_int   = round(coef(ex_5_5)[1], 2))
#&gt; unweighted_int.(Intercept)   weighted_int.(Intercept)
#&gt;                      -7.91                      -3.45</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Case weights tell <code>glm()</code> to count each rare-class observation as if it appeared multiple times, raising the intercept toward what it would be under a balanced sample. Standard errors from weighted GLMs treat the weights as known frequencies, so <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence intervals</a> shrink artificially compared to actually having that many samples. For correct inference, prefer a real resampling scheme or a robust sandwich estimator via <code>sandwich::vcovHC()</code>.</p>

</details>

</section>

<h2>Section 6. End-to-end classification workflows (4 problems)</h2>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-6-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 6.1: Train/test split and out-of-sample AUC</h3>

<p class="exercise-task"><strong>Task:</strong> Take the <code>tx</code> dataset and do a 70/30 train/test split with <code>set.seed(2026)</code>. Fit a logistic regression <code>fraud ~ amount + risk_score</code> on the training rows, score the test rows, and compute test-set AUC. Save the AUC scalar (rounded to 3 decimals) to <code>ex_6_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.999</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Generalization is measured by scoring rows the model never saw while it was being fit.</p><p>Split the row indices with <code>sample()</code>, fit on the training rows, then score <code>predict(..., newdata = test, type = &quot;response&quot;)</code> and feed it to <code>pROC::auc(pROC::roc(...))</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(2026)
idx       &lt;- sample(seq_len(nrow(tx)), size = floor(0.7 * nrow(tx)))
train     &lt;- tx[idx, ]
test      &lt;- tx[-idx, ]

fit       &lt;- glm(fraud ~ amount + risk_score, data = train, family = binomial)
test_prob &lt;- predict(fit, newdata = test, type = &quot;response&quot;)
ex_6_1    &lt;- round(as.numeric(pROC::auc(pROC::roc(test$fraud, test_prob, quiet = TRUE))), 3)
ex_6_1
#&gt; [1] 0.999</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The training AUC tells you how well the model fits the data it has seen; the test AUC tells you how well it generalizes. The gap between them quantifies overfitting. For small samples, repeat the split many times or use <code>caret::createFolds()</code> or <code>rsample::vfold_cv()</code> for <a class="auto-link" href="rsample-vfold_cv-in-R.html" title="rsample vfold_cv() in R: V-Fold Cross-Validation Splits">k-fold cross-validation</a>. Hand-coded splits with <code>sample()</code> are fine for one-off teaching but lack stratification by outcome.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-6-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.2: End-to-end churn prediction pipeline</h3>

<p class="exercise-task"><strong>Task:</strong> A SaaS retention team has 500 customers (inline <code>churn_df</code> below) with <code>tenure_months</code>, <code>monthly_spend</code>, <code>support_tickets</code>, and <code>churned</code>. Build a full pipeline: 80/20 train/test split with <code>set.seed(11)</code>, fit <code>churned ~ tenure_months + monthly_spend + support_tickets</code> on train, predict on test, and compute four test metrics (accuracy at 0.5, AUC, sensitivity, specificity). Save them as a named numeric vector to <code>ex_6_2</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
churn_df &lt;- tibble::tibble(
  tenure_months   = sample(1:60, 500, replace = TRUE),
  monthly_spend   = round(rnorm(500, 75, 20), 2),
  support_tickets = rpois(500, lambda = 2),
  churned         = rbinom(500, 1,
                           plogis(2 - 0.06 * sample(1:60, 500, replace = TRUE) +
                                  0.01 * rnorm(500, 75, 20) +
                                  0.3  * rpois(500, lambda = 2)))
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;    accuracy         auc sensitivity specificity
#&gt;       0.640       0.659       0.694       0.587</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A full evaluation reports a threshold-free ranking score alongside the threshold-dependent error rates.</p><p>After an 80/20 <code>sample()</code> split and <code>glm(churned ~ tenure_months + monthly_spend + support_tickets, ...)</code>, assemble accuracy, <code>pROC::auc()</code>, sensitivity, and specificity into a named <code>c()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
round(ex_6_2, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
idx   &lt;- sample(seq_len(nrow(churn_df)), size = floor(0.8 * nrow(churn_df)))
train &lt;- churn_df[idx, ]; test &lt;- churn_df[-idx, ]

fit       &lt;- glm(churned ~ tenure_months + monthly_spend + support_tickets,
                 data = train, family = binomial)
probs     &lt;- predict(fit, newdata = test, type = &quot;response&quot;)
pred      &lt;- ifelse(probs &gt; 0.5, 1L, 0L)

TP &lt;- sum(pred == 1L &amp; test$churned == 1L); TN &lt;- sum(pred == 0L &amp; test$churned == 0L)
FP &lt;- sum(pred == 1L &amp; test$churned == 0L); FN &lt;- sum(pred == 0L &amp; test$churned == 1L)

ex_6_2 &lt;- c(
  accuracy    = (TP + TN) / nrow(test),
  auc         = as.numeric(pROC::auc(pROC::roc(test$churned, probs, quiet = TRUE))),
  sensitivity = TP / (TP + FN),
  specificity = TN / (TN + FP)
)
round(ex_6_2, 3)
#&gt;    accuracy         auc sensitivity specificity
#&gt;       0.640       0.659       0.694       0.587</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A complete classification report needs more than accuracy. AUC is threshold-free; sensitivity/specificity expose where errors are happening at the chosen cutoff. For a churn use case, sensitivity matters more (catching at-risk customers), so the team might pick a lower threshold to trade specificity for recall. Wrap the whole pipeline in a function (<code>fit_eval(train, test)</code>) for repeatable benchmarking across model families.</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-6-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.3: Loan-default scoring with broom for tidy output</h3>

<p class="exercise-task"><strong>Task:</strong> The risk team needs a one-row-per-coefficient summary table for a loan default model. Fit <code>default ~ fico + dti + loan_amount</code> on the inline <code>loans</code> data, then pipe the fit through <code>broom::tidy(exponentiate = TRUE, conf.int = TRUE)</code> so each row has an odds ratio plus 95% CI. Save the tibble to <code>ex_6_3</code>.</p>

<div class="webr-container">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Interactive R</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(303)
loans &lt;- tibble::tibble(
  fico        = round(rnorm(400, 690, 50)),
  dti         = round(runif(400, 0.05, 0.55), 2),
  loan_amount = round(rlnorm(400, log(20000), 0.5)),
  default     = rbinom(400, 1,
                       plogis(2.5 - 0.012 * rnorm(400, 690, 50) +
                              3.0  * runif(400, 0.05, 0.55) +
                              0.00001 * rlnorm(400, log(20000), 0.5)))
)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 7
#&gt;   term         estimate std.error statistic   p.value conf.low conf.high
#&gt;   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 (Intercept)   1.05e+4    3.05     3.04   2.40e-3      29.9   4.39e+06
#&gt; 2 fico          9.86e-1    0.00451 -3.16   1.59e-3       0.977 9.95e-01
#&gt; 3 dti           3.86e+1    1.13     3.23   1.22e-3       4.65  4.20e+02
#&gt; 4 loan_amount   1.00e+0    0.00001  0.04   9.71e-1       1.00  1.00e+00</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>A tidy coefficient table puts one row per term, with odds ratios and intervals ready for downstream tooling.</p><p>Fit the <code>default ~ fico + dti + loan_amount</code> model, then call <code>broom::tidy()</code> with <code>exponentiate = TRUE</code> and <code>conf.int = TRUE</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit    &lt;- glm(default ~ fico + dti + loan_amount, data = loans, family = binomial)
ex_6_3 &lt;- broom::tidy(fit, exponentiate = TRUE, conf.int = TRUE)
ex_6_3
#&gt; # A tibble: 4 x 7
#&gt;   term         estimate std.error statistic   p.value conf.low conf.high
#&gt;   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 (Intercept)   1.05e+4    3.05      3.04   2.40e-3      29.9   4.39e+06
#&gt; 2 fico          9.86e-1    0.00451  -3.16   1.59e-3       0.977 9.95e-01
#&gt; 3 dti           3.86e+1    1.13      3.23   1.22e-3       4.65  4.20e+02
#&gt; 4 loan_amount   1.00e+0    0.00001   0.04   9.71e-1       1.00  1.00e+00</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>broom::tidy()</code> returns one row per coefficient as a tibble, which composes naturally with <code>dplyr</code>, <code>ggplot2</code>, and <code>gt</code>. <code>exponentiate = TRUE</code> converts log-odds to odds ratios automatically, and <code>conf.int = TRUE</code> adds profile-likelihood CIs. The accompanying <code>broom::glance()</code> returns one row per model (deviance, AIC, df) and <code>broom::augment()</code> returns one row per observation (predicted probabilities, residuals).</p>

</details>

</section>

<section class="exercise" data-exercise-id="Logistic-Regression-Exercises-in-R-ex-6-4" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 6.4: Marketing campaign response: pick the optimal threshold</h3>

<p class="exercise-task"><strong>Task:</strong> A marketing analyst wants to send a follow-up email only to customers whose predicted response probability exceeds a cost-justified threshold. The campaign costs <code>$0.50</code> per email and earns <code>$10</code> per response. Compute the expected-profit-maximizing threshold from the <code>signups</code> model <code>ex_3_3</code>. Save the scalar threshold (rounded to 3 decimals) to <code>ex_6_4</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.05</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A cost-aware cutoff is the threshold that maximizes total expected profit rather than raw accuracy.</p><p>Sweep candidate thresholds with <code>seq()</code>, compute profit per threshold from the $10 reward and $0.50 cost, and pick the best with <code>which.max()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_4 &lt;- # your code here
ex_6_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">probs   &lt;- predict(ex_3_3, type = &quot;response&quot;)
threshs &lt;- seq(0.01, 0.99, by = 0.01)

profit  &lt;- sapply(threshs, function(t) {
  send &lt;- probs &gt; t
  sum(send * (signups$converted * 10 - 0.5))
})

ex_6_4  &lt;- round(threshs[which.max(profit)], 3)
ex_6_4
#&gt; [1] 0.05</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The cost-aware threshold solves "email if expected profit > 0", i.e. <code>p * 10 - 0.5 &gt; 0</code>, which closed-form gives <code>p &gt; 0.05</code>. The empirical sweep recovers the same answer and generalizes to non-linear cost functions (e.g. fatigue limits, daily budgets). Always tie classification thresholds to a business objective, not an off-the-shelf default like 0.5; the right number for a high-volume low-cost campaign is very different from a one-shot expensive intervention.</p>

</details>

</section>

<h2>What to do next</h2>

<p>Reinforce the foundations with these companion hubs and the parent tutorial:</p>

<ul>

<li><a href="Logistic-Regression-With-R.html">Logistic Regression with R</a>: the parent tutorial covering theory, link functions, and assumptions</li>

<li><a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>: the OLS cousin with the same workflow but a continuous outcome</li>

<li><a href="Hypothesis-Testing-Exercises-in-R.html">Hypothesis Testing Exercises in R</a>: t-tests and chi-squared tests that feed <a class="auto-link" href="Variable-Selection-and-Importance-With-R.html" title="Feature Selection and Variable Importance">feature selection</a></li>

<li><a href="Cross-Validation-Exercises-in-R.html">Cross-Validation Exercises in R</a>: k-fold and repeated CV for unbiased model evaluation</li>

</ul>

{% endraw %}