---
title: "Mixed-Effects Models Exercises in R: 18 Practice Problems"
description: "Practice mixed-effects models in R with 18 hands-on problems: lme4 intercepts and slopes, nested designs, GLMM, REML and diagnostics. Hidden solutions."
keywords: "mixed effects models R exercises, lme4 R practice, random effects R exercises, lmer exercises, glmer practice, REML R tutorial"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "mixed effects models|lme4 exercises|random intercepts|random slopes|glmm in r"
auto_link_case_sensitive: false
sidebar_title: "Mixed-Effects Models Exercises"
sidebar_order: "162"
fr_parent: "Multilevel-Models-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Mixed-Effects Models Exercises in R: 18 Practice Problems</h1>

<p class="lead">Eighteen practice problems on mixed-effects models in R, covering random intercepts, random slopes, nested and crossed designs, generalized linear mixed models, REML versus ML inference, and post-fit diagnostics. Every problem ships with the expected output and a hidden solution you can reveal after attempting it.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="45" data-exercises="18" data-xp="270"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(lme4)
library(MuMIn)
library(dplyr)
library(ggplot2)
library(tibble)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Random Intercepts with lme4 (3 problems)</h2>

<h3>Exercise 1.1: Fit a random-intercept model for reaction times by subject</h3>

<p><strong>Task:</strong> The built-in <code>sleepstudy</code> dataset (from <code>lme4</code>) tracks reaction time for 18 subjects over 10 nights of progressive sleep restriction. Fit a model with a fixed effect for <code>Days</code> and a random intercept per <code>Subject</code> using <code>lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)</code>. Save the fitted model to <code>ex_1_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: Reaction ~ Days + (1 | Subject)
#&gt;    Data: sleepstudy
#&gt; REML criterion at convergence: 1786.46
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev.
#&gt;  Subject  (Intercept) 37.12
#&gt;  Residual             30.99
#&gt; Number of obs: 180, groups:  Subject, 18
#&gt; Fixed Effects:
#&gt; (Intercept)         Days
#&gt;      251.41        10.47</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)
ex_1_1
#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: Reaction ~ Days + (1 | Subject)
#&gt;    Data: sleepstudy
#&gt; REML criterion at convergence: 1786.46
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev.
#&gt;  Subject  (Intercept) 37.12
#&gt;  Residual             30.99
#&gt; Number of obs: 180, groups:  Subject, 18
#&gt; Fixed Effects:
#&gt; (Intercept)         Days
#&gt;      251.41        10.47</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The notation <code>(1 | Subject)</code> adds a separate intercept deviation for every level of <code>Subject</code>, while the <code>Days</code> coefficient stays a single population-level slope. The <code>Subject</code> standard deviation of 37.1 ms is far larger than zero, signalling that ignoring subject-to-subject baseline differences (i.e., a plain <code>lm()</code>) would underestimate uncertainty for the <code>Days</code> effect. REML is the default estimator because it gives less biased variance components than ML when group counts are modest.</p>

</details>

<h3>Exercise 1.2: Compute the intraclass correlation coefficient from variance components</h3>

<p><strong>Task:</strong> A sleep researcher reviewing your random-intercept fit wants the share of total residual variability that lives between subjects rather than within. From <code>ex_1_1</code>, extract the subject-level variance and residual variance using <code>VarCorr()</code>, then compute the <a class="auto-link" href="Multilevel-Models-in-R.html" title="Multilevel Models in R With brms: When Group Differences Beat Group Averages">intraclass correlation</a> as $\rho = \sigma_{\text{subj}}^2 / (\sigma_{\text{subj}}^2 + \sigma_{\text{resid}}^2)$. Save the scalar to <code>ex_1_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; (Intercept)
#&gt;   0.5893481</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">vc &lt;- VarCorr(ex_1_1)
sigma_subj_sq  &lt;- attr(vc$Subject, &quot;stddev&quot;)^2
sigma_resid_sq &lt;- attr(vc, &quot;sc&quot;)^2
ex_1_2 &lt;- sigma_subj_sq / (sigma_subj_sq + sigma_resid_sq)
ex_1_2
#&gt; (Intercept)
#&gt;   0.5893481</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>VarCorr()</code> returns a list with one entry per grouping factor plus a residual scale stored as the <code>&quot;sc&quot;</code> attribute. Squaring the standard deviations gives the variances on the original response scale. An ICC near 0.59 means almost 60% of the unexplained variance after accounting for <code>Days</code> is between-subject, so any inference that ignores grouping (pseudo-<a class="auto-link" href="Experimental-Design-Principles-in-R.html" title="Experimental Design in R: The Three Principles That Make Results Valid and Generalisable">replication</a>) will badly understate standard errors. The <code>performance::icc()</code> helper computes the same quantity in one call.</p>

</details>

<h3>Exercise 1.3: Extract subject-level BLUPs and order them by baseline reaction time</h3>

<p><strong>Task:</strong> You want to see which subjects have the slowest baseline reaction time after partialling out the average <code>Days</code> effect. Extract the conditional modes (BLUPs) from <code>ex_1_1</code> with <code>ranef()</code>, coerce them to a data frame with <code>Subject</code> as a column, and sort ascending by the intercept deviation. Save the ordered data frame to <code>ex_1_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;    Subject intercept_dev
#&gt; 1      335     -25.27598
#&gt; 2      309     -71.41859
#&gt; 3      310     -57.74656
#&gt; ...
#&gt; # 15 more rows (sorted ascending)
#&gt; Subject 308 ends with intercept_dev ~ 40.78 (slowest baseline)</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
head(ex_1_3, 3)
tail(ex_1_3, 1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">re &lt;- as.data.frame(ranef(ex_1_1)$Subject)
ex_1_3 &lt;- tibble(
  Subject = rownames(re),
  intercept_dev = re[, 1]
) |&gt; arrange(intercept_dev)
head(ex_1_3, 3)
tail(ex_1_3, 1)
#&gt; # tibble: head shows subjects 335, 309, 310 with the most negative deviations
#&gt; # tail shows Subject 308 with intercept_dev ~ 40.78 ms above the fixed intercept</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>ranef()</code> returns shrinkage estimates: subject deviations are pulled toward zero in proportion to how little data each subject contributes. These are not the same as fitting 18 separate intercepts with <code>lm()</code>: BLUPs borrow strength across subjects and produce smaller <a class="auto-link" href="Point-Estimation-in-R.html" title="Point Estimation in R: What Makes an Estimator Good? Bias, Variance, and MSE">mean squared error</a> for new predictions. Coercing to a tibble keeps the subject IDs as a column instead of leaving them buried in <code>rownames</code>, which is the form most downstream plotting and joining steps want.</p>

</details>

<h2>Section 2. Random Slopes and Correlated Effects (3 problems)</h2>

<h3>Exercise 2.1: Add a random slope for Days varying by Subject</h3>

<p><strong>Task:</strong> Inspecting the per-subject trajectories you noticed that some subjects degrade much faster than others as <code>Days</code> increases. Extend the previous model to let each subject have their own slope: fit <code>Reaction ~ Days + (Days | Subject)</code> on <code>sleepstudy</code> with <code>lmer()</code>. Save the fit to <code>ex_2_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: Reaction ~ Days + (Days | Subject)
#&gt;    Data: sleepstudy
#&gt; REML criterion at convergence: 1743.63
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev. Corr
#&gt;  Subject  (Intercept) 24.74
#&gt;           Days         5.92    0.07
#&gt;  Residual             25.59
#&gt; Number of obs: 180, groups:  Subject, 18
#&gt; Fixed Effects:
#&gt; (Intercept)         Days
#&gt;      251.41        10.47</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)
ex_2_1
#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: Reaction ~ Days + (Days | Subject)
#&gt;    Data: sleepstudy
#&gt; REML criterion at convergence: 1743.63
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev. Corr
#&gt;  Subject  (Intercept) 24.74
#&gt;           Days         5.92    0.07
#&gt;  Residual             25.59
#&gt; Number of obs: 180, groups:  Subject, 18</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>(Days | Subject)</code> is shorthand for <code>(1 + Days | Subject)</code>: an intercept and a slope per subject, with a covariance between them estimated from the data. The residual SD drops from 31 to 26 ms because per-subject variation in the rate of decline is no longer absorbed into the noise term. The fixed-effect estimates (251.4, 10.47) are unchanged because the design is balanced; in unbalanced data they would shift.</p>

</details>

<h3>Exercise 2.2: Inspect the correlation between random intercepts and slopes</h3>

<p><strong>Task:</strong> The reviewer asks whether subjects who start slow also degrade faster (positive intercept-slope correlation) or whether the two are independent. From <code>ex_2_1</code>, extract the correlation between the random intercept and the random slope from the <code>VarCorr()</code> output using <code>attr(VarCorr(ex_2_1)$Subject, &quot;correlation&quot;)[1, 2]</code>. Save the scalar to <code>ex_2_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.06632237</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- attr(VarCorr(ex_2_1)$Subject, &quot;correlation&quot;)[1, 2]
ex_2_2
#&gt; [1] 0.06632237</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The random-effects <a class="auto-link" href="Correlation-Analysis-in-R.html" title="Correlation in R: Pearson vs Spearman vs Kendall — Compute, Test, and Visualise">correlation matrix</a> is attached as an attribute on each grouping factor's variance-<a class="auto-link" href="Multivariate-Statistics-in-R.html" title="Multivariate Statistics in R: Distances, Mahalanobis, and Hotelling's T² Demystified">covariance matrix</a>; the off-diagonal element <code>[1, 2]</code> is the corr between intercept and <code>Days</code>. A value near 0.07 is effectively zero given the small subject count, meaning baseline reaction time tells you little about how steeply someone deteriorates. If this correlation were estimated as exactly ±1 it would signal a singular fit; consider <code>(Days || Subject)</code> (the double-bar form, which forces zero correlation) or refitting with a simpler random structure.</p>

</details>

<h3>Exercise 2.3: Compare random-intercept vs random-slope fits with anova</h3>

<p><strong>Task:</strong> To decide whether the slope term is worth the two extra parameters, compare the simpler <code>ex_1_1</code> against the richer <code>ex_2_1</code>. Pass both to <code>anova()</code>, which automatically refits with ML to make the <a class="auto-link" href="Likelihood-Ratio-Wald-and-Score-Tests-in-R.html" title="Likelihood Ratio, Wald & Score Tests in R: Three Ways to Test Hypotheses">likelihood ratio test</a> valid. Save the returned anova table to <code>ex_2_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; refitting model(s) with ML (instead of REML)
#&gt; Data: sleepstudy
#&gt; Models:
#&gt; ex_1_1: Reaction ~ Days + (1 | Subject)
#&gt; ex_2_1: Reaction ~ Days + (Days | Subject)
#&gt;        npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
#&gt; ex_1_1    4 1802.1 1814.8 -897.04   1794.1
#&gt; ex_2_1    6 1763.9 1783.1 -875.97   1751.9 42.139  2  1.226e-09 ***</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- anova(ex_1_1, ex_2_1)
ex_2_3
#&gt; refitting model(s) with ML (instead of REML)
#&gt; Models:
#&gt; ex_1_1: Reaction ~ Days + (1 | Subject)
#&gt; ex_2_1: Reaction ~ Days + (Days | Subject)
#&gt;        npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
#&gt; ex_1_1    4 1802.1 1814.8 -897.04   1794.1
#&gt; ex_2_1    6 1763.9 1783.1 -875.97   1751.9 42.139  2  1.226e-09 ***</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A likelihood ratio test for nested models requires ML, not REML, because REML log-likelihoods compare differently parameterised mean structures incorrectly. <code>anova.merMod()</code> quietly refits both models with <code>REML = FALSE</code> before computing the chi-square. Note that the LRT is known to be conservative on the boundary of the parameter space (testing whether a variance is zero), so the true <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">p-value</a> is likely even smaller; for borderline cases use parametric bootstrap with <code>pbkrtest::PBmodcomp()</code>.</p>

</details>

<h2>Section 3. Nested and Crossed Random Effects (3 problems)</h2>

<h3>Exercise 3.1: Build a nested random-effects model for ChickWeight</h3>

<p><strong>Task:</strong> An agronomist running a chick-feed trial gives you <code>ChickWeight</code>: weight measured at 12 time points for 50 chicks across 4 diets. Fit <code>weight ~ Time + Diet + (Time | Chick)</code> with <code>lmer()</code> so each chick has its own growth trajectory while diet enters as a fixed effect. Save the fit to <code>ex_3_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: weight ~ Time + Diet + (Time | Chick)
#&gt;    Data: ChickWeight
#&gt; REML criterion at convergence: 4824.1
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev. Corr
#&gt;  Chick    (Intercept) 11.27         
#&gt;           Time         3.91    -0.99
#&gt;  Residual             14.04         
#&gt; Number of obs: 578, groups:  Chick, 50
#&gt; Fixed Effects:
#&gt; (Intercept)         Time        Diet2        Diet3        Diet4
#&gt;      28.50        8.75        16.18        36.50        30.23</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- lmer(weight ~ Time + Diet + (Time | Chick), data = ChickWeight)
ex_3_1
#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: weight ~ Time + Diet + (Time | Chick)
#&gt;    Data: ChickWeight
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev. Corr
#&gt;  Chick    (Intercept) 11.27
#&gt;           Time         3.91    -0.99
#&gt;  Residual             14.04
#&gt; Number of obs: 578, groups:  Chick, 50</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Each <code>Chick</code> only ever receives one <code>Diet</code>, so <code>Chick</code> is implicitly nested inside <code>Diet</code>; you do not need <code>Diet/Chick</code> in the random part because the diet effect is captured as a fixed factor. The near-perfect negative correlation (-0.99) between random intercept and slope is a classic warning sign: the model is on the boundary, often because the time variable is not centred. Re-running with <code>Time</code> centred at its mean usually returns a sensible correlation and a non-degenerate covariance matrix.</p>

</details>

<h3>Exercise 3.2: Distinguish nested from crossed structure with implicit nesting</h3>

<p><strong>Task:</strong> An education researcher hands you a small school dataset where <code>class_id</code> values "1" and "2" both reappear inside three different schools "A", "B", "C". She wants the model to treat 1A and 1B as different classrooms. Build the tibble below and fit the correctly nested model <code>score ~ 1 + (1 | school_id/class_id)</code>. Save the nested fit to <code>ex_3_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: score ~ 1 + (1 | school_id/class_id)
#&gt; Random effects:
#&gt;  Groups              Name        Std.Dev.
#&gt;  class_id:school_id  (Intercept)  6.4
#&gt;  school_id           (Intercept)  3.9
#&gt;  Residual                         4.7
#&gt; Number of obs: 60, groups:  class_id:school_id, 6; school_id, 3</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
classrooms &lt;- tibble(
  school_id = rep(c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;), each = 20),
  class_id  = rep(rep(c(&quot;1&quot;, &quot;2&quot;), each = 10), times = 3),
  score     = rnorm(60, mean = 70, sd = 8)
)
ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
classrooms &lt;- tibble(
  school_id = rep(c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;), each = 20),
  class_id  = rep(rep(c(&quot;1&quot;, &quot;2&quot;), each = 10), times = 3),
  score     = rnorm(60, mean = 70, sd = 8)
)
ex_3_2 &lt;- lmer(score ~ 1 + (1 | school_id/class_id), data = classrooms)
ex_3_2
#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: score ~ 1 + (1 | school_id/class_id)
#&gt;  Groups              Name        Std.Dev.
#&gt;  class_id:school_id  (Intercept) ~ 6.4
#&gt;  school_id           (Intercept) ~ 3.9
#&gt;  Residual                       ~ 4.7
#&gt; Number of obs: 60, groups:  class_id:school_id, 6; school_id, 3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The shorthand <code>school_id/class_id</code> expands to <code>school_id + school_id:class_id</code>, which creates the interaction grouping factor needed when class labels are reused across schools. Writing <code>(1 | school_id) + (1 | class_id)</code> instead would tell <code>lmer()</code> that class "1" is the same unit in every school, which is wrong. The cleaner long-term fix is to mint globally unique class IDs (<code>paste(school_id, class_id, sep = &quot;_&quot;)</code>) and use <code>(1 | school_id) + (1 | unique_class)</code> so the structure is explicit in the data, not implicit in the formula.</p>

</details>

<h3>Exercise 3.3: Fit crossed random effects for subjects rated on shared items</h3>

<p><strong>Task:</strong> A psycholinguist runs an experiment where each of 30 subjects rates each of 20 items under one of two conditions (fully crossed). Build the tibble below and fit <code>rating ~ condition + (1 | subj) + (1 | item)</code> to absorb subject-level and item-level variability simultaneously. Save the fit to <code>ex_3_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Linear mixed model fit by REML ['lmerMod']
#&gt; Formula: rating ~ condition + (1 | subj) + (1 | item)
#&gt; Random effects:
#&gt;  Groups   Name        Std.Dev.
#&gt;  subj     (Intercept)  0.92
#&gt;  item     (Intercept)  1.05
#&gt;  Residual              1.50
#&gt; Number of obs: 600, groups:  subj, 30; item, 20
#&gt; Fixed Effects:
#&gt; (Intercept)   conditionB
#&gt;      4.10         0.45</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
psy &lt;- tibble(
  subj = rep(sprintf(&quot;s%02d&quot;, 1:30), each = 20),
  item = rep(sprintf(&quot;i%02d&quot;, 1:20), times = 30),
  condition = sample(c(&quot;A&quot;, &quot;B&quot;), 600, replace = TRUE)
)
psy$rating &lt;- 4 + 0.5 * (psy$condition == &quot;B&quot;) +
  rnorm(30, sd = 0.9)[as.integer(factor(psy$subj))] +
  rnorm(20, sd = 1.0)[as.integer(factor(psy$item))] +
  rnorm(600, sd = 1.5)
ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
psy &lt;- tibble(
  subj = rep(sprintf(&quot;s%02d&quot;, 1:30), each = 20),
  item = rep(sprintf(&quot;i%02d&quot;, 1:20), times = 30),
  condition = sample(c(&quot;A&quot;, &quot;B&quot;), 600, replace = TRUE)
)
psy$rating &lt;- 4 + 0.5 * (psy$condition == &quot;B&quot;) +
  rnorm(30, sd = 0.9)[as.integer(factor(psy$subj))] +
  rnorm(20, sd = 1.0)[as.integer(factor(psy$item))] +
  rnorm(600, sd = 1.5)
ex_3_3 &lt;- lmer(rating ~ condition + (1 | subj) + (1 | item), data = psy)
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Crossed effects appear when every level of one grouping factor (subjects) is observed with every level of another (items). Treating items as a fixed factor would burn 19 degrees of freedom and prevent generalization to new items; treating them as random instead lets you generalize the <code>condition</code> effect to the broader population of stimuli. Barr et al.'s "keep it maximal" advice would also add random slopes for <code>condition</code> by both subject and item, but that often fails to converge with small designs.</p>

</details>

<h2>Section 4. Model Comparison and Inference (3 problems)</h2>

<h3>Exercise 4.1: Refit with REML=FALSE for a likelihood ratio test of the fixed slope</h3>

<p><strong>Task:</strong> A reviewer wants a formal test of whether the <code>Days</code> fixed effect is needed at all. To do a likelihood ratio test for a fixed effect you must refit with <code>REML = FALSE</code>. Fit a null model <code>Reaction ~ 1 + (Days | Subject)</code> and a full model <code>Reaction ~ Days + (Days | Subject)</code>, both with <code>REML = FALSE</code>, then run <code>anova(null, full)</code>. Save the anova table to <code>ex_4_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Models:
#&gt; mod_null: Reaction ~ 1 + (Days | Subject)
#&gt; mod_full: Reaction ~ Days + (Days | Subject)
#&gt;          npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
#&gt; mod_null    5 1785.5 1801.5 -887.74   1775.5
#&gt; mod_full    6 1763.9 1783.1 -875.97   1751.9 23.54  1  1.23e-06 ***</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_null &lt;- # null fit
mod_full &lt;- # full fit
ex_4_1 &lt;- # anova table
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_null &lt;- lmer(Reaction ~ 1 + (Days | Subject), data = sleepstudy, REML = FALSE)
mod_full &lt;- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy, REML = FALSE)
ex_4_1 &lt;- anova(mod_null, mod_full)
ex_4_1
#&gt; Models:
#&gt; mod_null: Reaction ~ 1 + (Days | Subject)
#&gt; mod_full: Reaction ~ Days + (Days | Subject)
#&gt;          npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
#&gt; mod_null    5 1785.5 1801.5 -887.74   1775.5
#&gt; mod_full    6 1763.9 1783.1 -875.97   1751.9 23.54  1  1.23e-06 ***</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> REML estimates variance components after profiling out the fixed effects, so the REML log-likelihood depends on the fixed-effect design matrix and is not comparable between models with different fixed parts. Switching to ML with <code>REML = FALSE</code> fixes this. For random-effect tests (testing whether a variance is zero) the opposite advice applies: use REML, because ML biases variance estimates downward, especially with few groups.</p>

</details>

<h3>Exercise 4.2: Get Satterthwaite p-values for fixed effects with lmerTest</h3>

<p><strong>Task:</strong> Base <code>lme4</code> deliberately omits p-values for fixed effects because the reference distribution is unknown in small samples. Load <code>lmerTest</code>, refit <code>ex_2_1</code>, then call <code>summary()</code> on the new fit and pull out the <code>coefficients</code> matrix which now carries Satterthwaite degrees of freedom and t-tests. Save the coefficients matrix to <code>ex_4_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;             Estimate Std. Error    df t value Pr(&gt;|t|)
#&gt; (Intercept)  251.405      6.825 17.00   36.84  &lt; 2e-16 ***
#&gt; Days          10.467      1.546 17.00    6.77 3.27e-06 ***</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(lmerTest)
fit_lt &lt;- # refit with lmerTest::lmer
ex_4_2 &lt;- # coefficients matrix from summary()
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(lmerTest)
fit_lt &lt;- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)
ex_4_2 &lt;- summary(fit_lt)$coefficients
ex_4_2
#&gt;             Estimate Std. Error    df t value Pr(&gt;|t|)
#&gt; (Intercept)  251.405      6.825 17.00   36.84  &lt; 2e-16 ***
#&gt; Days          10.467      1.546 17.00    6.77 3.27e-06 ***</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>lmerTest</code> masks <code>lme4::lmer()</code> and attaches Satterthwaite-approximate degrees of freedom and t-tests to the summary. Df of 17 reflects the 18-subject design (n_groups - 1). Use Kenward-Roger (<code>lmerTest::lmer(..., ddf = &quot;Kenward-Roger&quot;)</code>) for smaller designs where Satterthwaite under-covers; it is slower but typically more accurate. Loading <code>lmerTest</code> after <code>lme4</code> is the canonical order, since you want the p-value-aware <code>lmer()</code> to win the name conflict.</p>

</details>

<h3>Exercise 4.3: Bootstrap a 95% confidence interval for the fixed slope</h3>

<p><strong>Task:</strong> The reviewer is sceptical of Satterthwaite for skewed responses and asks for a parametric bootstrap CI on the <code>Days</code> coefficient. Run <code>confint(ex_2_1, parm = &quot;Days&quot;, method = &quot;boot&quot;, nsim = 200, seed = 1)</code> and save the resulting 2-column matrix to <code>ex_4_3</code>. Use 200 simulations for speed; in published work use at least 2000.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;          2.5 %    97.5 %
#&gt; Days  7.95     12.95</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- confint(ex_2_1,
                  parm   = &quot;Days&quot;,
                  method = &quot;boot&quot;,
                  nsim   = 200,
                  seed   = 1)
ex_4_3
#&gt;          2.5 %    97.5 %
#&gt; Days  7.95     12.95</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Parametric bootstrap simulates new responses from the fitted model and refits each replicate; the empirical quantiles of the replicate coefficient form the CI. This is more honest than Wald intervals when the <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">sampling distribution</a> is asymmetric, which often happens for variance components and GLMM coefficients. The <code>seed</code> argument makes the run reproducible; without it, two readers running the same code see slightly different CIs.</p>

</details>

<h2>Section 5. Generalized Linear Mixed Models (3 problems)</h2>

<h3>Exercise 5.1: Fit a binomial GLMM with random subject intercepts</h3>

<p><strong>Task:</strong> A clinical trial team tracks weekly medication adherence (1 = took it, 0 = missed) over 8 visits for 50 patients across two treatment arms. Build the inline dataset below and fit <code>glmer(adherence ~ arm + (1 | patient), family = binomial)</code>. Save the fit to <code>ex_5_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Generalized linear mixed model fit by maximum likelihood (Laplace Approximation)
#&gt;  Family: binomial  ( logit )
#&gt; Formula: adherence ~ arm + (1 | patient)
#&gt;    Data: trial
#&gt; Random effects:
#&gt;  Groups  Name        Std.Dev.
#&gt;  patient (Intercept) 1.18
#&gt; Number of obs: 400, groups:  patient, 50
#&gt; Fixed Effects:
#&gt; (Intercept)     armB
#&gt;      0.45      0.71</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(3)
trial &lt;- tibble(
  patient   = rep(sprintf(&quot;p%02d&quot;, 1:50), each = 8),
  arm       = rep(sample(c(&quot;A&quot;, &quot;B&quot;), 50, replace = TRUE), each = 8)
)
trial$adherence &lt;- rbinom(400, 1, plogis(
  0.5 + 0.7 * (trial$arm == &quot;B&quot;) +
    rnorm(50, sd = 1.1)[as.integer(factor(trial$patient))]
))
ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(3)
trial &lt;- tibble(
  patient = rep(sprintf(&quot;p%02d&quot;, 1:50), each = 8),
  arm     = rep(sample(c(&quot;A&quot;, &quot;B&quot;), 50, replace = TRUE), each = 8)
)
trial$adherence &lt;- rbinom(400, 1, plogis(
  0.5 + 0.7 * (trial$arm == &quot;B&quot;) +
    rnorm(50, sd = 1.1)[as.integer(factor(trial$patient))]
))
ex_5_1 &lt;- glmer(adherence ~ arm + (1 | patient),
                family = binomial,
                data   = trial)
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A patient who is "compliant" tends to stay compliant across all 8 visits; a random intercept absorbs that within-person correlation so the <code>arm</code> coefficient gets honest standard errors. <code>glmer</code> defaults to the Laplace approximation, fast and adequate for binary outcomes with reasonable group sizes. For more accuracy use <code>nAGQ</code> = 10 or higher (adaptive Gauss-Hermite quadrature), but it only works for single-grouping-factor models.</p>

</details>

<h3>Exercise 5.2: Fit a Poisson GLMM with an offset for sequencing depth</h3>

<p><strong>Task:</strong> A geneticist counts read hits to a target gene across 30 RNA-seq samples in 4 tissue types. Because total sequencing depth varies, the model needs an <code>offset(log(read_total))</code> so the coefficients describe rates per read. Build the inline dataset below and fit <code>glmer(hits ~ tissue + (1 | sample) + offset(log(read_total)), family = poisson)</code>. Save the fit to <code>ex_5_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Generalized linear mixed model fit by maximum likelihood (Laplace Approximation)
#&gt;  Family: poisson  ( log )
#&gt; Formula: hits ~ tissue + (1 | sample) + offset(log(read_total))
#&gt; Random effects:
#&gt;  Groups Name        Std.Dev.
#&gt;  sample (Intercept) 0.21
#&gt; Number of obs: 30, groups:  sample, 30
#&gt; Fixed Effects:
#&gt; (Intercept)   tissueB   tissueC   tissueD
#&gt;     -7.55      0.32      0.81     -0.46</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(19)
rna &lt;- tibble(
  sample     = sprintf(&quot;s%02d&quot;, 1:30),
  tissue     = rep(c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;), length.out = 30),
  read_total = round(rlnorm(30, meanlog = 14.5, sdlog = 0.3))
)
rna$hits &lt;- rpois(30, lambda = exp(
  -7.5 +
    0.3 * (rna$tissue == &quot;B&quot;) +
    0.8 * (rna$tissue == &quot;C&quot;) -
    0.5 * (rna$tissue == &quot;D&quot;) +
    log(rna$read_total) +
    rnorm(30, sd = 0.2)
))
ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(19)
rna &lt;- tibble(
  sample     = sprintf(&quot;s%02d&quot;, 1:30),
  tissue     = rep(c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;), length.out = 30),
  read_total = round(rlnorm(30, meanlog = 14.5, sdlog = 0.3))
)
rna$hits &lt;- rpois(30, lambda = exp(
  -7.5 +
    0.3 * (rna$tissue == &quot;B&quot;) +
    0.8 * (rna$tissue == &quot;C&quot;) -
    0.5 * (rna$tissue == &quot;D&quot;) +
    log(rna$read_total) +
    rnorm(30, sd = 0.2)
))
ex_5_2 &lt;- glmer(hits ~ tissue + (1 | sample) + offset(log(read_total)),
                family = poisson,
                data   = rna)
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Including <code>log(read_total)</code> as an offset (coefficient fixed at 1) reparameterises counts as rates: the linear predictor returns <code>log(hits / read_total)</code>. Without the offset, deeply sequenced samples would have systematically higher counts and the tissue coefficients would absorb that noise. The random intercept on <code>sample</code> handles residual library-prep variation beyond what depth captures; with only one observation per sample it is identified by the Poisson mean-variance link.</p>

</details>

<h3>Exercise 5.3: Check overdispersion in a Poisson GLMM with the Pearson chi-square ratio</h3>

<p><strong>Task:</strong> Poisson assumes variance equals mean, which is rarely true for real count data. From <code>ex_5_2</code>, compute the dispersion statistic as <code>sum(residuals(ex_5_2, type = &quot;pearson&quot;)^2) / df.residual(ex_5_2)</code>. A value much above 1 (say, > 1.5) flags <a class="auto-link" href="Poisson-Regression-in-R.html" title="Poisson Regression in R: Model Count Data and Handle Overdispersion">overdispersion</a> and motivates a negative binomial or observation-level random effect. Save the scalar to <code>ex_5_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 1.03</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- sum(residuals(ex_5_2, type = &quot;pearson&quot;)^2) / df.residual(ex_5_2)
ex_5_3
#&gt; [1] 1.03</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A dispersion of about 1.0 says the Poisson mean-variance assumption fits the data, partly because the <code>(1 | sample)</code> random intercept acts as an observation-level random effect that already soaks up extra variance. If this number came back at 3 you would refit with <code>glmer.nb()</code> (negative binomial) or add an explicit observation-level random effect like <code>(1 | obs_id)</code> where <code>obs_id</code> is unique per row. <code>performance::check_overdispersion()</code> automates the whole check.</p>

</details>

<h2>Section 6. Diagnostics and Prediction (3 problems)</h2>

<h3>Exercise 6.1: Plot residuals versus fitted to inspect homoscedasticity</h3>

<p><strong>Task:</strong> Before trusting any standard error from <code>ex_2_1</code>, you want to see whether residuals fan out with fitted reaction time (<a class="auto-link" href="Heteroscedasticity-in-R.html" title="Heteroscedasticity in R: Breusch-Pagan Test & Robust Standard Errors">heteroscedasticity</a>) or curve (model mis-specification). Build a tibble of <code>fitted = fitted(ex_2_1)</code> and <code>resid = resid(ex_2_1)</code>, then plot with <code>ggplot()</code> adding a horizontal zero line and a <code>geom_smooth(se = FALSE)</code> trend. Save the ggplot to <code>ex_6_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ggplot object: points roughly centred on y = 0 across fitted range
#&gt;   - x axis: Fitted (range ~ 200 to 460 ms)
#&gt;   - y axis: Residual (range ~ -100 to 100 ms)
#&gt;   - red horizontal line at y = 0
#&gt;   - blue loess smoother stays close to zero with no obvious funnel</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">diag_df &lt;- tibble(
  fitted = fitted(ex_2_1),
  resid  = resid(ex_2_1)
)
ex_6_1 &lt;- ggplot(diag_df, aes(fitted, resid)) +
  geom_hline(yintercept = 0, colour = &quot;red&quot;) +
  geom_point(alpha = 0.5) +
  geom_smooth(se = FALSE) +
  labs(x = &quot;Fitted (ms)&quot;, y = &quot;Residual (ms)&quot;,
       title = &quot;Residuals vs Fitted for sleepstudy random-slope fit&quot;)
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Mixed-effects fits return residuals conditional on the random effects, so a flat scatter centred on zero is the diagnostic of choice. A funnel shape (variance growing with the mean) would suggest a log-transform on the response; a curved trend would suggest a non-linear time effect, e.g., a spline on <code>Days</code>. <code>DHARMa::simulateResiduals()</code> produces simulation-based residuals that are uniform on [0, 1] under a correct model and is more reliable for GLMM diagnostics.</p>

</details>

<h3>Exercise 6.2: Predict the population-average curve for new days</h3>

<p><strong>Task:</strong> A reaction-time experimenter writes up the paper and wants the population-average curve (not subject-specific) for <code>Days = 0</code> through <code>9</code>. Use <code>predict(ex_2_1, newdata = data.frame(Days = 0:9), re.form = NA)</code> to suppress random effects. Save the length-10 numeric vector to <code>ex_6_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;      1      2      3      4      5      6      7      8      9     10
#&gt; 251.41 261.88 272.34 282.81 293.28 303.74 314.21 324.68 335.14 345.61</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- predict(ex_2_1,
                  newdata = data.frame(Days = 0:9),
                  re.form = NA)
ex_6_2
#&gt;      1      2      3      4      5      6      7      8      9     10
#&gt; 251.41 261.88 272.34 282.81 293.28 303.74 314.21 324.68 335.14 345.61</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Setting <code>re.form = NA</code> (or equivalently <code>~0</code>) zeros out random effects, giving the marginal expectation: what the average subject would do. Using <code>re.form = NULL</code> (the default) would still need a <code>Subject</code> value in <code>newdata</code> to add the subject-specific deviations. For uncertainty around these population predictions, use <code>merTools::predictInterval()</code> or a parametric bootstrap, since <code>predict.merMod()</code> does not return standard errors.</p>

</details>

<h3>Exercise 6.3: Compute marginal and conditional R-squared with MuMIn</h3>

<p><strong>Task:</strong> A reviewer asks how much of the variability in <code>Reaction</code> is captured by the fixed effect <code>Days</code> alone versus the full model including random effects. Use <code>MuMIn::r.squaredGLMM(ex_2_1)</code> which returns a single-row matrix with columns <code>R2m</code> (fixed only) and <code>R2c</code> (fixed + random). Save the matrix to <code>ex_6_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;            R2m       R2c
#&gt; [1,] 0.2786443 0.7992246</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- MuMIn::r.squaredGLMM(ex_2_1)
ex_6_3
#&gt;            R2m       R2c
#&gt; [1,] 0.2786443 0.7992246</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Nakagawa-Schielzeth marginal R² (R2m) is the share of variance the fixed predictors alone explain; conditional R² (R2c) adds the variance soaked up by random effects. The gap (about 52 percentage points here) is the share captured by subject-to-subject heterogeneity, not by <code>Days</code>. For GLMMs you get two flavours of each (theoretical and delta-method), so the function returns a 2x2 matrix; the <code>theoretical</code> row is usually the one to report.</p>

</details>

<h2>What to do next</h2>

<ul>

<li>Read <a href="Multilevel-Models-in-R.html">Multilevel Models in R</a> for the conceptual map: when nesting matters, how shrinkage works, and how mixed-effects sits between fixed-effect and Bayesian hierarchical models.</li>

<li>Practice the underlying <a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a> to sharpen your intuition for the fixed-effect side before stacking random effects on top.</li>

<li>Work through <a href="ANOVA-Exercises-in-R.html">ANOVA Exercises in R</a> to see how repeated-measures ANOVA, the classical predecessor of mixed-effects models, handles the same correlated-residual problem with a different formalism.</li>

<li>Try the <a href="Generalized-Linear-Models-in-R-Exercises.html">Generalized Linear Models in R Exercises</a> to build comfort with <code>glm()</code> and link functions before tackling the GLMM material in Section 5.</li>

</ul>

{% endraw %}