---
title: "Multiple Regression Exercises in R: 17 Real-World Practice Problems"
description: "17 multiple regression exercises in R with runnable solutions: fit models, interpret partial slopes, run anova(), check VIF, diagnose residuals, predict."
keywords: "multiple regression exercises in R, multiple regression practice problems, multiple linear regression R, VIF multicollinearity R, regression diagnostics, stepwise regression R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "multiple regression exercises|multiple regression practice|multiple regression problems|multiple regression questions|regression exercises in R"
auto_link_case_sensitive: false
sidebar_title: "Multiple Regression Exercises"
sidebar_order: "142"
fr_parent: "Multiple-Regression-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Multiple Regression Exercises in R: 17 Real-World Practice Problems</h1>

<p class="lead">Seventeen practice problems that walk you through fitting multiple <a class="auto-link" href="adv-regression-models.html" title="Advanced Regression Models">regression models</a> in R, reading partial slopes, comparing nested models with <a class="auto-link" href="Two-Way-ANOVA-in-R.html" title="Two-Way ANOVA in R: Main Effects, Interactions, and Interaction Plots Interpreted">anova()</a>, checking VIF for multicollinearity, diagnosing residuals, adding interactions and polynomial terms, and predicting on a held-out slice. Every problem ships with a runnable scaffold, the expected printed output, and a hidden solution with an explanation you can self-check against.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="40" data-exercises="21" data-xp="315"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(dplyr)
library(ggplot2)
library(car)
library(lmtest)
library(broom)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Fit and interpret a multiple regression (4 problems)</h2>

<h3>Exercise 1.1: Fit a two-predictor model and pull both coefficients</h3>

<p><strong>Task:</strong> Use <code>mtcars</code> to fit a multiple regression of <code>mpg</code> on <code>wt</code> and <code>hp</code>. Save the fitted model object to <code>ex_1_1</code> so subsequent problems can reuse it, then print the named coefficient vector with <code>coef()</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; (Intercept)          wt          hp
#&gt; 37.22727012 -3.87783074 -0.03177295</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
coef(ex_1_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- lm(mpg ~ wt + hp, data = mtcars)
coef(ex_1_1)
#&gt; (Intercept)          wt          hp
#&gt; 37.22727012 -3.87783074 -0.03177295</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The formula <code>mpg ~ wt + hp</code> tells <code>lm()</code> to estimate one intercept and two partial slopes. <code>coef()</code> returns a named numeric vector, which is the cleanest way to grab a single slope by name later (e.g. <code>coef(ex_1_1)[&quot;wt&quot;]</code>). Each slope is conditional: the <code>wt</code> slope is the effect of weight after holding horsepower fixed, not the marginal effect of weight on its own.</p>

</details>

<h3>Exercise 1.2: Interpret a partial slope as a one-unit change</h3>

<p><strong>Task:</strong> Using the <code>ex_1_1</code> model from the previous exercise, compute the expected change in <code>mpg</code> when <code>wt</code> increases by 0.5 (half a thousand pounds) while <code>hp</code> stays constant. Save the scalar to <code>ex_1_2</code> (it should be negative).</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] -1.938915</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- unname(coef(ex_1_1)[&quot;wt&quot;] * 0.5)
ex_1_2
#&gt; [1] -1.938915</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A partial slope is the predicted change in the outcome per unit change in that predictor, holding the others fixed. Multiplying the slope by the size of the move (0.5) gives the predicted change directly. <code>unname()</code> strips the carried-over <code>wt</code> name so the result is a clean scalar, which matters when you feed numbers into reporting tables.</p>

</details>

<h3>Exercise 1.3: Build a 95 percent confidence interval for one coefficient</h3>

<p><strong>Task:</strong> From <code>ex_1_1</code>, use <code>confint()</code> to extract the 95 percent confidence interval for the <code>hp</code> coefficient only. Save the resulting two-element named numeric vector (the lower and upper bound) to <code>ex_1_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;       2.5 %      97.5 %
#&gt; -0.05024078 -0.01330512</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- confint(ex_1_1, parm = &quot;hp&quot;, level = 0.95)[1, ]
ex_1_3
#&gt;       2.5 %      97.5 %
#&gt; -0.05024078 -0.01330512</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>confint()</code> returns a matrix with one row per coefficient. Passing <code>parm = &quot;hp&quot;</code> limits the rows it computes, and <code>[1, ]</code> collapses the single row to a named vector. The interval excludes zero, which is the geometric statement of "p < 0.05" for that coefficient. Pair the slope with its interval whenever you report a regression result, because a slope without a width is incomplete information.</p>

</details>

<h3>Exercise 1.4: Extract Adjusted R-squared programmatically</h3>

<p><strong>Task:</strong> Fit a three-predictor model of <code>mpg</code> on <code>wt</code>, <code>hp</code>, and <code>cyl</code> using <code>mtcars</code>. Pull the adjusted R-squared from the <code>summary()</code> object (do not retype the number from the printout). Save the scalar to <code>ex_1_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.8327</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
round(ex_1_4, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ wt + hp + cyl, data = mtcars)
ex_1_4 &lt;- summary(fit)$adj.r.squared
round(ex_1_4, 4)
#&gt; [1] 0.8327</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Always read summary values programmatically, never from the printout. <code>summary(fit)</code> returns a list with named elements like <code>adj.r.squared</code>, <code>r.squared</code>, <code>coefficients</code>, <code>fstatistic</code>, and <code>sigma</code>. The adjusted version penalises model size, so it goes up only when an added predictor pulls its statistical weight. Compare adj-R² across nested models to decide whether a new variable is worth keeping.</p>

</details>

<h2>Section 2. Test predictor significance and compare models (3 problems)</h2>

<h3>Exercise 2.1: Read a single t-statistic from the coefficient table</h3>

<p><strong>Task:</strong> Refit the three-predictor model <code>mpg ~ wt + hp + cyl</code> on <code>mtcars</code>. Pull the t-statistic of the <code>cyl</code> coefficient out of the <code>summary()</code> coefficient matrix without retyping it. Save the scalar to <code>ex_2_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] -1.7086</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
round(ex_2_1, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ wt + hp + cyl, data = mtcars)
ex_2_1 &lt;- summary(fit)$coefficients[&quot;cyl&quot;, &quot;t value&quot;]
round(ex_2_1, 4)
#&gt; [1] -1.7086</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>summary(fit)$coefficients</code> is a 4-column matrix (Estimate, Std. Error, t value, Pr(>|t|)) indexed by predictor name. Indexing by name in both dimensions is robust to predictor reordering, which is why this pattern is safer than <code>[3, 3]</code>. The t-value here is borderline, which is exactly the kind of "should I keep this predictor?" signal you want to make a deliberate call on rather than eyeballing stars.</p>

</details>

<h3>Exercise 2.2: Compare two nested models with anova()</h3>

<p><strong>Task:</strong> On <code>mtcars</code>, fit a small model <code>mpg ~ wt</code> and a larger model <code>mpg ~ wt + hp + cyl</code>. Use <code>anova()</code> to test whether the two extra predictors jointly improve fit. Save the <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">p-value</a> of the <a class="auto-link" href="How-to-do-One-Way-ANOVA-in-R.html" title="One-Way ANOVA in R: Compare Group Means With aov()">F-test</a> (the <code>Pr(&gt;F)</code> value on the second row) to <code>ex_2_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 1.331e-05</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
signif(ex_2_2, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">small &lt;- lm(mpg ~ wt, data = mtcars)
large &lt;- lm(mpg ~ wt + hp + cyl, data = mtcars)
ex_2_2 &lt;- anova(small, large)$&quot;Pr(&gt;F)&quot;[2]
signif(ex_2_2, 4)
#&gt; [1] 1.331e-05</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>anova()</code> on two nested <code>lm</code> objects runs a partial F-test: does the extra block of predictors explain a statistically meaningful chunk of residual variance beyond the smaller model? The p-value is on the second row because the first row is the "smaller model" baseline. Use this test, not a stack of individual t-tests, whenever you want to add or drop a group of predictors together.</p>

</details>

<h3>Exercise 2.3: Stepwise selection by AIC with step()</h3>

<p><strong>Task:</strong> Start from the full model <code>mpg ~ wt + hp + cyl + drat + qsec</code> on <code>mtcars</code>. Run backward stepwise selection by <a class="auto-link" href="Model-Selection-in-R.html" title="Model Selection in R">AIC</a> using <code>step()</code> with <code>trace = 0</code>. Save the formula of the final selected model (as a <code>formula</code> object via <code>formula()</code>) to <code>ex_2_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; mpg ~ wt + qsec + hp
#&gt; &lt;environment: 0x...&gt;</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">full &lt;- lm(mpg ~ wt + hp + cyl + drat + qsec, data = mtcars)
selected &lt;- step(full, direction = &quot;backward&quot;, trace = 0)
ex_2_3 &lt;- formula(selected)
ex_2_3
#&gt; mpg ~ wt + qsec + hp</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>step()</code> greedily drops one predictor at a time, recomputes AIC, and stops when no single drop lowers AIC further. <code>direction = &quot;backward&quot;</code> starts from the full model and prunes; <code>&quot;both&quot;</code> lets it add variables back. AIC trades fit against complexity (<code>AIC = -2 log L + 2 k</code>), so unlike adjusted R² it imposes a hard penalty per parameter. Stepwise selection is a screening tool, not a final answer; always cross-check the chosen model on a holdout slice.</p>

</details>

<h2>Section 3. Diagnose residuals and check assumptions (4 problems)</h2>

<h3>Exercise 3.1: Build the residuals-vs-fitted plot manually</h3>

<p><strong>Task:</strong> From the model <code>ex_1_1</code> (mpg ~ wt + hp), build a tibble with columns <code>fitted</code> and <code>resid</code> using <code>fitted()</code> and <code>resid()</code>. Save the two-column tibble (32 rows) to <code>ex_3_1</code> so you can pipe it into <code>ggplot()</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 32 x 2
#&gt;    fitted   resid
#&gt;     &lt;dbl&gt;   &lt;dbl&gt;
#&gt;  1   23.6  -2.57
#&gt;  2   22.6  -1.59
#&gt;  3   25.3  -2.51
#&gt;  4   21.3  -0.13
#&gt;  5   18.2   0.50
#&gt; # 27 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
head(ex_3_1, 5)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- tibble(fitted = fitted(ex_1_1), resid = resid(ex_1_1))
head(ex_3_1, 5)
#&gt; # A tibble: 5 x 2
#&gt;   fitted  resid
#&gt;    &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1   23.6 -2.57
#&gt; 2   22.6 -1.59
#&gt; 3   25.3 -2.51
#&gt; 4   21.3 -0.13
#&gt; 5   18.2  0.50</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>fitted()</code> returns the predicted values at each training row and <code>resid()</code> returns observed minus predicted. Stacking them into a tibble is the gateway to every regression diagnostic plot: residuals-vs-fitted (heteroscedasticity), QQ plot (normality), scale-location (variance trend), residuals-vs-leverage (influence). If the residuals fan out as the fitted value grows, your variance is not constant and a log transform or <a class="auto-link" href="Heteroscedasticity-in-R.html" title="Heteroscedasticity in R: Breusch-Pagan Test & Robust Standard Errors">robust standard errors</a> are on the table.</p>

</details>

<h3>Exercise 3.2: Shapiro-Wilk test for residual normality</h3>

<p><strong>Task:</strong> Run a Shapiro-Wilk <a class="auto-link" href="How-to-do-Shapiro-Wilk-Test-in-R.html" title="Shapiro-Wilk Test in R: Test Normality With shapiro.test()">normality test</a> on the residuals of <code>ex_1_1</code> using <code>shapiro.test()</code>. Save the resulting <code>p.value</code> (a scalar) to <code>ex_3_2</code>. The expected p-value is around 0.13, meaning we do not reject normality at the 5 percent level.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.1295</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
round(ex_3_2, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- shapiro.test(resid(ex_1_1))$p.value
round(ex_3_2, 4)
#&gt; [1] 0.1295</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Shapiro-Wilk is a formal test of "the data are drawn from a <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">normal distribution</a>." With n = 32 it has limited power, so failing to reject (p > 0.05) does not mean "the residuals are perfectly normal," it means you do not have strong evidence against normality. Always pair the test with a QQ plot; the eyeball test catches tail issues that small-sample tests miss.</p>

</details>

<h3>Exercise 3.3: Breusch-Pagan test for heteroscedasticity</h3>

<p><strong>Task:</strong> Use <code>lmtest::bptest()</code> to run a Breusch-Pagan test for non-constant residual variance on <code>ex_1_1</code>. The null is constant variance (homoscedasticity). Save the p-value to <code>ex_3_3</code>. A small p-value means heteroscedasticity is present.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.0892</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
round(ex_3_3, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- bptest(ex_1_1)$p.value
round(ex_3_3, 4)
#&gt; [1] 0.0892</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Breusch-Pagan regresses the squared residuals on the original predictors and tests whether any predictor has explanatory power over the variance. A p of 0.09 sits in the "smoke but not flame" zone: there is mild evidence the variance is not flat. Common fixes are to log-transform the outcome, use <a class="auto-link" href="Weighted-Least-Squares-in-R.html" title="Weighted Least Squares in R: Handle Heteroscedasticity with Weights">weighted least squares</a>, or compute heteroscedasticity-consistent (HC3) standard errors via <code>sandwich::vcovHC()</code>.</p>

</details>

<h3>Exercise 3.4: Identify high-leverage observations with Cook's distance</h3>

<p><strong>Task:</strong> Compute <a class="auto-link" href="Regression-Diagnostics-in-R.html" title="Regression Diagnostics in R: 5 Plots That Reveal Model Violations Instantly">Cook's distance</a> for every row in <code>ex_1_1</code> with <code>cooks.distance()</code>. Save the names of all observations whose Cook's distance exceeds the conventional cutoff of <code>4 / n</code> (where n is <code>nrow(mtcars)</code>) to <code>ex_3_4</code> as a character vector.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] &quot;Chrysler Imperial&quot; &quot;Toyota Corolla&quot;    &quot;Maserati Bora&quot;</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
ex_3_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">cooks &lt;- cooks.distance(ex_1_1)
cutoff &lt;- 4 / nrow(mtcars)
ex_3_4 &lt;- names(cooks[cooks &gt; cutoff])
ex_3_4
#&gt; [1] &quot;Chrysler Imperial&quot; &quot;Toyota Corolla&quot;    &quot;Maserati Bora&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Cook's distance measures how much every fitted value would shift if you deleted one row. The <code>4/n</code> rule of thumb (0.125 here) flags candidates to inspect, not rows to delete blindly. Always look at flagged rows in context: the Maserati Bora has unusually high horsepower for its weight, so it is an honest <a class="auto-link" href="Outlier-Treatment-With-R.html" title="Outlier Treatment with R">outlier</a>, not a data error. Removing it would bias the slope estimate toward the bulk of the sample.</p>

</details>

<h2>Section 4. Detect multicollinearity (3 problems)</h2>

<h3>Exercise 4.1: Build the predictor correlation matrix</h3>

<p><strong>Task:</strong> Compute the <a class="auto-link" href="Correlation-Analysis-in-R.html" title="Correlation in R: Pearson vs Spearman vs Kendall — Compute, Test, and Visualise">Pearson correlation</a> matrix of the five potential predictors <code>wt</code>, <code>hp</code>, <code>cyl</code>, <code>disp</code>, <code>drat</code> from <code>mtcars</code>. Save the 5x5 numeric matrix to <code>ex_4_1</code> so you can spot pairs with absolute correlation above 0.8.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;             wt         hp        cyl       disp       drat
#&gt; wt   1.0000000  0.6587479  0.7824958  0.8879799 -0.7124406
#&gt; hp   0.6587479  1.0000000  0.8324475  0.7909486 -0.4487591
#&gt; cyl  0.7824958  0.8324475  1.0000000  0.9020329 -0.6999381
#&gt; disp 0.8879799  0.7909486  0.9020329  1.0000000 -0.7102139
#&gt; drat -0.7124406 -0.4487591 -0.6999381 -0.7102139  1.0000000</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
round(ex_4_1, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- cor(mtcars[, c(&quot;wt&quot;, &quot;hp&quot;, &quot;cyl&quot;, &quot;disp&quot;, &quot;drat&quot;)])
round(ex_4_1, 3)
#&gt;         wt    hp   cyl   disp   drat
#&gt; wt   1.000 0.659 0.782  0.888 -0.712
#&gt; hp   0.659 1.000 0.832  0.791 -0.449
#&gt; cyl  0.782 0.832 1.000  0.902 -0.700
#&gt; disp 0.888 0.791 0.902  1.000 -0.710
#&gt; drat -0.712 -0.449 -0.700 -0.710  1.000</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A <a class="auto-link" href="Correlation-in-R.html" title="Correlation in R: Choose Between Pearson, Spearman, and Kendall, With Tests">correlation matrix</a> is the first multicollinearity check: anything above 0.8 in absolute value is a warning sign. Here <code>disp</code> is strongly correlated with <code>wt</code>, <code>cyl</code>, and <code>hp</code>, which means putting all four in a model is likely to inflate standard errors and flip coefficient signs. The matrix is necessary but not sufficient; even with all pairwise correlations below 0.8, three predictors can still co-move enough to inflate VIF.</p>

</details>

<h3>Exercise 4.2: Compute VIF for a multi-predictor model</h3>

<p><strong>Task:</strong> Fit <code>mpg ~ wt + hp + cyl + disp</code> on <code>mtcars</code> and use <code>vif()</code> to compute the <a class="auto-link" href="Multicollinearity-in-R.html" title="Multicollinearity in R: Detect It With VIF Before It Corrupts Your Coefficients">variance inflation factor</a> for each predictor. Save the named numeric vector of four VIFs to <code>ex_4_2</code>. Any VIF above 5 (some authors use 10) is the conventional red flag.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;       wt       hp      cyl     disp
#&gt; 4.844618 3.258481 8.819479 7.324517</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
round(ex_4_2, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ wt + hp + cyl + disp, data = mtcars)
ex_4_2 &lt;- vif(fit)
round(ex_4_2, 4)
#&gt;     wt     hp    cyl   disp
#&gt; 4.8446 3.2585 8.8195 7.3245</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> VIF for predictor j is <code>1 / (1 - R_j^2)</code>, where <code>R_j^2</code> is the R-squared of regressing predictor j on every other predictor. A VIF of 8.8 for <code>cyl</code> means its standard error is sqrt(8.8) = 2.97 times larger than it would be if <code>cyl</code> were orthogonal to the rest. The fix is usually to drop one of the redundant predictors, combine them into a single derived variable, or shrink coefficients with ridge or lasso.</p>

</details>

<h3>Exercise 4.3: Drop the worst collinear predictor and re-check VIF</h3>

<p><strong>Task:</strong> From the model in Exercise 4.2, drop the predictor with the highest VIF (it should be <code>cyl</code>). Refit the three-predictor model, recompute VIF on the smaller model, and save the new named VIF vector to <code>ex_4_3</code>. All three VIFs should now be below 5.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;       wt       hp     disp
#&gt; 4.510914 2.736633 4.711599</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
round(ex_4_3, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit_reduced &lt;- lm(mpg ~ wt + hp + disp, data = mtcars)
ex_4_3 &lt;- vif(fit_reduced)
round(ex_4_3, 4)
#&gt;     wt     hp   disp
#&gt; 4.5109 2.7366 4.7116</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Dropping <code>cyl</code> removes the most redundant predictor; the remaining three are pairwise correlated but no longer flagged. This is the typical VIF workflow: identify the worst offender, drop it (or merge with a sibling), and confirm the rest fall under the threshold. If <a class="auto-link" href="Multiple-Regression-in-R.html" title="Multiple Regression in R: How to Build, Interpret, and Refine a Real Model">multiple predictors</a> had VIF above 5, drop them one at a time and re-check, because dropping one often pulls the others below threshold on its own.</p>

</details>

<h2>Section 5. Add interactions and transformations (4 problems)</h2>

<h3>Exercise 5.1: Fit a model with one interaction term</h3>

<p><strong>Task:</strong> On <code>mtcars</code>, fit a model where <code>mpg</code> depends on <code>wt</code>, <code>hp</code>, and their interaction <code>wt:hp</code>. Use the <code>*</code> shortcut so the formula reads <code>mpg ~ wt * hp</code>. Save the named coefficient vector (4 elements: intercept, wt, hp, wt:hp) to <code>ex_5_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; (Intercept)          wt          hp       wt:hp
#&gt; 49.80842369 -8.21662430 -0.12010209  0.02784815</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ wt * hp, data = mtcars)
ex_5_1 &lt;- coef(fit)
ex_5_1
#&gt; (Intercept)          wt          hp       wt:hp
#&gt; 49.80842369 -8.21662430 -0.12010209  0.02784815</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>wt * hp</code> expands to <code>wt + hp + wt:hp</code>, so you get both main effects and the interaction in one stroke. The positive interaction coefficient means the negative effect of weight on mpg shrinks as horsepower grows, which makes physical sense: heavy cars with weak engines are penalised most. Always include main effects when including an interaction; dropping a <a class="auto-link" href="Factorial-Experiments-in-R.html" title="Factorial Designs in R: 2^k Experiments, Main Effects, Confounding, and Interactions">main effect</a> forces it through zero and silently biases the interaction.</p>

</details>

<h3>Exercise 5.2: Log-transform the outcome and compare R-squared</h3>

<p><strong>Task:</strong> On <code>mtcars</code>, fit two models: <code>mpg ~ wt + hp</code> and <code>log(mpg) ~ wt + hp</code>. Pull the multiple R-squared from each <code>summary()</code>. Save a length-2 named numeric vector <code>c(linear = ..., log = ...)</code> of the two R-squared values to <code>ex_5_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;    linear       log
#&gt; 0.8267855 0.8782068</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
round(ex_5_2, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit_lin &lt;- lm(mpg ~ wt + hp, data = mtcars)
fit_log &lt;- lm(log(mpg) ~ wt + hp, data = mtcars)
ex_5_2 &lt;- c(
  linear = summary(fit_lin)$r.squared,
  log    = summary(fit_log)$r.squared
)
round(ex_5_2, 4)
#&gt; linear    log
#&gt; 0.8268 0.8782</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A log transform on the outcome turns additive effects into multiplicative ones; each coefficient becomes "approximate percentage change in mpg per unit predictor." The fit improves here because mpg has a long right tail and shrinks when logged, which evens out the residual variance. Watch out: R-squared on <code>log(mpg)</code> is not directly comparable to R-squared on <code>mpg</code>, because they live on different scales. Compare on the same metric (e.g. <a class="auto-link" href="Interpreting-Regression-Output-Completely.html" title="Interpreting Regression Output Completely: Every Number in lm Summary">residual standard error</a> on the original scale after back-transforming predictions).</p>

</details>

<h3>Exercise 5.3: Add a quadratic term with poly()</h3>

<p><strong>Task:</strong> On <code>mtcars</code>, fit a model where <code>mpg</code> depends on <code>wt</code>, <code>hp</code>, and a quadratic term in <code>hp</code>. Use the orthogonal polynomial form <code>poly(hp, 2)</code> to avoid collinearity between <code>hp</code> and <code>hp^2</code>. Save the adjusted R-squared scalar to <code>ex_5_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.844</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
round(ex_5_3, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ wt + poly(hp, 2), data = mtcars)
ex_5_3 &lt;- summary(fit)$adj.r.squared
round(ex_5_3, 3)
#&gt; [1] 0.844</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>poly(hp, 2)</code> builds two columns: a linear term and a quadratic term, both orthogonal to each other. That orthogonality matters because raw <code>hp</code> and <code>hp^2</code> are correlated by construction (VIF in the dozens), which destabilises the coefficient estimates even when the fit is fine. The adj-R² climbs from 0.815 to 0.844, suggesting the mpg-vs-hp relationship is genuinely curved, not linear.</p>

</details>

<h3>Exercise 5.4: Compare nested models with and without the interaction</h3>

<p><strong>Task:</strong> Build two nested models on <code>mtcars</code>: <code>m_main</code> is <code>mpg ~ wt + hp</code> and <code>m_intx</code> adds the interaction (<code>mpg ~ wt * hp</code>). Use <code>anova()</code> to test whether the interaction adds explanatory power. Save the F-statistic of the comparison (row 2) to <code>ex_5_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 14.821</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_4 &lt;- # your code here
round(ex_5_4, 3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">m_main &lt;- lm(mpg ~ wt + hp, data = mtcars)
m_intx &lt;- lm(mpg ~ wt * hp, data = mtcars)
ex_5_4 &lt;- anova(m_main, m_intx)$F[2]
round(ex_5_4, 3)
#&gt; [1] 14.821</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Comparing nested models with <code>anova()</code> is the principled way to decide whether the interaction is worth its degree of freedom. The F-statistic of 14.8 with p well under 0.001 says the interaction does pay rent; the residual sum of squares drops sharply when you allow the wt slope to flex with hp. Without this test you would be guessing from the t-stat of the interaction alone, which works here but breaks for multi-degree-of-freedom factor interactions.</p>

</details>

<h2>Section 6. Predict on new data (3 problems)</h2>

<h3>Exercise 6.1: Predict mpg for a new car with a confidence interval</h3>

<p><strong>Task:</strong> Using <code>ex_1_1</code> (mpg ~ wt + hp), predict the mean mpg for a hypothetical car with <code>wt = 3.0</code> and <code>hp = 110</code>. Ask for <code>interval = &quot;confidence&quot;</code>. Save the 1x3 numeric matrix (fit, lwr, upr) to <code>ex_6_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;        fit      lwr      upr
#&gt; 1 22.10593 20.79722 23.41464</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">new_car &lt;- data.frame(wt = 3.0, hp = 110)
ex_6_1 &lt;- # your code here
round(ex_6_1, 5)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">new_car &lt;- data.frame(wt = 3.0, hp = 110)
ex_6_1 &lt;- predict(ex_1_1, newdata = new_car, interval = &quot;confidence&quot;)
round(ex_6_1, 5)
#&gt;       fit    lwr     upr
#&gt; 1 22.106 20.797 23.415</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>interval = &quot;confidence&quot;</code> returns the interval for the <em>mean</em> prediction at that x. <code>interval = &quot;prediction&quot;</code> would be wider because it also accounts for the residual noise of a single new observation. Use the confidence interval when reporting "what does the model say the expected mpg is for cars like this?" and the prediction interval when you need to bound an actual future observation, like the next car off the line.</p>

</details>

<h3>Exercise 6.2: Compute hold-out RMSE on a train/test split</h3>

<p><strong>Task:</strong> Set <code>set.seed(42)</code>, sample 24 rows of <code>mtcars</code> for training and the remaining 8 as the test set. Fit <code>mpg ~ wt + hp + cyl</code> on the training rows, predict on the test rows, and save the scalar RMSE on the test set to <code>ex_6_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 2.7847</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
train_idx &lt;- sample(seq_len(nrow(mtcars)), size = 24)
train &lt;- mtcars[train_idx, ]
test  &lt;- mtcars[-train_idx, ]
ex_6_2 &lt;- # your code here
round(ex_6_2, 4)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
train_idx &lt;- sample(seq_len(nrow(mtcars)), size = 24)
train &lt;- mtcars[train_idx, ]
test  &lt;- mtcars[-train_idx, ]
fit &lt;- lm(mpg ~ wt + hp + cyl, data = train)
preds &lt;- predict(fit, newdata = test)
ex_6_2 &lt;- sqrt(mean((test$mpg - preds)^2))
round(ex_6_2, 4)
#&gt; [1] 2.7847</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Holdout RMSE is the honest scorecard for a regression model; in-sample R-squared always overstates performance because the model has already seen those rows. With only 8 test rows the estimate is noisy, so in practice repeat the split many times or use k-fold cross-validation via <code>caret::trainControl()</code> or <code>rsample::vfold_cv()</code>. The takeaway here is the pattern: fit on train, predict on test, score with a metric that lives on the outcome's scale.</p>

</details>

<h3>Exercise 6.3: Build a tidy coefficient table with broom</h3>

<p><strong>Task:</strong> Refit <code>mpg ~ wt + hp + cyl</code> on <code>mtcars</code> and use <code>broom::tidy()</code> with <code>conf.int = TRUE</code> to produce a tidy coefficient table. Save the 4-row tibble (intercept plus three predictors) with columns <code>term</code>, <code>estimate</code>, <code>std.error</code>, <code>statistic</code>, <code>p.value</code>, <code>conf.low</code>, <code>conf.high</code> to <code>ex_6_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 4 x 7
#&gt;   term        estimate std.error statistic  p.value conf.low conf.high
#&gt;   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 (Intercept) 38.8       1.79       21.7   4.02e-19  35.1     42.4
#&gt; 2 wt          -3.17      0.741      -4.28  2.00e- 4  -4.69    -1.65
#&gt; 3 hp          -0.0180    0.0119     -1.52  1.40e- 1  -0.0424   0.00641
#&gt; 4 cyl         -0.942     0.551      -1.71  9.85e- 2  -2.07     0.187</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ wt + hp + cyl, data = mtcars)
ex_6_3 &lt;- tidy(fit, conf.int = TRUE)
ex_6_3
#&gt; # A tibble: 4 x 7
#&gt;   term        estimate std.error statistic  p.value conf.low conf.high
#&gt;   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 (Intercept) 38.8       1.79       21.7   4.02e-19  35.1     42.4
#&gt; 2 wt          -3.17      0.741      -4.28  2.00e- 4  -4.69    -1.65
#&gt; 3 hp          -0.0180    0.0119     -1.52  1.40e- 1  -0.0424   0.00641
#&gt; 4 cyl         -0.942     0.551      -1.71  9.85e- 2  -2.07     0.187</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>broom::tidy()</code> turns a model object into a flat tibble that plays nicely with dplyr, <a class="auto-link" href="ggplot2-Tutorial-With-R.html" title="ggplot2 Short Tutorial">ggplot2</a>, and report generation. <code>conf.int = TRUE</code> adds confidence bounds in two extra columns. This format is the right shape for forest plots, regression tables in Quarto reports, and bulk comparison across many models (<code>purrr::map(fits, tidy) |&gt; bind_rows(.id = &quot;model&quot;)</code>).</p>

</details>

<h2>What to do next</h2>

<p>You have practiced every step of the multiple regression workflow: fitting, interpreting partial slopes, testing, diagnosing, fixing collinearity, adding interactions, and predicting. Pick a follow-up depending on what you want to deepen next.</p>

<ul>

<li><a href="Multiple-Regression-in-R.html">Multiple Regression in R</a>: the parent tutorial that walks through the same workflow with longer explanations.</li>

<li><a href="Linear-Regression-With-R.html">Linear Regression in R</a>: back to one predictor, useful if you want a refresher on the foundation.</li>

<li><a href="Logistic-Regression-With-R.html">Logistic Regression in R</a>: when the outcome is binary instead of continuous.</li>

<li><a href="Hypothesis-Testing-Exercises-in-R.html">R for Statistics: Hypothesis Testing Exercises</a>: practice the testing logic that underlies anova(), F-tests, and <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence intervals</a>.</li>

</ul>

{% endraw %}