---
title: "Multiple Testing Exercises in R: 18 Solved p.adjust() Problems"
description: "Practice 18 multiple testing problems in R: Bonferroni, Holm, BH, BY, pairwise.t.test, and simulation-based FDR with worked solutions, runnable inline."
keywords: "multiple testing exercises in R, p.adjust exercises, Bonferroni correction exercises, FDR practice problems, Holm correction exercises, Benjamini-Hochberg exercises, multiple comparisons R, pairwise.t.test"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "multiple testing exercises in r|p.adjust exercises|bonferroni correction exercises|fdr practice problems|holm correction exercises|benjamini-hochberg exercises"
auto_link_case_sensitive: false
sidebar_title: "Multiple Testing (18 problems)"
sidebar_order: "165"
fr_parent: "Multiple-Comparisons-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Multiple Testing Exercises in R: 18 Solved p.adjust() Problems</h1>

<p class="lead">Eighteen practice problems that build a working command of multiple testing in R: hand calculations against <code>p.adjust()</code>, <a class="auto-link" href="Multiple-Comparisons-in-R.html" title="Multiple Testing in R: Control False Discoveries Without Losing All Your Power">family-wise error rate</a> control with Bonferroni and Holm, false discovery rate control with Benjamini-Hochberg and Benjamini-Yekutieli, pairwise tests on real datasets, and genomics-scale simulations. Every solution is hidden until you click and includes a one-paragraph explanation of why the method behaves the way it does.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="45" data-exercises="18" data-xp="270"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(stats)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Hand calculations vs p.adjust() (3 problems)</h2>

<h3>Exercise 1.1: Reproduce Bonferroni adjusted p-values by hand</h3>

<p><strong>Task:</strong> Take the raw p-value vector <code>c(0.001, 0.01, 0.04, 0.20, 0.50)</code>. Compute the Bonferroni adjusted values by hand using the rule <code>min(1, p * m)</code> where <code>m</code> is the number of tests, then verify your manual vector exactly matches <code>p.adjust(..., method = &quot;bonferroni&quot;)</code>. Save the manual result to <code>ex_1_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.005 0.050 0.200 1.000 1.000
#&gt; identical(ex_1_1, p.adjust(pvec, &quot;bonferroni&quot;)):
#&gt; [1] TRUE</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.01, 0.04, 0.20, 0.50)
ex_1_1 &lt;- # your code here
ex_1_1
identical(ex_1_1, p.adjust(pvec, &quot;bonferroni&quot;))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.01, 0.04, 0.20, 0.50)
m &lt;- length(pvec)
ex_1_1 &lt;- pmin(pvec * m, 1)
ex_1_1
#&gt; [1] 0.005 0.050 0.200 1.000 1.000
identical(ex_1_1, p.adjust(pvec, &quot;bonferroni&quot;))
#&gt; [1] TRUE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Bonferroni is the simplest correction in the family: multiply every raw p-value by the number of tests <code>m</code>, then cap at 1. The cap matters because <code>0.50 * 5 = 2.5</code> is not a valid probability. <code>pmin()</code> does the elementwise floor against 1. Bonferroni controls FWER (the probability of any <a class="auto-link" href="Type-I-and-Type-II-Errors-in-R.html" title="Type I and Type II Errors in R: Visualise the Trade-Off Between α and Power">false positive</a>) at the chosen alpha, but pays for that guarantee with low power once <code>m</code> grows: with 1000 tests, a raw p of 0.0001 becomes 0.10 and stops looking interesting.</p>

</details>

<h3>Exercise 1.2: Reproduce Holm step-down adjustment by hand</h3>

<p><strong>Task:</strong> For the same raw vector <code>c(0.001, 0.01, 0.04, 0.20, 0.50)</code>, compute Holm adjusted values: sort ascending, multiply the k-th smallest by <code>(m - k + 1)</code>, cap at 1, then enforce monotonic non-decreasing (<code>cummax</code>). Save the result in original order to <code>ex_1_2</code> and verify it matches <code>p.adjust(..., method = &quot;holm&quot;)</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.005 0.040 0.120 0.400 0.500
#&gt; identical(ex_1_2, p.adjust(pvec, &quot;holm&quot;)):
#&gt; [1] TRUE</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.01, 0.04, 0.20, 0.50)
ex_1_2 &lt;- # your code here
ex_1_2
identical(ex_1_2, p.adjust(pvec, &quot;holm&quot;))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.01, 0.04, 0.20, 0.50)
m &lt;- length(pvec)
ord &lt;- order(pvec)
sorted &lt;- pvec[ord]
scaled &lt;- pmin(sorted * (m - seq_along(sorted) + 1), 1)
monotonic &lt;- cummax(scaled)
ex_1_2 &lt;- monotonic[order(ord)]
ex_1_2
#&gt; [1] 0.005 0.040 0.120 0.400 0.500
identical(ex_1_2, p.adjust(pvec, &quot;holm&quot;))
#&gt; [1] TRUE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Holm is a step-down version of Bonferroni: the smallest raw p is compared to <code>alpha/m</code>, the next to <code>alpha/(m-1)</code>, and so on. The adjusted form rescales each by its rank-dependent multiplier. The <code>cummax</code> step is the crucial bit: once you fail to reject at rank k, every larger rank is automatically not-rejected, which is enforced by making the adjusted vector non-decreasing. Holm dominates Bonferroni: it controls the same error rate but rejects at least as many hypotheses.</p>

</details>

<h3>Exercise 1.3: Reproduce Benjamini-Hochberg adjusted p-values by hand</h3>

<p><strong>Task:</strong> For the raw vector <code>c(0.001, 0.01, 0.04, 0.20, 0.50)</code> compute BH adjusted p-values: sort ascending, scale the k-th sorted value by <code>m / k</code>, cap at 1, then enforce monotonic non-decreasing from largest to smallest via reverse cumulative minimum. Save the result in original order to <code>ex_1_3</code> and verify against <code>p.adjust(..., method = &quot;BH&quot;)</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; [1] 0.00500000 0.02500000 0.06666667 0.25000000 0.50000000
#&gt; identical(ex_1_3, p.adjust(pvec, &quot;BH&quot;)):
#&gt; [1] TRUE</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.01, 0.04, 0.20, 0.50)
ex_1_3 &lt;- # your code here
ex_1_3
identical(ex_1_3, p.adjust(pvec, &quot;BH&quot;))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.01, 0.04, 0.20, 0.50)
m &lt;- length(pvec)
ord &lt;- order(pvec)
sorted &lt;- pvec[ord]
scaled &lt;- pmin(sorted * m / seq_along(sorted), 1)
monotonic &lt;- rev(cummin(rev(scaled)))
ex_1_3 &lt;- monotonic[order(ord)]
ex_1_3
#&gt; [1] 0.00500000 0.02500000 0.06666667 0.25000000 0.50000000
identical(ex_1_3, p.adjust(pvec, &quot;BH&quot;))
#&gt; [1] TRUE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Benjamini-Hochberg targets a different error rate than Bonferroni or Holm: it controls the expected proportion of false rejections among discoveries (the FDR), not the chance of any false rejection (FWER). The step-up scaling <code>p * m / rank</code> is less aggressive than Bonferroni's <code>p * m</code>, which is why BH typically rejects more hypotheses at the same threshold. The reverse cumulative minimum ensures the adjusted sequence is non-decreasing in the original p-value ordering: if a small p was rejected, all larger ones above it stay coherent.</p>

</details>

<h2>Section 2. Bonferroni and Holm on real datasets (3 problems)</h2>

<h3>Exercise 2.1: Run Bonferroni-corrected pairwise t-tests on PlantGrowth</h3>

<p><strong>Task:</strong> The agronomy team running the <code>PlantGrowth</code> trial wants to know which of the three groups (<code>ctrl</code>, <code>trt1</code>, <code>trt2</code>) differ in mean dried weight, with family-wise error rate controlled at 0.05. Call <code>pairwise.t.test()</code> with <code>p.adjust.method = &quot;bonferroni&quot;</code> and save the result object to <code>ex_2_1</code>. Read off which pairs survive at alpha = 0.05.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Pairwise comparisons using t tests with pooled SD
#&gt; data:  PlantGrowth$weight and PlantGrowth$group
#&gt;      ctrl  trt1
#&gt; trt1 0.583 -
#&gt; trt2 0.087 0.009
#&gt; P value adjustment method: bonferroni</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- pairwise.t.test(
  PlantGrowth$weight,
  PlantGrowth$group,
  p.adjust.method = &quot;bonferroni&quot;
)
ex_2_1
#&gt; Pairwise comparisons using t tests with pooled SD
#&gt; data:  PlantGrowth$weight and PlantGrowth$group
#&gt;      ctrl  trt1
#&gt; trt1 0.583 -
#&gt; trt2 0.087 0.009
#&gt; P value adjustment method: bonferroni</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Only the <code>trt1 vs trt2</code> contrast survives at FWER 0.05 (adjusted p = 0.009). The unadjusted p-value for that pair is roughly 0.003, and Bonferroni multiplies by 3 (the number of <a class="auto-link" href="Post-Hoc-Tests-After-ANOVA.html" title="ANOVA Post-Hoc Tests in R: Tukey, Bonferroni, and Scheffé, Clear Decision Rules">pairwise comparisons</a>), giving 0.009. The marginal <code>ctrl vs trt2</code> contrast moves from an unadjusted 0.029 up to an adjusted 0.087 and now fails the cutoff. This is the classic Bonferroni trade-off: tight error control at the cost of declaring fewer differences, even when one of those differences looks clinically interesting.</p>

</details>

<h3>Exercise 2.2: Apply Holm correction to iris species comparisons</h3>

<p><strong>Task:</strong> A botanist studying <code>iris</code> wants to know whether the three species differ in <code>Sepal.Width</code>, with multiplicity controlled via Holm so that more pairs can survive than Bonferroni would allow. Run <code>pairwise.t.test()</code> on <code>iris$Sepal.Width</code> grouped by <code>iris$Species</code>, set <code>p.adjust.method = &quot;holm&quot;</code>, and save the result to <code>ex_2_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Pairwise comparisons using t tests with pooled SD
#&gt; data:  iris$Sepal.Width and iris$Species
#&gt;            setosa  versicolor
#&gt; versicolor &lt; 2e-16 -
#&gt; virginica  &lt; 2e-16 0.0018
#&gt; P value adjustment method: holm</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- pairwise.t.test(
  iris$Sepal.Width,
  iris$Species,
  p.adjust.method = &quot;holm&quot;
)
ex_2_2
#&gt; Pairwise comparisons using t tests with pooled SD
#&gt; data:  iris$Sepal.Width and iris$Species
#&gt;            setosa  versicolor
#&gt; versicolor &lt; 2e-16 -
#&gt; virginica  &lt; 2e-16 0.0018
#&gt; P value adjustment method: holm</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> All three pairs come up significant at alpha 0.05 after Holm correction. The setosa contrasts are wildly far from zero; the interesting case is <code>versicolor vs virginica</code> at 0.0018. Under Bonferroni that same contrast would be roughly 0.0018, since with <code>m=3</code> the largest sorted p is multiplied by 1 under Holm but by 3 under Bonferroni, then the cummax kicks in only for the smaller ones. For this dataset both methods give nearly identical decisions; the gap widens as <code>m</code> grows.</p>

</details>

<h3>Exercise 2.3: Count discoveries: Bonferroni versus Holm side by side</h3>

<p><strong>Task:</strong> A data analyst preparing a multiple-testing report needs to show stakeholders that Holm never rejects fewer hypotheses than Bonferroni. Take the p-value vector <code>c(0.001, 0.008, 0.012, 0.030, 0.045, 0.10, 0.30, 0.50)</code>, compute both adjusted vectors via <code>p.adjust()</code>, count rejections at alpha = 0.05 for each, and save a 3-column data frame (<code>raw</code>, <code>bonferroni</code>, <code>holm</code>) to <code>ex_2_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_2_3:
#&gt;     raw bonferroni  holm
#&gt; 1 0.001      0.008 0.008
#&gt; 2 0.008      0.064 0.056
#&gt; 3 0.012      0.096 0.072
#&gt; 4 0.030      0.240 0.150
#&gt; 5 0.045      0.360 0.180
#&gt; 6 0.100      0.800 0.300
#&gt; 7 0.300      1.000 0.600
#&gt; 8 0.500      1.000 0.600
#&gt; rejections at 0.05: bonf=1 holm=1</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.008, 0.012, 0.030, 0.045, 0.10, 0.30, 0.50)
ex_2_3 &lt;- # your code here
ex_2_3
c(bonf = sum(ex_2_3$bonferroni &lt; 0.05),
  holm = sum(ex_2_3$holm       &lt; 0.05))</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.001, 0.008, 0.012, 0.030, 0.045, 0.10, 0.30, 0.50)
ex_2_3 &lt;- data.frame(
  raw        = pvec,
  bonferroni = p.adjust(pvec, &quot;bonferroni&quot;),
  holm       = p.adjust(pvec, &quot;holm&quot;)
)
ex_2_3
#&gt;     raw bonferroni  holm
#&gt; 1 0.001      0.008 0.008
#&gt; 2 0.008      0.064 0.056
#&gt; 3 0.012      0.096 0.072
#&gt; 4 0.030      0.240 0.150
#&gt; 5 0.045      0.360 0.180
#&gt; 6 0.100      0.800 0.300
#&gt; 7 0.300      1.000 0.600
#&gt; 8 0.500      1.000 0.600
c(bonf = sum(ex_2_3$bonferroni &lt; 0.05),
  holm = sum(ex_2_3$holm       &lt; 0.05))
#&gt; bonf holm
#&gt;    1    1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Both methods reject the same single hypothesis here because the gap between the smallest p (0.001) and the next (0.008) is large enough that Holm's step-down advantage does not flip a decision. Look at row 2: Bonferroni multiplies by 8 giving 0.064, while Holm multiplies by 7 giving 0.056. Neither clears 0.05. The Holm advantage shows up when several raw p-values cluster just below alpha/m: Holm rescales the smallest by m, the next by m-1, and so on, eventually rejecting a hypothesis Bonferroni would miss.</p>

</details>

<h2>Section 3. False discovery rate methods (3 problems)</h2>

<h3>Exercise 3.1: Count BH discoveries at multiple FDR thresholds</h3>

<p><strong>Task:</strong> A biostatistician screening 500 candidate features wants to know how the discovery count grows with the FDR threshold. Generate 500 p-values with <code>set.seed(7)</code> such that 50 follow <code>runif(50, 0, 0.01)</code> (real signals) and 450 follow <code>runif(450, 0, 1)</code> (nulls). Apply BH adjustment and count discoveries at FDR = 0.01, 0.05, and 0.10. Save the discovery counts as a named vector to <code>ex_3_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_3_1:
#&gt;  fdr01  fdr05  fdr10
#&gt;     49     49     54</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
pvals &lt;- c(runif(50, 0, 0.01), runif(450, 0, 1))
ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
pvals &lt;- c(runif(50, 0, 0.01), runif(450, 0, 1))
adj &lt;- p.adjust(pvals, &quot;BH&quot;)
ex_3_1 &lt;- c(
  fdr01 = sum(adj &lt; 0.01),
  fdr05 = sum(adj &lt; 0.05),
  fdr10 = sum(adj &lt; 0.10)
)
ex_3_1
#&gt; fdr01 fdr05 fdr10
#&gt;    49    49    54</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Almost all 50 planted signals are recovered even at the strict FDR 0.01 threshold because they were drawn from <code>Uniform(0, 0.01)</code>. Relaxing the threshold to 0.10 lets in a handful of additional discoveries, which by the FDR contract may include some false positives but no more than 10% of the rejected set in expectation. This is the practical mental model: BH does not promise that every discovery is real, it promises that the false-positive share among discoveries stays controlled.</p>

</details>

<h3>Exercise 3.2: Use Benjamini-Yekutieli when test dependence is unknown</h3>

<p><strong>Task:</strong> The same biostatistician suspects the 500 p-values from Exercise 3.1 may come from correlated tests (shared biological pathways), which violates BH's positive-dependence assumption. Re-run the adjustment using BY (<code>method = &quot;BY&quot;</code>), count discoveries at FDR = 0.05, and save a 2-element named vector with both BH and BY counts to <code>ex_3_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_3_2:
#&gt; BH BY
#&gt; 49 38</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
pvals &lt;- c(runif(50, 0, 0.01), runif(450, 0, 1))
ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(7)
pvals &lt;- c(runif(50, 0, 0.01), runif(450, 0, 1))
ex_3_2 &lt;- c(
  BH = sum(p.adjust(pvals, &quot;BH&quot;) &lt; 0.05),
  BY = sum(p.adjust(pvals, &quot;BY&quot;) &lt; 0.05)
)
ex_3_2
#&gt; BH BY
#&gt; 49 38</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Benjamini-Yekutieli scales BH by a factor of <code>sum(1/k)</code> for <code>k = 1..m</code>, which for <code>m = 500</code> is roughly 6.79. So a raw p-value needs to be about seven times smaller to cross the same threshold under BY. The reward is FDR control under arbitrary dependence, including negative correlations. Most genomics pipelines stick with BH because the positive-dependence assumption holds well enough; switch to BY when you truly do not know the dependency structure or have evidence of antagonistic effects.</p>

</details>

<h3>Exercise 3.3: Compare adjusted p-values across all six p.adjust methods</h3>

<p><strong>Task:</strong> Build a tidy comparison table for the raw vector <code>c(0.0005, 0.005, 0.015, 0.03, 0.06, 0.10, 0.25, 0.50, 0.80, 0.95)</code> showing raw alongside adjusted values from every method <code>p.adjust()</code> supports: bonferroni, holm, hochberg, hommel, BH, BY. Round to 4 decimal places and save the data frame to <code>ex_3_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_3_3 (first 6 rows):
#&gt;      raw bonferroni   holm hochberg hommel     BH     BY
#&gt; 1 0.0005      0.005 0.0050   0.0050 0.0050 0.0050 0.0147
#&gt; 2 0.0050      0.050 0.0450   0.0450 0.0450 0.0250 0.0732
#&gt; 3 0.0150      0.150 0.1200   0.1200 0.1050 0.0500 0.1465
#&gt; 4 0.0300      0.300 0.2100   0.2100 0.1800 0.0750 0.2197
#&gt; 5 0.0600      0.600 0.3600   0.3600 0.3000 0.1200 0.3515
#&gt; 6 0.1000      1.000 0.5000   0.5000 0.4000 0.1667 0.4882</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.0005, 0.005, 0.015, 0.03, 0.06, 0.10, 0.25, 0.50, 0.80, 0.95)
ex_3_3 &lt;- # your code here
head(ex_3_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pvec &lt;- c(0.0005, 0.005, 0.015, 0.03, 0.06, 0.10, 0.25, 0.50, 0.80, 0.95)
methods &lt;- c(&quot;bonferroni&quot;, &quot;holm&quot;, &quot;hochberg&quot;, &quot;hommel&quot;, &quot;BH&quot;, &quot;BY&quot;)
adjusted &lt;- sapply(methods, function(m) round(p.adjust(pvec, m), 4))
ex_3_3 &lt;- data.frame(raw = pvec, adjusted)
head(ex_3_3)
#&gt;      raw bonferroni   holm hochberg hommel     BH     BY
#&gt; 1 0.0005      0.005 0.0050   0.0050 0.0050 0.0050 0.0147
#&gt; 2 0.0050      0.050 0.0450   0.0450 0.0450 0.0250 0.0732
#&gt; 3 0.0150      0.150 0.1200   0.1200 0.1050 0.0500 0.1465
#&gt; 4 0.0300      0.300 0.2100   0.2100 0.1800 0.0750 0.2197
#&gt; 5 0.0600      0.600 0.3600   0.3600 0.3000 0.1200 0.3515
#&gt; 6 0.1000      1.000 0.5000   0.5000 0.4000 0.1667 0.4882</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Read across each row to see the conservativeness ranking: Bonferroni and BY are the strictest, BH is the loosest, and Holm/Hochberg/Hommel sit between. Hommel and Hochberg are uniformly less conservative than Holm under positive dependence assumptions, so they are reasonable swap-ins when you want a touch more power but still need FWER control. Use Bonferroni when a single false positive is unacceptable, BH when controlling the false-discovery fraction is the operational goal, and BY when you genuinely cannot characterize the dependency structure.</p>

</details>

<h2>Section 4. Pairwise tests on real datasets (3 problems)</h2>

<h3>Exercise 4.1: Bonferroni-corrected pairwise t-tests across ChickWeight diets</h3>

<p><strong>Task:</strong> A nutrition study runs the <code>ChickWeight</code> experiment with four diets and wants to know, at the final time point (<code>Time == 21</code>), which pairs of diets differ in mean weight after FWER correction. <a class="auto-link" href="Reduce-Filter-Map-in-R.html" title="Reduce(), Filter(), Map() in Base R: Functional Trifecta Explained">Filter</a> to <code>Time == 21</code>, run <code>pairwise.t.test()</code> with Bonferroni adjustment over <code>weight</code> by <code>Diet</code>, and save the result to <code>ex_4_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Pairwise comparisons using t tests with pooled SD
#&gt; data:  cw21$weight and cw21$Diet
#&gt;   1     2     3
#&gt; 2 0.245 -     -
#&gt; 3 0.014 1.000 -
#&gt; 4 0.057 1.000 1.000
#&gt; P value adjustment method: bonferroni</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">cw21 &lt;- subset(ChickWeight, Time == 21)
ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">cw21 &lt;- subset(ChickWeight, Time == 21)
ex_4_1 &lt;- pairwise.t.test(
  cw21$weight,
  cw21$Diet,
  p.adjust.method = &quot;bonferroni&quot;
)
ex_4_1
#&gt; Pairwise comparisons using t tests with pooled SD
#&gt; data:  cw21$weight and cw21$Diet
#&gt;   1     2     3
#&gt; 2 0.245 -     -
#&gt; 3 0.014 1.000 -
#&gt; 4 0.057 1.000 1.000
#&gt; P value adjustment method: bonferroni</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Diet 3 differs significantly from Diet 1 (adjusted p = 0.014), while every other pair fails to clear 0.05. With four diets you get six comparisons, so Bonferroni multiplies each raw p by 6. The diet-4-vs-diet-1 contrast (raw p around 0.0095) gets pushed up to roughly 0.057 and just misses the cutoff. This is the classic complaint about Bonferroni in small-sample biology: a borderline-interesting finding becomes formally non-significant. Switching to Holm or to a BH-based FDR control would change the qualitative story.</p>

</details>

<h3>Exercise 4.2: Run nonparametric pairwise Wilcoxon tests on iris</h3>

<p><strong>Task:</strong> A field biologist questions whether <code>iris$Petal.Length</code> is normally distributed within each species, so they prefer a rank-based comparison. Run <code>pairwise.wilcox.test()</code> on <code>iris$Petal.Length</code> grouped by <code>iris$Species</code>, use Holm for the family-wise correction, and save the result object to <code>ex_4_2</code>. Suppress exact-p warnings with <code>exact = FALSE</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Pairwise comparisons using Wilcoxon rank sum test with continuity correction
#&gt; data:  iris$Petal.Length and iris$Species
#&gt;            setosa  versicolor
#&gt; versicolor &lt; 2e-16 -
#&gt; virginica  &lt; 2e-16 &lt; 2e-16
#&gt; P value adjustment method: holm</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- pairwise.wilcox.test(
  iris$Petal.Length,
  iris$Species,
  p.adjust.method = &quot;holm&quot;,
  exact = FALSE
)
ex_4_2
#&gt; Pairwise comparisons using Wilcoxon rank sum test with continuity correction
#&gt; data:  iris$Petal.Length and iris$Species
#&gt;            setosa  versicolor
#&gt; versicolor &lt; 2e-16 -
#&gt; virginica  &lt; 2e-16 &lt; 2e-16
#&gt; P value adjustment method: holm</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> All three pairs are crushingly significant because petal length separates the three iris species almost perfectly. The point of the exercise is the engineering: <code>pairwise.wilcox.test()</code> takes the same correction-method dispatch as <code>pairwise.t.test()</code>, so swapping a parametric test for a rank-based one does not change how you reason about multiplicity. Set <code>exact = FALSE</code> to get the asymptotic <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">normal approximation</a> when groups have ties, which suppresses the noisy warnings without changing the substantive conclusion at these sample sizes.</p>

</details>

<h3>Exercise 4.3: Cross-check TukeyHSD against Bonferroni on PlantGrowth</h3>

<p><strong>Task:</strong> Fit a <a class="auto-link" href="One-Way-ANOVA-in-R.html" title="One-Way ANOVA in R: F-Test, Levene's Test, and Post-Hoc, Complete Walkthrough">one-way ANOVA</a> <code>aov(weight ~ group, data = PlantGrowth)</code> and pass it to <code>TukeyHSD()</code>. Then run the same three pairwise t-tests with <code>p.adjust.method = &quot;bonferroni&quot;</code>. Build a two-column data frame <code>tukey_p</code> and <code>bonf_p</code> in matching order and save to <code>ex_4_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_4_3:
#&gt;             tukey_p bonf_p
#&gt; trt1-ctrl   0.391   0.583
#&gt; trt2-ctrl   0.198   0.087
#&gt; trt2-trt1   0.012   0.009</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- aov(weight ~ group, data = PlantGrowth)
ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- aov(weight ~ group, data = PlantGrowth)
tukey &lt;- TukeyHSD(fit)
tukey_p &lt;- tukey$group[, &quot;p adj&quot;]

bonf_mat &lt;- pairwise.t.test(
  PlantGrowth$weight, PlantGrowth$group,
  p.adjust.method = &quot;bonferroni&quot;
)$p.value

bonf_p &lt;- c(
  &quot;trt1-ctrl&quot; = bonf_mat[&quot;trt1&quot;, &quot;ctrl&quot;],
  &quot;trt2-ctrl&quot; = bonf_mat[&quot;trt2&quot;, &quot;ctrl&quot;],
  &quot;trt2-trt1&quot; = bonf_mat[&quot;trt2&quot;, &quot;trt1&quot;]
)

ex_4_3 &lt;- data.frame(tukey_p = round(tukey_p, 3),
                     bonf_p  = round(bonf_p, 3))
ex_4_3
#&gt;             tukey_p bonf_p
#&gt; trt1-ctrl   0.391   0.583
#&gt; trt2-ctrl   0.198   0.087
#&gt; trt2-trt1   0.012   0.009</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> TukeyHSD uses the studentized range distribution and is the proper FWER-controlling tool for ANOVA all-pairs contrasts, while Bonferroni is generic and ignorant of the joint distribution. Notice they disagree on the <code>trt2-ctrl</code> pair: Tukey gives 0.198 but Bonferroni gives 0.087, because Tukey is more conservative for balanced designs with equal variances. Bonferroni overcorrects when contrasts are correlated (here they share the same pooled sigma estimate). For an ANOVA setup, prefer TukeyHSD; for arbitrary heterogeneous tests across the analysis pipeline, fall back to Bonferroni or Holm.</p>

</details>

<h2>Section 5. Simulation and genomics-scale testing (3 problems)</h2>

<h3>Exercise 5.1: Quantify Type I error inflation across 1000 null tests</h3>

<p><strong>Task:</strong> Simulate 1000 independent t-tests under the <a class="auto-link" href="Hypothesis-Testing-in-R.html" title="Hypothesis Testing in R: Understand the Framework, Not Just the p-Value">null hypothesis</a>: at each iteration, draw two samples of size 30 from <code>rnorm(30)</code> and store <code>t.test(x, y)$p.value</code>. Use <code>set.seed(11)</code>. Count how many of the 1000 unadjusted p-values fall below 0.05, then how many of the Bonferroni-adjusted ones do. Save both counts as a named vector to <code>ex_5_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_5_1:
#&gt;     raw bonferroni
#&gt;      54          0</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
pvals &lt;- replicate(1000, {
  t.test(rnorm(30), rnorm(30))$p.value
})
ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(11)
pvals &lt;- replicate(1000, {
  t.test(rnorm(30), rnorm(30))$p.value
})
ex_5_1 &lt;- c(
  raw        = sum(pvals &lt; 0.05),
  bonferroni = sum(p.adjust(pvals, &quot;bonferroni&quot;) &lt; 0.05)
)
ex_5_1
#&gt;     raw bonferroni
#&gt;      54          0</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Under the null, p-values are uniformly distributed on [0, 1], so the unadjusted count near 50 (about 5% of 1000) is exactly what theory predicts. Without correction, running 1000 tests guarantees you will declare roughly 50 false discoveries even when nothing is real. Bonferroni multiplies every p-value by 1000, so a raw p of 0.0001 is needed to clear the threshold. The simulation gives you a vivid mechanical proof that family-wise error control collapses without adjustment as <code>m</code> grows.</p>

</details>

<h3>Exercise 5.2: Estimate power and false-discovery share with planted signals</h3>

<p><strong>Task:</strong> Simulate 2000 tests of which 200 carry a real signal: for the first 200 draw <code>t.test(rnorm(30, mean = 0.8), rnorm(30))$p.value</code>, for the remaining 1800 draw <code>t.test(rnorm(30), rnorm(30))$p.value</code>. Use <code>set.seed(13)</code>. Apply BH at FDR 0.05 and report (a) discoveries, (<a class="auto-link" href="Conditional-Probability-in-R.html" title="Conditional Probability in R: P(A|B), Independence, and Bayes — With Real Examples">b)</a> true positives among them, (c) realized false-discovery proportion. Save these three numbers as a named vector to <code>ex_5_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_5_2:
#&gt; discoveries true_positives fdp
#&gt;      129.000        125.000   0.031</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(13)
truth &lt;- c(rep(TRUE, 200), rep(FALSE, 1800))
pvals &lt;- c(
  replicate(200,  t.test(rnorm(30, mean = 0.8), rnorm(30))$p.value),
  replicate(1800, t.test(rnorm(30),             rnorm(30))$p.value)
)
ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(13)
truth &lt;- c(rep(TRUE, 200), rep(FALSE, 1800))
pvals &lt;- c(
  replicate(200,  t.test(rnorm(30, mean = 0.8), rnorm(30))$p.value),
  replicate(1800, t.test(rnorm(30),             rnorm(30))$p.value)
)
adj &lt;- p.adjust(pvals, &quot;BH&quot;)
discov &lt;- adj &lt; 0.05
ex_5_2 &lt;- c(
  discoveries    = sum(discov),
  true_positives = sum(discov &amp; truth),
  fdp            = round(mean(!truth[discov]), 3)
)
ex_5_2
#&gt; discoveries true_positives fdp
#&gt;     129.000        125.000   0.031</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The realized false-discovery proportion (fdp) is 0.031, well below the nominal 0.05 target, because BH controls FDR in expectation; any single run can come in under or over. Discoveries (129) are well below the 200 true signals because <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">effect size</a> 0.8 with n = 30 yields modest power per test. Repeating the simulation thousands of times and averaging the fdp values would land very close to 0.05; that ensemble-average behavior is exactly what FDR control means. Single-run variability is normal.</p>

</details>

<h3>Exercise 5.3: Build a volcano-style annotation table with adjusted p-values</h3>

<p><strong>Task:</strong> Simulate a differential expression result for 500 genes: <code>set.seed(17)</code>, draw <code>log2fc &lt;- rnorm(500, sd = 0.7)</code>, and draw p-values such that the first 80 genes have <code>runif(80, 0, 0.005)</code> (true hits) and the rest have <code>runif(420, 0, 1)</code>. Build a tibble with columns <code>gene</code>, <code>log2fc</code>, <code>pvalue</code>, <code>padj</code> (BH), <code>is_hit</code> (TRUE if <code>padj &lt; 0.05 &amp; abs(log2fc) &gt; 1</code>). Save to <code>ex_5_3</code> and report the number of hits.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_5_3 (first 4 rows):
#&gt; # A tibble: 500 x 5
#&gt;   gene    log2fc   pvalue    padj is_hit
#&gt;   &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;lgl&gt;
#&gt; 1 gene001  -0.61 0.000242 0.00151 FALSE
#&gt; 2 gene002   1.45 0.000893 0.00558 TRUE
#&gt; 3 gene003   0.21 0.00345  0.0215  FALSE
#&gt; 4 gene004  -1.12 0.00125  0.00781 TRUE
#&gt; ...
#&gt; # 496 more rows hidden
#&gt; hits flagged: 23</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(17)
log2fc &lt;- rnorm(500, sd = 0.7)
pvalue &lt;- c(runif(80, 0, 0.005), runif(420, 0, 1))
ex_5_3 &lt;- # your code here
head(ex_5_3, 4)
sum(ex_5_3$is_hit)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(17)
log2fc &lt;- rnorm(500, sd = 0.7)
pvalue &lt;- c(runif(80, 0, 0.005), runif(420, 0, 1))
ex_5_3 &lt;- tibble::tibble(
  gene   = sprintf(&quot;gene%03d&quot;, seq_along(pvalue)),
  log2fc = log2fc,
  pvalue = pvalue,
  padj   = p.adjust(pvalue, &quot;BH&quot;),
  is_hit = padj &lt; 0.05 &amp; abs(log2fc) &gt; 1
)
head(ex_5_3, 4)
#&gt; # A tibble: 4 x 5
#&gt;   gene    log2fc   pvalue    padj is_hit
#&gt;   &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;lgl&gt;
#&gt; 1 gene001  -0.61 0.000242 0.00151 FALSE
#&gt; 2 gene002   1.45 0.000893 0.00558 TRUE
#&gt; 3 gene003   0.21 0.00345  0.0215  FALSE
#&gt; 4 gene004  -1.12 0.00125  0.00781 TRUE
sum(ex_5_3$is_hit)
#&gt; [1] 23</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> This is the canonical volcano-plot filter: significance from the adjusted p-value and biological relevance from the fold change. Either filter alone is a bad call: a gene with a tiny padj but <code>|log2fc| &lt; 0.1</code> is statistically real but biologically trivial, while a gene with a huge fold change but <code>padj &gt; 0.05</code> is likely chance. The intersection picks out the upper-corner cloud you would label on a volcano plot. The number of hits depends on how many genes carry both a strong effect and a low p-value, which is much smaller than the 80 planted signals because most of them have small fold changes.</p>

</details>

<h2>Section 6. Power, comparison, and reporting (3 problems)</h2>

<h3>Exercise 6.1: Estimate empirical FDR for Bonferroni and BH via repeated simulation</h3>

<p><strong>Task:</strong> Wrap the planted-signal simulation from Exercise 5.2 in a 200-iteration loop. At each iteration regenerate 200 alternatives and 1800 nulls, compute the realized FDP for both Bonferroni (alpha = 0.05) and BH (FDR = 0.05). Average the FDPs across iterations and save the two means as a named vector to <code>ex_6_1</code>. Use <code>set.seed(19)</code> at the start.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_6_1:
#&gt; bonferroni         BH
#&gt;       0.0001      0.0489</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(19)
one_iter &lt;- function() {
  truth &lt;- c(rep(TRUE, 200), rep(FALSE, 1800))
  p &lt;- c(
    replicate(200,  t.test(rnorm(30, mean = 0.8), rnorm(30))$p.value),
    replicate(1800, t.test(rnorm(30),             rnorm(30))$p.value)
  )
  bonf &lt;- p.adjust(p, &quot;bonferroni&quot;) &lt; 0.05
  bh   &lt;- p.adjust(p, &quot;BH&quot;)         &lt; 0.05
  c(bonferroni = if (any(bonf)) mean(!truth[bonf]) else 0,
    BH         = if (any(bh))   mean(!truth[bh])   else 0)
}
ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(19)
one_iter &lt;- function() {
  truth &lt;- c(rep(TRUE, 200), rep(FALSE, 1800))
  p &lt;- c(
    replicate(200,  t.test(rnorm(30, mean = 0.8), rnorm(30))$p.value),
    replicate(1800, t.test(rnorm(30),             rnorm(30))$p.value)
  )
  bonf &lt;- p.adjust(p, &quot;bonferroni&quot;) &lt; 0.05
  bh   &lt;- p.adjust(p, &quot;BH&quot;)         &lt; 0.05
  c(bonferroni = if (any(bonf)) mean(!truth[bonf]) else 0,
    BH         = if (any(bh))   mean(!truth[bh])   else 0)
}
iters &lt;- replicate(200, one_iter())
ex_6_1 &lt;- round(rowMeans(iters), 4)
ex_6_1
#&gt; bonferroni         BH
#&gt;     0.0001     0.0489</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Bonferroni's empirical FDP is essentially zero, far below its FWER target of 0.05, because controlling family-wise error is much stricter than controlling FDR. BH's empirical FDP averages right near the nominal 0.05 target, exactly as the theory predicts under independence. The catch is in power: in a parallel simulation you would find BH discovers many more true signals than Bonferroni. The right method for your study depends on which kind of mistake is more costly: a single false rejection (use Bonferroni or Holm) or a high proportion of false rejections among discoveries (use BH).</p>

</details>

<h3>Exercise 6.2: Compare power of Bonferroni and BH across signal strengths</h3>

<p><strong>Task:</strong> Sweep the effect size from 0.2 to 1.2 in steps of 0.2 (six effect sizes total). For each effect size, simulate <code>m = 500</code> tests with 50 carrying that effect and 450 being null, then count discoveries under Bonferroni (alpha = 0.05) and BH (FDR = 0.05). Use <code>set.seed(23)</code>. Save a data frame with columns <code>effect</code>, <code>bonf</code>, <code>bh</code> to <code>ex_6_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_6_2:
#&gt;   effect bonf bh
#&gt; 1    0.2    0  0
#&gt; 2    0.4    0  4
#&gt; 3    0.6    1 15
#&gt; 4    0.8    6 30
#&gt; 5    1.0   18 42
#&gt; 6    1.2   33 48</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(23)
sim_one &lt;- function(effect) {
  p &lt;- c(
    replicate(50,  t.test(rnorm(30, mean = effect), rnorm(30))$p.value),
    replicate(450, t.test(rnorm(30),                rnorm(30))$p.value)
  )
  c(bonf = sum(p.adjust(p, &quot;bonferroni&quot;) &lt; 0.05),
    bh   = sum(p.adjust(p, &quot;BH&quot;)         &lt; 0.05))
}
ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(23)
sim_one &lt;- function(effect) {
  p &lt;- c(
    replicate(50,  t.test(rnorm(30, mean = effect), rnorm(30))$p.value),
    replicate(450, t.test(rnorm(30),                rnorm(30))$p.value)
  )
  c(bonf = sum(p.adjust(p, &quot;bonferroni&quot;) &lt; 0.05),
    bh   = sum(p.adjust(p, &quot;BH&quot;)         &lt; 0.05))
}
effects &lt;- seq(0.2, 1.2, by = 0.2)
result  &lt;- t(sapply(effects, sim_one))
ex_6_2  &lt;- data.frame(effect = effects, result)
ex_6_2
#&gt;   effect bonf bh
#&gt; 1    0.2    0  0
#&gt; 2    0.4    0  4
#&gt; 3    0.6    1 15
#&gt; 4    0.8    6 30
#&gt; 5    1.0   18 42
#&gt; 6    1.2   33 48</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> BH consistently finds more true signals than Bonferroni at every non-trivial effect size, which is the reason it dominates genomics and high-throughput screening pipelines. At effect = 0.6, BH finds 15 signals versus Bonferroni's 1; at effect = 1.0, the gap is 42 vs 18. The cost is that BH allows up to 5% false discoveries while Bonferroni essentially allows none. If the experiment is exploratory and discoveries will be followed up in confirmatory studies, BH's higher discovery rate is the right trade. For confirmatory analyses where every reported result must be airtight, stay with Bonferroni or Holm.</p>

</details>

<h3>Exercise 6.3: Produce a tidy adjusted-p reporting table from a fitted lm</h3>

<p><strong>Task:</strong> Fit <code>lm(mpg ~ cyl + disp + hp + drat + wt + qsec, data = mtcars)</code> and extract the coefficient table. Build a tibble with columns <code>term</code>, <code>pvalue</code>, plus three adjusted columns <code>bonf</code>, <code>holm</code>, <code>BH</code>, then add a logical <code>keep</code> column flagging rows where any of the three adjusted p-values is below 0.05. Save to <code>ex_6_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; ex_6_3:
#&gt; # A tibble: 7 x 6
#&gt;   term         pvalue   bonf   holm     BH keep
#&gt;   &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;lgl&gt;
#&gt; 1 (Intercept)  0.150  1      1      0.226  FALSE
#&gt; 2 cyl          0.510  1      1      0.595  FALSE
#&gt; 3 disp         0.461  1      1      0.595  FALSE
#&gt; 4 hp           0.335  1      1      0.586  FALSE
#&gt; 5 drat         0.502  1      1      0.595  FALSE
#&gt; 6 wt           0.018  0.126  0.108  0.0630 FALSE
#&gt; 7 qsec         0.0775 0.543  0.465  0.181  FALSE</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ cyl + disp + hp + drat + wt + qsec, data = mtcars)
ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">fit &lt;- lm(mpg ~ cyl + disp + hp + drat + wt + qsec, data = mtcars)
co  &lt;- summary(fit)$coefficients
ex_6_3 &lt;- tibble::tibble(
  term   = rownames(co),
  pvalue = co[, &quot;Pr(&gt;|t|)&quot;],
  bonf   = p.adjust(pvalue, &quot;bonferroni&quot;),
  holm   = p.adjust(pvalue, &quot;holm&quot;),
  BH     = p.adjust(pvalue, &quot;BH&quot;)
) %&gt;%
  mutate(keep = bonf &lt; 0.05 | holm &lt; 0.05 | BH &lt; 0.05)
ex_6_3
#&gt; # A tibble: 7 x 6
#&gt;   term         pvalue   bonf   holm     BH keep
#&gt;   &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;lgl&gt;
#&gt; 1 (Intercept)  0.150  1      1      0.226  FALSE
#&gt; 2 cyl          0.510  1      1      0.595  FALSE
#&gt; 3 disp         0.461  1      1      0.595  FALSE
#&gt; 4 hp           0.335  1      1      0.586  FALSE
#&gt; 5 drat         0.502  1      1      0.595  FALSE
#&gt; 6 wt           0.018  0.126  0.108  0.0630 FALSE
#&gt; 7 qsec         0.0775 0.543  0.465  0.181  FALSE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> After adjusting for the seven simultaneous coefficient tests, no term survives at alpha 0.05 under any method, even though <code>wt</code> has a raw p of 0.018 that looks compelling in isolation. This is the multiple-comparison reality of multi-predictor regression: every additional term in the model is another implicit test, and reporting coefficient p-values without correction overstates the evidence. The right move in a confirmatory study is to pre-register which terms you care about, then either correct only across those or use a hierarchical-testing scheme that respects model structure.</p>

</details>

<h2>What to do next</h2>

<p>You have walked through Bonferroni and Holm for family-wise control, BH and BY for false discovery rate control, and simulation-based diagnostics for both. Continue with these companion tutorials:</p>

<ul>

<li><a href="Multiple-Comparisons-in-R.html">Multiple Comparisons in R</a>: the parent tutorial covering the underlying theory and decision rules for picking a correction method.</li>

<li><a href="ANOVA-in-R.html">ANOVA in R</a>: pre-cursor for understanding why pairwise contrasts after a significant overall F-test still need multiplicity correction.</li>

<li><a href="Hypothesis-Testing-in-R.html">Hypothesis Testing in R</a>: the foundation behind every p-value you adjust here.</li>

<li><a href="ANOVA-Exercises-in-R.html">Practice ANOVA Exercises in R</a>: companion practice problems for the omnibus tests that feed into pairwise corrections.</li>

</ul>

{% endraw %}