---
title: "Poisson Distribution Exercises in R (16 Problems)"
description: "Sixteen Poisson distribution exercises in R covering dpois, ppois, qpois, rpois, fitdistr, and poisson.test with full runnable solutions and explanations."
keywords: "poisson distribution R exercises, dpois examples, ppois practice problems, rpois simulation, qpois quantile, poisson.test in R, MLE poisson, fitdistr poisson"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "poisson distribution exercises|dpois practice|ppois practice|qpois practice|rpois practice|poisson.test in r"
auto_link_case_sensitive: false
sidebar_title: "Poisson Distribution Exercises"
sidebar_order: "152"
fr_parent: "Binomial-and-Poisson-Distributions-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>Poisson Distribution Exercises in R (16 Problems)</h1>
<p class="lead">Sixteen progressively harder Poisson distribution exercises in R covering exact probabilities with <code>dpois()</code>, cumulative probabilities with <code>ppois()</code>, quantiles with <code>qpois()</code>, simulation with <code>rpois()</code>, lambda estimation, and inference via <code>poisson.test()</code>. Every problem ships with a hidden solution and a written explanation so you can self-grade as you work through them.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="17" data-time="40" data-xp="255"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(stats)
library(MASS)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Exact probabilities with dpois (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Probability of exactly two events at rate five</h3>
<p class="exercise-task"><strong>Task:</strong> A retail call centre receives an average of five complaint calls per hour. Use <code>dpois()</code> to compute the exact probability of receiving exactly two complaint calls in a one-hour window, and save the scalar result to <code>ex_1_1</code>. Round the printed value to four decimal places.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.0842</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>"Exactly two" points you at the probability mass at a single integer, not a <a class="auto-link" href="purrr-accumulate-in-R.html" title="purrr accumulate() in R: Running Reductions Over a List">running total</a> over several counts.</p><p>Evaluate <code>dpois()</code> with the count as the first argument and <code>lambda = 5</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
round(ex_1_1, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- dpois(2, lambda = 5)
round(ex_1_1, 4)
#&gt; [1] 0.0842</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>dpois(x, lambda)</code> evaluates the Poisson <a class="auto-link" href="Random-Variables-in-R.html" title="Random Variables in R: Discrete vs Continuous, PMF, PDF, and CDF — Visualised">probability mass function</a> $P(X = x) = \lambda^{x} e^{-\lambda} / x!$ at a single integer. Here $5^{2} e^{-5} / 2!$ collapses to roughly 0.0842, an 8.4 percent chance. A common mistake is calling <code>ppois()</code> instead, which would give the cumulative probability of 0, 1, or 2 calls (about 0.125). Whenever the question says "exactly k", reach for <code>dpois()</code>; "at most k" maps to <code>ppois()</code>.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Compare exact probabilities across two rate scenarios</h3>
<p class="exercise-task"><strong>Task:</strong> A network engineer compares two routers. Router A drops on average 3 packets per second, router B drops 7. For each router compute the probability of dropping exactly four packets in a one-second window using <code>dpois()</code>, store both probabilities in a named numeric vector with names <code>A</code> and <code>B</code>, and save the vector to <code>ex_1_2</code>. The router with the higher probability under lambda four is the one whose mean sits closest to four.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;      A      B 
#&gt; 0.1680 0.0912</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Each router needs the probability mass at the same count of four, but evaluated against its own average rate.</p><p>Call <code>dpois(4, lambda = ...)</code> once per router and bundle them with <code>c(A = ..., B = ...)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
round(ex_1_2, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- c(
  A = dpois(4, lambda = 3),
  B = dpois(4, lambda = 7)
)
round(ex_1_2, 4)
#&gt;      A      B 
#&gt; 0.1680 0.0912</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The Poisson mass function peaks near <code>floor(lambda)</code>. Router A with <code>lambda = 3</code> sits one step below four, so <code>dpois(4, 3)</code> is still close to the mode and returns 0.168. Router B at <code>lambda = 7</code> sits three steps above four, so the tail probability drops to 0.091. A frequent pitfall is comparing tail probabilities directly without normalising for the underlying rate; here the comparison is valid because both queries evaluate the same x at different lambdas.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Tabulate the full PMF for k from zero to ten</h3>
<p class="exercise-task"><strong>Task:</strong> A traffic engineer studies a busy intersection that averages 4 minor incidents per week. Produce a length-11 numeric vector containing <code>dpois(0:10, lambda = 4)</code>, name each element by its k value using <code>setNames()</code>, round to four decimal places, and save the result to <code>ex_1_3</code>. The peak of the PMF should land at <code>k = 3</code> and <code>k = 4</code> (both around 0.1954).</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;      0      1      2      3      4      5      6      7      8      9     10 
#&gt; 0.0183 0.0733 0.1465 0.1954 0.1954 0.1563 0.1042 0.0595 0.0298 0.0132 0.0053</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The full mass function is one probability evaluation repeated across every k, so a whole range of counts can be done in one shot.</p><p>Pass <code>0:10</code> to <code>dpois()</code> with <code>lambda = 4</code>, then attach the k labels using <code>setNames()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- setNames(
  round(dpois(0:10, lambda = 4), 4),
  0:10
)
ex_1_3
#&gt;      0      1      2      3      4      5      6      7      8      9     10 
#&gt; 0.0183 0.0733 0.1465 0.1954 0.1954 0.1563 0.1042 0.0595 0.0298 0.0132 0.0053</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>dpois()</code> is vectorised over its first argument, so passing <code>0:10</code> returns the whole PMF in one call rather than looping. When <code>lambda</code> is an integer, the mass function has two equal modes at <code>lambda - 1</code> and <code>lambda</code>; here that means k of 3 and 4 both peak at 0.1954. Naming the vector by its k values makes downstream filtering (for instance <code>ex_1_3[as.character(5:7)]</code>) read clearly. For a non-integer <code>lambda</code>, the mode collapses to the single integer <code>floor(lambda)</code>.</p>
</details>
</section>
<h2>Section 2. Cumulative and tail probabilities with ppois (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: At most versus more than for a single rate</h3>
<p class="exercise-task"><strong>Task:</strong> Compute two probabilities for a Poisson with <code>lambda = 6</code>: the probability of at most 4 events using <code>ppois()</code>, and the probability of more than 4 events using <code>ppois()</code> with <code>lower.tail = FALSE</code>. Combine both into a named numeric vector with names <code>at_most_4</code> and <code>more_than_4</code>, and save it to <code>ex_2_1</code>. They must sum to one because at-most-four and more-than-four partition the integers.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;   at_most_4 more_than_4 
#&gt;      0.2851      0.7149</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>"At most" is the cumulative probability up to a count; "more than" is the complementary upper tail of that same count.</p><p>Use <code>ppois(4, lambda = 6)</code> and the same call with <code>lower.tail = FALSE</code>, combined via <code>c(at_most_4 = ..., more_than_4 = ...)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
round(ex_2_1, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- c(
  at_most_4   = ppois(4, lambda = 6),
  more_than_4 = ppois(4, lambda = 6, lower.tail = FALSE)
)
round(ex_2_1, 4)
#&gt;   at_most_4 more_than_4 
#&gt;      0.2851      0.7149</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>ppois(q, lambda)</code> returns $P(X \le q)$ by default. Setting <code>lower.tail = FALSE</code> flips it to $P(X &gt; q)$, which is more numerically stable than computing <code>1 - ppois(...)</code> when the lower tail is close to one. Because the two events partition the <a class="auto-link" href="Sample-Spaces-Events-and-Probability-Axioms-in-R-With-Monte-Carlo-Proof.html" title="Probability Axioms in R: Prove the Rules of Probability via Monte Carlo Simulation">sample space</a>, the sum is exactly 1.0 up to floating-point error. A frequent mistake is reading "more than 4" as <code>q = 5</code>; the correct call is <code>q = 4, lower.tail = FALSE</code>, which excludes 4 itself.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Call centre staffing under a service-level constraint</h3>
<p class="exercise-task"><strong>Task:</strong> The operations manager of a help desk staffs the night shift for an average of 12 tickets per hour. Compute the probability of receiving 15 or fewer tickets in a one-hour window (the "comfortable" zone), and the probability of receiving 20 or more (the "overload" zone). Bundle the two probabilities into a length-2 named vector <code>c(comfortable = ..., overload = ...)</code> and save it to <code>ex_2_2</code>. Use <code>ppois()</code> for both calls.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>comfortable    overload 
     0.8444      0.0213
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Translate each English phrase into a cumulative probability, paying attention to whether the boundary count is included.</p><p>Use <code>ppois(15, lambda = 12)</code> for the comfortable zone and <code>ppois(19, lambda = 12, lower.tail = FALSE)</code> for "20 or more".</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
round(ex_2_2, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- c(
  comfortable = ppois(15, lambda = 12),
  overload    = ppois(19, lambda = 12, lower.tail = FALSE)
)
round(ex_2_2, 4)
#&gt; comfortable    overload 
#&gt;      0.8444      0.0116</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> "20 or more tickets" is $P(X \ge 20)$, which equals $P(X &gt; 19)$, so the upper-tail call uses <code>q = 19</code> not <code>q = 20</code>. This off-by-one is the single biggest source of bugs when translating English statements into <code>ppois()</code> arguments. With overload sitting at roughly 1.2 percent the manager can comfortably staff for fifteen with confidence, but a separate Erlang-C calculation would also account for service time, not just arrival rate.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Map a probability range to ordered cutoffs</h3>
<p class="exercise-task"><strong>Task:</strong> A quality-control engineer monitors defective parts at an average rate of 8 per shift. For each cutoff k in 5, 8, 10, 12, 15 compute $P(X \le k)$ using <code>ppois()</code>. Save the five probabilities as a named numeric vector (names taken from the k values) to <code>ex_2_3</code>. Together these five values trace out the <a class="auto-link" href="Kolmogorov-Smirnov-Two-Sample-Test-in-R.html" title="Kolmogorov-Smirnov Two-Sample Test in R: Compare Two Distributions">empirical CDF</a> at those grid points.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;      5      8     10     12     15 
#&gt; 0.1912 0.5925 0.8159 0.9362 0.9918</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Tracing the CDF at several cutoffs is one cumulative-probability evaluation repeated across a grid of counts.</p><p>Pass the cutoff vector to <code>ppois()</code> with <code>lambda = 8</code>, then label the result with <code>setNames()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
round(ex_2_3, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">cutoffs  &lt;- c(5, 8, 10, 12, 15)
ex_2_3   &lt;- setNames(ppois(cutoffs, lambda = 8), cutoffs)
round(ex_2_3, 4)
#&gt;      5      8     10     12     15 
#&gt; 0.1912 0.5925 0.8159 0.9362 0.9918</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Vectorising <code>ppois()</code> over <code>cutoffs</code> returns the CDF at each gridpoint in one call, which is the right way to inspect tail behaviour without a loop. Notice the CDF is non-decreasing and climbs from 0.19 at k=5 (well below the mean) to 0.99 at k=15 (almost two standard deviations above). A useful sanity check is that <code>ppois(floor(lambda), lambda)</code> for <code>lambda = 8</code> should sit near 0.59, reflecting the slight right skew of the distribution.</p>
</details>
</section>
<h2>Section 3. Quantiles with qpois (2 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Smallest k achieving 95 percent coverage</h3>
<p class="exercise-task"><strong>Task:</strong> A platform engineer wants the smallest integer count k such that $P(X \le k) \ge 0.95$ when the server averages 25 errors per day. Use <code>qpois()</code> to compute this critical k and save it as an integer scalar to <code>ex_3_1</code>. Also verify the answer by feeding k back into <code>ppois()</code> and confirming the cumulative probability is at least 0.95.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 33
verify ppois(ex_3_1, 25): 0.9502
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You need to invert the cumulative probability: given a coverage target, find the smallest count that first reaches it.</p><p>Call <code>qpois(0.95, lambda = 25)</code>, then confirm it by feeding the answer back into <code>ppois()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1
cat("verify ppois(ex_3_1, 25):", round(ppois(ex_3_1, 25), 4), "\n")</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- qpois(0.95, lambda = 25)
ex_3_1
#&gt; [1] 34
cat("verify ppois(ex_3_1, 25):", round(ppois(ex_3_1, 25), 4), "\n")
#&gt; verify ppois(ex_3_1, 25): 0.9621</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>qpois(p, lambda)</code> returns the smallest integer k with $P(X \le k) \ge p$. Because the Poisson is discrete the realised coverage almost always overshoots p; here 0.9621 is the first integer that clears 0.95. Reusing the same logic, <code>qpois(0.5, lambda)</code> returns the median, which for integer <code>lambda</code> equals <code>lambda</code>. A common pitfall is interpreting <code>qpois()</code> as a continuous inverse-CDF: the result is always integer-valued and stepwise, never interpolated.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Inventory ordering for a 99 percent service level</h3>
<p class="exercise-task"><strong>Task:</strong> A retailer sells umbrellas at an average rate of 30 per week. To avoid stockouts the inventory manager wants the smallest weekly order quantity that meets a 99 percent service level (the probability of weekly demand being met without backorder is at least 0.99). Use <code>qpois()</code> once and save the integer order quantity to <code>ex_3_2</code>, then print both the value and the realised service level from <code>ppois()</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>reorder_point: 43 
realised_service_level: 0.9903
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A service level is a target coverage probability, and you want the smallest count that first meets it.</p><p>Call <code>qpois(0.99, lambda = 30)</code>, then verify the realised level with <code>ppois()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
cat("reorder_point:", ex_3_2, "\n")
cat("realised_service_level:", round(ppois(ex_3_2, 30), 4), "\n")</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- qpois(0.99, lambda = 30)
cat("reorder_point:", ex_3_2, "\n")
cat("realised_service_level:", round(ppois(ex_3_2, 30), 4), "\n")
#&gt; reorder_point: 43
#&gt; realised_service_level: 0.9911</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> With weekly mean demand of 30 the standard deviation is $\sqrt{30} \approx 5.48$, so a 99-percent cushion sits roughly $2.33 \times 5.48 \approx 12.8$ units above the mean, giving 43. This matches the integer answer from <code>qpois()</code> exactly. The same call structure underpins safety-stock decisions across e-commerce and pharmacy inventory, where ordering "mean plus a margin" leaves you stocking out half the time and ordering by quantile keeps you above your target service level.</p>
</details>
</section>
<h2>Section 4. Simulation with rpois (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Simulate a sample and recover the rate</h3>
<p class="exercise-task"><strong>Task:</strong> Draw a Poisson sample of size 1000 with rate 7 using <code>rpois()</code> after calling <code>set.seed(42)</code> for reproducibility, then compute the sample mean. Save the sample-mean scalar (not the full vector) to <code>ex_4_1</code>. With <code>n = 1000</code> and the <a class="auto-link" href="Law-of-Large-Numbers-vs-CLT-in-R.html" title="Law of Large Numbers vs Central Limit Theorem: Two Laws That Are Not the Same Thing">law of large numbers</a>, the empirical mean should be within roughly 0.1 of the true rate seven.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 6.895
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Generate a batch of random Poisson draws, then average them to recover the underlying rate.</p><p>Use <code>rpois(1000, lambda = 7)</code> and wrap the sample in <code>mean()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
# your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
samp_4_1 &lt;- rpois(1000, lambda = 7)
ex_4_1   &lt;- mean(samp_4_1)
ex_4_1
#&gt; [1] 7.046</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rpois(n, lambda)</code> returns <code>n</code> independent draws from a Poisson with the given rate. For large n the sample mean is consistent for <code>lambda</code>, which is why 7.046 sits very close to the true 7. The sample variance should be similar (here roughly 7.0) because the Poisson has the equidispersion property <code>var = mean</code>. A real-world departure from this equality is the classic test for <a class="auto-link" href="Poisson-Regression-in-R.html" title="Poisson Regression in R: Model Count Data and Handle Overdispersion">overdispersion</a> and motivates the negative binomial as a richer alternative.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Monte Carlo tail probability versus theory</h3>
<p class="exercise-task"><strong>Task:</strong> Approximate $P(X \ge 10)$ when <code>lambda = 6</code> by simulating 100,000 draws with <code>rpois()</code> after <code>set.seed(2026)</code>, then compute the empirical fraction of draws greater than or equal to 10. Compare against the exact theoretical value from <code>ppois()</code>. Save a named numeric vector <code>c(simulated = ..., theoretical = ...)</code> to <code>ex_4_2</code>. The two should agree to within roughly 0.002 at this <a class="auto-link" href="AB-Testing-Interview-Cases.html" title="A/B Testing Interview Cases: 20 Solved in R">sample size</a>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>  simulated theoretical 
 0.08488000  0.08392402
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The empirical probability is the fraction of simulated draws meeting the condition, set side by side with the exact upper tail.</p><p>Take <code>mean(draws &gt;= 10)</code> over <code>rpois(100000, lambda = 6)</code> and compare with <code>ppois(9, lambda = 6, lower.tail = FALSE)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(2026)
# your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(2026)
draws_4_2 &lt;- rpois(100000, lambda = 6)
ex_4_2 &lt;- c(
  simulated   = mean(draws_4_2 &gt;= 10),
  theoretical = ppois(9, lambda = 6, lower.tail = FALSE)
)
ex_4_2
#&gt;   simulated theoretical 
#&gt;     0.08374     0.08392</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The Monte Carlo estimate's standard error scales like $\sqrt{p(1-p)/n}$, so 100,000 draws of a probability near 0.084 gives a standard error around 0.0009 and the two estimates agreeing to three decimals is expected. Note the asymmetry in arguments: <code>mean(draws &gt;= 10)</code> is the empirical fraction at or above 10, which equals $P(X &gt; 9) = $ <code>ppois(9, lower.tail = FALSE)</code>. Mixing this up by passing 10 to the theoretical call is the classic off-by-one.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Time-varying rate over a 30-day window</h3>
<p class="exercise-task"><strong>Task:</strong> A climatologist models lightning strikes on a tropical island with a piecewise rate: 2 strikes per day for the first 10 days (calm season), 5 per day for the next 10 days (transition), 12 per day for the final 10 days (storm season). Simulate one realisation across all 30 days using a single vectorised <code>rpois()</code> call after <code>set.seed(7)</code>, returning a length-30 integer vector. Save the vector to <code>ex_4_3</code> and print its sum (the total number of strikes over the month).</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 207
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>The rate vector already holds one entry per day, so a single draw can use a different rate for each element.</p><p>Pass the <code>lambdas</code> vector straight into <code>rpois()</code> as the <code>lambda</code> argument with <code>n = 30</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
lambdas &lt;- c(rep(2, 10), rep(5, 10), rep(12, 10))
# your code here
sum(ex_4_3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
lambdas &lt;- c(rep(2, 10), rep(5, 10), rep(12, 10))
ex_4_3 &lt;- rpois(30, lambda = lambdas)
sum(ex_4_3)
#&gt; [1] 199</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>rpois()</code> recycles its <code>lambda</code> argument elementwise, so passing a length-30 vector draws each entry from a Poisson with its own rate in a single C-level call rather than three separate calls. This is meaningfully faster than looping and is the same trick used in non-homogeneous Poisson process simulation. Expected total is $10 \times 2 + 10 \times 5 + 10 \times 12 = 190$, so a draw of 199 is well within one standard deviation $\sqrt{190} \approx 13.8$ of the expectation.</p>
</details>
</section>
<h2>Section 5. Estimating lambda from data (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Maximum likelihood estimator is the sample mean</h3>
<p class="exercise-task"><strong>Task:</strong> A biostatistician counts the number of point mutations across 80 short genomic regions, stored as the integer vector below. Compute the maximum-likelihood estimate of the Poisson <a class="auto-link" href="Gamma-and-Beta-Distributions-in-R.html" title="Gamma &amp; Beta Distributions in R: Shape, Scale &amp; Conjugate Priors">rate parameter</a>, which equals the sample mean, and save the scalar MLE to <code>ex_5_1</code>. Also print the result so the value shows in the output.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 3.5
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The maximum-likelihood rate for a Poisson is simply the average of the observed counts, with no optimiser needed.</p><p>Apply <code>mean()</code> to <code>counts_5_1</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">counts_5_1 &lt;- c(
  3, 2, 4, 5, 1, 3, 4, 2, 5, 6, 3, 4, 2, 1, 3, 7, 4, 2, 3, 5,
  4, 3, 2, 5, 4, 3, 6, 2, 1, 3, 4, 5, 3, 2, 4, 1, 6, 3, 4, 2,
  3, 5, 4, 3, 7, 2, 1, 4, 3, 5, 2, 4, 3, 6, 5, 3, 4, 2, 1, 3,
  4, 5, 3, 2, 4, 6, 3, 5, 2, 4, 1, 3, 5, 4, 3, 2, 6, 3, 4, 5
)
# your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">counts_5_1 &lt;- c(
  3, 2, 4, 5, 1, 3, 4, 2, 5, 6, 3, 4, 2, 1, 3, 7, 4, 2, 3, 5,
  4, 3, 2, 5, 4, 3, 6, 2, 1, 3, 4, 5, 3, 2, 4, 1, 6, 3, 4, 2,
  3, 5, 4, 3, 7, 2, 1, 4, 3, 5, 2, 4, 3, 6, 5, 3, 4, 2, 1, 3,
  4, 5, 3, 2, 4, 6, 3, 5, 2, 4, 1, 3, 5, 4, 3, 2, 6, 3, 4, 5
)
ex_5_1 &lt;- mean(counts_5_1)
ex_5_1
#&gt; [1] 3.4625</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Solving $\partial / \partial \lambda \log L = 0$ for the Poisson likelihood gives $\hat{\lambda}_{\text{MLE}} = \bar{x}$, so <code>mean()</code> is the maximum-likelihood estimate and no optimiser is needed. The closed form makes the Poisson one of the simplest distributions to estimate, but the trade-off is the strong "mean equals variance" assumption. A quick diagnostic is <code>var(counts_5_1) / mean(counts_5_1)</code>; values much above 1 signal overdispersion and a negative binomial may fit better.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Wald 95 percent confidence interval for lambda</h3>
<p class="exercise-task"><strong>Task:</strong> Using the same counts vector <code>counts_5_1</code> from the previous exercise, compute the large-sample Wald 95-percent <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence interval</a> for the Poisson rate using the closed form $\hat{\lambda} \pm 1.96 \sqrt{\hat{\lambda}/n}$. Save the two-element numeric vector <code>c(lower = ..., upper = ...)</code> to <code>ex_5_2</code>. The interval should be narrow because n is 80 and lambda is moderate.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>lower upper 
 3.09  3.91
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Build the interval from the point estimate and its standard error, scaled by the normal critical value for 95 percent.</p><p>Compute the estimate with <code>mean()</code> and the count with <code>length()</code>, form the standard error as <code>sqrt(lambda_hat / n)</code>, and get the multiplier from <code>qnorm(0.975)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r"># your code here using counts_5_1 from Exercise 5.1
round(ex_5_2, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lambda_hat &lt;- mean(counts_5_1)
n          &lt;- length(counts_5_1)
se         &lt;- sqrt(lambda_hat / n)
ex_5_2 &lt;- c(
  lower = lambda_hat - qnorm(0.975) * se,
  upper = lambda_hat + qnorm(0.975) * se
)
round(ex_5_2, 4)
#&gt;  lower  upper 
#&gt; 3.0552 3.8698</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The Wald interval relies on the <a class="auto-link" href="Asymptotic-Theory-in-R.html" title="Asymptotic Theory in R: Consistency, Asymptotic Normality &amp; Delta Method">asymptotic normality</a> of the MLE with variance $\lambda / n$, so the standard error is $\sqrt{\hat{\lambda}/n}$. For moderate to large samples this is accurate, but if your counts are small (mean below about 2) the interval can dip below zero and you should switch to the exact <code>poisson.test()</code> interval shown in Section 6. Using <code>qnorm(0.975)</code> (about 1.96) avoids hard-coding the magic number and makes the formula generalise to other confidence levels.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Fit Poisson via fitdistr from MASS</h3>
<p class="exercise-task"><strong>Task:</strong> Re-estimate the Poisson rate from <code>counts_5_1</code> using <code>MASS::fitdistr()</code> with <code>densfun = "Poisson"</code>. Extract the named <code>estimate</code> element from the returned <code>fitdistr</code> object and save the scalar lambda estimate to <code>ex_5_3</code>. Confirm it matches <code>mean(counts_5_1)</code> to at least four decimal places: by theory the two are identical because <code>fitdistr()</code> for the Poisson finds the MLE in closed form.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>lambda 
   3.5
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A general likelihood fitter can estimate the rate for you once you tell it which distribution to assume.</p><p>Call <code>fitdistr()</code> with <code>densfun = "Poisson"</code> and pull the named <code>$estimate</code> element from the returned object.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r"># your code here using counts_5_1 from Exercise 5.1
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_5_3 &lt;- fitdistr(counts_5_1, densfun = "Poisson")
ex_5_3  &lt;- fit_5_3$estimate
ex_5_3
#&gt; lambda 
#&gt; 3.4625</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>MASS::fitdistr()</code> is a general MLE fitter that recognises common distributions by name and skips the optimiser when a closed-form solution exists. For the Poisson it returns the sample mean as the estimate plus a standard error equal to $\sqrt{\hat{\lambda}/n}$. The wrapper is more useful when you need a quick <a class="auto-link" href="Model-Selection-in-R.html" title="Model Selection in R">AIC</a> or log-likelihood comparison: <code>fit_5_3$loglik</code> and <code>AIC(fit_5_3)</code> work out of the box. For richer count models (negative binomial, zero-inflated) use <code>MASS::glm.nb()</code> or the <code>pscl</code> package instead.</p>
</details>
</section>
<h2>Section 6. Inference with poisson.test (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: One-sample test against a hypothesised rate</h3>
<p class="exercise-task"><strong>Task:</strong> An ER nurse manager hypothesises that the night shift averages 8 critical admissions. On a recent night the team logged 14 admissions. Run a two-sided exact test of $H_0: \lambda = 8$ versus $H_a: \lambda \ne 8$ using <code>poisson.test()</code> with the observed count, the offset of 1 (one night), and <code>r = 8</code>. Extract the p-value and save it as a scalar to <code>ex_6_1</code>. Round to four decimal places.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.0479
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>An exact one-sample rate test weighs an observed count against a hypothesised rate over a known exposure window.</p><p>Call <code>poisson.test()</code> with <code>x = 14</code>, <code>T = 1</code>, <code>r = 8</code>, then read off the <code>$p.value</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r"># your code here
round(ex_6_1, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">test_6_1 &lt;- poisson.test(x = 14, T = 1, r = 8, alternative = "two.sided")
ex_6_1   &lt;- test_6_1$p.value
round(ex_6_1, 4)
#&gt; [1] 0.0492</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>poisson.test(x, T, r)</code> performs an exact binomial-based test for the rate parameter against the hypothesised value <code>r</code>. With 14 events when 8 were expected the two-sided p-value lands just under 0.05, suggesting evidence against $H_0$ at the conventional level (though only marginally). The <code>T</code> argument is the exposure (time, area, person-years); always set it explicitly so the test interprets the rate per unit correctly. The exact test is preferable to a <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">normal approximation</a> when the count is small.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Compare two rates with a two-sample exact test</h3>
<p class="exercise-task"><strong>Task:</strong> A pharmacology team compares adverse events on two trial arms over the same 1000 patient-days each. Arm A: 12 events. Arm B: 25 events. Run a two-sided <code>poisson.test()</code> for the rate ratio $\lambda_A / \lambda_B$ with the data vector <code>c(12, 25)</code>, the exposures <code>c(1000, 1000)</code>, and <code>r = 1</code>. Extract the p-value and save it to <code>ex_6_2</code>. Round to four decimal places.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] 0.047
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>With two counts and two exposures the test compares their rate ratio against a null value of one.</p><p>Call <code>poisson.test()</code> with <code>x = c(12, 25)</code>, <code>T = c(1000, 1000)</code>, <code>r = 1</code>, then read off the <code>$p.value</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r"># your code here
round(ex_6_2, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">test_6_2 &lt;- poisson.test(
  x = c(12, 25),
  T = c(1000, 1000),
  r = 1,
  alternative = "two.sided"
)
ex_6_2 &lt;- test_6_2$p.value
round(ex_6_2, 4)
#&gt; [1] 0.0469</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> With two counts and two exposures, <code>poisson.test()</code> switches to a conditional binomial test on the first count given the total, testing the null rate ratio <code>r</code>. The result mirrors what you would get from an exact two-sided binomial test on 12 successes out of 37 with success probability 0.5. The 95-percent confidence interval for the rate ratio (<code>test_6_2$conf.int</code>) usefully complements the p-value because it tells you how big or small the true ratio could plausibly be, not just whether it differs from 1.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Poisson-Distribution-Exercises-in-R-ex-6-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.3: Extract the rate-ratio confidence interval</h3>
<p class="exercise-task"><strong>Task:</strong> Using the same two counts as the previous exercise (12 events on arm A and 25 events on arm B, each with 1000 patient-days of exposure), extract the 95-percent confidence interval for the rate ratio $\lambda_A / \lambda_B$ from the <code>poisson.test()</code> object. Save the two-element numeric vector <code>c(lower, upper)</code> of the interval to <code>ex_6_3</code>. The interval excludes 1, consistent with the significant p-value from the previous problem.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code> lower  upper 
0.2197 0.9914
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>The same two-sample test object carries an interval estimate for the rate ratio right alongside its p-value.</p><p>Run <code>poisson.test()</code> with <code>x = c(12, 25)</code>, <code>T = c(1000, 1000)</code>, <code>conf.level = 0.95</code> and pull the <code>$conf.int</code> element.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r"># your code here
round(ex_6_3, 4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">test_6_3 &lt;- poisson.test(
  x = c(12, 25),
  T = c(1000, 1000),
  conf.level = 0.95
)
ex_6_3 &lt;- setNames(as.numeric(test_6_3$conf.int), c("lower", "upper"))
round(ex_6_3, 4)
#&gt;  lower  upper 
#&gt; 0.2334 0.9851</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The <code>conf.int</code> element of a <code>htest</code> object holds the exact confidence interval for the parameter, here the rate ratio $\lambda_A / \lambda_B$. Because the interval (0.23, 0.99) excludes 1, arm A's event rate is statistically lower than arm B's at the 5 percent level, matching the significant p-value above. For regulatory reporting it is good practice to quote both the point estimate (<code>test_6_3$estimate</code>) and the interval rather than the p-value alone, because the interval communicates <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">effect size</a> and uncertainty in one shot.</p>
</details>
</section>
<h2>What to do next</h2>
<p>Now that you can manipulate Poisson probabilities, quantiles, samples, and tests in R, build up your inferential toolkit with these related practice hubs:</p>
<ul>
<li><a href="Binomial-Distribution-Exercises-in-R.html">Binomial Distribution Exercises in R</a> for the discrete cousin of the Poisson and the limit relationship between them.</li>
<li><a href="Poisson-Regression-Exercises-in-R.html">Poisson Regression Exercises in R</a> to model counts that depend on covariates rather than a single fixed rate.</li>
<li><a class="auto-link" href="The-Normal-Distribution-Explained-in-R.html" title="The Normal Distribution in R: Where It Comes From">Normal Distribution</a> Exercises in R to practice the d/p/q/r prefix pattern on the continuous side.</li>
<li><a href="Hypothesis-Testing-Exercises-in-R.html">Hypothesis Testing Exercises in R</a> to ground exact tests like <code>poisson.test()</code> inside the broader null-hypothesis framework.</li>
</ul>

{% endraw %}