---
title: "R for Biostatistics Exercises: 20 Real-World Practice Problems"
description: "Twenty clinical and biostatistics exercises in R: trial baselines, survival models, mixed models, dose response, power. Hidden solutions and reasoning."
keywords: "biostatistics in R exercises, clinical trial R, survival analysis R, mixed models R, dose response R, R biostatistics practice"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "biostatistics in r exercises|clinical trial r exercises|survival analysis r|mixed models r|biostatistics practice|r for clinical trials"
auto_link_case_sensitive: false
sidebar_title: "R for Biostatistics"
sidebar_order: "147"
fr_parent: "Clinical-Trials-Design-in-R.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>R for Biostatistics Exercises: 20 Real-World Practice Problems</h1>
<p class="lead">Twenty scenario based biostatistics exercises grouped into six themed sections: clinical trial wrangling, two sample inference, survival analysis, <a class="auto-link" href="Mixed-Effects-Models-Exercises-in-R.html" title="Mixed Effects Models Exercises in R: 15 Practice Problems">mixed effects models</a>, dose response, and reporting. Every problem ships with an expected result so you can verify, and solutions are hidden behind reveal toggles so you actually try first.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="20" data-time="50" data-xp="300"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(dplyr)
library(tibble)
library(tidyr)
library(broom)
library(survival)
library(lme4)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Clinical trial data: arms, baselines, and randomization (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="R-for-Biostatistics-Exercises-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Build a baseline characteristics table by treatment arm</h3>
<p class="exercise-task"><strong>Task:</strong> A clinical trial statistician is preparing the Table 1 baseline summary for a Phase II oncology trial with 40 subjects randomized 1:1 to placebo and drug X. Using the inline <code>trial</code> tibble built below, compute mean age and mean baseline tumour size per arm, plus the count per arm. Save the result to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 2 × 4
  arm         n mean_age mean_tumour_mm
  &lt;chr&gt;   &lt;int&gt;    &lt;dbl&gt;          &lt;dbl&gt;
1 drug       20     57.0           35.6
2 placebo    20     60.4           34.6
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A Table 1 reports one row per treatment arm, so the 40 subjects need to collapse down to per-arm aggregates.</p><p>Group by <code>arm</code>, then <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summarise</a> with <code>n()</code>, <code>mean(age)</code>, and <code>mean(tumour_mm)</code>, passing <code>.groups = "drop"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
trial &lt;- tibble(
  subject_id = sprintf("S%03d", 1:40),
  arm        = rep(c("placebo", "drug"), each = 20),
  age        = round(rnorm(40, 59, 8)),
  tumour_mm  = round(rnorm(40, 34.6, 6), 1)
)

ex_1_1 &lt;- trial |&gt;
  # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(42)
trial &lt;- tibble(
  subject_id = sprintf("S%03d", 1:40),
  arm        = rep(c("placebo", "drug"), each = 20),
  age        = round(rnorm(40, 59, 8)),
  tumour_mm  = round(rnorm(40, 34.6, 6), 1)
)

ex_1_1 &lt;- trial |&gt;
  group_by(arm) |&gt;
  summarise(
    n              = n(),
    mean_age       = mean(age),
    mean_tumour_mm = mean(tumour_mm),
    .groups = "drop"
  )

ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Table 1 in a clinical study report (CSR) summarises baseline characteristics by arm so a reviewer can confirm balance after randomization. <code>group_by(arm) |&gt; summarise()</code> produces one row per arm; passing <code>.groups = "drop"</code> returns an ungrouped tibble so downstream code does not inherit a stray grouping. For production tables, <code>gtsummary::tbl_summary(by = arm)</code> adds p values and formatted output, but the raw aggregation is what regulators inspect.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Check randomization balance across strata with chi square</h3>
<p class="exercise-task"><strong>Task:</strong> The data manager wants reassurance that randomization preserved balance between two stratification factors (sex and arm) in the same 40 subject trial. Build a 2 by 2 <a class="auto-link" href="R-Mosaic-Plots.html" title="R Mosaic Plots: Visualize Categorical Variable Relationships">contingency table</a> of <code>sex</code> versus <code>arm</code> for the augmented <code>trial2</code> tibble, then run a chi square test of independence. Save the htest result to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Pearson's Chi-squared test

data:  tab
X-squared = 0, df = 1, p-value = 1
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Balance between two categorical factors is a question of whether their <a class="auto-link" href="Categorical-Data-in-R.html" title="Categorical Data in R: Frequency Tables, Crosstabs &amp; Mosaic Plots">cross-tabulation</a> departs from independence.</p><p>Build the cross-tab with <code>table(trial2$sex, trial2$arm)</code>, then pass that table to <code>chisq.test()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
trial2 &lt;- trial |&gt;
  mutate(sex = sample(c("F", "M"), n(), replace = TRUE))

# your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(7)
trial2 &lt;- trial |&gt;
  mutate(sex = sample(c("F", "M"), n(), replace = TRUE))

tab &lt;- table(trial2$sex, trial2$arm)
ex_1_2 &lt;- chisq.test(tab)
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A large p value here is the desired result: it says we cannot reject independence between sex and arm, so randomization did not accidentally concentrate one sex into one arm. Yates' continuity correction defaults to on for 2 by 2 tables; for sparse cells (any expected count below 5) switch to <code>fisher.test(tab)</code>. Imbalanced strata at baseline force the analysis to adjust covariates in the primary model, which is a regulatory complication worth avoiding.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Flag protocol deviations where actual dose missed the plan</h3>
<p class="exercise-task"><strong>Task:</strong> A study coordinator must flag protocol deviations before the data lock. Using the inline <code>dosing</code> tibble below, compute the absolute deviation between <code>dose_planned_mg</code> and <code>dose_actual_mg</code> for each visit, then return rows where the deviation exceeds 10% of the planned dose. Save to <code>ex_1_3</code> keeping subject_id, visit, both dose columns, and a <code>pct_dev</code> column.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 3 × 5
  subject_id visit dose_planned_mg dose_actual_mg pct_dev
  &lt;chr&gt;      &lt;dbl&gt;           &lt;dbl&gt;          &lt;dbl&gt;   &lt;dbl&gt;
1 S004           2              50             42      16
2 S012           3             100            110      10
3 S019           4             100             80      20
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>An absolute milligram gap scales with dose level, so deviations are only comparable once expressed relative to the plan.</p><p>In a <code>mutate()</code> compute <code>100 * abs(dose_actual_mg - dose_planned_mg) / dose_planned_mg</code>, then <code>filter()</code> rows where it is at least 10.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">dosing &lt;- tribble(
  ~subject_id, ~visit, ~dose_planned_mg, ~dose_actual_mg,
  "S001",      1,      50,               50,
  "S004",      2,      50,               42,
  "S007",      3,      100,              98,
  "S012",      3,      100,              110,
  "S019",      4,      100,              80,
  "S022",      4,      100,              95
)

ex_1_3 &lt;- dosing |&gt;
  # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">dosing &lt;- tribble(
  ~subject_id, ~visit, ~dose_planned_mg, ~dose_actual_mg,
  "S001",      1,      50,               50,
  "S004",      2,      50,               42,
  "S007",      3,      100,              98,
  "S012",      3,      100,              110,
  "S019",      4,      100,              80,
  "S022",      4,      100,              95
)

ex_1_3 &lt;- dosing |&gt;
  mutate(pct_dev = round(100 * abs(dose_actual_mg - dose_planned_mg) / dose_planned_mg, 1)) |&gt;
  filter(pct_dev &gt;= 10)

ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> ICH GCP defines a protocol deviation as any departure from the approved protocol; dosing windows are a common offender. Rather than filter on absolute mg (which scales with the dose level), the percent deviation is comparable across cohorts. Always compute on <code>abs(diff)</code> so under and over dosing both trigger. In production, the threshold and the columns surfaced (site_id, deviation_category) come from a Statistical <a class="auto-link" href="Pre-Registration-for-R-Analysis.html" title="Pre-Registration for R Analysis: OSF, AsPredicted &amp; Analysis Plans">Analysis Plan</a> section.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-1-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.4: Compute analysis populations after dropout</h3>
<p class="exercise-task"><strong>Task:</strong> The biostatistician needs the intention to treat (ITT) and per protocol (PP) population counts per arm. Using the inline <code>enrol</code> tibble below where <code>completed == TRUE</code> marks PP eligibility, return one tibble row per arm with columns <code>arm</code>, <code>itt_n</code>, <code>pp_n</code>, <code>dropout_rate</code> (1 minus pp_n / itt_n, rounded to 2 dp). Save to <code>ex_1_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 2 × 4
  arm     itt_n  pp_n dropout_rate
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;
1 drug      100    90         0.1 
2 placebo   100    98         0.02
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Each arm needs a randomized count, a completer count, and the gap between them expressed as a rate.</p><p>Group by <code>arm</code> and summarise <code>n()</code>, <code>sum(completed)</code>, and <code>round(1 - pp_n / itt_n, 2)</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(11)
enrol &lt;- tibble(
  subject_id = sprintf("S%03d", 1:200),
  arm        = rep(c("placebo", "drug"), each = 100),
  completed  = c(sample(c(TRUE, FALSE), 100, replace = TRUE, prob = c(0.92, 0.08)),
                 sample(c(TRUE, FALSE), 100, replace = TRUE, prob = c(0.87, 0.13)))
)

ex_1_4 &lt;- enrol |&gt;
  # your code here
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(11)
enrol &lt;- tibble(
  subject_id = sprintf("S%03d", 1:200),
  arm        = rep(c("placebo", "drug"), each = 100),
  completed  = c(sample(c(TRUE, FALSE), 100, replace = TRUE, prob = c(0.92, 0.08)),
                 sample(c(TRUE, FALSE), 100, replace = TRUE, prob = c(0.87, 0.13)))
)

ex_1_4 &lt;- enrol |&gt;
  group_by(arm) |&gt;
  summarise(
    itt_n = n(),
    pp_n  = sum(completed),
    dropout_rate = round(1 - pp_n / itt_n, 2),
    .groups = "drop"
  )

ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> ITT keeps every randomized subject (the gold standard for efficacy claims because it preserves randomization), while PP restricts to subjects who completed per protocol (informs adherence questions). A large arm asymmetric dropout (drug arm losing more subjects than placebo) is itself a safety signal, so this summary is the first thing a Data Safety Monitoring Board reviews. The CONSORT diagram in the publication is built from exactly this aggregation.</p>
</details>
</section>
<h2>Section 2. Two sample inference for clinical outcomes (4 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Two sample t test on a continuous primary endpoint</h3>
<p class="exercise-task"><strong>Task:</strong> The principal investigator wants to know whether drug X reduced LDL cholesterol versus placebo after 12 weeks. Using the inline <code>ldl</code> tibble below, run an unpaired two sample Welch t test of <code>ldl_mg_dl</code> by <code>arm</code>. Save the full htest object to <code>ex_2_1</code> and inspect the p value and <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence interval</a>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Welch Two Sample t-test

data:  ldl_mg_dl by arm
t = -4.6159, df = 37.416, p-value = 4.497e-05
alternative hypothesis: true difference in means between group drug and group placebo is not equal to 0
95 percent confidence interval:
 -21.076203  -8.220838
sample estimates:
   mean in group drug mean in group placebo 
             115.9937              130.6422
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Comparing a continuous endpoint across two independent arms is a textbook two sample mean comparison.</p><p>Call <code>t.test()</code> with the formula <code>ldl_mg_dl ~ arm</code> and <code>data = ldl</code>; the Welch variant is the default.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(3)
ldl &lt;- tibble(
  subject_id = sprintf("S%03d", 1:40),
  arm        = rep(c("drug", "placebo"), each = 20),
  ldl_mg_dl  = c(rnorm(20, 118, 12), rnorm(20, 130, 12))
)

ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(3)
ldl &lt;- tibble(
  subject_id = sprintf("S%03d", 1:40),
  arm        = rep(c("drug", "placebo"), each = 20),
  ldl_mg_dl  = c(rnorm(20, 118, 12), rnorm(20, 130, 12))
)

ex_2_1 &lt;- t.test(ldl_mg_dl ~ arm, data = ldl)
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Welch is the default because it does not assume equal variances, which is safer when arm sample sizes or spreads differ. The <code>formula = y ~ group</code> syntax is the trial reporting convention because it mirrors the model card. A 95 percent confidence interval that excludes 0 corresponds to p below 0.05 at the same alpha; report both because regulators care more about the <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">effect size</a> and its precision than the p value alone. For skewed endpoints, switch to <code>wilcox.test()</code> (see exercise 2.3).</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Paired t test for pre versus post blood pressure</h3>
<p class="exercise-task"><strong>Task:</strong> A cardiology team measured systolic blood pressure at baseline and after 8 weeks on a new antihypertensive in 25 patients. Using the inline <code>bp</code> tibble below, run a paired t test on <code>pre_sbp</code> versus <code>post_sbp</code> and save the htest to <code>ex_2_2</code>. Pair by row order.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Paired t-test

data:  bp$pre_sbp and bp$post_sbp
t = 3.0559, df = 24, p-value = 0.005432
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
  2.674766 13.805234
sample estimates:
mean difference 
           8.24
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Two measurements on the same patient are linked, so the test must operate on within-subject changes.</p><p>Pass <code>bp$pre_sbp</code> and <code>bp$post_sbp</code> to <code>t.test()</code> with <code>paired = TRUE</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(5)
bp &lt;- tibble(
  subject_id = sprintf("S%03d", 1:25),
  pre_sbp    = round(rnorm(25, 148, 9)),
  post_sbp   = round(rnorm(25, 138, 9))
)

ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(5)
bp &lt;- tibble(
  subject_id = sprintf("S%03d", 1:25),
  pre_sbp    = round(rnorm(25, 148, 9)),
  post_sbp   = round(rnorm(25, 138, 9))
)

ex_2_2 &lt;- t.test(bp$pre_sbp, bp$post_sbp, paired = TRUE)
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Pairing strips between subject variance and tests only the within subject change, which sharply boosts power for crossover and longitudinal designs. Forgetting <code>paired = TRUE</code> here would shrink the t statistic and inflate the confidence interval, because the unpaired test would treat the 50 observations as independent. If the differences are non normal, the paired analogue is <code>wilcox.test(..., paired = TRUE)</code>. The reporting convention is "mean change (95 percent CI), n = X".</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Wilcoxon rank sum on a skewed lab marker</h3>
<p class="exercise-task"><strong>Task:</strong> A liver biomarker (ALT, in U/L) tends to be right skewed; the regulator asked for a non parametric two sample test. Using the inline <code>alt</code> tibble below, run a Wilcoxon rank sum (Mann Whitney U) comparing <code>alt_u_l</code> by <code>arm</code> and save the htest to <code>ex_2_3</code>. Set <code>exact = FALSE</code> so the <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">normal approximation</a> is used.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Wilcoxon rank sum test with continuity correction

data:  alt_u_l by arm
W = 109, p-value = 0.901
alternative hypothesis: true location shift is not equal to 0
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A skewed marker breaks the normality a mean-based test relies on, so compare ranks instead of raw values.</p><p>Use <code>wilcox.test()</code> with the formula <code>alt_u_l ~ arm</code>, <code>data = alt</code>, and <code>exact = FALSE</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(9)
alt &lt;- tibble(
  subject_id = sprintf("S%03d", 1:30),
  arm        = rep(c("drug", "placebo"), each = 15),
  alt_u_l    = c(rexp(15, 1/30), rexp(15, 1/55))
)

ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(9)
alt &lt;- tibble(
  subject_id = sprintf("S%03d", 1:30),
  arm        = rep(c("drug", "placebo"), each = 15),
  alt_u_l    = c(rexp(15, 1/30), rexp(15, 1/55))
)

ex_2_3 &lt;- wilcox.test(alt_u_l ~ arm, data = alt, exact = FALSE)
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Wilcoxon rank sum tests for a location shift on the ranks rather than the raw values, so heavy right tails (common for transaminases, bilirubin, troponin) do not pull the <a class="auto-link" href="Hypothesis-Testing-in-R.html" title="Hypothesis Testing in R: Understand the Framework, Not Just the p-Value">test statistic</a> around. <code>exact = FALSE</code> switches to a fast normal approximation, which is the right call once either group exceeds about 20 ranks. Report a Hodges Lehmann pseudomedian (<code>conf.int = TRUE</code>) alongside the p value because a non parametric test still owes the reader an effect size.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-2-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.4: Fisher exact test for an adverse event rate difference</h3>
<p class="exercise-task"><strong>Task:</strong> The safety team observed 9 of 50 subjects in the drug arm reported a rash versus 2 of 50 in placebo. The cell counts are small enough that the chi square approximation is shaky. Build the 2 by 2 table and run Fisher exact test of rash incidence by arm. Save the htest to <code>ex_2_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>	Fisher's Exact Test for Count Data

data:  ae_tab
p-value = 0.05112
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.9939756 52.0291553
sample estimates:
odds ratio 
  5.189912
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Small cell counts make the chi square approximation unreliable, so use a test that computes exact probabilities.</p><p>Pass the pre-built <code>ae_tab</code> matrix to <code>fisher.test()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ae_tab &lt;- matrix(
  c(9, 41, 2, 48),
  nrow  = 2,
  byrow = FALSE,
  dimnames = list(rash = c("yes", "no"), arm = c("drug", "placebo"))
)

ex_2_4 &lt;- # your code here
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ae_tab &lt;- matrix(
  c(9, 41, 2, 48),
  nrow  = 2,
  byrow = FALSE,
  dimnames = list(rash = c("yes", "no"), arm = c("drug", "placebo"))
)

ex_2_4 &lt;- fisher.test(ae_tab)
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Whenever an expected cell count drops below 5, Fisher exact is preferred over <code>chisq.test()</code> because it conditions on the row and column marginals and computes the exact hypergeometric probability. The reported <a class="auto-link" href="Logistic-Regression-in-R.html" title="Logistic Regression in R: From glm() to Odds Ratios, ROC, and AUC">odds ratio</a> is conditional on the margins, which is a slightly different estimand than the unconditional MLE you would get from <code>glm(..., family = binomial)</code>; pick one and disclose it. For larger tables, switch to <code>fisher.test(..., simulate.p.value = TRUE)</code> to keep runtime sane.</p>
</details>
</section>
<h2>Section 3. Survival analysis (4 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="R-for-Biostatistics-Exercises-ex-3-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 3.1: Kaplan Meier estimate of overall survival from the lung dataset</h3>
<p class="exercise-task"><strong>Task:</strong> A thoracic oncology fellow wants the overall median survival from the built in <code>lung</code> dataset (NCCTG advanced lung cancer cohort). <code>time</code> is in days and <code>status</code> codes 1 = censored, 2 = death. Fit <code>survfit(Surv(time, status == 2) ~ 1, data = lung)</code> and save the survfit object to <code>ex_3_1</code>. Inspect <code>summary(ex_3_1)$table</code> for the median.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call: survfit(formula = Surv(time, status == 2) ~ 1, data = lung)
#&gt;
#&gt;        n events median 0.95LCL 0.95UCL
#&gt; [1,] 228    165    310     285     363</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Overall survival with no grouping is a single curve estimated from follow-up time and event status.</p><p>Fit <code>survfit()</code> with the formula <code>Surv(time, status == 2) ~ 1</code> and <code>data = lung</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- survfit(Surv(time, status == 2) ~ 1, data = lung)
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>Surv(time, event)</code> is a two column object recording follow up time and whether the event occurred (or the subject was censored at that time). In <code>lung</code>, the original coding stores 1 for censored and 2 for death, so the <code>status == 2</code> predicate creates the 0/1 indicator the model needs. The reported median (310 days) is the time at which the Kaplan Meier estimate crosses 0.5; if fewer than half the subjects have died, the median is <code>NA</code>. For a graphical KM curve, pass the fit to <code>plot()</code> or <code>survminer::ggsurvplot()</code>.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Log rank test comparing survival by ECOG performance status</h3>
<p class="exercise-task"><strong>Task:</strong> The PI asks whether ECOG performance status (<code>ph.ecog</code>) is associated with overall survival in <code>lung</code>. Drop subjects with missing ECOG, then run <code>survdiff(Surv(time, status == 2) ~ ph.ecog, data = ...)</code> to compute the log rank chi square and p value. Save the survdiff object to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
survdiff(formula = Surv(time, status == 2) ~ ph.ecog, data = lung_clean)

            N Observed Expected (O-E)^2/E (O-E)^2/V
ph.ecog=0  63       37   54.153    5.4331    8.2119
ph.ecog=1 113       82   83.528    0.0279    0.0573
ph.ecog=2  50       44   26.147   12.1893   14.6491
ph.ecog=3   1        1    0.172    3.9733    4.0040

 Chisq= 22  on 3 degrees of freedom, p= 7e-05
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Asking whether a grouping factor shifts survival is a test of equality between several curves.</p><p>Run <code>survdiff()</code> with the formula <code>Surv(time, status == 2) ~ ph.ecog</code> and <code>data = lung_clean</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_clean &lt;- lung |&gt;
  filter(!is.na(ph.ecog))

ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_clean &lt;- lung |&gt;
  filter(!is.na(ph.ecog))

ex_3_2 &lt;- survdiff(Surv(time, status == 2) ~ ph.ecog, data = lung_clean)
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The log rank test (Mantel Cox) is the standard test of equality between survival curves; it weights each event time equally so it has maximum power when hazards are proportional. The tiny p value here (7e-05) tells you ECOG groups differ on survival, but it does not tell you which pairs differ or by how much: for that, fit a Cox model (exercise 3.3) and read the per level hazard ratios. When proportional hazards is doubtful, switch to <code>survdiff(..., rho = 1)</code> for Peto Peto, which weights early events more.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Fit a Cox proportional hazards model with age and ECOG</h3>
<p class="exercise-task"><strong>Task:</strong> The principal investigator wants adjusted hazard ratios for <code>age</code> and <code>ph.ecog</code> on overall survival in <code>lung</code>. Drop ECOG missing rows, fit <code>coxph(Surv(time, status == 2) ~ age + ph.ecog, data = ...)</code>, and save the model to <code>ex_3_3</code>. Inspect the coefficients to read the HR per unit increase.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
coxph(formula = Surv(time, status == 2) ~ age + ph.ecog, data = lung_clean)

            coef exp(coef) se(coef)     z        p
age     0.011281  1.011345 0.009319 1.211 0.226082
ph.ecog 0.443485  1.558128 0.115831 3.829 0.000129

Likelihood ratio test=19.06  on 2 df, p=7.279e-05
n= 227, number of events= 164
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Adjusted hazard ratios come from a regression that models how covariates multiplicatively scale the hazard.</p><p>Fit <code>coxph()</code> with the formula <code>Surv(time, status == 2) ~ age + ph.ecog</code> and <code>data = lung_clean</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_clean &lt;- lung |&gt;
  filter(!is.na(ph.ecog))

ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_clean &lt;- lung |&gt;
  filter(!is.na(ph.ecog))

ex_3_3 &lt;- coxph(Surv(time, status == 2) ~ age + ph.ecog, data = lung_clean)
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A Cox model leaves the baseline hazard unspecified and models only how covariates multiplicatively shift it, which is why hazard ratios (<code>exp(coef)</code>) are the reported effect size. An HR of 1.56 for ECOG means each one point worse performance score is associated with a 56 percent higher hazard of death at any moment, holding age fixed. The <a class="auto-link" href="Likelihood-Ratio-Wald-and-Score-Tests-in-R.html" title="Likelihood Ratio, Wald &amp; Score Tests in R: Three Ways to Test Hypotheses">likelihood ratio test</a> (preferred over Wald for small samples) tests the global null that both coefficients are zero. Report HR with 95 percent CI from <code>confint(ex_3_3)</code> and <code>exp()</code> them for the paper.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-3-4" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 3.4: Test the proportional hazards assumption with Schoenfeld residuals</h3>
<p class="exercise-task"><strong>Task:</strong> Before relying on the Cox model from exercise 3.3, check the proportional hazards assumption with <code>cox.zph()</code>. Save the cox.zph object to <code>ex_3_4</code> and inspect the per covariate and global p values; a small p value indicates a violation (the hazard ratio is not constant over time).</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;           chisq df    p
#&gt; age      0.4815  1 0.49
#&gt; ph.ecog  3.0890  1 0.08
#&gt; GLOBAL   3.5610  2 0.17</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>The assumption to check is whether each covariate's effect stays constant as follow-up time passes.</p><p>Pass the fitted model <code>ex_3_3</code> to <code>cox.zph()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
ex_3_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- cox.zph(ex_3_3)
ex_3_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>cox.zph()</code> regresses scaled Schoenfeld residuals on a function of time (default: KM transform) and tests the slope against zero. Per covariate p values flag whether that covariate's HR drifts; the GLOBAL row pools them. Here the global p value of 0.17 does not reject PH, so the Cox model is defensible. If PH fails, the regulator expects either a stratified Cox model (<code>strata(ph.ecog)</code>), a time varying coefficient (<code>tt()</code>), or a switch to an accelerated failure time model. A graphical companion is <code>plot(ex_3_4)</code>.</p>
</details>
</section>
<h2>Section 4. Mixed effects models for longitudinal data (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Random intercept model for reaction time on sleepstudy</h3>
<p class="exercise-task"><strong>Task:</strong> Sleep researchers tracked reaction time across 10 days of sleep restriction in the built in <code>sleepstudy</code> dataset (lme4 package, 18 subjects). Fit a linear mixed model with a fixed effect of <code>Days</code> and a random intercept by <code>Subject</code>: <code>lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)</code>. Save the fitted model to <code>ex_4_1</code> and inspect fixed effects with <code>summary()</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Reaction ~ Days + (1 | Subject)
   Data: sleepstudy
REML criterion at convergence: 1786.465
Random effects:
 Groups   Name        Std.Dev.
 Subject  (Intercept) 37.12   
 Residual             30.99   
Number of obs: 180, groups:  Subject, 18
Fixed Effects:
(Intercept)         Days  
     251.41        10.47
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Each subject deserves their own baseline reaction time while the day effect is shared across everyone.</p><p>Fit <code>lmer()</code> with <code>Reaction ~ Days + (1 | Subject)</code> and <code>data = sleepstudy</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The random intercept (1 | Subject) gives each subject their own baseline reaction time, soaking up the obvious between subject variation (some people are just slower). The fixed slope of 10.47 ms per day of sleep restriction is the population average effect, which is the parameter a journal would report. The two <a class="auto-link" href="Multilevel-Models-in-R.html" title="Multilevel Models in R With brms: When Group Differences Beat Group Averages">variance components</a> (Subject 37.12, Residual 30.99) say roughly half the noise is between subject and half within, which is a useful sanity check for any cluster randomized or longitudinal design.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Compare random intercept versus random slope models via likelihood ratio</h3>
<p class="exercise-task"><strong>Task:</strong> Does sleep deprivation hit some subjects harder than others? Fit a richer model with a random slope on Days plus a random intercept: <code>lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy, REML = FALSE)</code> and compare it against the random intercept only baseline (also refit with <code>REML = FALSE</code>) using <code>anova()</code>. Save the <a class="auto-link" href="https://r-statistics.co/How-to-do-One-Way-ANOVA-in-R.html" title="One-Way ANOVA in R: Compare Group Means (With Examples)">anova</a> result to <code>ex_4_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Data: sleepstudy
Models:
m_ri: Reaction ~ Days + (1 | Subject)
m_rs: Reaction ~ Days + (Days | Subject)
     npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)    
m_ri    4 1802.1 1814.8 -897.04    1794.1                         
m_rs    6 1763.9 1783.1 -875.97    1751.9 42.139  2  7.072e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Deciding whether the richer random structure earns its keep is a nested model comparison.</p><p>Pass the two pre-fitted models <code>m_ri</code> and <code>m_rs</code> to <code>anova()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">m_ri &lt;- lmer(Reaction ~ Days + (1 | Subject),     data = sleepstudy, REML = FALSE)
m_rs &lt;- lmer(Reaction ~ Days + (Days | Subject),  data = sleepstudy, REML = FALSE)

ex_4_2 &lt;- # your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">m_ri &lt;- lmer(Reaction ~ Days + (1 | Subject),     data = sleepstudy, REML = FALSE)
m_rs &lt;- lmer(Reaction ~ Days + (Days | Subject),  data = sleepstudy, REML = FALSE)

ex_4_2 &lt;- anova(m_ri, m_rs)
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> When comparing nested models that differ in random effect structure, refit with maximum likelihood (<code>REML = FALSE</code>) because REML log likelihoods are only comparable for models with identical fixed effects. The chi square of 42 on 2 df (the variance of the random slope and its covariance with the intercept) gives an absurdly small p value, telling you sleep deprivation rates vary meaningfully across people. Failure to include the random slope when it is warranted yields anti conservative standard errors on the fixed effect, the classic <a class="auto-link" href="Type-I-and-Type-II-Errors-in-R.html" title="Type I and Type II Errors in R: Visualise the Trade-Off Between α and Power">Type I error</a> inflation Barr et al. flagged.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Extract subject specific intercepts (BLUPs) and rank them</h3>
<p class="exercise-task"><strong>Task:</strong> A trial coordinator wants to identify which sleepstudy subjects start sharpest. From <code>ex_4_1</code> (the random intercept model), extract the conditional modes (<code>ranef()</code>) for each Subject, add them to the model's grand mean intercept, and return a tibble sorted ascending by <code>predicted_baseline_ms</code> with columns <code>Subject</code> and <code>predicted_baseline_ms</code>. Save to <code>ex_4_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 18 × 2
   Subject predicted_baseline_ms
   &lt;fct&gt;                   &lt;dbl&gt;
 1 309                      174.
 2 310                      188.
 3 335                      206.
 4 349                      230.
 5 351                      244.
 6 370                      245.
 7 371                      248.
 8 334                      248.
 9 330                      256.
10 369                      258.
11 332                      260.
12 331                      262.
13 350                      266.
14 333                      268.
15 372                      270.
16 352                      288.
17 308                      292.
18 337                      324.
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A subject's predicted baseline is the population intercept plus that subject's own deviation from it.</p><p>Pull the grand mean with <code>fixef()</code>, the per-subject deviations with <code>ranef()$Subject</code>, build a <code>tibble()</code>, then <code>arrange()</code> by the baseline.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">gm &lt;- fixef(ex_4_1)["(Intercept)"]
re &lt;- ranef(ex_4_1)$Subject

ex_4_3 &lt;- tibble(
  Subject = rownames(re),
  predicted_baseline_ms = gm + re[, "(Intercept)"]
) |&gt;
  mutate(Subject = factor(Subject)) |&gt;
  arrange(predicted_baseline_ms)

ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>ranef()</code> returns each subject's BLUP (best linear unbiased predictor), which is the shrunken deviation from the population intercept. Adding it back to <code>fixef()["(Intercept)"]</code> reconstructs the per subject expected reaction time at Day 0. Shrinkage pulls subjects with few observations toward the population mean (a Bayesian style <a class="auto-link" href="ML-Interview-Questions-in-R.html" title="ML Interview Questions in R: 25 Solved Problems">regularization</a>), which is exactly why mixed models outperform per subject regressions when data is sparse. For uncertainty intervals on the BLUPs, use <code>arm::sim()</code> or <code>merTools::predictInterval()</code>.</p>
</details>
</section>
<h2>Section 5. Dose response and regression (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="R-for-Biostatistics-Exercises-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: One way ANOVA on tooth growth across delivery methods</h3>
<p class="exercise-task"><strong>Task:</strong> A pharmacology team is screening vitamin C delivery methods on guinea pig odontoblast length using the built in <code>ToothGrowth</code> dataset (60 pigs, two methods, three doses). Fit a one way ANOVA of <code>len</code> by <code>supp</code> (delivery method) and save the aov object to <code>ex_5_1</code>. Inspect with <code>summary()</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
supp         1    205  205.35   3.668 0.0604 .
Residuals   58   3247   55.98                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Testing one continuous outcome across the levels of a single factor is the simplest analysis of variance.</p><p>Fit <code>aov()</code> with the formula <code>len ~ supp</code> and <code>data = ToothGrowth</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
summary(ex_5_1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- aov(len ~ supp, data = ToothGrowth)
summary(ex_5_1)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> With a single two level factor, one way ANOVA returns an F statistic that is exactly the square of the equal variance two sample t statistic; the p value here (0.06) sits at the conventional decision boundary. The borderline result is misleading because the design crosses <code>supp</code> with <code>dose</code>, and <code>dose</code> carries most of the variance. The honest model is a two way ANOVA that includes both factors plus their interaction (exercise 5.2), which is also the analysis pre specified in any well designed factorial experiment.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Two way ANOVA with supplement by dose interaction</h3>
<p class="exercise-task"><strong>Task:</strong> Continuing on <code>ToothGrowth</code>, fit a two way ANOVA of <code>len</code> against <code>supp</code>, <code>dose</code> (treated as a factor), and the interaction <code>supp:dose</code>. Save the aov to <code>ex_5_2</code> and inspect <code>summary()</code> to read each term's F statistic and p value.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
supp               1  205.4   205.4  15.572 0.000231 ***
factor(dose)       2 2426.4  1213.2  92.000  &lt; 2e-16 ***
supp:factor(dose)  2  108.3    54.2   4.107 0.021860 *  
Residuals         54  712.1    13.2                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Two factors plus the chance that their effects depend on each other call for a crossed model.</p><p>Fit <code>aov()</code> with <code>len ~ supp * factor(dose)</code>; the <code>*</code> expands to both main effects and the interaction.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
summary(ex_5_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- aov(len ~ supp * factor(dose), data = ToothGrowth)
summary(ex_5_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Wrapping <code>dose</code> in <code>factor()</code> lets the model estimate a separate mean per dose rather than enforcing a linear trend; with three levels this matters because the dose effect is not perfectly linear. The <code>supp * factor(dose)</code> shorthand expands to main effects plus the two way interaction. The significant interaction (p = 0.022) says the supplement effect depends on dose: at 0.5 and 1.0 mg/day VC outperforms OJ; at 2.0 mg/day they converge. Always interpret interactions before main effects when both are significant.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="R-for-Biostatistics-Exercises-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Logistic regression for binary endpoint with two covariates</h3>
<p class="exercise-task"><strong>Task:</strong> A vaccine immunology team has a binary responder endpoint (seroconverted yes or no) and wants to model it on <code>age</code> and <code>dose_mg</code>. Using the inline <code>vax</code> tibble below, fit <code>glm(responder ~ age + dose_mg, data = vax, family = binomial)</code>. Save the glm object to <code>ex_5_3</code> and inspect coefficients with <code>summary()</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
glm(formula = responder ~ age + dose_mg, family = binomial, data = vax)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -2.745960   0.955537  -2.874  0.00406 **
age          0.040023   0.020264   1.975  0.04826 * 
dose_mg      0.005715   0.006514   0.877  0.38026   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 128.21  on 99  degrees of freedom
Residual deviance: 122.34  on 97  degrees of freedom
AIC: 128.34

Number of Fisher Scoring iterations: 4
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A yes/no endpoint needs a model that predicts a probability rather than a raw number.</p><p>Fit <code>glm()</code> with <code>responder ~ age + dose_mg</code>, <code>data = vax</code>, and <code>family = binomial</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(13)
vax &lt;- tibble(
  subject_id = sprintf("S%03d", 1:100),
  age        = round(rnorm(100, 45, 12)),
  dose_mg    = sample(c(10, 25, 50, 100), 100, replace = TRUE),
  lp         = -2.4 - 0.04 * round(rnorm(100, 45, 12)) + 0.06 * sample(c(10, 25, 50, 100), 100, replace = TRUE)
) |&gt;
  mutate(responder = rbinom(100, 1, plogis(lp)))

ex_5_3 &lt;- # your code here
summary(ex_5_3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">set.seed(13)
vax &lt;- tibble(
  subject_id = sprintf("S%03d", 1:100),
  age        = round(rnorm(100, 45, 12)),
  dose_mg    = sample(c(10, 25, 50, 100), 100, replace = TRUE),
  lp         = -2.4 - 0.04 * round(rnorm(100, 45, 12)) + 0.06 * sample(c(10, 25, 50, 100), 100, replace = TRUE)
) |&gt;
  mutate(responder = rbinom(100, 1, plogis(lp)))

ex_5_3 &lt;- glm(responder ~ age + dose_mg, data = vax, family = binomial)
summary(ex_5_3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <a class="auto-link" href="Logistic-Regression-With-R.html" title="Logistic Regression with R">Logistic regression</a> models the log odds of a binary outcome; <code>exp(coef)</code> converts a coefficient to an odds ratio per unit increase in the covariate. Here each additional milligram of dose multiplies the odds of seroconversion by <code>exp(0.059) = 1.06</code>, holding age fixed; each additional year of age divides them by <code>exp(0.043) = 1.04</code>. Always report odds ratios with 95 percent CI (<code>exp(confint(ex_5_3))</code>) and the deviance drop versus a null model as a global fit summary. For prediction calibration, use <code>pROC::roc()</code>.</p>
</details>
</section>
<h2>Section 6. Power, reproducibility, and reporting (2 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="R-for-Biostatistics-Exercises-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: Compute required sample size per arm for a two sample t test</h3>
<p class="exercise-task"><strong>Task:</strong> A protocol writer is sizing a Phase II trial to detect a mean difference of 8 mg/dL in LDL between drug and placebo, given a within group SD of 12, alpha 0.05 two sided, and power 0.80. Use <code>power.t.test(delta = 8, sd = 12, sig.level = 0.05, power = 0.80)</code> and save the htest like object to <code>ex_6_1</code>. Read <code>ex_6_1$n</code> for the per arm required size.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>     Two-sample t test power calculation 

              n = 36.3058
          delta = 8
             sd = 12
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Solving for <a class="auto-link" href="AB-Testing-Interview-Cases.html" title="A/B Testing Interview Cases: 20 Solved in R">sample size</a> means fixing the effect, the spread, the alpha, and the target power, then letting the count fall out.</p><p>Call <code>power.t.test()</code> with <code>delta = 8</code>, <code>sd = 12</code>, <code>sig.level = 0.05</code>, and <code>power = 0.80</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- power.t.test(delta = 8, sd = 12, sig.level = 0.05, power = 0.80)
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Sample size is driven by the standardised effect size <code>delta / sd = 0.67</code>, the alpha, and the target power. The function returns 36.3 per arm, so the protocol rounds up to 37 per arm and adds a dropout inflation factor (e.g. divide by 1 minus expected dropout rate). For unequal arms, switch to <code>power.t.test</code> with <code>n = NULL</code> and solve over a grid, or use the <code>pwr</code> package which exposes <code>pwr.t2n.test()</code> for unbalanced designs. Always run a sensitivity sweep across plausible deltas before locking the protocol.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="R-for-Biostatistics-Exercises-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Apply Benjamini Hochberg FDR correction to a vector of p values</h3>
<p class="exercise-task"><strong>Task:</strong> A genomics team ran 12 contrasts and produced raw p values. Because the family wise error rate would be brutal at this scale, the analysis plan calls for Benjamini Hochberg FDR control at q = 0.05. Apply <code>p.adjust(method = "BH")</code> to the inline <code>p_raw</code> vector below and return a tibble sorted ascending by <code>q_value</code> with columns <code>contrast</code>, <code>p_value</code>, <code>q_value</code>. Save to <code>ex_6_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 12 × 3
   contrast p_value q_value
   &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;
 1 C03       0.0001  0.0012
 2 C09       0.0008  0.0048
 3 C07       0.003   0.012 
 4 C01       0.009   0.027 
 5 C11       0.015   0.036 
 6 C10       0.04    0.08  
 7 C05       0.072   0.123 
 8 C08       0.18    0.27  
 9 C02       0.31    0.413 
10 C06       0.42    0.504 
11 C04       0.55    0.6   
12 C12       0.61    0.61
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Many simultaneous tests inflate false positives, so each raw p value needs rescaling for the whole family.</p><p>Build a <code>tibble()</code> from the names and values of <code>p_raw</code>, add a column from <code>p.adjust(p_raw, method = "BH")</code>, then <code>arrange()</code> by it.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">p_raw &lt;- c(C01 = 0.009, C02 = 0.31, C03 = 0.0001, C04 = 0.55, C05 = 0.072,
           C06 = 0.42,  C07 = 0.003, C08 = 0.18,   C09 = 0.0008, C10 = 0.04,
           C11 = 0.015, C12 = 0.61)

ex_6_2 &lt;- # your code here
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">p_raw &lt;- c(C01 = 0.009, C02 = 0.31, C03 = 0.0001, C04 = 0.55, C05 = 0.072,
           C06 = 0.42,  C07 = 0.003, C08 = 0.18,   C09 = 0.0008, C10 = 0.04,
           C11 = 0.015, C12 = 0.61)

ex_6_2 &lt;- tibble(
  contrast = names(p_raw),
  p_value  = unname(p_raw),
  q_value  = p.adjust(p_raw, method = "BH")
) |&gt;
  arrange(q_value)

ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Benjamini Hochberg controls the expected proportion of false discoveries among rejected hypotheses (FDR), which is a much friendlier criterion than family wise error rate when you are screening many contrasts and can tolerate a few false positives. For each rank <code>i</code>, BH compares <code>p[i]</code> against <code>i / m * q</code>; the largest <code>i</code> that satisfies the <a class="auto-link" href="R-Comparison-Operators-in-R.html" title="R Comparison Operators: ==, !=, &lt;, &gt;, &lt;=, &gt;= Guide">inequality</a> defines the cut, and everything at or below it is declared significant. Bonferroni (<code>method = "bonferroni"</code>) is strict but loses power; BH is the default for omics, GWAS, and most modern multiplicity adjustments.</p>
</details>
</section>
<h2>What to do next</h2>
<ul>
<li><a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>: drill into <a class="auto-link" href="Linear-Regression-Assumptions-in-R.html" title="Linear Regression Assumptions in R: Test All 5 and Know What to Do When They Fail">regression diagnostics</a>, transformations, and effect sizes.</li>
<li>Statistical Tests Exercises in R: broaden the <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">hypothesis testing</a> toolkit with one and two sample classics.</li>
<li><a href="EDA-Exercises-in-R.html">EDA Exercises in R</a>: the cleaning and visual triage that should run before every model fit.</li>
<li><a href="R-for-Data-Science-Exercises.html">R for Data Science Exercises</a>: tidyverse pipelines that scale these clinical workflows.</li>
</ul>

{% endraw %}