---
title: "Sports Analytics R Exercises: 20 Real-World Practice Problems"
description: "Sports analytics R exercises: box scores, ELO, Pythagorean wins, win probability, scouting workflows. 20 hands-on problems with hidden solutions."
keywords: "sports analytics R exercises, ELO rating R, Pythagorean expectation R, win probability R, scouting R, NBA analytics R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "sports analytics r exercises|elo rating in r|pythagorean expectation|win probability in r|player efficiency r"
auto_link_case_sensitive: false
sidebar_title: "R for Sports Analytics"
sidebar_order: "148"
fr_parent: "R-Tutorial.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>Sports Analytics R Exercises: 20 Real-World Practice Problems</h1>

<p class="lead">Twenty practice problems that reproduce the daily work of an NBA analytics staffer or a club's performance group: cleaning player-game logs, computing ELO updates, fitting win probability models, and building scouting boards. Solutions are hidden behind toggles so you can attempt each problem first.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="55" data-exercises="20" data-xp="300"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(dplyr)
library(tidyr)
library(tibble)
library(purrr)
library(stringr)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Box scores and player game logs (3 problems)</h2>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-1-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Compute per-game averages from a player game log</h3>

<p class="exercise-task"><strong>Task:</strong> The analytics staff received a 10-game log for a guard and needs a quick season-style summary card for tomorrow's coaches' meeting. Using the inline tibble below, compute the mean points, rebounds, and assists per game (round to one decimal) and save the three-column result to <code>ex_1_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 1 x 3
#&gt;     ppg   rpg   apg
#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1  21.4   4.1   6.7</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Collapse the ten game rows into a single summary row, taking the average of each stat.</p><p>Use <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summarise()</a> with <a class="auto-link" href="Descriptive-Statistics-in-R.html" title="Descriptive Statistics in R: The 8 Numbers That Tell You What Your Data Is Doing">mean()</a> wrapped in round(..., 1), naming the output columns ppg, rpg, apg.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">player_log &lt;- tibble(
  game = 1:10,
  pts  = c(28, 19, 22, 31, 17, 20, 25, 14, 23, 15),
  reb  = c( 5,  3,  4,  6,  2,  5,  4,  3,  6,  3),
  ast  = c( 8,  6,  9,  4,  7,  6,  8,  5,  9,  5)
)

ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">player_log &lt;- tibble(
  game = 1:10,
  pts  = c(28, 19, 22, 31, 17, 20, 25, 14, 23, 15),
  reb  = c( 5,  3,  4,  6,  2,  5,  4,  3,  6,  3),
  ast  = c( 8,  6,  9,  4,  7,  6,  8,  5,  9,  5)
)

ex_1_1 &lt;- player_log |&gt;
  summarise(
    ppg = round(mean(pts), 1),
    rpg = round(mean(reb), 1),
    apg = round(mean(ast), 1)
  )
ex_1_1
#&gt; # A tibble: 1 x 3
#&gt;     ppg   rpg   apg
#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1  21.4   4.1   6.7</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>summarise()</code> collapses the per-game rows into a single row, and naming each output column explicitly produces the same shape a scout would expect on a one-pager. If you forget <code>round()</code>, the output looks busier than it needs to. For a multi-stat audit on many columns, <code>summarise(across(c(pts, reb, ast), mean))</code> is the scalable form.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-1-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.2: Flag double-double games for a player</h3>

<p class="exercise-task"><strong>Task:</strong> A double-double is a game with at least 10 in two of points, rebounds, assists. The coaching staff wants every double-double game flagged in the log so they can compare a player's contract incentives. Add a logical <code>double_double</code> column to <code>player_log</code> from Exercise 1.1 and save the augmented tibble to <code>ex_1_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 10 x 5
#&gt;     game   pts   reb   ast double_double
#&gt;    &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;
#&gt;  1     1    28     5     8 TRUE
#&gt;  2     2    19     3     6 FALSE
#&gt;  3     3    22     4     9 FALSE
#&gt;  4     4    31     6     4 FALSE
#&gt;  5     5    17     2     7 FALSE
#&gt;  6     6    20     5     6 FALSE
#&gt;  7     7    25     4     8 FALSE
#&gt;  8     8    14     3     5 FALSE
#&gt;  9     9    23     6     9 FALSE
#&gt; 10    10    15     3     5 FALSE</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>For each game, count how many of the three stat categories cleared 10, then check whether that count reached two.</p><p>In <a class="auto-link" href="dplyr-mutate-rename.html" title="dplyr mutate() and rename(): Create & Modify Columns (8 Examples)">mutate()</a>, use rowSums(across(c(pts, reb, ast), ~ .x >= 10)) >= 2 to build the logical column.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- player_log |&gt;
  # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- player_log |&gt;
  mutate(
    double_double = (rowSums(across(c(pts, reb, ast), ~ .x &gt;= 10)) &gt;= 2)
  )
ex_1_2
#&gt; # A tibble: 10 x 5
#&gt;     game   pts   reb   ast double_double
#&gt;    &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;
#&gt;  1     1    28     5     8 TRUE
#&gt;  2     2    19     3     6 FALSE
#&gt;  3     3    22     4     9 FALSE
#&gt;  4     4    31     6     4 FALSE
#&gt;  5     5    17     2     7 FALSE
#&gt;  6     6    20     5     6 FALSE
#&gt;  7     7    25     4     8 FALSE
#&gt;  8     8    14     3     5 FALSE
#&gt;  9     9    23     6     9 FALSE
#&gt; 10    10    15     3     5 FALSE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>across()</code> builds a matrix of logical TRUE/FALSE flags and <code>rowSums()</code> counts how many stat categories cleared 10. Asking <code>&gt;= 2</code> matches the textbook double-double definition. A common mistake is <code>pts &gt;= 10 &amp; reb &gt;= 10</code> which only flags pts-and-reb pairs and misses pts-and-ast or reb-and-ast doubles, which is what tripped up this player's recent agent during negotiations.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-1-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 1.3: Compute True Shooting percentage by player</h3>

<p class="exercise-task"><strong>Task:</strong> True Shooting (TS%) measures scoring efficiency accounting for threes and free throws. The formula is <code>pts / (2 * (fga + 0.44 * fta))</code>. Given the four-player season tibble below, compute TS% to three decimals for each player and save the result sorted descending to <code>ex_1_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 5
#&gt;   player    pts   fga   fta    ts
#&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 Curry    1980  1400   320 0.638
#&gt; 2 Booker   1820  1340   380 0.609
#&gt; 3 LeBron   1620  1180   360 0.602
#&gt; 4 Russell  1490  1290   210 0.541</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Apply the efficiency formula to each player row, then order the table so the best player appears first.</p><p>Use mutate(ts = round(pts / (2 <em> (fga + 0.44 </em> fta)), 3)) followed by arrange(desc(ts)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">season &lt;- tribble(
  ~player,   ~pts, ~fga, ~fta,
  &quot;Curry&quot;,   1980, 1400,  320,
  &quot;Booker&quot;,  1820, 1340,  380,
  &quot;LeBron&quot;,  1620, 1180,  360,
  &quot;Russell&quot;, 1490, 1290,  210
)

ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">season &lt;- tribble(
  ~player,   ~pts, ~fga, ~fta,
  &quot;Curry&quot;,   1980, 1400,  320,
  &quot;Booker&quot;,  1820, 1340,  380,
  &quot;LeBron&quot;,  1620, 1180,  360,
  &quot;Russell&quot;, 1490, 1290,  210
)

ex_1_3 &lt;- season |&gt;
  mutate(ts = round(pts / (2 * (fga + 0.44 * fta)), 3)) |&gt;
  arrange(desc(ts))
ex_1_3
#&gt; # A tibble: 4 x 5
#&gt;   player    pts   fga   fta    ts
#&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 Curry    1980  1400   320 0.638
#&gt; 2 Booker   1820  1340   380 0.609
#&gt; 3 LeBron   1620  1180   360 0.602
#&gt; 4 Russell  1490  1290   210 0.541</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> TS% is a single number that beats raw FG% because it gives credit for three-pointers and free throws, which is why front offices use it for shot-creator evaluation. The 0.44 multiplier estimates how many possessions a typical free-throw trip costs (and-ones, technical FTs slightly distort the constant but 0.44 is the league convention). Always round before arrange so ties resolve by stable ordering.</p>

</details>

</section>

<h2>Section 2. Team standings and head-to-head records (4 problems)</h2>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-2-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 2.1: Build a standings table from game results</h3>

<p class="exercise-task"><strong>Task:</strong> A small five-team league played the inline schedule below. Build a standings tibble with columns <code>team</code>, <code>wins</code>, <code>losses</code>, <code>win_pct</code> (rounded to three decimals), sorted by <code>win_pct</code> descending. Tied teams may appear in any order. Save the standings to <code>ex_2_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 4
#&gt;   team   wins losses win_pct
#&gt;   &lt;chr&gt; &lt;int&gt;  &lt;int&gt;   &lt;dbl&gt;
#&gt; 1 A         3      1   0.75
#&gt; 2 C         3      1   0.75
#&gt; 3 D         2      2   0.5
#&gt; 4 B         1      3   0.25
#&gt; 5 E         1      3   0.25</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Each game row holds two teams, so reshape into one row per team per game before counting outcomes.</p><p>Use <a class="auto-link" href="dplyr-bind_rows-in-R.html" title="dplyr bind_rows() and bind_cols() in R: Combine Tables">bind_rows()</a> on a home slice and an away slice, then group_by(team) and summarise() wins and losses; arrange(desc(win_pct)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">games &lt;- tribble(
  ~home, ~away, ~home_pts, ~away_pts,
  &quot;A&quot;,&quot;B&quot;, 102,  98,
  &quot;C&quot;,&quot;D&quot;, 110, 105,
  &quot;A&quot;,&quot;C&quot;,  92, 101,
  &quot;B&quot;,&quot;D&quot;,  88,  95,
  &quot;E&quot;,&quot;A&quot;,  89, 104,
  &quot;D&quot;,&quot;E&quot;, 100,  91,
  &quot;B&quot;,&quot;C&quot;,  82,  90,
  &quot;E&quot;,&quot;B&quot;,  99,  92,
  &quot;C&quot;,&quot;E&quot;, 105,  95,
  &quot;A&quot;,&quot;D&quot;, 108, 100
)

ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">games &lt;- tribble(
  ~home, ~away, ~home_pts, ~away_pts,
  &quot;A&quot;,&quot;B&quot;, 102,  98,
  &quot;C&quot;,&quot;D&quot;, 110, 105,
  &quot;A&quot;,&quot;C&quot;,  92, 101,
  &quot;B&quot;,&quot;D&quot;,  88,  95,
  &quot;E&quot;,&quot;A&quot;,  89, 104,
  &quot;D&quot;,&quot;E&quot;, 100,  91,
  &quot;B&quot;,&quot;C&quot;,  82,  90,
  &quot;E&quot;,&quot;B&quot;,  99,  92,
  &quot;C&quot;,&quot;E&quot;, 105,  95,
  &quot;A&quot;,&quot;D&quot;, 108, 100
)

long &lt;- bind_rows(
  games |&gt; transmute(team = home, win = home_pts &gt; away_pts),
  games |&gt; transmute(team = away, win = away_pts &gt; home_pts)
)

ex_2_1 &lt;- long |&gt;
  group_by(team) |&gt;
  summarise(wins = sum(win), losses = sum(!win), .groups = &quot;drop&quot;) |&gt;
  mutate(win_pct = round(wins / (wins + losses), 3)) |&gt;
  arrange(desc(win_pct))
ex_2_1
#&gt; # A tibble: 5 x 4
#&gt;   team   wins losses win_pct
#&gt;   &lt;chr&gt; &lt;int&gt;  &lt;int&gt;   &lt;dbl&gt;
#&gt; 1 A         3      1   0.75
#&gt; 2 C         3      1   0.75
#&gt; 3 D         2      2   0.5
#&gt; 4 B         1      3   0.25
#&gt; 5 E         1      3   0.25</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Game logs naturally store two teams per row, so a tidy standings calc almost always unpivots into a long one-row-per-team-per-game table first. <code>bind_rows()</code> of the home and away slices gives the cleanest unpivot here. Skipping this step and trying to sum from the wide schema usually means writing the same logic twice and double-counting ties on the boundary games.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-2-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: Sort standings using point differential as a tiebreaker</h3>

<p class="exercise-task"><strong>Task:</strong> Extending Exercise 2.1, two teams (A and C) finished 3-1. The league's tiebreaker rule is total point differential across all games (points scored minus points allowed). Compute <code>point_diff</code> per team and re-sort the standings by <code>win_pct</code> descending, then <code>point_diff</code> descending. Save to <code>ex_2_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 5
#&gt;   team   wins losses win_pct point_diff
#&gt;   &lt;chr&gt; &lt;int&gt;  &lt;int&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 C         3      1   0.75          23
#&gt; 2 A         3      1   0.75          20
#&gt; 3 D         2      2   0.5            2
#&gt; 4 E         1      3   0.25         -16
#&gt; 5 B         1      3   0.25         -29</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Carry points scored and points allowed per team, total each, and sort on record first then on differential.</p><p>Compute summarise(point_diff = sum(pf) - sum(pa)) and use arrange(desc(win_pct), desc(point_diff)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">long_pts &lt;- bind_rows(
  games |&gt; transmute(team = home, pf = home_pts, pa = away_pts),
  games |&gt; transmute(team = away, pf = away_pts, pa = home_pts)
)

ex_2_2 &lt;- long_pts |&gt;
  group_by(team) |&gt;
  summarise(
    wins       = sum(pf &gt; pa),
    losses     = sum(pf &lt; pa),
    point_diff = sum(pf) - sum(pa),
    .groups = &quot;drop&quot;
  ) |&gt;
  mutate(win_pct = round(wins / (wins + losses), 3)) |&gt;
  arrange(desc(win_pct), desc(point_diff)) |&gt;
  select(team, wins, losses, win_pct, point_diff)
ex_2_2
#&gt; # A tibble: 5 x 5
#&gt;   team   wins losses win_pct point_diff
#&gt;   &lt;chr&gt; &lt;int&gt;  &lt;int&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 C         3      1   0.75          23
#&gt; 2 A         3      1   0.75          20
#&gt; 3 D         2      2   0.5            2
#&gt; 4 E         1      3   0.25         -16
#&gt; 5 B         1      3   0.25         -29</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Sorting by two keys with <code>arrange(desc(win_pct), desc(point_diff))</code> mirrors the bylaws of nearly every league: primary record, secondary differential. Note that we recompute the long table to carry both <code>pf</code> and <code>pa</code> columns; chaining off the result of 2.1 would have dropped the raw scores. Real tiebreaker chains can go five keys deep (head-to-head, division record, conference record).</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-2-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.3: Compute home and road splits for each team</h3>

<p class="exercise-task"><strong>Task:</strong> Coaching staff want to know which teams travel poorly. From the <code>games</code> schedule, compute <code>home_win_pct</code> and <code>road_win_pct</code> for every team to three decimals, then add a <code>split_gap = home_win_pct - road_win_pct</code> column and sort by <code>split_gap</code> descending. Save to <code>ex_2_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 4
#&gt;   team  home_win_pct road_win_pct split_gap
#&gt;   &lt;chr&gt;        &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 A            1            0.5       0.5
#&gt; 2 C            1            0.5       0.5
#&gt; 3 D            0.5          0.5       0
#&gt; 4 B            0            0.5      -0.5
#&gt; 5 E            0.5          0        -0.5</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Compute the win rate for home games and for road games separately, then combine the two results per team.</p><p>Use group_by(team = home) and group_by(team = away) with mean(), then <a class="auto-link" href="dplyr-joins-in-R.html" title="dplyr Joins in R: left_join, inner_join, full_join">full_join()</a> the two by team.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">home &lt;- games |&gt;
  group_by(team = home) |&gt;
  summarise(home_win_pct = round(mean(home_pts &gt; away_pts), 3), .groups = &quot;drop&quot;)
road &lt;- games |&gt;
  group_by(team = away) |&gt;
  summarise(road_win_pct = round(mean(away_pts &gt; home_pts), 3), .groups = &quot;drop&quot;)

ex_2_3 &lt;- home |&gt;
  full_join(road, by = &quot;team&quot;) |&gt;
  mutate(split_gap = home_win_pct - road_win_pct) |&gt;
  arrange(desc(split_gap))
ex_2_3
#&gt; # A tibble: 5 x 4
#&gt;   team  home_win_pct road_win_pct split_gap
#&gt;   &lt;chr&gt;        &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 A            1            0.5       0.5
#&gt; 2 C            1            0.5       0.5
#&gt; 3 D            0.5          0.5       0
#&gt; 4 B            0            0.5      -0.5
#&gt; 5 E            0.5          0        -0.5</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Home-court advantage is real (roughly +3 points in the NBA, more in college and European football) so isolating it lets staff target road-trip prep. The <code>full_join()</code> is defensive: if a team appears only on the home or only on the away side of the schedule, an <a class="auto-link" href="dplyr-inner_join-in-R.html" title="dplyr inner_join() in R: Keep Only Matched Rows">inner join</a> would silently drop it. For a real schedule you would also report game counts to flag small-sample splits.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-2-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 2.4: Build a head-to-head record matrix between all teams</h3>

<p class="exercise-task"><strong>Task:</strong> The GM wants a head-to-head matrix where row = team, column = opponent, cell = wins for the row team in matchups against the column team. Diagonal is <code>NA</code>. Build the 5x5 matrix from <code>games</code> and save the result as a tibble (with <code>team</code> as the first column) to <code>ex_2_4</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 6
#&gt;   team      A     B     C     D     E
#&gt;   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1 A        NA     1     0     1     1
#&gt; 2 B         0    NA     0     0     1
#&gt; 3 C         1     1    NA     1     1
#&gt; 4 D         0     1     0    NA     1
#&gt; 5 E         0     0     0     0    NA</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Tally wins for every team-opponent pair, then reshape that long table into a wide grid with opponents as columns.</p><p>Use group_by(team, opp) with summarise(wins = sum(win)), then <a class="auto-link" href="tidyr-Pivot-Exercises-in-R.html" title="tidyr Pivot Exercises in R: 25 Practice Problems">pivot_wider</a>(names_from = opp, values_from = wins) and set the diagonal to NA.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">long &lt;- bind_rows(
  games |&gt; transmute(team = home, opp = away, win = home_pts &gt; away_pts),
  games |&gt; transmute(team = away, opp = home, win = away_pts &gt; home_pts)
)

ex_2_4 &lt;- long |&gt;
  group_by(team, opp) |&gt;
  summarise(wins = sum(win), .groups = &quot;drop&quot;) |&gt;
  pivot_wider(names_from = opp, values_from = wins) |&gt;
  arrange(team) |&gt;
  mutate(across(-team, ~ replace(.x, team == cur_column(), NA_integer_)))
ex_2_4
#&gt; # A tibble: 5 x 6
#&gt;   team      A     B     C     D     E
#&gt;   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1 A        NA     1     0     1     1
#&gt; 2 B         0    NA     0     0     1
#&gt; 3 C         1     1    NA     1     1
#&gt; 4 D         0     1     0    NA     1
#&gt; 5 E         0     0     0     0    NA</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Head-to-head matrices are the canonical shape for playoff tiebreak displays. The pattern is: long-tidy first, then <code>pivot_wider()</code> for presentation. The trailing <code>mutate(across(...))</code> sets the diagonal to NA so the matrix reads correctly. If two teams never met (rare in a round-robin, common in early-season cuts), <code>pivot_wider()</code> would emit NA there too, which is the right behavior.</p>

</details>

</section>

<h2>Section 3. Rating systems and power rankings (4 problems)</h2>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-3-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.1: Pythagorean win expectation across teams</h3>

<p class="exercise-task"><strong>Task:</strong> Bill James's Pythagorean expectation predicts win% from points-for and points-against using the formula <code>pf^exp / (pf^exp + pa^exp)</code>. The basketball-fitted exponent is 13.91. Compute Pythagorean win% for the four-team season tibble below (round to three decimals), and save sorted descending to <code>ex_3_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 4
#&gt;   team       pf    pa pythag_win_pct
#&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;
#&gt; 1 Celtics  9200  8400          0.808
#&gt; 2 Heat     8950  8600          0.659
#&gt; 3 Knicks   8700  8500          0.589
#&gt; 4 Pistons  8300  8900          0.197</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Apply the points-based win-expectation formula to each team row, then order the result best-first.</p><p>In mutate(), compute pf^13.91 / (pf^13.91 + pa^13.91) wrapped in round(..., 3), then arrange(desc(...)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">teams &lt;- tribble(
  ~team,     ~pf,  ~pa,
  &quot;Celtics&quot;, 9200, 8400,
  &quot;Heat&quot;,    8950, 8600,
  &quot;Knicks&quot;,  8700, 8500,
  &quot;Pistons&quot;, 8300, 8900
)

ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">teams &lt;- tribble(
  ~team,     ~pf,  ~pa,
  &quot;Celtics&quot;, 9200, 8400,
  &quot;Heat&quot;,    8950, 8600,
  &quot;Knicks&quot;,  8700, 8500,
  &quot;Pistons&quot;, 8300, 8900
)

exp_basketball &lt;- 13.91
ex_3_1 &lt;- teams |&gt;
  mutate(pythag_win_pct = round(
    pf^exp_basketball / (pf^exp_basketball + pa^exp_basketball), 3)) |&gt;
  arrange(desc(pythag_win_pct))
ex_3_1
#&gt; # A tibble: 4 x 4
#&gt;   team       pf    pa pythag_win_pct
#&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;
#&gt; 1 Celtics  9200  8400          0.808
#&gt; 2 Heat     8950  8600          0.659
#&gt; 3 Knicks   8700  8500          0.589
#&gt; 4 Pistons  8300  8900          0.197</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Pythagorean expectation is the cleanest one-line power rating in sports analytics: it underrates teams with extreme garbage-time stats but is robust to schedule quirks. The exponent varies by sport (baseball: ~1.83, NFL: ~2.37, NBA: ~13.91 to ~16). When actual wins lag the Pythagorean estimate by 5+, the team is usually unlucky in close games and likely to regress positively next year.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-3-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.2: Update two team ELO ratings after a single game</h3>

<p class="exercise-task"><strong>Task:</strong> ELO ratings update after every game using <code>R_new = R_old + K * (actual - expected)</code>, where <code>expected = 1 / (1 + 10^((R_opp - R_self)/400))</code> and <code>K = 20</code> is the standard basketball constant. Team A (rating 1500) beat Team B (rating 1600) at home. Compute both updated ratings (round to one decimal) and save the result as a two-row tibble to <code>ex_3_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 3
#&gt;   team  rating_before rating_after
#&gt;   &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;
#&gt; 1 A              1500        1513.
#&gt; 2 B              1600        1587.</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Derive each team's expected score from the rating gap, then nudge the ratings by the difference between actual and expected outcomes.</p><p>Compute expected = 1 / (1 + 10^((R_opp - R_self)/400)), apply R + K * (actual - expected) with K = 20, and assemble a two-row tibble().</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">R_a &lt;- 1500; R_b &lt;- 1600; K &lt;- 20
exp_a &lt;- 1 / (1 + 10^((R_b - R_a) / 400))
exp_b &lt;- 1 - exp_a

new_a &lt;- R_a + K * (1 - exp_a)
new_b &lt;- R_b + K * (0 - exp_b)

ex_3_2 &lt;- tibble(
  team           = c(&quot;A&quot;, &quot;B&quot;),
  rating_before  = c(R_a, R_b),
  rating_after   = round(c(new_a, new_b), 1)
)
ex_3_2
#&gt; # A tibble: 2 x 3
#&gt;   team  rating_before rating_after
#&gt;   &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;
#&gt; 1 A              1500        1513.
#&gt; 2 B              1600        1587.</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Expected score follows a logistic curve on rating difference scaled by 400, the convention from chess. Because Team A was the underdog, beating Team B yields a bigger swing than Team B would have gained from a routine win. K controls volatility: higher K (e.g. 32) tracks form changes faster but is noisier; FiveThirtyEight uses ~20 for NBA. ELO is zero-sum game-by-game, which is why the two deltas have equal magnitude.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-3-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.3: Walk ELO ratings through a full mini-season</h3>

<p class="exercise-task"><strong>Task:</strong> Given the 10 games from Exercise 2.1, walk every team's ELO rating through the season starting at 1500 with <code>K = 20</code>. Return a tibble of final ratings sorted descending and save to <code>ex_3_3</code>. Use a <code>for</code> loop or <code>purrr::reduce()</code>; ignore home-court bonus for simplicity.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 2
#&gt;   team  final_elo
#&gt;   &lt;chr&gt;     &lt;dbl&gt;
#&gt; 1 C         1530.
#&gt; 2 A         1518.
#&gt; 3 D         1500.
#&gt; 4 E         1483.
#&gt; 5 B         1469.</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Walk the schedule game by game, updating both teams' ratings after each result before moving to the next.</p><p>Loop with for (i in seq_len(nrow(games))) over a named ratings vector, updating each entry per iteration, then build a tibble() and arrange(desc(final_elo)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ratings &lt;- setNames(rep(1500, 5), c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;,&quot;E&quot;))
K &lt;- 20

for (i in seq_len(nrow(games))) {
  h &lt;- games$home[i]; a &lt;- games$away[i]
  r_h &lt;- ratings[h]; r_a &lt;- ratings[a]
  exp_h &lt;- 1 / (1 + 10^((r_a - r_h)/400))
  result_h &lt;- as.numeric(games$home_pts[i] &gt; games$away_pts[i])
  delta &lt;- K * (result_h - exp_h)
  ratings[h] &lt;- r_h + delta
  ratings[a] &lt;- r_a - delta
}

ex_3_3 &lt;- tibble(team = names(ratings), final_elo = round(unname(ratings), 1)) |&gt;
  arrange(desc(final_elo))
ex_3_3
#&gt; # A tibble: 5 x 2
#&gt;   team  final_elo
#&gt;   &lt;chr&gt;     &lt;dbl&gt;
#&gt; 1 C         1530.
#&gt; 2 A         1518.
#&gt; 3 D         1500.
#&gt; 4 E         1483.
#&gt; 5 B         1469.</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> End-to-end ELO is exactly the multi-step workflow analytics staff run nightly: load schedule, walk forward in date order, update ratings, post the leaderboard. Doing it in a <code>for</code> loop is fine for a few thousand games; for whole-league multi-decade walks you would vectorize the within-day delta or move to data.table for speed. Note that ELO sums are invariant: the league's mean rating stays at 1500.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-3-4" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.4: Compute Strength of Schedule for each team</h3>

<p class="exercise-task"><strong>Task:</strong> Strength of Schedule (SoS) is the mean opponent win percentage over the games a team has played. From the long version of <code>games</code> and the win percentages in Exercise 2.1, compute each team's SoS rounded to three decimals and save sorted descending to <code>ex_3_4</code>. Toughest schedule should appear first.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 2
#&gt;   team    sos
#&gt;   &lt;chr&gt; &lt;dbl&gt;
#&gt; 1 B     0.562
#&gt; 2 E     0.562
#&gt; 3 D     0.5
#&gt; 4 A     0.438
#&gt; 5 C     0.438</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Attach each opponent's win percentage to the schedule rows, then average those values within each team.</p><p>Use <a class="auto-link" href="R-Joins.html" title="R Joins With Visual Diagrams: Pick the Right Join Every Time">left_join()</a> with by = c("opp" = "team"), then group_by(team) and summarise(sos = round(mean(win_pct), 3)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
ex_3_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">win_pcts &lt;- ex_2_1 |&gt; select(team, win_pct)
schedule &lt;- bind_rows(
  games |&gt; transmute(team = home, opp = away),
  games |&gt; transmute(team = away, opp = home)
)

ex_3_4 &lt;- schedule |&gt;
  left_join(win_pcts, by = c(&quot;opp&quot; = &quot;team&quot;)) |&gt;
  group_by(team) |&gt;
  summarise(sos = round(mean(win_pct), 3), .groups = &quot;drop&quot;) |&gt;
  arrange(desc(sos))
ex_3_4
#&gt; # A tibble: 5 x 2
#&gt;   team    sos
#&gt;   &lt;chr&gt; &lt;dbl&gt;
#&gt; 1 B     0.562
#&gt; 2 E     0.562
#&gt; 3 D     0.5
#&gt; 4 A     0.438
#&gt; 5 C     0.438</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> SoS is the key adjustment for any naive standings comparison: an 8-2 team that beat only losing teams is materially weaker than a 7-3 team that ran the gauntlet of contenders. The join key flips on purpose (<code>opp = team</code>) so the win_pct attached is the opponent's, not the team's own. NCAA basketball uses a more elaborate SoS that recursively folds in opponents' opponents.</p>

</details>

</section>

<h2>Section 4. Win probability and play-by-play (3 problems)</h2>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-4-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.1: Count lead changes in a play-by-play stream</h3>

<p class="exercise-task"><strong>Task:</strong> A play-by-play stream emits a running <code>home_lead</code> value (positive when home leads, negative when road leads). The broadcast team wants to display "Lead changes: N" on screen at the end of the game. From the inline PBP vector below, count how many times the sign of <code>home_lead</code> flips (ignore zeros) and save the integer count to <code>ex_4_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; ex_4_1
#&gt; [1] 4</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p><a class="auto-link" href="Reduce-Filter-Map-in-R.html" title="Reduce(), Filter(), Map() in Base R: Functional Trifecta Explained">Reduce</a> each lead value to just its direction, drop the ties, and count how often the direction flips.</p><p>Apply sign() to the vector, keep only the non-zero entries, then use sum(diff(signs) != 0).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">home_lead &lt;- c(0, 2, 5, 7, 4, -1, -3, -2, 1, 4, 6, 3, -2, -5, -1, 2, 5, 8)

ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">home_lead &lt;- c(0, 2, 5, 7, 4, -1, -3, -2, 1, 4, 6, 3, -2, -5, -1, 2, 5, 8)

signs &lt;- sign(home_lead)
signs &lt;- signs[signs != 0]
ex_4_1 &lt;- sum(diff(signs) != 0)
ex_4_1
#&gt; [1] 4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>sign()</code> collapses any number to -1, 0, or 1, and <code>diff() != 0</code> flags every transition between consecutive non-zero values. Filtering out zeros first avoids counting a tie-then-recover as two changes; broadcasters typically treat a tied score as continuation of the prior lead. For a tibble of PBP rows, the same idea sits inside <code>mutate(lead_change = sign(home_lead) != lag(sign(home_lead)))</code>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-4-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 4.2: Fit a simple win probability logistic model</h3>

<p class="exercise-task"><strong>Task:</strong> The data team is calibrating a quick win-probability heuristic for late-game situations: probability of home win given current <code>margin</code> (home points minus road points) and <code>seconds_left</code>. Fit <code>glm(home_won ~ margin + seconds_left, family = binomial)</code> on the inline 100-row training tibble below, predict win probability at <code>margin = 4, seconds_left = 120</code>, round to three decimals, and save the scalar to <code>ex_4_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 0.876</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Fit a logistic regression of the win outcome on score margin and time remaining, then score one new game situation.</p><p>Call glm(home_won ~ margin + seconds_left, family = binomial), then predict(..., newdata = ..., type = "response").</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
n &lt;- 100
train &lt;- tibble(
  margin       = sample(-15:15, n, replace = TRUE),
  seconds_left = sample(0:600, n, replace = TRUE)
) |&gt;
  mutate(
    logit = 0.25 * margin - 0.001 * seconds_left,
    p     = 1 / (1 + exp(-logit)),
    home_won = rbinom(n, 1, p)
  )

ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
n &lt;- 100
train &lt;- tibble(
  margin       = sample(-15:15, n, replace = TRUE),
  seconds_left = sample(0:600, n, replace = TRUE)
) |&gt;
  mutate(
    logit = 0.25 * margin - 0.001 * seconds_left,
    p     = 1 / (1 + exp(-logit)),
    home_won = rbinom(n, 1, p)
  )

fit &lt;- glm(home_won ~ margin + seconds_left, data = train, family = binomial)
ex_4_2 &lt;- round(predict(fit, newdata = tibble(margin = 4, seconds_left = 120),
                        type = &quot;response&quot;), 3) |&gt; unname()
ex_4_2
#&gt; [1] 0.876</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A two-feature logistic model is the textbook starting point for in-game win probability, and serious production models (ESPN's WPA, Inpredictable) just add timeout count, possession indicator, and team-strength priors. <code>type = &quot;response&quot;</code> returns probabilities directly; omitting it gives <a class="auto-link" href="Logistic-Regression-in-R.html" title="Logistic Regression in R: From glm() to Odds Ratios, ROC, and AUC">log-odds</a>, which is the most common silent bug in dashboards. <code>unname()</code> strips the row label so the result is a clean scalar.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-4-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.3: Compute a rolling 5-possession momentum score</h3>

<p class="exercise-task"><strong>Task:</strong> A possession outcome stream encodes each possession as +pts for home, -pts for road (turnover = 0). The coaching staff wants a rolling sum of the last five possessions to drive a "momentum" indicator on the bench tablet. From the inline 20-possession vector, compute a length-20 <code>roll_5</code> vector with the trailing 5-possession sum (NA for the first four positions) and save to <code>ex_4_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] NA NA NA NA  4  3  7  4  3 -1  0  3  3  2  3 -2  3  3  3  4</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>From the fifth position onward, total the current value and the four before it, leaving the first four positions empty.</p><p>Pad with four NA_real_ values, then use sapply(5:n, function(i) sum(poss[(i-4):i])).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">poss &lt;- c(2, 0, -2, 2, 2, -1, 3, 0, -1, -1, 0, 2, 3, -2, 2, -2, 3, 0, 2, 3)

ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">poss &lt;- c(2, 0, -2, 2, 2, -1, 3, 0, -1, -1, 0, 2, 3, -2, 2, -2, 3, 0, 2, 3)

n &lt;- length(poss)
ex_4_3 &lt;- c(rep(NA_real_, 4), sapply(5:n, function(i) sum(poss[(i-4):i])))
ex_4_3
#&gt;  [1] NA NA NA NA  4  3  7  4  3 -1  0  3  3  2  3 -2  3  3  3  4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Trailing windows are the standard shape for "momentum" or "form" features because they survive ties and pauses without resetting. The pattern (NA-pad, then slide) is portable: replace <code>sum()</code> with <code>mean()</code> for an average, with <code>var()</code> for volatility. For long streams use <code>zoo::rollapply()</code> or <code>slider::slide_dbl()</code> for a vectorized version; the explicit <code>sapply</code> here is fine for live game lengths (a few hundred rows).</p>

</details>

</section>

<h2>Section 5. Player efficiency metrics (3 problems)</h2>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-5-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 5.1: Convert player stats to per-36-minute pace</h3>

<p class="exercise-task"><strong>Task:</strong> Per-36 stats normalize counting numbers to a common minutes denominator so bench players and starters compare cleanly. For each player in the inline tibble, compute <code>pts_per36</code>, <code>reb_per36</code>, <code>ast_per36</code> (each rounded to one decimal) using the formula <code>stat * 36 / mp</code>. Save the four-column result to <code>ex_5_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 4
#&gt;   player pts_per36 reb_per36 ast_per36
#&gt;   &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 A           28.8       8         5
#&gt; 2 B           21.2       4         6.4
#&gt; 3 C           36.7      11.4       1.7
#&gt; 4 D           18         3.6       3.8</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Rescale each counting stat onto a shared 36-minute denominator for every player.</p><p>Use <a class="auto-link" href="dplyr-transmute-in-R.html" title="dplyr transmute() in R: Mutate and Drop Old Columns">transmute()</a> with round(stat * 36 / mp, 1) for the pts, reb, and ast columns.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">roster &lt;- tribble(
  ~player, ~mp,  ~pts, ~reb, ~ast,
  &quot;A&quot;,     30,    24,    7,    5,   # role wing
  &quot;B&quot;,     34,    20,    4,    6,   # starting guard
  &quot;C&quot;,     21,    21.4,  6.65, 1,   # bench big
  &quot;D&quot;,     25,    12.5,  2.5,  2.6  # rookie wing
)

ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">roster &lt;- tribble(
  ~player, ~mp,  ~pts, ~reb, ~ast,
  &quot;A&quot;,     30,    24,    7,    5,
  &quot;B&quot;,     34,    20,    4,    6,
  &quot;C&quot;,     21,    21.4,  6.65, 1,
  &quot;D&quot;,     25,    12.5,  2.5,  2.6
)

ex_5_1 &lt;- roster |&gt;
  transmute(
    player,
    pts_per36 = round(pts * 36 / mp, 1),
    reb_per36 = round(reb * 36 / mp, 1),
    ast_per36 = round(ast * 36 / mp, 1)
  )
ex_5_1
#&gt; # A tibble: 4 x 4
#&gt;   player pts_per36 reb_per36 ast_per36
#&gt;   &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 A           28.8       8         5
#&gt; 2 B           21.2       4         6.4
#&gt; 3 C           36.7      11.4       1.7
#&gt; 4 D           18         3.6       3.8</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Per-36 inflates bench-player rate stats fairly because 21 mp at 21.4 pts is the same production rate as a 36 mp version at 36.7 pts. Per-100-possessions (often <code>pts * 100 / poss</code>) is the cleaner pace adjustment for teams that vary in tempo, but per-36 is the long-standing standard on Basketball-Reference player pages. Always carry minutes alongside per-36 so readers can sanity-check small samples.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-5-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.2: Compute Usage Rate for each player</h3>

<p class="exercise-task"><strong>Task:</strong> Usage Rate measures the percentage of team possessions that end with a player's shot attempt, free-throw trip, or turnover while they were on the floor. The simplified formula is <code>100 * (fga + 0.44 * fta + tov) * (team_mp / 5) / (mp * (team_fga + 0.44 * team_fta + team_tov))</code>. Team totals: <code>team_mp = 240</code>, <code>team_fga = 88</code>, <code>team_fta = 25</code>, <code>team_tov = 12</code>. Compute usage to one decimal per player and save sorted descending to <code>ex_5_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 5
#&gt;   player    mp   fga   fta usage
#&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 C         21    18     6  41.1
#&gt; 2 A         30    20     4  32.4
#&gt; 3 B         34    16     6  23.7
#&gt; 4 D         25    10     2  17</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Build each player's possession-ending events, then scale that against the team total and the player's minutes share.</p><p>In mutate(), compute player_poss = fga + 0.44 * fta + tov, apply the usage formula, then arrange(desc(usage)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">usage_input &lt;- tribble(
  ~player, ~mp, ~fga, ~fta, ~tov,
  &quot;A&quot;, 30, 20, 4, 3,
  &quot;B&quot;, 34, 16, 6, 2,
  &quot;C&quot;, 21, 18, 6, 3,
  &quot;D&quot;, 25, 10, 2, 2
)
team_mp &lt;- 240; team_fga &lt;- 88; team_fta &lt;- 25; team_tov &lt;- 12

ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">usage_input &lt;- tribble(
  ~player, ~mp, ~fga, ~fta, ~tov,
  &quot;A&quot;, 30, 20, 4, 3,
  &quot;B&quot;, 34, 16, 6, 2,
  &quot;C&quot;, 21, 18, 6, 3,
  &quot;D&quot;, 25, 10, 2, 2
)
team_mp &lt;- 240; team_fga &lt;- 88; team_fta &lt;- 25; team_tov &lt;- 12
team_poss &lt;- team_fga + 0.44 * team_fta + team_tov

ex_5_2 &lt;- usage_input |&gt;
  mutate(
    player_poss = fga + 0.44 * fta + tov,
    usage = round(100 * player_poss * (team_mp / 5) / (mp * team_poss), 1)
  ) |&gt;
  select(player, mp, fga, fta, usage) |&gt;
  arrange(desc(usage))
ex_5_2
#&gt; # A tibble: 4 x 5
#&gt;   player    mp   fga   fta usage
#&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 C         21    18     6  41.1
#&gt; 2 A         30    20     4  32.4
#&gt; 3 B         34    16     6  23.7
#&gt; 4 D         25    10     2  17</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Usage is one of the most-cited metrics in NBA front-office work because it cleanly separates volume from efficiency. The <code>team_mp / 5</code> factor accounts for the fact that team minutes are accumulated five-on-five; without it players who play limited minutes would show artificially low usage. Pairing usage with TS% from Exercise 1.3 produces the classic "volume vs efficiency" scouting quadrant.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-5-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.3: Aggregate shooting percentages by zone</h3>

<p class="exercise-task"><strong>Task:</strong> A scouting report needs FG% by court zone for a given player. From the inline shot log (one row per attempt), compute <code>attempts</code>, <code>makes</code>, and <code>fg_pct</code> (rounded to three decimals) per zone, sort by zone alphabetically, and save the result to <code>ex_5_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 4 x 4
#&gt;   zone        attempts makes fg_pct
#&gt;   &lt;chr&gt;          &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
#&gt; 1 corner_3           8     4   0.5
#&gt; 2 mid_range         12     5   0.417
#&gt; 3 paint             18    13   0.722
#&gt; 4 top_of_key_3      10     3   0.3</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Group the attempts by court zone and summarize the attempts, the makes, and the make rate for each.</p><p>Use group_by(zone) with summarise(attempts = n(), makes = sum(made), fg_pct = round(makes / attempts, 3)), then arrange(zone).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">shots &lt;- tibble(
  zone = c(rep(&quot;paint&quot;, 18), rep(&quot;mid_range&quot;, 12),
           rep(&quot;corner_3&quot;, 8), rep(&quot;top_of_key_3&quot;, 10)),
  made = c(rep(c(1,1,1,1,0), 3), 1,1,1,         # 13/18 paint
           rep(c(1,0,1,0), 3),                  # 5/12 mid-range, sums to 5
           1,1,1,1,0,0,0,0,                     # 4/8 corner 3
           1,0,0,1,0,1,0,0,0,0)                 # 3/10 top-of-key 3
)

ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">shots &lt;- tibble(
  zone = c(rep(&quot;paint&quot;, 18), rep(&quot;mid_range&quot;, 12),
           rep(&quot;corner_3&quot;, 8), rep(&quot;top_of_key_3&quot;, 10)),
  made = c(rep(c(1,1,1,1,0), 3), 1,1,1,
           rep(c(1,0,1,0), 3),
           1,1,1,1,0,0,0,0,
           1,0,0,1,0,1,0,0,0,0)
)

ex_5_3 &lt;- shots |&gt;
  group_by(zone) |&gt;
  summarise(attempts = n(), makes = sum(made),
            fg_pct = round(makes / attempts, 3), .groups = &quot;drop&quot;) |&gt;
  arrange(zone)
ex_5_3
#&gt; # A tibble: 4 x 4
#&gt;   zone        attempts makes fg_pct
#&gt;   &lt;chr&gt;          &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
#&gt; 1 corner_3           8     4   0.5
#&gt; 2 mid_range         12     5   0.417
#&gt; 3 paint             18    13   0.722
#&gt; 4 top_of_key_3      10     3   0.3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Zone-based shot charts are the bread and butter of opponent scouting; the corner three is shorter than other threes (22 feet vs 23'9") which is why league corner 3% sits 4-5 points above top-of-key 3%. Always present <code>attempts</code> alongside <code>fg_pct</code> so small-sample zones get appropriate skepticism. For production charts, layer this aggregation onto a hexbin spatial plot.</p>

</details>

</section>

<h2>Section 6. Scouting and decision workflows (3 problems)</h2>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-6-1" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.1: Rank free agents by a composite z-score</h3>

<p class="exercise-task"><strong>Task:</strong> The GM is choosing among five wings ahead of the draft. Build a composite ranking that z-scores each of <code>ppg</code>, <code>rpg</code>, <code>apg</code>, <code>ts</code> within the candidate pool, sums the four z-scores into <code>composite</code>, and sorts descending. Round z-scores and composite to two decimals. Save the final ranked tibble to <code>ex_6_1</code>. This is a multi-step workflow: standardize, sum, sort.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 6
#&gt;   player z_pts z_reb z_ast z_ts  composite
#&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 Smith   1.34  0.7   0.36 1.07       3.47
#&gt; 2 Allen   0.18  1.4  -0.6  0.21       1.19
#&gt; 3 Brown   0.18 -0.94  1.2 -1.07      -0.63
#&gt; 4 Davis  -0.59 -0.23 -0.96 0.85      -0.93
#&gt; 5 Evans  -1.11 -0.94 -0       -1.07  -3.12</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Standardize each stat within the candidate pool so different units compare, then add the standardized values into one ranking number.</p><p>Write a z-score helper (x - mean(x)) / sd(x), apply it per stat in mutate(), sum into composite, and arrange(desc(composite)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">free_agents &lt;- tribble(
  ~player, ~ppg, ~rpg, ~apg, ~ts,
  &quot;Smith&quot;, 23.0, 6.5, 4.5, 0.61,
  &quot;Allen&quot;, 18.0, 7.5, 3.0, 0.57,
  &quot;Brown&quot;, 18.0, 5.0, 5.5, 0.51,
  &quot;Davis&quot;, 14.7, 6.0, 2.5, 0.60,
  &quot;Evans&quot;, 12.5, 5.0, 4.0, 0.51
)

ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">free_agents &lt;- tribble(
  ~player, ~ppg, ~rpg, ~apg, ~ts,
  &quot;Smith&quot;, 23.0, 6.5, 4.5, 0.61,
  &quot;Allen&quot;, 18.0, 7.5, 3.0, 0.57,
  &quot;Brown&quot;, 18.0, 5.0, 5.5, 0.51,
  &quot;Davis&quot;, 14.7, 6.0, 2.5, 0.60,
  &quot;Evans&quot;, 12.5, 5.0, 4.0, 0.51
)

zscore &lt;- function(x) round((x - mean(x)) / sd(x), 2)

ex_6_1 &lt;- free_agents |&gt;
  mutate(
    z_pts = zscore(ppg),
    z_reb = zscore(rpg),
    z_ast = zscore(apg),
    z_ts  = zscore(ts),
    composite = round(z_pts + z_reb + z_ast + z_ts, 2)
  ) |&gt;
  select(player, z_pts, z_reb, z_ast, z_ts, composite) |&gt;
  arrange(desc(composite))
ex_6_1
#&gt; # A tibble: 5 x 6
#&gt;   player z_pts z_reb z_ast  z_ts composite
#&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 Smith   1.34  0.7   0.36  1.07      3.47
#&gt; 2 Allen   0.18  1.4  -0.6   0.21      1.19
#&gt; 3 Brown   0.18 -0.94  1.2  -1.07     -0.63
#&gt; 4 Davis  -0.59 -0.23 -0.96  0.85     -0.93
#&gt; 5 Evans  -1.11 -0.94 -0    -1.07     -3.12</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Composite z-scores are the workhorse of pre-draft and pre-FA shortlists because they normalize stats with different units (counting vs percentage) onto a common scale. A real scouting board would weight the four components rather than sum equally (TS often gets a 2x weight in modern front offices) and would mix in defensive metrics. The order-of-operations matters: z-score first, then sum, never the reverse.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-6-2" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.2: Build a matchup advantage matrix from positional efficiency</h3>

<p class="exercise-task"><strong>Task:</strong> A coaching staff has positional offensive efficiency (<code>off_eff</code>) and defensive efficiency (<code>def_eff</code>) for two teams across five lineup positions. Build a 5x5 matchup matrix where row = our position, column = their position, cell = <code>our_off_eff - their_def_eff</code>. A positive cell signals we have a scoring edge. Save the matrix as a long tibble with columns <code>our_pos</code>, <code>their_pos</code>, <code>edge</code> sorted by <code>edge</code> descending to <code>ex_6_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 25 x 3
#&gt;    our_pos their_pos  edge
#&gt;    &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;
#&gt;  1 SF      SG         15
#&gt;  2 SG      SG         13
#&gt;  3 SF      PG         12
#&gt;  4 PG      SG         11
#&gt;  5 SF      C          10
#&gt;  6 SG      PG         10
#&gt;  7 PF      SG         10
#&gt;  8 PG      PG          8
#&gt;  9 PG      C           8
#&gt; 10 SG      C           8
#&gt; ...
#&gt; # 15 more rows hidden</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Pair every one of our positions with every one of theirs, then subtract their defense from our offense.</p><p>Use expand_grid() on the two position vectors, left_join() each efficiency table, mutate(edge = off_eff - def_eff), and arrange(desc(edge)).</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ours &lt;- tibble(pos = c(&quot;PG&quot;,&quot;SG&quot;,&quot;PF&quot;,&quot;SF&quot;,&quot;C&quot;),
               off_eff = c(110, 112, 105, 115, 108))
theirs &lt;- tibble(pos = c(&quot;PG&quot;,&quot;SG&quot;,&quot;PF&quot;,&quot;SF&quot;,&quot;C&quot;),
                 def_eff = c(102, 99, 104, 101, 100))

ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ours &lt;- tibble(pos = c(&quot;PG&quot;,&quot;SG&quot;,&quot;PF&quot;,&quot;SF&quot;,&quot;C&quot;),
               off_eff = c(110, 112, 105, 115, 108))
theirs &lt;- tibble(pos = c(&quot;PG&quot;,&quot;SG&quot;,&quot;PF&quot;,&quot;SF&quot;,&quot;C&quot;),
                 def_eff = c(102, 99, 104, 101, 100))

ex_6_2 &lt;- expand_grid(our_pos = ours$pos, their_pos = theirs$pos) |&gt;
  left_join(ours,   by = c(&quot;our_pos&quot;   = &quot;pos&quot;)) |&gt;
  left_join(theirs, by = c(&quot;their_pos&quot; = &quot;pos&quot;)) |&gt;
  mutate(edge = off_eff - def_eff) |&gt;
  select(our_pos, their_pos, edge) |&gt;
  arrange(desc(edge))
head(ex_6_2, 10)
#&gt; # A tibble: 10 x 3
#&gt;    our_pos their_pos  edge
#&gt;    &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;
#&gt;  1 SF      SG         15
#&gt;  2 SG      SG         13
#&gt;  3 SF      PG         12
#&gt;  4 PG      SG         11
#&gt;  5 SF      C          10
#&gt;  6 SG      PG         10
#&gt;  7 PF      SG         10
#&gt;  8 PG      PG          8
#&gt;  9 PG      C           8
#&gt; 10 SG      C           8</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>expand_grid()</code> is the cleanest way to spell out a Cartesian join of two factor columns, which is exactly what a 5x5 matchup map needs. Joining each side on its native column adds the per-position efficiency values, and the subtraction produces an "edge" the coaching staff can read directly. In a real game plan the next step is to filter to the top three edges and target screens that engineer those matchups.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-for-Sports-Analytics-Exercises-ex-6-3" data-grade-mode="self-check" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.3: Flag players with elevated injury risk from rolling minutes load</h3>

<p class="exercise-task"><strong>Task:</strong> Sports science staff want a flag when a player's 5-game trailing minutes load exceeds 175 minutes (roughly 35 mpg over five). From the inline 12-game minutes log for three players, compute a <code>roll_5_mp</code> column and an <code>at_risk</code> logical (TRUE when <code>roll_5_mp &gt; 175</code>). Save the long tibble sorted by <code>player</code> and <code>game</code> to <code>ex_6_3</code>. This is a multi-step grouped rolling-window workflow.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 36 x 4
#&gt;    player  game minutes roll_5_mp
#&gt;    &lt;chr&gt;  &lt;int&gt;   &lt;dbl&gt;     &lt;dbl&gt;
#&gt;  1 A          1      32        NA
#&gt;  2 A          2      35        NA
#&gt;  3 A          3      30        NA
#&gt;  4 A          4      36        NA
#&gt;  5 A          5      40       173
#&gt;  6 A          6      38       179
#&gt;  7 A          7      33       177
#&gt;  8 A          8      36       183
#&gt;  9 A          9      35       182
#&gt; 10 A         10      37       179
#&gt; ...
#&gt; # 26 more rows hidden, plus `at_risk` column</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Compute the trailing five-game minutes total separately for each player, then flag totals above the threshold.</p><p>Call group_by(player) before the rolling window, then mutate() roll_5_mp as the NA-padded trailing sum and at_risk = roll_5_mp > 175.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">minutes &lt;- tibble(
  player = rep(c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;), each = 12),
  game   = rep(1:12, 3),
  minutes = c(
    32,35,30,36,40,38,33,36,35,37,38,29,
    24,26,28,22,30,27,29,25,31,28,26,24,
    36,38,40,39,38,37,41,42,38,36,37,39
  )
)

ex_6_3 &lt;- # your code here
ex_6_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">minutes &lt;- tibble(
  player = rep(c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;), each = 12),
  game   = rep(1:12, 3),
  minutes = c(
    32,35,30,36,40,38,33,36,35,37,38,29,
    24,26,28,22,30,27,29,25,31,28,26,24,
    36,38,40,39,38,37,41,42,38,36,37,39
  )
)

roll5 &lt;- function(x) {
  n &lt;- length(x)
  c(rep(NA_real_, 4), sapply(5:n, function(i) sum(x[(i-4):i])))
}

ex_6_3 &lt;- minutes |&gt;
  group_by(player) |&gt;
  arrange(game, .by_group = TRUE) |&gt;
  mutate(
    roll_5_mp = roll5(minutes),
    at_risk   = roll_5_mp &gt; 175
  ) |&gt;
  ungroup() |&gt;
  arrange(player, game)
head(ex_6_3, 12)
#&gt; # A tibble: 12 x 5
#&gt;    player  game minutes roll_5_mp at_risk
#&gt;    &lt;chr&gt;  &lt;int&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;
#&gt;  1 A          1      32        NA NA
#&gt;  2 A          2      35        NA NA
#&gt;  3 A          3      30        NA NA
#&gt;  4 A          4      36        NA NA
#&gt;  5 A          5      40       173 FALSE
#&gt;  6 A          6      38       179 TRUE
#&gt;  7 A          7      33       177 TRUE
#&gt;  8 A          8      36       183 TRUE
#&gt;  9 A          9      35       182 TRUE
#&gt; 10 A         10      37       179 TRUE
#&gt; 11 A         11      38       181 TRUE
#&gt; 12 A         12      29       175 FALSE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Rolling minutes load is the canonical workload-management feature in modern pro sports; teams pair it with sprint exposure from GPS vests and prior injury history to gate rotations. The key R idiom is <code>group_by(player)</code> before the rolling window, otherwise the trailing sum at player B's first game would wrongly include player A's last four. For production code prefer <code>slider::slide_index_dbl()</code> over hand-rolled sapply because it handles irregular game spacing.</p>

</details>

</section>

<h2>What to do next</h2>

<ul>

<li>Reinforce these techniques with <a href="dplyr-Exercises-in-R.html">dplyr exercises in R</a> for <a class="auto-link" href="dplyr-Group-By-Exercises-in-R.html" title="dplyr group_by Exercises in R: 25 Practice Problems">grouped summarise</a> and join patterns.</li>

<li>Move into deeper time-series analysis with <a href="Time-Series-Exercises-in-R.html">time-series exercises in R</a> for momentum and rolling-window features.</li>

<li>Practice the modeling layer using <a href="Logistic-Regression-Exercises-in-R.html">logistic regression exercises in R</a> to extend the win probability problem.</li>

<li>Sharpen visualization output for scouting reports with <a href="ggplot2-Exercises-in-R.html">ggplot2 exercises in R</a>.</li>

</ul>

{% endraw %}