---
title: "R Vectors Exercises: 18 Hands-On Problems with Worked Solutions"
description: "18 interactive R vector exercises with worked answers: creation, coercion, indexing, named vectors, recycling, NA handling, z-scoring, and binning."
keywords: "R vectors exercises, R vector practice problems, R indexing exercises, R recycling exercises, R named vector practice, R NA handling exercises"
mathjax: false
webr: true
curriculum_id: "E1.2"
post_type: "EX"
auto_link_terms: "R vectors exercises|R vector practice|R indexing exercises|R recycling exercises|named vector in R"
auto_link_case_sensitive: false
sidebar_section: "Practice Exercises"
sidebar_title: "R Vectors (18 problems)"
sidebar_order: "150"
fr_parent: "R-Vectors.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>R Vectors Exercises: 18 Hands-On Problems with Worked Solutions</h1>

<p class="lead">Eighteen runnable exercises covering the full vector workflow in R: creation, coercion, positive and <a class="auto-link" href="R-Subsetting.html" title="R Subsetting: One Definitive Rule for [], [[]], $, and @ — No More Guessing">logical indexing</a>, named lookups, vectorised arithmetic, recycling, NA handling, and real-world workflows like z-scoring and binning. Solutions are hidden until you click. Code blocks share state across the page, so variables defined early are available later.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="45" data-exercises="18" data-xp="270"></div>

<p>Vectors are the single most important data structure in R. Scalars are length-one vectors, <a class="auto-link" href="R-Data-Frames.html" title="R Data Frames: Every Operation You'll Need, With 10 Real Examples">data frame columns</a> are vectors, and almost every base function is vectorised. Working through these exercises in order builds the intuition you need for dplyr, <a class="auto-link" href="ggplot2-Tutorial-With-R.html" title="ggplot2 Short Tutorial">ggplot2</a>, and modelling code that follows.</p>

<p>The difficulty mix is roughly three Beginner warm-ups, eleven Intermediate problems that match the questions analysts hit on the job, and four Advanced workflows that combine three or four ideas at once. Run each block as you go.</p>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(stats)
set.seed(42)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. Creating and inspecting vectors (3 problems)</h2>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-1-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Build the same sequence four ways and verify equality</h3>

<p class="exercise-task"><strong>Task:</strong> Create the numeric sequence <code>1, 2, 3, ..., 10</code> four different ways: with <code>c()</code>, with the <code>:</code> shortcut, with <code>seq()</code>, and with <code>seq_len()</code>. Then use <code>identical()</code> to test which pairs are truly identical (values AND storage type). Save the four vectors to <code>ex_1_1</code> as a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> so the comparisons are easy to inspect.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $v1 -&gt; double:  1  2  3  4  5  6  7  8  9 10
#&gt; $v2 -&gt; integer: 1  2  3  4  5  6  7  8  9 10
#&gt; $v3 -&gt; double:  1  2  3  4  5  6  7  8  9 10
#&gt; $v4 -&gt; integer: 1  2  3  4  5  6  7  8  9 10
#&gt; identical(v1, v3) : TRUE   # both double
#&gt; identical(v2, v4) : TRUE   # both integer
#&gt; identical(v1, v2) : FALSE  # same values, different storage type</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Four construction routes can print the same numbers yet leave the vector with a different underlying storage type, so think about what "truly identical" should mean.</p><p>Build a named list using <code>c()</code>, <code>:</code>, <code>seq()</code>, and <code>seq_len()</code>, then compare pairs with <code>identical()</code> and inspect storage with <code>typeof()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- list(
  v1 = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  v2 = 1:10,
  v3 = seq(1, 10, by = 1),
  v4 = seq_len(10)
)

sapply(ex_1_1, typeof)
identical(ex_1_1$v1, ex_1_1$v3)
identical(ex_1_1$v2, ex_1_1$v4)
identical(ex_1_1$v1, ex_1_1$v2)
#&gt; [1] TRUE
#&gt; [1] TRUE
#&gt; [1] FALSE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>c(1, 2, ...)</code> and <code>seq()</code> produce double-precision vectors because the literals <code>1</code>, <code>2</code>, ... are doubles by default. The <code>:</code> operator and <code>seq_len()</code> produce <a class="auto-link" href="R-Vectors.html" title="R Vectors: The Foundation of Everything in R (Master This First)">integer vectors</a>. The values print identically but <code>identical()</code> checks storage type as well as numerical equality, which is why the cross-type comparison returns <code>FALSE</code>. Use <code>L</code> suffixes (<code>1L:10L</code>) or <code>as.integer()</code> when you need integer storage.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-1-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.2: Predict type coercion in mixed c() calls</h3>

<p class="exercise-task"><strong>Task:</strong> Run <code>typeof()</code> on each of these five calls and predict the result before checking: <code>c(1, 2, 3)</code>, <code>c(1L, 2L, 3L)</code>, <code>c(1, 2L, 3)</code>, <code>c(1, &quot;2&quot;, 3)</code>, <code>c(1, TRUE, 3)</code>. Save the five returned type strings as a character vector to <code>ex_1_2</code>. The point is to internalise R's <a class="auto-link" href="R-Type-Coercion.html" title="R Type Coercion: Why Your Numeric Columns Silently Turn Into Characters">coercion hierarchy</a> without looking it up every time.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] &quot;double&quot;    &quot;integer&quot;   &quot;double&quot;    &quot;character&quot; &quot;double&quot;</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>When values of different kinds land in one vector, R promotes them all to a single common kind following a fixed precedence order.</p><p>Wrap each <code>c(...)</code> call in <code>typeof()</code> and gather the five resulting strings with another <code>c()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- c(
  typeof(c(1, 2, 3)),
  typeof(c(1L, 2L, 3L)),
  typeof(c(1, 2L, 3)),
  typeof(c(1, &quot;2&quot;, 3)),
  typeof(c(1, TRUE, 3))
)
ex_1_2
#&gt; [1] &quot;double&quot;    &quot;integer&quot;   &quot;double&quot;    &quot;character&quot; &quot;double&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> R coerces along the hierarchy <code>logical &lt; integer &lt; double &lt; character</code>. <code>c()</code> picks the most general type present, so a single character literal forces everything to character and a single double demotes integers. The trap is <code>c(1, &quot;2&quot;, 3)</code>: the middle string silently turns numeric values into the strings <code>&quot;1&quot;</code> and <code>&quot;3&quot;</code>, which then fail arithmetic downstream. Validate input types with <code>is.numeric()</code> before doing math on untrusted vectors.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-1-3" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.3: Audit a seq() with length, head, and tail</h3>

<p class="exercise-task"><strong>Task:</strong> Create <code>prices &lt;- seq(5, 100, by = 5)</code> and report three quick diagnostics: the total length, the first three values, and the last three values. Combine them into a named list and save to <code>ex_1_3</code>. This is the kind of one-line audit you write at the top of every analysis to confirm an input vector is the shape you expect.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $len
#&gt; [1] 20
#&gt; $first3
#&gt; [1]  5 10 15
#&gt; $last3
#&gt; [1]  90  95 100</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A quick three-part audit confirms a vector's size plus both of its ends in one glance.</p><p>Combine <code>length()</code>, <code>head(prices, 3)</code>, and <code>tail(prices, 3)</code> into a named list.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">prices &lt;- seq(5, 100, by = 5)
ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">prices &lt;- seq(5, 100, by = 5)
ex_1_3 &lt;- list(
  len    = length(prices),
  first3 = head(prices, 3),
  last3  = tail(prices, 3)
)
ex_1_3
#&gt; $len
#&gt; [1] 20
#&gt; $first3
#&gt; [1]  5 10 15
#&gt; $last3
#&gt; [1]  90  95 100</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>length()</code>, <code>head()</code>, and <code>tail()</code> are the three cheapest checks you can run on an unknown vector. Together they confirm "right size, right start, right end" in three lines. <code>head()</code> and <code>tail()</code> default to six elements, so pass <code>n = 3</code> (or just <code>3</code>) when you want a tighter peek. For data frames the same trio works because <code>length()</code> returns the column count and <code>head()</code>/<code>tail()</code> slice rows.</p>

</details>

</section>

<h2>Section 2. Indexing and subsetting (4 problems)</h2>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-2-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 2.1: Positional and contiguous slice on a price ladder</h3>

<p class="exercise-task"><strong>Task:</strong> A jeweller is preparing a sale flyer using the <code>prices</code> vector from Exercise 1.3 (a 20-step price ladder from 5 to 100). Pull two slices: the prices at positions 1, 5, and 10 (the "anchor" tiers shown in the flyer), and the contiguous block from positions 11 through 15 (the mid-tier upsell band). Save both as a named list to <code>ex_2_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $anchors
#&gt; [1]  5 25 50
#&gt; $upsell_band
#&gt; [1] 55 60 65 70 75</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>An index vector inside the brackets returns elements in exactly the order you ask for, and a contiguous run can be written compactly.</p><p>Use <code>prices[c(1, 5, 10)]</code> for the anchors and <code>prices[11:15]</code> for the band, collected in a named list.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- list(
  anchors     = prices[c(1, 5, 10)],
  upsell_band = prices[11:15]
)
ex_2_1
#&gt; $anchors
#&gt; [1]  5 25 50
#&gt; $upsell_band
#&gt; [1] 55 60 65 70 75</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A vector of indices inside <code>[ ]</code> returns elements in the order requested, so <code>prices[c(1, 5, 10)]</code> is positional and <code>prices[c(10, 5, 1)]</code> reverses the order. The <code>:</code> shortcut builds a contiguous integer vector, making <code>prices[11:15]</code> the idiomatic way to pull a window. For overlapping or repeated picks (e.g., <code>prices[c(1, 1, 2)]</code>) the values repeat in the output: this is how <code>c()</code> with index vectors differs from set membership.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-2-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: Drop the last two elements two ways</h3>

<p class="exercise-task"><strong>Task:</strong> Using <code>prices</code>, return everything except the last two elements. Solve it twice: once with a negative index built from <code>length()</code>, and once with <code>head()</code> using a negative count. Confirm the two approaches return the same vector by using <code>identical()</code>. Save a list with both vectors and the equality check to <code>ex_2_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $neg_idx
#&gt;  [1]  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90
#&gt; $head_neg
#&gt;  [1]  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90
#&gt; $same
#&gt; [1] TRUE</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>You can describe the elements to keep either by the positions you exclude or by trimming a fixed count off one end.</p><p>Build a negative index from <code>length(prices)</code> and also use <code>head(prices, -2)</code>, then compare the two with <code>identical()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">n &lt;- length(prices)
ex_2_2 &lt;- list(
  neg_idx  = prices[-c(n - 1, n)],
  head_neg = head(prices, -2),
  same     = identical(prices[-c(n - 1, n)], head(prices, -2))
)
ex_2_2
#&gt; $same
#&gt; [1] TRUE</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Negative indexing means "exclude these positions". <code>prices[-1]</code> drops the first element, <code>prices[-c(n-1, n)]</code> drops the last two. <code>head(x, -k)</code> and <code>tail(x, -k)</code> accept negative counts as a cleaner idiom for trimming. Both produce the same result, but the <code>head(prices, -2)</code> form is more readable in pipelines and harder to off-by-one. Mixing positive and negative indices in the same call is an error: pick one or the other.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-2-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.3: Compound logical filter on a price band</h3>

<p class="exercise-task"><strong>Task:</strong> A marketing analyst is targeting the "mid-band" customers and needs the <code>prices</code> values strictly greater than 30 AND strictly less than 75. Build a logical vector using <code>&amp;</code>, then use it to subset <code>prices</code>. Save the resulting numeric vector to <code>ex_2_3</code>. Important: do NOT use <code>&amp;&amp;</code>. That is the scalar form for single <code>if</code> conditions.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 35 40 45 50 55 60 65 70</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Build a single mask that is TRUE only where both bounds hold at once, then use it to subset.</p><p>Combine <code>prices &gt; 30</code> and <code>prices &lt; 75</code> with <code>&amp;</code>, and index <code>prices</code> with that logical vector.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- prices[prices &gt; 30 &amp; prices &lt; 75]
ex_2_3
#&gt; [1] 35 40 45 50 55 60 65 70</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>&amp;</code> and <code>|</code> are element-wise, returning a logical vector the same length as their inputs. <code>&amp;&amp;</code> and <code>||</code> collapse to a single TRUE/FALSE and only look at the first element of each side: using them inside <code>[ ]</code> silently filters by one comparison and drops the rest. The condition <code>x &gt; 30 &amp; x &lt; 75</code> is far cleaner than <code>between(x, 30, 75)</code> (which is dplyr) when you only need base R, and it's compiler-friendly because both comparisons short-circuit on FALSE.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-2-4" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.4: Use which() to locate failing tests in a QA batch</h3>

<p class="exercise-task"><strong>Task:</strong> A QA engineer ran 15 unit tests and stores the pass/fail outcomes as the logical vector <code>results &lt;- c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE)</code>. Report two things: the positions (test numbers) that failed, and the count of failures. Save both as a named list to <code>ex_2_4</code>. This is the standard "where did it break?" lookup pattern.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $failed_positions
#&gt; [1]  3  7 12 15
#&gt; $failure_count
#&gt; [1] 4</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Flip the pass/fail mask so that failures become TRUE, then turn that into positions and a tally.</p><p>Apply <code>which(!results)</code> for the failing positions and <code>sum(!results)</code> for the count, in a named list.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">results &lt;- c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE,
             TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE)
ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">results &lt;- c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE,
             TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE)

ex_2_4 &lt;- list(
  failed_positions = which(!results),
  failure_count    = sum(!results)
)
ex_2_4
#&gt; $failed_positions
#&gt; [1]  3  7 12 15
#&gt; $failure_count
#&gt; [1] 4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>which()</code> converts a logical vector to the integer positions where it is TRUE. Negating with <code>!</code> flips the mask before passing in, so <code>which(!results)</code> gives the failing positions. For the count, <code>sum()</code> on a logical coerces TRUE to 1 and FALSE to 0, so <code>sum(!results)</code> counts failures without an explicit loop. This logical-to-position trick is the foundation of dplyr's <code>slice()</code> and <code>filter()</code> semantics.</p>

</details>

</section>

<h2>Section 3. Named vectors and lookups (3 problems)</h2>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-3-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.1: Three lookups on a named population vector</h3>

<p class="exercise-task"><strong>Task:</strong> A policy analyst keeps populations in millions in a named vector: <code>pop &lt;- c(USA = 331, China = 1412, India = 1417, Brazil = 215, Nigeria = 223)</code>. Pull three things: India's population by name, the values for USA and Nigeria in a single subset call, and the country names whose population exceeds 300 million. Save the three results as a named list to <code>ex_3_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $india
#&gt; India
#&gt;  1417
#&gt; $usa_nigeria
#&gt;     USA Nigeria
#&gt;     331     223
#&gt; $over_300m
#&gt; [1] &quot;USA&quot;   &quot;China&quot; &quot;India&quot;</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A named vector behaves like a dictionary, and to get matching labels you apply the test to the names rather than to the values.</p><p>Use <code>pop[&quot;India&quot;]</code>, <code>pop[c(&quot;USA&quot;, &quot;Nigeria&quot;)]</code>, and <code>names(pop)[pop &gt; 300]</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pop &lt;- c(USA = 331, China = 1412, India = 1417, Brazil = 215, Nigeria = 223)
ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pop &lt;- c(USA = 331, China = 1412, India = 1417, Brazil = 215, Nigeria = 223)

ex_3_1 &lt;- list(
  india       = pop[&quot;India&quot;],
  usa_nigeria = pop[c(&quot;USA&quot;, &quot;Nigeria&quot;)],
  over_300m   = names(pop)[pop &gt; 300]
)
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Character indexing on named vectors is one of R's most elegant features: <code>pop[&quot;India&quot;]</code> works like a dictionary lookup, and the result preserves the name in the output. <code>names(pop)[pop &gt; 300]</code> shows the pattern for "give me the labels of the matching values": apply the logical to <code>names()</code>, not to <code>pop</code> itself. The alternative <code>pop[pop &gt; 300]</code> returns values with their names attached, which is useful when you want both.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-3-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.2: Build a SKU price book and pull a basket</h3>

<p class="exercise-task"><strong>Task:</strong> A retailer maintains a named price book: SKU-A = 19.99, SKU-B = 24.99, SKU-C = 34.99, SKU-D = 49.99, SKU-E = 69.99, SKU-F = 89.99. Build it as a named numeric vector, then pull the prices for a customer basket containing SKU-A, SKU-C, and SKU-F in that order. Sum the basket to get the total. Save the basket vector and total as a named list to <code>ex_3_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $basket
#&gt; SKU-A SKU-C SKU-F
#&gt; 19.99 34.99 89.99
#&gt; $total
#&gt; [1] 144.97</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Names that contain a hyphen must be quoted when you build the vector, and a key lookup returns values in the order of the keys you pass.</p><p>Create the vector with backticked names like `<code> </code>SKU-A<code> </code><code>, index it by </code>c("SKU-A", "SKU-C", "SKU-F")<code>, and total with </code>sum()`.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">price_book &lt;- c(
  `SKU-A` = 19.99, `SKU-B` = 24.99, `SKU-C` = 34.99,
  `SKU-D` = 49.99, `SKU-E` = 69.99, `SKU-F` = 89.99
)
basket_skus &lt;- c(&quot;SKU-A&quot;, &quot;SKU-C&quot;, &quot;SKU-F&quot;)

ex_3_2 &lt;- list(
  basket = price_book[basket_skus],
  total  = sum(price_book[basket_skus])
)
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Backticks around <code>SKU-A</code> are required because the hyphen would otherwise be parsed as minus. The basket lookup is the canonical use case for named vectors: instead of an <code>if/else</code> cascade or a <code>match()</code> call, you index by the keys directly and the values come back in the requested order. For thousands of lookups, named vectors are faster than data frames because there's no row-search overhead.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-3-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.3: Sort a named vector by name and by value</h3>

<p class="exercise-task"><strong>Task:</strong> Take the <code>pop</code> vector from Exercise 3.1. Produce two sorted versions: one sorted alphabetically by country name, and one sorted by population in descending order. The descending sort should keep the names attached so the result is still self-describing. Save both as a named list to <code>ex_3_3</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $by_name
#&gt;  Brazil   China   India Nigeria     USA
#&gt;     215    1412    1417     223     331
#&gt; $by_value_desc
#&gt;   India   China     USA Nigeria  Brazil
#&gt;    1417    1412     331     223     215</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Sorting by the values is direct, but sorting by the labels needs a permutation derived from the names.</p><p>Use <code>order(names(pop))</code> for the alphabetical version and <code>sort(pop, decreasing = TRUE)</code> for the descending one.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- list(
  by_name       = pop[order(names(pop))],
  by_value_desc = sort(pop, decreasing = TRUE)
)
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>sort()</code> works on the values and carries the names along, which is exactly what you want for the descending case. To sort by name instead, use <code>order(names(pop))</code> to get the permutation and index back in. <code>order()</code> is the more general tool because it returns positions (so you can apply the same permutation to a parallel vector). For ties or mixed-type sorts, pass multiple vectors to <code>order()</code>: it breaks ties on the second argument.</p>

</details>

</section>

<h2>Section 4. Vectorized arithmetic and recycling (3 problems)</h2>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-4-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.1: Convert a Fahrenheit vector to Celsius</h3>

<p class="exercise-task"><strong>Task:</strong> A climatologist stores daily highs in Fahrenheit: <code>temps_f &lt;- c(30, 40, 50, 60, 70, 80, 90, 100)</code>. Convert the whole vector to Celsius in one shot using the formula <code>(F - 32) * 5 / 9</code>. The point is to write the formula once and have R apply it element-wise without any loop. Save the resulting numeric vector to <code>ex_4_1</code>, rounded to two decimals.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] -1.11  4.44 10.00 15.56 21.11 26.67 32.22 37.78</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Write the conversion formula once and let R apply it across every element with no loop in sight.</p><p>Compute <code>(temps_f - 32) * 5 / 9</code> and wrap the expression in <code>round(..., 2)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">temps_f &lt;- c(30, 40, 50, 60, 70, 80, 90, 100)
ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">temps_f &lt;- c(30, 40, 50, 60, 70, 80, 90, 100)
ex_4_1 &lt;- round((temps_f - 32) * 5 / 9, 2)
ex_4_1
#&gt; [1] -1.11  4.44 10.00 15.56 21.11 26.67 32.22 37.78</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Every arithmetic operator (<code>-</code>, <code>*</code>, <code>/</code>, <code>^</code>) is vectorised, so the scalar <code>32</code> is recycled across all eight elements automatically. There is no need for <code>sapply()</code> or a <code>for</code> loop. The compiled C code under the hood runs orders of magnitude faster than a manual loop in R. The same pattern handles columns in a data frame because columns are just vectors: <code>mtcars$mpg * 1.609</code> converts MPG to kilometres-per-litre across all rows in one expression.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-4-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 4.2: The recycling trap with mismatched lengths</h3>

<p class="exercise-task"><strong>Task:</strong> Define <code>a &lt;- c(1, 2, 3, 4)</code> and <code>b &lt;- c(5, 6, 7)</code>. Compute <code>a + b</code> and capture both the result AND any warning that R emits. The result should NOT throw a hard error, but the mismatch produces a warning because 3 does not divide evenly into 4. Save the resulting numeric vector to <code>ex_4_2</code>, then write a comment explaining what value the 4th element holds and why.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Warning message:
#&gt; In a + b : longer object length is not a multiple of shorter object length
#&gt; [1]  6  8 10  9
#&gt; # position 4: a[4] = 4 plus the recycled b[1] = 5 gives 9</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>When one vector is shorter, R reuses its elements from the start, and an uneven fit produces a warning rather than a hard error.</p><p>Assign <code>a + b</code> straight to <code>ex_4_2</code>; the shorter <code>b</code> wraps, so position 4 pairs <code>a[4]</code> with <code>b[1]</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">a &lt;- c(1, 2, 3, 4)
b &lt;- c(5, 6, 7)
ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">a &lt;- c(1, 2, 3, 4)
b &lt;- c(5, 6, 7)

ex_4_2 &lt;- a + b
ex_4_2
#&gt; Warning message:
#&gt; In a + b : longer object length is not a multiple of shorter object length
#&gt; [1]  6  8 10  9</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> R recycles the shorter vector to match the longer one. When the longer length is an exact multiple of the shorter (e.g., 6 and 3), there is no warning, which silently masks bugs. When it is not a multiple, R still does the operation but warns you. Position 4 holds <code>a[4] + b[1] = 4 + 5 = 9</code> because <code>b</code> wraps back to its first element. Always treat recycling warnings as errors: in production code, wrap risky arithmetic in <code>if (length(a) != length(b)) stop(...)</code> so a typo cannot quietly corrupt a result.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-4-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.3: cumsum and diff for a daily P&L stream</h3>

<p class="exercise-task"><strong>Task:</strong> A trading desk tracks daily P&L for one week: <code>pnl &lt;- c(250, -150, 280, 145, -245, 90)</code>. Compute two derived vectors that the risk team reads every morning. First, the running cumulative P&L starting from a Monday opening balance of 1000. Second, the day-over-day deltas (which equal <code>pnl</code> itself but force the student to use <code>diff()</code> on the cumulative series). Save both to <code>ex_4_3</code> as a named list.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $running_balance
#&gt; [1] 1250 1100 1380 1525 1280 1370
#&gt; $daily_delta
#&gt; [1]  250 -150  280  145 -245   90</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A running total and a day-over-day change are two complementary views of the same series, and one can be recovered from the other.</p><p>Use <code>1000 + cumsum(pnl)</code> for the balance, then <code>diff()</code> on that balance with the opening 1000 prepended.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pnl &lt;- c(250, -150, 280, 145, -245, 90)
ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pnl &lt;- c(250, -150, 280, 145, -245, 90)

running_balance &lt;- 1000 + cumsum(pnl)
daily_delta     &lt;- diff(c(1000, running_balance))

ex_4_3 &lt;- list(
  running_balance = running_balance,
  daily_delta     = daily_delta
)
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>cumsum()</code> is the vectorised running total: it returns a vector the same length as its input. Adding the scalar <code>1000</code> shifts every element up by the opening balance, again thanks to recycling. <code>diff()</code> returns first differences, which is one element shorter than its input, so to recover the daily P&L we prepend the opening balance to the running series before calling <code>diff()</code>. These two operators together cover ~80% of time-series feature engineering in base R.</p>

</details>

</section>

<h2>Section 5. NA, NULL, and special values (3 problems)</h2>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-5-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 5.1: NA propagation in mean and sum</h3>

<p class="exercise-task"><strong>Task:</strong> The ops team has a vector of response times in milliseconds with a couple of dropped measurements: <code>rt &lt;- c(120, 95, NA, 140, 75, NA, 88)</code>. Compute three things: the default <code>mean(rt)</code> (which propagates NA), the NA-skipping mean via <code>na.rm = TRUE</code>, and the total of non-<a class="auto-link" href="Missing-Value-Treatment-With-R.html" title="Missing Value Treatment">missing values</a> via <code>sum(rt, na.rm = TRUE)</code>. Save all three to <code>ex_5_1</code> as a named list so the contrast is obvious.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $mean_default
#&gt; [1] NA
#&gt; $mean_narm
#&gt; [1] 103.6
#&gt; $sum_narm
#&gt; [1] 518</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A missing value contaminates an aggregate unless the function is explicitly told to ignore it.</p><p>Call <code>mean(rt)</code>, <code>mean(rt, na.rm = TRUE)</code>, and <code>sum(rt, na.rm = TRUE)</code> into a named list.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">rt &lt;- c(120, 95, NA, 140, 75, NA, 88)
ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">rt &lt;- c(120, 95, NA, 140, 75, NA, 88)

ex_5_1 &lt;- list(
  mean_default = mean(rt),
  mean_narm    = mean(rt, na.rm = TRUE),
  sum_narm     = sum(rt, na.rm = TRUE)
)
ex_5_1
#&gt; $mean_default
#&gt; [1] NA
#&gt; $mean_narm
#&gt; [1] 103.6
#&gt; $sum_narm
#&gt; [1] 518</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> NA propagation is contagious: any arithmetic that touches an NA returns NA unless the function explicitly knows to skip them. Most aggregators in base R (<code>mean</code>, <code>sum</code>, <code>sd</code>, <code>min</code>, <code>max</code>, <code>median</code>, <code>var</code>) accept <code>na.rm = TRUE</code> for that purpose. Silent NAs are the single most common reason a downstream model errors out with "input contains missing values", so the safer default in pipelines is to either drop them upstream or impute, not to silently <code>na.rm</code>.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-5-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.2: Distinguish NA, NULL, NaN, and Inf</h3>

<p class="exercise-task"><strong>Task:</strong> Build a list containing one of each: <code>NA</code> (missing), <code>NULL</code> (absent), <code>NaN</code> (not-a-number, from <code>0/0</code>), and <code>Inf</code> (from <code>1/0</code>). For each value, run the four tests <code>is.na</code>, <code>is.null</code>, <code>is.nan</code>, and <code>is.finite</code> and store the four logical results. Save the lot as a list of four named logical vectors to <code>ex_5_2</code>. The point is to see which tests fire on which value.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $na      : is.na=TRUE  is.null=FALSE is.nan=FALSE is.finite=FALSE
#&gt; $null    : is.na=logical(0) is.null=TRUE is.nan=logical(0) is.finite=logical(0)
#&gt; $nan     : is.na=TRUE  is.null=FALSE is.nan=TRUE  is.finite=FALSE
#&gt; $inf     : is.na=FALSE is.null=FALSE is.nan=FALSE is.finite=FALSE</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Each special value answers a different question about missingness, absence, and finiteness, and one of them has zero length.</p><p>Run <code>is.na</code>, <code>is.null</code>, <code>is.nan</code>, and <code>is.finite</code> against <code>NA</code>, <code>NULL</code>, <code>0 / 0</code>, and <code>1 / 0</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">test_one &lt;- function(x) c(
  is.na     = is.na(x),
  is.null   = is.null(x),
  is.nan    = is.nan(x),
  is.finite = is.finite(x)
)

ex_5_2 &lt;- list(
  na   = test_one(NA),
  null = test_one(NULL),
  nan  = test_one(0 / 0),
  inf  = test_one(1 / 0)
)
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Two facts catch most beginners: <code>is.na(NaN)</code> is TRUE because NaN counts as a flavour of missing, and <code>is.null(NA)</code> is FALSE because NA is a value but NULL is the absence of a value. Tests applied to NULL return zero-length logicals because NULL has length zero. <code>is.finite(Inf)</code> is FALSE, which matters for ratio calculations where a denominator can hit zero. The defensive pattern is <code>x[is.finite(x)]</code> to keep only "real" numbers before averaging.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-5-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.3: Last-observation-carried-forward on a sensor stream</h3>

<p class="exercise-task"><strong>Task:</strong> A sensor team has 10 hourly readings with intermittent dropouts: <code>sensor &lt;- c(22.1, NA, 22.3, NA, NA, 22.8, NA, 23.1, NA, NA)</code>. Fill the NAs by carrying the most recent non-NA value forward (LOCF). Save the imputed numeric vector to <code>ex_5_3</code>. Constraint: write the loop yourself, do not use <code>zoo::na.locf</code> or <code>tidyr::fill</code>. The exercise is about understanding what those packages do under the hood.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;  [1] 22.1 22.1 22.3 22.3 22.3 22.8 22.8 23.1 23.1 23.1</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Fill each gap by reaching back to the most recent value already known, walking the series strictly in time order.</p><p>Loop with <code>seq_along()</code>, and when <code>is.na()</code> is TRUE at position <code>i</code> (with <code>i &gt; 1</code>), copy element <code>i - 1</code> forward.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">sensor &lt;- c(22.1, NA, 22.3, NA, NA, 22.8, NA, 23.1, NA, NA)
ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">sensor &lt;- c(22.1, NA, 22.3, NA, NA, 22.8, NA, 23.1, NA, NA)

ex_5_3 &lt;- sensor
for (i in seq_along(ex_5_3)) {
  if (is.na(ex_5_3[i]) &amp;&amp; i &gt; 1) {
    ex_5_3[i] &lt;- ex_5_3[i - 1]
  }
}
ex_5_3
#&gt;  [1] 22.1 22.1 22.3 22.3 22.3 22.8 22.8 23.1 23.1 23.1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> LOCF is the simplest imputation method and the only one that respects time order without lookahead. The single-pass loop works because by the time we hit position <code>i</code>, position <code>i - 1</code> has already been filled (if it was NA, the previous iteration set it). The base-R vectorised trick uses <code>cummax</code> on a position index: <code>ex_5_3 &lt;- sensor[cummax((!is.na(sensor)) * seq_along(sensor))]</code>. LOCF assumes the underlying signal is roughly piecewise-constant; for trending data, linear interpolation via <code>approx()</code> is usually better.</p>

</details>

</section>

<h2>Section 6. Real-world vector workflows (2 problems)</h2>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-6-1" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.1: Z-score a vector and flag outliers</h3>

<p class="exercise-task"><strong>Task:</strong> The fraud team scores transaction amounts for <a class="auto-link" href="Outlier-Treatment-With-R.html" title="Outlier Treatment with R">outlier detection</a>: <code>amounts &lt;- c(45.0, 52.3, 47.8, 245.0, 49.1, 50.4, 9.2, 51.5, 48.9, 53.7)</code>. Compute the z-score of each amount (subtract the mean, divide by the standard deviation), then flag the values whose absolute z-score exceeds 2 as outliers. Save a list with two elements: <code>z</code> (numeric vector of z-scores) and <code>outliers</code> (numeric vector of original amounts that exceeded the threshold) to <code>ex_6_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $z
#&gt;  [1] -0.13  0.00 -0.08  3.46 -0.10 -0.08 -0.81 -0.07 -0.09  -0.06
#&gt; $outliers
#&gt; [1] 245.0   9.2</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Re-express each value as how many spread-units it sits from the centre, then threshold on the magnitude of that distance.</p><p>Compute <code>(amounts - mean(amounts)) / sd(amounts)</code>, then subset <code>amounts</code> where <code>abs(z) &gt; 2</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">amounts &lt;- c(45.0, 52.3, 47.8, 245.0, 49.1, 50.4, 9.2, 51.5, 48.9, 53.7)
ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">amounts &lt;- c(45.0, 52.3, 47.8, 245.0, 49.1, 50.4, 9.2, 51.5, 48.9, 53.7)

z &lt;- (amounts - mean(amounts)) / sd(amounts)
ex_6_1 &lt;- list(
  z        = round(z, 2),
  outliers = amounts[abs(z) &gt; 2]
)
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The z-score <code>(x - mean(x)) / sd(x)</code> is the workhorse of distance-based outlier detection. Because <code>mean</code> and <code>sd</code> themselves are pulled up by the outliers, a single extreme value (here 245.0) inflates the standard deviation and can mask other outliers. The robust alternative is the modified z-score using <code>median()</code> and <code>mad()</code>: <code>(x - median(x)) / mad(x)</code>. For very small samples (n < 30) or skewed distributions, prefer the IQR rule (<code>Q1 - 1.5 * IQR</code> and <code>Q3 + 1.5 * IQR</code>) over either z-score.</p>

</details>

</section>

<section class="exercise" data-exercise-id="R-Vectors-Exercises-ex-6-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.2: Bucket customers into segments with cut()</h3>

<p class="exercise-task"><strong>Task:</strong> A marketing analyst has 12 customer lifetime values: <code>clv &lt;- c(120, 450, 88, 230, 890, 1250, 75, 340, 1100, 95, 560, 410)</code>. Bucket them into three named segments using <code>cut()</code>: "low" (less than 250), "mid" (250 to 800), and "high" (over 800). Use <code>table()</code> to count how many customers fall into each bucket. Save the segment factor and the count table as a named list to <code>ex_6_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $segment
#&gt;  [1] low  mid  low  low  high high low  mid  high low  mid  mid
#&gt; Levels: low mid high
#&gt; $counts
#&gt;  low  mid high
#&gt;    5    4    3</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Turn the continuous values into a small set of labeled bands, using open-ended outer edges so nothing escapes a bucket.</p><p>Call <code>cut()</code> with <code>breaks = c(-Inf, 250, 800, Inf)</code>, the three <code>labels</code>, and <code>right = FALSE</code>, then count with <code>table()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">clv &lt;- c(120, 450, 88, 230, 890, 1250, 75, 340, 1100, 95, 560, 410)
ex_6_2 &lt;- # your code here
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">clv &lt;- c(120, 450, 88, 230, 890, 1250, 75, 340, 1100, 95, 560, 410)

segment &lt;- cut(
  clv,
  breaks = c(-Inf, 250, 800, Inf),
  labels = c(&quot;low&quot;, &quot;mid&quot;, &quot;high&quot;),
  right  = FALSE
)

ex_6_2 &lt;- list(
  segment = segment,
  counts  = table(segment)
)
ex_6_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>cut()</code> is the canonical way to turn a continuous numeric vector into an <a class="auto-link" href="R-Factors.html" title="R Factors: The Data Type That Trips Up Almost Every R Beginner">ordered factor</a> with labeled bins. Using <code>-Inf</code> and <code>Inf</code> as the outer breakpoints catches anything below the lowest cut or above the highest, so you never accidentally produce NAs. The <code>right = FALSE</code> flag makes intervals left-closed and right-open <code>[a, b)</code>, which matches how most product specs are written ("250 to 800 means at least 250 and below 800"). <code>table()</code> on a factor returns counts in factor-level order rather than alphabetical, preserving the low / mid / high reading direction.</p>

</details>

</section>

<h2>What to do next</h2>

<ul>

<li>Read the parent tutorial: <a href="R-Vectors.html">R Vectors</a> covers vector internals, attributes, and the recycling rule.</li>

<li>Practice list and data frame indexing: <a href="Apply-Family-Exercises-in-R.html">Apply Family Exercises in R</a> builds on vectorised thinking with <code>sapply</code>, <code>lapply</code>, and <code>mapply</code>.</li>

<li>Move on to wrangling: <a href="dplyr-Exercises-in-R.html">dplyr Exercises in R</a> applies the same filter, mutate, and group patterns to data frame columns (which are vectors).</li>

<li>Stress-test your loop intuition: <a href="Loops-vs-Vectorization-Exercises-in-R.html">Loops vs Vectorization Exercises in R</a> shows when an explicit loop beats a vectorised expression and when it doesn't.</li>

</ul>

{% endraw %}