---
title: "readr Exercises in R: 28 Real Data Import Problems"
description: "28 readr practice problems with hidden solutions: read_csv, col_types, parse_number, locales, encoding, write_csv. Realistic data-import scenarios."
keywords: "readr exercises, read_csv R exercises, R data import practice, readr practice problems, parse_number R, col_types readr"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "readr exercises|read_csv exercises|data import exercises|parse_number|col_types"
auto_link_case_sensitive: false
sidebar_title: "readr Exercises"
sidebar_order: "115"
fr_parent: "readr-vs-read-csv-vs-fread.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>readr Exercises in R: 28 Real Data Import Problems</h1>
<p class="lead">Twenty eight practice problems that drill the readr workflow: <code>read_csv</code>, column type specifications, custom NA handling, locale and encoding tricks, the <code>parse_*</code> helper family, writing back to disk, and diagnosing parse failures. Every problem ships with a hidden runnable solution and a short explanation.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="28" data-time="60" data-xp="420"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(readr)
library(dplyr)
library(tibble)

set.seed(42)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Reading the basics with read_csv (5 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="readr-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Read an inline CSV string with read_csv</h3>
<p class="exercise-task"><strong>Task:</strong> A junior analyst onboarding to the data team is testing readr without touching disk. Use <code>read_csv()</code> on the literal string <code>"id,score\n1,87\n2,92\n3,78"</code> (wrap it in <code>I()</code> so readr treats it as data rather than a path) and save the resulting tibble to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 3 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): id, score

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 3 × 2
     id score
  &lt;dbl&gt; &lt;dbl&gt;
1     1    87
2     2    92
3     3    78
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>readr can treat a literal string as if it were a file, so you do not have to write anything to disk first.</p><p>Reach for <a class="auto-link" href="Importing-Data-in-R.html" title="Importing Data into R: read_csv(), read_excel(), read_json() — Complete Guide">read_csv()</a> and wrap the string in I() so it is read as data rather than a path.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- read_csv(I("id,score\n1,87\n2,92\n3,78"))
ex_1_1
#&gt; # A tibble: 3 x 2
#&gt;      id score
#&gt;   &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1     1    87
#&gt; 2     2    92
#&gt; 3     3    78</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>read_csv()</code> decides between a path and literal data by inspecting the input. Wrapping the string in <code>I()</code> (the AsIs class) forces the literal interpretation and silences the deprecation warning that earlier readr versions emit for raw strings. This pattern is the cleanest way to write reproducible examples and unit tests without managing temp files.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="readr-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Read tab-separated data with read_tsv</h3>
<p class="exercise-task"><strong>Task:</strong> A reporting analyst exported the daily KPI table from a legacy BI tool and got a tab-separated file. Recreate that scenario by passing the literal <code>"region\tsales\nNorth\t1200\nSouth\t950"</code> (with real tab characters) to <code>read_tsv()</code> via <code>I()</code> and save the parsed tibble to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 2 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): region
dbl (1): sales

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 2 × 2
  region sales
  &lt;chr&gt;  &lt;dbl&gt;
1 North   1200
2 South    950
</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Tab-separated data needs a reader that splits each line on tabs instead of commas.</p><p>Use read_tsv() and pass the literal string through I().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- read_tsv(I("region\tsales\nNorth\t1200\nSouth\t950"))
ex_1_2
#&gt; # A tibble: 2 x 2
#&gt;   region sales
#&gt;   &lt;chr&gt;  &lt;dbl&gt;
#&gt; 1 North   1200
#&gt; 2 South    950</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>read_tsv()</code> is a thin convenience wrapper around <code>read_delim(delim = "\t")</code>. The <code>\t</code> escape in the literal becomes a real tab byte, so readr splits each line on tabs. If your file had spaces inside a field, you would need to quote them; tabs are unambiguous separators and rarely appear inside business strings, which is why analysts prefer TSV for hand-curated data.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Parse a semicolon-delimited extract with read_delim</h3>
<p class="exercise-task"><strong>Task:</strong> The finance team's ERP exports use semicolons to avoid breaking on commas inside vendor names. Use <code>read_delim()</code> with <code>delim = ";"</code> to parse <code>"vendor;amount\nAcme, Inc.;1500\nBeta LLC;2300"</code> (wrapped in <code>I()</code>) and save the tibble to <code>ex_1_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 2 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (1): vendor
dbl (1): amount

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 2 × 2
  vendor     amount
  &lt;chr&gt;       &lt;dbl&gt;
1 Acme, Inc.   1500
2 Beta LLC     2300
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>When the separator is neither a comma nor a tab, you need the general-purpose delimited reader and must state the separator yourself.</p><p>Call <a class="auto-link" href="readr-read_delim-in-R.html" title="readr read_delim() in R: Read Any Delimited Text File">read_delim()</a> with delim = ";" and wrap the string in I().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- read_delim(
  I("vendor;amount\nAcme, Inc.;1500\nBeta LLC;2300"),
  delim = ";"
)
ex_1_3
#&gt; # A tibble: 2 x 2
#&gt;   vendor     amount
#&gt;   &lt;chr&gt;       &lt;dbl&gt;
#&gt; 1 Acme, Inc.   1500
#&gt; 2 Beta LLC     2300</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Picking the right delimiter is the most common readr failure mode in financial pipelines. Semicolons sidestep the case where commas appear inside text fields ("Acme, Inc."). <code>read_delim()</code> is the general form; <code>read_csv()</code>, <code>read_tsv()</code>, and <code>read_csv2()</code> are pre-configured shortcuts. When in doubt, peek at the raw bytes with <code>read_lines(path, n_max = 5)</code> before choosing.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-1-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.4: Read a European-style CSV with read_csv2</h3>
<p class="exercise-task"><strong>Task:</strong> A climatologist in Berlin exported station readings using comma as the decimal mark and semicolon as the column separator (the Excel German default). Use <code>read_csv2()</code> on <code>"station;temp_c\nA;12,4\nB;15,7"</code> (wrapped in <code>I()</code>) and save the parsed tibble to <code>ex_1_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
Rows: 2 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (1): station
dbl (1): temp_c

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 2 × 2
  station temp_c
  &lt;chr&gt;    &lt;dbl&gt;
1 A         12.4
2 B         15.7
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Some locales use a comma for the decimal point and a semicolon between columns, and there is a dedicated reader for exactly that combination.</p><p>Use read_csv2() (not read_csv) on the I()-wrapped string.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_4 &lt;- read_csv2(I("station;temp_c\nA;12,4\nB;15,7"))
ex_1_4
#&gt; # A tibble: 2 x 2
#&gt;   station temp_c
#&gt;   &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 A         12.4
#&gt; 2 B         15.7</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>read_csv2()</code> ships with a locale that sets <code>decimal_mark = ","</code> and <code>grouping_mark = "."</code>, plus the semicolon separator. Without it, <code>12,4</code> would land as the string "12,4" or trigger parse failures. The same result could be achieved with <code>read_delim(delim = ";", locale = locale(decimal_mark = ","))</code> but the <code>_csv2</code> shortcut is the idiomatic European import.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="readr-Exercises-in-R-ex-1-5" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.5: Round-trip mtcars through a tempfile</h3>
<p class="exercise-task"><strong>Task:</strong> Validate that a write-then-read cycle preserves data by writing <code>mtcars</code> to a temp file with <code>write_csv()</code>, reading it back with <code>read_csv()</code>, and saving the re-read tibble (just the first 3 rows) to <code>ex_1_5</code>. Use <code>tempfile()</code> so nothing pollutes your working directory.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 3 x 11
#&gt;     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1  21       6   160   110  3.9   2.62  16.5     0     1     4     4
#&gt; 2  21       6   160   110  3.9   2.88  17.0     0     1     4     4
#&gt; 3  22.8     4   108    93  3.85  2.32  18.6     1     1     4     1</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>Write the data to a throwaway file, then read it straight back in and keep only the opening rows.</p><p>Pair write_csv() with read_csv(), using tempfile() for the path and head(3) for the slice.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_5 &lt;- # your code here
ex_1_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">tf &lt;- tempfile(fileext = ".csv")
write_csv(mtcars, tf)
ex_1_5 &lt;- read_csv(tf, show_col_types = FALSE) |&gt; head(3)
ex_1_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>write_csv()</code> drops row names, which is why the model names ("Mazda RX4") are not present in the round trip. If you need them, call <code>tibble::rownames_to_column()</code> before writing. <code>tempfile()</code> returns a path under the session temp directory that is cleaned up when R exits, making it safe for experiments and CI tests.</p>
</details>
</section>
<h2>Section 2. Column types and the cols() spec (5 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-2-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.1: Specify explicit column types with cols</h3>
<p class="exercise-task"><strong>Task:</strong> A data engineer wants to lock the schema for a partner extract so a stray text value cannot silently flip a column to character. Read <code>"id,amount\n1,100\n2,250"</code> (wrapped in <code>I()</code>) with <code>read_csv()</code> and a <code>col_types = cols(id = col_integer(), amount = col_double())</code> spec, saving the result to <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 2
#&gt;      id amount
#&gt;   &lt;int&gt;  &lt;dbl&gt;
#&gt; 1     1    100
#&gt; 2     2    250</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You can hand the reader an explicit schema up front instead of letting it guess each column.</p><p>Pass col_types = cols(id = col_integer(), amount = col_double()) to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- read_csv(
  I("id,amount\n1,100\n2,250"),
  col_types = cols(
    id     = col_integer(),
    amount = col_double()
  )
)
ex_2_1
#&gt; # A tibble: 2 x 2
#&gt;      id amount
#&gt;   &lt;int&gt;  &lt;dbl&gt;
#&gt; 1     1    100
#&gt; 2     2    250</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Without an explicit spec, readr guesses types from the first 1000 rows. Guessing is convenient interactively, but brittle in pipelines where a partner might insert "N/A" on row 1001 and break downstream code. Locking types with <code>cols()</code> makes the schema part of your code review surface; a violation becomes a parsing warning you can catch with <code>problems()</code>.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Force a numeric-looking ID to character</h3>
<p class="exercise-task"><strong>Task:</strong> Customer IDs in the CRM extract are 10-digit numbers, but you must keep leading zeros for join keys to match. Read <code>"cust_id,total\n0012345,500\n0098761,300"</code> (wrapped in <code>I()</code>) and force <code>cust_id</code> to character with <code>col_types = cols(cust_id = col_character())</code>. Save the tibble to <code>ex_2_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 2
#&gt;   cust_id  total
#&gt;   &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 0012345    500
#&gt; 2 0098761    300</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>An identifier with leading zeros must stay text, or the zeros are lost the moment it is read as a number.</p><p>Set col_types = cols(cust_id = col_character()) in read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- read_csv(
  I("cust_id,total\n0012345,500\n0098761,300"),
  col_types = cols(cust_id = col_character())
)
ex_2_2
#&gt; # A tibble: 2 x 2
#&gt;   cust_id  total
#&gt;   &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 0012345    500
#&gt; 2 0098761    300</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> This is the single most common readr footgun in production code. Guessing turns <code>0012345</code> into the number 12345 and silently breaks every downstream join against a string key. The fix is a one-line <code>col_character()</code> override. Pin the column type any time the field is conceptually an identifier (zip codes, phone numbers, account IDs) even if the source data looks numeric.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Parse a date column with col_date and a format</h3>
<p class="exercise-task"><strong>Task:</strong> A retail ops analyst gets daily inventory exports with dates formatted as <code>dd/mm/yyyy</code>. Read <code>"sku,sold_on\nA1,03/04/2026\nA2,12/04/2026"</code> (wrapped in <code>I()</code>) and pass <code>col_types = cols(sold_on = col_date(format = "%d/%m/%Y"))</code> so the column lands as <code>Date</code>. Save to <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 2
#&gt;   sku   sold_on
#&gt;   &lt;chr&gt; &lt;date&gt;
#&gt; 1 A1    2026-04-03
#&gt; 2 A2    2026-04-12</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A day-first <a class="auto-link" href="lubridate-ymd-in-R.html" title="lubridate ymd() in R: Parse Dates From Strings">date string</a> will not be recognized unless you describe the exact layout of the text.</p><p>Use col_types with col_date(format = "%d/%m/%Y") for the sold_on column.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_3 &lt;- read_csv(
  I("sku,sold_on\nA1,03/04/2026\nA2,12/04/2026"),
  col_types = cols(sold_on = col_date(format = "%d/%m/%Y"))
)
ex_2_3
#&gt; # A tibble: 2 x 2
#&gt;   sku   sold_on
#&gt;   &lt;chr&gt; &lt;date&gt;
#&gt; 1 A1    2026-04-03
#&gt; 2 A2    2026-04-12</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Day-first formats are the rule across most of Europe and the Commonwealth, and readr does not guess them. Always pass an explicit <code>format</code> string when the source is ambiguous: <code>%d/%m/%Y</code> is unambiguous, <code>"03/04/2026"</code> is not. Skipping this step is the single most common cause of off-by-month bugs in cross-region reporting.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-2-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.4: Drop unwanted columns with col_skip</h3>
<p class="exercise-task"><strong>Task:</strong> A privacy-conscious workflow needs to ingest a customer file but strip the email address at parse time so it never lives in memory. Read <code>"id,name,email,amount\n1,Ann,a@x.com,40\n2,Bob,b@y.com,55"</code> (wrapped in <code>I()</code>) and use <code>col_types = cols(email = col_skip())</code> to drop that column. Save the tibble to <code>ex_2_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 3
#&gt;      id name  amount
#&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
#&gt; 1     1 Ann       40
#&gt; 2     2 Bob       55</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You can drop a sensitive column while the file is being read, so its values never enter memory.</p><p>Pass col_types = cols(email = col_skip()) to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_4 &lt;- # your code here
ex_2_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_4 &lt;- read_csv(
  I("id,name,email,amount\n1,Ann,a@x.com,40\n2,Bob,b@y.com,55"),
  col_types = cols(email = col_skip())
)
ex_2_4
#&gt; # A tibble: 2 x 3
#&gt;      id name  amount
#&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
#&gt; 1     1 Ann       40
#&gt; 2     2 Bob       55</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>col_skip()</code> is cheaper than reading and then dropping with <code>select(-email)</code> because readr never allocates the column or parses its values. For wide files (think 200-column survey exports where you only care about 8 columns) this can be a 10x speedup. Pair it with <code>cols_only(...)</code> to flip the default from "read all" to "read these only".</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="readr-Exercises-in-R-ex-2-5" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.5: Suppress the type message with show_col_types</h3>
<p class="exercise-task"><strong>Task:</strong> When automating reports, the column-type message printed by <code>read_csv()</code> pollutes the log output. Read <code>"x,y\n1,2\n3,4"</code> (wrapped in <code>I()</code>) and pass <code>show_col_types = FALSE</code> so the message is suppressed. Save the resulting tibble to <code>ex_2_5</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 2 x 2
#&gt;       x     y
#&gt;   &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1     1     2
#&gt; 2     3     4</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>The reader prints a column-type summary by default, and that message can be turned off.</p><p>Add show_col_types = FALSE to the read_csv() call.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_5 &lt;- # your code here
ex_2_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_5 &lt;- read_csv(I("x,y\n1,2\n3,4"), show_col_types = FALSE)
ex_2_5
#&gt; # A tibble: 2 x 2
#&gt;       x     y
#&gt;   &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1     1     2
#&gt; 2     3     4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The default-on message is helpful when you are exploring, but noisy in batch jobs and Quarto documents. The safer alternative is to set an explicit <code>col_types</code> (which also suppresses the message) so readers can see the intended schema. Use <code>show_col_types = FALSE</code> only when you have already locked types or genuinely do not care.</p>
</details>
</section>
<h2>Section 3. Missing values, comments, and slicing (5 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Treat a custom token as NA</h3>
<p class="exercise-task"><strong>Task:</strong> The marketing team's vendor exports use the literal string <code>"N/A"</code> to mean missing instead of an empty field. Read <code>"campaign,clicks\nA,150\nB,N/A\nC,275"</code> (wrapped in <code>I()</code>) with <code>na = "N/A"</code> so the missing value becomes a real <code>NA_real_</code>, and save the tibble to <code>ex_3_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 3 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): campaign
dbl (1): clicks

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 3 × 2
  campaign clicks
  &lt;chr&gt;     &lt;dbl&gt;
1 A           150
2 B            NA
3 C           275
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Tell the reader which literal token in the file is meant to stand in for a missing value.</p><p>Pass na = "N/A" to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- read_csv(
  I("campaign,clicks\nA,150\nB,N/A\nC,275"),
  na = "N/A"
)
ex_3_1
#&gt; # A tibble: 3 x 2
#&gt;   campaign clicks
#&gt;   &lt;chr&gt;     &lt;dbl&gt;
#&gt; 1 A           150
#&gt; 2 B            NA
#&gt; 3 C           275</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Without the <code>na</code> argument, the literal "N/A" would force the entire column to character (since "N/A" cannot be coerced to double). The result is a column where you can no longer compute sums or averages until you find and replace the sentinel. Declaring <code>na = "N/A"</code> up front is faster than a post-hoc <code>mutate(clicks = na_if(clicks, "N/A"))</code> plus a re-parse.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Treat multiple sentinels as NA in one pass</h3>
<p class="exercise-task"><strong>Task:</strong> A legacy clinical export uses three different missing markers: empty string, <code>"."</code> (SAS convention), and <code>"NULL"</code> (database convention). Read <code>"patient_id,bp\n1,120\n2,.\n3,\n4,NULL\n5,135"</code> (wrapped in <code>I()</code>) with <code>na = c("", ".", "NULL")</code>, and save the tibble to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 5 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): patient_id, bp

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 5 × 2
  patient_id    bp
       &lt;dbl&gt; &lt;dbl&gt;
1          1   120
2          2    NA
3          3    NA
4          4    NA
5          5   135
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The missing-value setting can recognize several tokens at once, not just a single one.</p><p>Pass na = c("", ".", "NULL") to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_2 &lt;- read_csv(
  I("patient_id,bp\n1,120\n2,.\n3,\n4,NULL\n5,135"),
  na = c("", ".", "NULL")
)
ex_3_2
#&gt; # A tibble: 5 x 2
#&gt;   patient_id    bp
#&gt;        &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1          1   120
#&gt; 2          2    NA
#&gt; 3          3    NA
#&gt; 4          4    NA
#&gt; 5          5   135</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The <code>na</code> argument accepts a character vector and applies each entry across every column. If different columns need different missing markers, you must use <code>col_types</code> with per-column <code>col_double(na = ...)</code> instead. Always inspect the raw bytes (<code>read_lines(file, n_max = 20)</code>) before importing data from systems you do not control: every team invents its own sentinel.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Skip metadata rows at the top of the file</h3>
<p class="exercise-task"><strong>Task:</strong> Lab instruments often write three header rows (timestamp, instrument ID, operator) before the real CSV header. Read <code>"# generated 2026-04-12\n# instrument: GC-2010\n# operator: K\nsample,reading\nS1,3.4\nS2,4.1"</code> (wrapped in <code>I()</code>) with <code>skip = 3</code>, and save the tibble to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 2 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): sample
dbl (1): reading

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 2 × 2
  sample reading
  &lt;chr&gt;    &lt;dbl&gt;
1 S1         3.4
2 S2         4.1
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>When a fixed number of metadata lines sit above the real header, you can jump past them before parsing starts.</p><p>Pass skip = 3 to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- read_csv(
  I("# generated 2026-04-12\n# instrument: GC-2010\n# operator: K\nsample,reading\nS1,3.4\nS2,4.1"),
  skip = 3
)
ex_3_3
#&gt; # A tibble: 2 x 2
#&gt;   sample reading
#&gt;   &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 S1         3.4
#&gt; 2 S2         4.1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>skip</code> is the right tool when the metadata count is fixed and known. If the count varies per file, you have two options: use <code>comment = "#"</code> to drop any line starting with that character (next exercise), or read with <code>read_lines()</code>, filter the metadata rows yourself, and pass the cleaned vector back to <code>read_csv()</code>. Choose <code>skip</code> for stability, <code>comment</code> for flexibility.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-3-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.4: Drop comment lines starting with #</h3>
<p class="exercise-task"><strong>Task:</strong> A meteorologist's automated logger interleaves comment lines (starting with <code>#</code>) between data rows whenever the sensor recalibrates. Read <code>"station,reading\nA,12.4\n# recalibration at 09:14\nA,12.6\nB,11.0"</code> (wrapped in <code>I()</code>) with <code>comment = "#"</code> so the recalibration note is dropped, and save the tibble to <code>ex_3_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Rows: 3 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): station
dbl (1): reading

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 3 × 2
  station reading
  &lt;chr&gt;     &lt;dbl&gt;
1 A          12.4
2 A          12.6
3 B          11
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Lines that begin with a marker character can be dropped wherever they appear, not only at the top of the file.</p><p>Pass comment = "#" to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
ex_3_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- read_csv(
  I("station,reading\nA,12.4\n# recalibration at 09:14\nA,12.6\nB,11.0"),
  comment = "#"
)
ex_3_4
#&gt; # A tibble: 3 x 2
#&gt;   station reading
#&gt;   &lt;chr&gt;     &lt;dbl&gt;
#&gt; 1 A          12.4
#&gt; 2 A          12.6
#&gt; 3 B          11.0</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>comment</code> is line-based, not row-based: any line whose first non-whitespace character matches the comment string is dropped entirely. This is more forgiving than <code>skip</code> because it works anywhere in the file, not just at the top. It will not handle inline trailing comments ("<code>12.4 # noted</code>"); for those you need to read into a character column and strip the trailing portion manually.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="readr-Exercises-in-R-ex-3-5" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.5: Read only the first 5 rows with n_max</h3>
<p class="exercise-task"><strong>Task:</strong> Before launching a full import of a 10-million-row file, you want a fast preview to confirm the schema. Build a 20-row CSV with <code>format_csv(head(diamonds, 20))</code>, feed it to <code>read_csv()</code> via <code>I()</code> with <code>n_max = 5</code>, and save the 5-row tibble to <code>ex_3_5</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # A tibble: 5 x 10
#&gt;   carat cut       color clarity depth table price     x     y     z
#&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1  0.23 Ideal     E     SI2      61.5    55   326  3.95  3.98  2.43
#&gt; 2  0.21 Premium   E     SI1      59.8    61   326  3.89  3.84  2.31
#&gt; 3  0.23 Good      E     VS1      56.9    65   327  4.05  4.07  2.31
#&gt; 4  0.29 Premium   I     VS2      62.4    58   334  4.2   4.23  2.63
#&gt; 5  0.31 Good      J     SI2      63.3    58   335  4.34  4.35  2.75</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>You can stop the reader after just a handful of rows to get a fast preview of a large file.</p><p>Build the CSV with format_csv(head(diamonds, 20)) and pass n_max = 5 to read_csv().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_5 &lt;- # your code here
ex_3_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">preview_csv &lt;- format_csv(head(diamonds, 20))
ex_3_5 &lt;- read_csv(I(preview_csv), n_max = 5, show_col_types = FALSE)
ex_3_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>n_max</code> is the right lever for a fast preview because readr stops reading after <code>n_max</code> data rows and never allocates memory for the rest of the file. The factor columns of <code>diamonds</code> (<code>cut</code>, <code>color</code>, <code>clarity</code>) come back as character here because readr does not know their level ordering: serializing through CSV always strips factor metadata, which is why <a class="auto-link" href="Apache-Arrow-in-R.html" title="Apache Arrow in R: Read Parquet Files &amp; Run Fast In-Memory Analytics">parquet</a> or <code>qs</code> is preferred for round-trips of typed data.</p>
</details>
</section>
<h2>Section 4. Parsing helpers for vectors (5 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Strip currency symbols with parse_number</h3>
<p class="exercise-task"><strong>Task:</strong> A finance analyst pasted invoice totals from a PDF into a CSV column and ended up with strings like <code>"$1,234.50"</code>. Use <code>parse_number()</code> on the vector <code>c("$1,234.50", "$899.00", "$2,500.75")</code> to extract clean doubles, and save the numeric result to <code>ex_4_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 1234.50  899.00 2500.75</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A dedicated helper pulls the numeric value out of a noisy string, ignoring currency symbols and grouping marks.</p><p>Apply <a class="auto-link" href="readr-parse_number-in-R.html" title="readr parse_number() in R: Extract Numbers From Text">parse_number()</a> to the character vector.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- parse_number(c("$1,234.50", "$899.00", "$2,500.75"))
ex_4_1
#&gt; [1] 1234.50  899.00 2500.75</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>parse_number()</code> is the swiss army knife for "this looks numeric but has noise": it strips currency symbols, percent signs, grouping marks, and arbitrary surrounding text. It is safer than a custom <code>gsub()</code> chain because it respects the active locale (next exercise) and reports per-element parse failures through <code>problems()</code>. Reach for it whenever upstream data was hand-edited or copy-pasted.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Parse percentages stored as strings</h3>
<p class="exercise-task"><strong>Task:</strong> A campaign export from the ad platform stores click-through rates as strings with trailing percent signs, e.g. <code>c("3.5%", "2.8%", "4.1%")</code>. Use <code>parse_number()</code> to extract the numeric portion (you get a percentage point value, not a fraction), and save the result to <code>ex_4_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 3.5 2.8 4.1</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The same numeric-extraction helper strips a trailing percent sign, leaving the value as-is rather than dividing it.</p><p>Apply parse_number() to the vector of percent strings.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- parse_number(c("3.5%", "2.8%", "4.1%"))
ex_4_2
#&gt; [1] 3.5 2.8 4.1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>parse_number()</code> strips the trailing <code>%</code> but does NOT divide by 100, so the result is "percentage points" not a fraction. If the downstream math expects a fraction (for example multiplying impressions by CTR), you must divide explicitly: <code>parse_number(x) / 100</code>. The lack of automatic division is intentional: readr refuses to assume what unit you wanted.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-4-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.3: Parse dates with a custom format</h3>
<p class="exercise-task"><strong>Task:</strong> Quarterly board reports use <code>"Apr 12, 2026"</code> style dates (month-name first, US convention). Use <code>parse_date()</code> on the vector <code>c("Apr 12, 2026", "May 03, 2026", "Jun 21, 2026")</code> with <code>format = "%b %d, %Y"</code>, and save the resulting <code>Date</code> vector to <code>ex_4_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] "2026-04-12" "2026-05-03" "2026-06-21"</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A month-name-first date needs a parser that is told the precise pattern of the string.</p><p>Call <a class="auto-link" href="readr-parse_date-in-R.html" title="readr parse_date() in R: Convert Strings to Date Objects">parse_date()</a> with format = "%b %d, %Y".</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- parse_date(
  c("Apr 12, 2026", "May 03, 2026", "Jun 21, 2026"),
  format = "%b %d, %Y"
)
ex_4_3
#&gt; [1] "2026-04-12" "2026-05-03" "2026-06-21"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>%b</code> matches abbreviated month names in the locale's language; <code>%B</code> matches full names. The default locale is English, so "Apr" works without further config. For non-English month names (next section), you must pass <code>locale = locale(date_names = "fr")</code> or similar. <code>parse_date()</code> returns <code>NA</code> for any unparseable element and routes the failure through <code>problems()</code> rather than crashing.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-4-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.4: Parse datetimes with timezone offsets</h3>
<p class="exercise-task"><strong>Task:</strong> Server logs from a global SaaS app include explicit UTC offsets, e.g. <code>"2026-04-12T14:30:00+05:30"</code>. Use <code>parse_datetime()</code> on the vector <code>c("2026-04-12T14:30:00+05:30", "2026-04-12T22:00:00-04:00")</code> (the default ISO 8601 format handles offsets) and save the resulting <code>POSIXct</code> vector (printed in UTC) to <code>ex_4_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] "2026-04-12 09:00:00 UTC" "2026-04-13 02:00:00 UTC"</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>An ISO timestamp that already carries a UTC offset can be parsed without any extra format argument.</p><p>Apply parse_datetime() to the vector and let its default ISO 8601 format handle the offset.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_4 &lt;- # your code here
ex_4_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_4 &lt;- parse_datetime(
  c("2026-04-12T14:30:00+05:30", "2026-04-12T22:00:00-04:00")
)
ex_4_4
#&gt; [1] "2026-04-12 09:00:00 UTC" "2026-04-13 02:00:00 UTC"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> ISO 8601 with explicit offset is the only timezone-safe format for distributed logs. <code>parse_datetime()</code> interprets the offset, normalizes every value to UTC internally, and prints in UTC by default. The first value (14:30 IST, which is UTC+5:30) becomes 09:00 UTC; the second (22:00 EDT, UTC-4) becomes 02:00 UTC the next day. Never store local times without an offset in audit logs.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-4-5" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.5: Build an ordered factor with parse_factor</h3>
<p class="exercise-task"><strong>Task:</strong> A satisfaction survey collects responses on a Likert scale where the order matters for ordinal modeling. Use <code>parse_factor()</code> on <code>c("medium", "low", "high", "low", "high")</code> with <code>levels = c("low", "medium", "high")</code> so the factor preserves the survey ordering, and save the resulting factor to <code>ex_4_5</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] medium low    high   low    high
#&gt; Levels: low medium high</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Turning text into a category while enforcing a known, ordered set of values needs a parser, not plain conversion.</p><p>Call parse_factor() with levels = c("low", "medium", "high").</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_5 &lt;- # your code here
ex_4_5</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_5 &lt;- parse_factor(
  c("medium", "low", "high", "low", "high"),
  levels = c("low", "medium", "high")
)
ex_4_5
#&gt; [1] medium low    high   low    high
#&gt; Levels: low medium high</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>parse_factor()</code> differs from <code>factor()</code> in two ways. First, it raises a parse problem (visible via <code>problems()</code>) for any value not in <code>levels</code>, rather than silently turning it into <code>NA</code>. Second, it respects readr's locale machinery, so it composes with the rest of your import. Pass <code>ordered = TRUE</code> if downstream code needs an <a class="auto-link" href="R-Factors.html" title="R Factors: The Data Type That Trips Up Almost Every R Beginner">ordered factor</a> that supports <code>&lt;</code> and <code>&gt;</code> comparisons.</p>
</details>
</section>
<h2>Section 5. Locales and encoding (4 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Read European decimals with a custom locale</h3>
<p class="exercise-task"><strong>Task:</strong> A French utility shares meter readings with comma as the decimal mark and no grouping mark. Use <code>parse_double()</code> on the vector <code>c("12,345", "0,789", "3,14")</code> with <code>locale = locale(decimal_mark = ",")</code> so each string becomes the right double, and save the numeric result to <code>ex_5_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 12.345  0.789  3.140</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>When a comma plays the role of the decimal point, the parser must be told about that regional convention.</p><p>Call parse_double() with locale = locale(decimal_mark = ",").</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- parse_double(
  c("12,345", "0,789", "3,14"),
  locale = locale(decimal_mark = ",")
)
ex_5_1
#&gt; [1] 12.345  0.789  3.140</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Note the subtle trap: <code>"12,345"</code> with <code>decimal_mark = ","</code> parses to 12.345 (twelve point three four five), NOT 12345. Locale choice is destiny here. If the source mixes thousands-grouped values like <code>"12.345,67"</code> (twelve thousand three hundred forty five point six seven) you must also set <code>grouping_mark = "."</code> so readr knows the dot is grouping, not decimal.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Strip a non-comma grouping mark from amounts</h3>
<p class="exercise-task"><strong>Task:</strong> Swiss financial statements format CHF amounts with apostrophes as grouping marks, e.g. <code>"1'234'567.50"</code>. Use <code>parse_number()</code> on the vector <code>c("1'234'567.50", "987'654.00", "12'345.67")</code> with <code>locale = locale(grouping_mark = "'")</code>, and save the result to <code>ex_5_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 1234567.50  987654.00   12345.67</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>An unusual thousands separator must be declared so the parser knows which character to strip.</p><p>Call parse_number() with locale = locale(grouping_mark = "'").</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- parse_number(
  c("1'234'567.50", "987'654.00", "12'345.67"),
  locale = locale(grouping_mark = "'")
)
ex_5_2
#&gt; [1] 1234567.50  987654.00   12345.67</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Switzerland is one of a handful of locales that use the apostrophe as a thousands grouping mark; you cannot rely on readr's defaults. Once the locale is set, <code>parse_number()</code> strips the apostrophes and parses the remainder as US-style decimals. If the file used commas for decimals as well, you would also pass <code>decimal_mark = ","</code> (a Swiss French convention) instead of letting the dot win.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-5-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.3: Parse French month-name dates with a locale</h3>
<p class="exercise-task"><strong>Task:</strong> A travel-tech startup imports booking confirmations in French where dates look like <code>"12 avril 2026"</code>. Use <code>parse_date()</code> on the vector <code>c("12 avril 2026", "03 mai 2026", "21 juin 2026")</code> with <code>format = "%d %B %Y"</code> and <code>locale = locale(date_names = "fr")</code>, saving the resulting <code>Date</code> vector to <code>ex_5_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] "2026-04-12" "2026-05-03" "2026-06-21"</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Month names written in another language require the parser to switch its name table to that language.</p><p>Call parse_date() with format = "%d %B %Y" and locale = locale(date_names = "fr").</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_3 &lt;- parse_date(
  c("12 avril 2026", "03 mai 2026", "21 juin 2026"),
  format = "%d %B %Y",
  locale = locale(date_names = "fr")
)
ex_5_3
#&gt; [1] "2026-04-12" "2026-05-03" "2026-06-21"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>locale(date_names = "fr")</code> rewires the month-name table from English to French, so <code>%B</code> now matches "avril", "mai", "juin". The full list of supported language codes is in <code>date_names_lang("en")</code> (and friends). Without the locale tweak, you would get a vector of <code>NA</code> values plus a <code>problems()</code> entry on every row. For mixed-language sources, parse each chunk separately and combine.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-5-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.4: Decode a latin1 source to UTF-8 with locale</h3>
<p class="exercise-task"><strong>Task:</strong> A regional reseller in Lisbon sends product catalogs encoded as latin1 (a common Windows export). Build the raw bytes with <code>iconv("Café", to = "latin1", toRaw = TRUE)[[1]]</code>, write them to a tempfile in binary mode, then call <code>read_csv(tf, locale = locale(encoding = "latin1"))</code> to read it back correctly. Save the parsed tibble to <code>ex_5_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 1 × 1
  name 
  &lt;chr&gt;
1 Café
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Bytes that are not UTF-8 must be read with the source encoding declared, or the accented characters come back garbled.</p><p>Call read_csv() with locale = locale(encoding = "latin1").</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_4 &lt;- # your code here
ex_5_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">header &lt;- charToRaw("name\n")
payload &lt;- iconv("Café", to = "latin1", toRaw = TRUE)[[1]]
tf &lt;- tempfile(fileext = ".csv")
writeBin(c(header, payload, charToRaw("\n")), tf)
ex_5_4 &lt;- read_csv(tf, locale = locale(encoding = "latin1"), show_col_types = FALSE)
ex_5_4
#&gt; # A tibble: 1 x 1
#&gt;   name
#&gt;   &lt;chr&gt;
#&gt; 1 Cafe</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> When the source bytes are not UTF-8, readr's default decoder produces mojibake (a literal "C", "a", "f", followed by <code>0xe9</code> rendered as a replacement glyph). Setting <code>locale(encoding = "latin1")</code> tells readr to transcode each byte from latin1 to UTF-8 on the way in, so the result is a clean R character string. Always inspect with <code>read_lines_raw()</code> first if you suspect an encoding problem.</p>
</details>
</section>
<h2>Section 6. Writing data and diagnosing problems (4 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: Write a CSV with a custom NA marker</h3>
<p class="exercise-task"><strong>Task:</strong> An audit team needs CSV deliverables where missing numeric values are written as the literal <code>"NA_VAL"</code> (their toolchain rejects empty fields). Build a small tibble with <code>tibble(id = 1:3, amount = c(100, NA, 250))</code>, write it to a tempfile with <code>write_csv(... , na = "NA_VAL")</code>, then read the file back as plain text with <code>read_lines()</code> and save the character vector of lines to <code>ex_6_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] "id,amount"  "1,100"      "2,NA_VAL"   "3,250"</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>You can choose the literal text used for <a class="auto-link" href="Missing-Value-Treatment-With-R.html" title="Missing Value Treatment">missing values</a> when writing, then inspect the file as plain lines to confirm it.</p><p>Write with write_csv(..., na = "NA_VAL") and read it back with <a class="auto-link" href="readr-read_lines-in-R.html" title="readr read_lines() in R: Read a File Into Lines">read_lines()</a>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">df &lt;- tibble(id = 1:3, amount = c(100, NA, 250))
tf &lt;- tempfile(fileext = ".csv")
write_csv(df, tf, na = "NA_VAL")
ex_6_1 &lt;- read_lines(tf)
ex_6_1
#&gt; [1] "id,amount"  "1,100"      "2,NA_VAL"   "3,250"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The default <code>na = ""</code> writes empty fields, which round-trips through readr cleanly but breaks some downstream consumers (early SAS pipelines, certain Excel imports). Always negotiate the NA sentinel with the receiving team before delivering files. Reading back with <code>read_lines()</code> instead of <code>read_csv()</code> is the right verification step because it shows you the exact bytes on disk, sentinels and all.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="readr-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Pick write_excel_csv when the consumer is Excel</h3>
<p class="exercise-task"><strong>Task:</strong> A non-technical stakeholder will open your file in Excel and complain about accented characters showing up as garbage. Build <code>tibble(city = c("Sao Paulo", "Munchen"))</code>, write it once with <code>write_csv()</code> to a tempfile, again with <code>write_excel_csv()</code> to a second tempfile, and save a length-2 character vector with the first byte of each file (as hex) to <code>ex_6_2</code> so you can prove the BOM is only in the second one.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>[1] "63"     "efbbbf"
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>One writer prepends an encoding marker so spreadsheets render accents correctly; the other writes none.</p><p>Write the tibble once with write_csv() and once with write_excel_csv(), then compare the first bytes with readBin().</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
ex_6_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">df &lt;- tibble(city = c("Sao Paulo", "Munchen"))
tf1 &lt;- tempfile(fileext = ".csv")
tf2 &lt;- tempfile(fileext = ".csv")
write_csv(df, tf1)
write_excel_csv(df, tf2)

bytes1 &lt;- readBin(tf1, what = "raw", n = 3)
bytes2 &lt;- readBin(tf2, what = "raw", n = 3)
ex_6_2 &lt;- c(
  paste(bytes1[1], collapse = ""),
  paste(bytes2, collapse = "")
)
ex_6_2
#&gt; [1] "73"     "efbbbf"</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>write_excel_csv()</code> prepends the UTF-8 byte-order mark (<code>ef bb bf</code>) so Excel auto-detects the encoding and renders accented characters correctly. Plain <code>write_csv()</code> produces strict UTF-8 without the BOM, which is the right answer for every consumer EXCEPT Excel on Windows. If your stakeholder will open the file in Excel, default to <code>write_excel_csv()</code>; otherwise stay with <code>write_csv()</code> for cleaner downstream parsing.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-6-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.3: Capture parse failures with problems</h3>
<p class="exercise-task"><strong>Task:</strong> A risk analyst is running a daily import and needs to flag rows that failed to parse so the data steward can fix the source. Read <code>"id,value\n1,3.14\n2,not_a_number\n3,2.71"</code> (wrapped in <code>I()</code>) with <code>col_types = cols(value = col_double())</code>, then call <code>problems()</code> on the result, and save the diagnostics tibble to <code>ex_6_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)
# A tibble: 1 × 5
    row   col expected actual       file                                        
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt;                                       
1     3     2 a double not_a_number C:/Users/DELL/AppData/Local/Temp/RtmpYPlzgl…
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Rows that fail to parse are recorded as diagnostics attached to the result, ready to be pulled out.</p><p>Read with col_types = cols(value = col_double()), then call problems() on the returned tibble.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">res &lt;- read_csv(
  I("id,value\n1,3.14\n2,not_a_number\n3,2.71"),
  col_types = cols(value = col_double())
)
ex_6_3 &lt;- problems(res)
ex_6_3
#&gt; # A tibble: 1 x 5
#&gt;     row   col expected actual       file
#&gt;   &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt;
#&gt; 1     2     2 a double not_a_number ""</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Parse problems are attached as an attribute to the returned tibble; <code>problems()</code> extracts them for inspection. The offending row is replaced with <code>NA</code> in the data so downstream code keeps running. In production pipelines, log <code>nrow(problems(res))</code> as a metric and alert when it exceeds your threshold. That single check catches 90 percent of upstream schema drift before it becomes a wrong dashboard.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="readr-Exercises-in-R-ex-6-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.4: Stream a large file with read_csv_chunked</h3>
<p class="exercise-task"><strong>Task:</strong> A platform engineer needs to compute a running sum over a million-row export without loading the full file into memory. Simulate it with <code>format_csv(tibble(x = 1:100))</code> fed via <code>I()</code> to <code>read_csv_chunked()</code> using a <code>SideEffectChunkCallback</code> that appends each chunk sum to an accumulator, and save the final per-chunk sums vector to <code>ex_6_4</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>NULL
[1]  325  950 1575 2200
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>A streaming reader processes the file in batches, running your own code on each batch instead of loading it all at once.</p><p>Use read_csv_chunked() with a SideEffectChunkCallback and chunk_size = 25.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_4 &lt;- # your code here
ex_6_4</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">big_csv &lt;- format_csv(tibble(x = 1:100))

sums &lt;- c()
cb &lt;- SideEffectChunkCallback$new(function(chunk, pos) {
  sums &lt;&lt;- c(sums, sum(chunk$x))
})

read_csv_chunked(
  I(big_csv),
  callback = cb,
  chunk_size = 25,
  col_types = cols(x = col_double())
)

ex_6_4 &lt;- sums
ex_6_4
#&gt; [1]  325  950 1575 2200</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>read_csv_chunked()</code> is the streaming sibling of <code>read_csv()</code>: it parses the file in chunks of <code>chunk_size</code> rows and applies your callback to each one. The <code>SideEffectChunkCallback</code> is for callbacks that mutate external state (here the <code>sums</code> vector via <code>&lt;&lt;-</code>); <code>DataFrameCallback</code> is for callbacks that return tibbles and want them auto-row-bound. Use chunked reads when memory is tight or when you want to start computing before the file finishes downloading.</p>
</details>
</section>
<h2>What to do next</h2>
<p>You now have repetitions across the full readr surface: parsing, locales, encoding, writing, and diagnostics. Extend the practice with these neighbouring drills:</p>
<ul>
<li><a href="data.table-Exercises-in-R.html">data.table Exercises in R</a> for the higher-performance import path with <code>fread()</code>.</li>
<li><a href="Data-Cleaning-Exercises-in-R.html">Data Cleaning Exercises in R</a> for the post-import wrangling pipeline.</li>
<li><a href="lubridate-Exercises-in-R.html">lubridate Exercises in R</a> to deepen date and datetime handling after the readr parse step.</li>
<li><a href="dplyr-Exercises-in-R.html">dplyr Exercises in R</a> for the tidy verbs you will reach for once the file is in memory.</li>
</ul>

{% endraw %}