---
title: "SEM Exercises in R: 16 lavaan Practice Problems"
description: "16 structural equation modeling exercises in R with worked lavaan solutions: path models, CFA, fit indices, mediation, bootstrap, multi-group invariance, and ordered-categorical SEM."
keywords: "SEM exercises in R, lavaan exercises, lavaan practice, structural equation modeling exercises, lavaan CFA, lavaan mediation, lavaan bootstrap, measurement invariance R, lavaan WLSMV, modification indices"
mathjax: true
webr: true
curriculum_id: "E8.4"
post_type: "EX"
auto_link_terms: "SEM exercises in R|lavaan exercises|lavaan practice|structural equation modeling exercises|lavaan path model|lavaan CFA|SEM practice problems"
auto_link_case_sensitive: false
sidebar_title: "SEM Exercises (16 problems)"
sidebar_order: "143"
fr_parent: "CFA-and-Structural-Equation-Modeling-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>SEM Exercises in R: 16 lavaan Practice Problems</h1>

<p class="lead">These 16 structural equation modeling exercises in R take you through the full <code>lavaan</code> workflow on bundled datasets: writing model syntax, fitting CFA and full SEMs, reading fit indices, interpreting <a class="auto-link" href="CFA-and-Structural-Equation-Modeling-in-R.html" title="SEM and CFA in R With lavaan: From Path Diagram to Fit Statistics">modification indices</a>, estimating indirect effects with bootstrap intervals, testing measurement invariance across groups, and handling ordered-categorical indicators. Solutions are hidden behind a click and explained.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="40" data-exercises="16" data-xp="240"></div>

<h2>How are these problems structured?</h2>

<p>Every problem gives you a task, the exact output your solution must reproduce, and a difficulty tag. You write code in the Your turn block, then expand the solution to verify your approach and read why it works. Code blocks share state across the page like notebook cells, so you only need to load packages once.</p>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(lavaan)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p>The two datasets used throughout are bundled with <code>lavaan</code> itself: <code>PoliticalDemocracy</code> (75 nations, eight indicators of industrialization and political democracy in 1960 and 1965) and <code>HolzingerSwineford1939</code> (301 schoolchildren, nine cognitive tests grouped into visual, textual, and speed factors).</p>

<h2>Section 1. Specifying and fitting your first lavaan model (3 problems)</h2>

<h3>Exercise 1.1: Fit a two-equation path model on PoliticalDemocracy</h3>

<p><strong>Task:</strong> A political scientist wants to confirm that 1960 industrialization (<code>x1</code>) predicts 1960 democracy (<code>y1</code>), which in turn predicts 1965 democracy (<code>y5</code>). Use <code>lavaan::sem()</code> to fit a two-equation path model with <code>y1</code> regressed on <code>x1</code>, and <code>y5</code> regressed on <code>y1</code>. Save the fitted object to <code>ex_1_1</code> and print <code>summary(ex_1_1)</code> so the parameter estimates appear.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; lavaan 0.6 ended normally after 1 iterations
#&gt;   Estimator                                         ML
#&gt;   Number of observations                            75
#&gt; Model Test User Model:
#&gt;   Test statistic                                 0.000
#&gt;   Degrees of freedom                                 0
#&gt; Regressions:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)
#&gt;   y1 ~
#&gt;     x1                1.270    0.131    9.677    0.000
#&gt;   y5 ~
#&gt;     y1                0.838    0.046   18.108    0.000</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
summary(ex_1_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_1_1 &lt;- '
  y1 ~ x1
  y5 ~ y1
'
ex_1_1 &lt;- sem(mod_1_1, data = PoliticalDemocracy)
summary(ex_1_1)
#&gt; lavaan 0.6 ended normally after 1 iterations
#&gt;   Number of observations                            75
#&gt; Model Test User Model:
#&gt;   Test statistic                                 0.000
#&gt;   Degrees of freedom                                 0</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The <code>~</code> operator means "regressed on" in lavaan syntax, exactly as in base R formulas. With two equations and three observed variables, the model is just-identified (df = 0), so the chi-square is forced to zero and no fit can be assessed. Just-identified path models always reproduce the covariances perfectly, which is why interesting SEMs add latent variables or constraints to push degrees of freedom above zero.</p>

</details>

<h3>Exercise 1.2: Specify a three-indicator measurement model with the =~ operator</h3>

<p><strong>Task:</strong> Define a one-factor measurement model where a latent <code>visual</code> factor is measured by three indicators (<code>x1</code>, <code>x2</code>, <code>x3</code>) from <code>HolzingerSwineford1939</code>. Use <code>cfa()</code> to fit it and save the result to <code>ex_1_2</code>. The <code>=~</code> operator reads as "is measured by" and tells lavaan to estimate <a class="auto-link" href="Exploratory-Factor-Analysis-in-R.html" title="Exploratory Factor Analysis in R: Find Latent Constructs in Your Correlation Matrix">factor loadings</a>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; lavaan 0.6 ended normally after 19 iterations
#&gt;   Number of observations                           301
#&gt; Model Test User Model:
#&gt;   Test statistic                                 0.000
#&gt;   Degrees of freedom                                 0
#&gt; Latent Variables:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)
#&gt;   visual =~
#&gt;     x1                1.000
#&gt;     x2                0.554    0.100    5.554    0.000
#&gt;     x3                0.729    0.109    6.685    0.000</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
summary(ex_1_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_1_2 &lt;- 'visual =~ x1 + x2 + x3'
ex_1_2 &lt;- cfa(mod_1_2, data = HolzingerSwineford1939)
summary(ex_1_2)
#&gt; Number of observations                           301
#&gt; Latent Variables:
#&gt;   visual =~
#&gt;     x1                1.000
#&gt;     x2                0.554    0.100    5.554    0.000
#&gt;     x3                0.729    0.109    6.685    0.000</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The first indicator's loading is fixed to 1 by default ("marker variable" identification), which gives the latent factor a scale. Without this constraint the factor would be unidentified because you can rescale the latent variable and absorb the change into the loadings. With three indicators the model has 6 unique covariances and 6 free parameters (2 loadings + 3 residuals + 1 factor variance), so df = 0 and fit is perfect by construction.</p>

</details>

<h3>Exercise 1.3: Free a residual covariance with the ~~ operator</h3>

<p><strong>Task:</strong> Returning to the three-indicator <code>visual</code> factor on <code>HolzingerSwineford1939</code>, suppose <code>x1</code> and <code>x3</code> share a residual correlation because both are timed tasks. Modify the model from Exercise 1.2 to also estimate <code>x1 ~~ x3</code> (free residual covariance) and save the refit to <code>ex_1_3</code>. Use <code>parameterEstimates(ex_1_3)</code> to confirm the new parameter.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # The new row in parameterEstimates(ex_1_3):
#&gt;   lhs op rhs   est    se      z pvalue
#&gt;    x1 ~~  x3 0.297 0.198  1.500 0.134</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
parameterEstimates(ex_1_3)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_1_3 &lt;- '
  visual =~ x1 + x2 + x3
  x1 ~~ x3
'
ex_1_3 &lt;- cfa(mod_1_3, data = HolzingerSwineford1939)
parameterEstimates(ex_1_3)
#&gt;      lhs op    rhs   est    se      z pvalue
#&gt; 1 visual =~     x1 1.000 0.000     NA     NA
#&gt; 2 visual =~     x2 0.554 0.100  5.554  0.000
#&gt; 3 visual =~     x3 0.729 0.109  6.685  0.000
#&gt; 4     x1 ~~     x1 0.553 0.119  4.652  0.000
#&gt; 5     x1 ~~     x3 0.297 0.198  1.500  0.134</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The <code>~~</code> operator covers both variances (<code>x1 ~~ x1</code>) and covariances (<code>x1 ~~ x3</code>). lavaan estimates every indicator's residual variance automatically, so you only write <code>~~</code> lines when you want to free an off-diagonal residual covariance the default model fixed to zero. With this new parameter the model becomes unidentified for a three-indicator factor (df would go negative), so in practice you would need either four indicators or an equality constraint elsewhere to test the residual covariance.</p>

</details>

<h2>Section 2. Confirmatory factor analysis (3 problems)</h2>

<h3>Exercise 2.1: Fit a classic three-factor CFA on HolzingerSwineford1939</h3>

<p><strong>Task:</strong> The canonical Holzinger-Swineford CFA defines three correlated factors: <code>visual</code> measured by <code>x1, x2, x3</code>; <code>textual</code> by <code>x4, x5, x6</code>; and <code>speed</code> by <code>x7, x8, x9</code>. Specify this model, fit it with <code>cfa()</code>, and save the fitted object to <code>ex_2_1</code>. Print only the fit statistics line of <code>summary(ex_2_1, fit.measures = TRUE)</code> (the Test User Model block).</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; lavaan 0.6 ended normally after 35 iterations
#&gt;   Number of observations                           301
#&gt; Model Test User Model:
#&gt;   Test statistic                                85.306
#&gt;   Degrees of freedom                                24
#&gt;   P-value (Chi-square)                           0.000</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
summary(ex_2_1, fit.measures = TRUE)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_2_1 &lt;- '
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
'
ex_2_1 &lt;- cfa(mod_2_1, data = HolzingerSwineford1939)
summary(ex_2_1, fit.measures = TRUE)
#&gt; Test statistic                                85.306
#&gt; Degrees of freedom                                24
#&gt; P-value (Chi-square)                           0.000</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> With three factors and three indicators each, lavaan estimates 6 free factor loadings (one per factor is fixed at 1), 9 residual variances, 3 factor variances, and 3 factor covariances, for 21 parameters against 45 unique covariances, giving df = 24. The chi-square is significant, which technically rejects exact fit, but with n = 301 the test is over-powered. That is why we look at CFI, TLI, RMSEA, and SRMR before judging the model, which Exercise 3.1 covers.</p>

</details>

<h3>Exercise 2.2: Extract standardized loadings with the std.all column</h3>

<p><strong>Task:</strong> Using <code>ex_2_1</code> from the previous exercise, pull only the factor loadings (rows where <code>op == &quot;=~&quot;</code>) with their standardized values (<code>std.all</code>). Save the resulting data frame to <code>ex_2_2</code>. Standardized loadings are easier to interpret than raw because all variables are on the same scale.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;      lhs op rhs   est std.all
#&gt; 1 visual =~  x1 1.000   0.772
#&gt; 2 visual =~  x2 0.554   0.424
#&gt; 3 visual =~  x3 0.729   0.581
#&gt; 4 textual =~ x4 1.000   0.852
#&gt; 5 textual =~ x5 1.113   0.855
#&gt; 6 textual =~ x6 0.926   0.838
#&gt; 7 speed =~  x7 1.000   0.570
#&gt; 8 speed =~  x8 1.180   0.723
#&gt; 9 speed =~  x9 1.082   0.665</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pe &lt;- parameterEstimates(ex_2_1, standardized = TRUE)
ex_2_2 &lt;- pe[pe$op == &quot;=~&quot;, c(&quot;lhs&quot;, &quot;op&quot;, &quot;rhs&quot;, &quot;est&quot;, &quot;std.all&quot;)]
ex_2_2
#&gt;       lhs op rhs   est std.all
#&gt; 1  visual =~  x1 1.000   0.772
#&gt; 2  visual =~  x2 0.554   0.424
#&gt; 3  visual =~  x3 0.729   0.581
#&gt; ...</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>parameterEstimates()</code> with <code>standardized = TRUE</code> adds three new columns: <code>std.lv</code> (latent variable standardized), <code>std.all</code> (both latent and observed standardized), and <code>std.nox</code> (everything except exogenous covariates standardized). <code>std.all</code> is the right column for reading loadings as correlations between indicator and factor. Anything above ~.5 is a reasonable loading; values below ~.3 suggest the indicator is barely tapping the factor.</p>

</details>

<h3>Exercise 2.3: Inspect estimates with the standardizedSolution helper</h3>

<p><strong>Task:</strong> Instead of slicing <code>parameterEstimates()</code> by hand, use <code>standardizedSolution(ex_2_1)</code> to get a clean table of standardized estimates with <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence intervals</a>. <a class="auto-link" href="Reduce-Filter-Map-in-R.html" title="Reduce(), Filter(), Map() in Base R: Functional Trifecta Explained">Filter</a> the result to only the factor covariance rows (where both sides are latent factors and <code>op == &quot;~~&quot;</code>) and save it to <code>ex_2_3</code>. This gives you the inter-factor correlations.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;       lhs op     rhs est.std    se      z pvalue ci.lower ci.upper
#&gt; 1  visual ~~  textual   0.459 0.064  7.189  0.000    0.334    0.585
#&gt; 2  visual ~~    speed   0.471 0.073  6.461  0.000    0.328    0.613
#&gt; 3 textual ~~    speed   0.283 0.069  4.117  0.000    0.149    0.418</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ss &lt;- standardizedSolution(ex_2_1)
latents &lt;- c(&quot;visual&quot;, &quot;textual&quot;, &quot;speed&quot;)
ex_2_3 &lt;- ss[ss$op == &quot;~~&quot; &amp; ss$lhs %in% latents &amp; ss$rhs %in% latents &amp; ss$lhs != ss$rhs, ]
ex_2_3
#&gt;       lhs op     rhs est.std    se      z pvalue ci.lower ci.upper
#&gt; 1  visual ~~  textual   0.459 0.064  7.189  0.000    0.334    0.585
#&gt; 2  visual ~~    speed   0.471 0.073  6.461  0.000    0.328    0.613
#&gt; 3 textual ~~    speed   0.283 0.069  4.117  0.000    0.149    0.418</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>standardizedSolution()</code> reports the standardized estimates directly with proper standard errors via the <a class="auto-link" href="Asymptotic-Theory-in-R.html" title="Asymptotic Theory in R: Consistency, Asymptotic Normality & Delta Method">delta method</a>, plus 95% confidence intervals out of the box. The factor correlations here (.46, .47, .28) show that visual and textual share moderate variance, and so do visual and speed, but textual and speed are weaker. None hit .85, so discriminant validity is supported and the three-factor structure makes sense.</p>

</details>

<h2>Section 3. Model fit and respecification (3 problems)</h2>

<h3>Exercise 3.1: Pull CFI, TLI, RMSEA, and SRMR from fitMeasures</h3>

<p><strong>Task:</strong> Global fit of a CFA is judged by a handful of indices. Pull just <code>cfi</code>, <code>tli</code>, <code>rmsea</code>, and <code>srmr</code> from <code>ex_2_1</code> using <code>fitMeasures()</code> with the index names passed as a character vector. Save the named numeric to <code>ex_3_1</code> and round it to three decimals. Common thresholds for acceptable fit are CFI/TLI > .90, RMSEA < .08, SRMR < .08.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;   cfi   tli rmsea  srmr
#&gt; 0.931 0.896 0.092 0.065</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- round(fitMeasures(ex_2_1, c(&quot;cfi&quot;, &quot;tli&quot;, &quot;rmsea&quot;, &quot;srmr&quot;)), 3)
ex_3_1
#&gt;   cfi   tli rmsea  srmr
#&gt; 0.931 0.896 0.092 0.065</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> CFI = .93 and SRMR = .065 look fine, but RMSEA = .092 sits just over the .08 mark and TLI = .896 is borderline. With n = 301 this often signals a minor misspecification that modification indices can reveal. Always report all four: any single index can be misleading because CFI penalizes badly fitting baseline models, RMSEA over-rejects small models, and SRMR is insensitive to misspecified factor variances.</p>

</details>

<h3>Exercise 3.2: Use modification indices to find a missing parameter</h3>

<p><strong>Task:</strong> The borderline RMSEA in <code>ex_2_1</code> suggests one or two paths are missing. Run <code>modindices(ex_2_1, sort. = TRUE)</code> and save the top 5 rows (largest <code>mi</code>) to <code>ex_3_2</code>. Each row tells you the expected drop in chi-square (<code>mi</code>) and the standardized parameter value (<code>sepc.all</code>) if the suggested path were freed.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;       lhs op rhs     mi     epc sepc.all
#&gt; 1  visual =~  x9 36.411   0.577    0.519
#&gt; 2      x7 ~~  x8 34.145   0.536    0.488
#&gt; 3      x8 ~~  x9 14.946  -0.423   -0.415
#&gt; 4  visual =~  x7  18.631  -0.422   -0.380
#&gt; 5     x2 ~~  x7   8.918   0.213    0.157</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mi &lt;- modindices(ex_2_1, sort. = TRUE)
ex_3_2 &lt;- head(mi[, c(&quot;lhs&quot;, &quot;op&quot;, &quot;rhs&quot;, &quot;mi&quot;, &quot;epc&quot;, &quot;sepc.all&quot;)], 5)
ex_3_2
#&gt;       lhs op rhs     mi     epc sepc.all
#&gt; 1  visual =~  x9 36.411   0.577    0.519
#&gt; 2      x7 ~~  x8 34.145   0.536    0.488</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The largest modification index points to a cross-loading of <code>x9</code> (speeded discrimination) on the <code>visual</code> factor, suggesting <code>x9</code> taps both visual and speed abilities. Freeing this single parameter would drop chi-square by about 36. Treat modification indices as hypothesis generators, not as automatic improvements: only free a parameter if it makes substantive theoretical sense. Chasing every large MI gives you a model that fits the sample perfectly and replicates poorly.</p>

</details>

<h3>Exercise 3.3: Compare nested models with anova</h3>

<p><strong>Task:</strong> Test whether freeing the <code>visual =~ x9</code> cross-loading from Exercise 3.2 produces a significantly better fit than the original three-factor model. Fit the augmented model, then call <code>anova(ex_2_1, ex_3_3_alt)</code> and save the comparison table to <code>ex_3_3</code>. A significant chi-square difference (p < .05) supports the more complex model.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Chi-Squared Difference Test
#&gt;             Df    AIC    BIC Chisq Chisq diff Df diff Pr(&gt;Chisq)
#&gt; ex_2_1      24   7517   7596 85.31
#&gt; ex_3_3_alt  23   7484   7567 50.34      34.97       1  3.34e-09</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_3_3 &lt;- '
  visual  =~ x1 + x2 + x3 + x9
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
'
ex_3_3_alt &lt;- cfa(mod_3_3, data = HolzingerSwineford1939)
ex_3_3 &lt;- anova(ex_2_1, ex_3_3_alt)
ex_3_3
#&gt; Chi-Squared Difference Test
#&gt;             Df Chisq Chisq diff Df diff Pr(&gt;Chisq)
#&gt; ex_2_1      24 85.31
#&gt; ex_3_3_alt  23 50.34      34.97       1  3.34e-09</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>anova()</code> on two lavaan fits runs the chi-square difference test for nested models. The drop of nearly 35 chi-square units on 1 df is highly significant (p < .001), and the AIC also drops, so the cross-loading buys real explanatory power. But before keeping it, ask whether a measurement that loads on both visual and speed factors is theoretically defensible. If it is not, the better move is to drop <code>x9</code> rather than chase the MI.</p>

</details>

<h2>Section 4. Full SEM with structural paths (3 problems)</h2>

<h3>Exercise 4.1: Fit the classic Bollen industrialization-democracy SEM</h3>

<p><strong>Task:</strong> The hallmark SEM on <code>PoliticalDemocracy</code> defines three latent variables: <code>ind60</code> (industrialization 1960) measured by <code>x1, x2, x3</code>; <code>dem60</code> (democracy 1960) measured by <code>y1, y2, y3, y4</code>; and <code>dem65</code> (democracy 1965) measured by <code>y5, y6, y7, y8</code>. The structural part regresses both <code>dem60</code> and <code>dem65</code> on <code>ind60</code>, plus <code>dem65</code> on <code>dem60</code>. Fit this model and save it to <code>ex_4_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Model Test User Model:
#&gt;   Test statistic                                72.462
#&gt;   Degrees of freedom                                51
#&gt;   P-value (Chi-square)                           0.026
#&gt; Regressions:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)
#&gt;   dem60 ~
#&gt;     ind60             1.483    0.399    3.715    0.000
#&gt;   dem65 ~
#&gt;     ind60             0.572    0.221    2.586    0.010
#&gt;     dem60             0.837    0.098    8.514    0.000</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
summary(ex_4_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_4_1 &lt;- '
  # Measurement
  ind60 =~ x1 + x2 + x3
  dem60 =~ y1 + y2 + y3 + y4
  dem65 =~ y5 + y6 + y7 + y8
  # Structural
  dem60 ~ ind60
  dem65 ~ ind60 + dem60
'
ex_4_1 &lt;- sem(mod_4_1, data = PoliticalDemocracy)
summary(ex_4_1)
#&gt; Test statistic                                72.462
#&gt; Degrees of freedom                                51
#&gt; Regressions:
#&gt;   dem65 ~
#&gt;     ind60             0.572    0.221    2.586    0.010
#&gt;     dem60             0.837    0.098    8.514    0.000</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> A full SEM has both a measurement model (the <code>=~</code> lines) and a structural model (the <code>~</code> lines). lavaan estimates them simultaneously, propagating measurement error into the structural coefficients. The chi-square is only marginally significant (p = .026), CFI typically exceeds .95 on this model, so fit is acceptable. The structural finding: industrialization in 1960 raises democracy in 1960, which then carries forward to 1965, with a small extra direct push from <code>ind60</code> to <code>dem65</code>.</p>

</details>

<h3>Exercise 4.2: Define an indirect effect with the := operator</h3>

<p><strong>Task:</strong> In the model from Exercise 4.1, the indirect effect of <code>ind60</code> on <code>dem65</code> flows through <code>dem60</code>. Label the two structural coefficients (<code>a</code> for <code>dem60 ~ ind60</code>, <code>b</code> for <code>dem65 ~ dem60</code>) and define <code>indirect := a * b</code> and <code>total := a * b + c</code> (where <code>c</code> is the direct path). Save the refit to <code>ex_4_2</code> and print the "Defined Parameters" block from <code>summary()</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Defined Parameters:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)
#&gt;     indirect          1.241    0.350    3.548    0.000
#&gt;     total             1.813    0.421    4.304    0.000</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
summary(ex_4_2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_4_2 &lt;- '
  ind60 =~ x1 + x2 + x3
  dem60 =~ y1 + y2 + y3 + y4
  dem65 =~ y5 + y6 + y7 + y8
  dem60 ~ a*ind60
  dem65 ~ c*ind60 + b*dem60
  indirect := a * b
  total    := a * b + c
'
ex_4_2 &lt;- sem(mod_4_2, data = PoliticalDemocracy)
summary(ex_4_2)
#&gt; Defined Parameters:
#&gt;     indirect          1.241    0.350    3.548    0.000
#&gt;     total             1.813    0.421    4.304    0.000</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Pre-multiplying a coefficient by a label (<code>a*ind60</code>) names that parameter so you can reuse it. The <code>:=</code> operator defines a new parameter as a function of the named ones, and lavaan applies the delta method to compute its standard error and z-test. The indirect effect (1.24) is highly significant, and it accounts for most of the total effect (1.81), confirming that 1960 democracy is the main channel through which industrialization shapes 1965 democracy.</p>

</details>

<h3>Exercise 4.3: Bootstrap a confidence interval for the indirect effect</h3>

<p><strong>Task:</strong> Delta-method standard errors assume the <a class="auto-link" href="Normal-t-F-and-Chi-Squared-Distributions-in-R.html" title="Normal, t, F, and Chi-Squared in R: Understand Each Distribution and When It Arises">sampling distribution</a> of the indirect effect is normal, which is wrong when sample size is small or the product is skewed. Refit <code>ex_4_2</code> with <code>se = &quot;bootstrap&quot;</code> and <code>bootstrap = 200</code> (use a small number so the page runs fast), then use <code>parameterEstimates(ex_4_3, boot.ci.type = &quot;perc&quot;)</code> to pull the <a class="auto-link" href="Bootstrap-Confidence-Intervals-in-R.html" title="Bootstrap CIs in R: Distribution-Free Confidence Intervals for Any Statistic">percentile bootstrap</a> CI for the <code>indirect</code> row. Save the row to <code>ex_4_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;        lhs op rhs    label   est    se     z pvalue ci.lower ci.upper
#&gt; 1 indirect :=  a*b indirect 1.241 0.317 3.913  0.000    0.711    1.916</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_4_3 &lt;- '
  ind60 =~ x1 + x2 + x3
  dem60 =~ y1 + y2 + y3 + y4
  dem65 =~ y5 + y6 + y7 + y8
  dem60 ~ a*ind60
  dem65 ~ c*ind60 + b*dem60
  indirect := a * b
'
fit_4_3 &lt;- sem(mod_4_3, data = PoliticalDemocracy, se = &quot;bootstrap&quot;, bootstrap = 200)
pe &lt;- parameterEstimates(fit_4_3, boot.ci.type = &quot;perc&quot;)
ex_4_3 &lt;- pe[pe$label == &quot;indirect&quot;, ]
ex_4_3
#&gt;        lhs op rhs    label   est    se     z pvalue ci.lower ci.upper
#&gt; 1 indirect :=  a*b indirect 1.241 0.317 3.913  0.000    0.711    1.916</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> For mediation analysis, bootstrap percentile or bias-corrected intervals are the standard reporting choice because the product of two normals is skewed. In a real analysis you would use <code>bootstrap = 5000</code> or more; 200 here is purely for runtime. The CI excludes zero, so the indirect effect is significant by a non-parametric criterion as well as by the delta method. Researchers writing for journals usually report <code>boot.ci.type = &quot;bca.simple&quot;</code> for bias-corrected bootstrap intervals.</p>

</details>

<h2>Section 5. Multi-group, invariance, and categorical SEM (3 problems)</h2>

<h3>Exercise 5.1: Fit the Holzinger-Swineford CFA separately for two schools</h3>

<p><strong>Task:</strong> The <code>HolzingerSwineford1939</code> dataset has a <code>school</code> variable with two levels: Pasteur and Grant-White. Fit the three-factor CFA from Exercise 2.1 separately to each school using the <code>group = &quot;school&quot;</code> argument and save the fit to <code>ex_5_1</code>. Inspect <code>summary(ex_5_1, fit.measures = TRUE)</code> to see per-group estimates and the combined fit.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Number of observations per group:
#&gt;   Pasteur                                          156
#&gt;   Grant-White                                      145
#&gt; Model Test User Model:
#&gt;   Test statistic                               115.851
#&gt;   Degrees of freedom                                48
#&gt;   P-value (Chi-square)                           0.000</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
summary(ex_5_1, fit.measures = TRUE)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_5_1 &lt;- '
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
'
ex_5_1 &lt;- cfa(mod_5_1, data = HolzingerSwineford1939, group = &quot;school&quot;)
summary(ex_5_1, fit.measures = TRUE)
#&gt; Number of observations per group:
#&gt;   Pasteur                                          156
#&gt;   Grant-White                                      145</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Passing <code>group =</code> tells lavaan to fit the model separately within each grouping level by default: every parameter is free in every group, so the df is roughly double the single-group model. This "configural" model is the baseline against which invariance constraints are tested. If the configural model itself fits poorly, the factor structure differs between groups and stronger invariance tests are not meaningful.</p>

</details>

<h3>Exercise 5.2: Test metric invariance by constraining loadings equal across groups</h3>

<p><strong>Task:</strong> To test whether factor loadings are equivalent across schools (metric invariance), refit the model with <code>group.equal = &quot;loadings&quot;</code>, then compare to <code>ex_5_1</code> with <code>anova()</code>. Save the comparison table to <code>ex_5_2</code>. A non-significant chi-square difference supports metric invariance, which is the prerequisite for comparing factor means or regression coefficients across groups.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; Chi-Squared Difference Test
#&gt;            Df    AIC    BIC Chisq Chisq diff Df diff Pr(&gt;Chisq)
#&gt; ex_5_1     48   7484   7715 115.9
#&gt; ex_5_2_alt 54   7483   7691 124.0       8.19       6     0.224</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_5_2 &lt;- '
  visual  =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9
'
ex_5_2_alt &lt;- cfa(mod_5_2, data = HolzingerSwineford1939,
                  group = &quot;school&quot;, group.equal = &quot;loadings&quot;)
ex_5_2 &lt;- anova(ex_5_1, ex_5_2_alt)
ex_5_2
#&gt; Chi-Squared Difference Test
#&gt;            Df Chisq Chisq diff Df diff Pr(&gt;Chisq)
#&gt; ex_5_1     48 115.9
#&gt; ex_5_2_alt 54 124.0       8.19       6     0.224</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Metric (weak) invariance means a one-unit change in the latent variable produces the same change in each indicator in every group. The test constrains 6 loadings equal across groups (2 free loadings per factor x 3 factors), so df grows by 6. The non-significant p value (.22) supports metric invariance. Next you would test scalar invariance with <code>group.equal = c(&quot;loadings&quot;, &quot;intercepts&quot;)</code> to check whether group mean differences in indicators are explained entirely by latent mean differences.</p>

</details>

<h3>Exercise 5.3: Fit an ordered-categorical CFA with the WLSMV estimator</h3>

<p><strong>Task:</strong> Treat indicators <code>y1</code> through <code>y4</code> from <code>PoliticalDemocracy</code> as ordered-categorical (they are 4-point democracy ratings). Fit a one-factor CFA on them with <code>ordered = c(&quot;y1&quot;,&quot;y2&quot;,&quot;y3&quot;,&quot;y4&quot;)</code>, which switches lavaan to the WLSMV estimator and tetrachoric/polychoric correlations. Save the fit to <code>ex_5_3</code> and print the <code>Estimator</code> line plus standardized loadings.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; lavaan 0.6 ended normally after 22 iterations
#&gt;   Estimator                                       DWLS
#&gt;   Number of observations                            75
#&gt; Latent Variables:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.all
#&gt;   dem60 =~
#&gt;     y1                1.000                              0.838
#&gt;     y2                1.302    0.171    7.617    0.000   0.866
#&gt;     y3                1.230    0.171    7.207    0.000   0.815
#&gt;     y4                1.305    0.158    8.275    0.000   0.876</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
summary(ex_5_3, standardized = TRUE)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">mod_5_3 &lt;- 'dem60 =~ y1 + y2 + y3 + y4'
ex_5_3 &lt;- cfa(mod_5_3,
              data = PoliticalDemocracy,
              ordered = c(&quot;y1&quot;, &quot;y2&quot;, &quot;y3&quot;, &quot;y4&quot;))
summary(ex_5_3, standardized = TRUE)
#&gt;   Estimator                                       DWLS
#&gt;   y1                1.000                              0.838
#&gt;   y2                1.302    0.171    7.617    0.000   0.866</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> When you declare indicators ordered, lavaan switches from maximum likelihood on the raw <a class="auto-link" href="Multivariate-Statistics-in-R.html" title="Multivariate Statistics in R: Distances, Mahalanobis, and Hotelling's T² Demystified">covariance matrix</a> to diagonally <a class="auto-link" href="Weighted-Least-Squares-in-R.html" title="Weighted Least Squares in R: Handle Heteroscedasticity with Weights">weighted least squares</a> (DWLS) on the polychoric <a class="auto-link" href="Correlation-Analysis-in-R.html" title="Correlation in R: Pearson vs Spearman vs Kendall — Compute, Test, and Visualise">correlation matrix</a>, with mean- and variance-adjusted test statistics (the WLSMV variant). This is the correct estimator for Likert-style data with five or fewer categories, where treating ordinal scores as continuous biases loadings downward and inflates chi-square. <a class="auto-link" href="Heteroscedasticity-in-R.html" title="Heteroscedasticity in R: Breusch-Pagan Test & Robust Standard Errors">Robust standard errors</a> are reported by default.</p>

</details>

<h2>Section 6. Reporting (1 problem)</h2>

<h3>Exercise 6.1: Build a publication-ready loadings table</h3>

<p><strong>Task:</strong> For the three-factor CFA fit <code>ex_2_1</code>, build a <a class="auto-link" href="Tidy-Data-in-R.html" title="Tidy Data: The One Rule That Makes R Code Readable, Reusable, and Debuggable">tidy data</a> frame with one row per indicator, columns <code>factor</code>, <code>indicator</code>, <code>loading</code> (raw <code>est</code>), <code>std_loading</code> (<code>std.all</code>), and <code>pvalue</code>, rounded to three decimals. Sort by factor and then by descending standardized loading. Save the table to <code>ex_6_1</code>. This is the format you would paste into a paper or report.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt;    factor indicator loading std_loading pvalue
#&gt; 1 textual        x5   1.113       0.855  0.000
#&gt; 2 textual        x4   1.000       0.852  0.000
#&gt; 3 textual        x6   0.926       0.838  0.000
#&gt; 4  visual        x1   1.000       0.772  0.000
#&gt; 5  visual        x3   0.729       0.581  0.000
#&gt; 6  visual        x2   0.554       0.424  0.000
#&gt; 7   speed        x8   1.180       0.723  0.000
#&gt; 8   speed        x9   1.082       0.665  0.000
#&gt; 9   speed        x7   1.000       0.570  0.000</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pe &lt;- parameterEstimates(ex_2_1, standardized = TRUE)
load_rows &lt;- pe[pe$op == &quot;=~&quot;, ]
ex_6_1 &lt;- data.frame(
  factor      = load_rows$lhs,
  indicator   = load_rows$rhs,
  loading     = round(load_rows$est, 3),
  std_loading = round(load_rows$std.all, 3),
  pvalue      = round(load_rows$pvalue, 3)
)
ex_6_1 &lt;- ex_6_1[order(ex_6_1$factor, -ex_6_1$std_loading), ]
ex_6_1
#&gt;    factor indicator loading std_loading pvalue
#&gt; 1 textual        x5   1.113       0.855  0.000
#&gt; 2 textual        x4   1.000       0.852  0.000</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>parameterEstimates(..., standardized = TRUE)</code> is the single source of truth for everything you would print: estimates, standard errors, p values, standardized values, and confidence intervals. Building a clean data frame from it puts you one <code>write.csv()</code> or <code>knitr::kable()</code> away from a paper-ready table. The marker loading (first indicator of each factor) shows NA for the p value in lavaan output because that parameter is fixed, but using <code>est</code> and <code>std.all</code> still gives you a populated cell.</p>

</details>

<h2>What to do next</h2>

<p>You have written lavaan syntax for path models, CFAs, and full SEMs; pulled fit indices; tested nested models; bootstrapped indirect effects; and handled multi-group and ordered-<a class="auto-link" href="Categorical-Data-in-R.html" title="Categorical Data in R: Frequency Tables, Crosstabs & Mosaic Plots">categorical data</a>. The next steps:</p>

<ul>

<li>Revisit the parent tutorial, <a href="CFA-and-Structural-Equation-Modeling-in-R.html">CFA and Structural Equation Modeling in R</a>, for theory and figure-by-figure walkthroughs of every model used above.</li>

<li>Practise the regression building blocks behind path models in the <a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a>.</li>

<li>Move into latent-variable mixture and growth models with the <a href="Factor-Analysis-Exercises-in-R.html">Factor Analysis Exercises in R</a>.</li>

<li>Use the <a href="ggplot2-Exercises-in-R.html">ggplot2 Exercises in R</a> to plot path diagrams and residual matrices for your fits.</li>

</ul>

{% endraw %}