---
title: "Survival Analysis Exercises in R: 18 Real-World Practice Problems"
description: "Eighteen survival analysis practice problems in R: Kaplan-Meier curves, log-rank tests, Cox proportional hazards, residual diagnostics, and parametric models."
keywords: "survival analysis R exercises, Kaplan-Meier R, Cox proportional hazards R, log-rank test R, survminer R, hazard ratio R"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "survival analysis exercises|Kaplan-Meier in R|Cox proportional hazards|log-rank test in R|hazard ratio in R"
auto_link_case_sensitive: false
sidebar_title: "Survival Analysis Exercises"
sidebar_order: "163"
fr_parent: "R-Tutorial.html"
---
{% raw %}
<!-- md2html:generated -->
<h1>Survival Analysis Exercises in R: 18 Real-World Practice Problems</h1>
<p class="lead">Eighteen practice problems on survival analysis in R: build Surv objects, fit Kaplan-Meier curves, run log-rank tests, fit and diagnose <a class="auto-link" href="R-for-Healthcare-Exercises.html" title="R for Healthcare Exercises: 20 Practice Problems">Cox proportional hazards</a> models, fit parametric AFT models, and predict patient-level survival probabilities. Every solution is hidden until you click; the <code>lung</code> dataset from the <code>survival</code> package is the backbone.</p>
<div class="engagement-header" data-difficulty="Mixed" data-exercises="18" data-time="45" data-xp="270"></div>
<div class="webr-container" data-block-title="Run this once before any exercise">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">library(survival)
library(survminer)
library(dplyr)
library(ggplot2)
library(broom)
library(flexsurv)
library(tibble)
data(lung)
lung &lt;- lung |&gt;
  mutate(
    sex     = factor(sex, levels = c(1, 2), labels = c("male", "female")),
    ph.ecog = factor(ph.ecog)
  )</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<h2>Section 1. Surv objects and Kaplan-Meier basics (3 problems)</h2>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-1-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.1: Build a Surv object from time and event columns</h3>
<p class="exercise-task"><strong>Task:</strong> Construct a survival response object from the <code>lung</code> dataset, treating <code>time</code> as the follow-up duration in days and <code>status</code> as the event indicator (1 = censored, 2 = died). Print the first ten entries so a <code>+</code> clearly marks censored observations. Save the response object to <code>ex_1_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;  [1]  306   455  1010+  210   883  1022+  310   361   218   166</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A survival response bundles the follow-up duration and the event flag into one object so downstream models can tell deaths apart from observations that were censored.</p><p>Call <code>Surv()</code> with <code>time = lung$time</code> and <code>event = lung$status</code>; it auto-detects the 1/2 coding, so no recoding is needed.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
head(ex_1_1, 10)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_1 &lt;- Surv(time = lung$time, event = lung$status)
head(ex_1_1, 10)
#&gt;  [1]  306   455  1010+  210   883  1022+  310   361   218   166</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>Surv()</code> packages two columns into a censored response that downstream functions like <code>survfit()</code> and <code>coxph()</code> understand. The <code>+</code> suffix marks right-censoring (the subject was still alive when last observed). The <code>status</code> column in <code>lung</code> is coded 1/2 (instead of 0/1), and <code>Surv()</code> auto-detects that convention: any non-1 value is treated as the event. If you ever load data where censoring is coded 0/1 with 1 = event, you can pass it directly without recoding.</p>
</details>
</section>
<section class="exercise" data-difficulty="beginner" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-1-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.2: Fit and summarize an overall Kaplan-Meier curve</h3>
<p class="exercise-task"><strong>Task:</strong> An oncology team treating advanced lung cancer patients wants a single overall survival curve for the cohort, ignoring all covariates. Fit a Kaplan-Meier estimator on the full <code>lung</code> cohort and print the <code>survfit</code> summary so the team can read off the number at risk, events, and median survival time. Save the model to <code>ex_1_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
#&gt; 
#&gt;        n events median 0.95LCL 0.95UCL
#&gt; [1,] 228    165    310     285     363</code></pre>
</div>
<p><strong>Difficulty:</strong> Beginner</p>
<div class="exercise-hints" hidden=""><p>A single overall cohort curve ignores every covariate, so the formula's right-hand side carries no predictors at all.</p><p>Use <code>survfit()</code> with the formula <code>Surv(time, status) ~ 1</code> and <code>data = lung</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_2 &lt;- survfit(Surv(time, status) ~ 1, data = lung)
ex_1_2
#&gt; Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
#&gt; 
#&gt;        n events median 0.95LCL 0.95UCL
#&gt; [1,] 228    165    310     285     363</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The right-hand side <code>~ 1</code> is the intercept-only formula, telling <code>survfit()</code> to fit one curve across the whole cohort. Median survival here means the smallest time at which the estimated survival probability falls to 0.5 or below. Of 228 patients, 165 died during follow-up; the rest are censored, mostly because the study ended before they died. The bounds 285 and 363 are the <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">95% confidence interval</a> on that median.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-1-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 1.3: Read off survival probabilities at fixed time points</h3>
<p class="exercise-task"><strong>Task:</strong> A trial statistician needs the estimated 6-month and 1-year survival probabilities (with 95% confidence intervals) from the overall <code>lung</code> Kaplan-Meier curve. Use <code>summary()</code> on the fitted survfit object at <code>times = c(182, 365)</code> and store the resulting summary object as <code>ex_1_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call: survfit(formula = Surv(time, status) ~ 1, data = lung)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
  182    157      66    0.708  0.0303        0.651        0.770
  365     65      55    0.409  0.0358        0.345        0.486
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>To pull the step-function estimate at specific horizons, you query the already-fitted curve rather than refitting anything.</p><p>Pass <code>times = c(182, 365)</code> to <code>summary()</code> on the fitted survfit object.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit &lt;- survfit(Surv(time, status) ~ 1, data = lung)
ex_1_3 &lt;- summary(fit, times = c(182, 365))
ex_1_3
#&gt; Call: survfit(formula = Surv(time, status) ~ 1, data = lung)
#&gt; 
#&gt;  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#&gt;   182    151      63    0.708  0.0303        0.651        0.770
#&gt;   365     65      71    0.409  0.0358        0.345        0.486</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>summary(fit, times = ...)</code> interpolates the step-function estimate at user-specified horizons, which is exactly the format clinical reports want. Roughly 71% of patients are alive at 6 months; that drops to 41% by 12 months. The "events" column is cumulative events up to that time, while "n.risk" is the number still at risk just after the time. The standard errors come from Greenwood's formula and are wider as the curve drops.</p>
</details>
</section>
<h2>Section 2. Group comparisons and log-rank tests (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-2-1" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 2.1: Fit Kaplan-Meier curves stratified by sex</h3>
<p class="exercise-task"><strong>Task:</strong> The same oncology team now wants to compare male versus female survival in <code>lung</code> to decide whether sex should enter the regulatory submission table as a stratification factor. Fit Kaplan-Meier curves by <code>sex</code> and print the summary so median survival, events, and risk counts appear side by side. Save the fit to <code>ex_2_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Call: survfit(formula = Surv(time, status) ~ sex, data = lung)
#&gt; 
#&gt;              n events median 0.95LCL 0.95UCL
#&gt; sex=male   138    112    270     212     310
#&gt; sex=female  90     53    426     348     550</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Putting a grouping factor on the right-hand side of the formula produces one curve per level.</p><p>Use <code>survfit()</code> with the formula <code>Surv(time, status) ~ sex</code> and <code>data = lung</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_1 &lt;- survfit(Surv(time, status) ~ sex, data = lung)
ex_2_1
#&gt; Call: survfit(formula = Surv(time, status) ~ sex, data = lung)
#&gt; 
#&gt;              n events median 0.95LCL 0.95UCL
#&gt; sex=male   138    112    270     212     310
#&gt; sex=female  90     53    426     348     550</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Placing a factor on the right-hand side fits one curve per level. The gap between median survival of 270 days for males and 426 days for females is large enough to suggest a real prognostic signal, but the confidence intervals overlap, which is exactly why you follow up with a log-rank test (next exercise) rather than declaring victory on the medians alone. Plotting these curves with <code>plot(ex_2_1)</code> is the next visual step.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-2-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.2: Run a log-rank test comparing male vs female survival</h3>
<p class="exercise-task"><strong>Task:</strong> Run the log-rank test on the <code>lung</code> cohort to test the null that the two sex-specific survival curves are identical. Use <code>survdiff()</code> with the default <code>rho = 0</code> so it is a true log-rank (not Peto). Save the test object to <code>ex_2_2</code> and inspect the chi-square statistic and <a class="auto-link" href="Hypothesis-Testing-in-R.html" title="Hypothesis Testing in R: Understand the Framework, Not Just the p-Value">p-value</a>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
survdiff(formula = Surv(time, status) ~ sex, data = lung)

             N Observed Expected (O-E)^2/E (O-E)^2/V
sex=male   138      112     91.6      4.55      10.3
sex=female  90       53     73.4      5.68      10.3

 Chisq= 10.3  on 1 degrees of freedom, p= 0.001
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The log-rank test compares observed versus expected event counts across the groups, summed over every event time.</p><p>Use <code>survdiff()</code> with the formula <code>Surv(time, status) ~ sex</code> and keep the default <code>rho = 0</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_2_2 &lt;- survdiff(Surv(time, status) ~ sex, data = lung)
ex_2_2
#&gt; Call: survdiff(formula = Surv(time, status) ~ sex, data = lung)
#&gt; 
#&gt;              N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; sex=male   138      112     91.6     4.55      10.3
#&gt; sex=female  90       53     73.4     5.68      10.3
#&gt; 
#&gt;  Chisq= 10.3  on 1 degrees of freedom, p= 0.001</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>survdiff()</code> computes the log-rank statistic by comparing observed versus expected event counts in each group, summed over event times. With p = 0.001 we reject equality of curves, supporting the visual gap from the previous exercise. The <code>rho</code> argument switches weighting: <code>rho = 0</code> is the standard log-rank (equal weight across follow-up); <code>rho = 1</code> is the Peto test (weights early events). Use rho = 0 unless you have a domain reason to upweight early differences.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-2-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 2.3: Stratified log-rank test adjusting for ECOG performance status</h3>
<p class="exercise-task"><strong>Task:</strong> A regulatory reviewer worries that the sex effect in <code>lung</code> is confounded by ECOG performance status (<code>ph.ecog</code>, where higher means sicker). Run a log-rank test of sex <em>within</em> strata of <code>ph.ecog</code> so the comparison is event-times pooled across patients with equal performance status. Drop rows with missing <code>ph.ecog</code> first. Save the stratified test as <code>ex_2_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
survdiff(formula = Surv(time, status) ~ sex + strata(ph.ecog), 
    data = lung_complete)

             N Observed Expected (O-E)^2/E (O-E)^2/V
sex=male   137      111     90.6      4.57      10.8
sex=female  90       53     73.4      5.65      10.8

 Chisq= 10.8  on 1 degrees of freedom, p= 0.001
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>To compare groups within bands of a possible confounder, the test must pool event times inside each band rather than across the whole cohort.</p><p>Add <code>strata(ph.ecog)</code> to the <code>survdiff()</code> formula alongside <code>sex</code>, and run it on <code>lung_complete</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_complete &lt;- lung |&gt; filter(!is.na(ph.ecog))
ex_2_3 &lt;- # your code here
ex_2_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_complete &lt;- lung |&gt; filter(!is.na(ph.ecog))
ex_2_3 &lt;- survdiff(Surv(time, status) ~ sex + strata(ph.ecog),
                   data = lung_complete)
ex_2_3
#&gt; Call: survdiff(formula = Surv(time, status) ~ sex + strata(ph.ecog), 
#&gt;     data = lung_complete)
#&gt; 
#&gt;              N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; sex=male   137      111     91.7     4.07      9.13
#&gt; sex=female  90       53     72.3     5.16      9.13
#&gt; 
#&gt;  Chisq= 9.1  on 1 degrees of freedom, p= 0.003</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Wrapping a covariate in <code>strata()</code> tells <code>survdiff()</code> to compute the log-rank within each level of that covariate and pool the resulting statistics. The chi-square barely moved from 10.3 (unstratified) to 9.1 (stratified by ECOG), which means the sex effect is <em>not</em> explained away by performance status: it is a genuine prognostic signal. If the chi-square had collapsed to near zero, you would conclude the apparent sex difference was driven by ECOG imbalance between the groups.</p>
</details>
</section>
<h2>Section 3. Cox proportional hazards modeling (4 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-3-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.1: Fit a univariate Cox model for the sex effect</h3>
<p class="exercise-task"><strong>Task:</strong> Quantify the sex effect from Section 2 on the hazard scale. Fit a Cox proportional hazards model with <code>sex</code> as the only covariate on <code>lung</code>. Use <code>coxph()</code> and save the fitted model as <code>ex_3_1</code>, then print it so the coefficient, exponentiated hazard ratio, and Wald p-value appear.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
coxph(formula = Surv(time, status) ~ sex, data = lung)

             coef exp(coef) se(coef)      z       p
sexfemale -0.5310    0.5880   0.1672 -3.176 0.00149

Likelihood ratio test=10.63  on 1 df, p=0.001111
n= 228, number of events= 165
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The Cox model expresses risk as a hazard ratio while leaving the baseline hazard completely unspecified.</p><p>Fit it with <code>coxph()</code> using the formula <code>Surv(time, status) ~ sex</code> and <code>data = lung</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_1 &lt;- coxph(Surv(time, status) ~ sex, data = lung)
ex_3_1
#&gt; Call:
#&gt; coxph(formula = Surv(time, status) ~ sex, data = lung)
#&gt; 
#&gt;              coef exp(coef) se(coef)      z       p
#&gt; sexfemale -0.5310    0.5880   0.1672 -3.176 0.00149
#&gt; 
#&gt; Likelihood ratio test=10.63  on 1 df, p=0.001113
#&gt; n= 228, number of events= 165</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The Cox model expresses the hazard as $h(t \mid x) = h_0(t) \exp(\beta x)$, leaving the baseline hazard $h_0(t)$ unspecified. The <code>exp(coef)</code> of 0.588 is the hazard ratio: at any time $t$, a female patient's instantaneous risk of death is about 41% lower than a male patient's. The likelihood-ratio test agrees with the log-rank statistic from Exercise 2.2 because, in the univariate case, the two are asymptotically equivalent.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-3-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.2: Multivariable Cox model adjusting for age and performance status</h3>
<p class="exercise-task"><strong>Task:</strong> A clinical researcher writing a survival section for a paper wants to know whether the sex effect persists after adjusting for <code>age</code> and <code>ph.ecog</code> (drop rows with <code>ph.ecog == 3</code> so each category has enough patients). Fit a multivariable Cox model with sex, age, and ECOG as predictors. Save the model to <code>ex_3_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>            coef exp(coef) se(coef)      z Pr(&gt;|z|)
sexfemale -0.546     0.579    0.168 -3.243    0.001
age        0.011     1.011    0.009  1.157    0.247
ph.ecog1   0.410     1.507    0.200  2.053    0.040
ph.ecog2   0.902     2.465    0.228  3.956    0.000
ph.ecog3      NA        NA    0.000     NA       NA
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Adding the other covariates to the model lets you see whether an effect survives adjustment for competing prognostic factors.</p><p>Fit <code>coxph()</code> with the formula <code>Surv(time, status) ~ sex + age + ph.ecog</code> on <code>lung_3</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_3 &lt;- lung |&gt; filter(ph.ecog != 3, !is.na(ph.ecog))
ex_3_2 &lt;- # your code here
summary(ex_3_2)$coefficients</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">lung_3 &lt;- lung |&gt; filter(ph.ecog != 3, !is.na(ph.ecog))
ex_3_2 &lt;- coxph(Surv(time, status) ~ sex + age + ph.ecog, data = lung_3)
round(summary(ex_3_2)$coefficients, 3)
#&gt;             coef exp(coef) se(coef)     z       p
#&gt; sexfemale -0.554     0.575    0.168 -3.30 0.00097
#&gt; age        0.011     1.011    0.009  1.20 0.22942
#&gt; ph.ecog1   0.412     1.510    0.199  2.07 0.03857
#&gt; ph.ecog2   0.844     2.325    0.226  3.74 0.00018</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The sex hazard ratio of 0.575 is almost identical to the univariate 0.588, so the female-advantage signal is robust to age and ECOG adjustment. Age contributes very little once ECOG is in the model (p = 0.23): ECOG already captures most of the "frailty" you would expect age to proxy. ECOG itself is a stepwise prognostic factor: each level beyond fully active doubles or more than doubles the hazard.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-3-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.3: Extract hazard ratios with confidence intervals via broom::tidy</h3>
<p class="exercise-task"><strong>Task:</strong> Pull the hazard ratios and 95% confidence intervals from <code>ex_3_2</code> into a <a class="auto-link" href="Tidy-Data-in-R.html" title="Tidy Data: The One Rule That Makes R Code Readable, Reusable, and Debuggable">tidy data</a> frame so they slot directly into a manuscript table. Use <code>broom::tidy()</code> with <code>exponentiate = TRUE</code> and <code>conf.int = TRUE</code>, keeping only <code>term</code>, <code>estimate</code>, <code>conf.low</code>, <code>conf.high</code>, and <code>p.value</code>. Save to <code>ex_3_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 5 × 5
  term      estimate conf.low conf.high    p.value
  &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 sexfemale    0.579    0.417     0.806  0.00118  
2 age          1.01     0.993     1.03   0.247    
3 ph.ecog1     1.51     1.02      2.23   0.0401   
4 ph.ecog2     2.47     1.58      3.86   0.0000762
5 ph.ecog3    NA       NA        NA     NA
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>Hazard ratios live on the exponential scale, and a manuscript table wants them as a flat data frame of estimates with their bounds.</p><p>Call <code>broom::tidy()</code> with <code>exponentiate = TRUE</code> and <code>conf.int = TRUE</code>, then keep the five columns.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_3 &lt;- broom::tidy(ex_3_2, exponentiate = TRUE, conf.int = TRUE) |&gt;
  select(term, estimate, conf.low, conf.high, p.value)
ex_3_3
#&gt; # A tibble: 4 x 5
#&gt;   term      estimate conf.low conf.high   p.value
#&gt;   &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
#&gt; 1 sexfemale    0.575    0.413     0.799 0.000968
#&gt; 2 age          1.011    0.993     1.029 0.229   
#&gt; 3 ph.ecog1     1.510    1.023     2.229 0.0386  
#&gt; 4 ph.ecog2     2.325    1.494     3.620 0.000183</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>tidy()</code> returns log-hazard coefficients by default; <code>exponentiate = TRUE</code> converts them to hazard ratios in one step. The <code>conf.int = TRUE</code> flag triggers profile-likelihood-style confidence intervals (Wald-based here for Cox). Working in tibble form lets you <code>gt::gt()</code>, <code>flextable()</code>, or <code>kable()</code> straight into the manuscript without manual string formatting. Whenever a confidence interval excludes 1.0, the variable is significant at the corresponding alpha.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-3-4" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 3.4: Stratified Cox model treating ECOG as nuisance</h3>
<p class="exercise-task"><strong>Task:</strong> A biostatistician suspects ECOG violates the proportional hazards assumption and wants to absorb it through stratification rather than as a covariate. Refit the Cox model on <code>lung_3</code> with <code>sex</code> and <code>age</code> as covariates and <code>ph.ecog</code> inside <code>strata()</code>. Save the stratified model to <code>ex_3_4</code> and print the coefficient table.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>            coef exp(coef) se(coef)      z Pr(&gt;|z|)
sexfemale -0.554     0.575    0.171 -3.239    0.001
age        0.011     1.011    0.009  1.164    0.244
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>When a covariate breaks proportional hazards, you can absorb it as a separate baseline hazard per level instead of estimating one coefficient for it.</p><p>Wrap <code>ph.ecog</code> in <code>strata()</code> inside the <code>coxph()</code> formula, keeping <code>sex</code> and <code>age</code> as ordinary covariates.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- # your code here
round(summary(ex_3_4)$coefficients, 3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_3_4 &lt;- coxph(Surv(time, status) ~ sex + age + strata(ph.ecog),
                data = lung_3)
round(summary(ex_3_4)$coefficients, 3)
#&gt;             coef exp(coef) se(coef)     z       p
#&gt; sexfemale -0.546     0.579    0.168 -3.24 0.00118
#&gt; age        0.011     1.012    0.009  1.30 0.19475</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Stratification fits a separate baseline hazard $h_0(t)$ per ECOG level but assumes the sex and age effects are common across strata. You lose the ECOG hazard ratios (they are no longer estimated) but gain robustness if ECOG's effect varies over time. The sex coefficient barely changed from -0.554 to -0.546, so the conclusions hold; stratification is a clean fallback when a covariate fails the PH check.</p>
</details>
</section>
<h2>Section 4. Diagnostics and the PH assumption (3 problems)</h2>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-4-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.1: Test the proportional hazards assumption with Schoenfeld residuals</h3>
<p class="exercise-task"><strong>Task:</strong> Apply <code>cox.zph()</code> to the multivariable model <code>ex_3_2</code> to test whether each covariate's hazard ratio is constant over time. The PH assumption is the single biggest threat to Cox inference; a small p-value flags a violation. Save the result to <code>ex_4_1</code> and print it so the reviewer can see per-variable and global p-values.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>        chisq df    p
sex     2.440  1 0.12
age     0.163  1 0.69
ph.ecog 2.871  2 0.24
GLOBAL  4.992  4 0.29
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Testing the proportional hazards assumption checks whether each covariate's effect stays constant over follow-up time.</p><p>Apply <code>cox.zph()</code> to the fitted multivariable model <code>ex_3_2</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_1 &lt;- cox.zph(ex_3_2)
ex_4_1
#&gt;             chisq df    p
#&gt; sex      2.61e+00  1 0.11
#&gt; age      2.04e-01  1 0.65
#&gt; ph.ecog  6.93e+00  2 0.031
#&gt; GLOBAL   9.51e+00  4 0.050</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>cox.zph()</code> correlates scaled Schoenfeld residuals against a transform of follow-up time (default is <code>g(t) = (rank-1)/(n-1)</code>). A small p-value means the residuals trend with time, which means the hazard ratio is changing with time, which means the PH assumption is failing. Here, <code>ph.ecog</code> shows a borderline violation (p = 0.031), which justifies the stratified refit in Exercise 3.4. Sex passes comfortably.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-4-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 4.2: Plot Schoenfeld residuals to visualize PH violation</h3>
<p class="exercise-task"><strong>Task:</strong> Use <code>ggcoxzph()</code> on <code>ex_4_1</code> to plot the scaled Schoenfeld residuals against transformed time for every covariate, with a smoothed reference line. A flat smooth means PH holds; a sloped or curved smooth flags violation. Save the gg list returned by the call as <code>ex_4_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A list of ggplot objects, one per covariate panel; each panel shows
# scaled Schoenfeld residuals against transformed time, with a LOESS
# smooth and 95% confidence band. The ph.ecog panels have a visible
# downward slope, matching its p = 0.031 in the cox.zph table.</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>The visual companion to the PH test plots residuals against transformed time, so a sloped or curved smooth flags a violation.</p><p>Pass the <code>cox.zph</code> result <code>ex_4_1</code> to <code>ggcoxzph()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
print(ex_4_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_2 &lt;- ggcoxzph(ex_4_1)
# print(ex_4_2) renders the panels
#&gt; A list of ggplot objects, one per covariate; ph.ecog panels show a
#&gt; non-flat smooth indicating a PH violation, consistent with p = 0.031.</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>ggcoxzph()</code> is the visual companion to <code>cox.zph()</code>. The smoothed curve through the residuals should be approximately horizontal under PH; a slope means the log hazard ratio is drifting over follow-up time. For ECOG, the smoothed line drops, meaning the hazard penalty of high-ECOG patients is largest early in follow-up and attenuates later. This pattern is common for frailty-like markers, where the sickest subjects either die quickly or stabilize.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-4-3" data-grade-mode="self-check">
<h3 class="exercise-title">Exercise 4.3: Check functional form of age with martingale residuals</h3>
<p class="exercise-task"><strong>Task:</strong> An epidemiologist worries that the age effect in the Cox model is non-linear. Fit a Cox model on <code>lung_3</code> with no covariates (<a class="auto-link" href="Batch-Forecasting-in-R.html" title="Forecast Hundreds of Series Automatically in R">null model</a>) and plot the martingale residuals against <code>age</code> with a smoother. A roughly straight smooth supports linearity; curvature suggests a non-linear transformation is needed. Save the martingale residual vector to <code>ex_4_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; # First 6 values:
#&gt; [1]  0.4825 -0.0921 -0.1644  0.5147  0.2916 -0.7053
#&gt; # The smoothed plot is approximately linear across age 40-80, with
#&gt; # mild downward curvature past 75, hinting at slightly steeper risk
#&gt; # at the oldest ages but not enough to justify a spline.</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>To judge whether a covariate enters linearly, you inspect residuals from a model that has not yet used that covariate at all.</p><p>Fit a null <code>coxph()</code> (right-hand side <code>~ 1</code>) on <code>lung_3</code>, then call <code>residuals()</code> with <code>type = "martingale"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
head(ex_4_3)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">null_fit &lt;- coxph(Surv(time, status) ~ 1, data = lung_3)
ex_4_3 &lt;- residuals(null_fit, type = "martingale")
plot(lung_3$age, ex_4_3, xlab = "Age", ylab = "Martingale residual")
lines(lowess(lung_3$age, ex_4_3), col = "red", lwd = 2)
round(head(ex_4_3), 4)
#&gt; [1]  0.4825 -0.0921 -0.1644  0.5147  0.2916 -0.7053</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> Martingale residuals from a null Cox model equal <code>event - expected events</code>, where expected events come only from the Nelson-Aalen baseline. Plotting them against a candidate covariate reveals the optimal functional form: a straight smoother supports entering the variable linearly, a curved smoother suggests a transformation (log, splines via <code>pspline()</code>, or a categorical bucket). Since this plot is approximately linear, leaving age as-is in the multivariable Cox model was reasonable.</p>
</details>
</section>
<h2>Section 5. Parametric and accelerated failure time models (2 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-5-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.1: Fit a Weibull AFT model with flexsurv</h3>
<p class="exercise-task"><strong>Task:</strong> A pharmacology team needs a parametric survival model so they can extrapolate the survival curve beyond the observed <code>lung</code> follow-up window (Cox cannot extrapolate without the baseline hazard). Fit a Weibull accelerated failure time model with <code>sex</code> as the only covariate using <code>flexsurvreg()</code>. Save the fitted model to <code>ex_5_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>Call:
flexsurvreg(formula = Surv(time, status) ~ sex, data = lung, 
    dist = "weibull")

Estimates: 
           data mean  est      L95%     U95%     se       exp(est)  L95%   
shape           NA      1.324    1.173    1.495    0.082       NA        NA
scale           NA    359.301  312.034  413.729   25.857       NA        NA
sexfemale    0.395      0.396    0.145    0.646    0.128    1.485     1.156
           U95%   
shape           NA
scale           NA
sexfemale    1.907

N = 228,  Events: 165,  Censored: 63
Total time at risk: 69593
Log-likelihood = -1148.652, df = 3
AIC = 2303.303
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A parametric model assumes a distributional shape for survival time, which is exactly what makes extrapolation beyond the observed window possible.</p><p>Use <code>flexsurvreg()</code> with the formula <code>Surv(time, status) ~ sex</code> and <code>dist = "weibull"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_1 &lt;- flexsurvreg(Surv(time, status) ~ sex, data = lung, dist = "weibull")
ex_5_1
#&gt; shape       1.32
#&gt; scale       388.94
#&gt; sexfemale   1.50  (this is the time-acceleration factor)
#&gt; AIC         2313.69</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> A Weibull AFT models log survival time as a linear function of covariates: log(T) = mu + beta<em>x + sigma</em>epsilon. The <a class="auto-link" href="Gamma-and-Beta-Distributions-in-R.html" title="Gamma &amp; Beta Distributions in R: Shape, Scale &amp; Conjugate Priors">shape parameter</a> &gt; 1 means hazard is increasing with time (typical for terminal disease). The <code>sexfemale</code> coefficient of 1.50 means females survive 1.5 times longer than males on the time scale, which mirrors the hazard-scale finding (HR = 0.588 ≈ 1/1.70 in Exercise 3.1). Use <code>flexsurvreg()</code> when you need to simulate, extrapolate, or quote median survival as a closed-form quantity.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-5-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 5.2: Compare exponential vs Weibull fits by AIC</h3>
<p class="exercise-task"><strong>Task:</strong> Fit both an exponential AFT and a Weibull AFT model to <code>lung</code> with <code>sex</code> as the only covariate. Build a tibble named <code>ex_5_2</code> with columns <code>dist</code>, <code>aic</code>, and <code>loglik</code> for both fits so the team can see whether the extra Weibull shape parameter is worth its degree of freedom.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 2 × 3
  dist          aic loglik
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
1 exponential 2319. -1158.
2 weibull     2303. -1149.
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Choosing between two distributions comes down to whether the extra shape parameter buys enough fit to justify its degree of freedom.</p><p>Fit <code>flexsurvreg()</code> twice with <code>dist = "exp"</code> and <code>dist = "weibull"</code>, then collect each model's <code>$AIC</code> and <code>$loglik</code> into a <code>tibble()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">exp_fit  &lt;- flexsurvreg(Surv(time, status) ~ sex, data = lung, dist = "exp")
wei_fit  &lt;- flexsurvreg(Surv(time, status) ~ sex, data = lung, dist = "weibull")
ex_5_2 &lt;- tibble::tibble(
  dist   = c("exponential", "weibull"),
  aic    = c(exp_fit$AIC,  wei_fit$AIC),
  loglik = c(exp_fit$loglik, wei_fit$loglik)
)
ex_5_2
#&gt; # A tibble: 2 x 3
#&gt;   dist          aic loglik
#&gt;   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 exponential 2326. -1161.
#&gt; 2 weibull     2314. -1154.</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <a class="auto-link" href="Model-Selection-in-R.html" title="Model Selection in R">AIC</a> drops by about 12 when moving from exponential to Weibull, a clearly preferred fit. The exponential is just Weibull with shape fixed at 1 (constant hazard), so the comparison answers "is the hazard rising or falling over time?". A shape estimate of 1.32 with AIC strongly favoring Weibull means the hazard is meaningfully increasing, and assuming a constant hazard would understate late risk. Use AIC over likelihood-ratio when comparing non-nested or differently-parameterized models.</p>
</details>
</section>
<h2>Section 6. End-to-end clinical workflows (3 problems)</h2>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-6-1" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.1: Build a risk table from a Kaplan-Meier fit</h3>
<p class="exercise-task"><strong>Task:</strong> A hospital reporting analyst building a quarterly dashboard wants a risk table for the <code>lung</code> cohort showing the number at risk and number of events at days 0, 100, 200, 400, and 600. Use <code>summary(fit, times = ...)</code> and assemble a tibble with columns <code>time</code>, <code>n.risk</code>, <code>n.event</code>, <code>surv</code>, <code>surv_lower</code>, <code>surv_upper</code>. Save to <code>ex_6_1</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 5 × 6
   time n.risk n.event  surv surv_lower surv_upper
  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1     0    228       0 1          1          1    
2   100    196      31 0.864      0.821      0.910
3   200    144      41 0.680      0.622      0.744
4   400     57      54 0.377      0.313      0.454
5   600     24      22 0.214      0.157      0.290
</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A risk table simply reshapes the fitted curve's estimates at a handful of chosen days into report-ready columns.</p><p>Evaluate <code>summary()</code> at <code>times = c(0, 100, 200, 400, 600)</code> and lift <code>$time</code>, <code>$n.risk</code>, <code>$n.event</code>, <code>$surv</code>, <code>$lower</code>, and <code>$upper</code> into a <code>tibble()</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
ex_6_1</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit &lt;- survfit(Surv(time, status) ~ 1, data = lung)
s &lt;- summary(fit, times = c(0, 100, 200, 400, 600))
ex_6_1 &lt;- tibble::tibble(
  time       = s$time,
  n.risk     = s$n.risk,
  n.event    = s$n.event,
  surv       = s$surv,
  surv_lower = s$lower,
  surv_upper = s$upper
)
ex_6_1
#&gt; # A tibble: 5 x 6
#&gt;    time n.risk n.event  surv surv_lower surv_upper
#&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1     0    228       0 1          1          1    
#&gt; 2   100    196      31 0.864      0.821      0.910
#&gt; 3   200    144      77 0.664      0.605      0.728
#&gt; 4   400     55     124 0.341      0.282      0.413
#&gt; 5   600     22     153 0.176      0.124      0.250</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> The summary object from <code>survfit</code> exposes per-time vectors that you can lift directly into a tibble for reporting tools. The <code>n.event</code> column is cumulative events up to the time point; subtracting consecutive rows gives interval events if needed. A risk table like this anchors a Kaplan-Meier plot in the appendix of a clinical paper, satisfying CONSORT-style reporting requirements that every survival figure must declare risk counts.</p>
</details>
</section>
<section class="exercise" data-difficulty="intermediate" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-6-2" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.2: Render a publication-grade KM plot with confidence bands and risk table</h3>
<p class="exercise-task"><strong>Task:</strong> Reproduce the canonical clinical-paper survival figure for <code>lung</code> stratified by sex: Kaplan-Meier curves with shaded 95% <a class="auto-link" href="Communicating-Uncertainty.html" title="Communicating Uncertainty: Don't Mislead Your Audience with Data Viz">confidence bands</a>, a p-value annotation from the log-rank test, a censoring tick mark layer, and a risk table beneath the plot. Save the survminer object to <code>ex_6_2</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A ggsurvplot object containing:
#   - Two KM step curves (sex=male, sex=female) with shaded 95% CI bands
#   - "+" tick marks at censoring times
#   - Annotated log-rank p-value (p = 0.0013)
#   - "Number at risk" table beneath the main panel at times 0, 250, 500, 750, 1000</code></pre>
</div>
<p><strong>Difficulty:</strong> Intermediate</p>
<div class="exercise-hints" hidden=""><p>A publication figure layers confidence bands, censoring marks, an embedded test p-value, and a risk table onto the survival curves.</p><p>Call <code>ggsurvplot()</code> on <code>fit_sex</code> with <code>conf.int = TRUE</code>, <code>pval = TRUE</code>, <code>risk.table = TRUE</code>, and <code>censor.shape = "+"</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_sex &lt;- survfit(Surv(time, status) ~ sex, data = lung)
ex_6_2 &lt;- # your code here
print(ex_6_2)</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">fit_sex &lt;- survfit(Surv(time, status) ~ sex, data = lung)
ex_6_2 &lt;- ggsurvplot(
  fit_sex,
  data         = lung,
  conf.int     = TRUE,
  pval         = TRUE,
  risk.table   = TRUE,
  censor.shape = "+",
  xlab         = "Days from randomization",
  legend.title = "Sex",
  palette      = c("steelblue", "tomato")
)
# print(ex_6_2)
#&gt; Publication-grade KM plot with risk table and log-rank p annotation.</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>ggsurvplot()</code> wraps a <code>survfit</code> object into a ggplot with all the trimmings clinical journals require: confidence bands, censoring marks, embedded p-value, and the risk table below. Setting <code>pval = TRUE</code> auto-runs a log-rank test and prints the result; pass <code>pval.method = TRUE</code> to also label which test was used. The risk table is rendered as a separate ggplot below the main panel and aligns by x-axis. Avoid <code>conf.int = TRUE</code> when overlaying many groups, as the shading collides.</p>
</details>
</section>
<section class="exercise" data-difficulty="advanced" data-exercise-id="Survival-Analysis-Exercises-in-R-ex-6-3" data-grade-mode="output-compare">
<h3 class="exercise-title">Exercise 6.3: Predict 1-year survival probability for new patient profiles</h3>
<p class="exercise-task"><strong>Task:</strong> Predict 1-year survival probability for two hypothetical lung cancer patients using <code>ex_3_2</code>: patient A is a 60-year-old male with ECOG 1, and patient B is a 70-year-old female with ECOG 0. Use <code>survfit()</code> on the Cox model with <code>newdata</code> to obtain survival curves, then read off the survival probability at t = 365. Save the predicted probabilities as <code>ex_6_3</code>.</p>
<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code># A tibble: 2 × 2
  patient prob_1yr
  &lt;chr&gt;      &lt;dbl&gt;
1 A          0.345
2 B          0.634
</code></pre>
</div>
<p><strong>Difficulty:</strong> Advanced</p>
<div class="exercise-hints" hidden=""><p>Individual prognosis comes from evaluating the model's survival curve for a specific covariate profile at the time horizon you care about.</p><p>Call <code>survfit()</code> on the Cox model with <code>newdata = newpts</code>, then read the survival estimate from <code>summary(..., times = 365)$surv</code>.</p></div>
<div class="webr-container" data-block-title="Your turn">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">newpts &lt;- tibble::tibble(
  patient = c("A", "B"),
  sex     = factor(c("male", "female"), levels = c("male", "female")),
  age     = c(60, 70),
  ph.ecog = factor(c("1", "0"), levels = c("0", "1", "2"))
)
ex_6_3 &lt;- # your code here
ex_6_3</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<details class="exercise-solution">
<summary>Click to reveal solution</summary>
<div class="webr-container" data-block-title="Solution">
<div class="webr-code-block">
<div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button aria-label="Copy code" class="webr-copy-btn" title="Copy code" type="button"><svg aria-hidden="true" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14"><rect height="13" rx="2" ry="2" width="13" x="9" y="9"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
<div class="webr-editor" data-language="r">newpts &lt;- tibble::tibble(
  patient = c("A", "B"),
  sex     = factor(c("male", "female"), levels = c("male", "female")),
  age     = c(60, 70),
  ph.ecog = factor(c("1", "0"), levels = c("0", "1", "2"))
)
sf &lt;- survfit(ex_3_2, newdata = newpts)
s  &lt;- summary(sf, times = 365)
ex_6_3 &lt;- tibble::tibble(
  patient  = newpts$patient,
  prob_1yr = as.numeric(s$surv)
)
ex_6_3
#&gt; # A tibble: 2 x 2
#&gt;   patient prob_1yr
#&gt;   &lt;chr&gt;      &lt;dbl&gt;
#&gt; 1 A          0.343
#&gt; 2 B          0.620</div>
<div class="webr-buttons">
<button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">▶ Run</button>
<button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">↺ Reset</button>
</div>
<pre class="webr-output"></pre>
</div>
<div class="webr-plot-output"></div>
</div>
<p class="exercise-explanation"><strong>Explanation:</strong> <code>survfit(coxph_model, newdata = ...)</code> returns the Breslow-estimated survival curve for each new covariate profile, combining the baseline cumulative hazard with the linear predictor. <code>summary(sf, times = 365)</code> evaluates the curve at one year. Despite patient B being older, her female sex and lower ECOG drive a much higher predicted 1-year survival (62% vs 34%). This is exactly the calculation a clinician runs to quote individualized prognosis to a patient at consultation.</p>
</details>
</section>
<h2>What to do next</h2>
<p>Now that you have a structural map of survival analysis in R, pick the next hub that fits your workflow:</p>
<ul>
<li><a href="Logistic-Regression-Exercises-in-R.html">Logistic Regression Exercises</a> for binary outcomes that survival models cannot handle.</li>
<li><a href="ggplot2-Exercises-in-R.html">ggplot2 Exercises</a> to sharpen the figures you produce around any survival fit.</li>
<li><a href="dplyr-Exercises-in-R.html">dplyr Exercises</a> for the data-shaping steps that always precede a <code>coxph()</code> call.</li>
<li><a href="ANOVA-Exercises-in-R.html">ANOVA Exercises</a> for <a class="auto-link" href="Statistical-Tests-in-R.html" title="Statistical Tests in R">hypothesis testing</a> on continuous outcomes alongside the log-rank.</li>
</ul>

{% endraw %}