---
title: "T-Test Exercises in R: 20 Real-World Practice Problems"
description: "20 t-test exercises in R covering one-sample, two-sample (Welch and Student), paired tests, assumptions, effect sizes, power, and reporting workflows."
keywords: "t test R exercises, t-test practice problems, one-sample t-test R, paired t-test exercises, Welch t-test R, Cohen's d R, t-test power analysis"
mathjax: true
webr: true
post_type: "EX"
auto_link_terms: "t-test exercises|t-test practice|one-sample t-test|paired t-test|welch t-test|cohen's d"
auto_link_case_sensitive: false
sidebar_title: "t-Test Exercises (20 problems)"
sidebar_order: "152"
fr_parent: "t-Tests-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>T-Test Exercises in R: 20 Real-World Practice Problems</h1>

<p class="lead">Twenty <a class="auto-link" href="t-Test-Exercises-in-R.html" title="t-Test Exercises in R: 12 One, Two & Paired Sample Problems, Solved Step-by-Step">t-test problems</a> covering one-sample, two-sample (Welch and Student), paired, and one-sided variants with assumption checks, effect sizes, power calculations, and end-to-end stakeholder workflows. Every solution is hidden until you click; verify against the Expected result block before peeking.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="50" data-exercises="20" data-xp="300"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(dplyr)
library(tidyr)
library(car)
library(pwr)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p>The dataset stable used across this hub: <code>iris</code>, <code>mtcars</code>, <code>ToothGrowth</code>, <code>PlantGrowth</code>, <code>ChickWeight</code>, plus inline tibbles where a domain scenario calls for one. Throughout, save each answer to <code>ex_&lt;section&gt;_&lt;problem&gt;</code> so you can sanity-check against the Expected result before revealing the solution.</p>

<h2>Section 1. One-sample t-tests (4 problems)</h2>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-1-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 1.1: Test whether iris Sepal.Length mean equals 5.85</h3>

<p class="exercise-task"><strong>Task:</strong> The botany lab claims the global mean sepal length across iris species is 5.85 cm. Using the built-in <code>iris</code> dataset, run a two-sided <a class="auto-link" href="t-Tests-in-R.html" title="t-Tests in R: Every Variant With the Decision Rule for Choosing Between Them">one-sample t-test</a> of <code>Sepal.Length</code> against the null mean 5.85 and save the htest object to <code>ex_1_1</code>. Report whether the p-value rejects the null at alpha 0.05.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	One Sample t-test
#&gt;
#&gt; data:  iris$Sepal.Length
#&gt; t = -0.39031, df = 149, p-value = 0.6969
#&gt; alternative hypothesis: true mean is not equal to 5.85
#&gt; 95 percent confidence interval:
#&gt;  5.709732 5.976934
#&gt; sample mean
#&gt;     5.843333</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>A claimed population mean is something you supply from outside the data, never something you estimate from the sample itself.</p><p>Feed the vector and the claimed value as <code>mu</code> to <code>t.test()</code>; the two-sided test is the default, so no <code>alternative</code> is needed.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- t.test(iris$Sepal.Length, mu = 5.85)
ex_1_1
#&gt; 	One Sample t-test
#&gt;
#&gt; data:  iris$Sepal.Length
#&gt; t = -0.39031, df = 149, p-value = 0.6969
#&gt; alternative hypothesis: true mean is not equal to 5.85
#&gt; 95 percent confidence interval:
#&gt;  5.709732 5.976934
#&gt; sample mean
#&gt;     5.843333</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>t.test(x, mu = 5.85)</code> defaults to a two-sided test against the supplied null mean. The p-value 0.697 is far above 0.05, so the data do not contradict the lab's claim. The 95 percent CI [5.71, 5.98] contains 5.85, which is the same conclusion expressed as an interval. Always pull <code>mu</code> from the scientific claim, never from the data itself.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-1-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.2: One-sided test that mtcars mpg exceeds 18</h3>

<p class="exercise-task"><strong>Task:</strong> A fuel-economy reviewer wants evidence that the average car in <code>mtcars</code> gets more than 18 mpg. Run a one-sided (greater) one-sample t-test of <code>mtcars$mpg</code> against mu = 18 and save the htest object to <code>ex_1_2</code>. Confirm whether the lower CI bound stays above 18.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	One Sample t-test
#&gt;
#&gt; data:  mtcars$mpg
#&gt; t = 2.4286, df = 31, p-value = 0.01054
#&gt; alternative hypothesis: true mean is greater than 18
#&gt; 95 percent confidence interval:
#&gt;  18.40632      Inf
#&gt; sample mean
#&gt;      20.09062</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>When you have a directional prediction, the test should put all its attention on one tail instead of splitting it across both.</p><p>Set <code>alternative = &quot;greater&quot;</code> in <code>t.test()</code> alongside <code>mu = 18</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- t.test(mtcars$mpg, mu = 18, alternative = &quot;greater&quot;)
ex_1_2
#&gt; 	One Sample t-test
#&gt;
#&gt; data:  mtcars$mpg
#&gt; t = 2.4286, df = 31, p-value = 0.01054
#&gt; alternative hypothesis: true mean is greater than 18
#&gt; 95 percent confidence interval:
#&gt;  18.40632      Inf
#&gt; sample mean
#&gt;      20.09062</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Setting <code>alternative = &quot;greater&quot;</code> halves the p-value compared to the two-sided test only when the sample mean is on the predicted side. The CI becomes one-sided: [18.41, Inf), and because its finite endpoint exceeds 18, the test rejects at alpha 0.05. The common mistake is using "greater" when the sample mean is below the null; in that case R still reports a finite p but it will be near 1, not near 0.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-1-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.3: Manufacturing QA against a 10 mm bolt spec</h3>

<p class="exercise-task"><strong>Task:</strong> A factory specification requires bolts to average 10 mm. Quality control measures 12 bolts and finds the lengths shown below. Run a two-sided one-sample t-test against mu = 10 and save the htest object to <code>ex_1_3</code>. Decide whether the line should be paused (reject at alpha 0.01).</p>

<div class="webr-container" data-block-title="Setup data">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup data</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">bolt_lengths &lt;- c(10.02, 9.97, 10.05, 9.95, 10.01, 10.04,
                  9.98, 10.06, 9.96, 10.03, 9.99, 10.04)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	One Sample t-test
#&gt;
#&gt; data:  bolt_lengths
#&gt; t = 1.2456, df = 11, p-value = 0.2389
#&gt; alternative hypothesis: true mean is not equal to 10
#&gt; 95 percent confidence interval:
#&gt;   9.990078 10.033255
#&gt; sample mean
#&gt;    10.01167</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Compare the measured average against the engineering target without assuming which direction any drift would take.</p><p>Call <code>t.test()</code> on <code>bolt_lengths</code> with <code>mu = 10</code> and leave <code>alternative</code> at its two-sided default.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- t.test(bolt_lengths, mu = 10)
ex_1_3
#&gt; 	One Sample t-test
#&gt;
#&gt; data:  bolt_lengths
#&gt; t = 1.2456, df = 11, p-value = 0.2389
#&gt; alternative hypothesis: true mean is not equal to 10
#&gt; 95 percent confidence interval:
#&gt;   9.990078 10.033255
#&gt; sample mean
#&gt;    10.01167</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A p-value of 0.24 is nowhere near 0.01, so the line is statistically on-spec. Small samples (n = 12) have low power, so a non-rejection is not proof of compliance; it just means this evidence is insufficient to flag drift. For ongoing monitoring, an SPC chart with control limits is more useful than a single t-test because it visualizes trend, not just a single snapshot.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-1-4" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 1.4: Extract the 95% CI from a t-test object</h3>

<p class="exercise-task"><strong>Task:</strong> You ran the test in Exercise 1.1 and now need just the 95 percent <a class="auto-link" href="Confidence-Intervals-in-R.html" title="Confidence Intervals in R: The Definition Most Textbooks State Incorrectly">confidence interval</a> as a length-two numeric vector for a downstream report. Pull <code>conf.int</code> directly off the htest object and strip the attribute. Save the resulting unnamed numeric vector to <code>ex_1_4</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] 5.709732 5.976934</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A test result is a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a>, so the interval you want is just one element you can pull out directly.</p><p>Index <code>$conf.int</code> off <code>ex_1_1</code> and wrap it in <code>as.numeric()</code> to strip the trailing attribute.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- as.numeric(ex_1_1$conf.int)
ex_1_4
#&gt; [1] 5.709732 5.976934</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> <code>t.test()</code> returns an <code>htest</code> list with <code>$conf.int</code>, <code>$estimate</code>, <code>$statistic</code>, <code>$p.value</code>, and <code>$parameter</code> (df). Wrapping in <code>as.numeric()</code> drops the <code>conf.level</code> attribute that tags along, which matters when you later paste the values into a report or pass them to a function that errors on attributes. For one-sided tests one endpoint will be <code>-Inf</code> or <code>Inf</code>, which <code>as.numeric</code> preserves.</p>

</details>

</section>

<h2>Section 2. Two-sample tests: Welch and Student (4 problems)</h2>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-2-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 2.1: Compare Petal.Length between setosa and versicolor</h3>

<p class="exercise-task"><strong>Task:</strong> Use the <code>iris</code> dataset to compare <code>Petal.Length</code> between species <code>setosa</code> and <code>versicolor</code>. Run a two-sample (Welch) t-test using the formula interface and filter out the <code>virginica</code> rows before testing. Save the htest object to <code>ex_2_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  Petal.Length by Species
#&gt; t = -39.493, df = 62.14, p-value &lt; 2.2e-16
#&gt; alternative hypothesis: true difference in means between group setosa and group versicolor is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -2.939618 -2.656382
#&gt; mean in group setosa mean in group versicolor
#&gt;                1.462                    4.260</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Trim the dataset down to just the two groups you want to compare before running any two-group test.</p><p>Use <code>subset()</code> to keep the two species, <code>droplevels()</code> to clear the unused factor level, then <code>t.test(Petal.Length ~ Species, data = ...)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">two_species &lt;- subset(iris, Species %in% c(&quot;setosa&quot;, &quot;versicolor&quot;))
two_species$Species &lt;- droplevels(two_species$Species)
ex_2_1 &lt;- t.test(Petal.Length ~ Species, data = two_species)
ex_2_1
#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  Petal.Length by Species
#&gt; t = -39.493, df = 62.14, p-value &lt; 2.2e-16
#&gt; alternative hypothesis: true difference in means between group setosa and group versicolor is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -2.939618 -2.656382
#&gt; mean in group setosa mean in group versicolor
#&gt;                1.462                    4.260</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Formula <code>Petal.Length ~ Species</code> is the cleanest two-sample syntax when data live in a data frame. <code>t.test()</code> defaults to <code>var.equal = FALSE</code> (Welch), which is the right default because equal variances are rarely true and Welch is robust when they happen to be equal. Dropping unused factor levels with <code>droplevels()</code> prevents R from silently trying a three-group comparison that errors on a two-sample test.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-2-2" data-grade-mode="self-check" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.2: Welch vs Student on ToothGrowth supplement groups</h3>

<p class="exercise-task"><strong>Task:</strong> Using <code>ToothGrowth</code>, compare tooth length <code>len</code> between supplements <code>OJ</code> and <code>VC</code> two ways: first with the default Welch correction, then with <code>var.equal = TRUE</code> (Student). Store the two htest objects in a named list <code>ex_2_2</code> with elements <code>welch</code> and <code>student</code>, then compare the two p-values.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $welch
#&gt; 	Welch Two Sample t-test
#&gt; ...
#&gt; t = 1.9153, df = 55.309, p-value = 0.06063
#&gt;
#&gt; $student
#&gt; 	Two Sample t-test
#&gt; ...
#&gt; t = 1.9153, df = 58, p-value = 0.06039</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>The only thing separating the two variants is whether the test is allowed to pool the two group variances into one.</p><p>Run <code>t.test(len ~ supp, data = ToothGrowth)</code> twice, the second call adding <code>var.equal = TRUE</code>, and wrap both in a named <code>list()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2$welch$p.value
ex_2_2$student$p.value</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- list(
  welch   = t.test(len ~ supp, data = ToothGrowth),
  student = t.test(len ~ supp, data = ToothGrowth, var.equal = TRUE)
)
c(welch = ex_2_2$welch$p.value, student = ex_2_2$student$p.value)
#&gt;      welch    student
#&gt; 0.06062661 0.06039337</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> When sample sizes are equal and variances similar, Welch and Student give nearly identical p-values, as here (0.061 vs 0.060). The Welch df is fractional because Satterthwaite approximation accounts for unequal variances even when they are unequal only slightly. Practical guidance: use Welch by default and only use Student if you have a strong prior reason to assume equal variances, since Student is anti-conservative when variances differ.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-2-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 2.3: One-sided test that PlantGrowth trt1 differs from ctrl</h3>

<p class="exercise-task"><strong>Task:</strong> Using <code>PlantGrowth</code>, test whether the treatment <code>trt1</code> group has a different mean weight from the <code>ctrl</code> group. <a class="auto-link" href="Reduce-Filter-Map-in-R.html" title="Reduce(), Filter(), Map() in Base R: Functional Trifecta Explained">Filter</a> to just those two groups, then run a two-sided Welch t-test. Save the htest to <code>ex_2_3</code>, then report whether the result is significant at alpha 0.10.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  weight by group
#&gt; t = 1.1913, df = 16.524, p-value = 0.2504
#&gt; alternative hypothesis: true difference in means between group ctrl and group trt1 is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.2875162  1.0295162
#&gt; mean in group ctrl mean in group trt1
#&gt;              5.032              4.661</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Keep only the control and treatment-one rows before comparing their means.</p><p>Use <code>subset()</code> to filter <code>group</code> to <code>c(&quot;ctrl&quot;, &quot;trt1&quot;)</code>, then <code>droplevels()</code>, then <code>t.test(weight ~ group, data = ...)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">plants &lt;- subset(PlantGrowth, group %in% c(&quot;ctrl&quot;, &quot;trt1&quot;))
plants$group &lt;- droplevels(plants$group)
ex_2_3 &lt;- t.test(weight ~ group, data = plants)
ex_2_3
#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  weight by group
#&gt; t = 1.1913, df = 16.524, p-value = 0.2504
#&gt; alternative hypothesis: true difference in means between group ctrl and group trt1 is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.2875162  1.0295162
#&gt; mean in group ctrl mean in group trt1
#&gt;              5.032              4.661</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> p = 0.25 is well above 0.10, so trt1 is not detectably different from control. The CI [-0.29, 1.03] crosses zero, confirming the same conclusion. If you suspected trt1 reduces weight, a one-sided test (alternative = "greater" for ctrl) might be motivated by prior science, but the convention is to pre-register one-sided tests; otherwise reviewers will assume you fished for the smaller p-value.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-2-4" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 2.4: Welch holds up under unequal sample sizes</h3>

<p class="exercise-task"><strong>Task:</strong> Construct two simulated groups, group A with 50 observations and group B with only 6 observations, both from normal populations with different variances. Run a Welch t-test on the combined data using the formula interface. Save the htest object to <code>ex_2_4</code> and note the fractional degrees of freedom.</p>

<div class="webr-container" data-block-title="Setup data">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup data</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(2026)
grp &lt;- factor(c(rep(&quot;A&quot;, 50), rep(&quot;B&quot;, 6)))
y   &lt;- c(rnorm(50, mean = 10, sd = 1),
         rnorm(6,  mean = 11, sd = 4))
unequal_df &lt;- data.frame(grp, y)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  y by grp
#&gt; t = -0.81935, df = 5.1456, p-value = 0.4493
#&gt; alternative hypothesis: true difference in means between group A and group B is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -5.494091  2.756478
#&gt; mean in group A mean in group B
#&gt;        9.842977       11.211784</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Lopsided group sizes need no special handling; the default two-sample test already corrects for them on its own.</p><p>Call <code>t.test(y ~ grp, data = unequal_df)</code> and read the fractional <code>df</code> off the returned object.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_4 &lt;- # your code here
ex_2_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_4 &lt;- t.test(y ~ grp, data = unequal_df)
ex_2_4
#&gt; 	Welch Two Sample t-test
#&gt;
#&gt; data:  y by grp
#&gt; t = -0.81935, df = 5.1456, p-value = 0.4493
#&gt; ...</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Welch df collapses toward the smaller sample size whenever that group also has the bigger variance, which is the exact scenario that makes Student's pooled-variance test wildly anti-conservative. Here df = 5.1, not the n1 + n2 - 2 = 54 you would get from Student. If you had run Student here you would have inflated <a class="auto-link" href="Hypothesis-Testing-in-R.html" title="Hypothesis Testing in R: Understand the Framework, Not Just the p-Value">Type I error</a> roughly fivefold. Lesson: never pool variances without testing them, and Welch makes the whole question moot.</p>

</details>

</section>

<h2>Section 3. Paired t-tests (3 problems)</h2>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-3-1" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 3.1: Weight-loss before and after, paired design</h3>

<p class="exercise-task"><strong>Task:</strong> A nutrition study weighs 10 participants before and after a 12-week program. The two vectors are paired by subject id, so use <code>paired = TRUE</code>. Run a two-sided paired t-test and save the htest object to <code>ex_3_1</code>.</p>

<div class="webr-container" data-block-title="Setup data">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup data</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">before &lt;- c(82, 75, 90, 68, 79, 85, 92, 70, 77, 88)
after  &lt;- c(80, 73, 87, 67, 78, 82, 89, 69, 75, 86)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	Paired t-test
#&gt;
#&gt; data:  before and after
#&gt; t = 8.1029, df = 9, p-value = 1.987e-05
#&gt; alternative hypothesis: true mean difference is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  1.541544 2.658456
#&gt; mean difference
#&gt;             2.1</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Each subject contributes two readings that belong together, so the test should analyze the within-subject change, not two separate samples.</p><p>Pass both vectors to <code>t.test()</code> with <code>paired = TRUE</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- t.test(before, after, paired = TRUE)
ex_3_1
#&gt; 	Paired t-test
#&gt;
#&gt; data:  before and after
#&gt; t = 8.1029, df = 9, p-value = 1.987e-05
#&gt; alternative hypothesis: true mean difference is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  1.541544 2.658456
#&gt; mean difference
#&gt;             2.1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A paired t-test is mathematically a one-sample t-test on the within-subject differences (before minus after) against mu = 0. The order of arguments only flips the sign of the t-statistic and CI, not the p-value. If you forgot <code>paired = TRUE</code> here, R would run an independent two-sample test and produce a far larger p-value because between-subject variance swamps the consistent 2-3 kg drop. The pairing is what gives the test its power.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-3-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 3.2: Paired test on ChickWeight, day 0 vs day 21</h3>

<p class="exercise-task"><strong>Task:</strong> Using <code>ChickWeight</code>, build a paired comparison of <code>weight</code> at <code>Time == 0</code> versus <code>Time == 21</code> for the same chick. Reshape so each chick contributes one before and one after value, drop chicks missing either time point, and run a paired t-test. Save the htest object to <code>ex_3_2</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	Paired t-test
#&gt;
#&gt; data:  pair_wide$t0 and pair_wide$t21
#&gt; t = -20.611, df = 44, p-value &lt; 2.2e-16
#&gt; alternative hypothesis: true mean difference is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -147.0541 -120.7237
#&gt; mean difference
#&gt;       -133.8889</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Pairing only works once each chick sits on one row with its two time points side by side, and any chick missing either point must be dropped.</p><p>Reshape with <code>pivot_wider()</code> keyed on <code>Chick</code>, <code>filter()</code> out the <code>NA</code> rows, then call <code>t.test(..., paired = TRUE)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pair_wide &lt;- ChickWeight |&gt;
  filter(Time %in% c(0, 21)) |&gt;
  pivot_wider(id_cols = Chick, names_from = Time, values_from = weight, names_prefix = &quot;t&quot;) |&gt;
  filter(!is.na(t0), !is.na(t21))

ex_3_2 &lt;- t.test(pair_wide$t0, pair_wide$t21, paired = TRUE)
ex_3_2
#&gt; 	Paired t-test
#&gt;
#&gt; data:  pair_wide$t0 and pair_wide$t21
#&gt; t = -20.611, df = 44, p-value &lt; 2.2e-16</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Real paired studies almost always lose some subjects to follow-up, so <code>filter(!is.na(t0), !is.na(t21))</code> is mandatory before pairing. Reshaping with <code>pivot_wider()</code> turns a long-format panel into a one-row-per-chick wide table, which is the shape <code>paired = TRUE</code> expects. The huge effect (mean diff = 134 g) is unsurprising biologically and the p-value floors at the machine epsilon (< 2.2e-16); always report <code>&lt; 1e-3</code> or <code>&lt; 0.001</code> rather than the exact floor value.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-3-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 3.3: When paired beats independent: pre vs post BP</h3>

<p class="exercise-task"><strong>Task:</strong> A clinic measures systolic blood pressure on 8 patients before and after a new med. Run the same data both ways: once as a paired t-test, once as a two-sample t-test (which ignores the pairing). Save a named list with <code>paired</code> and <code>unpaired</code> htest objects to <code>ex_3_3</code> and compare the two p-values.</p>

<div class="webr-container" data-block-title="Setup data">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup data</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">pre  &lt;- c(142, 138, 150, 145, 139, 155, 148, 141)
post &lt;- c(135, 130, 144, 137, 132, 147, 140, 134)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;     paired   unpaired
#&gt; 4.0863e-09 1.7126e-02</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Run the identical numbers through a design that respects the within-patient link and one that ignores it entirely.</p><p>Build a <code>list()</code> holding <code>t.test(pre, post, paired = TRUE)</code> and a plain <code>t.test(pre, post)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
sapply(ex_3_3, function(h) h$p.value)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- list(
  paired   = t.test(pre, post, paired = TRUE),
  unpaired = t.test(pre, post)
)
sapply(ex_3_3, function(h) h$p.value)
#&gt;      paired    unpaired
#&gt; 4.086e-09 1.713e-02</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Both tests agree on direction, but the paired p-value is roughly seven orders of magnitude smaller. Why: most of the variance in BP comes from between-patient differences (some run high, some run low). The paired test eliminates that nuisance variance by analyzing within-patient changes. Forgetting to pair when your design IS paired is the single most common t-test error in practice; the diagnostic is "is the same unit (person, chick, plot) measured twice?" If yes, pair.</p>

</details>

</section>

<h2>Section 4. Assumptions, robustness & alternatives (3 problems)</h2>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-4-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.1: Shapiro-Wilk normality check before a t-test</h3>

<p class="exercise-task"><strong>Task:</strong> Before trusting the Welch t-test in Exercise 2.3, run Shapiro-Wilk normality tests on the <code>weight</code> values within each PlantGrowth group (<code>ctrl</code> and <code>trt1</code>). Save a named list with the two <code>htest</code> objects to <code>ex_4_1</code> and report whether either group rejects normality at alpha 0.05.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $ctrl
#&gt; 	Shapiro-Wilk normality test
#&gt; data:  weight[group == &quot;ctrl&quot;]
#&gt; W = 0.95682, p-value = 0.7475
#&gt;
#&gt; $trt1
#&gt; 	Shapiro-Wilk normality test
#&gt; data:  weight[group == &quot;trt1&quot;]
#&gt; W = 0.9304, p-value = 0.4519</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Check the <a class="auto-link" href="Univariate-EDA-in-R.html" title="Univariate EDA in R: Every Variable Deserves Individual Attention Before Modelling">distribution shape</a> one group at a time before trusting any mean-based comparison.</p><p>Call <code>shapiro.test()</code> on the <code>weight</code> values of each group and store the two results in a named <code>list()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">plants &lt;- subset(PlantGrowth, group %in% c(&quot;ctrl&quot;, &quot;trt1&quot;))
ex_4_1 &lt;- list(
  ctrl = shapiro.test(plants$weight[plants$group == &quot;ctrl&quot;]),
  trt1 = shapiro.test(plants$weight[plants$group == &quot;trt1&quot;])
)
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Neither group rejects normality (p = 0.75 and 0.45), so the t-test in 2.3 is safe to interpret. Shapiro-Wilk is sensitive at moderate n (10 to 50) and underpowered below n = 8, so absent rejection is weak evidence of normality at very small sizes. A pragmatic alternative is to look at a <a class="auto-link" href="Regression-Diagnostics-in-R.html" title="Regression Diagnostics in R: 5 Plots That Reveal Model Violations Instantly">Q-Q plot</a> directly with <code>qqnorm()</code> and rely on the <a class="auto-link" href="Central-Limit-Theorem-in-R.html" title="Central Limit Theorem in R: Simulate It From Skewed, Bimodal, and Uniform Distributions">Central Limit Theorem</a> for n >= 30 since the t-statistic is robust to mild non-normality.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-4-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.2: Levene's test for equal variances</h3>

<p class="exercise-task"><strong>Task:</strong> Before deciding between Welch and Student on the <code>ToothGrowth</code> supplement comparison, run <a class="auto-link" href="One-Way-ANOVA-in-R.html" title="One-Way ANOVA in R: F-Test, Levene's Test, and Post-Hoc, Complete Walkthrough">Levene's test</a> for <a class="auto-link" href="Normality-and-Variance-Tests-in-R.html" title="Test Normality and Equal Variance in R: What the Tests Can and Can't Tell You">homogeneity of variance</a> using <code>car::leveneTest</code> with center = "median". Save the resulting ANOVA-style object to <code>ex_4_2</code> and read off the p-value to confirm which test variant to prefer.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; Levene's Test for Homogeneity of Variance (center = &quot;median&quot;)
#&gt;       Df F value Pr(&gt;F)
#&gt; group  1  1.2136 0.2752
#&gt;       58</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Before choosing between pooled and separate variances, test whether the two spreads are even comparable.</p><p>Call <code>leveneTest(len ~ supp, data = ToothGrowth, center = &quot;median&quot;)</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- leveneTest(len ~ supp, data = ToothGrowth, center = &quot;median&quot;)
ex_4_2
#&gt; Levene's Test for Homogeneity of Variance (center = &quot;median&quot;)
#&gt;       Df F value Pr(&gt;F)
#&gt; group  1  1.2136 0.2752
#&gt;       58</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Levene's test does not reject equal variances (p = 0.28). Pre-test then pick test is a known statistical pitfall called the conditional test problem: it inflates Type I error in the second-stage t-test. The cleaner modern advice is to skip Levene entirely and always use Welch, which costs essentially nothing in power when variances are equal and recovers the right alpha when they are not. Center = "median" (Brown-Forsythe) is more robust than the classic mean-centred Levene.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-4-3" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 4.3: Wilcoxon rank-sum as a robust alternative</h3>

<p class="exercise-task"><strong>Task:</strong> A skewed revenue distribution makes a two-sample t-test on <code>mtcars$mpg</code> between <code>am == 0</code> and <code>am == 1</code> look fragile to outliers. Run a Mann-Whitney / <a class="auto-link" href="Mann-Whitney-U-Test-in-R.html" title="Mann-Whitney U Test in R: Two Independent Groups, Distribution-Free">Wilcoxon rank-sum test</a> using <code>wilcox.test()</code> with the formula interface and save the htest object to <code>ex_4_3</code>, then compare its p-value to the Welch t-test.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; 	Wilcoxon rank sum test with continuity correction
#&gt;
#&gt; data:  mpg by am
#&gt; W = 42, p-value = 0.001871
#&gt; alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>When outliers make a mean-based test shaky, switch to a procedure that compares ranks rather than averages.</p><p>Call <code>wilcox.test(mpg ~ am, data = mtcars)</code> using the formula interface.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- wilcox.test(mpg ~ am, data = mtcars)
ex_4_3
#&gt; 	Wilcoxon rank sum test with continuity correction
#&gt; data:  mpg by am
#&gt; W = 42, p-value = 0.001871

t.test(mpg ~ am, data = mtcars)$p.value
#&gt; [1] 0.001373638</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Both tests reject at alpha 0.01, but Wilcoxon is testing a location shift in ranks rather than a difference of means. Use the rank-sum when (1) the data are clearly skewed and your sample is too small for the <a class="auto-link" href="Law-of-Large-Numbers-vs-CLT-in-R.html" title="Law of Large Numbers vs Central Limit Theorem: Two Laws That Are Not the Same Thing">CLT</a> to bail you out, or (2) the response is ordinal. Note that <code>wilcox.test()</code> reports W, not U; W = U + n1(n1+1)/2. R's continuity correction can be turned off with <code>correct = FALSE</code> for tiny samples where it over-shrinks the p-value.</p>

</details>

</section>

<h2>Section 5. Effect sizes, CIs & power (3 problems)</h2>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-5-1" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.1: Cohen's d for the iris Petal.Length comparison</h3>

<p class="exercise-task"><strong>Task:</strong> The htest object from Exercise 2.1 gives a p-value but no standardized <a class="auto-link" href="Effect-Size-in-R.html" title="Effect Size in R: The Number p-Values Never Tell You (Cohen's d, η², and r)">effect size</a>. Compute Cohen's d for <code>Petal.Length</code> between setosa and versicolor using the pooled standard deviation, by hand: numerator is the difference in means, denominator is the pooled SD. Save the scalar to <code>ex_5_1</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] -10.51747</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>A standardized effect size rescales the raw gap between means by the typical spread shared by the two groups.</p><p>Build the pooled SD from each group's <code>var()</code> and sample size, then divide the difference in means by it.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">g1 &lt;- iris$Petal.Length[iris$Species == &quot;setosa&quot;]
g2 &lt;- iris$Petal.Length[iris$Species == &quot;versicolor&quot;]
n1 &lt;- length(g1); n2 &lt;- length(g2)
s_pooled &lt;- sqrt(((n1 - 1) * var(g1) + (n2 - 1) * var(g2)) / (n1 + n2 - 2))
ex_5_1 &lt;- (mean(g1) - mean(g2)) / s_pooled
ex_5_1
#&gt; [1] -10.51747</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Cohen's d expresses the mean difference in pooled-SD units, so d = -10.5 means the two species centroids are over ten standard deviations apart on petal length, which is enormous by Cohen's rules of thumb (d = 0.2 small, 0.5 medium, 0.8 large). The pooled SD denominator is the conventional choice; using the SD of a single group or an averaged SD gives slightly different effect sizes (Glass's delta or Hedges' g). With unequal n the Hedges correction (1 - 3/(4(n1+n2)-9)) reduces small-sample bias.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-5-2" data-grade-mode="output-compare" data-difficulty="intermediate">

<h3 class="exercise-title">Exercise 5.2: Power calculation for a planned two-sample study</h3>

<p class="exercise-task"><strong>Task:</strong> A clinical team is planning a two-arm trial expecting a medium effect (Cohen's d = 0.5). They want 80 percent power at alpha 0.05 (two-sided). Use <code>pwr::pwr.t.test()</code> to compute the required sample size per group. Save the returned power.htest object to <code>ex_5_2</code> and read off <code>n</code>.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;      Two-sample t test power calculation
#&gt;
#&gt;               n = 63.76561
#&gt;               d = 0.5
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt;     alternative = two.sided
#&gt;
#&gt; NOTE: n is number in *each* group</code></pre>
</div>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="exercise-hints" hidden><p>Fix the expected effect, the alpha, and the power you want, and the only unknown left is how many subjects each arm needs.</p><p>Call <code>pwr.t.test()</code> with <code>d</code>, <code>sig.level</code>, <code>power</code>, and <code>type = &quot;two.sample&quot;</code>, leaving <code>n</code> unspecified.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- pwr.t.test(d = 0.5, sig.level = 0.05, power = 0.80,
                     type = &quot;two.sample&quot;, alternative = &quot;two.sided&quot;)
ex_5_2
#&gt;      Two-sample t test power calculation
#&gt;               n = 63.76561
#&gt;               d = 0.5
#&gt;       sig.level = 0.05
#&gt;           power = 0.8
#&gt;     alternative = two.sided</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> The result n = 63.77 means round UP to 64 per group, or 128 total. Always round up: rounding down would leave you short of 80 percent power. Note <code>type = &quot;two.sample&quot;</code> is critical; the default is "two.sample" but spelling it out prevents bugs when colleagues read your code. For unequal group sizes use <code>pwr.t2n.test()</code> and supply n1 and n2 directly. To bracket sensitivity, recompute at d = 0.4 and 0.6 to show how n explodes for smaller anticipated effects.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-5-3" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 5.3: Post-hoc power from an observed effect</h3>

<p class="exercise-task"><strong>Task:</strong> Using the ToothGrowth supplement comparison (Welch from Exercise 2.2), compute the observed Cohen's d, then plug it into <code>pwr.t.test()</code> with n = 30 per group to estimate the achieved power. Save the power.htest object to <code>ex_5_3</code> and note that the test was underpowered.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt;      Two-sample t test power calculation
#&gt;
#&gt;               n = 30
#&gt;               d = 0.4946386
#&gt;       sig.level = 0.05
#&gt;           power = 0.4753406
#&gt;     alternative = two.sided</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>First measure the effect the study actually observed, then ask how likely a design that size was to detect it.</p><p>Compute the observed Cohen's d from the pooled SD, then pass it plus <code>n = 30</code> to <code>pwr.t.test()</code> with <code>power</code> left out.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">g_oj &lt;- ToothGrowth$len[ToothGrowth$supp == &quot;OJ&quot;]
g_vc &lt;- ToothGrowth$len[ToothGrowth$supp == &quot;VC&quot;]
n1 &lt;- length(g_oj); n2 &lt;- length(g_vc)
s_pooled &lt;- sqrt(((n1 - 1) * var(g_oj) + (n2 - 1) * var(g_vc)) / (n1 + n2 - 2))
d_obs &lt;- (mean(g_oj) - mean(g_vc)) / s_pooled

ex_5_3 &lt;- pwr.t.test(n = 30, d = d_obs, sig.level = 0.05, type = &quot;two.sample&quot;)
ex_5_3
#&gt;               n = 30, d = 0.495, power = 0.475</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Observed power = 0.48 explains exactly why the p-value (0.06) hovered just above 0.05: the design had less than a coin-flip chance of detecting the very effect it observed. Many journals now ask authors NOT to report <a class="auto-link" href="Statistical-Power-Analysis-in-R.html" title="Power Analysis in R: Calculate the Sample Size You Need Before You Collect Any Data">post-hoc power</a> because it is mathematically equivalent to the p-value and offers no extra information. The legitimate use is exactly what we did here: to justify a larger <a class="auto-link" href="Experimental-Design-Principles-in-R.html" title="Experimental Design in R: The Three Principles That Make Results Valid and Generalisable">replication</a> study, not to retroactively explain a non-significant result.</p>

</details>

</section>

<h2>Section 6. End-to-end domain workflows (3 problems)</h2>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-6-1" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.1: Clinical trial paired BP with assumption check and CI</h3>

<p class="exercise-task"><strong>Task:</strong> A cardiology PI needs a one-paragraph summary of a paired BP trial: mean change, 95 percent CI, p-value, and a normality check on the differences. Build a small workflow that runs <code>shapiro.test()</code> on the differences, runs the paired t-test, and returns a named list with <code>shapiro</code>, <code>ttest</code>, and <code>diff_mean</code>. Save the list to <code>ex_6_1</code>.</p>

<div class="webr-container" data-block-title="Setup data">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup data</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">bp_before &lt;- c(150, 148, 155, 142, 160, 152, 145, 158, 149, 153)
bp_after  &lt;- c(140, 138, 146, 134, 150, 144, 138, 148, 141, 145)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $shapiro$p.value : ~ 0.71
#&gt; $ttest$p.value   : ~ 1.0e-8
#&gt; $diff_mean       : -8.7</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Screen the within-subject differences for normality, not the raw before and after columns, which can each be non-normal on their own.</p><p>Compute the difference vector, then build a <code>list()</code> of <code>shapiro.test()</code> on it, <code>t.test(..., paired = TRUE)</code>, and <code>mean()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_1 &lt;- # your code here
c(shapiro = ex_6_1$shapiro$p.value,
  ttest   = ex_6_1$ttest$p.value,
  diff    = ex_6_1$diff_mean)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">diffs &lt;- bp_after - bp_before
ex_6_1 &lt;- list(
  shapiro   = shapiro.test(diffs),
  ttest     = t.test(bp_before, bp_after, paired = TRUE),
  diff_mean = mean(diffs)
)
c(shapiro = ex_6_1$shapiro$p.value,
  ttest   = ex_6_1$ttest$p.value,
  diff    = ex_6_1$diff_mean)
#&gt;      shapiro        ttest         diff
#&gt; 7.080e-01 1.058e-08 -8.700e+00</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> A clinical workflow is rarely "run one test." You sequence a normality screen on the DIFFERENCES (not the raw before/after, which can each be non-normal even when their pairwise differences are normal), then the paired test, then a CI. Wrapping all three in a list keeps everything together for downstream <code>kable()</code> or <code>gtsummary</code> rendering. The CI for the mean change is the natural way to communicate effect magnitude to clinicians; p-values alone are not actionable in a clinical setting.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-6-2" data-grade-mode="output-compare" data-difficulty="advanced">

<h3 class="exercise-title">Exercise 6.2: A/B test on per-user spend with unequal allocation</h3>

<p class="exercise-task"><strong>Task:</strong> A growth analyst runs an <a class="auto-link" href="AB-Testing-in-R.html" title="A/B Testing in R: Plan Your Sample Size, Analyse Correctly, and Know When to Stop">A/B test</a> with 75 percent traffic on control and 25 percent on treatment. The per-user 30-day spend is shown below as two vectors. Run a Welch t-test plus a one-sided variant testing the marketing hypothesis that treatment lifts spend. Save a named list <code>ex_6_2</code> with elements <code>twoSided</code> and <code>oneSided</code>.</p>

<div class="webr-container" data-block-title="Setup data">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Setup data</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">set.seed(42)
spend_ctrl &lt;- round(rgamma(750, shape = 2, scale = 25), 2)
spend_trt  &lt;- round(rgamma(250, shape = 2.2, scale = 25), 2)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; $twoSided$p.value : ~ 0.085
#&gt; $oneSided$p.value : ~ 0.042</code></pre>
</div>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="exercise-hints" hidden><p>Report both the neutral two-tailed result and the directional one the marketing hypothesis actually predicted.</p><p>Build a <code>list()</code> with <code>t.test(spend_trt, spend_ctrl)</code> and the same call plus <code>alternative = &quot;greater&quot;</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- # your code here
sapply(ex_6_2, function(h) h$p.value)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_2 &lt;- list(
  twoSided = t.test(spend_trt, spend_ctrl),
  oneSided = t.test(spend_trt, spend_ctrl, alternative = &quot;greater&quot;)
)
sapply(ex_6_2, function(h) h$p.value)
#&gt;   twoSided   oneSided
#&gt; 0.08470     0.04235</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Two practical points for A/B tests. First, gamma-distributed revenue violates normality; the CLT rescues a t-test at n = 750 and 250, but for n < ~50 per arm you should use a Mann-Whitney or a permutation test instead. Second, the one-sided test halves the two-sided p-value only when the observed sign matches the hypothesis. Pre-register one-sidedness; post-hoc switching is p-hacking. Many companies report both two-sided p-values and a separate predicted direction in dashboards.</p>

</details>

</section>

<section class="exercise" data-exercise-id="T-Test-Exercises-in-R-ex-6-3" data-grade-mode="output-compare" data-difficulty="beginner">

<h3 class="exercise-title">Exercise 6.3: A reusable APA-style reporter function</h3>

<p class="exercise-task"><strong>Task:</strong> Write a function <code>apa_t</code> that takes an <code>htest</code> object (from <code>t.test</code>) and returns a one-line APA-formatted character string with t, df, p, and 95 percent CI. Save the function itself to <code>ex_6_3</code> and demonstrate it on the htest from Exercise 1.1.</p>

<div class="exercise-expected">
<p><strong>Expected result:</strong></p>
<pre><code>#&gt; [1] &quot;t(149) = -0.39, p = 0.697, 95% CI [5.71, 5.98]&quot;</code></pre>
</div>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="exercise-hints" hidden><p>Pull the reporting pieces straight off the test object and stitch them into a single formatted line.</p><p>Write a <code>function(h)</code> that reads <code>h$parameter</code>, <code>h$statistic</code>, <code>h$p.value</code>, and <code>h$conf.int</code>, then assembles them with <code>sprintf()</code>.</p></div>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- # your code here
ex_6_3(ex_1_1)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details class="exercise-solution">
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_6_3 &lt;- function(h) {
  sprintf(&quot;t(%g) = %.2f, p = %.3f, 95%% CI [%.2f, %.2f]&quot;,
          h$parameter, h$statistic, h$p.value,
          h$conf.int[1], h$conf.int[2])
}
ex_6_3(ex_1_1)
#&gt; [1] &quot;t(149) = -0.39, p = 0.697, 95% CI [5.71, 5.98]&quot;</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p class="exercise-explanation"><strong>Explanation:</strong> Reporters that wrap repeated stats output pay for themselves after the third paste. APA style asks for italic t and df; in markdown you would wrap the t and df in underscores. For p-values below 0.001 the convention is to print "p < 0.001" rather than the exact tiny value, which a robust function would handle with <code>if (h$p.value &lt; 0.001) &quot;p &lt; .001&quot; else sprintf(&quot;p = %.3f&quot;, h$p.value)</code>. Pairing this with <code>broom::tidy()</code> gives you a tibble row per test, ideal for batch reporting.</p>

</details>

</section>

<h2>What to do next</h2>

<ul>

<li><a href="t-Tests-in-R.html">t-Tests in R</a> is the conceptual companion: every variant, when to use it, and the decision rule for picking between Welch, Student, and paired.</li>

<li><a href="ANOVA-Exercises-in-R.html">ANOVA Exercises in R</a> extends two-group comparisons to three or more groups when a t-test is no longer the right tool.</li>

<li><a href="Power-Analysis-Exercises-in-R.html">Power Analysis Exercises in R</a> drills deeper into sample size planning beyond the two problems here.</li>

<li><a href="Linear-Regression-Exercises-in-R.html">Linear Regression Exercises in R</a> is the next step once you start adding covariates to a two-group comparison.</li>

</ul>

{% endraw %}