---
title: "tidyr Reshaping Exercises in R: 18 Real-World Practice Problems"
description: "Practice tidyr reshaping with 18 scenario-based problems: pivot_longer, pivot_wider, names_sep, names_pattern, .value, separate, complete, fill. Hidden solutions."
keywords: "tidyr exercises, pivot_longer exercises, pivot_wider exercises, tidyr reshaping exercises, reshape data in R, wide to long R, long to wide R, tidyr practice"
mathjax: false
webr: true
post_type: "EX"
auto_link_terms: "tidyr exercises|pivot_longer exercises|pivot_wider exercises|tidyr reshaping exercises|reshape data exercises in r"
auto_link_case_sensitive: false
sidebar_title: "tidyr Reshaping Exercises"
sidebar_order: "150"
fr_parent: "pivot_longer-pivot_wider-Reshape-Data-in-R.html"
---
{% raw %}
<!-- md2html:generated -->

<h1>tidyr Reshaping Exercises in R: 18 Real-World Practice Problems</h1>

<p class="lead">Eighteen scenario-based tidyr reshaping exercises grouped into five themed sections covering pivot_longer, pivot_wider, names_sep, names_pattern, the .value sentinel, separate, unite, complete, and fill. Every problem ships with an expected result, and solutions are hidden behind reveal toggles so you actually try first.</p>

<div class="engagement-header" data-difficulty="Mixed" data-time="40" data-exercises="18" data-xp="270"></div>

<div class="webr-container" data-block-title="Run this once before any exercise">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Run this once before any exercise</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">library(tidyr)
library(dplyr)
library(tibble)</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<h2>Section 1. pivot_longer basics (4 problems)</h2>

<h3>Exercise 1.1: Reshape relig_income into long format with pivot_longer</h3>

<p><strong>Task:</strong> A demographic researcher needs to reshape the built-in tidyr dataset <code>relig_income</code>, which stores 18 US religions across 10 income-bracket columns, into a long-format tibble where each religion-bracket pair is its own row. Use <code>pivot_longer()</code> with <code>cols = -religion</code> to fold the 10 bracket columns into a key column called <code>bracket</code> and a value column called <code>count</code>. Save the result to <code>ex_1_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 180 x 3
#&gt;   religion bracket           count
#&gt;   &lt;chr&gt;    &lt;chr&gt;             &lt;dbl&gt;
#&gt; 1 Agnostic &lt;$10k                27
#&gt; 2 Agnostic $10-20k              34
#&gt; 3 Agnostic $20-30k              60
#&gt; 4 Agnostic $30-40k              81
#&gt; 5 Agnostic $40-50k              76
#&gt; 6 Agnostic $50-75k             137
#&gt; # 174 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- # your code here
ex_1_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_1 &lt;- pivot_longer(
  relig_income,
  cols      = -religion,
  names_to  = &quot;bracket&quot;,
  values_to = &quot;count&quot;
)
ex_1_1
#&gt; # A tibble: 180 x 3
#&gt;   religion bracket  count
#&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 Agnostic &lt;$10k       27
#&gt; 2 Agnostic $10-20k     34
#&gt; ...</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>cols = -religion</code> is the negative-selection idiom: pick every column EXCEPT <code>religion</code>. Eighteen rows times ten bracket columns produces 180 long rows. The <code>names_to</code> argument labels the new key column and <code>values_to</code> labels the value column. Cleaner than <code>gather()</code> (the deprecated predecessor), because the column-selection helpers are aligned with <code>dplyr::select()</code>.</p>

</details>

<h3>Exercise 1.2: Pivot only the first six weeks of billboard</h3>

<p><strong>Task:</strong> The chart historian working with the tidyr <code>billboard</code> dataset only cares about the first six weeks of each track's run, not all 76 weekly columns. Use <code>pivot_longer()</code> with <code>cols = wk1:wk6</code> so only those six columns are folded into a <code>week</code> key and <code>rank</code> value column, keeping <code>artist</code>, <code>track</code>, and <code>date.entered</code> as id columns, and drop NA ranks with <code>values_drop_na = TRUE</code>. Save to <code>ex_1_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 1,902 x 5
#&gt;   artist  track                   date.entered week   rank
#&gt;   &lt;chr&gt;   &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt; &lt;dbl&gt;
#&gt; 1 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk1      87
#&gt; 2 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk2      82
#&gt; 3 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk3      72
#&gt; ...
#&gt; # 1,896 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- # your code here
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_2 &lt;- pivot_longer(
  billboard,
  cols             = wk1:wk6,
  names_to         = &quot;week&quot;,
  values_to        = &quot;rank&quot;,
  values_drop_na   = TRUE
)
ex_1_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>wk1:wk6</code> uses the column-range selector (positional, between named columns) so only six of the 76 weekly columns participate. <code>values_drop_na = TRUE</code> discards rows where the track had not yet entered or had already exited the chart in that week, which is the natural behavior for time-series-style ranks. Without it, the result would be 317 * 6 = 1902 rows minus drops; with NA rows kept you carry useless padding.</p>

</details>

<h3>Exercise 1.3: Strip the wk prefix and cast week to integer</h3>

<p><strong>Task:</strong> Continuing the billboard analysis, your downstream plotting code expects <code>week</code> to be a clean integer rather than strings like <code>wk3</code>. Redo the pivot from Exercise 1.2 using <code>cols = wk1:wk6</code> but add <code>names_prefix = &quot;wk&quot;</code> to strip the literal prefix and <code>names_transform = list(week = as.integer)</code> to coerce the resulting key column to integer in one pass. Save to <code>ex_1_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 1,902 x 5
#&gt;   artist  track                   date.entered  week  rank
#&gt;   &lt;chr&gt;   &lt;chr&gt;                   &lt;date&gt;       &lt;int&gt; &lt;dbl&gt;
#&gt; 1 2 Pac   Baby Don't Cry (Keep...  2000-02-26      1    87
#&gt; 2 2 Pac   Baby Don't Cry (Keep...  2000-02-26      2    82
#&gt; ...</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- # your code here
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_3 &lt;- pivot_longer(
  billboard,
  cols             = wk1:wk6,
  names_to         = &quot;week&quot;,
  values_to        = &quot;rank&quot;,
  names_prefix     = &quot;wk&quot;,
  names_transform  = list(week = as.integer),
  values_drop_na   = TRUE
)
ex_1_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Doing the strip-and-cast inline avoids a follow-up <code>mutate(week = as.integer(...))</code> and keeps the type clean from the moment the column is born. <code>names_prefix</code> accepts a regular expression, so <code>&quot;wk&quot;</code> would also drop a literal <code>&quot;wks&quot;</code> if it appeared. A common mistake is using <code>parse_number()</code> post-pivot, which works but loses the chain. For a column that already lacks a prefix, omit <code>names_prefix</code> and use only <code>names_transform</code>.</p>

</details>

<h3>Exercise 1.4: Find each track's peak chart position</h3>

<p><strong>Task:</strong> The chart historian now wants every track's all-time peak ranking across the full 76 weeks. Pivot every <code>wk*</code> column to long form using <code>cols = starts_with(&quot;wk&quot;)</code> with <code>values_drop_na = TRUE</code>, then group by <code>artist</code> and <code>track</code>, <a class="auto-link" href="dplyr-group-by-summarise.html" title="dplyr group_by() + summarise(): The Combination That Answers Most Business Questions">summarise</a> to take <code>min(rank)</code> as <code>peak_rank</code>, and sort ascending so the strongest performers float to the top. Save the result to <code>ex_1_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 317 x 3
#&gt;   artist                 track                       peak_rank
#&gt;   &lt;chr&gt;                  &lt;chr&gt;                           &lt;dbl&gt;
#&gt; 1 Destiny's Child        Independent Women Part I            1
#&gt; 2 Santana                Maria, Maria                        1
#&gt; 3 Savage Garden          I Knew I Loved You                  1
#&gt; 4 Madonna                Music                               1
#&gt; 5 Aguilera, Christina    Come On Over Baby (All I W...       1
#&gt; # 312 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- # your code here
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_1_4 &lt;- billboard |&gt;
  pivot_longer(
    cols           = starts_with(&quot;wk&quot;),
    names_to       = &quot;week&quot;,
    values_to      = &quot;rank&quot;,
    values_drop_na = TRUE
  ) |&gt;
  group_by(artist, track) |&gt;
  summarise(peak_rank = min(rank), .groups = &quot;drop&quot;) |&gt;
  arrange(peak_rank)
ex_1_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>starts_with(&quot;wk&quot;)</code> is the tidyselect helper that grabs every column whose name begins with the prefix, future-proofing against more weekly columns being added. The pivot turns each track-week pair into a row, the group-and-summarise then collapses each track back to its best showing. Dropping NAs is essential here: without it, <code>min()</code> would return <code>NA</code> for any track that hit the chart even briefly before exiting.</p>

</details>

<h2>Section 2. pivot_wider basics (3 problems)</h2>

<h3>Exercise 2.1: Reshape fish_encounters from long to wide</h3>

<p><strong>Task:</strong> The conservation team has the built-in tidyr <code>fish_encounters</code> dataset listing whether each of 19 fish was seen at each of 11 monitoring stations in long form (<code>fish</code>, <code>station</code>, <code>seen</code>). Reshape it so each row is one fish and each column is a station with the <code>seen</code> flag in the cells, using <code>pivot_wider(names_from = station, values_from = seen)</code>. Save the result to <code>ex_2_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 19 x 12
#&gt;   fish  Release I80_1   Lisbon  Rstr  Base_TD   BCE   BCW   BCE2  BCW2   MAE   MAW
#&gt;   &lt;fct&gt;   &lt;int&gt; &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1 4842        1     1       1       1       1     1     1     1     1     1     1
#&gt; 2 4843        1     1       1       1       1     1     1     1     1     1     1
#&gt; 3 4844        1     1       1       1       1     1     1     1     1     1     1
#&gt; 4 4845        1     1       1       1       1    NA    NA    NA    NA    NA    NA
#&gt; # 15 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Beginner</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- # your code here
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_1 &lt;- pivot_wider(
  fish_encounters,
  names_from  = station,
  values_from = seen
)
ex_2_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>pivot_wider()</code> is the exact inverse of <code>pivot_longer()</code>: the column you point to with <code>names_from</code> supplies the new column names, and the column you point to with <code>values_from</code> supplies the cell values. Any combination of fish-and-station that did not appear in the long source becomes an <code>NA</code> in the wide result, which is why fish 4845 has NAs from station <code>BCE</code> onward. The default <code>values_fill = NA</code> produces this behavior; Exercise 2.2 swaps it out.</p>

</details>

<h3>Exercise 2.2: Replace NA cells with zero using values_fill</h3>

<p><strong>Task:</strong> The previous reshape left <code>NA</code> in every cell where a fish was never observed at a station, but the downstream report expects zeros there instead so absence is encoded numerically. Repeat the <code>pivot_wider()</code> call on <code>fish_encounters</code> and add <code>values_fill = 0</code> so absent observations are encoded as 0 rather than NA. Save the result to <code>ex_2_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 19 x 12
#&gt;   fish  Release I80_1 Lisbon  Rstr Base_TD   BCE   BCW   BCE2  BCW2   MAE   MAW
#&gt;   &lt;fct&gt;   &lt;int&gt; &lt;int&gt;  &lt;int&gt; &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1 4842        1     1      1     1       1     1     1      1     1     1     1
#&gt; 2 4845        1     1      1     1       1     0     0      0     0     0     0
#&gt; ...</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- # your code here
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_2 &lt;- pivot_wider(
  fish_encounters,
  names_from  = station,
  values_from = seen,
  values_fill = 0
)
ex_2_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>values_fill</code> accepts either a single scalar (applied to every value column) or a <a class="auto-link" href="R-Lists.html" title="R Lists: When Data Frames Aren't Flexible Enough (Complete Guide)">named list</a> (per-value-column fills). For binary presence flags, zero is the right semantic default: it means observed-absent rather than unknown. Passing <code>values_fill = list(seen = 0L)</code> would be the most explicit form and is preferred when you have multiple value columns with different natural defaults.</p>

</details>

<h3>Exercise 2.3: Pivot a tidy summary back to a reporting matrix</h3>

<p><strong>Task:</strong> A finance analyst has a tidy three-column summary tibble (built inline below) with <code>region</code>, <code>quarter</code>, and <code>revenue</code>, and needs to hand it to leadership formatted as a region-by-quarter matrix where rows are regions and columns are the four quarters. Use <code>pivot_wider(names_from = quarter, values_from = revenue)</code> on the inline tibble and save to <code>ex_2_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 5
#&gt;   region    Q1    Q2    Q3    Q4
#&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 North    120   135   150   165
#&gt; 2 South     90   100   110   125
#&gt; 3 East     150   160   170   190</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">revenue_long &lt;- tribble(
  ~region, ~quarter, ~revenue,
  &quot;North&quot;, &quot;Q1&quot;, 120, &quot;North&quot;, &quot;Q2&quot;, 135, &quot;North&quot;, &quot;Q3&quot;, 150, &quot;North&quot;, &quot;Q4&quot;, 165,
  &quot;South&quot;, &quot;Q1&quot;,  90, &quot;South&quot;, &quot;Q2&quot;, 100, &quot;South&quot;, &quot;Q3&quot;, 110, &quot;South&quot;, &quot;Q4&quot;, 125,
  &quot;East&quot;,  &quot;Q1&quot;, 150, &quot;East&quot;,  &quot;Q2&quot;, 160, &quot;East&quot;,  &quot;Q3&quot;, 170, &quot;East&quot;,  &quot;Q4&quot;, 190
)

ex_2_3 &lt;- # your code here
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_2_3 &lt;- pivot_wider(
  revenue_long,
  names_from  = quarter,
  values_from = revenue
)
ex_2_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> This is the most common reporting flip: analysts model and aggregate in long form (one row per region-quarter) because that is the shape every dplyr verb expects, then pivot wide only at the very end for human-readable display. Resist the temptation to keep data wide upstream: a tidy long table joins, filters, and groups cleanly, while a wide one fights every verb you throw at it.</p>

</details>

<h2>Section 3. Advanced pivot_longer (4 problems)</h2>

<h3>Exercise 3.1: Split encoded column names with names_sep</h3>

<p><strong>Task:</strong> A health-records inline tibble (built below) has columns <code>male_old</code>, <code>male_young</code>, <code>female_old</code>, <code>female_young</code>, where the column names encode TWO variables (sex and age group) joined by <code>_</code>. Pivot to long form using <code>pivot_longer()</code> with <code>names_to = c(&quot;sex&quot;, &quot;age&quot;)</code> and <code>names_sep = &quot;_&quot;</code> so the joined column names split into two clean key columns plus one value column called <code>n</code>. Save to <code>ex_3_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 12 x 4
#&gt;   country sex    age       n
#&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt;
#&gt; 1 US      male   old      42
#&gt; 2 US      male   young    18
#&gt; 3 US      female old      55
#&gt; 4 US      female young    23
#&gt; 5 UK      male   old      31
#&gt; # 7 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">health &lt;- tribble(
  ~country, ~male_old, ~male_young, ~female_old, ~female_young,
  &quot;US&quot;,     42,        18,           55,          23,
  &quot;UK&quot;,     31,        14,           40,          19,
  &quot;DE&quot;,     27,        12,           36,          17
)

ex_3_1 &lt;- # your code here
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_1 &lt;- pivot_longer(
  health,
  cols      = -country,
  names_to  = c(&quot;sex&quot;, &quot;age&quot;),
  names_sep = &quot;_&quot;,
  values_to = &quot;n&quot;
)
ex_3_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> When <code>names_to</code> is a character vector of length two and <code>names_sep</code> is given, each old column name is split into that many pieces and each piece becomes a value in the corresponding key column. Three countries times four columns produces 12 long rows. Without <code>names_sep</code>, you would get a single column called <code>&quot;sex_age&quot;</code> with values like <code>&quot;male_old&quot;</code>, forcing a follow-up <code>separate()</code> call.</p>

</details>

<h3>Exercise 3.2: Extract two key columns with a regex via names_pattern</h3>

<p><strong>Task:</strong> A macroeconomic inline tibble (built below) has columns like <code>gdp_2020</code>, <code>gdp_2021</code>, <code>pop_2020</code>, <code>pop_2021</code>. Use <code>pivot_longer()</code> with <code>names_to = c(&quot;metric&quot;, &quot;year&quot;)</code> and <code>names_pattern = &quot;(gdp|pop)_(\\d+)&quot;</code> to capture both pieces, then add <code>names_transform = list(year = as.integer)</code> so year lands as integer. Save the result to <code>ex_3_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 12 x 4
#&gt;   country metric  year value
#&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;
#&gt; 1 US      gdp     2020 21000
#&gt; 2 US      gdp     2021 23000
#&gt; 3 US      pop     2020   331
#&gt; 4 US      pop     2021   332
#&gt; 5 UK      gdp     2020  2800
#&gt; # 7 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">econ &lt;- tribble(
  ~country, ~gdp_2020, ~gdp_2021, ~pop_2020, ~pop_2021,
  &quot;US&quot;,     21000,     23000,     331,       332,
  &quot;UK&quot;,      2800,      3100,      67,        67,
  &quot;DE&quot;,      3800,      4200,      83,        84
)

ex_3_2 &lt;- # your code here
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_2 &lt;- pivot_longer(
  econ,
  cols             = -country,
  names_to         = c(&quot;metric&quot;, &quot;year&quot;),
  names_pattern    = &quot;(gdp|pop)_(\\d+)&quot;,
  values_to        = &quot;value&quot;,
  names_transform  = list(year = as.integer)
)
ex_3_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Use <code>names_pattern</code> (regex with one capture group per <code>names_to</code> entry) when the separator is ambiguous or when you need precise control over what each piece looks like. The pattern <code>(gdp|pop)_(\d+)</code> says: first capture is the literal <code>gdp</code> or <code>pop</code>, second capture is one or more digits. Compared to <code>names_sep = &quot;_&quot;</code> this is safer because it rejects malformed column names instead of silently splitting them in surprising ways.</p>

</details>

<h3>Exercise 3.3: Spread paired columns with the .value sentinel</h3>

<p><strong>Task:</strong> The built-in tidyr <code>household</code> dataset has columns <code>dob_child1</code>, <code>dob_child2</code>, <code>name_child1</code>, <code>name_child2</code>, where each child contributes two parallel columns. Use <code>pivot_longer()</code> with <code>names_to = c(&quot;.value&quot;, &quot;child&quot;)</code> and <code>names_sep = &quot;_&quot;</code> so the <code>dob</code> and <code>name</code> prefixes become their own columns and <code>child</code> (containing <code>&quot;child1&quot;</code> or <code>&quot;child2&quot;</code>) becomes the long-form id. Save the result to <code>ex_3_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 8 x 4
#&gt;   family child  dob        name
#&gt;    &lt;int&gt; &lt;chr&gt;  &lt;date&gt;     &lt;chr&gt;
#&gt; 1      1 child1 1998-11-26 Susan
#&gt; 2      1 child2 NA         NA
#&gt; 3      2 child1 1996-06-22 Mark
#&gt; 4      2 child2 NA         NA
#&gt; 5      3 child1 2002-07-11 Sam
#&gt; 6      3 child2 2004-04-05 Seth
#&gt; # 2 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- # your code here
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_3 &lt;- pivot_longer(
  household,
  cols      = -family,
  names_to  = c(&quot;.value&quot;, &quot;child&quot;),
  names_sep = &quot;_&quot;
)
ex_3_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> The <code>.value</code> sentinel is the killer feature for paired columns. When <code>names_to</code> contains <code>&quot;.value&quot;</code>, the matching piece of each old column name becomes the NEW column name in the result rather than a value inside a key column. Four old columns collapse into two value columns (<code>dob</code>, <code>name</code>) plus one new key column (<code>child</code>). Without <code>.value</code> you would get a single value column smashing dates and strings together, type-coerced to character.</p>

</details>

<h3>Exercise 3.4: Convert numeric stems with names_transform</h3>

<p><strong>Task:</strong> A field-survey inline tibble (built below) stores depth readings in columns <code>depth_5</code>, <code>depth_10</code>, <code>depth_15</code>, <code>depth_20</code> (the suffix is meters). Pivot to long using <code>names_prefix = &quot;depth_&quot;</code> to strip the literal stem, then ensure the new <code>depth</code> key is numeric using <code>names_transform = list(depth = as.numeric)</code> so it can sit on a continuous axis. Save to <code>ex_3_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 12 x 3
#&gt;   site  depth reading
#&gt;   &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1 A         5    18.2
#&gt; 2 A        10    17.4
#&gt; 3 A        15    16.1
#&gt; 4 A        20    14.3
#&gt; 5 B         5    19.0
#&gt; # 7 more rows hidden</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">survey &lt;- tribble(
  ~site, ~depth_5, ~depth_10, ~depth_15, ~depth_20,
  &quot;A&quot;,   18.2,     17.4,      16.1,      14.3,
  &quot;B&quot;,   19.0,     18.1,      16.8,      15.0,
  &quot;C&quot;,   17.5,     16.7,      15.4,      13.7
)

ex_3_4 &lt;- # your code here
ex_3_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_3_4 &lt;- pivot_longer(
  survey,
  cols             = -site,
  names_to         = &quot;depth&quot;,
  values_to        = &quot;reading&quot;,
  names_prefix     = &quot;depth_&quot;,
  names_transform  = list(depth = as.numeric)
)
ex_3_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Stripping the prefix turns <code>depth_15</code> into <code>&quot;15&quot;</code>, but it is still a character. <code>names_transform</code> lets you coerce in the same call so the column is born as numeric and behaves correctly on plot axes and joins. A common mistake is reaching for <code>as.integer</code> here: it would silently drop fractional depths if any appeared. <code>as.numeric</code> (double) is the safer default.</p>

</details>

<h2>Section 4. Advanced pivot_wider (3 problems)</h2>

<h3>Exercise 4.1: Spread two value columns at once</h3>

<p><strong>Task:</strong> A student-scores inline tibble (built below) has one row per student-subject containing both a <code>score</code> and a <code>grade</code> letter. Use <code>pivot_wider(names_from = subject, values_from = c(score, grade))</code> so each student gets one row with paired score and grade columns per subject, producing names like <code>score_math</code> and <code>grade_math</code>. Save the result to <code>ex_4_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 3 x 5
#&gt;   student  score_math  score_eng grade_math grade_eng
#&gt;   &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;  &lt;chr&gt;      &lt;chr&gt;
#&gt; 1 Ada            92         88   A          B
#&gt; 2 Bea            78         95   C          A
#&gt; 3 Cy             85         80   B          B</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">scores &lt;- tribble(
  ~student, ~subject, ~score, ~grade,
  &quot;Ada&quot;,    &quot;math&quot;,      92,  &quot;A&quot;,
  &quot;Ada&quot;,    &quot;eng&quot;,       88,  &quot;B&quot;,
  &quot;Bea&quot;,    &quot;math&quot;,      78,  &quot;C&quot;,
  &quot;Bea&quot;,    &quot;eng&quot;,       95,  &quot;A&quot;,
  &quot;Cy&quot;,     &quot;math&quot;,      85,  &quot;B&quot;,
  &quot;Cy&quot;,     &quot;eng&quot;,       80,  &quot;B&quot;
)

ex_4_1 &lt;- # your code here
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_1 &lt;- pivot_wider(
  scores,
  names_from  = subject,
  values_from = c(score, grade)
)
ex_4_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> Passing a vector to <code>values_from</code> produces one new column PER value-input PER name-input, with names auto-generated as <code>{value}_{name}</code>. Two subjects times two value columns gives four new columns. If you do not like the auto naming, swap in <code>names_glue</code> to take control: <code>names_glue = &quot;{subject}.{.value}&quot;</code> would produce <code>math.score</code>, <code>eng.score</code>, and so on.</p>

</details>

<h3>Exercise 4.2: Aggregate duplicate cells with values_fn = sum</h3>

<p><strong>Task:</strong> A retail manager has a transaction log inline tibble (built below) where each row is a sale with <code>store</code>, <code>product</code>, and <code>units_sold</code>, and a store may post multiple sales for the same product. Pivot to a store-by-product matrix that SUMS units, using <code>values_fn = sum</code> inside <code>pivot_wider()</code> to aggregate duplicate combinations rather than crashing with a list-column warning. Save the result to <code>ex_4_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 2 x 4
#&gt;   store    Widget Gadget Gizmo
#&gt;   &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 NorthSt      12      7     5
#&gt; 2 SouthSt       8     11     3</code></pre>

<p><strong>Difficulty:</strong> Advanced</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">sales &lt;- tribble(
  ~store,     ~product,  ~units_sold,
  &quot;NorthSt&quot;,  &quot;Widget&quot;,   5,
  &quot;NorthSt&quot;,  &quot;Widget&quot;,   7,
  &quot;NorthSt&quot;,  &quot;Gadget&quot;,   7,
  &quot;NorthSt&quot;,  &quot;Gizmo&quot;,    5,
  &quot;SouthSt&quot;,  &quot;Widget&quot;,   8,
  &quot;SouthSt&quot;,  &quot;Gadget&quot;,   6,
  &quot;SouthSt&quot;,  &quot;Gadget&quot;,   5,
  &quot;SouthSt&quot;,  &quot;Gizmo&quot;,    3
)

ex_4_2 &lt;- # your code here
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_2 &lt;- pivot_wider(
  sales,
  names_from  = product,
  values_from = units_sold,
  values_fn   = sum
)
ex_4_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> When the <code>(name_id, value_id)</code> pairs are not unique, <code>pivot_wider()</code> cannot decide which value to drop into a cell, so by default it stuffs all values into a list-column and warns. <code>values_fn = sum</code> says aggregate-then-drop; you could pass <code>mean</code>, <code>max</code>, or any reducer that accepts a numeric vector. The alternative pattern is to <code>group_by()</code> and <code>summarise()</code> upstream so the input is already unique, then pivot without <code>values_fn</code>. Either works; <code>values_fn</code> is faster to type.</p>

</details>

<h3>Exercise 4.3: Build custom column names with names_glue</h3>

<p><strong>Task:</strong> The portfolio team wants column names like <code>Q1_revenue</code>, <code>Q1_cost</code>, <code>Q2_revenue</code>, <code>Q2_cost</code> from a tidy quarter-by-metric inline tibble (built below). Use <code>pivot_wider()</code> with <code>names_from = c(quarter, metric)</code> and <code>names_glue = &quot;{quarter}_{metric}&quot;</code> to produce the custom naming layout instead of the default underscore-joined order. Save the result to <code>ex_4_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 2 x 5
#&gt;   region   Q1_revenue Q1_cost Q2_revenue Q2_cost
#&gt;   &lt;chr&gt;         &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1 North           120      80        135      85
#&gt; 2 South            90      60        100      62</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">finance &lt;- tribble(
  ~region, ~quarter, ~metric,    ~value,
  &quot;North&quot;, &quot;Q1&quot;,     &quot;revenue&quot;,  120,
  &quot;North&quot;, &quot;Q1&quot;,     &quot;cost&quot;,      80,
  &quot;North&quot;, &quot;Q2&quot;,     &quot;revenue&quot;,  135,
  &quot;North&quot;, &quot;Q2&quot;,     &quot;cost&quot;,      85,
  &quot;South&quot;, &quot;Q1&quot;,     &quot;revenue&quot;,   90,
  &quot;South&quot;, &quot;Q1&quot;,     &quot;cost&quot;,      60,
  &quot;South&quot;, &quot;Q2&quot;,     &quot;revenue&quot;,  100,
  &quot;South&quot;, &quot;Q2&quot;,     &quot;cost&quot;,      62
)

ex_4_3 &lt;- # your code here
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_4_3 &lt;- pivot_wider(
  finance,
  names_from  = c(quarter, metric),
  values_from = value,
  names_glue  = &quot;{quarter}_{metric}&quot;
)
ex_4_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>names_glue</code> accepts a glue template string where each placeholder refers to a column listed in <code>names_from</code>. The default join would also produce <code>Q1_revenue</code>-style names here, but <code>names_glue</code> becomes essential when you want to insert a constant, change separators per-column, or rearrange the order (<code>&quot;{metric}-{quarter}&quot;</code> would give <code>revenue-Q1</code>). Glue templates <a class="auto-link" href="R-Function-Operators.html" title="R Function Operators: Compose, Negate & Partial Application">compose</a> cleanly with <code>dplyr::rename_with()</code> if you want post-hoc adjustments.</p>

</details>

<h2>Section 5. Companion verbs: separate, unite, complete, fill (4 problems)</h2>

<h3>Exercise 5.1: Split full_name into first and last with separate_wider_delim</h3>

<p><strong>Task:</strong> A data-entry sheet has a single <code>full_name</code> column with values like <code>&quot;Ada Lovelace&quot;</code> and <code>&quot;Alan Turing&quot;</code>, but downstream code expects <code>first</code> and <code>last</code> as separate columns. Use the modern <code>separate_wider_delim()</code> from tidyr 1.3+ with <code>delim = &quot; &quot;</code> and <code>names = c(&quot;first&quot;, &quot;last&quot;)</code> to split on the space, applied to the inline tibble of five names below. Save the result to <code>ex_5_1</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 5 x 2
#&gt;   first    last
#&gt;   &lt;chr&gt;    &lt;chr&gt;
#&gt; 1 Ada      Lovelace
#&gt; 2 Alan     Turing
#&gt; 3 Grace    Hopper
#&gt; 4 Donald   Knuth
#&gt; 5 Margaret Hamilton</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">people &lt;- tibble(full_name = c(
  &quot;Ada Lovelace&quot;, &quot;Alan Turing&quot;, &quot;Grace Hopper&quot;,
  &quot;Donald Knuth&quot;, &quot;Margaret Hamilton&quot;
))

ex_5_1 &lt;- # your code here
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_1 &lt;- separate_wider_delim(
  people,
  cols  = full_name,
  delim = &quot; &quot;,
  names = c(&quot;first&quot;, &quot;last&quot;)
)
ex_5_1</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>separate_wider_delim()</code> is the tidyr 1.3+ replacement for the older <code>separate()</code>. It is stricter by default: if any row has the wrong number of pieces, it errors loudly rather than silently filling with NA. For names with middle parts, pass <code>too_many = &quot;merge&quot;</code> to glue extras into the last piece. The <code>_wider_</code> naming convention echoes the pivot family: <code>_wider_</code> adds columns, <code>_longer_</code> would add rows.</p>

</details>

<h3>Exercise 5.2: Reunite year/month/day into an ISO date string</h3>

<p><strong>Task:</strong> An export pipeline split a timestamp into separate <code>year</code>, <code>month</code>, and <code>day</code> integer columns, but the downstream API expects a single ISO-style <code>date</code> string like <code>&quot;2024-03-15&quot;</code>. Use <code>unite()</code> on the inline tibble below with <code>col = &quot;date&quot;</code>, the three columns in order, and <code>sep = &quot;-&quot;</code> to merge the three components back into one column. Save the result to <code>ex_5_2</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 5 x 1
#&gt;   date
#&gt;   &lt;chr&gt;
#&gt; 1 2024-01-12
#&gt; 2 2024-02-04
#&gt; 3 2024-03-15
#&gt; 4 2024-04-22
#&gt; 5 2024-05-30</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">parts &lt;- tribble(
  ~year, ~month, ~day,
  2024,    &quot;01&quot;,   &quot;12&quot;,
  2024,    &quot;02&quot;,   &quot;04&quot;,
  2024,    &quot;03&quot;,   &quot;15&quot;,
  2024,    &quot;04&quot;,   &quot;22&quot;,
  2024,    &quot;05&quot;,   &quot;30&quot;
)

ex_5_2 &lt;- # your code here
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_2 &lt;- unite(parts, col = &quot;date&quot;, year, month, day, sep = &quot;-&quot;)
ex_5_2</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>unite()</code> is the natural inverse of <code>separate()</code> and the same logic as base R <code>paste(..., sep = &quot;-&quot;)</code> but column-aware. By default the source columns are dropped; pass <code>remove = FALSE</code> to keep them alongside the new combined column. To get a real <code>Date</code> object instead of a string, follow up with <code>mutate(date = as.Date(date))</code> or skip <code>unite</code> entirely and use <code>lubridate::make_date(year, month, day)</code>.</p>

</details>

<h3>Exercise 5.3: Complete missing date-by-category combinations</h3>

<p><strong>Task:</strong> A sensor log inline tibble (built below) has readings only on days where a sensor reported, so days with no signal are silently absent. Use <code>complete(date, sensor_id, fill = list(reading = 0))</code> to materialize every date-by-sensor combination explicitly, filling the previously absent <code>reading</code> cells with 0 instead of NA. Save the result to <code>ex_5_3</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 6 x 3
#&gt;   date       sensor_id reading
#&gt;   &lt;date&gt;     &lt;chr&gt;       &lt;dbl&gt;
#&gt; 1 2024-06-01 S1            12
#&gt; 2 2024-06-01 S2             0
#&gt; 3 2024-06-02 S1            14
#&gt; 4 2024-06-02 S2             9
#&gt; 5 2024-06-03 S1             0
#&gt; 6 2024-06-03 S2            11</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">sensors &lt;- tribble(
  ~date,                ~sensor_id, ~reading,
  as.Date(&quot;2024-06-01&quot;), &quot;S1&quot;,       12,
  as.Date(&quot;2024-06-02&quot;), &quot;S1&quot;,       14,
  as.Date(&quot;2024-06-02&quot;), &quot;S2&quot;,        9,
  as.Date(&quot;2024-06-03&quot;), &quot;S2&quot;,       11
)

ex_5_3 &lt;- # your code here
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_3 &lt;- complete(
  sensors,
  date, sensor_id,
  fill = list(reading = 0)
)
ex_5_3</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>complete()</code> builds the Cartesian product of the values seen in the columns you pass, joins it against the original data, and keeps the union. Missing rows are added with NA in unspecified columns, but <code>fill = list(reading = 0)</code> lets you replace those NAs at birth. This is the canonical move before plotting <a class="auto-link" href="Time-Series-Analysis-With-R.html" title="Time Series Analysis with R">time series</a> so gaps look like genuine zeros instead of disappearing lines. For dense full-range completion, pair with <code>tidyr::full_seq()</code> to enumerate every date.</p>

</details>

<h3>Exercise 5.4: Carry forward report dates with fill</h3>

<p><strong>Task:</strong> A daily-report inline tibble (built below) lists the report date only on the first row of each batch and leaves it NA on subsequent rows so the printed report looks tidier. Use <code>fill(date, .direction = &quot;down&quot;)</code> to carry the date forward into the NA rows so every observation knows its report date, then save the result to <code>ex_5_4</code>.</p>

<p><strong>Expected result:</strong></p>

<pre><code>#&gt; # A tibble: 6 x 3
#&gt;   date       item   value
#&gt;   &lt;date&gt;     &lt;chr&gt;  &lt;dbl&gt;
#&gt; 1 2024-07-01 alpha     10
#&gt; 2 2024-07-01 beta      12
#&gt; 3 2024-07-01 gamma     14
#&gt; 4 2024-07-02 alpha     11
#&gt; 5 2024-07-02 beta      13
#&gt; 6 2024-07-02 gamma     15</code></pre>

<p><strong>Difficulty:</strong> Intermediate</p>

<div class="webr-container" data-block-title="Your turn">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Your turn</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">report &lt;- tribble(
  ~date,                  ~item,   ~value,
  as.Date(&quot;2024-07-01&quot;),  &quot;alpha&quot;,  10,
  NA,                     &quot;beta&quot;,   12,
  NA,                     &quot;gamma&quot;,  14,
  as.Date(&quot;2024-07-02&quot;),  &quot;alpha&quot;,  11,
  NA,                     &quot;beta&quot;,   13,
  NA,                     &quot;gamma&quot;,  15
)

ex_5_4 &lt;- # your code here
ex_5_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<details>
<summary>Click to reveal solution</summary>

<div class="webr-container" data-block-title="Solution">
  <div class="webr-code-block">
    <div class="webr-header"><div class="webr-header-left"><span class="webr-header-badge">R</span><span class="webr-header-label">Solution</span></div><div class="webr-header-right"><button type="button" class="webr-copy-btn" aria-label="Copy code" title="Copy code"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run <span class="webr-run-shortcut">Ctrl+Enter</span></button></div></div>
    <div class="webr-editor" data-language="r">ex_5_4 &lt;- fill(report, date, .direction = &quot;down&quot;)
ex_5_4</div>
    <div class="webr-buttons">
      <button class="btn btn-sm btn-primary webr-run-btn" onclick="runWebR(this)">&#9654; Run</button>
      <button class="btn btn-sm btn-default webr-reset-btn" onclick="resetWebR(this)">&#8634; Reset</button>
    </div>
    <pre class="webr-output"></pre>
  </div>
  <div class="webr-plot-output"></div>
</div>

<p><strong>Explanation:</strong> <code>fill()</code> replaces NAs in the columns you name with the nearest non-NA value, defaulting to downward direction. This is the classic move when spreadsheets repeat a header value only at the top of each block. Pass <code>.direction = &quot;up&quot;</code> to back-fill from below, or <code>&quot;downup&quot;</code> to fill in both directions when an NA might sit between two known values. Always pair with <code>group_by()</code> if NAs should only fill within partitions, never across them.</p>

</details>

<h2>What to do next</h2>

<ul>

<li><a href="pivot_longer-pivot_wider-Reshape-Data-in-R.html">pivot_longer and pivot_wider: Reshape Data in R</a> is the parent tutorial covering every option in depth.</li>

<li><a href="dplyr-Exercises-in-R.html">dplyr Exercises in R</a> practices the verbs you chain BEFORE and AFTER a reshape.</li>

<li><a href="tidyverse-Exercises-in-R.html">tidyverse Exercises in R</a> puts reshaping in cross-package pipelines.</li>

<li><a href="Data-Wrangling-Exercises-in-R.html">Data Wrangling Exercises in R</a> covers the broader cleaning workflow these reshapes plug into.</li>

</ul>

{% endraw %}