---
title: Scale Naming Convention
---
flowchart LR
    A["scale_"] --> B["aesthetic_"]
    B --> C["type"]
    A2["scale_"] --> B2["color_"]
    B2 --> C2["brewer()"]
    A3["scale_"] --> B3["x_"]
    B3 --> C3["log10()"]
    A4["scale_"] --> B4["fill_"]
    B4 --> C4["manual()"]
