---
title: ggplot2 Labeling Functions
---
mindmap
  root((Labels &<br/>Annotations))
    labs&lpar;&rpar;
      title
      subtitle
      caption
      axis labels
    geom_text&lpar;&rpar;
      data-driven
      map to aes
    geom_label&lpar;&rpar;
      background box
      label.padding
    ggrepel
      no overlaps
      geom_text_repel
      geom_label_repel
    annotate&lpar;&rpar;
      text at coords
      rectangles
      arrows
      curves
