---
title: pivot_longer() Arguments
---
flowchart LR
    A["cols
which columns
to stack"] --> D["pivot_longer()"]
    B["names_to
new column for
the old names"] --> D
    C["values_to
new column for
the old values"] --> D
    D --> E["Longer
tibble"]
