---
title: R Environments at a Glance
---
mindmap
  root(("R<br/>Environments"))
    Structure
      Frame<br/>of bindings
      Parent<br/>pointer
      Reference<br/>semantics
    Special kinds
      globalenv
      baseenv
      emptyenv
      Package envs
    In action
      Scoping<br/>lookup
      Closures
      Execution<br/>frames
