---
title: The 4 Building Blocks of R Syntax
---
mindmap
  root(("R Syntax"))
    Arithmetic
      "+ - * /"
      "^ %% %/%"
    Assignment
      "x <- 5"
      "naming rules"
    Comments
      "# single line"
      "block comments"
    First Script
      ".R file"
      "run in RStudio"
