---
title: Core R Syntax Elements
---
mindmap
  root((R Syntax))
    Arithmetic
      "+ - * /"
      "^ %% %/%"
    Assignment
      "x &lt;- value"
    Comments
      "# single line"
    Variables
      "valid names"
      "snake_case"
    Scripts
      ".R files"
