---
title: S3 Inheritance Lookup
---
flowchart LR
    A["Call summary(obj)"] --> B{"summary.\ngolden_retriever?"}
    B -->|"No"| C{"summary.\ndog?"}
    C -->|"No"| D{"summary.\nanimal?"}
    D -->|"No"| E{"summary.\ndefault?"}
    B -->|"Yes"| F["Run it"]
    C -->|"Yes"| F
    D -->|"Yes"| F
    E -->|"Yes"| F
    E -->|"No"| G["Error"]
