---
title: S4 Inheritance Example
---
classDiagram
    Shape <|-- Circle
    Shape <|-- Rectangle
    Circle <|-- Ellipse
    class Shape {
        +character color
        +area()
        +describe()
    }
    class Circle {
        +numeric radius
        +area()
    }
    class Rectangle {
        +numeric width
        +numeric height
        +area()
    }
    class Ellipse {
        +numeric semi_minor
        +area()
    }
