---
title: stringr Function Families
---
mindmap
  root((stringr))
    Detect & Filter
      str_detect
      str_subset
      str_count
    Extract & Locate
      str_extract
      str_sub
      str_match
    Replace & Transform
      str_replace
      str_to_upper
      str_to_lower
    Split & Combine
      str_split
      str_c
    Format & Pad
      str_pad
      str_trim
      str_trunc
