"""Per-tool FAQ content used by build.py to inject FAQPage JSON-LD.

Each entry: 3-4 Q&A pairs designed for Google's "People Also Ask",
AI Overviews, and LLM extraction. Questions match real search queries.
Answers are 30-70 words, self-contained, and end with a concrete pointer.

Adding a new tool: add a slug -> list of {q, a} dicts. build.py reads
this file each run and emits a FAQPage JSON-LD block per tool.
"""

FAQS = {
    'ab-test-calculator': [
        {'q': 'When should I use a two-proportion z-test versus a Bayesian beta-binomial for an A/B test?',
         'a': 'Use the two-proportion z-test when stakeholders expect a p-value or your team operates under a fixed alpha. Use the Bayesian beta-binomial when you need a direct probability statement like "B beats A with 94% probability" or want to incorporate a prior. The calculator runs both side by side so you can compare verdicts before deciding which to report.'},
        {'q': 'How do I calculate the sample size needed for an A/B test?',
         'a': 'Enter your baseline conversion rate, the minimum detectable effect (MDE) you care about, and your target power (typically 0.80) and significance level (0.05). The calculator returns the required sample size per arm using the same formula as R\'s pwr.2p.test. For 10% baseline and 1pp MDE at 80% power, you need about 14,750 per arm.'},
        {'q': 'Can I peek at A/B test results before the test ends?',
         'a': 'Not safely with a fixed-horizon test — peeking inflates Type I error. Use the calculator\'s Sequential mode, which applies Pocock alpha-spending so you can take K interim looks while keeping the family-wise error rate at 5%. With 3 looks, the per-peek alpha shrinks to about 0.022.'},
    ],
    'anova-output-interpreter': [
        {'q': 'What is the difference between Type I, Type II, and Type III sum of squares in ANOVA?',
         'a': 'Type I (sequential) tests each term after adjusting for terms entered before it. Type II tests each main effect after the other main effects but ignores interactions. Type III tests each term after every other term including interactions. R\'s base aov() defaults to Type I; use car::Anova() for Type II or III.'},
        {'q': 'How do I interpret an ANOVA table with significant interaction terms?',
         'a': 'When an interaction is significant, the main effects are not interpretable on their own — the effect of one factor depends on the level of the other. Drop straight to the interaction plot or estimated marginal means (emmeans) and report differences within each combination of levels.'},
        {'q': 'When should I use ANOVA versus a t-test or Kruskal-Wallis?',
         'a': 'Use a t-test for two groups, ANOVA for three or more groups with a continuous outcome, and Kruskal-Wallis (non-parametric) when residuals are non-normal or variances are very unequal. ANOVA assumes normality of residuals and homogeneity of variance — check these with diagnostic plots before reporting.'},
    ],
    'bayes-factor-calculator': [
        {'q': 'What does a Bayes Factor of 10 mean?',
         'a': 'A Bayes Factor (BF10) of 10 means the data are 10 times more likely under the alternative hypothesis than under the null. On the Jeffreys scale this is "strong" evidence for the alternative. BF10 between 1 and 3 is anecdotal, 3 to 10 is moderate, above 100 is decisive. Interpret cautiously when priors are weakly justified.'},
        {'q': 'How is a Bayes Factor different from a p-value?',
         'a': 'A p-value tells you how surprising your data would be if the null were true; it cannot quantify evidence FOR the null. A Bayes Factor compares two models directly and can support either side, including "the data favor the null." Use BF when you need to claim no effect, not just fail to reject.'},
        {'q': 'Which prior should I use for a Bayes Factor t-test?',
         'a': 'A Cauchy prior on the standardized effect size with scale 1/sqrt(2) (about 0.707) is the default for the BayesFactor R package and reflects medium-sized effects. Use a wider scale if you expect large effects, narrower if you expect small ones. The calculator shows how BF10 changes as you vary the prior.'},
    ],
    'bayes-theorem-calculator': [
        {'q': 'How do I calculate the probability of disease given a positive test?',
         'a': 'Use Bayes\' theorem: P(disease|positive) = sensitivity × prevalence / (sensitivity × prevalence + (1 - specificity) × (1 - prevalence)). For a 1% prevalence disease with 99% sensitivity and 95% specificity, a positive test still only gives a 17% chance of disease — the base rate dominates.'},
        {'q': 'Why does a 99% accurate test still have a high false positive rate for rare conditions?',
         'a': 'When the disease is rare, the small percentage of false positives across the large healthy population can outnumber true positives. This is the base rate fallacy. The calculator shows the natural-frequency tree (out of 10,000 people, X test positive, of whom Y actually have the disease) so the math becomes intuitive.'},
        {'q': 'What is the difference between sensitivity, specificity, and positive predictive value?',
         'a': 'Sensitivity = P(positive | disease). Specificity = P(negative | no disease). Positive predictive value (PPV) = P(disease | positive) — what the patient actually wants to know. PPV depends on prevalence, sensitivity, and specificity together; high sensitivity alone does not guarantee high PPV.'},
    ],
    'bootstrap-ci-calculator': [
        {'q': 'When should I use a bootstrap confidence interval instead of a t-interval?',
         'a': 'Use a bootstrap CI when the sampling distribution is not normal, the statistic is non-standard (median, ratio, percentile), or the sample is too small for the central limit theorem to kick in. Bootstrap is also the only practical option for many ML metrics like AUC or F1. Skip it when n is very small (under 20) or data has heavy outliers.'},
        {'q': 'What is the difference between percentile, BCa, and basic bootstrap intervals?',
         'a': 'Percentile uses the 2.5th and 97.5th quantiles of bootstrap replicates — simple but biased for skewed statistics. BCa (bias-corrected and accelerated) adjusts for both bias and skew and is the preferred default. Basic bootstrap reflects percentiles around the original estimate. The calculator shows all three so you can compare.'},
        {'q': 'How many bootstrap resamples do I need?',
         'a': 'For confidence intervals, 2,000 resamples is the practical minimum and 10,000 is standard. For p-values via bootstrap hypothesis testing, use at least 10,000. The calculator runs 10,000 by default; results stabilize within ±0.5pp of the true bootstrap distribution.'},
    ],
    'chi-square-calculator': [
        {'q': 'When should I use Chi-square versus Fisher\'s exact test?',
         'a': 'Use chi-square when all expected cell counts are at least 5. Switch to Fisher\'s exact when any expected cell count drops below 5, sample size is small (n < 30), or you have a 2x2 table where the asymptotic approximation is unreliable. Fisher\'s test is also the right choice for case-control studies with rare outcomes.'},
        {'q': 'How do I interpret Cramer\'s V from a chi-square test?',
         'a': 'Cramer\'s V measures the strength of association in a contingency table, ranging from 0 (no association) to 1 (perfect). Rules of thumb: 0.1 = small, 0.3 = medium, 0.5 = large. Unlike the chi-square statistic itself, V does not grow with sample size, so it tells you whether a "significant" result is also practically meaningful.'},
        {'q': 'What does Yates\' continuity correction do?',
         'a': 'Yates\' correction adjusts the chi-square statistic downward by 0.5 in 2x2 tables to compensate for treating discrete counts as continuous. It reduces the false-positive rate but is conservative for moderate samples. R\'s chisq.test applies it by default; set correct=FALSE to disable. Modern practice often skips it in favor of Fisher\'s exact for small samples.'},
    ],
    'confidence-interval-calculator': [
        {'q': 'How do I calculate a confidence interval for a proportion?',
         'a': 'For large samples, use the Wald formula: p +/- z * sqrt(p(1-p)/n). For small samples or extreme proportions, use Wilson or Clopper-Pearson — they give better coverage. The calculator runs all four (Wald, Wilson, Agresti-Coull, exact) so you can compare; Wilson is the recommended default in R\'s prop.test.'},
        {'q': 'What does a 95% confidence interval actually mean?',
         'a': 'A 95% CI means that if you repeated the same study many times, 95% of the resulting intervals would contain the true parameter. It does NOT mean there is a 95% probability the parameter lies in this specific interval — that is a Bayesian credible interval. Use the Bayes Theorem or Bootstrap CI tools when you need probability statements.'},
        {'q': 'When should I use a t-interval versus a z-interval?',
         'a': 'Use the t-interval whenever the population standard deviation is unknown — which is almost always in practice. The z-interval applies only when sigma is known. The two converge as n grows; the difference matters most when n is below 30. R\'s t.test is the practical default.'},
    ],
    'confusion-matrix-interpreter': [
        {'q': 'What is the difference between sensitivity and specificity?',
         'a': 'Sensitivity (recall, true positive rate) is P(predicted positive | actually positive) — how well the model catches positives. Specificity is P(predicted negative | actually negative) — how well it excludes negatives. They trade off as you move the classification threshold. ROC analysis plots them against each other.'},
        {'q': 'When should I use F1 score versus accuracy?',
         'a': 'Use F1 when classes are imbalanced — accuracy can hit 95% on a 95/5 dataset by always predicting the majority class. F1 (the harmonic mean of precision and recall) penalizes that. Use accuracy only when classes are balanced and false positives and false negatives carry similar cost.'},
        {'q': 'What does Matthews correlation coefficient measure?',
         'a': 'MCC is a single-number summary that accounts for all four cells of the confusion matrix and works well even on imbalanced data. It ranges from -1 (perfect disagreement) to +1 (perfect agreement), with 0 being random. MCC is more informative than F1 because F1 ignores true negatives.'},
    ],
    'dag-confounder-picker': [
        {'q': 'What is the difference between a confounder and a collider?',
         'a': 'A confounder causes both the exposure and the outcome — adjust for it to remove bias. A collider is caused by both — adjusting for a collider INTRODUCES bias by opening a non-causal path. The picker uses d-separation to tell you which variables are which, given your DAG.'},
        {'q': 'How do I choose which variables to control for in a regression?',
         'a': 'Draw the DAG, then find a minimal sufficient adjustment set: variables that block all backdoor paths from exposure to outcome without opening collider paths. The picker computes this automatically. Avoid the "throw everything in" approach — it can introduce M-bias by conditioning on colliders.'},
        {'q': 'What is M-bias in causal inference?',
         'a': 'M-bias arises when you condition on a variable that is a common effect of two other variables, opening a non-causal path between them. The DAG looks like an M. Adjusting for the wrong "confounder" (one that is actually a collider) can flip the sign of your estimated effect. The picker flags these explicitly.'},
    ],
    'diagnostic-plot-interpreter': [
        {'q': 'How do I read a residuals vs fitted plot?',
         'a': 'A flat horizontal red line through zero with a roughly even spread indicates the linear and constant-variance assumptions hold. A funnel shape suggests heteroscedasticity (try log transform or weighted least squares). A curve suggests a missing non-linear term. Outlier points sticking out warrant a closer look.'},
        {'q': 'What does a Q-Q plot tell me about my regression?',
         'a': 'A Q-Q plot of residuals against theoretical normal quantiles tests the normality assumption. Points should fall on the diagonal line. Heavy tails (points curving up at both ends) suggest outliers or a heavy-tailed error distribution; an S-shape suggests skew. Mild departures rarely matter when n is large.'},
        {'q': 'When should I worry about Cook\'s distance?',
         'a': 'A Cook\'s distance above 1 is the conventional threshold for concern, though anything above 4/n deserves a look. High values flag observations that change your coefficients substantially when removed. Investigate them — they may be data errors, genuine outliers, or indicate the model is wrong for that part of the predictor space.'},
    ],
    'effect-size-converter': [
        {'q': 'How do I convert Cohen\'s d to eta squared?',
         'a': 'For two-group comparisons: eta squared = d^2 / (d^2 + 4) when groups are balanced. For unequal groups, use the formula in the calculator that accounts for n1 and n2. Going the other way: d = 2 * sqrt(eta^2 / (1 - eta^2)). Cohen\'s d > 0.8 corresponds to eta squared > 0.14, conventionally "large".'},
        {'q': 'What counts as a small, medium, or large effect size?',
         'a': 'Cohen\'s rules of thumb: d = 0.2 small, 0.5 medium, 0.8 large; eta squared = 0.01 / 0.06 / 0.14; correlation r = 0.1 / 0.3 / 0.5. These are field-agnostic defaults — in your domain, "small" may be practically meaningful (medical trials) or trivial (psychology). Always interpret against domain benchmarks.'},
        {'q': 'Why use Hedges\' g instead of Cohen\'s d?',
         'a': 'Cohen\'s d is biased upward in small samples. Hedges\' g multiplies d by a correction factor that approaches 1 as n grows, removing that bias. For n above 50 the difference is negligible; below 20 it matters. The calculator shows both and recommends g when n < 50.'},
    ],
    'equivalence-noninferiority-calculator': [
        {'q': 'What is the difference between equivalence and non-inferiority testing?',
         'a': 'Equivalence tests show two treatments are similar enough — the difference is within +/- delta. Non-inferiority tests show the new treatment is not worse by more than delta in one direction. Both use TOST (two one-sided tests) but with different alternative hypotheses. Choose non-inferiority when the new treatment\'s advantage is on cost or safety, not efficacy.'},
        {'q': 'How do I choose the equivalence margin?',
         'a': 'The margin should be the largest difference that would still be considered clinically or practically irrelevant. For drug trials, regulators often specify it (often 10-20% of the active control effect). Avoid setting it to make a borderline result come out positive — pre-register the margin before unblinding.'},
        {'q': 'Why does TOST use alpha = 0.05 not 0.025?',
         'a': 'TOST runs two one-sided tests, but rejecting both at alpha = 0.05 gives an overall Type I error of 0.05, not 0.10, because the rejection regions don\'t overlap. This is mathematically equivalent to a 90% confidence interval falling entirely within +/- delta. The calculator shows both views.'},
    ],
    'glm-output-interpreter': [
        {'q': 'How do I interpret a logistic regression coefficient?',
         'a': 'On the log-odds scale, a coefficient of beta means a one-unit increase in x changes the log-odds of the outcome by beta. Exponentiate to get the odds ratio: a coefficient of 0.69 = OR of about 2 (doubles the odds). For probability, the change depends on the baseline rate — use predicted probabilities, not coefficients, to communicate effects.'},
        {'q': 'What is a Poisson regression and when do I use it?',
         'a': 'Poisson regression models count outcomes (number of events per unit time or exposure). Use it when the outcome is a non-negative integer with no fixed upper bound — emails per day, hospital visits, accidents. Coefficients are on the log-rate scale; exp(beta) is a rate ratio. Check for overdispersion and consider negative binomial if dispersion > 1.'},
        {'q': 'How do I assess goodness of fit for a GLM?',
         'a': 'Compare residual deviance to a chi-squared distribution with residual degrees of freedom — a much larger deviance suggests poor fit or overdispersion. For logistic regression, also check Hosmer-Lemeshow, calibration plots, and ROC AUC. AIC compares non-nested models. The interpreter highlights all of these from your summary(glm) output.'},
    ],
    'lm-output-interpreter': [
        {'q': 'What does the (Intercept) row mean in summary(lm)?',
         'a': 'The intercept is the predicted outcome when all predictors equal zero — or, for factor predictors, when each is at its reference level. If predictors are not centered, the intercept can be far outside the data range and may not be interpretable on its own. Center continuous predictors when the intercept needs to mean something.'},
        {'q': 'How do I interpret a negative coefficient in linear regression?',
         'a': 'A negative coefficient means the outcome decreases as the predictor increases, holding other variables constant. In R\'s mtcars, "wt -3.9 ***" means each additional 1000 lbs of weight is associated with a 3.9 mpg decrease, after adjusting for other terms in the model. The "after adjusting" qualifier matters — sign can flip when you add or remove confounders.'},
        {'q': 'What is the difference between R-squared and adjusted R-squared?',
         'a': 'R-squared is the proportion of variance explained — it always increases when you add predictors, even useless ones. Adjusted R-squared penalizes for the number of predictors and only goes up when the new term genuinely improves fit. Use adjusted R-squared to compare models with different numbers of predictors.'},
    ],
    'multiple-testing-correction': [
        {'q': 'When should I use Bonferroni versus Benjamini-Hochberg?',
         'a': 'Bonferroni controls family-wise error rate (FWER) — the probability of ANY false positive. Use it when even one false positive is costly (clinical trials, regulatory). BH controls false discovery rate (FDR) — the expected proportion of false positives. Use it for genomics, A/B test screens, and other discovery contexts where some false positives are acceptable.'},
        {'q': 'What\'s the difference between Holm and Bonferroni correction?',
         'a': 'Holm is uniformly more powerful than Bonferroni and controls the same family-wise error rate. It applies the Bonferroni cutoff only to the smallest p-value, then a slightly less strict cutoff to the next, and so on. There is essentially no reason to use Bonferroni instead of Holm when controlling FWER.'},
        {'q': 'How does FDR control work?',
         'a': 'Benjamini-Hochberg (BH) sorts p-values smallest to largest and finds the largest k where p_k <= k * alpha / m. All tests with p-values at or below that threshold are rejected. The expected proportion of false discoveries among the rejections is at most alpha. With m = 1000 tests and alpha = 0.05, you expect about 5% of "discoveries" to be false.'},
    ],
    'nonparametric-test-picker': [
        {'q': 'When should I use Mann-Whitney instead of a t-test?',
         'a': 'Use Mann-Whitney (Wilcoxon rank-sum) when the data are ordinal, heavily skewed, or have outliers that would distort means. It tests whether one distribution stochastically dominates the other. The cost is power — when residuals truly are normal, t-test is more powerful. With n above 30 per group, the difference is small.'},
        {'q': 'What is the Wilcoxon signed-rank test?',
         'a': 'It is the non-parametric counterpart of the paired t-test. Use it when you have paired or matched observations (before/after, twins, matched cases) and the differences are not normally distributed. It tests whether the median of the differences is zero. Sign test is even more robust but loses power.'},
        {'q': 'When should I use Kruskal-Wallis instead of ANOVA?',
         'a': 'Kruskal-Wallis tests whether three or more groups come from the same distribution, using ranks instead of means. Use it when ANOVA assumptions (normality, equal variance) are clearly violated. Follow up significant results with pairwise Wilcoxon tests with multiple-testing correction; R\'s pairwise.wilcox.test does this automatically.'},
    ],
    'normality-test-picker': [
        {'q': 'Which normality test should I use: Shapiro-Wilk or Kolmogorov-Smirnov?',
         'a': 'Use Shapiro-Wilk for n up to about 5000 — it has the highest power for detecting non-normality across most alternatives. KS is very weak unless you specify the mean and SD a priori; the Lilliefors variant fixes this but is still less powerful than Shapiro-Wilk. Anderson-Darling is competitive and works well in the tails.'},
        {'q': 'Why does my data fail a normality test even though it looks normal?',
         'a': 'With large n (above ~5000), normality tests become so sensitive they reject for trivial deviations that don\'t affect inference. The reverse problem applies for small n: tests can\'t distinguish normal from clearly non-normal. Always pair the test with a Q-Q plot and consider whether the deviation matters for your analysis.'},
        {'q': 'Do I need to test for normality before running a t-test?',
         'a': 'For n above 30 per group, the central limit theorem makes t-test robust to mild non-normality of the underlying data. Test the residuals, not the raw data. If you see heavy skew, outliers, or a clear non-normal shape, switch to Mann-Whitney or use a transformation; otherwise t-test is usually fine.'},
    ],
    'outlier-detection-calculator': [
        {'q': 'What is the Tukey 1.5 IQR rule for outliers?',
         'a': 'Any observation more than 1.5 times the interquartile range below the first quartile or above the third quartile is flagged as an outlier. It is the rule behind the whiskers on a boxplot. Use 3 * IQR for "extreme" outliers. This rule is non-parametric and works on any continuous distribution.'},
        {'q': 'When should I use Grubbs\' test versus Tukey\'s IQR rule?',
         'a': 'Grubbs\' test assumes a normal distribution and tests one outlier at a time with a formal p-value — use it when you need a hypothesis test result. Tukey\'s rule is non-parametric and flags multiple outliers at once but does not give a p-value. For exploratory work, start with Tukey; for reporting, use Grubbs.'},
        {'q': 'Should I always remove outliers before fitting a model?',
         'a': 'No. Remove only data-entry errors and impossible values. Genuine extreme observations may carry the most information. Use robust regression (rlm), bootstrapping, or trimming if outliers distort your fit. Always report what you removed, why, and how the analysis changes if you keep them.'},
    ],
    'power-analysis': [
        {'q': 'How do I calculate the power of a t-test?',
         'a': 'Power = 1 - beta, the probability of detecting a true effect. For a two-sample t-test, power depends on effect size (Cohen\'s d), sample size per group, and alpha. A standard target is 0.80. The calculator inverts the relationship: given any three of {n, d, alpha, power}, it solves for the fourth — same as R\'s pwr::pwr.t.test.'},
        {'q': 'What is the minimum detectable effect (MDE)?',
         'a': 'MDE is the smallest true effect size your study would detect with the desired power and alpha at a given sample size. If your MDE is 0.5 SD but you only care about effects above 0.2 SD, your study is underpowered and a non-significant result is uninformative. Always compute MDE before running an experiment.'},
        {'q': 'Why does my study need so many subjects to detect a small effect?',
         'a': 'Required sample size grows with the inverse square of the effect size. Halving the effect quadruples n. To detect Cohen\'s d = 0.2 (small) at 80% power needs about 200 per group; d = 0.5 (medium) needs 64; d = 0.8 (large) needs only 26. Run the math first to confirm the study is feasible.'},
    ],
    'reprex-builder': [
        {'q': 'What makes a good minimal reproducible example (reprex)?',
         'a': 'A reprex must run on a fresh R session with no external data or packages beyond what is in the snippet. It should reproduce the bug or question with the smallest amount of code possible — ideally under 30 lines. Use built-in datasets (mtcars, iris) or generate fake data with set.seed(). The builder validates these constraints automatically.'},
        {'q': 'Why does my Stack Overflow R question get downvoted?',
         'a': 'The most common reasons: pasting a screenshot instead of code, requiring a private CSV no one can access, omitting library() calls so packages are unclear, posting full project code instead of a minimal example, and not including the exact error message. The reprex builder catches all of these before you post.'},
        {'q': 'What is the reprex package and how does it work?',
         'a': 'reprex is an R package that runs your code in a fresh session, captures input and output together, and formats it as Markdown ready to paste into GitHub or Stack Overflow. The builder mimics this workflow in the browser — paste your code, get back a copy-paste-ready snippet with sessionInfo() included.'},
    ],
    'roc-auc-calculator': [
        {'q': 'What does AUC actually measure?',
         'a': 'AUC (area under the ROC curve) is the probability that a randomly chosen positive example has a higher predicted score than a randomly chosen negative example. AUC = 0.5 is random; 1.0 is perfect; 0.7-0.8 is fair, 0.8-0.9 is good. AUC is threshold-independent — it summarizes performance across every possible threshold.'},
        {'q': 'How do I choose a classification threshold from an ROC curve?',
         'a': 'Pick the threshold that matches your cost function. Equal-cost errors: use Youden\'s J (max sensitivity + specificity - 1). Asymmetric costs: shift toward fewer false negatives (cancer screening) or fewer false positives (spam filter). The calculator shows the cost-weighted optimum threshold for any false-positive vs false-negative cost ratio.'},
        {'q': 'When does a high AUC not mean a good classifier?',
         'a': 'AUC can be misleading on imbalanced data — a model can score well by ranking but still misclassify the minority class at any usable threshold. Look at precision-recall AUC instead. Also, AUC ignores calibration: two models with the same AUC may give very different probability estimates.'},
    ],
    'survival-power-calculator': [
        {'q': 'How do I calculate sample size for a survival analysis?',
         'a': 'Sample size depends on the number of EVENTS, not subjects. The calculator first solves for required events using the log-rank formula given hazard ratio and power, then divides by the expected event rate over the study period to get total enrollment. Schoenfeld\'s formula is the standard.'},
        {'q': 'What is the log-rank test and when is it appropriate?',
         'a': 'The log-rank test compares two or more survival curves under the proportional hazards assumption. Use it as the primary analysis in randomized trials with time-to-event endpoints. If hazards cross or the proportional assumption fails, switch to a weighted log-rank, restricted mean survival time, or accelerated failure time model.'},
        {'q': 'How do I interpret a hazard ratio?',
         'a': 'A hazard ratio of 0.7 means the instantaneous risk in the treatment group is 30% lower than in the control group at any time point, assuming proportional hazards. HR is not the same as risk ratio — it compounds over time. For a 5-year trial with HR = 0.7, the absolute survival difference depends on the baseline hazard.'},
    ],
    't-test-calculator': [
        {'q': 'When should I use Welch\'s t-test instead of Student\'s t-test?',
         'a': 'Welch\'s t-test does not assume equal variances and is the recommended default in R (it is what t.test() uses unless var.equal=TRUE). Student\'s pooled t-test is slightly more powerful when variances really are equal, but has worse Type I control when they are not. Pre-test for equal variance is itself a power-eating multiple comparison — just use Welch.'},
        {'q': 'How do I interpret Cohen\'s d from a t-test?',
         'a': 'Cohen\'s d is the standardized mean difference: (mean1 - mean2) / pooled SD. d = 0.2 is small, 0.5 medium, 0.8 large. The calculator shows d alongside the p-value because a tiny effect (d = 0.05) can still be highly significant with large samples — and a meaningful effect (d = 0.6) can be non-significant with small samples.'},
        {'q': 'When should I use a paired t-test instead of an independent t-test?',
         'a': 'Use paired t-test when each observation in one group has a natural counterpart in the other — same subject before/after, twins, matched cases. Pairing removes between-subject variance and dramatically increases power. Using independent t-test on paired data wastes the pairing information and inflates the standard error.'},
    ],
    'ts-stationarity-calculator': [
        {'q': 'How do I test if a time series is stationary?',
         'a': 'Use the ADF test (null: non-stationary) and KPSS test (null: stationary). Run both — agreement strengthens the conclusion. ADF rejects + KPSS does not reject = stationary. ADF does not reject + KPSS rejects = non-stationary. Disagreement suggests trend-stationarity (try detrending) or a near-unit-root process.'},
        {'q': 'How many times should I difference a time series for ARIMA?',
         'a': 'Difference until ADF rejects non-stationarity (usually 0, 1, or 2 times — d in ARIMA(p,d,q)). Over-differencing introduces moving-average components and inflates variance. The calculator runs ADF after each differencing and recommends the smallest d that achieves stationarity.'},
        {'q': 'What is the difference between an ADF test and a Phillips-Perron test?',
         'a': 'Both test for unit roots. ADF assumes the residuals are i.i.d. and uses augmented lags to absorb autocorrelation. Phillips-Perron is non-parametric in the autocorrelation correction (uses Newey-West HAC). PP can be more robust to heteroscedasticity but is also more prone to size distortion in small samples. ADF is the standard default.'},
    ],
    'type-i-ii-error-visualizer': [
        {'q': 'What is the difference between Type I and Type II error?',
         'a': 'Type I error (alpha) is rejecting a true null hypothesis — a false positive. Type II error (beta) is failing to reject a false null — a false negative. Power is 1 - beta. They trade off: lowering alpha (stricter test) increases beta (lower power). The visualizer shows both distributions and how they shift as you change alpha, n, or effect size.'},
        {'q': 'How does sample size affect Type II error?',
         'a': 'Larger n shrinks the standard error of the test statistic, separating the null and alternative distributions and reducing the overlap region. Type II error falls as n grows. Doubling n roughly halves beta when other parameters are fixed. The visualizer makes this explicit — drag the n slider and watch beta drop.'},
        {'q': 'Why is alpha conventionally set to 0.05?',
         'a': 'It is a historical convention from R.A. Fisher, not a theoretical optimum. Choose alpha based on the cost of a false positive in your domain: 0.001 for high-stakes drug trials, 0.05 for most science, 0.1 for exploratory or pilot work. Pre-register the choice; don\'t shop for an alpha that flatters your result.'},
    ],
    'vif-interpreter': [
        {'q': 'What is a Variance Inflation Factor (VIF)?',
         'a': 'VIF measures how much a predictor\'s standard error is inflated due to its correlation with other predictors. VIF = 1 means no collinearity; VIF > 5 is concerning; VIF > 10 is severe. The square root of VIF tells you by what factor the standard error is bigger than it would be without collinearity.'},
        {'q': 'How do I fix high multicollinearity?',
         'a': 'Options in order of preference: (1) drop redundant predictors, (2) combine correlated predictors via PCA or factor scores, (3) regularize with ridge regression, (4) center continuous predictors and their interaction terms (this often resolves "structural" collinearity without losing information).'},
        {'q': 'Does multicollinearity bias my coefficients?',
         'a': 'No — coefficient estimates remain unbiased. What inflates is their variance, making individual coefficients statistically insignificant even when the overall model fits well. Predicted values are unaffected. Multicollinearity is only a problem when you need to interpret individual coefficients or test their significance.'},
    ],
    'z-score-percentile': [
        {'q': 'How do I convert a z-score to a percentile?',
         'a': 'A z-score of z corresponds to the cumulative probability under the standard normal: percentile = pnorm(z). z = 0 is the 50th percentile, z = 1.0 is the 84th, z = 1.96 is the 97.5th. The calculator does the conversion both ways and shows the area under the normal curve for any z-score, percentile, or raw value with mean and SD.'},
        {'q': 'What is the difference between a z-score and a t-score?',
         'a': 'A z-score uses the population standard deviation; a t-score uses the sample standard deviation. The two are nearly identical for n above 30 but diverge for small samples. Use z for IQ scales, percentile rankings, and quality-control charts; use t for hypothesis tests when sigma is unknown.'},
        {'q': 'Are SAT and IQ scores really normally distributed?',
         'a': 'They are designed to be. SAT scores are scaled so the population mean is 1000 and SD is 200 across all takers; IQ tests target mean 100 and SD 15. The underlying ability is approximately normal in the general population, so the resulting score follows the same shape. Both are expressed as z-scores in disguise.'},
    ],
}

assert len(FAQS) == 27, f"Expected 27 tools, got {len(FAQS)}"
